### ISSUE TITLE
RDP Config reports version 1.5 after installing higher version

### ISSUE THREAD

**Issue by cowwoc** [stascorp/rdpwrap#100]
Repro steps:

1. Install version 1.6
2. Run RDP Config
3. Notice that the GUI reports RDPWrap version 1.5

**Comment by borebaug** [comment]
I saw the same thing.  Running the "update.bat" upgrades from v1.5 to 1.6.

**Comment by cheitzig** [comment]
Seems to still be an issue. Even after running update.bat, RDPCheck.exe still indicates v1.5. Also, choosing properties on rdpwrap.dll indicates version 1.5.0.0

**Comment by binarymaster** [comment]
This is not an issue, internal library version is 1.5, it doesn't need to recompile since all important settings are stored in INI file.

1.6 is the version of the final release package.

**Comment by binarymaster** [comment]
Added to FAQ in README.

This won't be fixed for now.
