### ISSUE TITLE
Listener state: Not listening [not supported]

### ISSUE THREAD

**Issue by faizanjaffer** [stascorp/rdpwrap#1000]
Can someone provide the ini configuration for
Windows Server 2016: Ver. 10.0.14393.3503

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/4216354/termsrv.zip)

Attached is termsrv.dll

**Comment by asmtron** [comment]
https://github.com/stascorp/rdpwrap/pull/859 with 10.0.14393.3503 support

**Comment by faizanjaffer** [comment]
Thanks
