### ISSUE TITLE
Windows 10.0.18362.657 x64 - Not listening, but Fully supported

### ISSUE THREAD

**Issue by harverto** [stascorp/rdpwrap#1002]
Hi, everyone
I've been using this tools years and years, but since a couple of days, system updated and service went down, I updated ini file and arrived this point 
![incidencia amate](https://user-images.githubusercontent.com/61226360/74816497-93e8d500-52fb-11ea-9f0c-9c5f3110faf5.png)
And there is no way, I've tried rebooting, reinstalling, etc... 
The only thing that left is to substitute system32 files termsrv.dll and rfxvmt.dll, but I'd like to know your opinion
Thank you!

**Comment by sinadarvi** [comment]
but in my case is just opposite, my listener state is Listening but not supported!

**Comment by harverto** [comment]
> but in my case is just opposite, my listener state is Listening but not supported!

Try on #988

**Comment by Harish4664** [comment]
![Capture](https://user-images.githubusercontent.com/61315186/75029853-e88d7b00-54c8-11ea-81c8-0c3d4fd42873.PNG)


whats is solution for this, i tried all possible way.

**Comment by harverto** [comment]
Finally, Remote Desktop Service was misconfigurated !!! It wasn't granted for Network Service, as it should be at Session Tab.
You can setup this at Services Console, services.msc.

Thank you all
