### ISSUE TITLE
Windows 10 version 10.0.18363.657 Now Working 23.02.2020

### ISSUE THREAD

**Issue by Smartaccounts** [stascorp/rdpwrap#1006]
Big thanks to @ development team @binarymaster and @stvkodra.
I have success created 3 users access simultaneously (like virtual machines) on Windows 10 Pro version 18363.657.

These are the files with working version of rdpwrap.ini. Mcafee has always removed RDPConf every single time. I have setup exclude this file. User may need to temporary disable Mcafee, download and unzip the file. Then, setup RDPConf excluded files in Mcafee. 

step 1, disable Mcafee or similar products 
step 2, download unzip the file
step 3, run install
step 4, stop Remote Desktop Service, type in windows search bar administrative tools>Services>right click Remote Desktop Service Stop and Yes.
step 5, replace attached rdpwrap.ini in Program Files>RDP Wrapper>rdpwrap
step 6, reboot computer
step 7, run RDPConf, it shows all green 

Done!

Next, user may create multiple-users right click This PC>Manage>Local Users and Groups>setup a new user with user name, password and description, choose prefer password method>Create

After, add Remote Desktop Users into Member of group tap click Add...>Advanced...>Find Now>Remote Desktop Users>OK

Final, find out windows10 pro Machine IP, click wireless icon>Properties>IPv4 address xxx.xxx.x.xx

Finish. User may remote access in another PC by using above IP address, Username, Password

[RDPWrap-v1.6.2-Win10pro 18363.657.zip](https://github.com/stascorp/rdpwrap/files/4240613/RDPWrap-v1.6.2-Win10pro.18363.657.zip)

**Comment by bezik46** [comment]
Definitely **does** work!
Using it daily!

**Comment by ghi820** [comment]
> 
> 
> Definitely does not work!

Calling BS on that.. applied it today and worked with 5 RDP and one console user simultaneously (just testing, didn't go higher because no more friends for "real human testing", but still...)

**Comment by JeffPerando** [comment]
Doesn't work for me either

**Comment by jereeth** [comment]
It worked for me, Tnx

**Comment by fafan999** [comment]
Awesome! Worked for me, 2 computers and an android device at the same time! Don't skip the step 6, reboot your computer.

**Comment by luvsicz** [comment]
check this!https://github.com/stascorp/rdpwrap/issues/1008#issuecomment-591017557

**Comment by Smartaccounts** [comment]
I have realized Mcafee keeps removing RDPconfig.exe file. It requires to put it into excluded files under the Real-Time Scanning. It needs to very specified location, otherwise, the exe file will be removed.

Meanwhile, it maybe a small bug either in my computer or in Mcafee. The port 3389 may not be able to forward in Mcafee (even it shows a tick next to Remote Desktop/Remove Assistance/Terminal Server, Mcafee doesn't apply the forward rule). I tried many times edit it, it stuck there was not able to save forward rule.

Mcfee is my favorite tool. I don't want to loss it. I changed Port number in Registry and created new inbound rule with same port in windows firewall, as well as created a new rule in Macfee under the Firewall>Ports and Systems Service with same port. Then, created new port forward rule in router and static IP (P.S, turn off Firewall completely, still doesn't work.)

It is now working fine with No-ip, the computer is accessible over internet by multiple users.

This is a great tool, Thanks to @binarymaster @stvkodra @all etc

**Comment by hzx505** [comment]
[10.0.18362.657-SLInit]
bInitialized.x86 =D577C
bServerSku.x86 =D5780
lMaxUserSessions.x86 =D5784
bAppServerAllowed.x86 =D578C
bRemoteConnAllowed.x86=D5790
bMultimonAllowed.x86 =D5794
ulMaxDebugSessions.x86=D5798
bFUSEnabled.x86 =D579C
bInitialized.x64 =F6A8C
bServerSku.x64 =F6A90
lMaxUserSessions.x64 =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64 =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64 =F6AAC

[10.0.18362.657]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B7D06
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FB5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=50535
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=50269
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=5A77A
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

**Comment by Neoministein** [comment]
Thank you very much :)
It works great!

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/983
