### ISSUE TITLE
kb3139914 broke multiple RDP sessions

### ISSUE THREAD

**Issue by gits68** [stascorp/rdpwrap#101]
Hi,

kb3139914 prevent rdpwrap from working, uninstalling kb3139914 make it work rigth again.

use the following command to uninstall it : 

**wusa.exe /uninstall /kb:3139914 /quiet /norestart**

you may also use the following vb script to automatically hide the KB : 

`
Dim hideupdates(1)

hideupdates(0) = "KB3139914"

set updateSession = createObject("Microsoft.Update.Session")
set updateSearcher = updateSession.CreateupdateSearcher()

Set searchResult = updateSearcher.Search("IsInstalled=0 and Type='Software'")

For i = 0 To searchResult.Updates.Count-1
set update = searchResult.Updates.Item(i)
For j = LBound(hideupdates) To UBound(hideupdates)
'MsgBox hideupdates(j)
if instr(1, update.Title, hideupdates(j), vbTextCompare) = 0 then
  'Wscript.echo "No match found for " & hideupdates(j)
else
Wscript.echo "Hiding updates..." & hideupdates(j)
update.IsHidden = True
end if
Next
Next
`

**Comment by fge1951** [comment]
English
For three days does not let me connect: Always indicates access denied. I guess it will be for some updating Windows 10. Les accompanied files.

![2016-03-15 23_43_50-](https://cloud.githubusercontent.com/assets/17862928/13796634/318b52c0-eb08-11e5-9524-9cf923e0d55a.png)
![2016-03-15 23_44_31-local rdp checker](https://cloud.githubusercontent.com/assets/17862928/13796635/31973f36-eb08-11e5-94e0-350b545dea1a.png)

Spanish
Desde hace tres días no me deja conectar: Siempre indica acceso denegado. Supongo será por alguna actualización de Windows 10. Les acompaño archivos.

**Comment by rufuswilson** [comment]
Hi,

I also have this problem but I can't see the problematic update "KB3139914". I am on windows 10.

Thanks,
Cédric

**Comment by binarymaster** [comment]
There is a problem with access rights somewhere, similar to https://github.com/stascorp/rdpwrap/issues/215#issuecomment-285807228.

The issue can be theoretically solved by using Sysinternals' FileMon program that will log file accesses. But since this thread is not active anymore, I'm closing it.

**Comment by lethallybad** [comment]
How do I find what needs access using Process Monitor? I filter for RDPCheck.exe and RDPConf.exe but nothing really comes up when I reopen RDPCheck and try logging in again.
