### ISSUE TITLE
Listener not listening and not supported for Windows build 18363.693

### ISSUE THREAD

**Issue by noonejr** [stascorp/rdpwrap#1018]
![image](https://user-images.githubusercontent.com/31583515/75841894-e0044100-5df4-11ea-9114-e931f2c0cfca.png)

**Comment by sk-lau** [comment]
you need apply #988

**Comment by noonejr** [comment]
Thanks, it worked

**Comment by dcbasso** [comment]
ON CMD show build ".693" but in the RDP config show ".165".
How can I fix it?
