### ISSUE TITLE
No binaries in distribution

### ISSUE THREAD

**Issue by DaveCausey** [stascorp/rdpwrap#102]
The binaries mentioned in the installation instructions don't appear to be present in any of the release packages.

**Comment by binarymaster** [comment]
![image](https://cloud.githubusercontent.com/assets/578406/13847246/4a75d03e-ec5d-11e5-9fe0-c710df8679e0.png)

What?

**Comment by DaveCausey** [comment]
I followed a stale (not broken) link to 
https://github.com/binarymaster/rdpwrap/releases from 
http://woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/.

I reported it to the blog owner.

Thanks.

**Comment by binarymaster** [comment]
Oh, alright. Thanks!

**Comment by cuninghamd** [comment]
The binaries mentioned in the installation instructions still don't appear to be present in any of the release packages. will they reappear at any time?

**Comment by justanothernetizen** [comment]
Hi,

Took me a few minutes to find it.. It is under the "releases" tab. Took me a few mins to find it.

**Comment by cuninghamd** [comment]
Fabulous - many thanks - surprisingly hard to spot when you don't know what you are looking for. Many many thanks. downloaded & works a treat.
Cheers.

**Comment by fvpDev** [comment]
Can't find the binaries either

**Comment by neuralx** [comment]
They are [here](https://github.com/stascorp/rdpwrap/releases)

**Comment by fvpDev** [comment]
Weird...for some reason I was looking under the "releases" tab/button and github was displaying as if the "tags" tab/button was selected. Thank you much for the direct link

**Comment by thedingwing** [comment]
Release 1.6 doesn't have support for the latest Windows 10 TH2 Release Terminal Services 10.0.10586.0. Can we get updated binaries?

**Comment by binarymaster** [comment]
Added to FAQ in README.
