### ISSUE TITLE
Listener state: Not listening [not supported]

### ISSUE THREAD

**Issue by KibSquib48** [stascorp/rdpwrap#1022]
I'm on the latest Windows 10 update (1909) and I just installed rdpwrap, but it just says Listener State: Not listening [not supported] in rdpconf.exe and rdpcheck.exe doesn't even work

**Comment by affinityv** [comment]
Use RDPConf.exe to see the actual required version.  You will likely find it as 10.0.18362.657 at this time.... you need 3rd party INI file as the update of the project will not give you an INI file that will work with many current day setups.
You can likely use [my ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file, then do `RDPWInst -r` in an elevated cmd session to restart RDP WRapper related service.

**Comment by 700nader007** [comment]
![RDP2020](https://user-images.githubusercontent.com/62025576/76332195-1fed8b80-6301-11ea-8ea8-8502dc98885e.jpg)
all green and working but  only one contention any way to unlock more than one  
Windows 10 update (1909)

**Comment by affinityv** [comment]
This is for group policy changes to enable multiple connections; it might not be exactly what you want, but it should be enough to guide you.
[https://www.hostwinds.com/guide/allow-multiple-remote-desktop-rdp-connections-in-windows-server-2012-2016/](https://www.hostwinds.com/guide/allow-multiple-remote-desktop-rdp-connections-in-windows-server-2012-2016/)

**Comment by affinityv** [comment]
Hint, if you don't have group policies, use `gpedit.msc` in an elevated cmd window.

**Comment by affinityv** [comment]
https://community.dynamics.com/365/b/dynamics365enterprisecloudfronts/posts/setup-simultaneous-remote-login-for-multiple-users

**Comment by 700nader007** [comment]
try this Working 100%
https://github.com/stascorp/rdpwrap/issues/988#issuecomment-597151413

**Comment by Myron-S** [comment]
INI file with definitions for Win Ver 1909 had worked for me too.

**Comment by Gringos78** [comment]
Windows 10 version 18363.720 This worked for me:

> Use RDPConf.exe to see the actual required version. You will likely find it as 10.0.18362.657 at this time.... you need 3rd party INI file as the update of the project will not give you an INI file that will work with many current day setups.
> You can likely use [my ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file, then do `RDPWInst -r` in an elevated cmd session to restart RDP WRapper related service.

**Comment by MeowKim** [comment]
> Use RDPConf.exe to see the actual required version. You will likely find it as 10.0.18362.657 at this time.... you need 3rd party INI file as the update of the project will not give you an INI file that will work with many current day setups.
> You can likely use [my ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file, then do `RDPWInst -r` in an elevated cmd session to restart RDP WRapper related service.

Works great!
Windows 10 Home
Version 1909 Build 18363.720

**Comment by jamco88** [comment]
> 
> 
> Use RDPConf.exe to see the actual required version. You will likely find it as 10.0.18362.657 at this time.... you need 3rd party INI file as the update of the project will not give you an INI file that will work with many current day setups.
> You can likely use [my ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file, then do `RDPWInst -r` in an elevated cmd session to restart RDP WRapper related service.

How do you use the ini file?

**Comment by Gringos78** [comment]
> > Use RDPConf.exe to see the actual required version. You will likely find it as 10.0.18362.657 at this time.... you need 3rd party INI file as the update of the project will not give you an INI file that will work with many current day setups.
> > You can likely use [my ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file, then do `RDPWInst -r` in an elevated cmd session to restart RDP WRapper related service.
> 
> How do you use the ini file?

Replace the rdpwrap.ini file in c:\Program Files\RDP Wrapper with the one provided. And then restart as mentioned above.

**Comment by fnxit** [comment]
> Use RDPConf.exe to see the actual required version. You will likely find it as 10.0.18362.657 at this time.... you need 3rd party INI file as the update of the project will not give you an INI file that will work with many current day setups.
> You can likely use [my ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file, then do `RDPWInst -r` in an elevated cmd session to restart RDP WRapper related service.

Hi, it works. Thank you!
But any ideas how to get back option to drag and drop file on RDP? Before Windows update it worked, but now i cant do it.

**Comment by affinityv** [comment]
This is a great way to update, you can add my [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file in the autoupdate.bat file.  You can even set a scheduled task for updates.
https://github.com/stascorp/rdpwrap/issues/860

**Comment by rmacnair** [comment]
@affinityv you frikking gem.... battling for almost a day to get this working again. Updated with your ini and all well!  Thanks so much.

**Comment by rabbity417** [comment]
> > Use RDPConf.exe to see the actual required version. You will likely find it as 10.0.18362.657 at this time.... you need 3rd party INI file as the update of the project will not give you an INI file that will work with many current day setups.
> > You can likely use [my ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file, then do `RDPWInst -r` in an elevated cmd session to restart RDP WRapper related service.
> 
> Works great!
> Windows 10 Home
> Version 1909 Build 18363.720

Hi.
My PC does not working Windows 10 Home, 1909 build 18363.720
"Listener state" is "Not listening"
How did you do on your PC?
I did change this ini file but it's same.
plz help me.

**Comment by recv2383-home** [comment]
The new INI worked like a charm on Windows home 1909 build

**Comment by jhonny003** [comment]
buenas tardes amigos! Les cuento que en varios equipos funcionando con Windows 10 y las recientes actualizaciones a la fecha, me dejaron de funcionar las conexiones remotas. Tengo 1 caso puntual que no logro resolver en donde me queda todo así:

![imagen](https://user-images.githubusercontent.com/60977204/80526013-82115700-8968-11ea-8486-9438fc290f41.png)

Tengo conexión por teamviewer también a estos equipos por lo que puedo conectar y controlar pero por remoto, se cayeron y no logro revertir el problema. A alguno le sucedió? En estos momentos es medio crítico tener a varios usuarios sin poder conectar. Apelo a su gran experiencia para ver qué puede ser lo que sucede.

Aguardo sus comentarios y me mantengo online. Desde ya, muchas gracias!

**Comment by magedib** [comment]
thanks affinityv
https://drive.google.com/file/d/1iFuEsYb8SxaYjqwSOEAbYXsazyJXK4xk/view?usp=sharing

**Comment by affinityv** [comment]
> thanks affinityv
> https://drive.google.com/file/d/1iFuEsYb8SxaYjqwSOEAbYXsazyJXK4xk/view?usp=sharing

Okay, that was my latest [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/0beacd3df2625d22df8aa98ce2d3a34292e5832d/rdpwrap.ini) file from back then... 16th Jan, 2021.

This is the current newest [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file.

**Comment by mawieder** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6481223/termsrv.zip)
Terminal Services version: 10.0.19041.964 not supported

**Comment by mawieder** [comment]
> Replace the rdpwrap.ini file in c:\Program Files\RDP Wrapper with the one provided. And then restart as mentioned above.

![image](https://user-images.githubusercontent.com/84206619/118333345-d5226180-b50b-11eb-9c98-8d6d5082ddba.png)

Running install.bat (as admin) does not create the above folder in C:\...

**Comment by affinityv** [comment]
> > Replace the rdpwrap.ini file in c:\Program Files\RDP Wrapper with the one provided. And then restart as mentioned above.
> 
> ![image](https://user-images.githubusercontent.com/84206619/118333345-d5226180-b50b-11eb-9c98-8d6d5082ddba.png)
> 
> Running install.bat (as admin) does not create the above folder in C:...

If you don't have that folder, then the install didn't work and/or your AV including Windows Defender is interfering.

Once it is installed correctly, then you need to update the INI after install and then run `RDPWInst -r` to activate the new INI that does NOT come form the original project itself.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/983
