### ISSUE TITLE
Version not updating

### ISSUE THREAD

**Issue by fipekui** [stascorp/rdpwrap#1024]
I added the 10.0.18362.657 lines in my rdpwrap.ini but the version shows 10.0.18362.53 in the wrapper configuration. Any ideas why the version wont update?

**Comment by affinityv** [comment]
Have you got Windows updates to apply to get a later version.  The version that shows in rdpconf is the one of the termsrv.dll .... not what it finds in the INI file.

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/983
