### ISSUE TITLE
Not listening [fully supported] 10.0.18362.657

### ISSUE THREAD

**Issue by f300** [stascorp/rdpwrap#1025]
Since the Feb/March Windows Updates I can't get RDPWrap to work.

![Capture](https://user-images.githubusercontent.com/41181259/76636186-88767b80-6540-11ea-8a35-dd1625d7db12.PNG)

I've uninstalled, rebooted, reinstalled, rebooted, etc multiple times. I'm using the ini from https://github.com/stascorp/rdpwrap/issues/1022#issuecomment-596437997 on Windows 10 Home 64bit

Any ideas?
Thanks!

**Comment by affinityv** [comment]
Can you do normal RDP without RDP Wrapper?  If not, perhaps an AV has taken out the RDP Windows registry components.  I have a couple of reg files in my repo, but I'm not sure if Win 10 Home is covered by the Win 10 Pro one.

**Comment by f300** [comment]
> Can you do normal RDP without RDP Wrapper? If not, perhaps an AV has taken out the RDP Windows registry components. I have a couple of reg files in my repo, but I'm not sure if Win 10 Home is covered by the Win 10 Pro one.

Thanks for your reply! Ofc Home can't act as an RDP Server without RDP Wrapper, so I guess you mean Remote Assistance? That works fine. No AV apart from Windows Defender.

However, I have another PC here with exactly the same Windows and termsrv.dll version as the problem PC, but a much fresher Windows install. I've not tried RDP Wrapper on it until just now, but it works fine.

I've exported and compared the registry entries under Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService between the two systems and they are the same. 

So, something has become misconfigured or corrupted on the problem system, as it should be working, but I have no idea where to look. SFC /SCANNOW finds nothing wrong.

**Comment by affinityv** [comment]
Windows Defender can stop rdp wrapper, make sure you have exclusions to protect it.

**Comment by f300** [comment]
I've added exclusions for the RDP Wrapper directory, rdpwrap.dll, RDPWInst.exe, etc and uninstalled / reinstalled - No change, still not listening.

**Comment by affinityv** [comment]
Whenever you do a reinstall, make sure you replace the ini file with one that supports your termsrv.dll version (shown in rdpconf).  Then restart RDP Wrapper `rdpwinst.exe -r`

**Comment by kouwei32** [comment]
Same issue on 10.0.18362.657, using updated alt INI, and restarted the wrapper via -r. Fully supported but not listening. Notably, restart logs had "StartService Error (Code 1056)", but config says that the service is running

**Comment by Dashu-Xu** [comment]
> Same issue on 10.0.18362.657, using updated alt INI, and restarted the wrapper via -r. Fully supported but not listening. Notably, restart logs had "StartService Error (Code 1056)", but config says that the service is running

have you solve the problem yet? I got the same problem but can you tell me where i can find the "restart logs", i want to check the service state as well... thx.

**Comment by kouwei32** [comment]
It is from the output of the command prompt when running the -r parameter. Not sure if this helps

**Comment by CaspianCanuck** [comment]
I am seeing the same problem as @kouwei32, i.e. **StartService Error (Code 1056)** when I run `rdpwinst.exe -r`

**Comment by CaspianCanuck** [comment]
Using the latest INI file linked from **affinityv**'s answer in issue #1022 fixed it for me.

**Comment by KevinH404** [comment]
> Using the latest INI file linked from **affinityv**'s answer in issue #1022 fixed it for me.

This fixed for me.

**Comment by f300** [comment]
> Using the latest INI file linked from **affinityv**'s answer in issue #1022 fixed it for me.

That's the ini I am already using.

**Comment by Zykov-Alexey** [comment]
thanks, #issue 1022 fixed

**Comment by jamco88** [comment]
> 
> 
> Using the latest INI file linked from **affinityv**'s answer in issue #1022 fixed it for me.

Where do you put the ini file?

**Comment by affinityv** [comment]
@jamco88 https://github.com/stascorp/rdpwrap/issues/1035#issuecomment-604501183

**Comment by richw100** [comment]
If this is the same problem that I have had, I think it might be because you have inadvertently removed read access to the NETWORK SERVICE user to the .ini file when copying it across.

I'd suggest reinstalling, then instead of copying the new .ini file over, edit the one in C:\Program Files\RDP Wrapper with notepad running as Administrator , and copy the new contents across.

At the same time, I'd recommend giving "NETWORK SERVICE" write and modify rights on the RDP Wrapper folder, and comment out the ";LogFile=\rdpwrap.txt" line in the .ini file. This should force RDPWrap to write it's logfile into the RDP Wrapper folder, so you should be able to trace it working.

The logfile should contain some lines saying it is patching in between the "freezing" and "resuming" threads, as below. If you see these two lines together, it indicates that RDPWrap has failed to read the .ini file, so check permissions again.

Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...

**Comment by richw100** [comment]
> At the same time, I'd recommend giving "NETWORK SERVICE" write and modify rights on the RDP Wrapper folder, and comment out the ";LogFile=\rdpwrap.txt" line in the .ini file. This should force RDPWrap to write it's logfile into the RDP Wrapper folder, so you should be able to trace it working.

Though I should point out, for security reasons, it will be best to revert this so NETWORK SERVICE does not have unrestricted write/modify rights on the folder, .ini or .dll, and only allow it write access to .txt file!

**Comment by latware** [comment]
> Using the latest INI file linked from **affinityv**'s answer in issue #1022 fixed it for me.

worked for me too on

OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19041 N/A Build 19041

just stopped service & replaced .ini in RDPwrapper directory, after restarting termserv I have RDP connection...

**Comment by jianwu** [comment]
Works for me: 10.0.19041.789
Use the solution in #1022, and instead of copy the ini file, I edited it to avoid permission problems.  Finally, get it to work.

**Comment by ctmakro** [comment]
- use the INI file mentioned in #1022
- IMPORTANT: instead of copy the ini file, edit it to avoid permission problems.

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/872
