### ISSUE TITLE
How many concurrency is supported in Win10？15？

### ISSUE THREAD

**Issue by davidcao2000** [stascorp/rdpwrap#1027]
My win 10 is 10.0.18363.720, Enterprise. I've updated the latest rdpwrap.ini and it works well. But I found the maximum number of remote sessions is 15(exclude local console sessions). Is there any way to increase this number?  Thanks a lot!

**Comment by Roachen** [comment]
Hey. Can you give me a link for that rdpwrap.ini for 18363.720? Thank you!

**Comment by davidcao2000** [comment]
I remember somewhere there is an "autoupdate" link, but I can't find it now:(  
so I paste the ini file here.  
[rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/4341736/rdpwrap.ini.zip)

**Comment by JaJe92** [comment]
I just had the issue not being able to connect using the 10.0.18363.720.
Thank you very much davidcao2000 for the file!

**Comment by maniek6** [comment]
I had the same problem. On windows 10 can connect just 15 sessions.
Have you any solution?

**Comment by davidcao2000** [comment]
I have no solution about the concurrency limit. Let's try to find more information.

**Comment by maniek6** [comment]
I prepared another VM so i have at the moment 30 rdps.

**Comment by plesiu** [comment]
If you encountered problem with limit number of sessions try to change in gpedit.msc this setting.  Local Computer Policy > Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Connections. Limit Number of Connections = 999999

I also had problem to connect with more than 10 sessions and after change this setting problem gone.
