### ISSUE TITLE
No Support for Windows 10 1909 Build 18636.418

### ISSUE THREAD

**Issue by BrunoFischerGermany** [stascorp/rdpwrap#1029]
Hello!
There is no Support for my Windows 10 1909 Build 18636.418. Can someone help?
Greets

**Comment by randolf** [comment]
Does this one work for you?  https://github.com/stascorp/rdpwrap/issues/763#issuecomment-593877831

**Comment by BrunoFischerGermany** [comment]
Thank You! 
That works Fine!!!! 👍👌👌👌👌👌
