### ISSUE TITLE
No download available from site...

### ISSUE THREAD

**Issue by Shand359** [stascorp/rdpwrap#103]
I downloaded what I thought was the correct files however it appears I downloaded the SOURCE FILES. The actual files I am looking for to install are NOT there.
![error](https://cloud.githubusercontent.com/assets/17927390/13878045/9bd319d8-ed06-11e5-91a1-5cf0032eb703.JPG)
If I am doing this wrong please tell me so I can get this downloaded and installed....

**Comment by binarymaster** [comment]
https://github.com/stascorp/rdpwrap/issues/102
