### ISSUE TITLE
RDPWrap

### ISSUE THREAD

**Issue by FrankenPahpii** [stascorp/rdpwrap#104]
v1.6 has stopped working on latest Redstone Win10 version.  Any suggestions on how to fix?  Thank you.  Specifically, the listening state says "not listening [not supported]".

**Comment by neuralx** [comment]
Have you tried running update.bat as Administrator?

**Comment by FrankenPahpii** [comment]
Yes, still does not work.

**Comment by binarymaster** [comment]
Probably a duplicate of https://github.com/stascorp/rdpwrap/issues/79
