### ISSUE TITLE
Listener state: Not listening [not supported]  for windows 10 home version 1709 (OS build 16299.1087)

### ISSUE THREAD

**Issue by PreyaBhatt** [stascorp/rdpwrap#1042]

**Comment by PreyaBhatt** [comment]
Hello,

Thank you for rdpwrap!

for me, RDPConfig is showing below configurations
Wrapper state 1.5.0.0 Installed
Service state 10.0.16299.087 Running
Listener State: Not Listening [not Supported]

Thank you!

**Comment by affinityv** [comment]
https://github.com/stascorp/rdpwrap/issues/1035#issuecomment-604501183

**Comment by PreyaBhatt** [comment]
I followed above step now status is Listener State: Not Listening [fullySupported]

**Comment by affinityv** [comment]
No AV or Windows Defender interference?  You have excluded the `c:\Program Files\RDP Wrapper` directory?

**Comment by PreyaBhatt** [comment]
I have disabled AV or Windows Defender interference

**Comment by PreyaBhatt** [comment]
now the status is Listener State: Listening [fullySupported] but while running RDPWInst.exe I am getting a message : no shared service found

**Comment by PreyaBhatt** [comment]
I am able to open RDC through RDPcheck successfully, but still, I am not able to take remote system

**Comment by affinityv** [comment]
Okay, what about firewall then?  If you can do RDPCheck on the remote box and connect, it should work....

**Comment by PreyaBhatt** [comment]
my firewall is off but still, I am getting below error while connecting Remote system


![remote](https://user-images.githubusercontent.com/62837421/77859157-63af2300-7225-11ea-8d29-02553c9f9cf4.png)

**Comment by PreyaBhatt** [comment]
> my firewall is off but still, I am getting below error while connecting Remote system
> 
> ![remote](https://user-images.githubusercontent.com/62837421/77859157-63af2300-7225-11ea-8d29-02553c9f9cf4.png)

**Comment by affinityv** [comment]
Okay, what about the network interface type, is it private or public; that could be an issue.

**Comment by PreyaBhatt** [comment]
for both private and public I have tried it is not working

**Comment by affinityv** [comment]
Somebody else?

**Comment by jhonny003** [comment]
buenas tardes amigos! Les cuento que me sucede lo mismo en varios equipos funcionando con Windows 10. El problema se inició luego de los reinicios de SO por parte de las actualizaciones. Me dejaron de funcionar las conexiones remotas por RDP con el mismo error:

![imagen](https://user-images.githubusercontent.com/60977204/80527692-28f6f280-896b-11ea-94ba-fa5894824a5d.png)

Tengo conexión por teamviewer también a estos equipos por lo que puedo conectar y controlar pero por remoto, se cayeron y no logro revertir el problema. A alguno le sucedió? En estos momentos es medio crítico tener a varios usuarios sin poder conectar. Apelo a su gran experiencia para ver qué puede ser lo que sucede.

Trabajo con el mismo AV desde hace 2 años, tengo cargadas las excepciones y habilitado el puerto + app dentro del Firewall.

Aguardo sus comentarios y me mantengo online. Desde ya, muchas gracias!
