### ISSUE TITLE
All Windows monitors go black for a moment every minute when rdwrap is running

### ISSUE THREAD

**Issue by lxnglz** [stascorp/rdpwrap#1045]
A ridiculous problem, but when rdwrap is running, the system on times gets into the state when all connected monitors start to blink black approximately once a minute. This is not when I connect through RDP but rather when I am working directly at my PC. This behaviour began a few months ago and it is not always reproducible. And it does not depend on the video card because it was changed recently. More likely it depends on the particular update of the rdwrap .ini file that reflects Windows updates. The only thing I can say for sure is that once I uninstall rdwrap, the blinking goes away, and once I install in back - it comes again.
I have Windows 10 64bit which is updated automatically. I have 1 4K and 1 regular FullHD monitor, and they blink simultaneously. But I dont' believe its about the monitors. As if the system tries to switch a user once per minute and then restores.

**Comment by s0nic9** [comment]
are you running TeamViewer in background ?

**Comment by lxnglz** [comment]
No, nothing special is running. I close everything but it does not help. In regard to the TeamViewer - I have never even installed it on my PC. Of course there are many standard Windows services running in the background, but nonthing unusual. I have a simple office setup: LibreOffice, Adobe Acrobat reader, a number of graphics editing and CAD tools - but nothing non-standard related to screen sharing or user management.

**Comment by s0nic9** [comment]
duplicate entries in .ini ?
you can reduce it to your version only to test, there is two sections per version

**Comment by lxnglz** [comment]
hmm, interesting. there were no duplicates in the the ini-file, but it was really long. I deleted all build-specific sections except the most recent Windows build and now the screen is not blinking anymore. Not sure if this was the only reason, but as it has solved the issue for now, I close it.
thanks!

**Comment by lxnglz** [comment]
unfortunately, the issue has come back again. Now the screen blinking happens not so often and may come and go sporadically. It probably happens more often when there is a lot apps open, but not neccessarly. I don't know what to think :(

**Comment by lxnglz** [comment]
apparently the reason was the Authentication mode set to "GUI Authentication only". I reset it to "Network Level Authentication", and the problem went away. at least for now.

**Comment by s0nic9** [comment]
you can try https://github.com/stascorp/rdpwrap/issues/858#issuecomment-523192537
it can be related.
