### ISSUE TITLE
Missing "issue" threads 1035 at least????

### ISSUE THREAD

**Issue by affinityv** [stascorp/rdpwrap#1052]
Can no longer see this comment or any of the thread issue, why?

https://github.com/stascorp/rdpwrap/issues/1035#issuecomment-604501183

**Comment by sebaxakerhtc** [comment]
> Can no longer see this comment or any of the thread issue, why?
> 
> [#1035 (comment)](https://github.com/stascorp/rdpwrap/issues/1035#issuecomment-604501183)

May be we need to send this question to M$...
;)
