### ISSUE TITLE
Terminal Services version: 10.0.18362.657 not supported

### ISSUE THREAD

**Issue by EmilioSerna** [stascorp/rdpwrap#1056]
Hello, i have a problem when i try to use multiple connections.

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.18362.657
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[+] TermService found (pid 4112).
[*] No shared services found.
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[*] Downloading latest INI file...
[+] Latest INI file -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting TermService...
[*] Configuring registry...
[*] Configuring firewall...
Aceptar

[+] Successfully installed.
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

Presione una tecla para continuar . . .

Here's my termsrv.dll
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/4498038/termsrv.zip)
Thank you.

**Comment by affinityv** [comment]
Does anybody even check for other messages / issues?  This has been solved long ago, do a little research and you will find many times what to do.

**Comment by affinityv** [comment]
https://github.com/stascorp/rdpwrap/issues/1022#issuecomment-596437997

**Comment by EmilioSerna** [comment]
I just did what the log said to, "If it doesn't help, send your termsrv.dll to project developer for support.", it worked, thank you!
