### ISSUE TITLE
termsrv.dll 10.0.18362.267

### ISSUE THREAD

**Issue by mahmoodyali** [stascorp/rdpwrap#1061]
Please update For Windows 10 Pro v1909 Terminal Service
termsrv.dll 10.0.18362.267

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/4517265/termsrv.zip)

**Comment by affinityv** [comment]
https://github.com/stascorp/rdpwrap/issues/1022#issuecomment-596437997

**Comment by mahmoodyali** [comment]
Worked !
Thanks  Bro.
You Saved My Life ;)

**Comment by mahmoodyali** [comment]
A Problem Found In This Version of termsrv.dll (10.0.18362.267).
"Disable Shadowing" Not Work Correctly.
I Just Want Single User Per Session Without Shadowing.

![shad](https://user-images.githubusercontent.com/6578314/80704815-87061000-8afa-11ea-803c-2e2f92659ec9.png)

**Comment by affinityv** [comment]
If there is a fix for the ini section, please let me know; I only maintain the ini from provided ini sections by others skilled in creating the sections....

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/871
