### ISSUE TITLE
Local console is disconnected when RDP connection is established in Win 10 Pro 10.0.18362.657

### ISSUE THREAD

**Issue by p1nky14** [stascorp/rdpwrap#1064]
There was already an issue here for older versions, but none of the workarounds seem to work on 1909 and the current termsrv.dll:
https://github.com/stascorp/rdpwrap/issues/422

Is there any other workaround that still works?

My goal is to have an open local session and RDP to the PC from mobile devices using the same user, but not have the local console session being taken over but instead getting a new session for the user when logging in via RDP from the mobile client.  I am using the MS "RD Client" on iOS (there doesn't seem to be any other available and they killed the good old iTag RDP years ago).
The use case is that I want to login remotely with this user and have all the applications and settings of this user available, but at the same time do NOT want to have my windows thrown around in the local session due to the different resolution on the mobile device and use RDP on the mobile device in a resolution that makes sense (and the MS RD Client not even allowing to set the same resolution as I have set locally).

The current behaviour is that when I login via RDP then the local session is taken over and I can login locally to create a new local session.
The desired behaviour is to keep the local session open when logging in via RDP and instead have a new session created for RDP.

See the settings below, the current behaviour is the same no matter what authentication mode I use.

![image](https://user-images.githubusercontent.com/64169180/80198562-86640a00-8620-11ea-8512-9f37ff7eb6eb.png)

**Comment by sk-lau** [comment]
Your settings seem correct

However you can try reset the none single session per user.

 First click on Single session per user then Apply. Then uncheck the box and Apply again. See if it works

**Comment by danmaxis** [comment]
It`s strange that my Win10 has this same version for termserv.dll but this config screen shows as "not compatible" and it is just like I didnt install anything at all...
I just wanted to two different users use the same computer, one locally and the other remote via RDP

**Comment by EngFelix** [comment]
> 
> 
> It`s strange that my Win10 has this same version for termserv.dll but this config screen shows as "not compatible" and it is just like I didnt install anything at all...
> I just wanted to two different users use the same computer, one locally and the other remote via RDP

Hey, same here. Changing the .ini from #1040 solved the issue for me.

> I had similar problem. You can use
> rdpwrap.zip
> for support RDP on current version Windows.
> 
> Step by step:
> 
>     Run PS from Administrator
>     Exec "get-service termservice|stop-service -force"
>     Replace original rdpwrap.ini in C:\Program Files\RDP Wrapper\ on rdpwrap in zip attached.
>     Exec "get-service termservice|start-service"
> 
> Done

**Comment by danmaxis** [comment]
It went just fine! Thanks man!

**Comment by p1nky14** [comment]
> However you can try reset the none single session per user.
> 
> First click on Single session per user then Apply. Then uncheck the box and Apply again. See if it works

Same result unfortunately, opening an RDP connection takes over the local console session. Please note that I can have multiple sessions with the same user, however the RDP connection takes over the console session (I can then login from console, to have an additional, parallel session with the same user, but I want the RDP connection to have a separate session instead of taking over the console session).

**Comment by egmsystems** [comment]
> rdpwrap.ini

file not exists in zip

**Comment by evandrix** [comment]
> > However you can try reset the none single session per user.
> > First click on Single session per user then Apply. Then uncheck the box and Apply again. See if it works
> 
> Same result unfortunately, opening an RDP connection takes over the local console session. Please note that I can have multiple sessions with the same user, however the RDP connection takes over the console session (I can then login from console, to have an additional, parallel session with the same user, but I want the RDP connection to have a separate session instead of taking over the console session).

this is happening to me too, on Win10 v2004, is there resolution in another issue?

**Comment by robbak** [comment]
No, that is per design. Logging in remotely will always disconnect the
local session. Without single session, more than one remote connection
could be made under the same user account, and, maybe, the local user could
log back in and get a new session instead of taking over the remote session.

This is a design decision and limitation of windows RDP.

It is recommended that each user that connects remotely have their own user
account. If they need to share some resources, then these can be shared,
say, using the public user's account, or by just giving all the users
access to a shared folder.

**Comment by sk-lau** [comment]
Yes I have found that RDP remote session will always take over the local console session no matter if you use multi session per user

Best to create another user for remote RDP login purposes

**Comment by sebaxakerhtc** [comment]
Same as https://github.com/stascorp/rdpwrap/issues/422
