### ISSUE TITLE
Service error: "The Remote Desktop Services service could not be started"

### ISSUE THREAD

**Issue by EliezerBee** [stascorp/rdpwrap#1066]
I know this isn't a RDPWrap issue. But it's preventing me from running RDP and can't find a usable solution via Google. I'm running Windows 8.1 Pro x64.

Everything was working fine until I ran a ESET malware scan, very specifically chose that I did _not_ want it making modifications to my system automatically, but nonetheless it went ahead and flagged and _quarantined_ RDPWrap files. I tried restoring them using the option within the ESET program but it apparently didn't work...

![image](https://user-images.githubusercontent.com/5578694/80313945-e6d78080-87b3-11ea-9bd6-a5611aa47f58.png)

![image](https://user-images.githubusercontent.com/5578694/80313962-f060e880-87b3-11ea-8399-9b070ad32655.png)

![image](https://user-images.githubusercontent.com/5578694/80313968-f35bd900-87b3-11ea-8267-b75cd557d69f.png)

![image](https://user-images.githubusercontent.com/5578694/80313971-f6ef6000-87b3-11ea-8d10-d5f36f5135f3.png)

Is this the problem?

![image](https://user-images.githubusercontent.com/5578694/80314058-8bf25900-87b4-11ea-9250-e3fd2c1e0024.png)

![image](https://user-images.githubusercontent.com/5578694/80314068-a4627380-87b4-11ea-9e74-7609793f2718.png)

How can I get the service started again?

**Comment by affinityv** [comment]
Antivirus or Windows Defender may be removing rdpwrap.dll -- create exceptions and install again.

**Comment by EliezerBee** [comment]
Where is rdpwrap.dll actually supposed to be saved?

**Comment by EliezerBee** [comment]
Defender is disabled.
Avira Free (the AV I use) has a place for exceptions, but I'm not sure what to exclude:

![image](https://user-images.githubusercontent.com/5578694/80317118-7cc8d680-87c7-11ea-9266-e837948cc6ae.png)

In any case, when I try to uninstall RDPWrap, I get this:

![image](https://user-images.githubusercontent.com/5578694/80317038-06c46f80-87c7-11ea-9b1d-693b223d9c67.png)

If I try to run the MSI, I get this:

![image](https://user-images.githubusercontent.com/5578694/80317044-0deb7d80-87c7-11ea-9611-ccc5aeeedc26.png)

**Comment by affinityv** [comment]
Exclude files in "C:\Program Files\RDP Wrapper" ...

**Comment by EliezerBee** [comment]
I decided it was easier to roll-back to a backup from 10 days ago of my Windows drive. It now works. :)

I did also exclude the two files (DLL and INI) in the RDP Wrapper folder.

Thank you for your help!
