### ISSUE TITLE
Win 2004 incompatibility, here the termserv.dll 

### ISSUE THREAD

**Issue by enricoti** [stascorp/rdpwrap#1067]
Hi to everyone,
as in subject I'm using Windows 10 PRO N [Workstation to be picky].
The version is the 2004 with this string: 19041.207 too fresh to be used asap as I hoped! :-(

Here you can find the termserv.dll of this build.

Thank you so much!
Regards!

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/4536043/termsrv.zip)

**Comment by sk-lau** [comment]
Hi your rdp version should be covered here :-1: 
 
https://github.com/stascorp/rdpwrap/issues/1055

**Comment by ahkui** [comment]
Can't use

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1004
