### ISSUE TITLE
Windows 10 Home: Unable to connect as non admin

### ISSUE THREAD

**Issue by philippseith** [stascorp/rdpwrap#107]
I removed my personal user from ther administrators group and, because there is no group for remote desktop users on Win 10 Home, granted the right to for remote login to the user using gpedit.msc. 
I can remotely reach the login screen of the Win10 Home, but if I login as user, I am getting "The requested session access is denied"
In the eventviewer on Home a crash of dwm.exe is reported. Sometimes it fails in combase.dll, sometimes in kernelbase.dll. The crash seems to occur shortly after the "access denied" was acknowledged.

**Comment by binarymaster** [comment]
See README.md: Adding "Remote Desktop Users" group.

**Comment by fm99** [comment]
Hi Stas'M,
You've just closed the issue with reference to README.md - which in turn just contains a reference to post 680572 on superuser.com. There are two different answers posted there: http://superuser.com/a/719819 and http://superuser.com/a/680573 . Which one is the correct solution that allows non-admin users to use RDP on a Win 10 Home machine?

**Comment by binarymaster** [comment]
Try first one

**Comment by fm99** [comment]
Hi again,
In brief, unfortunately it doesn't work - I've created a REG file as per the 1st answer (http://superuser.com/a/719819) and imported it under the System account using the PSexec tool method described in the 2nd answer (http://superuser.com/a/680573). The import was successful. After a reboot when trying to login with a non-admin user I still get this error: "To sign in remotely, you need the right to sign through Remote Desktop Services. By default, members [...]".
Am I missing something?

**Comment by fm99** [comment]
Ok, I have found the missing bit: The non-admin user must be added to the local "Remote Desktop Users" group (as mentioned in the 2nd answer). I.e. running cmd.exe as administrator I entered:
net localgroup "Remote Desktop Users" MyNonAdminUser /add
And bingo! Now I can sign in to a Win 10 Home machine with a non-admin user.

**Comment by binarymaster** [comment]
Good! :)
