### ISSUE TITLE
version compatibility

### ISSUE THREAD

**Issue by alitimer** [stascorp/rdpwrap#1073]
![rdpwrap](https://user-images.githubusercontent.com/43956778/80793142-e3cffc00-8bc8-11ea-9d28-a4f1c3949397.PNG)
Got confused with the versions. 

- RdpWrap shows windows version different than what system shows!
- By replacing `.dll` file given in [1070](https://github.com/stascorp/rdpwrap/issues/1070) located at `C:\Program Files\RDP Wrapper` directory, the RdpWrap version in the `RDPConf.exe` changes from 1.5.0.0 to windows version number! and "not supported" yet! sometimes "not fully supported" with other `.ini` contents.
- Shall I request from my windows version `.ini` content file?

**Comment by robbak** [comment]
Um, why would you install a random .dll file? I don't think a different dll file will work with your version of windows. Put your old one back.

The version numbers are not windows versions. The top one is the version of the rdp wrapper you have installed. The second is the version of the window termsrv.dll. file. 

The rdpwrap.ini listed in #1055 should work for everyone. It has the information to support all terminal services dlls up to the upcoming May 2020 windows update. Stop the remote desktop service, Download it and put it in your program files/rdpwrapper folder, then restart the remote desktop service.

**Comment by alitimer** [comment]
![rdpwrap2](https://user-images.githubusercontent.com/43956778/80795893-66a88500-8bd0-11ea-8a8b-556b9d265f16.PNG)

Surprisingly that was the only way I could successfully connected by +1 account remotely via RDP. I mean after replacing `C:\Program Files\RDP Wrapper\rdpwrap.dll` by `termsrv.dll` and renaming that to `rdpwrap.dll`. Not sure the relation here. 
Now hit the following error by fresh installation of [1.6.2](https://github.com/stascorp/rdpwrap/releases/tag/v1.6.2) and adding [1055](https://github.com/stascorp/rdpwrap/issues/1055) at the end of `C:\Program Files\RDP Wrapper\rdpwrap.ini`. 
Any advise?
![rdpwrap3](https://user-images.githubusercontent.com/43956778/80795164-555e7900-8bce-11ea-916e-6f388f98662f.PNG)
I have removed the connection number limit in group policy and it was working before. So it's not the case.
and BTW, `RDPConf.exe` is showing 1.5.0.0 instead of 1.6.2. I need a bit clarification!
![rdpwrap4](https://user-images.githubusercontent.com/43956778/80795726-ec780080-8bcf-11ea-885c-6d80c3da76bb.PNG)

**Comment by robbak** [comment]
Wel, if you really have replaced rdpwrap.dll with a random termsrv.dll, then that's broken it. You have basically uninstalled rdpwrapper, and your computer is probably just trying to load two different copies of termsrv.dll.

That won't do you any good.

Delete program files/rdpwrapper and start again. Currently, rdp wrapper just isn't working. That's what the blue image you just posted is telling you.

**Comment by alitimer** [comment]
Here is a fresh installation outcome; seems to have confliction:
```RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.18362.657
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[+] TermService found (pid 360).
[*] No shared services found.
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[*] Downloading latest INI file...
[+] Latest INI file -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting TermService...
[-] StartService error (code 1056).
[*] Configuring registry...
[*] Configuring firewall...
Ok.

[+] Successfully installed.
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

Press any key to continue . . .
```
Running `update.bat`:
```RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Checking for updates...
[*] Current update date: 2018.10.10
[*] Latest update date:  2018.10.10
[*] Everything is up to date.

Press any key to continue . . .
```
And `RDPWInst -w`:
```C:\Users\test\Downloads\RDPWrap-v1.6.2>RDPWInst -w
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Checking for updates...
[*] Current update date: 2018.10.10
[*] Latest update date:  2018.10.10
[*] Everything is up to date.
```
None of them helped.
![rdpwrap6](https://user-images.githubusercontent.com/43956778/80797884-8aba9500-8bd5-11ea-85ea-5991dc989f4f.PNG)
![rdpwrap5](https://user-images.githubusercontent.com/43956778/80797942-ac1b8100-8bd5-11ea-82c1-194cfaa87805.PNG)
![rdpwrap3](https://user-images.githubusercontent.com/43956778/80797951-b0e03500-8bd5-11ea-8595-775a08e0534e.PNG)

Here is my `C:\Windows\System32\termsrv.dll`. Any help please?

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/4563305/termsrv.zip)

**Comment by robbak** [comment]
Use this ini file - https://github.com/JD10NN3/rdpwrap/blob/patch-1/res/rdpwrap.ini

It supports everything currently available. Stop the remote access service, replace the rdpwrap.ini file in program files/rdpwrapper with the one i gave you, then start the service again

Or just use autoupdate.bat in #859

**Comment by alitimer** [comment]
`https://github.com/JD10NN3/rdpwrap/blob/patch-1/res/rdpwrap.ini` stopped the service (a few moment everythin's green/ok but got stopped):
![rdpwrap7](https://user-images.githubusercontent.com/43956778/80799312-1c77d180-8bd9-11ea-8582-54b7e95e8e7c.PNG)
`autoupdate.bat`  brings back everything as it was:
![rdpwrap6](https://user-images.githubusercontent.com/43956778/80799445-71b3e300-8bd9-11ea-8bb6-9c79c4e80553.PNG)
![rdpwrap3](https://user-images.githubusercontent.com/43956778/80799371-48935280-8bd9-11ea-9e32-b3268d570b83.PNG)

**Comment by affinityv** [comment]
This [ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) has more sections and covers everything that the above one referenced by @robbak does.

**Comment by alitimer** [comment]
Nice one, worked.
Thanks heaps!

![rdpwrap8](https://user-images.githubusercontent.com/43956778/80800426-01f32780-8bdc-11ea-9b1d-eacedc0795c8.PNG)
![rdpwrap9](https://user-images.githubusercontent.com/43956778/80800435-0586ae80-8bdc-11ea-911c-dae067614202.PNG)
