### ISSUE TITLE
rdpconf.exe says "fully supported(10.0.18362.657)" for two ini files, but one works and one doesn't

### ISSUE THREAD

**Issue by gartha1** [stascorp/rdpwrap#1076]
rdpconf.exe says "fully supported(10.0.18362.657)" for two ini files, but one works and one doesn't

For the one that doesn't work, rdpcheck says "The number of connections to this computer is limited and all connections are in use right now"

from what I can tell, pasting relevant sections from each in excel alongside each other, they have the same settings, but the order just differs.

[rdpwrap_works_ini.txt](https://github.com/stascorp/rdpwrap/files/4578555/rdpwrap_works_ini.txt)
[rdpwrap_notwork_ini.txt](https://github.com/stascorp/rdpwrap/files/4578556/rdpwrap_notwork_ini.txt)

The one that works is the one from @affinityv

**Comment by robbak** [comment]
Where did you get the non-working file from? I want to make sure that we
aren't recommending it to others. But this is a good reminder - just
because it says 'Supported' and 'listening' doesn't mean RDPWrapper is
working - a broken .ini file can stop it from working, but not crash
anything.

Unfortunately, the files are too different for a quick diff command to pin
down the important differences.

**Comment by gartha1** [comment]
I heard somewhere to look through pull requests for a recent rdpwrap.ini(I suppose, more recent than the one in the code section or perhaps more recent than the one that update.bat might fetch),  or an rdpwrap.ini with my termsrv.dll build in it and I found  https://github.com/stascorp/rdpwrap/pull/859  which had a link to https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini   which is the file that didn't work for me

**Comment by robbak** [comment]
@asmtron could you make sure that there isn't a problem with the .ini file currently in your repository?

@gartha1 perhaps you could lodge this as an issue on @asmtron 's github repository, https://github.com/asmtron/rdpwrap, if the file from there is still not working for you.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/983

**Comment by sebaxakerhtc** [comment]
Also look at https://github.com/stascorp/rdpwrap/issues/353
