### ISSUE TITLE
I can't get windows to uninstall RDP Wrapper so i can try to install fresh, nor can I get what is installed working

### ISSUE THREAD

**Issue by chrisbaber** [stascorp/rdpwrap#1078]
I had this working for a long time, but when I ran an antivirus for another issue, it killed RDP.  Now, I cannot get it working again, nor can i uninstall it.  I've downloaded the files and tried installing, but it says RDP is already installed.  I can see it listed in Programs and Features, but I get an error message when i try to uninstall.  Change and Repair seem to have no effect either.  If I try to run the uninstall.bat file that fails also.  I'm at a loss on how to simply remove RDP Wrapper altogether, so i can start fresh.

![install failed](https://user-images.githubusercontent.com/36215526/81126752-52cf8c80-8f0a-11ea-9e67-2cd883b9a77c.jpg)
![config](https://user-images.githubusercontent.com/36215526/81126754-53682300-8f0a-11ea-8b37-598cfd71349d.jpg)
![batch](https://user-images.githubusercontent.com/36215526/81126840-8f02ed00-8f0a-11ea-9bfc-1bd7ce60cf64.jpg)

**Comment by robbak** [comment]
Seems like your antivirus program has gone rogue, and deleted the
RDPWrapper files. You can't then uninstall it, because uninstalling
requires calling RDPInstall.exe, which has probably been deleted.

Disable your antivirus program's real-time protection, reinstall
RDWWrapper, update your .ini file, mark your Program Files/RDPWrapper directory as an exception in the antivirus program so it won't do it again, and then you should be right.

Or, change antivirus providers, and if they give you the option, tell them
that you are dropping them because it deleted an essential program,
RDPWrapper. I'm getting annoyed at all these antivirus programs deleting essential IT tools.

**Comment by chrisbaber** [comment]
It was a stand alone virus program that deleted files (eset online), even though I said to not quarantine them.  I don't have any stand alone anti-virus programs installed normally, I only use that one for a one-off check due to some weirdness I was experiencing.  I just use the built-in defender in Windows 10.  I've never previously specifically allowed RDP in that program, but came across an autoupdate batch file for RDP which suggested it, so I actually already did allow the exception, but I'm still having the issues.  Below is the exception as I have it setup, and also the files in program files/RDP Wrapper file, which is where I believe it's suggested to be installed.

I did download the installer.msi from github, which I don't think I've ever used before, but that didn't seem to actually install/do anything.  It is also in the wrapper folder.

not sure what else to try next.

![exclusions](https://user-images.githubusercontent.com/36215526/81129092-397e0e80-8f11-11ea-87c4-f557a1bff515.jpg)
![wrapper files](https://user-images.githubusercontent.com/36215526/81129094-397e0e80-8f11-11ea-8192-ba7ceed7849c.jpg)

**Comment by robbak** [comment]
The .msi just copies the files to Program Files and runs the install
program, so you can just do that. In an administrator command prompt, run
RDPWInst.exe . It should fix everything up for you, or at least tell you
why it isn't working.

**Comment by chrisbaber** [comment]
same as before, failed to set up TermService. Unknown error.

![error](https://user-images.githubusercontent.com/36215526/81130895-4f8ecd80-8f17-11ea-995a-c312d663555c.jpg)

**Comment by chrisbaber** [comment]
I checked services and tried starting Remote Desktop Services and got this error...

![RDS](https://user-images.githubusercontent.com/36215526/81131116-17d45580-8f18-11ea-92eb-16c9e3d28862.jpg)

So it seems to be a windows issue, not necessarily a RDP issue.  Not sure where to turn for help resolving this.

**Comment by robbak** [comment]
Next thing to try is to use that to do an uninstall. RDPWInst -u . My best
guess as to why TermService isn't starting is that it is trying to call a
now non-existant RDP Wrapper dll from somewhere .
I also don't see an rdpwrap.ini file there - the ones that rdpinst -r can
find are rather out of date. There's a newer one in this github repo's pull
request queue that should work.
 (that link on this site that says, "Pull Requests".)

**Comment by chrisbaber** [comment]
So, the weirdness continues.  running RDPWInst -u from an admin cmd prompt give the same error, Failed to setup TermService.  Unknown error.

I thought, before posting here, that I would just rename the RDP Wrapper folder, and start over.  So I created a new RDP Wrapper folder and tried to install, and uninstall before posting here.  I currently have a RDP Wrapper folder, and an OLD RDP Wrapper folder.  The .ini file(s) are (were) in the OLD RDP Wrapper folder.  I copied them to the new folder.  Not sure why they didn't get created when I tried to start over, but I suppose it's all related.

I've tried to RDPWInst -u from both locations, and have had the same error in each.

I moved on to working on cleaning up other stuff, and saw a Default.rdp file as I was moving around, and figured I'd just d-click and see what happened.

It connected to my remote host, and is working just fine!  In fact, for the first time in years, it actually shadowed correctly, and didn't interrupt the session on the server, which continued to play a video without any issues at all, while I was able to work away in the remote session for an hour with no problems at all.

Both the RDP Wrapper and OLD RDP Wrapper folders were checked, and both continue to give the same Stopped and Not Listening red 'errors' when I checked RDPConf.exe, but it's actually working fine, great even.

I'd still like to resolve this issue, and know that I only have the one working instance, which can be installed and uninstalled correctly, but I honestly don't know what else to check, nor am I certain it's best to continue messing with what seems to be actually working better than it has in a long time, even if it says it's not working.

I'm so confused.

**Comment by chrisbaber** [comment]
I just tried to uninstall again, and thought this might point to something useful

![uninstall](https://user-images.githubusercontent.com/36215526/81182093-5f3ffd80-8f7b-11ea-8ed5-be50164a82e9.jpg)

Not sure if c:\windows\Installer\bc009.msi is the right place to be trying to uninstall from, nor how that came to be the path, but it does correctly refer to RDP Wrapper, so maybe it's right?

**Comment by robbak** [comment]
You are probably using the feature that is the reason why all the rdp stuff is still in windows for us to mess with - Remote assistance. Even on an unmodified Windows Home, you can still create an invitation file that allows someone to Shadow your session, for remote troubleshooting purposes. It doesn't allow someone to create a second session, or to log in remotely if you aren't logging in.

Oh, that dialog is completely normal, when using the .msi file to install or uninstall. But I haven't used the .msi file - copying files out of the .zip is much easier.

I'm going to bow out here. I don't have any other suggestions to give you. Perhaps if you tried starting/restarting the remote access service from the services.msc, or from the command line (`net stop termservices `and `net start termservices`) you might get more information.

**Comment by chrisbaber** [comment]
First, I really appreciate your help with this; thank you!!

To be clear, I'm trying to use my laptop (which is giving the errors) to connect to the server, which is actually working.  My understanding of remote assistance is that it would allow my laptop to allow someone else to connect to the laptop, which may or may not work; I haven't tested it.

The server is basically unchanged for a long time, apart from perhaps some windows updates.

I tried running net stop termservices and got this

![net stop](https://user-images.githubusercontent.com/36215526/81186774-3589d500-8f81-11ea-8510-ab0b0279bdc2.jpg)

I checked services and see that Remote Desktop Services is set to Automatic, but not started.  Trying to start it gives this...

![rds error](https://user-images.githubusercontent.com/36215526/81186901-5baf7500-8f81-11ea-8535-4ce8b3ef5b0a.jpg)

I'm researching that now, but it seems like a Windows issue.  Solutions seem convoluted so far

**Comment by robbak** [comment]
I don't quite understand what you are doing. Ordinary unmodified Windows Home will happily act as a RDP client, connecting to a server. We use RDPWrapper to allow Windows Home and Professional to act as RDP servers, the computer you connect to, bypassing the limitations Microsoft puts on these.

You would only need RDPWrapper on your laptop computer if you wanted to connect to your laptop from another computer.

AS to why terminal services isn't working on your notebook computer, check whether you have a valid copy of termsrv.dll in Windows/System32. Many older how-tos recommend messing around with this file, copying in older versions of it, so this file may have been deleted. You also could use sfc to sort out any problems with missing or corrupted system files.

**Comment by chrisbaber** [comment]
Okay.  I didn't realize I could connect from the laptop without RDP Wrapper.  i thought I needed it on all machines.  

I do have termserv.dll in Windows/System32

File version 10.0.18362.657
Size 1.01 MB

I don't recall ever messing with that file, so I assume it's the correct version.

I'm happy to remove RDP Wrapper from the laptop, as it's one less thing to manage moving forward. But, I'm unable to do so.  I cannot find any way to simply remove it now.

Every attempt at uninstalling fails with "Failed to set up TermService. Unknown error."

I really do appreciate all your help, and I'm sorry my system is being intolerable.

**Comment by hdatma** [comment]
I see exactly the same problem with TermService on the latest version of W10Pro. 

```
>net start TermService      
The Remote Desktop Services service is starting.
The Remote Desktop Services service could not be started.
                                                         
A system error has occurred.                             
                                                         
System error 126 has occurred.                           
                                                         
The specified module could not be found.   
```

This may be useful:

```
>autoupdate.bat
___________________________________________
Automatic RDP Wrapper installer and updater

<check if the RDP Wrapper is up-to-date and working>

[-] TermService NOT running!

[*] Uninstall and reinstall RDP Wrapper...

RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Uninstalling...
[*] Configuring TermService...
[*] Starting TermService...
[-] Failed to set up TermService. Unknown error.
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] RDP Wrapper Library is already installed.
[*] Set Network Level Authentication in the windows registry...
The operation completed successfully.
The operation completed successfully.
No session exists for rdp-tcp
[-] Listener session rdp-tcp NOT found!

[*] Uninstall and reinstall RDP Wrapper...

RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Uninstalling...
[*] Configuring TermService...
[*] Starting TermService...
[-] Failed to set up TermService. Unknown error.
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] RDP Wrapper Library is already installed.
[*] Set Network Level Authentication in the windows registry...
The operation completed successfully.
The operation completed successfully.
[+] Found windows registry entry for "rdpwrap.dll".
[+] Found file: "c:\Program Files\RDP Wrapper\rdpwrap.ini".
[+] Installed "termsrv.dll" version: 10.0.19041.84.
[*] Read last "termsrv.dll" version from the windows registry...
[+] Current "termsrv.dll v.10.0.19041.84" same as last "termsrv.dll v.10.0.19041.84".
[*] Start searching [10.0.19041.84] version entry in file "c:\Program Files\RDP Wrapper\rdpwrap.ini"...
[-] NOT found "termsrv.dll" version entry [10.0.19041.84] in file "c:\Program Files\RDP Wrapper\rdpwrap.ini"!

[*] Download latest version of rdpwrap.ini from GitHub...
    -> "https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini"
[+] Successfully download from GitHhub latest version to "c:\Program Files\RDP Wrapper\rdpwrap_new.ini".
[*] Start streaming "c:\Program Files\RDP Wrapper\rdpwrap_new.ini" to "c:\Program Files\RDP Wrapper\rdpwrap.ini"...
[+] Update of "c:\Program Files\RDP Wrapper\rdpwrap.ini" finished successfully.

[*] Restart RDP Wrapper...

RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Restarting...
[*] Configuring TermService...
[*] Starting TermService...
[-] Failed to set up TermService. Unknown error.
[*] Set Network Level Authentication in the windows registry...
The operation completed successfully.
The operation completed successfully.
[*] Start searching [10.0.19041.84] version entry in file "c:\Program Files\RDP Wrapper\rdpwrap_new.ini"...
[+] Found "termsrv.dll" version entry [10.0.19041.84] in file "c:\Program Files\RDP Wrapper\rdpwrap_new.ini".
[*] RDP Wrapper seems to be up-to-date and working...
```

**Comment by heychief3000** [comment]
I had this working for about three days and Windows Anti-Virus decided to delete some important files.  
But I believe I have found a solution!

Why can i not just re-install the bloody thing?  TermService can't start and gives me the same error message as listed above.
But why? So lets investigate:

So I decided to review the code and found this:

**RDPWinst.dpr**
```
if not Reg.OpenKeyReadOnly('\SYSTEM\CurrentControlSet\Services\TermService\Parameters') then
  begin
    Reg.Free;
    Code := GetLastError;
    Writeln('[-] OpenKeyReadOnly error (code ', Code, ').');
    Halt(Code);
  end;
  TermServicePath := Reg.ReadString('ServiceDll');
  Reg.CloseKey;
  if (Pos('termsrv.dll', LowerCase(TermServicePath)) = 0)
  and (Pos('rdpwrap.dll', LowerCase(TermServicePath)) = 0) then
  begin
    Reg.Free;
    Writeln('[-] Another third-party TermService library is installed.');
    Writeln('[*] ServiceDll: "', TermServicePath, '".');
    Halt(ERROR_NOT_SUPPORTED);
  end;
 Reg.Free;

  Installed := Pos('rdpwrap.dll', LowerCase(TermServicePath)) > 0;`
```

So what we want to do is make the variable Installed evaluate to False.  This is done by the software reading what's in the ServiceDll reg value.

If you open up the registry and navigate to:

```
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters
ServiceDll
%ProgramFiles%\RDP Wrapper\rdpwrap.dll
```

Turns out this file rdpwrap.dll is deleted! Ouch!  Using a Search program like Everything, I cannot find it anywhere on my system.
So what the installation code does is looks for either rdpwrap.dll in the ServiceDll, or termsrv.dll. If it's empty, it will assume you installed some other 3rd party service.

So what I did was edit the value for 'ServiceDll' and set it to:
`C:\Windows\System32\termsrv.dll`
(It probably doesn't matter if it's a real file, since it's just checking what it's set to)

Then after that I was able to do a clean installation:

And yes, A new rdpwrap.dll is generated and the registry is updated to this path.  

Then use:
Using an autoupdate.bat file for getting the latest ini file updates.

Everything is working again for me.  Just need to backup rdpwrap.dll, and find out why Windows deleted it.
(I did try to add it to my exclusions, but still managed to disappear)

I hope this helps someone!

**Comment by iwiiiwi** [comment]
> I had this working for about three days and Windows Anti-Virus decided to delete some important files. But I believe I have found a solution!
> 
> Why can i not just re-install the bloody thing? TermService can't start and gives me the same error message as listed above. But why? So lets investigate:
> 
> So I decided to review the code and found this:
> 
> **RDPWinst.dpr**
> 
> ```
> if not Reg.OpenKeyReadOnly('\SYSTEM\CurrentControlSet\Services\TermService\Parameters') then
>   begin
>     Reg.Free;
>     Code := GetLastError;
>     Writeln('[-] OpenKeyReadOnly error (code ', Code, ').');
>     Halt(Code);
>   end;
>   TermServicePath := Reg.ReadString('ServiceDll');
>   Reg.CloseKey;
>   if (Pos('termsrv.dll', LowerCase(TermServicePath)) = 0)
>   and (Pos('rdpwrap.dll', LowerCase(TermServicePath)) = 0) then
>   begin
>     Reg.Free;
>     Writeln('[-] Another third-party TermService library is installed.');
>     Writeln('[*] ServiceDll: "', TermServicePath, '".');
>     Halt(ERROR_NOT_SUPPORTED);
>   end;
>  Reg.Free;
> 
>   Installed := Pos('rdpwrap.dll', LowerCase(TermServicePath)) > 0;`
> ```
> 
> So what we want to do is make the variable Installed evaluate to False. This is done by the software reading what's in the ServiceDll reg value.
> 
> If you open up the registry and navigate to:
> 
> ```
> Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters
> ServiceDll
> %ProgramFiles%\RDP Wrapper\rdpwrap.dll
> ```
> 
> Turns out this file rdpwrap.dll is deleted! Ouch! Using a Search program like Everything, I cannot find it anywhere on my system. So what the installation code does is looks for either rdpwrap.dll in the ServiceDll, or termsrv.dll. If it's empty, it will assume you installed some other 3rd party service.
> 
> So what I did was edit the value for 'ServiceDll' and set it to: `C:\Windows\System32\termsrv.dll` (It probably doesn't matter if it's a real file, since it's just checking what it's set to)
> 
> Then after that I was able to do a clean installation:
> 
> And yes, A new rdpwrap.dll is generated and the registry is updated to this path.
> 
> Then use: Using an autoupdate.bat file for getting the latest ini file updates.
> 
> Everything is working again for me. Just need to backup rdpwrap.dll, and find out why Windows deleted it. (I did try to add it to my exclusions, but still managed to disappear)
> 
> I hope this helps someone!

My rdpwrap.dll was also deleted by Anti-Virus.   It worked. Thank you much!
Something I want to added:   the type of  Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters   ServiceDll  is REG_EXPAND_SZ.
If someone deleted it by mistake like me,  you can receate it with this type.

**Comment by madkoding** [comment]
> I had this working for about three days and Windows Anti-Virus decided to delete some important files. But I believe I have found a solution!
> 
> Why can i not just re-install the bloody thing? TermService can't start and gives me the same error message as listed above. But why? So lets investigate:
> 
> So I decided to review the code and found this:
> 
> **RDPWinst.dpr**
> 
> ```
> if not Reg.OpenKeyReadOnly('\SYSTEM\CurrentControlSet\Services\TermService\Parameters') then
>   begin
>     Reg.Free;
>     Code := GetLastError;
>     Writeln('[-] OpenKeyReadOnly error (code ', Code, ').');
>     Halt(Code);
>   end;
>   TermServicePath := Reg.ReadString('ServiceDll');
>   Reg.CloseKey;
>   if (Pos('termsrv.dll', LowerCase(TermServicePath)) = 0)
>   and (Pos('rdpwrap.dll', LowerCase(TermServicePath)) = 0) then
>   begin
>     Reg.Free;
>     Writeln('[-] Another third-party TermService library is installed.');
>     Writeln('[*] ServiceDll: "', TermServicePath, '".');
>     Halt(ERROR_NOT_SUPPORTED);
>   end;
>  Reg.Free;
> 
>   Installed := Pos('rdpwrap.dll', LowerCase(TermServicePath)) > 0;`
> ```
> 
> So what we want to do is make the variable Installed evaluate to False. This is done by the software reading what's in the ServiceDll reg value.
> 
> If you open up the registry and navigate to:
> 
> ```
> Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters
> ServiceDll
> %ProgramFiles%\RDP Wrapper\rdpwrap.dll
> ```
> 
> Turns out this file rdpwrap.dll is deleted! Ouch! Using a Search program like Everything, I cannot find it anywhere on my system. So what the installation code does is looks for either rdpwrap.dll in the ServiceDll, or termsrv.dll. If it's empty, it will assume you installed some other 3rd party service.
> 
> So what I did was edit the value for 'ServiceDll' and set it to: `C:\Windows\System32\termsrv.dll` (It probably doesn't matter if it's a real file, since it's just checking what it's set to)
> 
> Then after that I was able to do a clean installation:
> 
> And yes, A new rdpwrap.dll is generated and the registry is updated to this path.
> 
> Then use: Using an autoupdate.bat file for getting the latest ini file updates.
> 
> Everything is working again for me. Just need to backup rdpwrap.dll, and find out why Windows deleted it. (I did try to add it to my exclusions, but still managed to disappear)
> 
> I hope this helps someone!

You are my hero

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/983
Some helpful info https://github.com/stascorp/rdpwrap/issues/1883

**Comment by danny1023cloud** [comment]
I started having this problem, but I am no techy guy so I don't know how to even follow what yall did to solve this problem. Can anyone help me step by step? That would be much appreciated!

**Comment by danny1023cloud** [comment]
I

> I started having this problem, but I am no techy guy so I don't know how to even follow what yall did to solve this problem. Can anyone help me step by step? That would be much appreciated!

I can get us on a discord call or something in order for anyone to help. Thanks

**Comment by duduzai2019** [comment]
![Uploading image.png…]()

but service state and listener state still red, how can i deal them

**Comment by duduzai2019** [comment]
![image](https://user-images.githubusercontent.com/96464964/187967683-99f946e8-517b-4e03-babd-cd29b8a7d575.png)
but service state and listener state still red, how can i deal them

**Comment by sebaxakerhtc** [comment]
> how can i deal them

Look for solution [here](https://github.com/stascorp/rdpwrap/issues/1883)

**Comment by Fransferdy** [comment]
> I had this working for about three days and Windows Anti-Virus decided to delete some important files. But I believe I have found a solution!
> 
> Why can i not just re-install the bloody thing? TermService can't start and gives me the same error message as listed above. But why? So lets investigate:
> 
> So I decided to review the code and found this:
> 
> **RDPWinst.dpr**
> 
> ```
> if not Reg.OpenKeyReadOnly('\SYSTEM\CurrentControlSet\Services\TermService\Parameters') then
>   begin
>     Reg.Free;
>     Code := GetLastError;
>     Writeln('[-] OpenKeyReadOnly error (code ', Code, ').');
>     Halt(Code);
>   end;
>   TermServicePath := Reg.ReadString('ServiceDll');
>   Reg.CloseKey;
>   if (Pos('termsrv.dll', LowerCase(TermServicePath)) = 0)
>   and (Pos('rdpwrap.dll', LowerCase(TermServicePath)) = 0) then
>   begin
>     Reg.Free;
>     Writeln('[-] Another third-party TermService library is installed.');
>     Writeln('[*] ServiceDll: "', TermServicePath, '".');
>     Halt(ERROR_NOT_SUPPORTED);
>   end;
>  Reg.Free;
> 
>   Installed := Pos('rdpwrap.dll', LowerCase(TermServicePath)) > 0;`
> ```
> 
> So what we want to do is make the variable Installed evaluate to False. This is done by the software reading what's in the ServiceDll reg value.
> 
> If you open up the registry and navigate to:
> 
> ```
> Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters
> ServiceDll
> %ProgramFiles%\RDP Wrapper\rdpwrap.dll
> ```
> 
> Turns out this file rdpwrap.dll is deleted! Ouch! Using a Search program like Everything, I cannot find it anywhere on my system. So what the installation code does is looks for either rdpwrap.dll in the ServiceDll, or termsrv.dll. If it's empty, it will assume you installed some other 3rd party service.
> 
> So what I did was edit the value for 'ServiceDll' and set it to: `C:\Windows\System32\termsrv.dll` (It probably doesn't matter if it's a real file, since it's just checking what it's set to)
> 
> Then after that I was able to do a clean installation:
> 
> And yes, A new rdpwrap.dll is generated and the registry is updated to this path.
> 
> Then use: Using an autoupdate.bat file for getting the latest ini file updates.
> 
> Everything is working again for me. Just need to backup rdpwrap.dll, and find out why Windows deleted it. (I did try to add it to my exclusions, but still managed to disappear)
> 
> I hope this helps someone!

You saved my day, you are my hero!

**Comment by Gowlfit** [comment]
> I had this working for about three days and Windows Anti-Virus decided to delete some important files. But I believe I have found a solution!
> 
> Why can i not just re-install the bloody thing? TermService can't start and gives me the same error message as listed above. But why? So lets investigate:
> 
> So I decided to review the code and found this:
> 
> **RDPWinst.dpr**
> 
> ```
> if not Reg.OpenKeyReadOnly('\SYSTEM\CurrentControlSet\Services\TermService\Parameters') then
>   begin
>     Reg.Free;
>     Code := GetLastError;
>     Writeln('[-] OpenKeyReadOnly error (code ', Code, ').');
>     Halt(Code);
>   end;
>   TermServicePath := Reg.ReadString('ServiceDll');
>   Reg.CloseKey;
>   if (Pos('termsrv.dll', LowerCase(TermServicePath)) = 0)
>   and (Pos('rdpwrap.dll', LowerCase(TermServicePath)) = 0) then
>   begin
>     Reg.Free;
>     Writeln('[-] Another third-party TermService library is installed.');
>     Writeln('[*] ServiceDll: "', TermServicePath, '".');
>     Halt(ERROR_NOT_SUPPORTED);
>   end;
>  Reg.Free;
> 
>   Installed := Pos('rdpwrap.dll', LowerCase(TermServicePath)) > 0;`
> ```
> 
> So what we want to do is make the variable Installed evaluate to False. This is done by the software reading what's in the ServiceDll reg value.
> 
> If you open up the registry and navigate to:
> 
> ```
> Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters
> ServiceDll
> %ProgramFiles%\RDP Wrapper\rdpwrap.dll
> ```
> 
> Turns out this file rdpwrap.dll is deleted! Ouch! Using a Search program like Everything, I cannot find it anywhere on my system. So what the installation code does is looks for either rdpwrap.dll in the ServiceDll, or termsrv.dll. If it's empty, it will assume you installed some other 3rd party service.
> 
> So what I did was edit the value for 'ServiceDll' and set it to: `C:\Windows\System32\termsrv.dll` (It probably doesn't matter if it's a real file, since it's just checking what it's set to)
> 
> Then after that I was able to do a clean installation:
> 
> And yes, A new rdpwrap.dll is generated and the registry is updated to this path.
> 
> Then use: Using an autoupdate.bat file for getting the latest ini file updates.
> 
> Everything is working again for me. Just need to backup rdpwrap.dll, and find out why Windows deleted it. (I did try to add it to my exclusions, but still managed to disappear)
> 
> I hope this helps someone!

lov u bro

**Comment by Yumiizera** [comment]
> I had this working for about three days and Windows Anti-Virus decided to delete some important files. But I believe I have found a solution!
> 
> Why can i not just re-install the bloody thing? TermService can't start and gives me the same error message as listed above. But why? So lets investigate:
> 
> So I decided to review the code and found this:
> 
> **RDPWinst.dpr**
> 
> ```
> if not Reg.OpenKeyReadOnly('\SYSTEM\CurrentControlSet\Services\TermService\Parameters') then
>   begin
>     Reg.Free;
>     Code := GetLastError;
>     Writeln('[-] OpenKeyReadOnly error (code ', Code, ').');
>     Halt(Code);
>   end;
>   TermServicePath := Reg.ReadString('ServiceDll');
>   Reg.CloseKey;
>   if (Pos('termsrv.dll', LowerCase(TermServicePath)) = 0)
>   and (Pos('rdpwrap.dll', LowerCase(TermServicePath)) = 0) then
>   begin
>     Reg.Free;
>     Writeln('[-] Another third-party TermService library is installed.');
>     Writeln('[*] ServiceDll: "', TermServicePath, '".');
>     Halt(ERROR_NOT_SUPPORTED);
>   end;
>  Reg.Free;
> 
>   Installed := Pos('rdpwrap.dll', LowerCase(TermServicePath)) > 0;`
> ```
> 
> So what we want to do is make the variable Installed evaluate to False. This is done by the software reading what's in the ServiceDll reg value.
> 
> If you open up the registry and navigate to:
> 
> ```
> Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters
> ServiceDll
> %ProgramFiles%\RDP Wrapper\rdpwrap.dll
> ```
> 
> Turns out this file rdpwrap.dll is deleted! Ouch! Using a Search program like Everything, I cannot find it anywhere on my system. So what the installation code does is looks for either rdpwrap.dll in the ServiceDll, or termsrv.dll. If it's empty, it will assume you installed some other 3rd party service.
> 
> So what I did was edit the value for 'ServiceDll' and set it to: `C:\Windows\System32\termsrv.dll` (It probably doesn't matter if it's a real file, since it's just checking what it's set to)
> 
> Then after that I was able to do a clean installation:
> 
> And yes, A new rdpwrap.dll is generated and the registry is updated to this path.
> 
> Then use: Using an autoupdate.bat file for getting the latest ini file updates.
> 
> Everything is working again for me. Just need to backup rdpwrap.dll, and find out why Windows deleted it. (I did try to add it to my exclusions, but still managed to disappear)
> 
> I hope this helps someone!

![image](https://github.com/user-attachments/assets/497f9a2e-fdef-4b8a-8631-6ab3d144272a)
I am not finding this file to edit. Please show me how to do it?

**Comment by Killua0026** [comment]
> I had this working for about three days and Windows Anti-Virus decided to delete some important files. But I believe I have found a solution!
> 
> Why can i not just re-install the bloody thing? TermService can't start and gives me the same error message as listed above. But why? So lets investigate:
> 
> So I decided to review the code and found this:
> 
> **RDPWinst.dpr**
> 
> ```
> if not Reg.OpenKeyReadOnly('\SYSTEM\CurrentControlSet\Services\TermService\Parameters') then
>   begin
>     Reg.Free;
>     Code := GetLastError;
>     Writeln('[-] OpenKeyReadOnly error (code ', Code, ').');
>     Halt(Code);
>   end;
>   TermServicePath := Reg.ReadString('ServiceDll');
>   Reg.CloseKey;
>   if (Pos('termsrv.dll', LowerCase(TermServicePath)) = 0)
>   and (Pos('rdpwrap.dll', LowerCase(TermServicePath)) = 0) then
>   begin
>     Reg.Free;
>     Writeln('[-] Another third-party TermService library is installed.');
>     Writeln('[*] ServiceDll: "', TermServicePath, '".');
>     Halt(ERROR_NOT_SUPPORTED);
>   end;
>  Reg.Free;
> 
>   Installed := Pos('rdpwrap.dll', LowerCase(TermServicePath)) > 0;`
> ```
> 
> So what we want to do is make the variable Installed evaluate to False. This is done by the software reading what's in the ServiceDll reg value.
> 
> If you open up the registry and navigate to:
> 
> ```
> Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters
> ServiceDll
> %ProgramFiles%\RDP Wrapper\rdpwrap.dll
> ```
> 
> Turns out this file rdpwrap.dll is deleted! Ouch! Using a Search program like Everything, I cannot find it anywhere on my system. So what the installation code does is looks for either rdpwrap.dll in the ServiceDll, or termsrv.dll. If it's empty, it will assume you installed some other 3rd party service.
> 
> So what I did was edit the value for 'ServiceDll' and set it to: `C:\Windows\System32\termsrv.dll` (It probably doesn't matter if it's a real file, since it's just checking what it's set to)
> 
> Then after that I was able to do a clean installation:
> 
> And yes, A new rdpwrap.dll is generated and the registry is updated to this path.
> 
> Then use: Using an autoupdate.bat file for getting the latest ini file updates.
> 
> Everything is working again for me. Just need to backup rdpwrap.dll, and find out why Windows deleted it. (I did try to add it to my exclusions, but still managed to disappear)
> 
> I hope this helps someone!

YOOO! THIS IS THE SOLUTION I'M LOOKING FOR THANKS!!!
