### ISSUE TITLE
win7 run install.bat  got error: " OpenKeyReadOnly error (code 0)." ?

### ISSUE THREAD

**Issue by gexiaopeng** [stascorp/rdpwrap#1089]
why  win7 run install.bat  got error: " OpenKeyReadOnly error (code 0)." ?

**Comment by robbak** [comment]
Judging by them error message, I'd say you didn't open an administrator cmd window to run it in. Open start menu, type 'cmd', then right click 'Command Prompt' and select 'run as administrator'. The install.bat should then run correctly.

Oh, I'd recommend copying the files to program files/rdpwrapper first - it's more neat if the files are there than in some folder on your desktop or downloads.

**Comment by gexiaopeng** [comment]
I worked out my problem by installing that reg entry:  https://github.com/stascorp/rdpwrap/issues/857
