### ISSUE TITLE
Win10 1903 - 18362.900

### ISSUE THREAD

**Issue by bobch45** [stascorp/rdpwrap#1091]
Hey, I'm running the build [Win10 Ver 1903 - OS build 18362.900] and after installing I get the listener state [not supported]

Does anyone have a fix for that?
Thank you :)
[
![Screenshot_1](https://user-images.githubusercontent.com/66838552/84524388-932ce200-ace2-11ea-96b0-0702cda202ea.jpg)
](url)

![Screenshot_2](https://user-images.githubusercontent.com/66838552/84524492-bb1c4580-ace2-11ea-9d19-119c8965417a.jpg)

**Comment by tisc0** [comment]
+1

**Comment by tisc0** [comment]
Actually this one helped me well #1087

**Comment by bobch45** [comment]
Thank you :+1:
