### ISSUE TITLE
RDP wrapper is 'not supported' on Win 10

### ISSUE THREAD

**Issue by balazstrasy** [stascorp/rdpwrap#1094]
Hi,  I just want to use RDP wrapper but RDPConf says not supported. I downloaded the latest ini file rdpwrap_10.0.18363.476_1909 and put them into C:\Program Files\RDP Wrapper and  computer was restarted. It still not supported? What can I do for it?
thanks in advance, 

![image](https://user-images.githubusercontent.com/17971216/84591838-d6519700-ae41-11ea-8e43-3d477674a74a.png)

**Comment by pepepl** [comment]
I have the same service state version, here is a file. Just copy to installation folder
[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/4776340/rdpwrap.txt)
Change .txt to .ini

**Comment by balazstrasy** [comment]
> I have the same service state version, here is a file. Just copy to installation folder
> [rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/4776340/rdpwrap.txt)
> Change .txt to .ini

Nice, it works. Thanks. :)

Does DRP Wrap affect the original windows license? 
Can I use it officially?

**Comment by pepepl** [comment]
Yes, you can. One licence = one user. If you want to connect more users you must use CAL licences pre user :)

**Comment by balazstrasy** [comment]
Thi system is win 10 pro and not possible to install CAL license on this system. RDP clients (4-5) are also win 10 pro.
