### ISSUE TITLE
Windows 8.1 6.3.9600.19628 

### ISSUE THREAD

**Issue by Win81User** [stascorp/rdpwrap#1099]
I am running a non-pro version of windows 8.1, I have downloaded the zipped version as the MSI one is blocked,  I updated my ini file with the below:
[6.3.9600.19628]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8A07D
LocalOnlyCode.x64=nopjmp
SingleUserPatch.x64=1
SingleUserOffset.x64=358E9
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=43EF5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=5C2E0
SLInitFunc.x64=New_CSLQuery_Initialize

6.3.9600.19628-SLInit]
bFUSEnabled.x64 =FA054
lMaxUserSessions.x64 =FA058
bAppServerAllowed.x64 =FA05C
bInitialized.x64 =FA060
bMultimonAllowed.x64 =FA064
bServerSku.x64 =FA068
ulMaxDebugSessions.x64=FA06C
bRemoteConnAllowed.x64=FA070

but I still get listner state not listening.  I restarted services with 

>RDPWInst -r
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Restarting...
[+] TermService found (pid 1928).
[*] Shared services found: CryptSvc, Dnscache, LanmanWorkstation, NlaSvc
[*] Terminating service...
[*] Starting CryptSvc...
[*] Starting Dnscache...
[*] Starting LanmanWorkstation...
[*] Starting NlaSvc...
[*] Starting TermService...
[+] Done.

and still no luck.  I put an exception in for defender for the dll as well.  Any suggestions?

**Comment by affinityv** [comment]
Square bracket missing  in your second INI section?

The new INI sections in an RDPWrap.ini file in the right directory?
(typically c:\program files\RDP Wrapper)

No other AV product installed, now or previously to take out RDP altogether?

**Comment by Win81User** [comment]
That was it. the square bracket
