### ISSUE TITLE
KB intermittently outputting in wrong user session

### ISSUE THREAD

**Issue by tiredckc** [stascorp/rdpwrap#110]
Win 10 Pro, rdpwrap 1.6 with patch, office 2010, myob 19.11 - have tried OS reload, same problem.

Users (3 concurrent) will seemingly lose KB control only to find their keystrokes coming out in another session assuming the other session has focus on something the keyboard can type into (text field).  

This can last for a few seconds to a few minutes.

Happens sometimes a few times a day or a few times an hour - varies.

This has apparently been a problem since upgrade to Win10 from Win7 around xmas.

**Comment by tiredckc** [comment]
Update: seems to be when users are typing in MYOB it comes up in IE, if they use Edge this doesn't seem to happen... today will be a test for that theory.

**Comment by binarymaster** [comment]
Obviously this issue isn't related to RDP Wrapper, because its code doesn't have control over user sessions.

However this can be Terminal Services bug.

**Comment by Zenida89** [comment]
I've the same issue. Rarely, when I focus the input in a browser textbox (eg. Chrome), but not all kinds of textboxes, I receive input from another account who is writing elsewhere.
They can't type in their field and the text appears just in my textbox (usually in a web brower). Obviously, it happens viceversa also.

I tried to use the Kaspersky virtual keyboard (it should be secure), but I got same result.

**Comment by tjcomserv** [comment]
Did you have any joy sorting this, as it seems like it only does it when connecting to banking / accounting websites. Sounds like a hack to me

**Comment by Zenida89** [comment]
Now also MS Edge is doing the same thing. It happens in Password fields on browsers. If I change the field type using the "developer tools" from type="password" to type="text"

Sounds like a keylogger to me too

I ask an explaination from the developer

**Comment by binarymaster** [comment]
> Sounds like a keylogger to me too. I ask an explaination from the developer

No keyloggers here, check out the source code (and build binaries from it, if you don't trust compiled binaries).

Better ask Microsoft support for their bugs.

**Comment by rhinterndorfer** [comment]
I can reproduce the problem on a Windows 8.1 64 bit system with recent updates. It happens with all web browsers (IE, Firefox and Chrome). When user of the physical computer has a web browser on top and remote user types something the input is send to the browser on top in the console session. I have tested the same setup on a Windows 10 Pro and Home 64 bit and there this problem does not occur. I have no second Windows 8 system to reproduce the problem.

**Comment by binarymaster** [comment]
Btw. this could be also a bug in specific keyboard driver.

**Comment by Zenida89** [comment]
I don't know if is a bug related to the generic keyboard driver, but is very annoying, since now Edge is affected too. Should be useful a workaround to avoid this kind of behavior

**Comment by rhinterndorfer** [comment]
I have done a Windows 8.1 setup within a VM and testet some configurations. I have now found out, that G DATA TOTAL SECURITY is causing this behaviour. When I disable "Keylogger protection" within G Data the problem disappears.

**Comment by Zenida89** [comment]
I'm using Kaspersky internet security. I'll try to check for a similar option.
