### ISSUE TITLE
Win 10 Pro 19041.329 Fully supported but not working

### ISSUE THREAD

**Issue by Beafke** [stascorp/rdpwrap#1101]
I have updated Windows 10 Pro x64 to the 2004 build (19041.329)

Updated RDP Wrapper:
![RDP Wrap 01](https://user-images.githubusercontent.com/67290684/85329263-75c1fa00-b4d2-11ea-9fc9-4b0882d2af6e.jpg)

Usually the update of the .ini file was enough, but some how something else is needed. 

When i try to login in it sais:
![RDP Wrap 02](https://user-images.githubusercontent.com/67290684/85329352-a30ea800-b4d2-11ea-982e-fcc3d0b2534f.jpg)

The number of connections on this computer is limited and all connections are in use. Try again later etc.

Any suggestions on how to fix this?

Cheers

**Comment by JD10NN3** [comment]
Did you tried #1105, it worked perfectly for me after a reboot.

**Comment by Zynth-dev** [comment]
> I have updated Windows 10 Pro x64 to the 2004 build (19041.329)
> 
> Updated RDP Wrapper:
> ![RDP Wrap 01](https://user-images.githubusercontent.com/67290684/85329263-75c1fa00-b4d2-11ea-9fc9-4b0882d2af6e.jpg)
> 
> Usually the update of the .ini file was enough, but some how something else is needed.
> 
> When i try to login in it sais:
> ![RDP Wrap 02](https://user-images.githubusercontent.com/67290684/85329352-a30ea800-b4d2-11ea-982e-fcc3d0b2534f.jpg)
> 
> The number of connections on this computer is limited and all connections are in use. Try again later etc.
> 
> Any suggestions on how to fix this?
> 
> Cheers

Similar issue here.
New windows installation, updated to same windows version.
Installed rdpwrap. Updated ini from #1105 . Rebooted.

![Annotation 2020-06-26 202612](https://user-images.githubusercontent.com/44590222/85889216-51745f00-b7eb-11ea-8769-b54a4e20fc04.png)

But when trying to log in, exact same issue as @Beafke

**Comment by Mimi-fi** [comment]
when trying to log in, exact same issue as @Beafke
Windows10 2004，x64，企业版

**Comment by evandrix** [comment]
me too ✋

**Comment by robbak** [comment]
Take a look at issue #1096 . The 'number of connections is limited' error
is quite common, and there are a number of posts suggesting solutions - it
isn't a simple error, however, and does not seem related to rdpwrapper -
there are a number of causes, and it is a problem with stock rdp too.

**Comment by Mimi-fi** [comment]
> Take a look at issue #1096 . The 'number of connections is limited' error
> is quite common, and there are a number of posts suggesting solutions - it
> isn't a simple error, however, and does not seem related to rdpwrapper -
> there are a number of causes, and it is a problem with stock rdp too.
> …

I test them #1096 , but , aftert reboot PC, "Service state" and "Listener state" turn red , I tried "uninstall.bat" and "install.bat" and changed "rdpwrap.ini" , turn green , "The number of connections on this computer is limited and all connections are in use."

**Comment by HarmHoeksema** [comment]
I initially also had "fully supported" but limited number of connections.

After setting autoupdate properly everything updated correctly on pc restart and it **seemed to work!**
https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

(before I was trying to update manually with "net stop termservice" as cmd admin)

My working current directory looks like this:
![image](https://user-images.githubusercontent.com/60991890/87242962-e012ee00-c431-11ea-8e10-6e7b8324fb8e.png)

**Comment by faith-tang** [comment]
@Mimi-fi 
how bout your企业版？working?兄弟

**Comment by Mimi-fi** [comment]
> @Mimi-fi
> how bout your企业版？working?兄弟

No,so I choose 家庭版

**Comment by strarsis** [comment]
Was able to fix it using some INI from another user - but `RDPConf.exe` incorrectly indicates an unsupported version, see https://github.com/stascorp/rdpwrap/issues/1054#issuecomment-742637185.

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/872
