### ISSUE TITLE
Rdp check.exe

### ISSUE THREAD

**Issue by whitehat9090** [stascorp/rdpwrap#1102]
hello!
I want to remove the follow window when rdp_check.exe run.
![warning](https://user-images.githubusercontent.com/62291551/85565141-bb221c80-b5e3-11ea-8488-67dc39b75acf.png)

**Comment by JD10NN3** [comment]
Take a look at the Pull Request #1107, This should resolve your issue.

**Comment by infiniti25** [comment]
This is definitely a good response, it removed that screen for me 👍

**Comment by sebaxakerhtc** [comment]
Compile this project by yourself without this ActiveX warning
