### ISSUE TITLE
Blocked by antivirus checking, can't install

### ISSUE THREAD

**Issue by gotouchgo** [stascorp/rdpwrap#1112]
Any solution for this? Is this intentional by Windows built-in antivirus software?

**Comment by robbak** [comment]
I haven't had it blocked myself, but antivirus software often flags on anything that modifies how system files work. Easy to fix - just disable the antivirus protection while you install, then mark the files as exceptions. 

    Go to Start > Settings > Update & Security > Windows Security > Virus & threat protection.
    Under Virus & threat protection settings, select Manage settings, and then under Exclusions, select Add or remove exclusions.
    Select Add an exclusion, and then select from files, folders, file types, or process.

**Comment by gotouchgo** [comment]
Unfortunately it now is in a state that shows installed, but can't be uninstalled, due to some file can't run.
Well anyhow I don't need it now.

**Comment by flooxo** [comment]
> Unfortunately it now is in a state that shows installed, but can't be uninstalled, due to some file can't run.

Any solutions for this?
