### ISSUE TITLE
Local Mouse Wheel Input Affects Remote User

### ISSUE THREAD

**Issue by patchrick84** [stascorp/rdpwrap#1114]
I'm not even sure if this is an issue with RDP Wrapper or something else, but maybe I can get some guidance either way.

I have RDP Wrapper (version 1.5.0.0 according to the config screen) installed on Windows 10 Pro Version 1909.  It's running on an Intel NUC, not that that should really matter.  My wife and I are both working from home and signed into the computer - hence the need for this software.  She's logged in directly to the machine using a physical keyboard and mouse connected to it.  I remote in to my own local user account via RDP from my Mac.  It mostly works fine.  Today I noticed that once in a while my mouse would seemingly scroll by itself.  I thought it was just some weirdness going on between the Mac and the RDP client, or whatever.  But then it seemed really natural like someone scrolling through a webpage.  So I yelled over to her and asked if she was scrolling her mouse, she said yeah.  I said "scroll up" and she did, and my webpage also moved in my remote session.

So, it would appear that for some reason the local mouse wheel movements are affecting both the local and remote sessions.  Any ideas how to stop that from happening?  No other mouse or keyboard input seems to carry over.  For what it's worth, I have Logitech Options installed for her wireless mouse and keyboard.  Don't know if that would have any effect or not.

Thanks in advance for the help.

![image](https://user-images.githubusercontent.com/56691001/86642434-e3c5f100-bfa9-11ea-8331-0a090d303449.png)
![image](https://user-images.githubusercontent.com/56691001/86642492-efb1b300-bfa9-11ea-89f5-4c242fc39216.png)

**Comment by robbak** [comment]
Before we go chasing hosts, are you using a wireless mouse too? Could you
possibly be getting interference from her mouse?

**Comment by patchrick84** [comment]
Ha!  I hadn't even thought of that.  That would've really been something.  But I don't think that's it since mine is connected via Bluetooth and hers via Unifying receiver.  And the fact that it's ONLY the scrolling seems like it would rule that out too.

**Comment by s0nic9** [comment]
is TeamViewer running on host ? it's known issue with TeamViewer doesn't support concurrent sessions, there are many interacts with other sessions.
or another remote software ?

**Comment by patchrick84** [comment]
Negative on the TeamViewer.  We had run that recently so she could get support from her IT department, but never installed it.  Only ran it that once.  The issue existed before and after that.

I think the problem has to do with Logitech Options.  I killed the associated processes that were running in my session, but left the ones for hers, and the phantom scrolling seems to have stopped.  I'm gonna monitor it for a few more days before deeming it solved, though.

**Comment by tvcat** [comment]
It could be the Logitech software installed, try removing that and you do not need the software if you do not use the extra feature.

**Comment by patchrick84** [comment]
Okay, so after another week has gone by I can confirm that this is caused by Logitech Options.  I've had no recurrence of the "phantom" scrolling so long as I keep those two processes (LogiOptions.exe and LogiOptionsMgr.exe) closed on the remote session's user.  

Thanks for all the suggestions.  Hopefully this post will be useful to someone else in the future.

**Comment by akshayagrwl** [comment]
Same issue and the same solution worked. Thanks
I just uninstalled logitechoptions from the rdp server
