### ISSUE TITLE
Please add support for Win10 Pro terminal server 10.0.18362.836

### ISSUE THREAD

**Issue by sms2000** [stascorp/rdpwrap#1115]
Hi
Any plans to support the Win 10 Pro Terminal Service v. 10.0.18362.836 ?

Thanks

**Comment by robbak** [comment]
Done. #1085 

Please check active pull requests before opening issues.

I believe that @asmtron's .ini file is complete - https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini

**Comment by DennisonWilliams** [comment]
I was able to use @asmtron's .ini as suggested above and RDConf.exe shows that it is fully supported, but the functionality does not work.  Whenever attempting an RDP session there is a prompt that another user is connected, and then the other session is disconnected once the connecting session is established.

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083
