### ISSUE TITLE
Fully supported but Not listening

### ISSUE THREAD

**Issue by EdithCGeng** [stascorp/rdpwrap#1116]
![image](https://user-images.githubusercontent.com/30523974/87113740-909db800-c2a1-11ea-8349-4240e7cafa68.png)
I'd like connect to this computer from another. How can I make it work?
when updating .ini, I noticed an error..
![image](https://user-images.githubusercontent.com/30523974/87117609-90a2b580-c2ab-11ea-91c9-ce949289e874.png)

**Comment by sebaxakerhtc** [comment]
TermService not started.
Look for the solution here https://github.com/stascorp/rdpwrap/issues/1883
