### ISSUE TITLE
Windows 10 10.0.19041.330

### ISSUE THREAD

**Issue by princepsycho** [stascorp/rdpwrap#1123]
Need rdpwrap.ini offset for this version of windows please,

**Comment by travismailsa** [comment]
See if that INI helps you
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/4946424/rdpwrap.zip)

**Comment by princepsycho** [comment]
No, still looking for this guys, can someone reverse enginer and get right offset for this version of windows ?????????????

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1004
