### ISSUE TITLE
OS build 18362.959 isn't supported?

### ISSUE THREAD

**Issue by GWAM** [stascorp/rdpwrap#1127]
Hi,
I have struggled with this for the longest time, I have OS build 18362.959, I followed all the instructions carefully including installing the INI file and trying some of the suggestions from the issues reported previously, but no luck.

When running the RDPConf.exe I get Listener state: Not listening and [not supported]
Any ideas?

Thanks in advance!

**Comment by princepsycho** [comment]
Add this in ini file.

[10.0.18362.959]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FC5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.959-SLInit]
bInitialized.x64 =F6A8C
bServerSku.x64 =F6A90
lMaxUserSessions.x64 =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64 =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64 =F6AAC

**Comment by affinityv** [comment]
Updated my [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file, thank you @princepsycho

**Comment by GWAM** [comment]
Hi 

> Add this in ini file.
> 
> [10.0.18362.959]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=82FC5
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0DBFC
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=1FE15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=22DDC
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.18362.959-SLInit]
> bInitialized.x64 =F6A8C
> bServerSku.x64 =F6A90
> lMaxUserSessions.x64 =F6A94
> bAppServerAllowed.x64 =F6A9C
> bRemoteConnAllowed.x64=F6AA0
> bMultimonAllowed.x64 =F6AA4
> ulMaxDebugSessions.x64=F6AA8
> bFUSEnabled.x64 =F6AAC

I added into the INI, restarted the termservice but still same issue, RDPConf shows:
Wrapper state: Installed                 ver. 1.5.0.0
Service state: Running                    ver. 10.0.18362.836 (strange that Windows actually shows a different build? 959) 
Listener state: Not listening            [not supported]

Any other ideas? thanks
M

**Comment by princepsycho** [comment]
> Hi
> 
> > Add this in ini file.
> > [10.0.18362.959]
> > LocalOnlyPatch.x64=1
> > LocalOnlyOffset.x64=82FC5
> > LocalOnlyCode.x64=jmpshort
> > SingleUserPatch.x64=1
> > SingleUserOffset.x64=0DBFC
> > SingleUserCode.x64=Zero
> > DefPolicyPatch.x64=1
> > DefPolicyOffset.x64=1FE15
> > DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> > SLInitHook.x64=1
> > SLInitOffset.x64=22DDC
> > SLInitFunc.x64=New_CSLQuery_Initialize
> > [10.0.18362.959-SLInit]
> > bInitialized.x64 =F6A8C
> > bServerSku.x64 =F6A90
> > lMaxUserSessions.x64 =F6A94
> > bAppServerAllowed.x64 =F6A9C
> > bRemoteConnAllowed.x64=F6AA0
> > bMultimonAllowed.x64 =F6AA4
> > ulMaxDebugSessions.x64=F6AA8
> > bFUSEnabled.x64 =F6AAC
> 
> I added into the INI, restarted the termservice but still same issue, RDPConf shows:
> Wrapper state: Installed ver. 1.5.0.0
> Service state: Running ver. 10.0.18362.836 (strange that Windows actually shows a different build? 959)
> Listener state: Not listening [not supported]
> 
> Any other ideas? thanks
> M

Hi,

on Which version of windows are you trying to install rdpwrap ? 10.0.18362.836  ? if yes use this ini file :

[10.0.18362.836]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FC5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.836-SLInit]
bInitialized.x64 =F6A8C
bServerSku.x64 =F6A90
lMaxUserSessions.x64 =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64 =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64 =F6AAC


The ini file i posted is for version 959 not for version 836.

**Comment by GWAM** [comment]
> > Hi
> > > Add this in ini file.
> > > [10.0.18362.959]
> > > LocalOnlyPatch.x64=1
> > > LocalOnlyOffset.x64=82FC5
> > > LocalOnlyCode.x64=jmpshort
> > > SingleUserPatch.x64=1
> > > SingleUserOffset.x64=0DBFC
> > > SingleUserCode.x64=Zero
> > > DefPolicyPatch.x64=1
> > > DefPolicyOffset.x64=1FE15
> > > DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> > > SLInitHook.x64=1
> > > SLInitOffset.x64=22DDC
> > > SLInitFunc.x64=New_CSLQuery_Initialize
> > > [10.0.18362.959-SLInit]
> > > bInitialized.x64 =F6A8C
> > > bServerSku.x64 =F6A90
> > > lMaxUserSessions.x64 =F6A94
> > > bAppServerAllowed.x64 =F6A9C
> > > bRemoteConnAllowed.x64=F6AA0
> > > bMultimonAllowed.x64 =F6AA4
> > > ulMaxDebugSessions.x64=F6AA8
> > > bFUSEnabled.x64 =F6AAC
> > 
> > 
> > I added into the INI, restarted the termservice but still same issue, RDPConf shows:
> > Wrapper state: Installed ver. 1.5.0.0
> > Service state: Running ver. 10.0.18362.836 (strange that Windows actually shows a different build? 959)
> > Listener state: Not listening [not supported]
> > Any other ideas? thanks
> > M
> 
> Hi,
> 
> on Which version of windows are you trying to install rdpwrap ? 10.0.18362.836 ? if yes use this ini file :
> 
> [10.0.18362.836]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=82FC5
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0DBFC
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=1FE15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=22DDC
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.18362.836-SLInit]
> bInitialized.x64 =F6A8C
> bServerSku.x64 =F6A90
> lMaxUserSessions.x64 =F6A94
> bAppServerAllowed.x64 =F6A9C
> bRemoteConnAllowed.x64=F6AA0
> bMultimonAllowed.x64 =F6AA4
> ulMaxDebugSessions.x64=F6AA8
> bFUSEnabled.x64 =F6AAC
> 
> The ini file i posted is for version 959 not for version 836.

Thanks @princepsycho , to clarify, my OS shows 10.0.18362.959, but RDPConf shows 10.0.18362.836
Regardless, I now have both entries in the INI file but RDPConf still shows not supported and not listening
Thoughts?
![OS Build](https://user-images.githubusercontent.com/4580094/88177142-5ebc1800-cbf6-11ea-9bb0-f9ff2a7a2541.PNG)
![RDPConf](https://user-images.githubusercontent.com/4580094/88177150-61b70880-cbf6-11ea-9c41-3f545608a764.PNG)

**Comment by princepsycho** [comment]
> > > Hi
> > > > Add this in ini file.
> > > > [10.0.18362.959]
> > > > LocalOnlyPatch.x64=1
> > > > LocalOnlyOffset.x64=82FC5
> > > > LocalOnlyCode.x64=jmpshort
> > > > SingleUserPatch.x64=1
> > > > SingleUserOffset.x64=0DBFC
> > > > SingleUserCode.x64=Zero
> > > > DefPolicyPatch.x64=1
> > > > DefPolicyOffset.x64=1FE15
> > > > DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> > > > SLInitHook.x64=1
> > > > SLInitOffset.x64=22DDC
> > > > SLInitFunc.x64=New_CSLQuery_Initialize
> > > > [10.0.18362.959-SLInit]
> > > > bInitialized.x64 =F6A8C
> > > > bServerSku.x64 =F6A90
> > > > lMaxUserSessions.x64 =F6A94
> > > > bAppServerAllowed.x64 =F6A9C
> > > > bRemoteConnAllowed.x64=F6AA0
> > > > bMultimonAllowed.x64 =F6AA4
> > > > ulMaxDebugSessions.x64=F6AA8
> > > > bFUSEnabled.x64 =F6AAC
> > > 
> > > 
> > > I added into the INI, restarted the termservice but still same issue, RDPConf shows:
> > > Wrapper state: Installed ver. 1.5.0.0
> > > Service state: Running ver. 10.0.18362.836 (strange that Windows actually shows a different build? 959)
> > > Listener state: Not listening [not supported]
> > > Any other ideas? thanks
> > > M
> > 
> > 
> > Hi,
> > on Which version of windows are you trying to install rdpwrap ? 10.0.18362.836 ? if yes use this ini file :
> > [10.0.18362.836]
> > LocalOnlyPatch.x64=1
> > LocalOnlyOffset.x64=82FC5
> > LocalOnlyCode.x64=jmpshort
> > SingleUserPatch.x64=1
> > SingleUserOffset.x64=0DBFC
> > SingleUserCode.x64=Zero
> > DefPolicyPatch.x64=1
> > DefPolicyOffset.x64=1FE15
> > DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> > SLInitHook.x64=1
> > SLInitOffset.x64=22DDC
> > SLInitFunc.x64=New_CSLQuery_Initialize
> > [10.0.18362.836-SLInit]
> > bInitialized.x64 =F6A8C
> > bServerSku.x64 =F6A90
> > lMaxUserSessions.x64 =F6A94
> > bAppServerAllowed.x64 =F6A9C
> > bRemoteConnAllowed.x64=F6AA0
> > bMultimonAllowed.x64 =F6AA4
> > ulMaxDebugSessions.x64=F6AA8
> > bFUSEnabled.x64 =F6AAC
> > The ini file i posted is for version 959 not for version 836.
> 
> Thanks @princepsycho , to clarify, my OS shows 10.0.18362.959, but RDPConf shows 10.0.18362.836
> Regardless, I now have both entries in the INI file but RDPConf still shows not supported and not listening
> Thoughts?
> ![OS Build](https://user-images.githubusercontent.com/4580094/88177142-5ebc1800-cbf6-11ea-9bb0-f9ff2a7a2541.PNG)
> ![RDPConf](https://user-images.githubusercontent.com/4580094/88177150-61b70880-cbf6-11ea-9c41-3f545608a764.PNG)

Ignore this, just edit ini file and install rdpwrap by this way,

Go on folder containing file, open cmd, and do "rdpwinst.exe -i"

**Comment by affinityv** [comment]
AV can take it out, including ESET, TrendMicro and possibly others; even Windows Defender will take it out if it doesn't have an exception for the `C:\program files\RDP Wrapper` directory.

**Comment by GWAM** [comment]
Thanks a lot everyone, running the RDPWinst.exe -i in addition to adding the whole folder as exclude from Defender did the trick, this is now working, thanks!!

**Comment by zolymo** [comment]
Hello, u have an ini file for Windows 1909 Build 18363.959
![borrar](https://user-images.githubusercontent.com/8655032/88634385-ec2abc80-d07b-11ea-973d-08b72a79b6ec.png)

RDPWrap show Build 18362.836
![borrar2](https://user-images.githubusercontent.com/8655032/88634637-4035a100-d07c-11ea-9941-28e5e911b0e2.png)

Regards
