### ISSUE TITLE
software maybe infected

### ISSUE THREAD

**Issue by skip1965** [stascorp/rdpwrap#1131]
Hi guys,
few minutes ago I downloaded v 1.6.2 (but same with 1.6.1) and I received a security warning.

Thus I submitted to opentip.kaspersky.com you executables...

RDPConf + RDPWInst are reported as malicious contents ( more than one signature) !!!

Please let me know.

Best regards,
Skip1965

[security-issues-2020-07-23_01.pdf](https://github.com/stascorp/rdpwrap/files/4967874/security-issues-2020-07-23_01.pdf)
[security-issues-2020-07-23_02.pdf](https://github.com/stascorp/rdpwrap/files/4967875/security-issues-2020-07-23_02.pdf)

**Comment by justintubbs** [comment]
Same thing here just now

**Comment by affinityv** [comment]
False positives.... MS and AV vendors tend to knock tools that can be used for both good and evil; but wihout fairness to those tools that are typically 100% used for good.

**Comment by jgwinner** [comment]
This actually reduces security, honestly - because you don't pay attention to the warning because it's wrong so often. 

Good to know this software is safe.

**Comment by danwdart** [comment]
Chrome actively blocks downloads of these files itself. It makes it look really suspicious.

**Comment by dsbcpas** [comment]
> 
> 
> Chrome actively blocks downloads of these files itself. It makes it look really suspicious.

Interestingly enough, Github took this site down in May for a few weeks, then it popped back up without any mention of the event by the developer. Nothing in open and closed issues anyway.

At the time they were disconnected, I researched various "sandbox" analysis, and one showed a specific file that was accessing areas one would not expect.  Wish I had a screen print of that page (as I recall the file had been uploaded on May 6th), but I did verify that file was deleted when she came back up. If I locate those notes I will post them. I don't use rdpwrap, but watch it out of curiosity.

Here is a sandbox analysis, but it excludes the May 15th +- 2020 Github take down period: [https://www.hybrid-analysis.com/search?query=rdpwrap](https://www.hybrid-analysis.com/search?query=rdpwrap)

**Comment by sk-lau** [comment]
use Edge to download

**Comment by FlyingDutchman1965** [comment]
I am making an educated guess that the RDPWrap was suspended for one or both of a couple of reasons:

1) GitHub is now owned by MS, and RDPWRap could be seen as taking business away
2) Some posters on here, in an effort to help others, posted versions of termsrv.dll, which is a definite no-no.

As far as being malwar/virus etc, I also have to prevent McAfee from wiping RDPConf.exe. Doesn't mind RDPWinst.exe though.

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/277
