### ISSUE TITLE
https://github.com/independentcod/RDPWraper

### ISSUE THREAD

**Issue by ind3p3nd3nt** [stascorp/rdpwrap#1138]
Instructions on how to install are included.
If you are looking for another version the trick is the following:
search in this repo the Windows version and look in Issues then find the ini infos of your version and add it to the INI in the archive 
on my Github, then install it.

Another option is to fork my repo here:
https://github.com/independentcod/RDPWraper
and add your info directly in the ini file then download and install it
(I'd prefer it that way)

Good luck and have a NICE DAY!

Remi

**Comment by sebaxakerhtc** [comment]
Not an RDPWrapper issue
