### ISSUE TITLE
Active RDP session limit

### ISSUE THREAD

**Issue by MarioPeedor** [stascorp/rdpwrap#114]
This is not an issue, just a question.

If I have around 100 users in windows 10/8, is there a limit of active RDP connections that can logged in at same time using RDP wrapper?

Nice soft. Hope there would be one for Windows server!

**Comment by binarymaster** [comment]
There is no software limit on concurrent sessions, it only depends on hardware (amount of free RAM).

RDP Wrapper is compatible with any edition of Windows NT 6.0+, with server editions too.
