### ISSUE TITLE
10.0.17763.1397

### ISSUE THREAD

**Issue by Merodi** [stascorp/rdpwrap#1144]
10.0.17763.1397
After windows update - not supported.

**Comment by SCH48** [comment]
Work! 
https://github.com/stascorp/rdpwrap/files/5051549/rdpwrap_windows_server_2019_datacenter_10.0.17763.1369.zip
replace "C:\Program Files\RDP Wrapper\rdpwrap.ini" and then run cmd console "RDPWinst.exe -r" or restart windows

**Comment by affinityv** [comment]
Is 10.0.17763.1397 the Windows version for the termsrv dll with version 10.0.17763.1369 from `RDPConf.exe` ?

**Comment by Merodi** [comment]
Thank you Very Much ~

**Comment by VitalyLitvinov74** [comment]
thanks!
