### ISSUE TITLE
Version 10.0.16362.836 or 18363.1016

### ISSUE THREAD

**Issue by tipstar23** [stascorp/rdpwrap#1146]
Hi guys,

Have a couple of issues with pcs I have all ports open but can't connect.

Whats the right version?
![Annotation 2020-08-14 204106](https://user-images.githubusercontent.com/49510410/90242095-b81f0c00-de6f-11ea-825a-d3298d09770f.png)

**Comment by saocode** [comment]
Are you connecting to "remotehost:7020"?  The default port for RDP is 3389.  I assume that if you change it in the Wrapper Config, you will need to specify that change when making a client connection.

**Comment by affinityv** [comment]
The right INI version section is the one that `RDPConf.exe` gives you, so actually 10.0.18362.836 (unlike  the tread title).

**Comment by sk-lau** [comment]
Actually we just need to check the termsrv.dll version the OS build version does NOT matter

Check the version with the rdprwap.ini to see if it's supported

**Comment by tipstar23** [comment]
Hi, no its not supported in .ini file? thats .1016
