### ISSUE TITLE
Specified account already exists

### ISSUE THREAD

**Issue by zaccmarin** [stascorp/rdpwrap#1147]
I was installing rdpwrap with the msi installer and half way through my antivirus blocked it, and when trying again (with the antivirus off) i got the error message "specifeid account already exists".
The library file appears in my control panel but i cant uninstall it because there is no uninstall file to run.
![image](https://user-images.githubusercontent.com/41835647/90486138-71136e00-e130-11ea-93fc-5b2fa63e6072.png)
So how can i remove it to try the reinstall?
edit:
If i try to uninstall the RDP wrapper library i get this error:
![image](https://user-images.githubusercontent.com/41835647/90488939-8be7e180-e134-11ea-9c03-4390793ad23f.png)

**Comment by ZaccoTobacco** [comment]
And this come
