### ISSUE TITLE
Not Listening [not supported]

### ISSUE THREAD

**Issue by zaccmarin** [stascorp/rdpwrap#1148]
installed using zip bat file,
So after running the bat the listener is not supported?
![image](https://user-images.githubusercontent.com/41835647/90491952-8ab8b380-e138-11ea-89c4-9e55df3921de.png)

**Comment by affinityv** [comment]
You need 3rd party INI file, like mine [here](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini).
Then run `RDPWInst -r` to restart the RDP server.  Make sure that Windows Defender and/or other AV products have an exception for the "C:\Program Files\RDP Wrapper" directory.

**Comment by zaccmarin** [comment]
oh thanks
