### ISSUE TITLE
I updated windows to 17763.1432 1809  and now rdpwrap does not work! can anyone help me?

### ISSUE THREAD

**Issue by Dezmonsolitude** [stascorp/rdpwrap#1153]

**Comment by zzelalex** [comment]
What is the termsrv.dll version number?

**Comment by Dezmonsolitude** [comment]
10.0.17763.1369

**Comment by zzelalex** [comment]
Excellent, you solved the problem by yourself and this issue should be closed.
https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini

**Comment by Dezmonsolitude** [comment]
thanks

**Comment by strarsis** [comment]
Was able to fix it using some INI from another user - but `RDPConf.exe` incorrectly indicates an unsupported version, see https://github.com/stascorp/rdpwrap/issues/1054#issuecomment-742637185.
