### ISSUE TITLE
Listener State [not supported]

### ISSUE THREAD

**Issue by sipi41** [stascorp/rdpwrap#116]
I can not create a multiple session RDP.... Any idea on what to do in this case??

![image](https://cloud.githubusercontent.com/assets/688562/15249146/bc3c7b8e-18e3-11e6-85d9-c10b9aada1a9.png)

Please Help!!!

**Comment by BurnDownTheIgloo** [comment]
Run the updates. Had same problem yesterday, update seemed to fix it. Also run all bats and exes as administrator

**Comment by mauriciocapua** [comment]
turn off 'single session per user'
and run update.bat

**Comment by BurnDownTheIgloo** [comment]
Don't have to disable single session per user. Works for me with that on

**Comment by sipi41** [comment]
Thank you guys! knowledge is power for sure... :-)

**Comment by vibs2006** [comment]
Thanks a lot. My error was solved after **turn off** '**single session per user**'
and run update.bat
