### ISSUE TITLE
Insecure way to solve many connection issues

### ISSUE THREAD

**Issue by bertisLongfellow** [stascorp/rdpwrap#1162]
I was encountering difficulties getting RDP Wrapper working, Windows 10 Home 1909, 18363.1016.

One change that led to success was changing the account I was using to test to 'administrator' status. I assume this means my problem is related to policies, or a user group that doesn't exist in Windows Home?

It doesn't matter to my use case, I'm just curious what fix I overlooked.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1083
