### ISSUE TITLE
[Not Listening] on v.10.0.19041.84

### ISSUE THREAD

**Issue by 5h4rdy** [stascorp/rdpwrap#1165]
Hi,

Running an install on a new PC termserv v.10.0.19041.84 and ran standard install.bat, followed by autoupdate.bat using the latest version from asmtron which completes with the below results:

Automatic RDP Wrapper installer and updater

<check if the RDP Wrapper is up-to-date and working>

[+] TermService running.
[+] Found listener session: AllowTSConnection (ID: 1).
[+] Found windows registry entry for "rdpwrap.dll".
[+] Found file: "C:\Program Files\RDP Wrapper\rdpwrap.ini".
[+] Installed "termsrv.dll" version: 10.0.19041.84.
[*] Read last "termsrv.dll" version from the windows registry...
[+] Current "termsrv.dll v.10.0.19041.84" same as last "termsrv.dll v.10.0.19041.84".
[*] Start searching [10.0.19041.84] version entry in file "C:\Program Files\RDP Wrapper\rdpwrap.ini"...
[+] Found "termsrv.dll" version entry [10.0.19041.84] in file "C:\Program Files\RDP Wrapper\rdpwrap.ini".
[*] RDP Wrapper seems to be up-to-date and working...

however, when running rdpconf.exe I receive "Listener State: not listening".

Any clues?

Thanks in advance.

**Comment by affinityv** [comment]
Sure, the best clues are, make an exception with Windows Defender or whatever "AV / Security" product you choose to use; my view though is that you shouldn't be using ANY third party tool for AV / Security as those tend to provide both a false sense of security as well as more potential security holes.  Run as a standard user (not admin) for normal things, that alone will save you from most problems and for sure practice safe computing!

Oh, and you must have a trusted 3rd party [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file, the stock project one doesn't cover many if any versions of Windows in use today (or it shouldn't).

Please don't turn off Windows updates either, delay feature updates as long as you can, but you need security updates enabled as Microsoft is so bad that there is regularly many critical security fixes every month!

**Comment by TBoneTheOriginal** [comment]
Same issue here - I got it working by replacing the rdpwrap.ini file with this one:

https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini

**Comment by ThoseITGuys** [comment]
my issue was that it would want the remote user to kick off the local user.

I tried the INI suggest above but once implemented. the remote user (seperate account on the PC) logs in and the current local users screen changes to the remote user desktop and they cannot move or anything. They can watch what the remote user is doing but they cannot move until the remote user disconnects then they see their user desktop again

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1004
