### ISSUE TITLE
Support for 10.0.19041.84

### ISSUE THREAD

**Issue by badsantacode** [stascorp/rdpwrap#1166]
Hello! 
Thank you for the job, but my version is not supported. Could you update INI file with specific version? Thanks! 

![image](https://user-images.githubusercontent.com/49001975/93820793-591a9700-fc66-11ea-9092-862c12399a6c.png)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5258096/termsrv.zip)

**Comment by shangdev** [comment]
Have you solved it?

**Comment by badsantacode** [comment]
Yes, I was not enough attentive recently and didn't read another issues. I read solution and implemented updated CFG, all OK!
