### ISSUE TITLE
Multiple monitor support

### ISSUE THREAD

**Issue by ManiacDC** [stascorp/rdpwrap#117]
On the display tab, there is a setting to "Use all my monitors for the remote session". However, this setting only works when connecting to a RDP server that supports multiple monitors (basically, only on ultimate/enterprise versions of Windows). Can rdpwrap be made to enable this setting on other versions of windows?

**Comment by kbmorris** [comment]
Hi. rdpwrap does attempt to allow multiple monitor support in the Terminal Service. What version of the termsrv.dll is on your system that is not allowing this? You can answer this question by looking at the RDP Wrapper Configuration (rdpconf.exe) Service state and ver. line.

**Comment by ManiacDC** [comment]
I should have been clear... I haven't actually tried this with RDPWrap, as I no longer have dual monitors at home now. I just remember not being able to use this feature when I've wanted to in the past (before knowing about RDPWrap). I didn't see it documented, so I didn't think it was implemented.

If this is implemented, then that's great and you can consider this closed! Thanks!

**Comment by binarymaster** [comment]
RDP Wrapper probably allows multiple monitor usage:
[/res/rdpwrap.ini#L1](https://github.com/stascorp/rdpwrap/blob/1395ea22bb48df7cb73ed85d4b523982f153ab87/res/rdpwrap.ini#L1)
[/res/rdpwrap.ini#L1059](https://github.com/stascorp/rdpwrap/blob/1395ea22bb48df7cb73ed85d4b523982f153ab87/res/rdpwrap.ini#L1059)

But we need someone who tested this feature to confirm that.

**Comment by Lihis** [comment]
I'll test tomorrow

**Comment by ManiacDC** [comment]
OK, I actually have a 2nd PC at home that has dual monitors... I tested it by remoting to my main PC and it works great. Thanks!
