### ISSUE TITLE
Windows 10 Home 1903 Build 18362.1082

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#1173]
Is this RDPWrap_ini_Updater a fix for my version OS and RDPWrapper?

Wrapper State: Installed
Service State: Running
Listener State: **_Not Listening_ Not Supported**

Version: 1.5.0.0
Ver: 10.0.18362.836

![RDP Wrapper Conf](https://user-images.githubusercontent.com/72182870/94770850-87852a00-036a-11eb-97ab-dc7afbd217e1.jpg)

**Comment by Iskandare** [comment]
I am also waiting for a patch for version 18363 1082
thank you !

**Comment by ryryonline** [comment]
This worked for me: https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini

**Comment by Freddd13** [comment]
> This worked for me: https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini
@ryryonline
Thanks! It really works.

**Comment by Freddd13** [comment]
> This worked for me: https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini

@ryryonline 
It really works. Thanks a lot!

**Comment by Kurisu1129** [comment]
> This worked for me: https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini

thanks a lot ! It works on my pc.

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083
