### ISSUE TITLE
Windows 10 Enterprise N - 1903 Build 18362.30 - NOT SUPPORTED 

### ISSUE THREAD

**Issue by amin137398** [stascorp/rdpwrap#1174]
hi 
I'm trying to use RDP WRAPPER on my windows 10 PCs and it was working fine with most of them . but in 1 case although everything seems to be similar to the other PCs ( windows version and build are the same ) but RDP WRAPPER is not working no matter what i do! 
I've aldeary tried replacing ini file or updating RDP WRAPPER but that didin't help . here is the information you might ask for : 
![rpd](https://user-images.githubusercontent.com/27921772/94987960-dacbc800-0576-11eb-87e3-0b840ca01d97.png)

**Comment by robbak** [comment]
affinityv's ini file supports that version


https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini

asmtron's does to:

https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini

**Comment by amin137398** [comment]
> affinityv's ini file supports that version https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini asmtron's does to: https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini
> […](#)

Dear robbak thanks for your quick reply 
I tried these 2 files and the status change from not supported to FULLY SUPPORTED but after installation with these new ini files my remote desktop service stops working and I can't start it again from windows service manager 
is there any specific installation steps I should follow ?

**Comment by amin137398** [comment]
------------------------------------------
Sorry it was my mistake . I had to copy the text in the link but I downloaded the link instead and got a 1.5 MB ini file that's why it was not working . 
It is working fine with the new ini files provided in the link : 
https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini
