### ISSUE TITLE
Concurrent Multiple Loopback Remote Desktop Session from same PC.

### ISSUE THREAD

**Issue by Spamm00r** [stascorp/rdpwrap#1175]
Hi,

I have enabled concurrent Remote Desktop and also allowed multiple logins for the same user. It works if the additional connection is made from another device.

But I want to connect to the second session from the same PC. Not necessarily to the same User account but from the same physical PC.

For example: 

1. I login phyiscially to User1

2. I open RDP and login via RDP to User1 from the same PC.

Is that possible to achieve?  If not, why is this not possible and are there ways around it?

The only limitation I have observed is that the second connection can not be from the same PC. otherwise the second or additional connection works just fine.

**Comment by redneck-f25** [comment]
Have you tried to connect to 127.1.1.2 or some other address within
127.0.0.0/8?

Spamm00r <notifications@github.com> schrieb am Sa., 3. Okt. 2020, 18:59:

**Comment by Spamm00r** [comment]
I tried with 127.0.0.2 and I get asked password, but the connection fails with error code 0x112f I think.

**Comment by redneck-f25** [comment]
https://stackoverflow.com/a/40607803/12674442

Cannot investigate more since i'm on vacation.

**Comment by Spamm00r** [comment]
I tried all the solutions suggested, lowering resolution and freeing memory. But the error remains. Occasionally it is not error 0x112f, then it is a gone without error code. But connections from a different PC work right away.

**Comment by Spamm00r** [comment]
If I try to connect from linux with rdesktop, I get disconnetc: Unknown reason.

**Comment by Spamm00r** [comment]
OK I have found the solution:

https://www.reddit.com/r/sysadmin/comments/gz6chp/rdp_issues_on_2004_update/

You have to disable the following two settings in Policy Editor:

Computer Configuration>Policies>Administrative Templates>Windows Components>Remote Desktop Services>Remote Desktop Session Host>Remote Desktop Session Environment

-Use hardware graphics adapters for all Remote Desktop Services Sessions

-Configure H.264/AVC Hardware encoding for Remote Desktop Connections

And now I can login the way I want it from Loopback.

Thanks For the Hint redneck-f25 !
