### ISSUE TITLE
Windows 10 2004 x86 only 5 Connections

### ISSUE THREAD

**Issue by SimpleCross45** [stascorp/rdpwrap#1176]
RDP is working, but only 5 Connections possible.
With the 6th Connection there is just this message:

![image](https://user-images.githubusercontent.com/72442225/95190179-32647080-07cf-11eb-91e0-30d0997a731b.png)

Windows 10 Pro 32Bit Version 2004.

Status :
![image](https://user-images.githubusercontent.com/72442225/95189930-d8fc4180-07ce-11eb-99d3-cd1c09bf0c9a.png)

ini from autoupdate.bat
[Main]
Updated=2020-08-14

**Comment by SimpleCross45** [comment]
Did a new Fresh install with Windows 10 Pro 64Bit Version 2004, did initial Setup with autoupdate.bat 
64Bit works without Problem, tested with 10 Connections
32Bit only 5 Connections

**Comment by SimpleCross45** [comment]
32bit 1809 windows 10 running fine , no Limit 
32bit 1903 and 1909 online 5 connections 
I did the Quick check with Stock termsrv.dll 

Any ideas what do do ? Anyone facing same issue?

**Comment by byservermps** [comment]
I'm also having the same problem, windows 10 x86 build 2004 and only 5 connections. Were you able to solve this problem?

**Comment by SimpleCross45** [comment]
no solution so far, but another information.
the 6.th Connections creates an Event in Windows protocolls - application
eventid 1001 : Windows Error Reporting

![image](https://user-images.githubusercontent.com/72442225/95653725-1b898b00-0afb-11eb-8437-02db4cc4d33c.png)

actually i dont know how to read These error reports, i'm working on it...

**Comment by nick7inc** [comment]
The lack of free memory - ?

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1004
