### ISSUE TITLE
Threat name: Trojan.GenericKD.44003828 in executable file

### ISSUE THREAD

**Issue by mata-r** [stascorp/rdpwrap#1179]
After all the warnings from the browser, once I execute the .msi file, I am getting McAfee and BitDefender critical alert because the file contains a trojan.

**Comment by robbak** [comment]
You have to broken antivirus programs. The file is fine, not it works by
using similar techniques to many viruses, so their brain dead automated
systems are triggered.

You can try reporting the false positive to them, but they aren't listening.

**Comment by mata-r** [comment]
Thanks
