### ISSUE TITLE
Cannot get 1.6 working on Win 10 Home

### ISSUE THREAD

**Issue by orangehand** [stascorp/rdpwrap#118]
Not listening Not supported. Please can someone point me?

**Comment by cowwoc** [comment]
@orangehand This is a terrible bug report. Please provide more details.

What did you try?
What were you expecting?
What output did you get instead?

**Comment by AllanYin** [comment]
This is Windows 10 Home.
RDPCheck could run, but cannot connected from other machine on the network.
Tried different port, did not work.
Checked the service and Listenner are running OK.
At least give some idea what to check next.
THX

**Comment by binarymaster** [comment]
@orangehand @AllanYin 
Make screenshot of your RDPConf, this will help us to detect the problem.

**Comment by robsoncombr** [comment]
+1

Mine was working perfectly. This happens after Windows 10 Home is upgraded to the latest version. It is not working anymore.

<img width="610" alt="captured" src="https://cloud.githubusercontent.com/assets/923997/15694661/1469e8c8-2776-11e6-9dce-cd31352fd653.png">

**Comment by robsoncombr** [comment]
-1

Good news... I clicked on: update.bat

From what I can see, it got updated to latest version, it is fully working and I can connect to the desktop now
![captured](https://cloud.githubusercontent.com/assets/923997/15694763/e6301328-2776-11e6-855a-26bdb3871d5a.png)

**Comment by mezzb** [comment]
same thing - sound answer here
https://github.com/stascorp/rdpwrap/issues/23#issuecomment-125948459

**Comment by binarymaster** [comment]
> Not listening Not supported.

In this situation ALWAYS run `update.bat` file. ONLY if this doesn't help, create an issue.

But... better to use [this](https://github.com/stascorp/rdpwrap/issues/79) thread.

**Comment by orangehand** [comment]
Sorted by running the update.bat - thanks
> On 1 Jun 2016, at 09:48, binarymaster <notifications@github.com> wrote:
> 
> Not listening Not supported.
> 
> In this situation ALWAYS run update.bat file. ONLY if this doesn't help, create an issue.
> 
> But... better to use this <https://github.com/stascorp/rdpwrap/issues/79> thread.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/stascorp/rdpwrap/issues/118#issuecomment-222931331>, or mute the thread <https://github.com/notifications/unsubscribe/AIrhq7s5yLXfMAW0IhX0XNWqU7X7HzgDks5qHUd3gaJpZM4ImV_w>.
> 


Regards
Nick Harvey
Orange Hand Systems, London & Wessex
** Enjoyable IT **

Computing, Networking, Telephony & Internet Solutions

http://www.orangehand.com
UK Local Call: +44 (0)330 223 2004
US Toll-free: +1-866 836 1737
VOIP: 30128172@voipfone.co.uk

Follow us on Twitter: @orange_hand
