### ISSUE TITLE
Is there a fix for 19401.508?

### ISSUE THREAD

**Issue by GWAM** [stascorp/rdpwrap#1180]
Hello,

I've been successful before with RDPWrap on a lower build, recently my computer went for a windows update without my permission :) and RDPWrap does not work anymore, I am now on:
Windows 10 Home
Version 2004
OS Build 19401.508

Is there a solution for this build?

Thanks!!

**Comment by bderiso** [comment]
I seem to be having the same problem on Windows 10 build 19401.450, RDP Service version 10.0.19041.84
Update: Fixed in https://github.com/stascorp/rdpwrap/issues/1142

**Comment by bderiso** [comment]
@GWAM does the fix in https://github.com/stascorp/rdpwrap/issues/1142 work for you?

**Comment by GWAM** [comment]
No, it doesn't, I even tried uninstalling and re-installing RDPWrap, no luck, the INI does not have an entry for 19401, not sure if anyone else if facing the same issue?

**Comment by KcinDB** [comment]
try this
https://github.com/stascorp/rdpwrap/issues/1163

**Comment by MartinRGB** [comment]
> #1163

works for me

**Comment by GWAM** [comment]
I can confirm [#1163 ] resolved my issue
