### ISSUE TITLE
Remote server does not allows more than 2 connections

### ISSUE THREAD

**Issue by alesribic73** [stascorp/rdpwrap#1181]
I use rdpwrap on server2019. I have added users, but when i try to connect 3rd user it says that there are too many users connected. i can just throw any of 2 users off the machine.

Any suggestions

**Comment by affinityv** [comment]
Exlcusions with Windows Defender?  Or other AV  "security" product interference?

**Comment by alesribic73** [comment]
I will try. Im using Windows Defender. I have set an exception to RDPWrapper folder.

**Comment by alesribic73** [comment]
Same thing. Only 2 concurrent sessions allowed. Any suggestions?

**Comment by alesribic73** [comment]
Solved... Even if Config shows me all ok, i have to restart termservice. I try inside services window, but  it did not work! then i use CMD "net stop termservice" and then "net start termservice" and it starts to work!
