### ISSUE TITLE
Version 10.0.18362.836

### ISSUE THREAD

**Issue by Montclair** [stascorp/rdpwrap#1187]
I get an error whenever I try to connect with this version, despite manually entering that info the .ini file and everything saying it's ready to go and running.  I suspect the offsets are wrong.  Is there an update for this version with correct offsets?

**Comment by Montclair** [comment]
So this project is apparently dead, then.

**Comment by robbak** [comment]
No, but you said you got "an error" without telling is what the error was,
and your said you manually entered some random offsets, without telling is
what they were, and which you shouldn't do anyway. We don't like having to
play 20 questions to work out what is wrong.

Search and read other posts here before posting new queries, because i can
guarantee that whatever your problem is, others have had and fixed it
before you.

**Comment by Montclair** [comment]
Actually, I have read the other posts.  I always do before posting.  There's nothing anywhere for this version that I can find.  I need the correct offsets for this version of termserv.dll, that's all, and that will presumably resolve the error.  I didn't make note of it specifically, which is why I didn't include it, as the correct offsets should resolve it, IMO.  

I've retested and the RDPCheck error is "Unknown code 0x4".  Very informative.  All indicators are green.  Actual remote attempts to connect are not successful.  I've tried within the same LAN to rule out NAT issues.  The ini file addition I made was using the latest offsets I could find here.

[10.0.18362.836]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B7D06
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FB5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=50535
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=50269
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=5A77A
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.836-SLInit]
bInitialized.x86 =D577C
bServerSku.x86 =D5780
lMaxUserSessions.x86 =D5784
bAppServerAllowed.x86 =D578C
bRemoteConnAllowed.x86=D5790
bMultimonAllowed.x86 =D5794
ulMaxDebugSessions.x86=D5798
bFUSEnabled.x86 =D579C
bInitialized.x64 =F6A8C
bServerSku.x64 =F6A90
lMaxUserSessions.x64 =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64 =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64 =F6AAC

**Comment by robbak** [comment]
affinityv's file covers that version.
https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini


Errors like that are common when people try to edit their own .ini files.

Lastly, make sure that when you download a file, you end up with dos-style
line endings, non linux. Easiest way to ensure that is to use asmtron's
autoupdate.bat tool -
https://github.com/asmtron/rdpwrap/blob/master/autoupdate.zip

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1083
