### ISSUE TITLE
Windows 10 version: 20H build: 19042.572

### ISSUE THREAD

**Issue by Sharpik** [stascorp/rdpwrap#1188]
rdpwrap.ini needs to be updatet to work on the last windows version (2020 10.21.).

**Comment by Sharpik** [comment]
It seems that this rdpwrap.ini from Asmtron fork work
[https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini](https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini)

**Comment by sk-lau** [comment]
> It seems that this rdpwrap.ini from Asmtron fork work
> https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini

It does not and should not work. There's no offset entry for October 2020 update. No 19042.572 in the rdpwrap.ini
Anyone has any ideas?

**Comment by sk-lau** [comment]
> > It seems that this rdpwrap.ini from Asmtron fork work
> > https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini
> 
> It does not and should not work. There's no offset entry for October 2020 update. No 19042.572 in the rdpwrap.ini
> Anyone has any ideas?

This .ini is only  for April 2004 update or known as 20H1 . However October update is 20H2

**Comment by Champion1971** [comment]
10.0.19041.84 works (dont know why). It's fully supported

**Comment by mabaega** [comment]
Win10 Pro 
Version 20H2 (OS Build 19042.572)

@affinityv Updated=2020-10-16
https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini

Working
https://ibb.co/GxHZwYR

**Comment by pcalpha** [comment]
The termsrv.dll of Version 20H2 is the same to 19041 right now.

**Comment by sk-lau** [comment]
> The termsrv.dll of Version 20H2 is the same to 19041 right now.

You are right so it actually solved this so called problem

**Comment by shamilsun** [comment]
19042.572
not working

**Comment by strarsis** [comment]
@shamilsun: Try the workaround in https://github.com/stascorp/rdpwrap/issues/1223

**Comment by pcaste2000** [comment]
> Win10 Pro
> Version 20H2 (OS Build 19042.572)
> 
> @affinityv Updated=2020-10-16
> https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini
> 
> Working
> https://ibb.co/GxHZwYR

Hi! Sure it works on version 10.0.19041.84 (I saw it on your uploaded pic) but (I don't know why) my version is 10.0.19041.662 and it isn't working at all .

Any ideas? Thanks so much in advance.

**Comment by pcaste2000** [comment]
> > Win10 Pro
> > Version 20H2 (OS Build 19042.572)
> > @affinityv Updated=2020-10-16
> > https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini
> > Working
> > https://ibb.co/GxHZwYR
> 
> Hi! Sure it works on version 10.0.19041.84 (I saw it on your uploaded pic) but (I don't know why) my version is 10.0.19041.662 and it isn't working at all .
> 
> Any ideas? Thanks so much in advance.

Patched by now: I unistalled the KB4586853 update and after rebooting I went back to version 10.0.19041.84. Then I got [fully supported]. Not a smart solution, but enough by now.

**Comment by pcaste2000** [comment]
> > > Win10 Pro
> > > Version 20H2 (OS Build 19042.572)
> > > @affinityv Updated=2020-10-16
> > > https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini
> > > Working
> > > https://ibb.co/GxHZwYR
> > 
> > 
> > Hi! Sure it works on version 10.0.19041.84 (I saw it on your uploaded pic) but (I don't know why) my version is 10.0.19041.662 and it isn't working at all .
> > Any ideas? Thanks so much in advance.
> 
> Patched by now: I unistalled the KB4586853 update and after rebooting I went back to version 10.0.19041.84. Then I got [fully supported]. Not a smart solution, but enough by now.

Solved: I found all .ini versions at: https://github.com/sebaxakerhtc/rdpwrap.ini (thanks to the user, nice work!)

**Comment by strarsis** [comment]
@sebaxakerhtc: For whatever reasons I get a Chrome security warning (red screen) when visiting the `rdpwrap.ini` in your GitHub fork.

**Comment by holmrn1** [comment]
> 
> 
> It seems that this rdpwrap.ini from Asmtron fork work
> https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini

👍👍👍
Works! Thx..

**Comment by jens-max** [comment]
> > > Win10 Pro 
> > > Version 20H2 (OS Build 19042.572) 
> > > @affinityv Aktualisiert = 2020-10-16 
> > > https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini 
> > > Arbeiten 
> > > https://ibb.co/GxHZwYR
> > 
> > 
> > Hallo! Sicher funktioniert es auf Version 10.0.19041.84 (ich habe es auf Ihrem hochgeladenen Bild gesehen), aber (ich weiß nicht warum) meine Version ist 10.0.19041.662 und es funktioniert überhaupt nicht.
> > Irgendwelche Ideen? Vielen Dank im Voraus.
> 
> Inzwischen gepatcht: Ich habe das KB4586853-Update deinstalliert und bin nach dem Neustart zur Version 10.0.19041.84 zurückgekehrt. Dann wurde ich [voll unterstützt]. Keine clevere Lösung, aber mittlerweile genug.

Hallo 
ich suche verzweifelt nach einer gepatchten termsrv.dll für 20H2. Könnte mir die jemand hochladen?
Vielen Dank und viele Grüße

**Comment by jens-max** [comment]
Hallo
ich suche verzweifelt nach einer gepatchten termsrv.dll für 20H2. Könnte mir die jemand hochladen?
Vielen Dank und viele Grüße

**Comment by affinityv** [comment]
> Hallo
> ich suche verzweifelt nach einer gepatchten termsrv.dll für 20H2. Könnte mir die jemand hochladen?
> Vielen Dank und viele Grüße

The termsrv.dll file itself is not patched, the INI file works with the normal, in place, termsrv.dll file.

What version of termsrv.dll is shown by `RDPConf.exe` ?

**Comment by totwired** [comment]
although in 20H2 works, the cursor of the remote machine has continuously the loading circle blinking.
when in vnc or working in the physical machine, this is not a problem.

is there any case that the defender with the rdpwraper service causing this issue?

**Comment by affinityv** [comment]
> although in 20H2 works, the cursor of the remote machine has continuously the loading circle blinking.
> when in vnc or working in the physical machine, this is not a problem.
> 
> is there any case that the defender with the rdpwraper service causing this issue?

You MUST add an exception for "C:\Program Files\RDP Wrapper" for Windows Defender -- at least you had to previously, probably the same now.  So, if you don't have the exception, then it could well be your problem.

**Comment by gtseriesx** [comment]
> Win10 Pro
> Version 20H2 (OS Build 19042.572)
> 
> @affinityv Updated=2020-10-16
> https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini
> 
> Working
> https://ibb.co/GxHZwYR

win10 home 20h2 working 
May 9th 2021

**Comment by simseb** [comment]
[https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini)

This one also works for **19042.964**

**Comment by totwired** [comment]
> > although in 20H2 works, the cursor of the remote machine has continuously the loading circle blinking.
> > when in vnc or working in the physical machine, this is not a problem.
> > is there any case that the defender with the rdpwraper service causing this issue?
> 
> You MUST add an exception for "C:\Program Files\RDP Wrapper" for Windows Defender -- at least you had to previously, probably the same now. So, if you don't have the exception, then it could well be your problem.

thank you for your interest

I bought a digital windows 10 pro code and I updated my system using correctly. i have an official RDP service but the problem remains!. defender works like crazy when using remote desktop.

**Comment by teoformartel** [comment]
> https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini
> 
> This one also works for **19042.964**

Thanks a lot. Works for 19042.985

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1004
