### ISSUE TITLE
Not working on Build 14352.rs1_release.160522-1930 of Windows Home Insider Preview

### ISSUE THREAD

**Issue by wedmonster** [stascorp/rdpwrap#119]
It seems that rdpwrap is not working on Windows with that version. How could I fix the problem?

**Comment by wedmonster** [comment]
How can I know the value of the following variables in rdpwrap.ini?

bServerSku.x64    
bInitialized.x64 
lMaxUserSessions.x64
bAppServerAllowed.x64
bRemoteConnAllowed.x64
bMultimonAllowed.x64 
ulMaxDebugSessions.x64
bFUSEnabled.x64

**Comment by binarymaster** [comment]
Everything is explained in `README.md`
