### ISSUE TITLE
I need offset for 10.0.20241.1000

### ISSUE THREAD

**Issue by saurav-biswas** [stascorp/rdpwrap#1194]
I need offset for 10.0.20241.1000 x64

**Comment by robbak** [comment]
Could you tell us what version of Windows this is from? Make sure you are getting that version number from rdpcheck.exe, or from the termsrv.dll file's properties page.

And it would be a good idea to upload the file somewhere and post a link here. People that can produce those offsets need a copy of the termsrv.dll file to locate them.

**Comment by saurav-biswas** [comment]
![image](https://user-images.githubusercontent.com/20636483/97891353-af462400-1d54-11eb-9fe2-e18b6f1193c6.png)

**Comment by saurav-biswas** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5476349/termsrv.zip)

**Comment by saurav-biswas** [comment]
Edition	Windows 10 Pro Insider Preview
Version	2004
Installed on	‎24-‎Oct-‎20
OS build	20241.1005
Experience	Windows Feature Experience Pack 120.27500.3.0

**Comment by sebaxakerhtc** [comment]
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/f557ce0a5985d29446d9e95843d1c23e2c2caada#diff-9e5bbfbeae79b59b305dda13323ba2b041f30f4887a84120392c479e1f7bba33

**Comment by strarsis** [comment]
Was able to fix it using some INI from another user - but `RDPConf.exe` incorrectly indicates an unsupported version, see https://github.com/stascorp/rdpwrap/issues/1054#issuecomment-742637185.
