### ISSUE TITLE
Need Support for 10.0.20246.1 

### ISSUE THREAD

**Issue by saurav-biswas** [stascorp/rdpwrap#1196]
![image](https://user-images.githubusercontent.com/20636483/98112850-ce65c280-1ec8-11eb-9cee-c7c654984c6d.png)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5487785/termsrv.zip)

**Comment by sebaxakerhtc** [comment]
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/88543cace358ebdb0030c0b5a362da600a9a4c02#diff-9e5bbfbeae79b59b305dda13323ba2b041f30f4887a84120392c479e1f7bba33
