### ISSUE TITLE
Win Ver 10.0.19041.84 Isuue Listener State: Not Listening

### ISSUE THREAD

**Issue by kg6300** [stascorp/rdpwrap#1199]
![Screenshot 2020-11-06 145444](https://user-images.githubusercontent.com/74047250/98351486-c2057500-2042-11eb-9ad9-8642856f8c89.png)

**Comment by robbak** [comment]
Restart your computer - sometimes it's the only way to properly reload the terminal services. Make sure your antivirus program isn't getting in the way, make sure your .ini file isn't using unix line endings (#1191 ) 

Also, could you let us know whose .ini file you are using?

**Comment by mdw123** [comment]
@robbak not the original reporter, but I have the same issue. I'm using the online .ini file, and I'm not finding a section in rdpwrap.ini for 10.0.19041.84.

**Comment by mdw123** [comment]
@robbak found your comment in another issue re: affinityv's file. It does have the section. I'm assuming this will work now. Thanks!

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1004
