### ISSUE TITLE
Need Support for 10.0.20251.1

### ISSUE THREAD

**Issue by saurav-biswas** [stascorp/rdpwrap#1200]
![image](https://user-images.githubusercontent.com/20636483/98388838-3eb34600-2079-11eb-8255-630fd7f8536a.png)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5502229/termsrv.zip)

**Comment by mensa84** [comment]
I need support for that version too please!
Did you find a solution already?

**Comment by affinityv** [comment]
You need a third party [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini), like mine -- it has this version covered.

Do the normal install, then copy over the new INI file over the one that is installed, then do `RDPWInst -r` -- all this as an admin user.

**Comment by mensa84** [comment]
I can't copy your INI over the existing one, even not as admin, cause it says it is currently in use. Do you know what I should do?

**Comment by affinityv** [comment]
You should be able to copy over the INI file, that only gets read at the time of starting RDP Wrapper.

**Comment by mensa84** [comment]
For me it is not possible. It can't be overwritten.
Do you know, which task I should kill or how to find out which one?

**Comment by affinityv** [comment]
Are you using an elevated CMD.EXE session?

**Comment by mensa84** [comment]
Thx, in the elevated cmd I was able to overwrite the rdpwrap.ini
Then I did RDPWinst -r in elevated cmd:

```
c:\Program Files\RDP Wrapper>RDPWInst.exe -r
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Restarting...
[+] TermService found (pid 7044).
[*] No shared services found.
[*] Terminating service...
[*] Starting TermService...
[-] StartService error (code 1056).
[+] Done.
```

But the problem is still not fixed:

![image](https://user-images.githubusercontent.com/30125802/99011618-d10d8b00-254c-11eb-944e-3c1283258e9d.png)

**Comment by affinityv** [comment]
Make sure that the file was written in normal DOS format.  How did you get/save the file?  Did you use an editor like notepad or something else?

Have you since tried to restart the computer as well, just in case a simple restart of RDP Wrapper wasn't enough for you?

**Comment by affinityv** [comment]
Also, Windows Defender has an exception for the RDP Wrapper files?  No other AV or "security?" product interfering?

**Comment by PLENAS** [comment]
mesmo proplema para 10.0.20257.1

**Comment by affinityv** [comment]
Is 10.0.20257.1 just the Windows version, or is it the termsrv.dll version as shown by `RDPConf.exe` ?

**Comment by affinityv** [comment]
Update [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file for 10.0.20251.1 from https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/10.0.20251.1-autogenerated.ini
