### ISSUE TITLE
old file from laptop backup detected as virus

### ISSUE THREAD

**Issue by Turphin** [stascorp/rdpwrap#1201]
PUA:Win32\Presenoker
![image](https://user-images.githubusercontent.com/45678161/98415830-d8a3d000-2032-11eb-8808-f72767d9af2c.png)
assuming that this is the same program that was on my laptop
content currently quarantined

**Comment by petesherick** [comment]
I have this flagged as well. 
v1.6.2

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/277
