### ISSUE TITLE
Need update for 19041.610

### ISSUE THREAD

**Issue by umityaz** [stascorp/rdpwrap#1202]
Need update for 19041.610

**Comment by robbak** [comment]
What windows version is this .ini file from?

As none of the .ini files I know of seem to have it, could you upload that termsvc.dll file somewhere and post a link here? Then someone can extract the information for it and add it to there .ini file for us.

**Comment by umityaz** [comment]
Windows 10 Pro 10.0.19041.610 and the download link for termsrv.dll https://gofile.io/d/zwZ4Nz

**Comment by robbak** [comment]
Oh, is that a windows version? Windows version numbers don't mean that much around here - we need the version of the .dll file, as listed by rdpconf.exe

I think your file is 10.0.19041.84, which is supported by all the popular .ini files.

Common .ini files recommended here:
Asmtron's file https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini
affinityv's file https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini
sebaxakerhtc's file: https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini (he has a script to pull offsets from files automatically, so is a good bet when you have a really new file)

**Comment by umityaz** [comment]
Thanks for your help. It worked. I have learned a new thing; the version you are talking about is the version of termsrv.dll.

This might help others searching with windows version :)
