### ISSUE TITLE
Windows 8.1 Ver 6.3.9600.19628 Issue Listener State: Not Listening [Not supported]

### ISSUE THREAD

**Issue by manuelb1978** [stascorp/rdpwrap#1205]
please fix the ini.
Thanks

**Comment by affinityv** [comment]
You need a third party [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini), like mine -- it has this version covered.

Do the normal install, then copy over the new INI file over the one that is installed, then do `RDPWInst -r` -- all this as an admin user.

**Comment by manuelb1978** [comment]
> You need a third party [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini), like mine -- it has this version covered.
> 
> Do the normal install, then copy over the new INI file over the one that is installed, then do `RDPWInst -r` -- all this as an admin user.

solved, thank you mate!
