### ISSUE TITLE
Allow Standard user to logon using RDP

### ISSUE THREAD

**Issue by daudhumayun** [stascorp/rdpwrap#1207]
I've Windows 7 Home Premium. I've successfully installed and running Remote Desktop using RDPWrap. However, only Administrator users are allowed to login using Remote Desktop. I want to allow Standard users to logon via Remote Desktop too.

**Comment by affinityv** [comment]
What does `RDPConf.exe` say?

**Comment by daudhumayun** [comment]
What value in RDPConf.exe you're asking about? Should I attach a screenshot of RDPConf.exe?

**Comment by affinityv** [comment]
It might be worth doing.  In the past there was some mumbo jumbo about creating a special "Remote Desktop Users" group, but I'm pretty sure that isn't necessary for RDP Wrapper.  Perhaps someone else can clarify.

**Comment by nick7inc** [comment]
The easiest way is to add user to "Remote Desktop Users" (the group is exist, no need to create it).

**Comment by brechtm** [comment]
> The easiest way is to add user to "Remote Desktop Users" (the group is exist, no need to create it).

I don't think this group exists on Windows 10 Home. `net localgroup` lists only these:
```
*Administrators
*Device Owners
*Distributed COM Users
*Event Log Readers
*Guests
*Hyper-V Administrators
*IIS_IUSRS
*OpenVPN Administrators
*Performance Log Users
*Performance Monitor Users
*Remote Management Users
*System Managed Accounts Group
*Users
```

**EDIT**: Aha! The readme links to [Allow Non-Administrator Users to Access Windows 7 Home Premium Via Remote Desktop](https://superuser.com/questions/680572/allow-non-administrator-users-to-access-windows-7-home-premium-via-remote-deskto). See also #107.

**Comment by daudhumayun** [comment]
> > The easiest way is to add user to "Remote Desktop Users" (the group is exist, no need to create it).
> 
> I don't think this group exists on Windows 10 Home. `net localgroup` lists only these:
> 
> ```
> *Administrators
> *Device Owners
> *Distributed COM Users
> *Event Log Readers
> *Guests
> *Hyper-V Administrators
> *IIS_IUSRS
> *OpenVPN Administrators
> *Performance Log Users
> *Performance Monitor Users
> *Remote Management Users
> *System Managed Accounts Group
> *Users
> ```
> 
> **EDIT**: Aha! The readme links to [Allow Non-Administrator Users to Access Windows 7 Home Premium Via Remote Desktop](https://superuser.com/questions/680572/allow-non-administrator-users-to-access-windows-7-home-premium-via-remote-deskto). See also #107.

True. The group doesn't exist on Windows Home Premium variant. However, the detail provided in the EDIT resolves the issue. Can't these configuration changes/hacks be made part of installation process or provisioned via RDPConf.exe?

**Comment by nick7inc** [comment]
It is very hard (may be - impossible) to use WinXP Home as remote desktop server. Use Windows XP pro

**Comment by nick7inc** [comment]
Minimum Windows XP SP2 (SP3 is better)

**Comment by HolisticDeveloper** [comment]
The steps in [this comment](https://github.com/stascorp/rdpwrap/issues/107#issuecomment-216041697) still worked for me.
