### ISSUE TITLE
Cannot get working on Windows10 preview(14352)

### ISSUE THREAD

**Issue by NSBlink** [stascorp/rdpwrap#121]

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/119

Run `update.bat`

**Comment by NSBlink** [comment]
I have runned the update.bat, and it shows everything is ok. but it will be broken when I connect.(my Windows is education edition)

**Comment by binarymaster** [comment]
Please provide more details, such as screenshot of RDPConf diagnostics and the error message.

**Comment by garrettwp** [comment]
I can comment that the latest update to support Windows 10 version 14352 is not working. When trying to remote desktop I receive the following dialog message "An internal error occurred." Then the terminal service stops running and needs to be restarted and same issue happens again.

![rdp_error](https://cloud.githubusercontent.com/assets/9434840/15738661/4cc533da-287a-11e6-94ef-3a5706f6b40d.jpg)
![rdpwrapconfig](https://cloud.githubusercontent.com/assets/9434840/15738662/4cc73e28-287a-11e6-9ae5-34ae1f8b984c.jpg)
[rdp_error.txt](https://github.com/stascorp/rdpwrap/files/295174/rdp_error.txt)

**Comment by binarymaster** [comment]
Well, this issue needs more research. I'll test this build in VM.

**Comment by hsbadr** [comment]
@binarymaster 
I've issues on that build as well. It seems that rdpwrap patches wrong address or some of the security updates stop RDP if I tried to connect while rdpwrap is installed. RDP works fine otherwise, when I uninstall rdpwrap and re-enable RDP.
