### ISSUE TITLE
WINDOWS V20H2 OS BUILD 19042.508

### ISSUE THREAD

**Issue by mhtkumar0025** [stascorp/rdpwrap#1213]
I installed RDP Wrap today only and found out that on my Windows 10 Pro the .ini file needs update. I have mentioned the Version and my OS build. Please help me. I am also attaching the screenshot of my RDPConfig

This is urgent!Thank you !

![windows info](https://user-images.githubusercontent.com/74907458/99956518-ffece380-2d3a-11eb-8c30-4b38f63f0e4e.PNG)
![rdpconfig](https://user-images.githubusercontent.com/74907458/99956522-01b6a700-2d3b-11eb-91df-ec5e958a4c82.PNG)

**Comment by robbak** [comment]
REcommended .ini files:

https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini
https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini

**Comment by mhtkumar0025** [comment]
I need to change the file name while copying them into the C Folder?

**Comment by robbak** [comment]
No, they don't go into c:\, they go into program files/rdpwrap. And the
name remains rdpwrap.ini

**Comment by mhtkumar0025** [comment]
Yes yes, it shows fully supported. Thank you bother! 👍

**Comment by mhtkumar0025** [comment]
Means a lot, Thank you for the quick issue

**Comment by mhtkumar0025** [comment]
thank you for the quick response. Means a lot!
