### ISSUE TITLE
rdpwrap.ini for 10.0.17763.1577 version

### ISSUE THREAD

**Issue by shanialisar** [stascorp/rdpwrap#1214]
Does anybody have ini file for this build 10.0.17763.1577 that works?

**Comment by robbak** [comment]
That is a windows version. Most of the ini files should support that, like
asmtrons and affinityv's files below. But to be sure, run rdpconf.exe and
look at the version number listed to the right of the 'Service State:
running' label. Then search through your chosen .ini file to make sure it
is there.

https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini
https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini

**Comment by shanialisar** [comment]
Thanks! I used one of the ini you've send! now its working!
