### ISSUE TITLE
This is detected by 40 AVs on VirusTotal

### ISSUE THREAD

**Issue by thatmaxplayle** [stascorp/rdpwrap#1227]
I take it that this is just a move from Microsoft to prevent people getting RDC on Win10 Home? Either that or the app makes use of memory hooking or something similar so is detected falsely by loads of AV's?

Please advise accordingly, thank you.

**Comment by robbak** [comment]
I think it is just blind heuristics - the trick that rdpwrapper plays, live
patching and wrapping a system .dll, is a common technique for making a
malware infection permanent.

This does it for a legitimate reason requested by the computer owner, so it
should be whitelisted by the antivirus vendors. But it hasn't been - so
maybe Microsoft is somehow putting pressure on them to stop them doing this.
