### ISSUE TITLE
Unsupported version

### ISSUE THREAD

**Issue by thatmaxplayle** [stascorp/rdpwrap#1228]
![image](https://user-images.githubusercontent.com/63079841/101270588-45b19f00-3772-11eb-9331-6538dc986a30.png)
Can somebody please advise me on how to fix this? Thank you in advance :)

**Comment by suanno** [comment]
I tried this, but it doesn't work.

net stop termservice
Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
net start termservice
Reboot your PC
https://github.com/stascorp/rdpwrap/files/3439496/rdpwrap_10.0.18362.267_x64.zip

**Comment by BRENTH561** [comment]
I used this http://rdpwrapper.myftp.biz/RDP_Wrapper_mod.zip. 

Simply put the existing RDP wrapper files that were in program files in an old folder and pasted the new ones from the mod.

**Comment by eslamiar** [comment]
The latest 20H2 updates break RDPWrap, the auto-update tool updated the .ini and .dll and after rebooting all is working again. 

https://github.com/asmtron/rdpwrap/blob/master/binary-download.md 

<img width="435" alt="Screen Shot 2020-12-10 at 1 08 31 PM" src="https://user-images.githubusercontent.com/62970726/101812287-2bb4eb00-3ae9-11eb-8907-6a1bfb986f5d.png">

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083
