### ISSUE TITLE
installer fails from inaccessible dependency and detects as virus in windows defender

### ISSUE THREAD

**Issue by Turphin** [stascorp/rdpwrap#1229]
![image](https://user-images.githubusercontent.com/45678161/101272780-48959b00-3744-11eb-91ec-b35666395469.png)

**Comment by sashaqwert** [comment]
Do not use MSI installer.
Use ZIP.
More info in Telegram chat: https://t.me/rdpwrap/23875
https://t.me/rdpwrap/21724

**Comment by beatinger** [comment]
The ZIP file won't even download, for the same reason (virus detected).

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/277
