### ISSUE TITLE
Win10 2004 - 19041.84 - Issue with remote user

### ISSUE THREAD

**Issue by ThoseITGuys** [stascorp/rdpwrap#1230]
I currently have my RDPwrap all green with listening, full support etc.

Now when I connect it wants to kick the local user off.

If I grab the latest INI from:

[https://github.com/Octanium91/rdpwrap](url)

then when the remote user (different account on PC) logs in the local users desktop changes to the remote user desktop but only as a viewer they cannot click or do anything. Only watch what the remote user is doing. They are unable to use their own profile until the remote user logs out. Then the local users desktop is shown again.

**Comment by ThoseITGuys** [comment]
No one else had this issue? Of remote user causing local user to mirror their desktop?

**Comment by robbak** [comment]
Very common if you are using another remote access tool, such as
TeamViewer, to test it. They don't play well together - tv doesn't know
which session it should be controlling.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1004
