### ISSUE TITLE
[Not Supported] problem

### ISSUE THREAD

**Issue by kanishk-04** [stascorp/rdpwrap#1232]
![IMG20201209002520](https://user-images.githubusercontent.com/69419501/101528383-41c18f00-39b5-11eb-94f7-8b7fd3a98073.jpg)
How do I solve this?

**Comment by arnoldvdm** [comment]
First make sure your using the right ini file ↓↓
Secondly open CMD **with administrator rights**.

1: `NET STOP TermService`
2: `NET START TermService`

Make also sure the TermService is enabled. 
.ini file↓

[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5662840/rdpwrap.zip)

**Comment by kanishk-04** [comment]
It worked.
Thanks
