### ISSUE TITLE
Audio redirection problem

### ISSUE THREAD

**Issue by gholipourm** [stascorp/rdpwrap#1237]
RDPwrap doesn't support microphone redirection. It can redirect audio out from server to client, but audio in from client to server doesn't work.
I tried different solution, none of them worked.

**Comment by arnoldvdm** [comment]
what have you already tried to fix it?

1.  Run mstsc (ctrl+r)
2. Click on show options at the left down corner
3. Click on local sources (tab 3)
4. Click on settings
If the options are disabled you have to turn off the remote desktop first.

**Comment by Spirosvw** [comment]
Hello, 

I stumbled upon the same issue, I wish to use the microphone and on the remote desktop settings I get "No input devices found".

I tried adjusting the settings at the "local resources" tab before I connect to the remote desktop but the only temp solution that I found with Windows Server 2019 is to enable the Remote Desktop Services for which I don't have a license and therefore I can only use it for a specific period before it closes.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/74
