### ISSUE TITLE
10.0.19042.685 is out.

### ISSUE THREAD

**Issue by isidorosss** [stascorp/rdpwrap#1238]
![19042685](https://user-images.githubusercontent.com/35171656/101738329-a8869b80-3ace-11eb-86c1-64c05254f945.png)

**Comment by Melnick704** [comment]
Fix 685 in this topic:

https://github.com/stascorp/rdpwrap/issues/1233#issuecomment-741621762

**Comment by Waterpook** [comment]
https://user-images.githubusercontent.com/35171656/101738329-a8869b80-3ace-11eb-86c1-64c05254f945.png

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1220
