### ISSUE TITLE
not supported [10.0.19042.685]

### ISSUE THREAD

**Issue by Melnick704** [stascorp/rdpwrap#1239]
10.0.19042.685 update not supported

**Comment by Melnick704** [comment]
Fix 685 in this topic:

https://github.com/stascorp/rdpwrap/issues/1233#issuecomment-741621762

**Comment by KrishnaST** [comment]
> 
> 
> Fix 685 in this topic:
> 
> [#1233 (comment)](https://github.com/stascorp/rdpwrap/issues/1233#issuecomment-741621762)

I believe there are two different versions 10.0.19041.685 and 10.0.19042.685

**Comment by Melnick704** [comment]
Yes, but my 10.0.**19042**.685 is not supported.  The topic I indicated above helped me

there the topic is called differently, but inside they discussed exactly 10.0.19042.685![image](https://user-images.githubusercontent.com/75782247/101882320-c6273400-3ba6-11eb-91d7-5620aab27db6.jpeg)

**Comment by Melnick704** [comment]
there the topic is called differently, but inside they discussed exactly 10.0.19042.685![Uploading 101882247...]

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1220
