### ISSUE TITLE
Supported version tells unsupported, same session as physical keyboard/mouse session ?

### ISSUE THREAD

**Issue by dezza** [stascorp/rdpwrap#124]
https://upl.io/ueemps
![Screenshot](https://upl.io/i/ueemps.png)
Here's a screenshot.

DLL version to the right. I aligned the version-column with the version column of the same version to the left.

cmd.exe shows unsupported.

**Side-question:**

I would like to use RDP to control my Windows PC from my bed like a remote with the same open applications and control multimedia applications (pause, forward, rewind etc.).

It seems RDP either starts a new session always just with the same user. Is it possible to do what I want? Control mouse/keyboard in the same user as already logged in via my physical mouse/keyboard?

**Comment by binarymaster** [comment]
>cmd.exe shows unsupported.

Use `update.bat`.

>Control mouse/keyboard in the same user as already logged in via my physical mouse/keyboard?

You need to disconnect your session first, then connect from another device by RDP. Also you may enable option `Single Session Per User` in configuration.

**Comment by dezza** [comment]
Whatever I do my PC always gets locked.

**Comment by spazebar** [comment]
No RDP isn't the correct technology to use for a media remote use case like
you are describing because as you say the session can only be open in one
place at a time. From what it sounds like you want to do I would recommend
you give VNC a try. Its more or less the FOSS equivalent to RDP.

**Comment by dezza** [comment]
@spacebar: Thanks for clarifying. Since RDP is better for both colors and performance I am puzzled why this won't be possible in any way. VNC even with 8-bit colors is nothing in comparison. If VNC is so bad and RDP so much better I am puzzled why no better alternative is here yet. VirtualBox uses RDP for whatever reason - maybe Windows compatability. I believe I need to try NoMachine as a replacement for both as it seems the most featureful remote server.
