### ISSUE TITLE
Could not connect more then ONE user [19041.685]

### ISSUE THREAD

**Issue by dcbasso** [stascorp/rdpwrap#1242]
The wrapper configuration says that is everything working (Installed, Running, Listening and Fully supported) but I can't connect with one then one user.
Windows have updated today.

**Comment by dcbasso** [comment]
https://github.com/stascorp/rdpwrap/issues/1233#issuecomment-742704239

using: 
https://github.com/stascorp/rdpwrap/files/5665638/termsrv.zip

**Comment by akshayagrwl** [comment]
I had the same issue and kept looking for if for hours,  i was updating the dll and ini manually by disabling the remote desktop service. 
Finally this worked for me:
I uninstalled the rdpwrapper
I Installed the rdpwrapper again 
followed the below instructions:
https://github.com/asmtron/rdpwrap/blob/master/binary-download.md
I ran the above updater from the c:/program files/rdp wrap folder
I ran the updater once more just in case the first didn't do the trick.

**Comment by dimrim** [comment]
#1233 
Sound just like my problem. In my case I was able to fix it by sorting the INI file differently.

**Comment by liuyangpy** [comment]
[https://github.com/stascorp/rdpwrap/issues/1246#issuecomment-744238158](url)

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1220 and https://github.com/stascorp/rdpwrap/issues/353
