### ISSUE TITLE
Why the ini file is needed?

### ISSUE THREAD

**Issue by cmaftuleac** [stascorp/rdpwrap#1243]
This may be offtop but anyway.

Why all these manipulations with .ini file is needed? Why cant just the application detect those offsets and what it needs at runtime?
What is the problem? Just thinking maybe can help with anything?

**Comment by robbak** [comment]
That would be an awful lot of programming. I mean, if you are offering, go
ahead! But the procedure for decompiling and extracting that data is
complex.

**Comment by cmaftuleac** [comment]
Is there any description what are the requirements?
How is it getting done manually every time?

**Comment by robbak** [comment]
There is a video in this repo that shows someone going through the
procedure, and @sebaxakerhtc had partially automated the procedure and has
also posted a video on his repo.

**Comment by cmaftuleac** [comment]
Thank you, will get my hands on it :)
