### ISSUE TITLE
listener state: Not listening [not supported] on Windows 10 home x64 10.0.19041

### ISSUE THREAD

**Issue by jcychan** [stascorp/rdpwrap#1245]
Hi,

I installed RDPW on my Windows 10.0.19041 64bit.  When I ran RDPWConfig, the listener state shows "Not listening".  during the install, I saw a message saying that the termsrv.dll version is not recognized.  Can someone help me?  thanks

**Comment by jcychan** [comment]
Can anyone help?  Do I need to upload anything?

**Comment by robbak** [comment]
No, just read some of the other issues posted. Your question is asked and
answered several times a week.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1883
