### ISSUE TITLE
Can only connect one user +admin [10.0.19041.662]

### ISSUE THREAD

**Issue by eyeTechSolutions** [stascorp/rdpwrap#1246]
Installed RDPwrapper auto updater via https://github.com/asmtron/rdpwrap/blob/master/binary-download.md
status says installed and fully supported but can only connect one user at a time, kinda...

i have 4 users, office1, office2, office3 and admin
i can connect with admin and one office user and all others will fail  with error: 

Your remote desktop services session has ended, possibly for one of the following reasons:
the administrator has ended the session.
an error occurred while the connection was being established
a network problem occurred.

If i restart i can connect with another office user and the admin account.

**Comment by liuyangpy** [comment]
[10.0.19041.662-SLInit]
bInitialized.x86      =D1954
bServerSku.x86        =D1958
lMaxUserSessions.x86  =D195C
bAppServerAllowed.x86 =D1964
bRemoteConnAllowed.x86=D196C
bMultimonAllowed.x86  =D1970
ulMaxDebugSessions.x86=D1974
bFUSEnabled.x86       =D1978

bInitialized.x64      =106028
bServerSku.x64        =10602C
lMaxUserSessions.x64  =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64  =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64       =10604C

[10.0.19041.662]
LocalOnlyPatch.x86 =1
LocalOnlyOffset.x86 =B5F59
LocalOnlyCode.x86 =jmpshort
SingleUserPatch.x86 =1
SingleUserOffset.x86 =3BC05
SingleUserCode.x86 =nop
DefPolicyPatch.x86 =1
DefPolicyOffset.x86 =3E779
DefPolicyCode.x86 =CDefPolicy_Query_eax_ecx
SLInitHook.x86 =1
SLInitOffset.x86 =68068
SLInitFunc.x86 =New_CSLQuery_Initialize

LocalOnlyPatch.x64 =1
LocalOnlyOffset.x64 =88E81
LocalOnlyCode.x64 =jmpshort
SingleUserPatch.x64 =1
SingleUserOffset.x64 =0CA0C
SingleUserCode.x64 =Zero
DefPolicyPatch.x64 =1
DefPolicyOffset.x64 =189D5
DefPolicyCode.x64 =CDefPolicy_Query_eax_rcx
SLInitHook.x64 =1
SLInitOffset.x64 =1D50C
SLInitFunc.x64 =New_CSLQuery_Initialize


[rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/5687147/rdpwrap.ini.zip)

**Comment by hunterseeker1** [comment]
Thank you.

Your updated rdpwrap.ini file fixed my "not listening" issue on build 10.0.19041

**Comment by ForwardUntoDawn** [comment]
Thanks for the updated INI @liuyangpy -
Works like a charm.  Rock on!

**Comment by look0613415** [comment]
更新到Microsoft Windows [版本 10.0.19041.685]后用最新的配置文件就可以了


[rdpwrap2020.12.25.zip](https://github.com/stascorp/rdpwrap/files/5741893/rdpwrap2020.12.25.zip)

**Comment by shirshak55** [comment]
@look0613415 thanks it worked is there some guide/tuts how to do it our self? How to find the hex code etc? 

"Give a man a mango, and you feed him for a day; show him how to grow mangoes, and you feed him for a lifetime."

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1220

**Comment by look0613415** [comment]
https://github.com/stascorp/rdpwrap/issues/1246#issuecomment-751459204
Just block the update
