### ISSUE TITLE
18383.1256 not supported

### ISSUE THREAD

**Issue by brkr24** [stascorp/rdpwrap#1249]
Hello, I have the following windows OS running, which is listed as not supported in RDPConf:

![Capture](https://user-images.githubusercontent.com/76136733/102423522-d720dc80-3fce-11eb-91e5-b872107091ef.PNG)

Thanks so much.

**Comment by robbak** [comment]
run rdpconf.exe and note the version of the termsvc.dll file, which will be
listed as the version of the 'service state'. Then search other posts here
for that version number, and I am sure that you will find support for it.

**Comment by brkr24** [comment]
You are correct- I was able to fix it using this thread: https://github.com/stascorp/rdpwrap/issues/1136#issuecomment-665956506. Thanks!
