### ISSUE TITLE
How to learn to update the rdp by myself in this project?

### ISSUE THREAD

**Issue by xmostera** [stascorp/rdpwrap#1250]
Instead of relying other, asking same questions over and over.
I would like to do contribution but I do not know where to go deeper into this topics.
So that I will also help up the community. Thank you.

**Comment by v-mwalk** [comment]
I too want to be able to contribute to this.  Looks like a set of offsets need to be determined.  If I remember rightly, before Stas did the release using an ini the offsets were byte offsets to modify the termsrv.dll itself.  Have done a google search for how to do this but cant find anything....?

**Comment by sebaxakerhtc** [comment]
Look at readme about this. There is a video, showing how to
