### ISSUE TITLE
fully supported but [Not Listening] on 19041.622

### ISSUE THREAD

**Issue by ElliotQi** [stascorp/rdpwrap#1251]
![image](https://user-images.githubusercontent.com/46469021/102488971-cc864600-40a7-11eb-8ec4-3d53b4aa06f8.png)
I've changed my rfxvmt.dll, reinstalled rdp. But it didn't  work

**Comment by ElliotQi** [comment]
Oh, I solved the problem by restart the termservice
net stop termservice
net start termservice
And the Listener state turned to be green

**Comment by look0613415** [comment]
https://github.com/stascorp/rdpwrap/issues/1246#issuecomment-751237612

**Comment by look0613415** [comment]
https://github.com/stascorp/rdpwrap/issues/1246#issuecomment-751237612

**Comment by ElliotQi** [comment]
> [#1246 (comment)](https://github.com/stascorp/rdpwrap/issues/1246#issuecomment-751237612)

fully supported 代表已经更新到最新版本到配置文件了

**Comment by JiangYizhou16** [comment]
I met the same problem. I updated my ini and restart the termservice, however it still doesn't works 'Not listening'...
Does the same probelm happen to you anymore?

**Comment by ElliotQi** [comment]
> I met the same problem. I updated my ini and restart the termservice, however it still doesn't works 'Not listening'...
> Does the same probelm happen to you anymore?

After restarting the termservice , my rdpwrapper works well. Could you check the process of restarting?

**Comment by JiangYizhou16** [comment]
I have never solved this problem in 19041.622, but it works after I updated to 19041.746 …… amazing

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/872

**Comment by ElliotQi** [comment]
您好,邮件已收到,会尽快处理

**Comment by dahe46** [comment]
> > I met the same problem. I updated my ini and restart the termservice, however it still doesn't works 'Not listening'...
> > Does the same probelm happen to you anymore?
> 
> After restarting the termservice , my rdpwrapper works well. Could you check the process of restarting?

I met the same problem,help me
