### ISSUE TITLE
W10 10.0.18362.267 All green, but doesn't work

### ISSUE THREAD

**Issue by LevanKikinashvili** [stascorp/rdpwrap#1254]
Everything seems fine, installed latest .ini , RDPConf all green, but multi user doesn't work, all connects to same account.

**Comment by SamuelTulach** [comment]
This project has not been updated for really long time. Can you sign in to different account?

If you don't need to login to the same account and you need just to connect multiple people at once, you can use [my patcher](https://github.com/SamuelTulach/lrdp) or manually patch the termsrv.dll file by opening it in HEX editor and replacing `39 81 3C 06 00 00 0F 84` with `B8 00 01 00 00 89 81 38 06 00 00 90`.

**Comment by LevanKikinashvili** [comment]
For example: When I'm locally signed in 'user1' and someone sign in 'user2' ,  I'm automatically switched to 'user2'

**Comment by robbak** [comment]
You are probably connecting to the computer using TeamViewer or similar.
These don't play well with rdp, as it doesn't know which session to follow.


Of your actually go to the computer, you'll see that everything is working.

**Comment by LevanKikinashvili** [comment]
.
