### ISSUE TITLE
windows home 10.0.18362.836 NOT Listening

### ISSUE THREAD

**Issue by lumengda** [stascorp/rdpwrap#1256]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5732815/termsrv.zip)
![无标题](https://user-images.githubusercontent.com/53165426/102950160-ff479880-4504-11eb-91da-6818ca69ac12.png)
![无标题1](https://user-images.githubusercontent.com/53165426/102950166-01a9f280-4505-11eb-9871-7c2617db017a.png)
![无标题3](https://user-images.githubusercontent.com/53165426/102950167-02428900-4505-11eb-88ba-373cea2ee5c4.png)

**Comment by lumengda** [comment]
![1](https://user-images.githubusercontent.com/53165426/102950235-3027cd80-4505-11eb-8b74-4970398dc6f3.png)
![2](https://user-images.githubusercontent.com/53165426/102950242-31f19100-4505-11eb-93bf-9281676f80ad.png)
![3](https://user-images.githubusercontent.com/53165426/102950247-3453eb00-4505-11eb-8bd7-7a1bc19e3d0d.png)

**Comment by robbak** [comment]
search the problem reports for that termsrv version number - 10.0.18462.836
and you'll find the solution.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1083
