### ISSUE TITLE
fully support by updating ini, but still disconnect other user on 19041.662

### ISSUE THREAD

**Issue by shyujiaxin** [stascorp/rdpwrap#1258]
I installed rdp wrapper and updated the ini file to add 19041.622 support.

to just replace the ini file in program file folder, the RdpConf prompts it is fully support
but connect another user from rdp will still disconnect local session.

After reboot the system, the RdpConf reports service not running state.
![image](https://user-images.githubusercontent.com/39482788/103011656-440b1800-4575-11eb-88a4-b7b2f9996663.png)

even start the services through cmd does not change any thing.

the ini content is below:

```


[10.0.19041.662]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B5F59
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88E81
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3BC05
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=0CA0C
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E779
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=189D5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=68068
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=1D50C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.662-SLInit]
bInitialized.x86 =D1954
bServerSku.x86 =D1958
lMaxUserSessions.x86 =D195C
bAppServerAllowed.x86 =D1964
bRemoteConnAllowed.x86=D196C
bMultimonAllowed.x86 =D1970
ulMaxDebugSessions.x86=D1974
bFUSEnabled.x86 =D1978

bInitialized.x64 =106028
bServerSku.x64 =10602C
lMaxUserSessions.x64 =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64 =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64 =10604C
```

**Comment by apavlishev** [comment]
https://winitpro.ru/index.php/2015/09/02/neskolko-rdp-sessij-v-windows-10/

**Comment by look0613415** [comment]
https://github.com/stascorp/rdpwrap/issues/1246#issuecomment-751237612

**Comment by sammer003** [comment]
pasted the code from above for termserv.dll version 10.0.19041.662 and checked with RDPConf show all GREEN and working.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1220 and https://github.com/stascorp/rdpwrap/issues/353
