### ISSUE TITLE
Windows 10 x64 v2004 - May 2020 Update (20H1) (10.0.19041.84), Another user is signed in. If you continue, they’ll be disconnected.

### ISSUE THREAD

**Issue by progman-vin** [stascorp/rdpwrap#1260]
The solution of the problem:
1.
https://github.com/geissbuehler/TermsrvPatcher/releases
2. 
https://www.mysysadmintips.com/windows/clients/545-multiple-rdp-remote-desktop-sessions-in-windows-10

**Comment by d3dx9** [comment]
https://github.com/asmtron/rdpwrap/blob/master/binary-download.md - try this here, that works for me :)

**Comment by BuNoze** [comment]
> https://github.com/asmtron/rdpwrap/blob/master/binary-download.md - try this here, that works for me :)

Thanks, worked for me too 👍

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1004
