### ISSUE TITLE
resolved the 10.0.18368.836 problem

### ISSUE THREAD

**Issue by etaerC** [stascorp/rdpwrap#1262]
I collected a lot of information and finally solved my problem. Thank you，everyone

Use _**RDPWrap - v1.6.2**_

The _**rdpwrap.ini**_ used is from https://github.com/stascorp/rdpwrap/issues/1149
### _- -_
1. **Turn off tamper protection!!**
(Otherwise, running install.bat will cause an error)
![Turn off tamper protection](https://user-images.githubusercontent.com/22704838/103752668-f39bbc00-5044-11eb-9f52-6136458bf320.png)

2. Run _install.bat_ as the administrator
(If you open rdpconf.exe at this time, you will find...not listening .. not surpported..)

3. Copy _rdpwrap.ini_ to _C: Program Files\RDP Wrapper_
(If you open rdpconf.exe at this time, you will find...not listening .. )

4. **Restart your computer!!**
(It should be completely normal now)

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1083
