### ISSUE TITLE
RDP Wrapper - Cannot Get Multiple Connections

### ISSUE THREAD

**Issue by dfenner-fcs** [stascorp/rdpwrap#1266]
I have downloaded RDPWrap-v1.6.2.zip from GitHub and extracted locally to Windows 10 Pro Version 10.0.18363 Build 18363. After running the install.bat file successfully. Initially I was getting [Not Supported] to the right of Listener State field. I was able to fix this by replacing the rdpwrap.ini file with the file matching my version which I have copied to issue as a text file. After reboot of PC, I opened RDP Wrapper Configuration Utility and all looks fine (see attached screenshot). If I use the RDPCheck utility and attempt to login as the same user with Single session per user unchecked, I get an Access Denied error. If I try and create a second RDP session from remote computer, I am told there is another user logged in. Continuing will disconnect their session would you like to proceed? If I click yes, it provides a warning on RDP#1 PC that RDP#2 PC is trying to connect. Inevitably RDP#1 is disconnected and RDP#2 is connected. Sometimes it just states on RDP#1 that "You have been disconnected because another connection was made to the remote computer" when RDP#2 logs in. RDP Wrapper appears as if it should be working properly but it is not. Any help would be greatly appreciated.

We also have TeamViewer12 and AnyDesk  installed on the PC for remote access from other groups. Not sure if this could be causing any issues.

![rdpwrapconfig](https://user-images.githubusercontent.com/61938762/103940359-cd345a00-50f2-11eb-8b87-be8eee3a5643.PNG)

[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/5783762/rdpwrap.txt)

**Comment by Barikad** [comment]
Same issue, Windows 10 pro 19042.685 (20H2)

**Comment by MournfulRaven** [comment]
The same problem 20H2

**Comment by leebinx** [comment]
same problem - anyone find a solution?

**Comment by Raito00** [comment]
To Fix Access Denied error:

Run - gpedit.msc - Need enable the policy “Limit number of connections” under Computer Configuration -> Administrative Templates -> Windows Components -> Remote Desktop Services -> Remote Desktop Session Host -> Connections section. Change its value to 999999

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1083 and https://github.com/stascorp/rdpwrap/issues/353
