### ISSUE TITLE
RDP Wrapper not working after REBOOT

### ISSUE THREAD

**Issue by amin137398** [stascorp/rdpwrap#1269]
Hi 
I'm using widnows 10 and rdp wrapper works fine on it . but if I restart the windows it just stops working and there is nothing I can to beside re-installing it ( as you can see it seems to uninstall itself! ) . I tried excluding the rdp wrapper folder in anti-virus and using diffrent ini files but none seems to work .
here are the pictures of how it looks like before and after reboot 
any suggestions ? 

![rdp before reboot](https://user-images.githubusercontent.com/27921772/104117570-69e73980-5337-11eb-9d1b-66dd6f8a5dd0.png)
![rdp after reboot](https://user-images.githubusercontent.com/27921772/104117572-6bb0fd00-5337-11eb-8de5-8c14961eb539.png)

**Comment by Soshampoo** [comment]
Uninstalling, reinstaling and not installing the autoupdater doesn't work :/
I coppied the ini file from the autoupdater post

**Comment by amin137398** [comment]
> 
> 
> Uninstalling, reinstaling and not installing the autoupdater doesn't work :/
> I coppied the ini file from the autoupdater post

you had same problem ?

**Comment by test2a** [comment]
can you try something? rdpcheck . run it, open an account, close it then try the regular way. @amin137398 @Soshampoo

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1083 and https://github.com/stascorp/rdpwrap/issues/1883

**Comment by test2a** [comment]
i have had good success with uninstalling "security update" in the add remove programs. that solves the problems regularly for me. occasionally windows 10 LTSC decided to update the security update and yet the RDP wrapper says its working. this solves my problems
