### ISSUE TITLE
Not working on 10.0.19041.746

### ISSUE THREAD

**Issue by tbishop9** [stascorp/rdpwrap#1270]
Can we please get updated INI?
![snip](https://user-images.githubusercontent.com/47014121/104380251-d43deb00-557e-11eb-9934-2366daa4f4bb.JPG)

**Comment by tbishop9** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5805047/termsrv.zip)
DLL as attached.

**Comment by vasumishra27** [comment]
Same issue here. Please help!

**Comment by v-mwalk** [comment]
Actually just an rdpwrap.ini file update needed.  I tried duplicating the [10.0.19041.662] and [10.0.19041.662-SLINIT] but it looks like MS have changed the offsets.  I would do the work to contribute for an undated ini but not sure how to get the offsets - are they pointing to locations in the termsrv.dll or to other dll's (or something totally different)?  I could look in Stas's source I suppose :-)

So, looked in the source code - yes, they are offsets in termsrv.dll and (I think) SLC.dll.  So what are the signatures at these offset locations that can be found (using a HEX editor search) that indicate the new offsets needed.  Anyone?

**Comment by arnoldvdm** [comment]
for me it doesn't work on the 19042.746 instead of the 19041
Update KB4598242  by the way.
[termsrv 19042.746.zip](https://github.com/stascorp/rdpwrap/files/5806276/termsrv.19042.746.zip)

**Comment by tvcat** [comment]
```
[10.0.19041.746]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F31
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize
```

SLInit still the same.

**Comment by mr-mmajoR** [comment]
> ```
> [10.0.19041.746]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=88F31
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CB22
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=18A15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1D5BC
> SLInitFunc.x64=New_CSLQuery_Initialize
> ```
> 
> SLInit still the same.

Thanks.
I added this text to rdpwrap.ini but it still does not work. 
Give full rdpwrap.ini please

**Comment by ChukXP** [comment]
[10.0.19041.746]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F31
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize
.
[10.0.19041.746-SLInit]
bInitialized.x64 =106028
bServerSku.x64 =10602C
lMaxUserSessions.x64 =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64 =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64 =10604C

This code works for me.

**Comment by v-mwalk** [comment]
Sorry, same as the others.  Trying this code my termsrv service crashes and burns.

**Comment by tbishop9** [comment]
Working for me.

**Comment by haririan** [comment]
could u please share rdpwrap.ini file completely  ?

**Comment by haririan** [comment]
****
![image](https://user-images.githubusercontent.com/9495208/104418366-0b66c900-558c-11eb-8acf-856902a5e6e3.png)

it say fully supported but still multi session remote **is not working** 

![image](https://user-images.githubusercontent.com/9495208/104418533-4832c000-558c-11eb-9e76-eeeebfb858ed.png)

**Comment by LancerMar** [comment]
> [10.0.19041.746]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=88F31
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CB22
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=18A15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1D5BC
> SLInitFunc.x64=New_CSLQuery_Initialize
> .
> [10.0.19041.746-SLInit]
> bInitialized.x64 =106028
> bServerSku.x64 =10602C
> lMaxUserSessions.x64 =106030
> bAppServerAllowed.x64 =106038
> bRemoteConnAllowed.x64=106040
> bMultimonAllowed.x64 =106044
> ulMaxDebugSessions.x64=106048
> bFUSEnabled.x64 =10604C
> 
> This code works for me.
it works for me

**Comment by haririan** [comment]
please share rdpwrap.ini file

**Comment by haririan** [comment]
> > [10.0.19041.746]
> > LocalOnlyPatch.x64=1
> > LocalOnlyOffset.x64=88F31
> > LocalOnlyCode.x64=jmpshort
> > SingleUserPatch.x64=1
> > SingleUserOffset.x64=0CB22
> > SingleUserCode.x64=Zero
> > DefPolicyPatch.x64=1
> > DefPolicyOffset.x64=18A15
> > DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> > SLInitHook.x64=1
> > SLInitOffset.x64=1D5BC
> > SLInitFunc.x64=New_CSLQuery_Initialize
> > .
> > [10.0.19041.746-SLInit]
> > bInitialized.x64 =106028
> > bServerSku.x64 =10602C
> > lMaxUserSessions.x64 =106030
> > bAppServerAllowed.x64 =106038
> > bRemoteConnAllowed.x64=106040
> > bMultimonAllowed.x64 =106044
> > ulMaxDebugSessions.x64=106048
> > bFUSEnabled.x64 =10604C
> > This code works for me.
> > it works for me

please share rdpwrap.ini file

**Comment by LancerMar** [comment]
[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/5807228/rdpwrap.txt)

**Comment by ghost** [comment]
> [rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/5807228/rdpwrap.txt)

I've tested it out, not working for me.

**Comment by haririan** [comment]
> [rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/5807228/rdpwrap.txt)

thank you very much its work perfectly

**Comment by artemmen** [comment]
TermService can not start with this file. Reboot not solved.

**Comment by d-and** [comment]
tested, works !
@arwent maybe just reboot

**Comment by haririan** [comment]
> tested, works !
> @arwent maybe just reboot

exactly after reboot it worked

**Comment by LancerMar** [comment]
I can not upload '.ini' file, so I change the suffix to '.txt' before uploading @arwent

**Comment by p5yc0runn3r** [comment]
> [10.0.19041.746]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=88F31
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CB22
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=18A15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1D5BC
> SLInitFunc.x64=New_CSLQuery_Initialize
> .
> [10.0.19041.746-SLInit]
> bInitialized.x64 =106028
> bServerSku.x64 =10602C
> lMaxUserSessions.x64 =106030
> bAppServerAllowed.x64 =106038
> bRemoteConnAllowed.x64=106040
> bMultimonAllowed.x64 =106044
> ulMaxDebugSessions.x64=106048
> bFUSEnabled.x64 =10604C
> 
> This code works for me.

Worked for me too on Windows 10 Home.

**Comment by rstegers** [comment]
The config posted above is correct, though there is a dot on the empty line which brakes the startup process. With an empty line it works as advertised:

```
[10.0.19041.746]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F31
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.746-SLInit]
bInitialized.x64 =106028
bServerSku.x64 =10602C
lMaxUserSessions.x64 =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64 =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64 =10604C
```

**Comment by 1Pekol** [comment]
I have similar problem but with x86 version. Can someone help my? 
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5807411/termsrv.zip)

**Comment by a-skv** [comment]
> 
> 
> [rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/5807228/rdpwrap.txt)

replace -> reboot -> done
thanks

**Comment by TGeRi** [comment]
Thanks for the 10.0.19041.746 update guys!!!!!

**Comment by NadavK** [comment]
This is what worked for me:

`SingleUserOffset.x64=0CA4C`

**Comment by mh-yavari** [comment]
How do you make changes to this file??
C:\Program Files\RDP Wrapper\rdpwrap.ini
I cant replace it with your file to support my system, Can anyone help me?

**Comment by TGeRi** [comment]
- stop terminal services service
- open notepad with admin privilages: start--run--notepad --> ctrl+shit+enter
- open the ini with this notepad
- copy-paster the new ini
- put an empty new line at the end of the ini (!)
- save
- restart terminal services service

**Comment by schorschroch** [comment]
Thanks a lot!

**Comment by mh-yavari** [comment]
> * stop terminal services service
> * open notepad with admin privilages: start--run--notepad --> ctrl+shit+enter
> * open the ini with this notepad
> * copy-paster the new ini
> * put an empty new line at the end of the ini (!)
> * save
> * restart terminal services service

Thanks Thanks Thanks

**Comment by arnoldvdm** [comment]
> [10.0.19041.746]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=88F31
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CB22
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=18A15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1D5BC
> SLInitFunc.x64=New_CSLQuery_Initialize
> .
> [10.0.19041.746-SLInit]
> bInitialized.x64 =106028
> bServerSku.x64 =10602C
> lMaxUserSessions.x64 =106030
> bAppServerAllowed.x64 =106038
> bRemoteConnAllowed.x64=106040
> bMultimonAllowed.x64 =106044
> ulMaxDebugSessions.x64=106048
> bFUSEnabled.x64 =10604C
> 
> This code works for me.

Thanks for the ini change.
Does this also work for the 19042.746 ?
I posted the 19042.746 termsrv.dll before.

[termsrv.dll 19042.746](https://github.com/stascorp/rdpwrap/files/5806276/termsrv.19042.746.zip)

**Comment by TGeRi** [comment]
Don't confuse the WIN VERSION and the DLL version. Looks the same but are different!
Post a shot of your rdpconf.exe!

**Comment by TGeRi** [comment]
Yes, that is the problem!
The file version of the DLL you posted: "FileVersion: 10.0.19041.746" :)

There is no "19042.746" DLL.

You should use the [10.0.19041.746] ini as the others as your DLL is alo v10.0.19041.746!

**Comment by giovypcq** [comment]
> [10.0.19041.746]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=88F31
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CB22
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=18A15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1D5BC
> SLInitFunc.x64=New_CSLQuery_Initialize
> .
> [10.0.19041.746-SLInit]
> bInitialized.x64 =106028
> bServerSku.x64 =10602C
> lMaxUserSessions.x64 =106030
> bAppServerAllowed.x64 =106038
> bRemoteConnAllowed.x64=106040
> bMultimonAllowed.x64 =106044
> ulMaxDebugSessions.x64=106048
> bFUSEnabled.x64 =10604C
> 
> This code works for me.


Perfect, it worked very well, thanks for your help

**Comment by Moonage62** [comment]
Excellent.  Thanks!

**Comment by arnoldvdm** [comment]
![image](https://user-images.githubusercontent.com/62776508/104499014-be5f1300-55dc-11eb-8d57-20ee73d1325f.png)

**Comment by DarkGUNMAN** [comment]
Has anyone deciphered the settings for the x86 version yet?
[termsrv_19041_746_x86.zip](https://github.com/stascorp/rdpwrap/files/5813074/termsrv_19041_746_x86.zip)

**Comment by TGeRi** [comment]
@arnoldvdm this is your win version. This doesn't matter! The terminal services' version is important!

**Comment by DarkGUNMAN** [comment]
Has anyone deciphered the settings for the x86 version yet?
https://github.com/stascorp/rdpwrap/files/5813074/termsrv_19041_746_x86.zip

![RDP](https://user-images.githubusercontent.com/77432966/104561341-2a726300-563f-11eb-889e-62c0b4dd5de5.JPG)
![Termsrv_ver](https://user-images.githubusercontent.com/77432966/104561999-a8366e80-563f-11eb-9d9c-2babe64d972f.JPG)

**Comment by TGeRi** [comment]
@DarkGUNMAN : this looks ok! The "not listening" part will be resolved after a reboot. I think.

**Comment by DarkGUNMAN** [comment]
@TGeRi The updated rdpwrap.ini only has settings for the x64 version, there are no x86 settings so far.

**Comment by TGeRi** [comment]
True! I hope someone will publish the x86 ini version too!

**Comment by GVP93** [comment]
Hi.

![image](https://user-images.githubusercontent.com/77437837/104576008-f5263f00-5657-11eb-843b-535a223c4776.png)

However, when I try to connect a remote session, it says it wants to disconnect the already local running session.
GPO is ok : 4 sessions allowed.

Any idea ?

Thanks.

**Comment by TGeRi** [comment]
For the same user és for different users?

**Comment by GVP93** [comment]
Two different users, one local, one remote. Was working before late night Windows update....

**Comment by liviuancas** [comment]
![Screenshot_rdp](https://user-images.githubusercontent.com/55387490/104584214-e5fcbc80-566a-11eb-9998-7883d3d7ca48.png)

Please help, i cannot get it working with multiple connection with different users.

**Comment by TGeRi** [comment]
Did you do a full reboot?

**Comment by liviuancas** [comment]
> Did you do a full reboot?

yes... still no multiple connections, it prompts me to disconnect/logout the other user.

**Comment by TGeRi** [comment]
And if you log into an acc, does it really disconnect the other connection?

**Comment by liviuancas** [comment]
> And if you log into an acc, does it really disconnect the other connection?

it prompts the other user to accept/disconnect but i have not checked if it really disconnects after you accept to be honest with you.

i also tried to change termserv.dll, got it working but user A logged in and when user B logged in on both sessions i would have seen the screen from user B, after user B logs off the screen on user A gets back to normal. (and i restored the termserv.dll)

**Comment by philipejapa** [comment]
> para mim, não funciona no 19042.746 em vez da
> atualização de 19041 KB4598242 por sinal.
> [termsrv 19042.746.zip](https://github.com/stascorp/rdpwrap/files/5806276/termsrv.19042.746.zip)


I tried using your dll but I can't put this update in the folder where it should be (C:\\ Windows \ System32) needs authorization and I'm as an administrator

**Comment by philipejapa** [comment]
> > testado, funciona!  @arwent talvez apenas reiniciar
> 
> exatamente depois de reiniciar funcionou


do you try more than one connection?

**Comment by philipejapa** [comment]
after restarting the simultaneous connections they returned to work normally with the update of rdpwrap.ini described by the friend at the beginning of this topic

**Comment by StarfighterJ** [comment]
Run Autoupdate as Admin. it work great for me today.

**Comment by TGeRi** [comment]
Which autoupdate? What does it do?

**Comment by GVP93** [comment]
As stated yesterday and after several tries, still unable to have 2 concurrent sessions even  if:

"C:\Program Files\RDP Wrapper\autoupdate.bat" output from 15/01/2021 at  9:40:03,41 
___________________________________________
Automatic RDP Wrapper installer and updater

<check if the RDP Wrapper is up-to-date and working>

[+] TermService running.
[+] Found listener session: rdp-tcp (ID: 65536).
[+] Found windows registry entry for "rdpwrap.dll".
[+] Found file: "C:\Program Files\RDP Wrapper\rdpwrap.ini".
[+] Installed "termsrv.dll" version: 10.0.19041.746.
[*] Read last "termsrv.dll" version from the windows registry...
[+] Current "termsrv.dll v.10.0.19041.746" same as last "termsrv.dll v.10.0.19041.746".
[*] Start searching [10.0.19041.746] version entry in file "C:\Program Files\RDP Wrapper\rdpwrap.ini"...
[+] Found "termsrv.dll" version entry [10.0.19041.746] in file "C:\Program Files\RDP Wrapper\rdpwrap.ini".
[*] RDP Wrapper seems to be up-to-date and working...

**Comment by fdiperna** [comment]
> 
> 
> > [10.0.19041.746]
> > LocalOnlyPatch.x64=1
> > LocalOnlyOffset.x64=88F31
> > LocalOnlyCode.x64=jmpshort
> > SingleUserPatch.x64=1
> > SingleUserOffset.x64=0CB22
> > SingleUserCode.x64=Zero
> > DefPolicyPatch.x64=1
> > DefPolicyOffset.x64=18A15
> > DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> > SLInitHook.x64=1
> > SLInitOffset.x64=1D5BC
> > SLInitFunc.x64=New_CSLQuery_Initialize
> > .
> > [10.0.19041.746-SLInit]
> > bInitialized.x64 =106028
> > bServerSku.x64 =10602C
> > lMaxUserSessions.x64 =106030
> > bAppServerAllowed.x64 =106038
> > bRemoteConnAllowed.x64=106040
> > bMultimonAllowed.x64 =106044
> > ulMaxDebugSessions.x64=106048
> > bFUSEnabled.x64 =10604C


This code works fine for me (you must conserve the "dot ", between)
Thanks for your help.

**Comment by NAlonsoCE** [comment]
> 
> 
> > [10.0.19041.746]
> > LocalOnlyPatch.x64=1
> > LocalOnlyOffset.x64=88F31
> > LocalOnlyCode.x64=jmpshort
> > SingleUserPatch.x64=1
> > SingleUserOffset.x64=0CB22
> > SingleUserCode.x64=Zero
> > DefPolicyPatch.x64=1
> > DefPolicyOffset.x64=18A15
> > DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> > SLInitHook.x64=1
> > SLInitOffset.x64=1D5BC
> > SLInitFunc.x64=New_CSLQuery_Initialize
> > .
> > [10.0.19041.746-SLInit]
> > bInitialized.x64 =106028
> > bServerSku.x64 =10602C
> > lMaxUserSessions.x64 =106030
> > bAppServerAllowed.x64 =106038
> > bRemoteConnAllowed.x64=106040
> > bMultimonAllowed.x64 =106044
> > ulMaxDebugSessions.x64=106048
> > bFUSEnabled.x64 =10604C
> > This code works for me.
> > it works for me

Perfect, it worked very well, thanks for your help

**Comment by eslamiar** [comment]
The auto-update tool link is below and from another GH user, make sure it's placed in directory where .dll/.ini are located as well as the .exe (that are whitelisted in AV) - In my example, I placed the RDPWInst.exe into C:\Program Files\RDP Wrap* directory alongside the auto-update batch file and helper directory. Run the autoupdate as administrator (elevated). This is NOT the same update file that came with RDP Wrapper Master, another user posted the tool in another thread and it's worked consistently since Microsoft started these updates that breaks RDPWRAPPER over a month ago. 

https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

**Comment by IBIT-ZEE** [comment]
also looking for the 19041.746 x86 (32bit) settings for rdpwrap.ini
as of today none of the updates has this info...
thanks!

**Comment by johnny3young** [comment]
> [rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/5807228/rdpwrap.txt)

Ayer actualicé, tengo la versión 19041.746. Reemplacé ese archivo, reinicié y listo. Muchas gracias

**Comment by maxi32uy** [comment]
someone can fix it? i try all your post and nothing for fix this version, RDPConf appear on green but still not concurrent users.

**Comment by TGeRi** [comment]
Which version?

**Comment by maxi32uy** [comment]
10.0.19041.746

**Comment by TGeRi** [comment]
Full reboot done? How does your rdpwrapconf.exe look like?

**Comment by MarcinWerra** [comment]
Settings for the x86 and x64 version:

```
[10.0.19041.746]
LocalOnlyPatch.x86  =1
LocalOnlyOffset.x86 =B5979
LocalOnlyCode.x86   =jmpshort
SingleUserPatch.x86 =1
SingleUserOffset.x86=3BC05
SingleUserCode.x86  =nop
DefPolicyPatch.x86  =1
DefPolicyOffset.x86 =3E779
DefPolicyCode.x86   =CDefPolicy_Query_eax_ecx
SLInitHook.x86      =1
SLInitOffset.x86    =67B9A
SLInitFunc.x86      =New_CSLQuery_Initialize

LocalOnlyPatch.x64  =1
LocalOnlyOffset.x64 =88F31
LocalOnlyCode.x64   =jmpshort
SingleUserPatch.x64 =1
SingleUserOffset.x64=0CB22
SingleUserCode.x64  =Zero
DefPolicyPatch.x64  =1
DefPolicyOffset.x64 =18A15
DefPolicyCode.x64   =CDefPolicy_Query_eax_rcx
SLInitHook.x64      =1
SLInitOffset.x64    =1D5BC
SLInitFunc.x64      =New_CSLQuery_Initialize

[10.0.19041.746-SLInit]
bInitialized.x86      =D0954
bServerSku.x86        =D0958
lMaxUserSessions.x86  =D095C
bAppServerAllowed.x86 =D0964
bRemoteConnAllowed.x86=D096C
bMultimonAllowed.x86  =D0970
ulMaxDebugSessions.x86=D0974
bFUSEnabled.x86       =D0978

bInitialized.x64      =106028
bServerSku.x64        =10602C
lMaxUserSessions.x64  =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64  =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64       =10604C
```

**Comment by SGS2021** [comment]
My service state says version 10.0.19041.662 even though I've installed update KB4598242 and my Termserv.dll is version 10.0.19041.746 - it's all working just curious why the different versions?
![RDP](https://user-images.githubusercontent.com/77444620/105350214-b60d6600-5be2-11eb-8b72-207fa0ed6883.jpg)

**Comment by TGeRi** [comment]
That IS strange! Where is your termsrv.dll?

**Comment by SGS2021** [comment]
C:\Windows\System32

**Comment by TGeRi** [comment]
I don't know either how can these versions differ.

**Comment by SGS2021** [comment]
Me neither! I will uninstall RDP Wrapper and then reinstall and see if it makes a difference - can't do it now as currently logged in remotely through RDP Wrapper!

**Comment by SGS2021** [comment]
Figured it out - I had a backup copy of Termsrv.dll version 10.0.19041.662 in the same folder as the RDP Wrapper setup files on my F drive so when running RDPConf.exe it gives the shown output. I deleted the backup file and now when I run RDPConf.exe it shows 10.0.19041.746 for the service state - so all good. Attached is cut down version of rdpwrap.ini with all previous offsets removed - only works for 64 bit Windows - if you need the 32 bit offsets adding let me know.
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5850417/rdpwrap.zip)

**Comment by IBIT-ZEE** [comment]
"if you need the 32 bit offsets adding let me know."

32bits settings will be welcome... ;-)

**Comment by SGS2021** [comment]
Here you go - 32 and 64 bit ini file for latest update.
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5850510/rdpwrap.zip)

**Comment by IBIT-ZEE** [comment]
> Settings for the x86 and x64 version:
> [10.0.19041.746]

...works fine, thank you... :-)

**Comment by ForwardUntoDawn** [comment]
> [rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/5807228/rdpwrap.txt)

@LancerMar 
Works perfectly - Thanks for providing the updated INI.

**Comment by HBastet** [comment]
Hello, Thank you for the solution. It works perfectly. Is there a way to learn how to do it? Could someone explain? Thanks

**Comment by TGeRi** [comment]
https://youtu.be/FiD86tmRBtk

Not so easy. :(

**Comment by eslamiar** [comment]
> The config posted above is correct, though there is a dot on the empty line which brakes the startup process. With an empty line it works as advertised:
> 
> ```
> [10.0.19041.746]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=88F31
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CB22
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=18A15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1D5BC
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.19041.746-SLInit]
> bInitialized.x64 =106028
> bServerSku.x64 =10602C
> lMaxUserSessions.x64 =106030
> bAppServerAllowed.x64 =106038
> bRemoteConnAllowed.x64=106040
> bMultimonAllowed.x64 =106044
> ulMaxDebugSessions.x64=106048
> bFUSEnabled.x64 =10604C
> ```

This worked, I kept removing the KB that was doing this until a fix came out...however MS added "Windows Update Medic Service" that will fire up Windows Update Service even if disabled. Thank you for this .

**Comment by BlueVirus2277** [comment]
Replace with the attached INI file. Just change the .txt to .ini and it works.  This for termsrv.dll ver 10.0.19041.746

[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/5920132/rdpwrap.txt)
