### ISSUE TITLE
Versión 10.0.17763.1697 Windows 10 LTSC no found

### ISSUE THREAD

**Issue by Franckino14** [stascorp/rdpwrap#1271]
![image](https://user-images.githubusercontent.com/77365125/104387258-7b863800-5515-11eb-983b-837d9e440e46.png)

**Comment by KipFun** [comment]
termsrv.dll here 
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5807001/termsrv.zip)

**Comment by texh2s00** [comment]
nop we need ini update

**Comment by KipFun** [comment]
> nop we need ini update

))
file for help finding offsets

**Comment by Franckino14** [comment]
I achieved something but the session is closed continuously

**Comment by Franckino14** [comment]
[10.0.17763.1697]
LocalOnlyPatch.x64 =1
LocalOnlyOffset.x64 =7E381
LocalOnlyCode.x64 =jmpshort
SingleUserPatch.x64 =1

SingleUserOffset.x64=1386C
SingleUserCode.x64 =Zero
DefPolicyPatch.x64 =1
DefPolicyOffset.x64 =184F5
DefPolicyCode.x64 =CDefPolicy_Query_eax_rcx
SLInitHook.x64 =1
SLInitOffset.x64 =2198C
SLInitFunc.x64 =New_CSLQuery_Initialize

**Comment by asmtron** [comment]
add 10.0.17763.1697 (x64)
[autoupdate (recommended)](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)
_Info: please use/downlaod the latest autoupdate.bat file (added "Wait for network connection" :: important fix)_

or

[rdpwrap.ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)
```

[10.0.17763.1697]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=7E421
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=138BC
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18545
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=21A3C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.17763.1697-SLInit]
bInitialized.x64      =F3B8C
bServerSku.x64        =F3B90
lMaxUserSessions.x64  =F3B94
bAppServerAllowed.x64 =F3B9C
bRemoteConnAllowed.x64=F3BA0
bMultimonAllowed.x64  =F3BA4
ulMaxDebugSessions.x64=F3BA8
bFUSEnabled.x64       =F3BAC
```

**Comment by Franckino14** [comment]
With these adaptations to the INI, there is no status under the version, and it keeps saying that it cannot connect because there is already another user

![image](https://user-images.githubusercontent.com/77365125/104450632-28e16600-557f-11eb-93ac-bfdf4e29cdfc.png)

**Comment by Franckino14** [comment]
solved with auto update thank you very much !!!

**Comment by msc201** [comment]
I followed the install on autoupdate, but it doesn't work. Can you explain more?

**Comment by jhonkar11** [comment]
Franckino14 Friend I have the Windows Ltsc, coml I get it to work for me. Thank you
