### ISSUE TITLE
Win 10 Pro service v. 10.0.18362.1316 needs ini update

### ISSUE THREAD

**Issue by coni99** [stascorp/rdpwrap#1272]
Please provide update for ini file for:
![Snímka obrazovky (54)](https://user-images.githubusercontent.com/34895999/104388122-d715ed00-5538-11eb-8879-afa49f838401.png)
Thanks !

**Comment by Atlantis1979** [comment]
Same issue here... just had a few Windows updates come through this morning and RDPWrap has now stopped. Any help appreciated.

**Comment by arnoldvdm** [comment]
Though I'm not someone who knows how to change it.
Please upload the: **termsrv.dll** file

**Comment by Atlantis1979** [comment]
termsrv.dll
https://filebin.net/h1yfempdxolu3w7j

**Comment by AlexRus18** [comment]
https://drive.google.com/file/d/1HkN0RPpCBB-5xGv7oC_s0ZwhWyUSCOzi/view?usp=sharing

**Comment by DarkDaemon1** [comment]
same problem. Waiting for ini file or bytes array for replace

**Comment by ducphan37** [comment]
Same Problem. Pls help me!

**Comment by seedsnj** [comment]
Remote PC appears to have rebooted after performing some damn Windows Update again last night.  RDP access is no longer working. Please help to provide a new ini.  Much appreciated!

**Comment by vdovin1981** [comment]
Same problem

**Comment by asmtron** [comment]
add 10.0.18362.1316 (x64) and 10.0.19041.746 (x64)
[autoupdate (recommended)](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)
_Info: please use/downlaod the latest autoupdate.bat file (added "Wait for network connection" :: important fix)_

or

[rdpwrap.ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)

```
[10.0.18362.1316]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=83075
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DC4C
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE65
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22E9C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.1316-SLInit]
bInitialized.x64      =F6A8C
bServerSku.x64        =F6A90
lMaxUserSessions.x64  =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64  =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64       =F6AAC
```


-------------------

please upload the 32Bit variant of termsrv.dll v.10.0.18362.1316 and v.10.0.19041.746

**Comment by christian-haider** [comment]
> 0.0.18362.1316-SLIni

Can anyone confim that the settings for [10.0.18362.1316] in asmtron's post (thx for your work) are working?

I deployed them, everything seems fine, but windows don't allow a second login.

![image](https://user-images.githubusercontent.com/26204847/104450528-89cd6600-55a0-11eb-924c-237dc4279184.png)

Br,

**Comment by christian-haider** [comment]
Can anyone confim that the settings for [10.0.18362.1316] in asmtron's post (thx for your work) are working?

I deployed them, everything seems fine, but windows don't allow a second login.

![image](https://user-images.githubusercontent.com/26204847/104450892-17a95100-55a1-11eb-9ae8-eea33fa6c96f.png)


Br,

**Comment by seedsnj** [comment]
RDP works again.  You guys are awesome! 

And I still can run 2 RDP sessions each under a different Windows user ...

**Comment by jhonny003** [comment]
Muchísimas gracias!!!! Son una comunidad excelente! Justo cuando me sucede el problema, ustedes plantean la solución. Eternamente agradecido. Dependo de muchos equipos que trabajan con RDP Wrapper y cuando falla luego de alguna actualización, se complicado todo. Un abrazo grande!

**Comment by DarkDaemon1** [comment]
> add 10.0.18362.1316 (x64) and 10.0.19041.746 (x64)
> [autoupdate (recommended)](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)
> _Info: please use/downlaod the latest autoupdate.bat file (added "Wait for network connection" :: important fix)_

Thank you for fast solution!

**Comment by coni99** [comment]
> add 10.0.18362.1316 (x64) and 10.0.19041.746 (x64)
> [autoupdate (recommended)](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)
> _Info: please use/downlaod the latest autoupdate.bat file (added "Wait for network connection" :: important fix)_
> 
> or
> 
> [rdpwrap.ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)
> 
> ```
> [10.0.18362.1316]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=83075
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0DC4C
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=1FE65
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=22E9C
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.18362.1316-SLInit]
> bInitialized.x64      =F6A8C
> bServerSku.x64        =F6A90
> lMaxUserSessions.x64  =F6A94
> bAppServerAllowed.x64 =F6A9C
> bRemoteConnAllowed.x64=F6AA0
> bMultimonAllowed.x64  =F6AA4
> ulMaxDebugSessions.x64=F6AA8
> bFUSEnabled.x64       =F6AAC
> ```
> 
> please upload the 32Bit variant of termsrv.dll v.10.0.18362.1316 and v.10.0.19041.746

Big Thanks !! Problem solved !
I wish Win10 updates could be cancelled forever.. Because this problem will be here over and over again each month I presume.

**Comment by tbishop9** [comment]
Would it be possible for someone to document how to find / generate the correct offsets for future updates?

**Comment by Atlantis1979** [comment]
> Would it be possible for someone to document how to find / generate the correct offsets for future updates?

Author of RDP Wrapper posted this about how they do it:
https://www.youtube.com/watch?v=FiD86tmRBtk

**Comment by 1Pekol** [comment]
Have some solution for x86 version? Thanks
[termsrv10.0.18362.1316 x86.zip](https://github.com/stascorp/rdpwrap/files/5814666/termsrv10.0.18362.1316.x86.zip)

**Comment by TGeRi** [comment]
Thanks for the fix guys (for 10.0.18362.1316)

**Comment by m4rf1n** [comment]
> 
> 
> add 10.0.18362.1316 (x64) and 10.0.19041.746 (x64)
> [autoupdate (recommended)](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)
> _Info: please use/downlaod the latest autoupdate.bat file (added "Wait for network connection" :: important fix)_
> 
> or
> 
> [rdpwrap.ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)
> 
> ```
> [10.0.18362.1316]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=83075
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0DC4C
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=1FE65
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=22E9C
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.18362.1316-SLInit]
> bInitialized.x64      =F6A8C
> bServerSku.x64        =F6A90
> lMaxUserSessions.x64  =F6A94
> bAppServerAllowed.x64 =F6A9C
> bRemoteConnAllowed.x64=F6AA0
> bMultimonAllowed.x64  =F6AA4
> ulMaxDebugSessions.x64=F6AA8
> bFUSEnabled.x64       =F6AAC
> ```
> 
> please upload the 32Bit variant of termsrv.dll v.10.0.18362.1316 and v.10.0.19041.746

makasih suhu

**Comment by adeit** [comment]
@asmtron 

> add 10.0.18362.1316 (x64) and 10.0.19041.746 (x64)
> [autoupdate (recommended)](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)
> _Info: please use/downlaod the latest autoupdate.bat file (added "Wait for network connection" :: important fix)_
> 
> or
> 
> [rdpwrap.ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)
> 
> ```
> [10.0.18362.1316]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=83075
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0DC4C
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=1FE65
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=22E9C
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.18362.1316-SLInit]
> bInitialized.x64      =F6A8C
> bServerSku.x64        =F6A90
> lMaxUserSessions.x64  =F6A94
> bAppServerAllowed.x64 =F6A9C
> bRemoteConnAllowed.x64=F6AA0
> bMultimonAllowed.x64  =F6AA4
> ulMaxDebugSessions.x64=F6AA8
> bFUSEnabled.x64       =F6AAC
> ```
> 
> please upload the 32Bit variant of termsrv.dll v.10.0.18362.1316 and v.10.0.19041.746

Thanks for your file !

Remark and question : several other sources (including the ones in your autoupdate script) use
SingleUserOffset.x64=0DD19
instead of your
SingleUserOffset.x64=0DC4C

Can you please double check and confirm the correct value.

Thanks !

**Comment by mkovags** [comment]
> > add 10.0.18362.1316 (x64) and 10.0.19041.746 (x64)
> > [autoupdate (recommended)](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)
> > _Info: please use/downlaod the latest autoupdate.bat file (added "Wait for network connection" :: important fix)_
> > or
> > [rdpwrap.ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)
> > ```
> > [10.0.18362.1316]
> > LocalOnlyPatch.x64=1
> > LocalOnlyOffset.x64=83075
> > LocalOnlyCode.x64=jmpshort
> > SingleUserPatch.x64=1
> > SingleUserOffset.x64=0DC4C
> > SingleUserCode.x64=Zero
> > DefPolicyPatch.x64=1
> > DefPolicyOffset.x64=1FE65
> > DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> > SLInitHook.x64=1
> > SLInitOffset.x64=22E9C
> > SLInitFunc.x64=New_CSLQuery_Initialize
> > 
> > [10.0.18362.1316-SLInit]
> > bInitialized.x64      =F6A8C
> > bServerSku.x64        =F6A90
> > lMaxUserSessions.x64  =F6A94
> > bAppServerAllowed.x64 =F6A9C
> > bRemoteConnAllowed.x64=F6AA0
> > bMultimonAllowed.x64  =F6AA4
> > ulMaxDebugSessions.x64=F6AA8
> > bFUSEnabled.x64       =F6AAC
> > ```
> > 
> > 
> > please upload the 32Bit variant of termsrv.dll v.10.0.18362.1316 and v.10.0.19041.746
> 
> Big Thanks !! Problem solved !
> I wish Win10 updates could be cancelled forever.. Because this problem will be here over and over again each month I presume.

Working perfectly here. Thank you a lot!
