### ISSUE TITLE
Not working 10.0.14393.4169

### ISSUE THREAD

**Issue by pravyroxor** [stascorp/rdpwrap#1274]
This not working version - 10.0.14393.4169 is from Windows server 2016
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5808609/termsrv.zip)

**Comment by asmtron** [comment]
add 10.0.14393.4169 (x64)
[autoupdate (recommended)](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)
_Info: please use/downlaod the latest autoupdate.bat file (added "Wait for network connection" :: important fix)_

or

[rdpwrap.ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)
```

[10.0.14393.4169]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8CE51
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=25FA4
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=29825
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=CA40
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.14393.4169-SLInit]
bServerSku.x64        =E63D0
lMaxUserSessions.x64  =E63D4
bAppServerAllowed.x64 =E63D8
bInitialized.x64      =E7470
bRemoteConnAllowed.x64=E7474
bMultimonAllowed.x64  =E7478
ulMaxDebugSessions.x64=E747C
bFUSEnabled.x64       =E7480

```

________________________________

please upload also the 32Bit variant of termsrv.dll 10.0.14393.4169

**Comment by pravyroxor** [comment]
Thanks man, it works like a charm :)

**Comment by Ronus1978** [comment]
It's not working for me. I'm using the 64Bits variant.

**Comment by pravyroxor** [comment]
> It's not working for me. I'm using the 64Bits variant.

This version is definitively working with x64 version of Windows Server 2016, check your rdpwrap.ini under C:\Program Files\RDP Wrapper, if it was updated. Or use mine version...
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5814411/rdpwrap.zip)

**Comment by Ronus1978** [comment]
Oops... It's the same version, but mine is a Windows 10... Maybe that's the problem...

**Comment by pravyroxor** [comment]
Actual version for Windows 10 x64 (20H2) is 10.0.19041.746

**Comment by Ronus1978** [comment]
![image](https://user-images.githubusercontent.com/77441140/104593438-00856480-5670-11eb-97ec-0abc1d7b9aff.png)
Maybe I'm doing something wrong...
