### ISSUE TITLE
Not working on LTSC2019 [10.0.17763.1697]

### ISSUE THREAD

**Issue by houchangjun1996** [stascorp/rdpwrap#1275]
After installed January 12, 2021—KB4598230 (OS Build 17763.1697)

**Comment by sebaxakerhtc** [comment]
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/2738288a7abd7f62026b085442f2f7920fcbdd25

**Comment by MrRobot5000** [comment]
Can confirm it breaks. Looking for working offsets for INI.
Thank you

**Comment by sebaxakerhtc** [comment]
> Can confirm it breaks. Looking for working offsets for INI.
> Thank you

Do you try my ini?
Try restart after applyng my ini.
Let me know if it not work - i will try it in virtual machine

**Comment by houchangjun1996** [comment]
> [sebaxakerhtc/rdpwrap.ini@2738288](https://github.com/sebaxakerhtc/rdpwrap.ini/commit/2738288a7abd7f62026b085442f2f7920fcbdd25)

Thank you, it's working.
