### ISSUE TITLE
unsupported in [10.0.18362.1316], who has the .ini file, please

### ISSUE THREAD

**Issue by kukudelaomao** [stascorp/rdpwrap#1279]

**Comment by ZinYY** [comment]
Add following codes to `C:\Program Files\RDP Wrapper\rdpwrap.ini`:

[10.0.18362.1316]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=83075
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DC4C
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE65
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22E9C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.1316-SLInit]
bInitialized.x64      =F6A8C
bServerSku.x64        =F6A90
lMaxUserSessions.x64  =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64  =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64       =F6AAC

**Comment by kukudelaomao** [comment]
thanks
