### ISSUE TITLE
Listener state: Not listening  [not supported]

### ISSUE THREAD

**Issue by jdevora** [stascorp/rdpwrap#128]
Hi,

I have a windows insider build of Windows 10 (love  Ubuntu on Windows  ;-)  .
I had rdpwrap working after running update.bat, but after the latest Windows Update (Windows 10 Insider Preview 14383). I can´t not get it running again.

![image](https://cloud.githubusercontent.com/assets/10220619/16808706/7cb2e5cc-4915-11e6-979c-acad277ef26b.png)

![image](https://cloud.githubusercontent.com/assets/10220619/16808646/3b78cbb2-4915-11e6-9994-bffc81905a32.png)

Looking that the general update will start rolling out in a few weeks,  what can I do for help?

**Comment by binarymaster** [comment]
> what can I do for help?

Please upload `termsrv.dll` build 14383, both x86 and x64 versions. Then I'll be able to add support for it.

**Comment by heathdutton** [comment]
I'm getting the exact same issue with listener state, but with Windows 10 Home version 1511 (OS Build 10586.420)
Here's my termsrv.dll https://www.dropbox.com/s/r7ag1ni7njw1ya0/termsrv.dll?dl=0
Sorry to piggyback your issue @jdevora  :)

**Comment by binarymaster** [comment]
@heathdutton build 10586 is already added to support.
