### ISSUE TITLE
10.0.18362.1316

### ISSUE THREAD

**Issue by Alex874** [stascorp/rdpwrap#1281]
Good afternoon. RDP stopped working. Can anyone help me?

**Comment by andbener** [comment]
the same problem

**Comment by sawwd** [comment]
This might help you all https://github.com/stascorp/rdpwrap/issues/1278#issuecomment-760007826

**Comment by elihoo** [comment]
> This might help you all [#1278 (comment)](https://github.com/stascorp/rdpwrap/issues/1278#issuecomment-760007826)

it helped. Thank you!!!

**Comment by Alex874** [comment]
Thank you. It helped

**Comment by andbener** [comment]
> This might help you all [#1278 (comment)](https://github.com/stascorp/rdpwrap/issues/1278#issuecomment-760007826)

Thank you so much

**Comment by fufaeff** [comment]
Thank

**Comment by ganmosti** [comment]
Thanks! it work

**Comment by ljcdndx** [comment]
thanks a lot

**Comment by lybvest** [comment]
![image](https://user-images.githubusercontent.com/64423128/114306694-34f1ab00-9b0f-11eb-8aee-f5445a98447c.png)
 i try all this steps,but also like this ,can anybody help me to solve it, thanks!

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1278
