### ISSUE TITLE
Not working 10.0.14393.4169 Windows 10 Enterprise 2016 LTSB x64

### ISSUE THREAD

**Issue by Ronus1978** [stascorp/rdpwrap#1284]
I'd tried the updated rdpwrap.ini but it's not working.

I've seen the 10.0.14393.4169 tag, but the multisession doesn't work.

**Comment by sebaxakerhtc** [comment]
Hi. Please, attach termsrv.dll.zip
I will try to help you

**Comment by Ronus1978** [comment]
It's going to sound weird, but I can't find the file in the Windows\System32 folder...

**Comment by sebaxakerhtc** [comment]
> It's going to sound weird, but I can't find the file in the Windows\System32 folder...

There should be a termsrv.dll
You can compress it to *.zip

**Comment by Prakhov** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5816597/termsrv.zip)

**Comment by sebaxakerhtc** [comment]
> 
> 
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/5816597/termsrv.zip)

It was difficult, but very interesting!
Thank you!
Try it and let me know if it work for you ;)
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/0e8d08c2f4bae0b3fccddeb955f87a26e1671066

**Comment by KristianFernando** [comment]
> > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/5816597/termsrv.zip)
> 
> It was difficult, but very interesting!
> Thank you!
> Try it and let me know if it work for you ;)
> [sebaxakerhtc/rdpwrap.ini@0e8d08c](https://github.com/sebaxakerhtc/rdpwrap.ini/commit/0e8d08c2f4bae0b3fccddeb955f87a26e1671066)

it worked for me on windows home single language .. tks

**Comment by Ronus1978** [comment]
It's still not working...

Here is the termsrv file
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5819923/termsrv.zip)

**Comment by Ronus1978** [comment]
I've compared both termsrv file and they're the same. It must be something else i'm not seeing...

**Comment by sebaxakerhtc** [comment]
> It's still not working...

Are you sure you are using my rdpwrap.ini?
You can try my modded version of rdpwraper because 

> it worked for me

I will try to install 2016 LTSB and try it by myself. I hope the values are right

**Comment by sebaxakerhtc** [comment]
> It's still not working...

You doing something wrong.
I installed LTSB, update it to 10.0.14393.4169, installed my RDPWraper MOD and all work fine.
<img width="1336" alt="Снимок экрана 2021-01-15 в 14 46 29" src="https://user-images.githubusercontent.com/32651506/104729047-85d84a00-5740-11eb-9919-1831022a7ef7.png">

**Comment by Ronus1978** [comment]
It's puts fully supported, but when you connect it kick the local user out.

**Comment by sebaxakerhtc** [comment]
> It's puts fully supported, but when you connect it kick the local user out.

Did you try reboot?

**Comment by Ronus1978** [comment]
I had to reboot because the listener was not working when I stopped the service and restarted it.

**Comment by Ronus1978** [comment]
It's working now!!!! This PC had an outdated versión. I've even installed the autoupdater for the ini file.

Thanks everyone!!!!!
