### ISSUE TITLE
Rdp not listening (fully supported)

### ISSUE THREAD

**Issue by t1222-ops** [stascorp/rdpwrap#1287]
I’ve had to reset my whole pc due to it slowing down and when I re installed rdp wrapper it says fully supported but not listening and service stopped I really need help I’ve gave all permissions changed the ini tried every thing and I can’t figure it out please help
![image](https://user-images.githubusercontent.com/77031132/104726360-5e2ab700-572b-11eb-89d9-8a1f12ccb88e.jpg)

**Comment by xmostera** [comment]
what is the OS you are using? It seem termserv ver is very old

**Comment by t1222-ops** [comment]
I was using latest windows 10 I managed to fix by 
change "ping -n 1 google.com | find "TTL=" >nul" to "ping -n 1 google.com | find "time=" >nul"
 However now I have the problem of no login screen even tho everything’s green 
![Uploading 367E18D8-2F51-4981-8376-5D232978AB4B.jpeg…]()

**Comment by MaxMood69** [comment]
Hi, I'm interested and get to know different people, in person and through
correspondence. Don't break me. Please. I am not a victim and not
dangerous, the more I am interested and get to know you, your programs and
ideas. And I've worked a lot with my software. I find it hard to say what
exactly was cheating. If you don't mind I'll study some of your programs?

сб, 16 янв. 2021 г., 13:24 t1222-ops <notifications@github.com>:

**Comment by Hema920207** [comment]
henhao  henhaoxihuan
