### ISSUE TITLE
Rdp wrapper won’t auto update 

### ISSUE THREAD

**Issue by t1222-ops** [stascorp/rdpwrap#1288]
When I install rdp wrapper and get to the auto update bit I get this
![397B182B-4C14-42EB-A15D-8F81CC6170F3](https://user-images.githubusercontent.com/77031132/104735751-e44dfa00-5739-11eb-9734-08b1e4c5a5e4.jpeg)

**Comment by asmtron** [comment]
IPv6 ping [bug](https://github.com/stascorp/rdpwrap/pull/1160/commits/953699c802ebf1a808c605d0d37a195d06026211) fixed in the batch autoupdate.bat ...
