### ISSUE TITLE
My pc that uses this solution became "invisible" to every other device

### ISSUE THREAD

**Issue by Boerny41** [stascorp/rdpwrap#1289]
Hey guys,

I got a server with this installed and I just noticed that, beside not being able to remotedesktop onto it because it runs Win 10.0.19042.746 and the rdpwrap.ini is to old, I also can't ping it anymore.

Basically the server is invisible to every other device but the router. However from the server itself I can ping every device in my network. I got no idea what the problem is and tought maybe the edited files caus the pc to not answer when pinged?

**Comment by redneck-f25** [comment]
This is NOT an issue with RDP Wrapper. Even this is not caused by Remote
Desktop Service.

Have a look at your Firewall. Allow incomming ICMP Echo Requests (Ping).
It's denied by default settings on Windows.

**Comment by Boerny41** [comment]
Okay good to know it is the only thing I could think of. However it is possible that I just never pinged it befor and therefor did not notice it not working.

The remote desktop not working is obviously the outdated rdpwrap. Let me just check the firewall thing to make sure there isn't something else wrong with the pc or my network

**Comment by Boerny41** [comment]
So I just did the changes to the firewall and rebooted the pc but still it times out when I ping it. I know this is really not the right place to ask for advice since it doesn't have anything to do with this but since I'm allready here^^

Any ideas?

Or is there already a working RDPwrap for 10.0.19042.746 so I can alteast use remotedesktop again

**Comment by redneck-f25** [comment]
Try this:
https://www.howtogeek.com/howto/windows-vista/allow-pings-icmp-echo-request-through-your-windows-vista-firewall/amp/

**Comment by redneck-f25** [comment]
https://github.com/stascorp/rdpwrap/issues/1244

**Comment by Boerny41** [comment]
thanks this worked just fine :)
