### ISSUE TITLE
Отредактированный termsrv.dll fo 19042.746

### ISSUE THREAD

**Issue by creativ45** [stascorp/rdpwrap#1290]
I have prepared edited termsrv.dll in HEX editor for Windows 10 x64 20H2 (19042.746)
It just needs to be replaced in the path C:\Windows\System32\termsrv.dll Before replacing, stop the TermService remote desktop service, and give full rights to the termsrv.dll file to rename it, do not delete your termsrv.dll in case my file Will not work for you.

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5822166/termsrv.zip)

**Comment by FMYY** [comment]
I have replaced it in PE, now it's in normal use, thank you very much

**Comment by dekeezhe** [comment]
> I have replaced it in PE, now it's in normal use, thank you very much
Hello! What does "in PE" mean? I managed to replace termsrv.dll in system32, but it doesn't work.

**Comment by FMYY** [comment]
PE is a virtual system to memory tool, You can do anything with high authority in it。This tool is very common in China, but I don't know the specific situation in other countries

**Comment by creativ45** [comment]
Способ рабочий.
