### ISSUE TITLE
Стас, что случилось?

### ISSUE THREAD

**Issue by sebaxakerhtc** [stascorp/rdpwrap#1291]
Почему ты забросил тему? Она актуальна

**Comment by sashaqwert** [comment]
Тема актуальна
# Причина
This project has been discontinued officially but its future-proof, but the community does the ini offsets of the microsoft termsrv.dll updates. it is also only a unlocker, anything else is not guaranteed and you operate it via standard settings available; anything.
termsrv.dll version != windows build

Message source: https://t.me/rdpwrap/22825

# Updaters / обновляторы INI:
1 - https://github.com/asmtron/rdpwrap/blob/master/binary-download.md
2 - https://t.me/rdpwrap/24684
3 - https://t.me/rdpwrap/21724
4 - https://www.octaniumsw.site/2019/04/rdp-wrapper-confg-update-tool-en.html
