### ISSUE TITLE
fully supported but not work. Ver. 10.0.19041.746

### ISSUE THREAD

**Issue by 1073730081** [stascorp/rdpwrap#1292]
Wrapper state: Installed
Service state: Running
Listening state: Listening
ver. 1.5.0.0
ver. 10.0.19041.746
[fully supported]

This is what I inserted in rdpwrap.ini.
```
[10.0.19041.746]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F31
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.746-SLInit]
bInitialized.x64 =106028
bServerSku.x64 =10602C
lMaxUserSessions.x64 =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64 =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64 =10604C

```

**Everything seems OK but WHY can't it work?** I mean it will disconnect when the other user is trying to connect.
![image](https://user-images.githubusercontent.com/33291243/104798449-dcf22380-5801-11eb-8a90-660962110f2f.png)

I updated windows on 13th and did not change anything in termsrv.dll. Actually it did not work since last update, although I tried reinstall and update rdpwrap.ini.

Does someone have the same trouble? What may cause the problem?

**Comment by xmostera** [comment]
Yeah , it seem the new updates has caused some setting to be incorrect. still waiting for fixes. It happened on windows 10 pros for my PC.

**Comment by FMYY** [comment]
我看你也是一个中国用户，那么直接中文回复你：
https://github.com/stascorp/rdpwrap/issues/1290
请看这个帖子，我是在PE下进行替换的，然后就可以多用户登录了

用RDPConf 软件查看，虽然第三项，右边是红色的，但是不影响多用户登录使用。

如果你没有pe，那么 请看这个帖子：https://github.com/stascorp/rdpwrap/issues/1282

倒数第二楼，有告诉你怎么windows里面进行替换。但是挺麻烦的，建议还是走pe的方法

**Comment by 1073730081** [comment]
#1290，感谢@FMYY
