### ISSUE TITLE
10.0.18362.1316 for x86 offset (Solved)

### ISSUE THREAD

**Issue by sihow29** [stascorp/rdpwrap#1294]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5827891/termsrv.zip) (termserv 32bit windows 10 pro)

Windows 10 pro 32-bit can install RDPwrap ,everything is listening/supported, however, it shows "the number of connection is limited". 

After hours of checking, it seem this x86 version of termserv 10.0.18362.1316 is missing, Could anyone share your rdpwrap if you are using windows 10 pro 32bit? Thank you

**Comment by ZeljkoManjkas** [comment]
I found values for x86 with reverse engineering (IDA disassembler).

Can you try on your machine?


[10.0.18362.1316]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B67C6
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=83075
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=35735
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=0DC4C
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=4D679
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE65
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=5C18A
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=22E9C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.1316-SLInit]
bInitialized.x86      =D377C
bServerSku.x86        =D3780
lMaxUserSessions.x86  =D3784
bAppServerAllowed.x86 =D378C
bRemoteConnAllowed.x86=D3790
bMultimonAllowed.x86  =D3794
ulMaxDebugSessions.x86=D3798
bFUSEnabled.x86       =D379C

bInitialized.x64      =F6A8C
bServerSku.x64        =F6A90
lMaxUserSessions.x64  =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64  =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64       =F6AAC

**Comment by asmtron** [comment]
@ZeljkoManjkas
good work, the x86 entries are correct, thx

**Comment by sihow29** [comment]
Appreciated all sirs, thank you all for shares.

**Comment by usGitBen** [comment]
Thank you very much, it worked for me fine!
