### ISSUE TITLE
The cloud-drive (pcloud, googledrive, etc), NAS, Syncthing, got error when multiple RDP connection

### ISSUE THREAD

**Issue by a224515a** [stascorp/rdpwrap#1295]
The file synchronization applications, including pcloud, synology NAS, Syncthing, got error prompt when multiple RDP connection.
The functionalities of the applications and cloud-drive seem to be intact, though these error prompts are really annoying.

![20210119_1gRAIVOWWRShX](https://user-images.githubusercontent.com/4298047/105009283-42017f80-5a75-11eb-918d-22aff0b98523.png)

![20210119_1hL61FRz6Shh2](https://user-images.githubusercontent.com/4298047/105009314-49288d80-5a75-11eb-8525-c45cef85b4c7.png)

**Comment by Pici60** [comment]
A felső hibaüzebetet sehogy sem tudom eltávolítani! Minden Windows induláskor megjelenik. Tud valaki segíteni? Köszönöm!

**Comment by binarymaster** [comment]
Not RDP Wrapper problem.
