### ISSUE TITLE
Not working on 10.0.10240.18818

### ISSUE THREAD

**Issue by rfgbnfycvjkktn** [stascorp/rdpwrap#1298]
[rdpwrap_ini.zip](https://github.com/stascorp/rdpwrap/files/5851837/rdpwrap_ini.zip)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5851845/termsrv.zip)

![image](https://user-images.githubusercontent.com/43771498/105406806-be9b8600-5c4e-11eb-8930-c21670a813a3.png)

**Comment by sebaxakerhtc** [comment]
Hi. Try it and let me know if it work.
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/c944a378147bc0cbfa6929c8f1c06e0be0ad3259#diff-9e5bbfbeae79b59b305dda13323ba2b041f30f4887a84120392c479e1f7bba33

**Comment by rfgbnfycvjkktn** [comment]
nice work
