### ISSUE TITLE
Listener Satet not supported

### ISSUE THREAD

**Issue by schulzdan2002** [stascorp/rdpwrap#1301]
![image](https://user-images.githubusercontent.com/77929587/105635322-7b196580-5e62-11eb-9aa0-4be4c28a3a01.png)
Betriebsystemname	Microsoft Windows 10 Home
Version	10.0.18363 Build 18363
would be kind if smn can help me.
Greetings!

**Comment by samrustem** [comment]
Renew rdpwrap.ini to support 10.0.18362.267

https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

**Comment by schulzdan2002** [comment]
thank you bro!
