### ISSUE TITLE
10.0.19041.746 all working/running/fully supported but can not connect

### ISSUE THREAD

**Issue by bubeconee** [stascorp/rdpwrap#1304]
Hi, i have trouble connecting. It started in the morning yesterday, nothing change as far as i know.
I can connect to that computer via other screen sharing program (teamviewer) but not via RDP Wrapper.
Using it for more then 3 years and this is first time having this kind of issue.
Any help would be appreciated
![image_2021-01-26_141801](https://user-images.githubusercontent.com/78028143/105849892-4c75c900-5fe1-11eb-8444-9995648236e7.png)
.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1270 and https://github.com/stascorp/rdpwrap/issues/353
