### ISSUE TITLE
full access without permission

### ISSUE THREAD

**Issue by gar7** [stascorp/rdpwrap#131]
Just installed v1.6 and set access level to full access WITH permission using config program.  But when I remoted into this computer I was given FULL access without any permissions.  I thought that if I set permissions in shadowing mode to WITH permission I would not be able to do anything unless someone was there to grant me permission.  is this s bug or do I not understand.  This is a windows 10 home  version 10586.494 that it is installed on.

**Comment by binarymaster** [comment]
> is this s bug or do I not understand

Shadowing allows to share same session with other user, it's like remote control of a session.

When you're just connecting to a host by RDP — it isn't shadowing.
