### ISSUE TITLE
20H2 Build: 19042.746 Not working

### ISSUE THREAD

**Issue by thatisfree** [stascorp/rdpwrap#1313]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5917309/termsrv.zip)

**Comment by mariopedroSpo** [comment]
[here](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)
autoupdate will fix that

**Comment by DakenYue** [comment]
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/5917309/termsrv.zip)

sorry，i don't know how to use it.
could you tell me please？

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1270

**Comment by DakenYue** [comment]
您好，您的邮件  张越   已收到！
