### ISSUE TITLE
20H2 Build: 19041.789 Not working

### ISSUE THREAD

**Issue by vgisbert** [stascorp/rdpwrap#1314]
[termsrv 10.0.19041.789.zip](https://github.com/stascorp/rdpwrap/files/5917963/termsrv.10.0.19041.789.zip)

**Comment by vgisbert** [comment]
Thanks for your hard work

**Comment by mariopedroSpo** [comment]
[try this](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)

**Comment by nagyimre1980** [comment]
no solution so not good (

**Comment by yuasa54** [comment]
yeah for now 789 build not in the wrapper ini file. so if you have autoupdater when they update the ini you will have it

**Comment by snipper12343** [comment]
Can someone post the new INI please?

**Comment by snipper12343** [comment]
@yuasa54 can you please post your new ini file or copy the lines? thank you

**Comment by MarcinWerra** [comment]
```
[10.0.19041.789]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B59D9
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3BC45
SingleUserCode.x86=nop
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E7C9
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
SLInitHook.x86=1
SLInitOffset.x86=67BF8
SLInitFunc.x86=New_CSLQuery_Initialize

LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F41
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CA4C
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.789-SLInit]
bInitialized.x86=D0954
bServerSku.x86=D0958
lMaxUserSessions.x86=D095C
bAppServerAllowed.x86=D0964
bRemoteConnAllowed.x86=D096C
bMultimonAllowed.x86=D0970
ulMaxDebugSessions.x86=D0974
bFUSEnabled.x86=D0978

bInitialized.x64=106028
bServerSku.x64=10602C
lMaxUserSessions.x64=106030
bAppServerAllowed.x64=106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64=106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64=10604C

```

**Comment by nagyimre1980** [comment]
thx
perfect

**Comment by emanuelvittar** [comment]
It fully works! Thanks!!!!

**Comment by vgisbert** [comment]
Nice reverse engineering job. Thank you.

**Comment by dmcdivitt** [comment]
MarcinWerra's change worked for me.

**Comment by vgisbert** [comment]
It fully works! Thanks MarcinWerra !!!!

**Comment by malicon** [comment]
**MarcinWerra** Thank you. It works great.

**Comment by Lux-91** [comment]
@MarcinWerra there is any guide/tutorial/article where i can try to learn how to update the ini file by myself?
Thx :)

**Comment by MarcinWerra** [comment]
When I tried to create the parameters for the .ini file myself for the first time, I watched the video on Youtube very carefully "[Practical reverse engineering (for RDP Wrapper)](https://www.youtube.com/watch?v=FiD86tmRBtk)" 
You can read the issue "[How to add support to a new Windows build? How to get the offset for the ini file? #1098](https://github.com/stascorp/rdpwrap/issues/1098)"
or [malicon's answer](https://github.com/stascorp/rdpwrap/issues/1273#issuecomment-773673260).

Recommended tools:
- [PDB Downloader](https://techcommunity.microsoft.com/t5/iis-support-blog/pdb-downloader/ba-p/342969)
- [Ghidra](https://ghidra-sre.org/ )

**Comment by lha314981** [comment]
Single session per user
doesn't work
best regards

**Comment by owencamilo** [comment]
Single session per user
doesn't work
best regards

**Comment by MarcinWerra** [comment]
**SingleUserOffset.x64=0CB22**
```
[10.0.19041.789]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B59D9
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3BC45
SingleUserCode.x86=nop
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E7C9
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
SLInitHook.x86=1
SLInitOffset.x86=67BF8
SLInitFunc.x86=New_CSLQuery_Initialize

LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F41
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.789-SLInit]
bInitialized.x86=D0954
bServerSku.x86=D0958
lMaxUserSessions.x86=D095C
bAppServerAllowed.x86=D0964
bRemoteConnAllowed.x86=D096C
bMultimonAllowed.x86=D0970
ulMaxDebugSessions.x86=D0974
bFUSEnabled.x86=D0978

bInitialized.x64=106028
bServerSku.x64=10602C
lMaxUserSessions.x64=106030
bAppServerAllowed.x64=106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64=106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64=10604C
```

**Comment by lha314981** [comment]
wciąż się nie poprawiło
pozdr

**Comment by lha314981** [comment]
it works OK
best regards

działa
gosciu wymiatasz
pozdrowienia

**Comment by lha314981** [comment]
here more precise test

in both cases ie
SingleUserOffset.x64=0CA4C
and 
SingleUserOffset.x64=0CB22
setting Single session per user has no effect

---testing from host computer 
i'm using client 5.1.2600.2180 (distibution client doesn’t connect)

connecting with user name and password entered In client  works as Single session per user  set active
disconected session is reused

connecting with user name and password entered on logon screen  works as Single session per user  set inactive
always new session is opened

---testing from remote computer 
5.1.2600.2180 and distibution client works the same
behaviour is as above

mixing both types of login behaves as Single session per user  set inactive

regards

**Comment by MarcinWerra** [comment]
In the rdpconf.exe application, set:
```
[ ] Single session per user
(o) GUI Authentication Only
```
After that, run the command:
`RDPWInst -r`
(to restart the remote desktop service)

I tested multi-session per user by connecting using client applications from Windows 10 and XP.
![RDP-10 0 19041 789-Multisession](https://user-images.githubusercontent.com/1309148/108179909-71ec8300-7106-11eb-830d-d0951dc2f9e2.jpg)

**Comment by lha314981** [comment]
I stand by my opinion
setting Single session per user has no effect

however
Authentication mode works as follows

GUI authentication only (windows login screen) - enables many sessions for same user, each login creates a new session, disconected sessions are not reused, disconected users should be logged out via (fe.) task manager->users->logoff user

Network level authentication (client login dialog) - makes that user can open one (mostly)  rdp session,  disconected session (one) is reused, if there is more disconeccted sessions, then system behaves as above.

question is: do code which handles "Single session per user"  functionality could be patched ?
if it doesn't  works it is possible that it changes some random code 
so maybe
SingleUserPatch.x64 set to 0 
see RDPWrap.cpp line 723 and below
 
regards

ps.
p. Marcinie ma Pan już to jakkolwiek ogarnięte, może się Panu uda znaleźć właściwe rozwiązanie
życzę powodzenia
pozdrawiam

**Comment by MarcinWerra** [comment]
> @lha314981 setting Single session per user has no effect

I cannot reproduce your problem.
I tested RDPWrap on dozens of computers with version 19041.789 and it works fine with Single session per user. 
>do code which handles "Single session per user" functionality could be patched ?
>if it doesn't works it is possible that it changes some random code

https://github.com/stascorp/rdpwrap/blob/a5c64a43319e4e375b391ad42c41504bcb349b4a/src-x86-x64-Fusix/RDPWrap.cpp#L722-L740
The code between lines 722 and 740 looks fine to me.
This function does not randomly change the code.
With the patch SingleUserOffset.x64 = **0CA4C**, SingleUserCode.x64 = Zero is patched **CSessionArbitrationHelperMgr::IsSingleSessionPerUserEnabled**
![rdp SingleUserOffset_CA4C](https://user-images.githubusercontent.com/1309148/108312804-8d639680-71b7-11eb-915b-521c25e4e97f.jpg)

With the patch SingleUserOffset.x64 = **0CB22**, SingleUserCode.x64 = Zero is patched **CSessionArbitrationHelper::IsSingleSessionPerUserEnabled**
![rdp SingleUserOffset_CB22](https://user-images.githubusercontent.com/1309148/108312817-93597780-71b7-11eb-8f98-36b2a2f3333e.jpg)

But the strangest thing is that, with the patch disabled by SingleUserPatch.x64 = 0, it also works fine for single session per user and multi session connections. 

PS.  @lha314981 :-) Może prędzej się dogadamy po polsku. (Proszę odezwać się przez Messenger https://www.facebook.com/WerraMarcin/)

**Comment by Mindaugas85** [comment]
So at least RDP Wrapper is working on halfway.
RDP multisession working, but not printer redirection :( and it's very saaaad.
When copying old rdpwrap ini file - printers working, but not RDP multisession,
if but I changing ini file to support [10.0.19041.789] Windows 10 20H2 multisession - after restarting pc - printers are disappearing, only leaving to redirect "Pdf creators", One notes and others non-real printers.
Termsrv.dll I haven't modified.

INFO UPDATE
I forgot to mention one thing, 
When I'm using unsupported rdp ini file, all printers redirecting,
then updating ini file after closing and saving file without pc restarting.
then and RDP working with multisession and printers redirecting, BUT BUT BUT - when i'm doing OS restart..... redirected printers disappiering and working onlu RDP multissession :( 
IN RDP config windows -showing that everuthin green and ok...

**Comment by kotoucx** [comment]
> So at least RDP Wrapper is working on halfway.
> RDP multisession working, but not printer redirection :( and it's very saaaad.
> When copying old rdpwrap ini file - printers working, but not RDP multisession,
> if but I changing ini file to support [10.0.19041.789] Windows 10 20H2 multisession - after restarting pc - printers are disappearing, only leaving to redirect "Pdf creators", One notes and others non-real printers.
> Termsrv.dll I haven't modified.

The following worked for me ..
https://github.com/stascorp/rdpwrap/issues/874#issuecomment-818376042
I have deleted highlighted italic rows:
[10.0.19041.789]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B59D9
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3BC45
SingleUserCode.x86=nop
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E7C9
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
**_SLInitHook.x86=1
SLInitOffset.x86=67BF8
SLInitFunc.x86=New_CSLQuery_Initialize_**

LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F41
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
**_SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize_**

[10.0.19041.789-SLInit]
bInitialized.x86=D0954
bServerSku.x86=D0958
lMaxUserSessions.x86=D095C
bAppServerAllowed.x86=D0964
bRemoteConnAllowed.x86=D096C
bMultimonAllowed.x86=D0970
ulMaxDebugSessions.x86=D0974
bFUSEnabled.x86=D0978

bInitialized.x64=106028
bServerSku.x64=10602C
lMaxUserSessions.x64=106030
bAppServerAllowed.x64=106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64=106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64=10604C
