### ISSUE TITLE
Not working on 10.0.10240.18818 x86 (LTSB)

### ISSUE THREAD

**Issue by barsmutabor** [stascorp/rdpwrap#1316]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5929833/termsrv.zip)

[+] Successfully installed.
[*] Set Network Level Authentication in the windows registry...
Операция успешно завершена.
Операция успешно завершена.
[*] Start searching [10.0.10240.18818] version entry in file "c:\Program Files\RDP Wrapper\rdpwrap_new.ini"...
[-] NOT found "termsrv.dll" version entry [10.0.10240.18818] in file "c:\Program Files\RDP Wrapper\rdpwrap_new.ini"!

**Comment by asmtron** [comment]
@ barsmutabor 
add 10.0.10240.18818 x86

[autoupdate](https://github.com/stascorp/rdpwrap/pull/1160) (recommended); or only [ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)

**Comment by barsmutabor** [comment]
Thanks
