### ISSUE TITLE
What is Online mode? 

### ISSUE THREAD

**Issue by AXEBro** [stascorp/rdpwrap#132]
Can you please explain online mode? I didn't specify -o, and curious what this means..

**Comment by binarymaster** [comment]
![image](https://cloud.githubusercontent.com/assets/578406/17326445/1ed139d6-58ba-11e6-8d4a-60130367bc66.png)

When you installing RDP Wrapper first time, in **online mode** it will download [latest INI file](https://github.com/stascorp/rdpwrap/blob/master/res/rdpwrap.ini) from GitHub.

**Comment by binarymaster** [comment]
If you don't specify `-o` flag, it will extract built-in INI file from installer.

**Comment by espeditomelo** [comment]
my PC was off line (without inernet access) and when i performed the "install.bat" two files (rdpwrap.dll and rdpwrap.ini) was created on "C:\Program Files\RDP Wrapper", and in my folder with the file installers did not have any dll or ini file.
can you please explain how to these files (dll and ini) was created on "C:\Program Files\RDP Wrapper" folder?
