### ISSUE TITLE
19041.746 not working after windows update

### ISSUE THREAD

**Issue by thgoliveira0216** [stascorp/rdpwrap#1325]
Hi guys, I need a new .ini file for the version 19041.746. Its stop working after windows update on feb 05....
Thanks!

**Comment by jimiwhite1020** [comment]
Same here. It's not working 19041.746

**Comment by DJAnthon** [comment]
The same. [fully supported] but not.
kb4601319

**Comment by remmahad** [comment]
You can use:
`[10.0.19041.746]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F31
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.746-SLInit]
bInitialized.x64 =106028
bServerSku.x64 =10602C
lMaxUserSessions.x64 =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64 =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64 =10604C`

Source:
https://github.com/stascorp/rdpwrap/issues/1273#issuecomment-759309253

Fixed it for me yesterday

**Comment by thgoliveira0216** [comment]
> You can use:
> `[10.0.19041.746]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=88F31
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CB22
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=18A15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1D5BC
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.19041.746-SLInit]
> bInitialized.x64 =106028
> bServerSku.x64 =10602C
> lMaxUserSessions.x64 =106030
> bAppServerAllowed.x64 =106038
> bRemoteConnAllowed.x64=106040
> bMultimonAllowed.x64 =106044
> ulMaxDebugSessions.x64=106048
> bFUSEnabled.x64 =10604C`
> 
> Source:
> [#1273 (comment)](https://github.com/stascorp/rdpwrap/issues/1273#issuecomment-759309253)
> 
> Fixed it for me yesterday

Thank you so much! worked for me!

**Comment by DJAnthon** [comment]
I have this file already! It is not working! I did these inserts at 01/16/2021

**Comment by z3r0r4** [comment]
Works for me.
Installed via cmd,updated file, check RDPConf.exe which confirms [fully supported] and finally checked with RDPCheck.exe .
Wrapper ver 1.5.0.0
Service ver 10.0.19041.746
Thanks a lot!
