### ISSUE TITLE
19041.804 can someone help me

### ISSUE THREAD

**Issue by jonytestXD** [stascorp/rdpwrap#1326]
my updated yesterday to build 19041.804 and rdp wrapper isnt working, can some one helpme thanks by the way

**Comment by Jbarrioscuarenta** [comment]
my build 19041.804 rdp wrapper isnt working, can some one helpme thanks

**Comment by XelaUA** [comment]
some problem on build 19041.804, need working .ini

**Comment by Zykov-Alexey** [comment]
It works for me

[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5980461/rdpwrap.zip)

**Comment by master-yun-yun** [comment]
> It works for me
> 
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5980461/rdpwrap.zip)

can you upload your termsrv.dll  file？
thx

**Comment by XelaUA** [comment]
> some problem on build 19041.804, need working .ini

all good, need to be copied with administrator rights

**Comment by BALAHLOP** [comment]
Help me please, после обновление не работает, что сделать чтобы он опять работал???

**Comment by sashaqwert** [comment]
> 
> 
> It works for me
> 
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5980461/rdpwrap.zip)

This is 100% DO NOT work.
This INI is not contains 19041.804 (It's your version from RDPConf?)
termsrv.dll version != Windows version

**Comment by TheRainTime** [comment]
> It works for me
> 
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5980461/rdpwrap.zip)
It can't work on 19041.804 ,  but on 19042.804
19041.804   fully supported but NOT LISTENING

**Comment by TheRainTime** [comment]
> It works for me
> 
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5980461/rdpwrap.zip)

It cannot work on 19041.804 
Not listening but fully supported

**Comment by sk-lau** [comment]
> > It works for me
> > [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5980461/rdpwrap.zip)
> 
> It cannot work on 19041.804
> Not listening but fully supported

Please try the latest version from Amstron

You can run the update program under Administrator

**Comment by NegroCR** [comment]
Sorry i was open another case (duplicated). I have the same problem. INI file didn´t works.

**Comment by NegroCR** [comment]
Amstron INI  file don´t contains lines for 19041.804 version, only for 19041.84 version.

**Comment by Aidas777** [comment]
That's true. Amstron INI file don´t contains lines for 19041.804 version. Only for .84

**Comment by chinamonkeyking** [comment]
My "OS Build" shows "19041.804" but in "RDP Wrapper Configuration" it shows "10.0.19041.789". So I refer to https://github.com/stascorp/rdpwrap/issues/1317 and it works for me

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317
