### ISSUE TITLE
Windows 7 Not Listening

### ISSUE THREAD

**Issue by Copones** [stascorp/rdpwrap#133]
Hi,

I've read and followed the instructions in the following issues:

40
43
45

But I'm still getting this screen

![error](https://cloud.githubusercontent.com/assets/20819244/17371396/fb7f4432-599f-11e6-86a0-3e6d46cea88a.jpg)

My OS is Windows 7 x86 SP1 Ultimate if you need more data just let me know.

My RDWrapper version is 1.6.1 but I've also tried with 1.6 and 1.5 with no luck.

Any help will be really appreciated.

**Comment by leszekw83** [comment]
Update ini file. Run update.bat file

**Comment by binarymaster** [comment]
Please provide result output of this command: `sc query TermService`

**Comment by Copones** [comment]
@leszekw83 

I already done so, that's my output

RDP Wrapper Library v1.6
Installer v2.3
Copyright (C) Stas'M Corp. 2016

[*] Checking for updates...
[*] Current update date: 2016.07.22
[*] Latest update date:  2016.07.22
[*] Everything is up to date.

@binarymaster 

my apologies but my ouput is in spanish (where I'm from...) if you need some translation just le me know.

sc query TermService

NOMBRE_SERVICIO: TermService
        TIPO               : 20  WIN32_SHARE_PROCESS
        ESTADO             : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        CÓD_SALIDA_WIN32   : 0  (0x0)
        CÓD_SALIDA_SERVICIO: 0  (0x0)
        PUNTO_COMPROB.     : 0x0
        INDICACIÓN_INICIO  : 0x0

**Comment by binarymaster** [comment]
@Copones Everything is fine with your output. Since it's technical data, it doesn't differ much between languages.

TermService works without issues. Now provide output of these commands:
```
reg query "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server"
reg query "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations"
reg query "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp"
```

**Comment by Copones** [comment]
Of course,

**reg query "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server"**
 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server
    RCDependentServices    REG_MULTI_SZ    CertPropSvc\0SessionEnv
    NotificationTimeOut    REG_DWORD    0x0
    SnapshotMonitors    REG_SZ    1
    ProductVersion    REG_SZ    5.1
    AllowRemoteRPC    REG_DWORD    0x0
    DelayConMgrTimeout    REG_DWORD    0x0
    fDenyTSConnections    REG_DWORD    0x0
    StartRCM    REG_DWORD    0x0
    TSAdvertise    REG_DWORD    0x0
    DeleteTempDirsOnExit    REG_DWORD    0x0
    fSingleSessionPerUser    REG_DWORD    0x0
    PerSessionTempDir    REG_DWORD    0x0
    TSUserEnabled    REG_DWORD    0x0
    InstanceID    REG_SZ    7b47e9c6-1640-4b00-a623-e570b6f
    TSAppCompat    REG_DWORD    0x0
    SessionDirectoryActive    REG_DWORD    0x0
    RailShowallNotifyIcons    REG_DWORD    0x1
    TsxCsl    REG_DWORD    0x4
    RDPVGCInstalled    REG_DWORD    0x1

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\AddIns
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\ConnectionHandler
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\DefaultUserConfiguration
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\KeyboardType Mapping
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\Licensing Core
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\RCM
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\SessionArbitrationHelper
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\SysProcs
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\TerminalTypes
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\Utilities
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\VIDEO
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\Wds
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\PerSessionTempDirs

**reg query "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations"**


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations
    DefaultSecurity    REG_BINARY    010014809C000000A800000000000000140000000200880006000000000014000100000001010000000000050400000000001400BF030F000101000000000005120000000000140089000F00010100000000000513000000000014008100000001010000000000051400000000001800BF030F000102000000000005200000002002000000001800210100000102000000000005200000002B020000010100000000000512000000010100000000000512000000
    ConsoleSecurity    REG_BINARY    010014809C000000A800000000000000140000000200880006000000000014000100000001010000000000050400000000001400BF030F000101000000000005120000000000140089000F00010100000000000513000000000014008100000001010000000000051400000000001800BF030F000102000000000005200000002002000000001800210100000102000000000005200000002B020000010100000000000512000000010100000000000512000000
    Flags    REG_DWORD    0x1
    SelfSignedCertificate    REG_BINARY    E832E24A24CAE7F24B48013D384AB621F3738C5D
    SelfSignedCertStore    REG_SZ    Remote Desktop

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\Console
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\EH-Tcp
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp

**reg query "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp"**

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
    PortNumber    REG_DWORD    0xd3d
    SecurityLayer    REG_DWORD    0x1
    UserAuthentication    REG_DWORD    0x0
    Shadow    REG_DWORD    0x2

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\TSMMRemotingAllowedApps

I'm not a developer... (not a good one...) but it seems that the first output is very.... empty? isn't?

Thanks again.

**Comment by binarymaster** [comment]
First output is okay, but the last (`WinStations\RDP-Tcp`) lacks some important values.

Try importing this registry file (save it as `RDPTcp.reg` and import):

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp]
"AudioEnumeratorDll"="rdpendp.dll"
"Callback"=dword:00000000
"CallbackNumber"=""
"CdClass"=dword:00000000
"CdDLL"=""
"CdFlag"=dword:00000000
"CdName"=""
"CfgDll"="RDPCFGEX.DLL"
"ColorDepth"=dword:00000003
"Comment"=""
"Domain"=""
"DrawGdiplusSupportLevel"=dword:00000001
"fAllowSecProtocolNegotiation"=dword:00000001
"fAutoClientDrives"=dword:00000001
"fAutoClientLpts"=dword:00000001
"fDisableAudioCapture"=dword:00000000
"fDisableCam"=dword:00000000
"fDisableCcm"=dword:00000000
"fDisableCdm"=dword:00000000
"fDisableClip"=dword:00000000
"fDisableCpm"=dword:00000000
"fDisableEncryption"=dword:00000001
"fDisableExe"=dword:00000000
"fDisableLPT"=dword:00000000
"fEnableWinStation"=dword:00000001
"fForceClientLptDef"=dword:00000001
"fHomeDirectoryMapRoot"=dword:00000000
"fInheritAutoClient"=dword:00000001
"fInheritAutoLogon"=dword:00000001
"fInheritCallback"=dword:00000000
"fInheritCallbackNumber"=dword:00000001
"fInheritColorDepth"=dword:00000000
"fInheritInitialProgram"=dword:00000001
"fInheritMaxDisconnectionTime"=dword:00000001
"fInheritMaxIdleTime"=dword:00000001
"fInheritMaxSessionTime"=dword:00000001
"fInheritReconnectSame"=dword:00000001
"fInheritResetBroken"=dword:00000001
"fInheritSecurity"=dword:00000000
"fInheritShadow"=dword:00000000
"fLogonDisabled"=dword:00000000
"fPromptForPassword"=dword:00000000
"fReconnectSame"=dword:00000000
"fResetBroken"=dword:00000000
"fUseDefaultGina"=dword:00000000
"InitialProgram"=""
"InputBufferLength"=dword:00000800
"InteractiveDelay"=dword:00000032
"KeepAliveTimeout"=dword:00000000
"KeyboardLayout"=dword:00000000
"LanAdapter"=dword:00000000
"LoadableProtocol_Object"="{18b726bb-6fe6-4fb9-9276-ed57ce7c7cb2}"
"MaxConnectionTime"=dword:00000000
"MaxDisconnectionTime"=dword:00000000
"MaxIdleTime"=dword:00000000
"MaxInstanceCount"=dword:ffffffff
"MinEncryptionLevel"=dword:00000002
"NWLogonServer"=""
"OutBufCount"=dword:00000006
"OutBufDelay"=dword:00000064
"OutBufLength"=dword:00000212
"Password"=""
"PdClass"=dword:00000002
"PdClass1"=dword:0000000b
"PdDLL"="tdtcp"
"PdDLL1"="tssecsrv"
"PdFlag"=dword:0000004e
"PdFlag1"=dword:00000000
"PdName"="tcp"
"PdName1"="tssecsrv"
"Username"=""
"WdDLL"="rdpwd"
"WdFlag"=dword:00000036
"WdName"="Microsoft RDP 7.1"
"WdPrefix"="RDP"
"WFProfilePath"=""
"WorkDirectory"=""
"WsxDLL"="rdpwsx"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\TSMMRemotingAllowedApps]
"ehshell.exe"=dword:00000002

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\UserOverride]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\UserOverride\Control Panel]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\UserOverride\Control Panel\Desktop]
```

After import, restart Terminal Services (run `RDPWInst -r`) or reboot your PC.

**Comment by Copones** [comment]
Right now I'm not able to connect to the pc but I'll try to test ASAP.

I'll let you know the results.

thx

**Comment by Copones** [comment]
Hi, your suggestion worked but partially, now I get this screen...

![rdp](https://cloud.githubusercontent.com/assets/20819244/17415788/83de55ac-5a8b-11e6-98dd-504e719aa6da.jpg)

but when I try to connect either using the rdpcheck.exe program or directly using remote desktop, I get this error.

![error](https://cloud.githubusercontent.com/assets/20819244/17415817/a52b11be-5a8b-11e6-8511-8169594a3d05.jpg)

I think the solution is close so... a final push please?

Thanks.

**Comment by binarymaster** [comment]
Try setting another port value

**Comment by Copones** [comment]
Hi, 

After several port changes, some install/reinstalls and finally using 

sfc /scannow

I've managed to make it work. 

So you may close the issue.

As a final suggestion for future releases, if you know that there are some registry keys involved and if this keys are common, perhaps it can be a good idea to add it to assure your program will work properly. 

If those keys already exists there is no problem to add them again, and if not you will fix in computers like mine.

Thank you very much.

**Comment by binarymaster** [comment]
Sounds good!

**Comment by Farzad-Sh** [comment]
Hi,
I am using Windows 10 Home edition.
To use RDP, I installed RDP Wrapper & execute update file as well. the suggested registry codes was imported but still listener state is not listening.

Please advise.

Regards,
Farzad
