### ISSUE TITLE
In Windows 10 20H2 buid-19042.804 not working

### ISSUE THREAD

**Issue by master-yun-yun** [stascorp/rdpwrap#1330]
HI
MY WIN10 UPDATED TO 19042.804.
BUT rdpwrap NOT WORKING.
MY termsrv.dll VER 10.0.19041.789 AND rdpwrap.ini IS RIGHT.
![03](https://user-images.githubusercontent.com/79097488/108077607-aaa93f80-70a7-11eb-991d-98ffc73b437a.png)

RDPConf SHOWS ALL FINE
![01](https://user-images.githubusercontent.com/79097488/108077635-b4cb3e00-70a7-11eb-9ae9-427d18a1a954.png)

RDPCheck SHOWS THE NUMBER OF CONNECTIONS TO THIS COMPUTER IS LIMITED AND ALL CONNECTIONS ARE IN USE RIGHT NOW. TRY CONNECTING LATER OR CONTACT YOUR SYSTEM ADMINSTRATOR.

![02](https://user-images.githubusercontent.com/79097488/108077667-bd237900-70a7-11eb-8e30-faa74129e4fd.png)
![02-02](https://user-images.githubusercontent.com/79097488/108077778-dfb59200-70a7-11eb-9f38-f61a18554e10.jpg)
CAN ANYBODY HELP ME？
THX

**Comment by BALAHLOP** [comment]
i got the same problem, what i did to solve problem run gpedit.msc, then choose Computer Configuration -> Administrative Templates -> Windows Components ->Remote Desktop Services ->Remote Desktop Session Host -> Connections-> Limit number of connections, set conecctions to 999999, restart computer.... it worked for me

**Comment by BALAHLOP** [comment]
![image](https://user-images.githubusercontent.com/79150938/108167375-41a0e680-70fe-11eb-8d79-eaea3612f648.png)

**Comment by master-yun-yun** [comment]
> i got the same problem, what i did to solve problem run gpedit.msc, then choose Computer Configuration -> Administrative Templates -> Windows Components ->Remote Desktop Services ->Remote Desktop Session Host -> Connections-> Limit number of connections, set conecctions to 999999, restart computer.... it worked for me

thx
i set conecctions to 99, but it not working
set conecctions to 999999 ,it worked for me
thx again

**Comment by owencamilo** [comment]
ve coloca network kevel authentication   en el programa
