### ISSUE TITLE
18363.1379 ini notworking

### ISSUE THREAD

**Issue by albuswu** [stascorp/rdpwrap#1334]
In the configuration app, it shows up as ver. 10.0.18362.1316. Downloaded the .ini file for this version and the app says it's fully supported, however multi user RDP is not enabled. Experienced similar issue before. Need a correct .ini for 18363.1379. Thanks! 

BTW, how to get all these values in the .ini file so I don't need to check here every time I update my system?

**Comment by Dremyslesh** [comment]
My problem looks exactly the same. I really want to get a new rdwrap.ini

**Comment by RandyGrouls** [comment]
I also would like to know how to update the .ini file myself after a windows update.

**Comment by dnettoRaw** [comment]
this work for me https://github.com/stascorp/rdpwrap/issues/1278#issuecomment-760007826 
i'm in 18363.1379

**Comment by spiderspawnx** [comment]
dnetto, that one did not work for me.

However the one in this zip did, hopefully this is the one I need that will still work after an update.
https://github.com/stascorp/rdpwrap/issues/1331#issuecomment-784027203

**Comment by albuswu** [comment]
> dnetto, that one did not work for me.
> 
> However the one in this zip did, hopefully this is the one I need that will still work after an update.
> [#1331 (comment)](https://github.com/stascorp/rdpwrap/issues/1331#issuecomment-784027203)

this works for me! Thank you so much!
