### ISSUE TITLE
Please create an ini file for my termsrv.dll, all others don't work

### ISSUE THREAD

**Issue by darwinians** [stascorp/rdpwrap#1345]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6114416/termsrv.zip)

**Comment by darwinians** [comment]
I found instructions on how to change the file myself.
It works.
Thanks!
https://it-advisor.ru/thin/122-win10term.html
https://www.mysysadmintips.com/windows/clients/545-multiple-rdp-remote-desktop-sessions-in-windows-10

**Comment by sebaxakerhtc** [comment]
Closed as solved
