### ISSUE TITLE
I have all green but will only let 1 RDP session 

### ISSUE THREAD

**Issue by TWiley1** [stascorp/rdpwrap#1347]
I can't seam to post my snip

**Comment by TWiley1** [comment]
![image](https://user-images.githubusercontent.com/80543485/110986090-77ff0980-832a-11eb-81c5-d120e9d9d6ae.png)

**Comment by TWiley1** [comment]
![image](https://user-images.githubusercontent.com/80543485/110986373-d330fc00-832a-11eb-923d-b6175e5a38a8.png)

**Comment by Chendhome** [comment]
I also met the same problem today! waiting for answers. Great thanks for the kind people.

**Comment by Chendhome** [comment]
I also met the same problem today! waiting for answers. Great thanks for the kind people in advance.

**Comment by xmostera** [comment]
You may try to install 1.6.2 version of rdpwrap to see whether it's fixed or not. After that, reboot your computer.

**Comment by sdunnaway** [comment]
I am having the same issue with a windows 10 workstation. I did install the 1.6.2 version, and am still only able to login as the same user one time, if i try a second time, it pulls the same session.
![rdpwrapper_win10](https://user-images.githubusercontent.com/66383412/111721575-91c2b400-8836-11eb-9c87-6a22cea8faf9.JPG)

**Comment by edgebyte-ai** [comment]
Seems that HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server:fSingleSessionPerUser=0 no longer works.

**Comment by xikavi** [comment]
Same issue on 10.0.19041.789
Helped switching to GUI authentication, network level authentication seems to be broken

**Comment by Begin2aim** [comment]
Same issue 19041.789
All RDPconf settings are green and the max limit of sessions has been set, but still showing connections is limited and will disconnect other users.
Searching answers for hours but still no progress.

**Comment by vivanusic** [comment]
Is that solved? 
I have same issue.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1883
