### ISSUE TITLE
RDP Wrapper Configuration not supported on windows 10 pro 2004

### ISSUE THREAD

**Issue by manavalan619** [stascorp/rdpwrap#1348]
Hi all, I have windows 10 pro version 2004 and build 19041.867 Virtual Machine and I have installed the RDP while check its configuration i got (not supported) I have refer some #1326  issue but still no luck any one plz help me.

![issue](https://user-images.githubusercontent.com/56670242/111266671-e278b800-8650-11eb-97f5-26637cf7d434.png)

**Comment by LiamKarlMitchell** [comment]
Duplicate of #1342

**Comment by manavalan619** [comment]
Thanks a lot, that save my day and task.
