### ISSUE TITLE
Broken shares since anniversary update

### ISSUE THREAD

**Issue by TanMan1217** [stascorp/rdpwrap#135]
First, thank you for this fantastic product. I just upgraded to 14393 (the Windows 10 anniversary update) and upgraded all my desktops to 1.6.1 with the current ini, and my connections are all working. However, I'm now having trouble with my network shares on every desktop. Although File Explorer still shows all mapped drives, they now appear with a red X in the icon. CMD net use shows no mapped drives (or that the drive is unavailable), yet attempting to remap one of the drives returns system error 85 and says the local name is already in use. Copying files seems to work fine, and executing msi's from File Explorer works, but trying to run a program from a mapped drive in File Explorer now results in "Windows cannot access <file>" with error code 0x800704b3 (invalid network path). This is a new behavior that only started after the upgrades. Any help is appreciated.

**UPDATE**
Turning off ProtectionMode fixes the problem (after a reboot). I'm not sure why this is a problem all of a sudden since ProtectionMode has been turned on by default since Vista. I doubt this is an optimal solution, so I'm still looking forward to a response.

ProtectionMode key:
<CODE>
`HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\ProtectionMode=dword:00000000`
</CODE>

**/UPDATE**

**Comment by PistiSan** [comment]
It works, thank you!

**Comment by zaphodbeeblebroxpotu** [comment]
I have the same issue and the ProtectionMode works.  However I still get red Xs by all of the network shares until I use them.  But I am able to access them without problems.  But I have seen this issue before with other versions of Windows.

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.
