### ISSUE TITLE
The latest version is detected as a virus

### ISSUE THREAD

**Issue by Reptorian1125** [stascorp/rdpwrap#1350]
It seems that Comodo and Firefox detects the latest msi build as a virus. I can only give you this info since I can only guess that it has some codes utilized by viruses.

**Comment by python-nodejs** [comment]
its falsely recognized.

**Comment by seedsnj** [comment]
Do we have a rough understanding based on what code signatures various anti-virus and detection programs determine and tag the rdpwrap distributable (*Inst.exe) as malicious?   The tags are typically called "RemoteAdmin".

**Comment by sebaxakerhtc** [comment]
Look at readme.md about antivirus exclusions
Duplicate of https://github.com/stascorp/rdpwrap/issues/277
