### ISSUE TITLE
Updating the Ini.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [stascorp/rdpwrap#1352]
Just wondering how to get the settings for updated versions of the file.

I feel like there should also be a signature scanning tool.
That way if the particular version of the dll is not available already (Ini on git last updated Oct 11, 2018 at the time of writing this) it could then scan and attempt to find the right addresses to patch.

Is there an explanation of how to find these addresses to patch and what they do?
I already have a signature scanning library from another project I could try it out, or does the maintainer have a tool they run to already do this?

Cheers

**Comment by YxT3** [comment]
See °issue#1314 where at 2021.02.03.@14:30 MarioPedroSpo refers to AsmTron's AutoUpdater.
▪ https://github.com/stascorp/rdpwrap/issues/1314
▪ https://github.com/asmTron/rdpWrap/blob/master/binary-download.md

**Comment by LiamKarlMitchell** [comment]
Yes sorry I forgot to update my comment, the AutoUpdater bat works for me.
But I saw it on a different issue.

**Comment by sebaxakerhtc** [comment]
Closing as SOLVED
