### ISSUE TITLE
Windows 10 can't create second connection

### ISSUE THREAD

**Issue by Wymaxep2011** [stascorp/rdpwrap#1353]
Hello,
I have Windows 10 corp 2016 (extended support) RUS (official, not cracked version).
Terminal Server 10.0.14393.4169. RDP Wrapper status us [fully supported]
[https://prnt.sc/10sbvfv](url)
I'm logged in at the PC. When I try to connect via mstsc from different PC, I receive a request to disconnect the current user instead of silent creation of the second session
> Another user is signed in. If you continue, they’ll be disconnected. Do you want to sign in anyway?
Usernames are different. Default user has no password, remote desktop user obviously has one.

What could I do with this?

**Comment by LiamKarlMitchell** [comment]
Same issue, but if I use the RDP Check or mstsc.exe then it does let me in?
But the Windows Store remote desktop app does not.
Also had to connect to different ip e.g. 127.0.0.2

http://woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/
I had to use the Automatic bat.

**Comment by sebaxakerhtc** [comment]
Closing because of missing answer from @Wymaxep2011
