### ISSUE TITLE
Banking

### ISSUE THREAD

**Issue by xoom** [stascorp/rdpwrap#1355]
When I'm using rdwrap and I try to log into banking, (which opens as a secure window) the user and password fields start populating by other users also logged on the same server (multi-users). This continues to happen right through the whole banking fields. It doesn't happen ant other time when I'm browsing other websites or typing in word, note, or excel. It only happens with banking, I also have Kaspersky as my virus protection, not sure if it's relevant. Can anyone help.

**Comment by s12321** [comment]
it doesn't make sense to me, unless you share the same profile with other users during rdp session. 
could you specific which bank and browser are you using?

**Comment by sebaxakerhtc** [comment]
Closing because of missing info from @xoom
