### ISSUE TITLE
RDPCheck no login form

### ISSUE THREAD

**Issue by kolgorin** [stascorp/rdpwrap#1357]
I have the latest build of Win10: 19042.870
**RDPConf** shows that everything should be ok, **fully supported**:
![image](https://user-images.githubusercontent.com/76019677/112389987-e1e9bc80-8cf5-11eb-8b16-c8a6d713df42.png)

Unfortunately **RDPCheck** shows **no login form:**
![image](https://user-images.githubusercontent.com/76019677/112390087-09408980-8cf6-11eb-9b83-04839a0bad91.png)

I restarted the computer, tried to reinstall RDPWraper, no change.

Any idea how to fix it or what is wrong?

**Comment by bharat-mukheja** [comment]
How did you make it work on that version of windows? I just tried this but it hasn't worked for me.
![image](https://user-images.githubusercontent.com/15804045/112393190-ed1df780-8cb7-11eb-8444-2d36ea0e3840.png)

**Comment by kolgorin** [comment]
> How did you make it work on that version of windows? I just tried this but it hasn't worked for me.

Green "Fully supported" is reported when you use the recent ini file.

**Comment by kolgorin** [comment]
It seems that the missing login form might be caused by login settings: Start > Settings > Accounts > Sign-in options > turn the “Require Windows Hello sign-in for Microsoft accounts” switch OFF. 
In my case it solved the issue.
