### ISSUE TITLE
[request]maximize the RDPCheck.exe window

### ISSUE THREAD

**Issue by BlademasterQAQ** [stascorp/rdpwrap#1358]
I want to remote connect the other user on the same host, but it seems that **Windows doesn't allow remote connect myself**.

I found that the RDPCheck.exe can do it! But the window is too small. I try some way to maximize the window, such as Spy++Lite and shortcut settings, but they don't work.

Could RDPCheck.exe support maximization? Or there are other ways to remote connect myself?

**Comment by BlademasterQAQ** [comment]
I found a solution! Use Windows Remote Desktop by a local temporary ipv6 address, it can cheat Windows!

**Comment by BlademasterQAQ** [comment]
> I found a solution! Use Windows Remote Desktop by a local temporary ipv6 address, it can cheat Windows!

But it don't work now😥

**Comment by sashaqwert** [comment]
Use
127.0.0.2 127.0.0.3 127.0.0.4 ..... 127.255.255.255

**Comment by BlademasterQAQ** [comment]
> Use
> 127.0.0.2 127.0.0.3 127.0.0.4 ..... 127.255.255.255

Thank you!
