### ISSUE TITLE
Not working on w10 pro 19042.906

### ISSUE THREAD

**Issue by jjvillegax** [stascorp/rdpwrap#1361]
Hello, it is not working for me for this version. please can help me.

**Comment by hugoalves8** [comment]
Same here :/

**Comment by Phierdomenico** [comment]
same here!

**Comment by hyotio1** [comment]
same here!

**Comment by torenus** [comment]
Work on Windows 10 Pro 21H1 19043.906
![work](https://user-images.githubusercontent.com/82082739/113864629-cc739880-97b3-11eb-93d5-f7d4435e3411.jpg)

**Comment by j33333** [comment]
Hi! I have the same picture with all green panels, but Its not working more than 1 RDP connection. If I try to reboot - RDP Windows Service run not correctly and RDP not working. Please help

**Comment by Xinjaaa** [comment]
same here!It look like quite dififcult

**Comment by torenus** [comment]
> Hi! I have the same picture with all green panels, but Its not working more than 1 RDP connection. If I try to reboot - RDP Windows Service run not correctly and RDP not working. Please help

Possible problems with Windows. Run sfc / scannow

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317
