### ISSUE TITLE
RDP NOT WORKING!! PLZ HELP

### ISSUE THREAD

**Issue by GxdARKlulz** [stascorp/rdpwrap#1362]
Hey! so everything is fine and  supported etc, but when i launch the rdpchecker, it just show me this. ANY one could help me? Thanks a lot
![rdp](https://user-images.githubusercontent.com/81941692/113530513-3c0b3d00-9594-11eb-93db-dda2c060c73a.PNG)

**Comment by sebaxakerhtc** [comment]
> ANY one could help me?

Still you have this issue?

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
