### ISSUE TITLE
Windows 10 Pro 

### ISSUE THREAD

**Issue by Mangala-A** [stascorp/rdpwrap#1364]
**Hi Team,**
I have access to single rdp connection how can I enable multiple concurrent rdp connections ? 
I tried increasing limits in group policy but it doesn't work
following are my Build details

Edition: Windows 10 Pro
Version: 20H2
OS Build: 19042.867

Regards,
Mangala-A

**Comment by landaida** [comment]
I tried to use the last release of rdpwrap on "Windows 10 pro" and the message it's  "not supported"
![image](https://user-images.githubusercontent.com/5694096/114071567-41f06f00-986f-11eb-9c87-f2a818d0b4d2.png)

**Comment by Mangala-A** [comment]
Hi,

Can I know what is the stable rdpwrap version we have and which windows build does it support ?

Thanks.

**Comment by landaida** [comment]
I found a solution, this pull request work perfect!!!!
https://github.com/stascorp/rdpwrap/pull/1160

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1317
