### ISSUE TITLE
Problem updating rdpwrap.ini - impossible stop services

### ISSUE THREAD

**Issue by enry86cami** [stascorp/rdpwrap#1368]
Hi all,
I downloaded RDPwrap-v1.6.2, and installed.
With RDPconf I see: 
wrapper state: installed, 
service state: running, 
listener state: listening, 
ver 1.5.0.0, 
ver 10.0.19041.84 [not supported]

Now, I need to update the rdpwrap.ini...
When I run:
net stop termservice

I have the reply:" impossible stop the service remote desktop service"...

So I'm not able to replace the rdpwrap.ini...

Please help me

**Comment by sk-lau** [comment]
Are you running the script as Administrator?

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1004
