### ISSUE TITLE
RDP wrapper not working

### ISSUE THREAD

**Issue by google4627** [stascorp/rdpwrap#1369]
Hi,

RDP wrapper is working but we could not connect from another system local and outside the network. Please help me to find out the issue [ attached image for reference. ]

![Capture](https://user-images.githubusercontent.com/35720127/114257518-2192f280-99de-11eb-997e-68c515c58b4e.JPG)

**Comment by gamalalden** [comment]
i have same problem any one can help

**Comment by OmarLopez18** [comment]
Did u solve the problem?

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/871 and https://github.com/stascorp/rdpwrap/issues/353
