### ISSUE TITLE
ver 19042.928 not working

### ISSUE THREAD

**Issue by rem5411** [stascorp/rdpwrap#1371]
Hello can you creat a new rdpwrap.ini for this new version please ?

**Comment by cepdicom** [comment]
I need RDPWRAP for version 19042.928. Does anyone please have the solution?

**Comment by XXcage** [comment]
[19042.928](https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini)

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1317
