### ISSUE TITLE
I need RDPWRAP for version 19042.928. Does anyone please have the solution?

### ISSUE THREAD

**Issue by cepdicom** [stascorp/rdpwrap#1372]
I need RDPWRAP for version 19042.928. Does anyone please have the solution?

**Comment by allexnew** [comment]
Me too!

**Comment by allexnew** [comment]
Solution: https://github.com/asmtron/rdpwrap/blob/master/binary-download.md
After that, everything worked. 
![Снимок экрана в 2021-04-16 15-01-20](https://user-images.githubusercontent.com/42377511/115021459-a68d7880-9ec4-11eb-8639-3532e2ccd752.png)

**Comment by seedsnj** [comment]
The auto update script retrieved through the above link indeed works to enable RDP connection on 10.0.19042.928 (shown by winver). 

rdpwrap.ini downloaded by the script says however "10.0.19041.964-...". Nonetheless this works.

**Comment by affinityv** [comment]
Updated my [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file for this.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1317
