### ISSUE TITLE
修改win10 ltsc 17763.1697版本（应该适用于所有版本）termsrv.dll方法

### ISSUE THREAD

**Issue by yufei8051** [stascorp/rdpwrap#1373]
使用十六进制编辑器打开termsrv.dll，查找“39 81 3C 06 00 00 0F 84 ”极其随后的任意四个字节（在此版本中是“A18F0100”），用“B8 00 01 00 00 89 81 38 06 00 00 90”替代，保存后替换文件即可。

**Comment by yufei8051** [comment]
已修改好的文件：
下载:https://qlxfmbc.lanzous.com/iWsAIo6zvqh 密码:atgy

**Comment by lededev** [comment]
你修改了两次标题，然而，还是多了一个m

**Comment by yufei8051** [comment]
> 了

这回不多了，哈哈

**Comment by pacolala** [comment]
@yufei8051 感谢您的分享，帮助很大。现在系统更新之后，新版本10.0.17763.1971就失效了。
请问您怎么知道要在哪个位置要修改成什么的内容。
盼授渔，感谢。

**Comment by binarymaster** [comment]
This is an international project, please stick to english.
