### ISSUE TITLE
Listening but not supported Win Ver 19041

### ISSUE THREAD

**Issue by EHKemp** [stascorp/rdpwrap#1375]
Hi,
Bit of a noob here tbh, but can anyone offer guidance on how to solve this issue? I've trawled the forums and tried a lot of the most commonly suggested solutions but nothing has worked so far at all. 

Any help at all would be so deeply appreciated!

**Comment by maksimsav** [comment]
Hi,
The same situation for 10941 on my Windows 10: listening but not supported.

**Comment by StrollStars** [comment]
[10.0.19041.789的文件](https://github.com/stascorp/rdpwrap/issues/1374#issuecomment-821189263)

**Comment by EHKemp** [comment]
@StrollStars what does this do? If you wouldn't mind elabroating that would be so so helpful!

**Comment by StrollStars** [comment]
@EHKemp If you want to update the profile to support the new version, you need to provide the new version of the termsrv.dll.
Bye the way, your title is Ver 10941 or Ver 19041?

**Comment by huseyinalperenn** [comment]
> @EHKemp If you want to update the profile to support the new version, you need to provide the new version of the termsrv.dll.
> Bye the way, your title is Ver 10941 or Ver 19041?

Can you tell us how to do it?

**Comment by EHKemp** [comment]
> @EHKemp If you want to update the profile to support the new version, you need to provide the new version of the termsrv.dll.
> Bye the way, your title is Ver 10941 or Ver 19041?

Ah thank you, tbh I think I might have already tried that unsuccessfully but I'll try again just to be sure. 
And oops that's a typo! It's Ver 19041!

If that still doesn't fix it and it's still telling me it's not listening; do you have a suggested fix beyond that?
Thanks again!

**Comment by StrollStars** [comment]
@EHKemp [10.0.19041.789](https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini) is available.

**Comment by davidgxue** [comment]
@StrollStars The termsrv.dll link you sent is a repo for rdpwrap.ini not for the termsrv.dll files. Did you  mean to link something else

**Comment by StrollStars** [comment]
@Linusky17 At first that repo was uploaded for the termsrv.dll files, and then after discovering the available rdpwrap.ini file, I modified that repo, which led to a reference error here. Let me delete the link.

**Comment by sebaxakerhtc** [comment]
Seems to be applicable to https://github.com/stascorp/rdpwrap/issues/1317 because of no version is provided
