### ISSUE TITLE
Installer Exiting out without doing anything.

### ISSUE THREAD

**Issue by cookerrr** [stascorp/rdpwrap#138]
I think my computer updated recently, and maybe the wrapper ins't quite up to date with my version of windows that I'm on.  Its build 14393.10  And I didn't' see the .10 part in the version compatibility list.  Any of the apps I try just exit out instantly, and the config tool just shows not installed.  I've used this wrapper flawlessly in the past, let me know if I'm doing something wrong.

**Comment by binarymaster** [comment]
Try running Command prompt as Administrator, and start `RDPWInst -i -o` from it.

(don't forget to go to the correct directory before doing it)

Then attach an installation log here.

**Comment by cookerrr** [comment]
so it installed after running it with those switches but said that my version of termmserv.dll isn't supported. here is the output...  Do you want my termsrv.dll?

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.14393.0
[-] This version of Terminal Services is not supported.
Send your termsrv.dll to project developer for support.
[+] TermService found (pid 1588).
[*] Shared services found: CryptSvc, Dnscache, LanmanWorkstation, NlaSvc
[*] Extracting files...
[+] Extracted config -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting CryptSvc...
[*] Starting Dnscache...
[-] StartService error (code 1056).
[*] Starting LanmanWorkstation...
[*] Starting NlaSvc...
[-] StartService error (code 1056).
[*] Starting TermService...
[*] Configuring registry...
[*] Configuring firewall...
Ok.

[+] Successfully installed.

**Comment by cookerrr** [comment]
ok I'm a dummy... I didn't realize i had version 1.6 of your wrapper sitting on my desktop and was using 1.6 and not 1.6.1... Thanks for your help anyways!
