### ISSUE TITLE
Version 10.0.19042.964 Dont work - Unsuported 

### ISSUE THREAD

**Issue by CaFekt** [stascorp/rdpwrap#1383]
Version 10.0.19042.964 Dont work - Unsuported .

Thank You All.

**Comment by HydrogenDeuterium** [comment]
do u have it work?
my 19042.928 did notwork,i'm not sure if it's my fault.

**Comment by jmeile** [comment]
Worked for me with this ini file:
https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini
