### ISSUE TITLE
Version 10.0.18362.1533 Not Supported

### ISSUE THREAD

**Issue by tacid** [stascorp/rdpwrap#1386]
Hello,

Can someone please provide the rdpwrap.ini file (or patch) for Windows 10 version 10.0.18362.1533?

Thank you

**Comment by asmtron** [comment]
hi,

please upload the termsrv.dll for v.10.0.18362.1533 (x64 and x86)

thx

**Comment by tacid** [comment]
Got one from Windows 10 Pro N x64 
[termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/6402319/termsrv.dll.zip)

Don't have x86 windows installation with this version of file

**Comment by asmtron** [comment]
add 10.0.18362.1533 (x64)

recommended to use: [autoupdate](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)

or direct link to [ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)

**Comment by tacid** [comment]
Thank you very much!

**Comment by xiaqingyun** [comment]
> add 10.0.18362.1533 (x64)
> 
> recommended to use: [autoupdate](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)
> 
> or direct link to [ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)

![image](https://user-images.githubusercontent.com/44727348/120214270-d3c09b00-c266-11eb-811e-af5425ed4fc6.png)
It seems not work
