### ISSUE TITLE
19041.789 not supported Help!

### ISSUE THREAD

**Issue by fermel01** [stascorp/rdpwrap#1391]
Windows10Pro was updated and it no longer works, can someone please help me?
![not sopport](https://user-images.githubusercontent.com/83359710/116906363-c8496800-ac05-11eb-9fde-0cdee327fcf5.png)

**Comment by sk-lau** [comment]
Try replace your rdpwrap.ini with this one from the link

https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

Of course you need to temporary stop the remote desktop service. Replace the rdpwrap.ini then start the RDP service

**Comment by engr-mazdaa-razavi** [comment]
> Try replace your rdpwrap.ini with this one from the link
> 
> https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini
> 
> Of course you need to temporary stop the remote desktop service. Replace the rdpwrap.ini then start the RDP service

Hi
the latest rdpwrap.ini (21332.1000-SLInit) do not worked on windows 10 20h2.
Please help me figure out how to fix this problem.
Thanks

**Comment by engr-mazdaa-razavi** [comment]
> > Try replace your rdpwrap.ini with this one from the link
> > https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini
> > Of course you need to temporary stop the remote desktop service. Replace the rdpwrap.ini then start the RDP service
> 
> Hi
> the latest rdpwrap.ini (21332.1000-SLInit) do not worked on windows 10 20h2.
> Please help me figure out how to fix this problem.
> Thanks

![RDPWrap-Error-1400-02-14](https://user-images.githubusercontent.com/83561176/116988828-2e0d2100-ace6-11eb-94cd-6618edb0b9d1.JPG)

**Comment by engr-mazdaa-razavi** [comment]
> > > Try replace your rdpwrap.ini with this one from the link
> > > https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini
> > > Of course you need to temporary stop the remote desktop service. Replace the rdpwrap.ini then start the RDP service
> > 
> > 
> > Hi
> > the latest rdpwrap.ini (21332.1000-SLInit) do not worked on windows 10 20h2.
> > Please help me figure out how to fix this problem.
> > Thanks
> 
> ![RDPWrap-Error-1400-02-14](https://user-images.githubusercontent.com/83561176/116988828-2e0d2100-ace6-11eb-94cd-6618edb0b9d1.JPG)
![RDPWrap-Configuration-1400-02-14](https://user-images.githubusercontent.com/83561176/116989116-8fcd8b00-ace6-11eb-92fd-ae01a49fcef6.JPG)

![RDPWrap-Configuration-1400-02-14](https://user-images.githubusercontent.com/83561176/116989158-9d831080-ace6-11eb-8e8a-ca1fb278f9c2.JPG)

**Comment by engr-mazdaa-razavi** [comment]
> > Try replace your rdpwrap.ini with this one from the link
> > https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini
> > Of course you need to temporary stop the remote desktop service. Replace the rdpwrap.ini then start the RDP service
> 
> Hi
> the latest rdpwrap.ini (21332.1000-SLInit) do not worked on windows 10 20h2.
> Please help me figure out how to fix this problem.
> Thanks

![RDPWrap-Configuration-1400-02-14](https://user-images.githubusercontent.com/83561176/116989257-c73c3780-ace6-11eb-9ead-c8c0c29487be.JPG)
![RDPWrap-Error-1400-02-14](https://user-images.githubusercontent.com/83561176/116989266-c905fb00-ace6-11eb-9ab9-7290f792741d.JPG)

**Comment by fermel01** [comment]
> Intente reemplazar su rdpwrap.ini con este del enlace
> 
> https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini
> 
> Por supuesto, debe detener temporalmente el servicio de escritorio remoto. Reemplace rdpwrap.ini y luego inicie el servicio RDP

copy paste?

> > Try replace your rdpwrap.ini with this one from the link
> > https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini
> > Of course you need to temporary stop the remote desktop service. Replace the rdpwrap.ini then start the RDP service
> 
> Hi
> the latest rdpwrap.ini (21332.1000-SLInit) do not worked on windows 10 20h2.
> Please help me figure out how to fix this problem.
> Thanks

copy paste

**Comment by fermel01** [comment]
> Try replace your rdpwrap.ini with this one from the link
> 
> https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini
> 
> Of course you need to temporary stop the remote desktop service. Replace the rdpwrap.ini then start the RDP service

Copy Paste?.....
