### ISSUE TITLE
Edited termsrv.dll 10.0.19041.964 (Windows 10 build 19042.985)

### ISSUE THREAD

**Issue by creativ45** [stascorp/rdpwrap#1399]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6476476/termsrv.zip)
Work termsrv.dll 10.0.19041.964 (Windows 10 build 19042.985)
Отредактированный termsrv.dll в HEX редакторе, заменить по пути c:\Windows\System32\termsrv.dll
Edited termsrv.dll in HEX editor, replace along the way c:\Windows\System32\termsrv.dll

**Comment by wgm096350** [comment]
The rdp wrapper displays "fully supported". But still can't used by many users simultaneously, Do I have to resplace the termsrv.dll with the one you provided?
![QQ截图20210514150035](https://user-images.githubusercontent.com/24369346/118234037-5d314880-b4c5-11eb-8e98-6c197595d983.png)

**Comment by wgm096350** [comment]
> The rdp wrapper displays "fully supported". But still can't used by many users simultaneously, Do I have to resplace the termsrv.dll with the one you provided?
> ![QQ截图20210514150035](https://user-images.githubusercontent.com/24369346/118234037-5d314880-b4c5-11eb-8e98-6c197595d983.png)

After replace the termsrv.dll, multiple users are allowed. THX

**Comment by wgm096350** [comment]
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/6476476/termsrv.zip)
> Work termsrv.dll 10.0.19041.964 (Windows 10 build 19042.985)
> Отредактированный termsrv.dll в HEX редакторе, заменить по пути c:\Windows\System32\termsrv.dll
> Edited termsrv.dll in HEX editor, replace along the way c:\Windows\System32\termsrv.dll

Dear creativ45, Is there any manuals on how to modify the termsrv.dll? Maybe, I could modify the dll myself on a differenct version of Windows 10.

**Comment by TeozMac** [comment]
Hello, 
I try to copy the / term.. / file , and I got the copy permission denied, even if I run Explorer with Admin rights.

How should I do ?
THX

**Comment by creativ45** [comment]
> Hello,
> I try to copy the / term.. / file , and I got the copy permission denied, even if I run Explorer with Admin rights.
> 
> How should I do ?
> THX

Нужно дать разрешение на редактирование файла.

**Comment by creativ45** [comment]
> > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/6476476/termsrv.zip)
> > Work termsrv.dll 10.0.19041.964 (Windows 10 build 19042.985)
> > Отредактированный termsrv.dll в HEX редакторе, заменить по пути c:\Windows\System32\termsrv.dll
> > Edited termsrv.dll in HEX editor, replace along the way c:\Windows\System32\termsrv.dll
> 
> Dear creativ45, Is there any manuals on how to modify the termsrv.dll? Maybe, I could modify the dll myself on a differenct version of Windows 10.
![image](https://user-images.githubusercontent.com/3502676/118249876-4be53d80-b4bf-11eb-9480-0c62ad575721.png)
Ищем строку начинающуюся с 39 81 3C 06 00 00
Затем это
![image](https://user-images.githubusercontent.com/3502676/118250191-9ff02200-b4bf-11eb-973e-24b0614ff988.png)
Меняем на Это
![image](https://user-images.githubusercontent.com/3502676/118250315-c4e49500-b4bf-11eb-98f1-1c048764c7f4.png)
Все готово! можно заменять.

**Comment by wgm096350** [comment]
> Hello,
> I try to copy the / term.. / file , and I got the copy permission denied, even if I run Explorer with Admin rights.
> 
> How should I do ?
> THX

To replace the dll file, you have to terminate the "Remote Desktop Services", then use the following command for replacing:
`takeown.exe /f termsrv.dll
icacls.exe termsrv.dll /grant administrators:F
copy "C:\Users\hp1\Desktop\termsrv.dll" "C:\Windows\System32\"`

**Comment by wgm096350** [comment]
> > > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/6476476/termsrv.zip)
> > > Work termsrv.dll 10.0.19041.964 (Windows 10 build 19042.985)
> > > Отредактированный termsrv.dll в HEX редакторе, заменить по пути c:\Windows\System32\termsrv.dll
> > > Edited termsrv.dll in HEX editor, replace along the way c:\Windows\System32\termsrv.dll
> > 
> > 
> > Dear creativ45, Is there any manuals on how to modify the termsrv.dll? Maybe, I could modify the dll myself on a differenct version of Windows 10.
> > ![image](https://user-images.githubusercontent.com/3502676/118249876-4be53d80-b4bf-11eb-9480-0c62ad575721.png)
> > Ищем строку начинающуюся с 39 81 3C 06 00 00
> > Затем это
> > ![image](https://user-images.githubusercontent.com/3502676/118250191-9ff02200-b4bf-11eb-973e-24b0614ff988.png)
> > Меняем на Это
> > ![image](https://user-images.githubusercontent.com/3502676/118250315-c4e49500-b4bf-11eb-98f1-1c048764c7f4.png)
> > Все готово! можно заменять.

Is the string "39 81 3C 06 00 00"  fixed? In future Windows updates, do I also search for "39 81 3C 06 00 00" and replace it with "B8 00 01 00 00 89 81 38 06 00 00 90"?

**Comment by creativ45** [comment]
> > > > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/6476476/termsrv.zip)
> > > > Work termsrv.dll 10.0.19041.964 (Windows 10 build 19042.985)
> > > > Отредактированный termsrv.dll в HEX редакторе, заменить по пути c:\Windows\System32\termsrv.dll
> > > > Edited termsrv.dll in HEX editor, replace along the way c:\Windows\System32\termsrv.dll
> > > 
> > > 
> > > Dear creativ45, Is there any manuals on how to modify the termsrv.dll? Maybe, I could modify the dll myself on a differenct version of Windows 10.
> > > ![image](https://user-images.githubusercontent.com/3502676/118249876-4be53d80-b4bf-11eb-9480-0c62ad575721.png)
> > > Ищем строку начинающуюся с 39 81 3C 06 00 00
> > > Затем это
> > > ![image](https://user-images.githubusercontent.com/3502676/118250191-9ff02200-b4bf-11eb-973e-24b0614ff988.png)
> > > Меняем на Это
> > > ![image](https://user-images.githubusercontent.com/3502676/118250315-c4e49500-b4bf-11eb-98f1-1c048764c7f4.png)
> > > Все готово! можно заменять.
> 
> Is the string "39 81 3C 06 00 00" fixed? In future Windows updates, do I also search for "39 81 3C 06 00 00" and replace it with "B8 00 01 00 00 89 81 38 06 00 00 90"?

Да, эта строка не меняется уже давно в новых версиях

**Comment by binarymaster** [comment]
Editing binary files is not tolerated in our community.
