### ISSUE TITLE
Provide MSI install package

### ISSUE THREAD

**Issue by avonwyss** [stascorp/rdpwrap#14]
The wrapper is incredibly helpful, especially for system administrators. Therefore it would be great to be able to roll it out via GPO software deployment, but for that a MSI package would be needed.

**Comment by C-Duv** [comment]
+1
I would also appreciate an MSI package.
(Then I could create a [Chocolatey](https://chocolatey.org) package for rdpwrap)

**Comment by binarymaster** [comment]
@avonwyss @C-Duv can you suggest an open or free software to make MSI file from `RDPWInst.exe`?

**Comment by avonwyss** [comment]
I'd try the WiX toolset - it worked well several years ago when I did installers (but it's been so long that I don't remember much aber its usage).
http://wixtoolset.org/

**Comment by dam012345** [comment]
Advanced Installer (free version) can be used too http://www.advancedinstaller.com/
If some advanced (paid) features needed you could ask for a free licence to their support (for an open source software)

**Comment by binarymaster** [comment]
Bundled with [v1.6.2 release](https://github.com/stascorp/rdpwrap/releases/tag/v1.6.2).

**Comment by Macrisss** [comment]
Firefox and F-secure detects harmfull app on the MSI installer and on the exe of the zip file. False detects or why?

**Comment by alksily** [comment]
Installer not working

![image](https://user-images.githubusercontent.com/5148853/147137237-14e98c57-486f-4765-a9e9-b788f5eb5e78.png)

**Comment by AlexisPERROTTEY** [comment]
2025-02-21 same issue
Could we be informed about the missing required program for the MSI to run ?
