### ISSUE TITLE
how to solve "the number of connections to this computer is limited "

### ISSUE THREAD

**Issue by saidelnajjar1** [stascorp/rdpwrap#1401]
dear suppoers 

how to solve this error, see attached pictures??
![Screenshot 2021-05-20 000303](https://user-images.githubusercontent.com/57902167/118890739-84da4380-b8ff-11eb-8efb-c3ad420f3eb5.png)

![Screenshot 2021-05-20 000430](https://user-images.githubusercontent.com/57902167/118890732-80158f80-b8ff-11eb-8122-e97bee169a4a.png)

note : I change the  group policy editor to set max connections to 999999, and also I modified termsrv.dll.

**Comment by sashaqwert** [comment]
Reboot PC.
If this not helped, then replace the rdpwrap.ini https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini and reboot PC.

**Comment by saidelnajjar1** [comment]
Problem solved

**Comment by namila007** [comment]
thanks

**Comment by BrenoFariasdaSilva** [comment]
> dear suppoers
> 
> how to solve this error, see attached pictures??
> ![Screenshot 2021-05-20 000303](https://user-images.githubusercontent.com/57902167/118890739-84da4380-b8ff-11eb-8efb-c3ad420f3eb5.png)
> 
> ![Screenshot 2021-05-20 000430](https://user-images.githubusercontent.com/57902167/118890732-80158f80-b8ff-11eb-8122-e97bee169a4a.png)
> 
> note : I change the group policy editor to set max connections to 999999, and also I modified termsrv.dll.

Which windows version where you using?

**Comment by Nostramo-DFIR** [comment]
> Problem solved

Hello!
How did you solve that? I've got the same problem.

**Comment by saidelnajjar1** [comment]
Yes I solved


Best Regards

Said A.Elnajjar
Sales and Marketing Manager

Tripoli - Libya

GSM +218 91 3462402
+218 92 5178731
Skype: said_elnajjar

________________________________

**Comment by saidelnajjar1** [comment]
I solved by Uninstaller RDP WRAPPER

And download last version,  after that download rdpwrap.ini  last version,  restart pc.
________________________________

**Comment by Nostramo-DFIR** [comment]
Thanks a lot !!! I'll try

**Comment by bitboy00** [comment]
I can't solve that for win11 
![image](https://user-images.githubusercontent.com/102959722/170465417-61e369f5-e8ff-480d-8cf3-4f2091bb459f.png)
Tried to uninstall and install again (the latest Version) and also latest ini.

**Comment by sebaxakerhtc** [comment]
> Problem solved

Closed as solved
Applicable to https://github.com/stascorp/rdpwrap/issues/1883
