### ISSUE TITLE
10.0.17763.1971 not supported

### ISSUE THREAD

**Issue by sbozdag** [stascorp/rdpwrap#1404]
hi,
latest windows server 2019 update brings v. 10.0.17763.1971 and is not supported. any ini settings to fix this?
thanks

**Comment by qustfack** [comment]
Also such a problem, we are waiting for the fix

**Comment by haba-haba** [comment]
Windows 1809 LTSC 10.0.17763.1971 (after KB5003217)
Please fix rdpwrap.ini
[termsrv.dll-10.0.17763.1971-original-x64.zip](https://github.com/stascorp/rdpwrap/files/6547034/termsrv.dll-10.0.17763.1971-original-x64.zip)
The substitution(copy section) from the previous version 10.0.17763.1697 does not work

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot
This will make sure that this is the version of termsrv.dll.

**Comment by haba-haba** [comment]
The solution from sebaxakerhtc:
[https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini](url)

[10.0.17763.1971]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=77B51
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=134B9
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18075
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1AD9C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.17763.1971-SLInit]
bInitialized.x64      =ECAB4
bServerSku.x64        =ECAB8
lMaxUserSessions.x64  =ECABC
bAppServerAllowed.x64 =ECAC4
bRemoteConnAllowed.x64=ECAC8
bMultimonAllowed.x64  =ECACC
ulMaxDebugSessions.x64=ECAD0
bFUSEnabled.x64       =ECAD4

**Comment by sebaxakerhtc** [comment]
> The solution from sebaxakerhtc

If you don't need whole big file - you can use *-autogenerated.ini
For example, for this version is https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/autogenerated/10.0.17763.1971-autogenerated.ini

**Comment by sbozdag** [comment]
thx!!
