### ISSUE TITLE
10.0.21382.1 not supported | Why does my ini file not work?

### ISSUE THREAD

**Issue by TSRBerry** [stascorp/rdpwrap#1405]
Hello,

I am using a Windows Insider Build at the time to try the new wslg feature. Of course there wouldn't be any entries for my termsrv.dll available to just download, right? So I tried my best to understand the offsets of a few older versions and create my own entries for this one. But for some reason I just get greeted by the blue screen with the message "The number of connection is limited" instead. Can you help me understand what I did wrong and teach me how to properly find the offsets? I already watched the youtube video but didn't really help me which is why I looked at the older versions to begin with.

My ini entries (ignore x86 values):

> [10.0.21382.1]
> ; LocalOnlyPatch.x86=1
> ; LocalOnlyOffset.x86=B65C9
> ; LocalOnlyCode.x86=jmpshort
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=986F1
> LocalOnlyCode.x64=jmpshort
> ; SingleUserPatch.x86=1
> ; SingleUserOffset.x86=3BD35
> ; SingleUserCode.x86=nop
> SingleUserPatch.x64=1
> SingleUserOffset.x64=078E9
> SingleUserCode.x64=Zero
> ; DefPolicyPatch.x86=1
> ; DefPolicyOffset.x86=3E8A9
> ; DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=1BB75
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> ; SLInitHook.x86=1
> ; SLInitOffset.x86=687F8
> ; SLInitFunc.x86=New_CSLQuery_Initialize
> SLInitHook.x64=1
> SLInitOffset.x64=25900
> SLInitFunc.x64=New_CSLQuery_Initialize

> [10.0.21382.1-SLInit]
> ; bInitialized.x86      =D1A04
> ; bServerSku.x86        =D1A08
> ; lMaxUserSessions.x86  =D1A0C
> ; bAppServerAllowed.x86 =D1A14
> ; bRemoteConnAllowed.x86=D1A1C
> ; bMultimonAllowed.x86  =D1A20
> ; ulMaxDebugSessions.x86=D1A24
> ; bFUSEnabled.x86       =D1A28
> 
> bInitialized.x64      =11EECC
> bServerSku.x64        =11EED0
> lMaxUserSessions.x64  =11EED4
> bAppServerAllowed.x64 =11EEDC
> bRemoteConnAllowed.x64=11EEE4
> bMultimonAllowed.x64  =11EEE8
> ulMaxDebugSessions.x64=11EEF0
> bFUSEnabled.x64       =11EEF4

Here is my termsrv.dll that I currently use. [termsrv.zip](https://github.com/stascorp/rdpwrap/files/6532242/termsrv.zip)

**Comment by rdpc9** [comment]
I tried checking your offsets against the termsrv you uploaded, almost all, except one seem correct.
```
    SingleUserPatch.x64=1
    SingleUserOffset.x64=078E9
    SingleUserCode.x64=Zero
```
this one is wrong, it goes to middle of CRemoteTerminal::GetClientAddress, but it's supposed to be a patch of CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
CSessionArbitrationHelper::IsSingleSessionPerUserEnabled seems changed, but I think the right place to patch is:
```
.text:00000001800088C0                 mov     r14d, 1 ; 1 to 0
.text:00000001800088C6                 cmp     cs:?bInitialized@CSLQuery@@0HA, edi ; int CSLQuery::bInitialized
```
r14d gets written to *arg2, which is later checked by the calling code, so that should indeed be the correct patch.
Try changing
```
    SingleUserOffset.x64=078E9
```
to
```
    SingleUserOffset.x64=88C2
```

As always make sure to save the config in CR+LF mode, and if you have issues you should verify that the patches have been applied by checking the log file or dumping the termsrv.dll from memory using a tool like Task Explorer from Explorer Suite, then checking in a hex editor or IDA, or just check it with a debugger, to ensure the patches are active.

**Comment by TSRBerry** [comment]
Thank you so much!
I'll check again and hopefully this solves the issue!

**Comment by TSRBerry** [comment]
Sadly the same issue occurs.
I'll try to debug it with the methods you listed and hope I can succeed.

**Comment by sebaxakerhtc** [comment]
> Of course there wouldn't be any entries for my termsrv.dll available to just download, right?

Not right.  ;)
![Снимок экрана 2021-06-10 в 11 18 57](https://user-images.githubusercontent.com/32651506/121490534-caa99980-c9dd-11eb-9b1b-4b059684814c.png)

**Comment by TSRBerry** [comment]
Oh thank you!
Maybe I'll find out how to properly do it by comparing the correct values.
I still wasn't really able to figure out what went wrong by debugging it as described above. I know that this method gives me all the info I would need to figure it out, but I need to spend a lot more time on it, to understand what I am doing, before it could be useful to me.

**Comment by TSRBerry** [comment]
Okay, after taking a quick look I realised that my values are pretty similar and I was only missing a 0 at the beginning of one of the offsets.

Instead of:
`SingleUserOffset.x64=88C2`
It should be:
`SingleUserOffset.x64=088C2`
because we need 5 chars for the offsets.

Turns out that my own script only gave me 4 chars for this entry which is why it didn't work even on other versions.

Thank you both for helping me with this issue! It is finally working now and if I run into problems again, I think I know how to debug it now. Also the autogenerated ini files in sebaxakerhtc's repo are really helpful as it was really easy to spot my issue with them!

**Comment by sebaxakerhtc** [comment]
> because we need 5 chars for the offsets

No. It doesn't matter.

**Comment by TSRBerry** [comment]
Really?
Why wasn't it working without it? I just assumed that this must have been the reason, but if you know or have an idea about the correct one, I would like to know!

**Comment by sebaxakerhtc** [comment]
I leave zero, because of my autoscript copy latest 5 symbols.
The important data is after zeroes.
May be it wants restart...
I don't know.

**Comment by sebaxakerhtc** [comment]
May be you haven't 1 empty row in the end of file. RDPWrap need it to work normaly

**Comment by TSRBerry** [comment]
Hmm yeah. There should have been an empty row at the end while I was testing. Restart might be it, since TermService really was acting weird when I was trying to stop and start it via command line or from the services control program (the one that you can also access via Computer Management).

Anyways, it's working now, so let's not worry about it too long - thank you for your help!

**Comment by sebaxakerhtc** [comment]
I'm glad to be helpful
