### ISSUE TITLE
Any way to get update.bat to work again?

### ISSUE THREAD

**Issue by ExeRamirez** [stascorp/rdpwrap#1406]
Hello!

Whenever I run update.bat the date of the last published .ini is 10/10/2018, so I have to manually download it from this git (thanks for that).

![image](https://user-images.githubusercontent.com/42702570/119407650-e82af380-bcba-11eb-836b-07bedc7fb6d8.png)

So update.bat is no longer maintained or do I need to do some configuration?

Thanks!

**Comment by sashaqwert** [comment]
Do not use update.bat

Use autoupdate.bat: https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

Autoupdate with termsrv.dll rollback feature: https://t.me/rdpwrap/29731

**Comment by sebaxakerhtc** [comment]
Closed as answered
