### ISSUE TITLE
10.0.18363.1556 not supported

### ISSUE THREAD

**Issue by ptiterreur02** [stascorp/rdpwrap#1407]
Hi,

somebody can fix 10.0.18363.1556

thanks

**Comment by ptiterreur02** [comment]
need for x86

**Comment by ptiterreur02** [comment]
[termsrv 18363-1556 original x86.zip](https://github.com/stascorp/rdpwrap/files/6537815/termsrv.18363-1556.original.x86.zip)

**Comment by ptiterreur02** [comment]
Solve with download the last autoupdate and excecute

**Comment by TTnTTT** [comment]
so did you solved this problem?can you ask me the way，thank very much
