### ISSUE TITLE
19043.1023 is not supported

### ISSUE THREAD

**Issue by LYRbbding** [stascorp/rdpwrap#1410]
It does not work on Windows 10, 21H1, 19043 build 1023

**Comment by r-miheev** [comment]
19043.1023
[19043.1023.zip](https://github.com/stascorp/rdpwrap/files/6552237/19043.1023.zip)

**Comment by batero2000** [comment]
> 19043.1023
> [19043.1023.zip](https://github.com/stascorp/rdpwrap/files/6552237/19043.1023.zip)

Finally, thanks mate, IDK why the wrapper shows new 19043.1023 as 19041.1023, but this is working ;) .

**Comment by LYRbbding** [comment]
> 19043.1023
> [19043.1023.zip](https://github.com/stascorp/rdpwrap/files/6552237/19043.1023.zip)

Thanks a lot! It works well!

**Comment by sebaxakerhtc** [comment]
> > 19043.1023
> > [19043.1023.zip](https://github.com/stascorp/rdpwrap/files/6552237/19043.1023.zip)
> 
> Thanks a lot! It works well!

You're welcome. Close the issue if it work for you

**Comment by zhouziquan** [comment]
> 19043.1023
> [19043.1023.zip](https://github.com/stascorp/rdpwrap/files/6552237/19043.1023.zip)

Thanks a lot! It works well!

**Comment by sebaxakerhtc** [comment]
> IDK why the wrapper shows new 19043.1023 as 19041.1023

![Снимок экрана 2021-06-10 в 11 44 38](https://user-images.githubusercontent.com/32651506/121494259-3fca9e00-c9e1-11eb-83ae-cac8b2129256.png)
