### ISSUE TITLE
10.0.19041.964

### ISSUE THREAD

**Issue by xxx-zzl** [stascorp/rdpwrap#1411]
10.0.19041.964 not supported

**Comment by Costor** [comment]
More precisely: The rdpwrap.ini that was provided by asmtron 26 days ago for 10.0.19041.964 does not do the job:
rdpconf.exe shows "[fully supported]",  but  actually only one session is possible at a time.

**Comment by Zaebumba** [comment]
Try this one:
https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini
