### ISSUE TITLE
Windows Update Settings

### ISSUE THREAD

**Issue by len-ny** [stascorp/rdpwrap#1413]
I have successfully installed rdpwrap on my windows pro 10 & it works fine. Great tool. 
Although I have autoupdater enabled, I reckon the wrapper may disabled by the future windows update. 
Question: Normally when a new windows update broke it, how long it took for the developers to release the new INI? Can this happen for the windows feature update too? (apart from security update).  I need to know these in order to adjust the numbers in "Choose when update are installed" settings in windows. I want to stop windows update long enough for rdpwrap developers to resolve the issue (if any). 
Can anyone please suggest how many days I should put in the settings?

**Comment by sebaxakerhtc** [comment]
Not an rdpwrapper issue
