### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by OneLoveDrew** [stascorp/rdpwrap#1416]
It says that there's a virus when I try to download "RDPWInst-v1.6.2.msi". Any ideas why?

**Comment by ghost** [comment]
> It says that there's a virus when I try to download "RDPWInst-v1.6.2.msi". Any ideas why?

What says that?

**Comment by OneLoveDrew** [comment]
> 
> 
> > It says that there's a virus when I try to download "RDPWInst-v1.6.2.msi". Any ideas why?
> 
> What says that?

My browser, also a few virus protectors I scanned it with at different times (Malwarebytes/Windows Defender, etc) and I'm wondering why.

**Comment by sashaqwert** [comment]
This is not a virus.
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=HackTool:Win32/RDPWrap&ThreatID=2147726445
This is "HackTool" (A tool for bypassing software limitations of the OS or third-party software.)

-------------------

P. S.: DO NOT USE MSI, use ZIP and autoupdate or rdpwrup

**Comment by OneLoveDrew** [comment]
So, it's good to know there aren't any malicious strings in the code, but how do I go about getting my Windows Defender to shut up about it?

**Comment by sashaqwert** [comment]
> how do I go about getting my Windows Defender to shut up about it?

Read defender documentation: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by OneLoveDrew** [comment]
> 
> 
> > how do I go about getting my Windows Defender to shut up about it?
> 
> Read defender documentation: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

Thank you! :)
