### ISSUE TITLE
18363.1556 not supported for x64

### ISSUE THREAD

**Issue by NewCoder1c** [stascorp/rdpwrap#1418]
Hi, 18363.1556 not supported for win 10 x64. Sombody please can fix it update?

**Comment by andmaltes** [comment]
Hi, same happening here 
![image](https://user-images.githubusercontent.com/38090766/120125289-c8de0b80-c17d-11eb-8408-c9c57e052931.png)

**Comment by felixpro1** [comment]
Same problem, please help.

**Comment by Li-yu-luo** [comment]
you can uninstall KB5003169 (OS internal version 18363.1556) and revert back to version 1500. This action can be found in System Settings - Update and Security - by viewing the Update History. (Reboot required)

**Comment by felixpro1** [comment]
Thank you, uninstalling the update worked. But the system will catch it again and I'm not in the position to disable the updates. Will the INI be corrected later to work with this Version of Windows?

**Comment by Li-yu-luo** [comment]
I'm also a beginner. If you want to turn off Windows updates, you can change the system's date such as 2023 (right click on the bottom corner of the desktop), then go to the Settings to defer the update, and finally change the date back to network synchronization.

**Comment by Li-yu-luo** [comment]
Oh, it's not able to call a shutdown. A shutdown must be complete. It just can be called delay.

**Comment by sebaxakerhtc** [comment]
> Thank you, uninstalling the update worked. But the system will catch it again and I'm not in the position to disable the updates. Will the INI be corrected later to work with this Version of Windows?

Update Windows and attach your termsrv.dll

**Comment by felixpro1** [comment]
[termsrv.txt](https://github.com/stascorp/rdpwrap/files/6735934/termsrv.txt)
Sorry for late reply. I attached the file, just need to be renamed to termsrv.dll

**Comment by sebaxakerhtc** [comment]
> 
> 
> [termsrv.txt](https://github.com/stascorp/rdpwrap/files/6735934/termsrv.txt) Sorry for late reply. I attached the file, just need to be renamed to termsrv.dll

https://github.com/sebaxakerhtc/rdpwrap.ini/commit/4bb6124b27ae382e2b17c109695e40769b790c95
