### ISSUE TITLE
Win 10 19041.985 not supported

### ISSUE THREAD

**Issue by erlake** [stascorp/rdpwrap#1421]
Can anyone help us with ini files for win 10 version 19041.985?
Thank you.

**Comment by erlake** [comment]
Can anyone help us with ini files for win 10 version 19041.985?
Thank you.

**Comment by JosXa** [comment]
Having troubles with 19043 aswell

**Comment by sashaqwert** [comment]
Please, attach your RDPconf screenshot.

**Comment by erlake** [comment]
The system was updated to version 19041.964 in the next topic downloaded ini. Thanks everyone
