### ISSUE TITLE
Windows 10 Version  10.0.19042.1052

### ISSUE THREAD

**Issue by juanwrs** [stascorp/rdpwrap#1426]
Please could you share us ini file for Windows 10 Version 10.0.19042.1052?

Thank you.

**Comment by lgzcoollg** [comment]
I have same problem.,need .ini

**Comment by klittapw** [comment]
Please could you share us ini file for Windows 10 Version 10.0.19042.1052?

Thank you.

**Comment by demicus** [comment]
wait for ini 10.0.19042.1052
please(

**Comment by satsis** [comment]
need same (

**Comment by 111blackjack111** [comment]
Also need. 10.0.19042.1052 - not working. But also I would like to learn to do it myself.

**Comment by 111blackjack111** [comment]
@sebaxakerhtc can you help please?

**Comment by sebaxakerhtc** [comment]
> @sebaxakerhtc can you help please?

Of cource. Attach your zipped termsrv.dll

With fast view Windows 10 Version 10.0.19042.1052 uses termsrv.dll 10.0.19041.1023.

Solution is here:

https://github.com/stascorp/rdpwrap/issues/1420

**Comment by 111blackjack111** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6629393/termsrv.zip)

**Comment by demicus** [comment]
https://drive.google.com/file/d/1HgGtGhkYUn8yPxE3_9vrqyTVql1iXMPH/view?usp=sharing

**Comment by sebaxakerhtc** [comment]
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/6629393/termsrv.zip)

As i said in my last comment –  my solution is already exists
Just use my ini
Always look at the tremsrv.dll version. Not Windows version! (File=>Properties)
![Снимок экрана 2021-06-10 в 11 00 05](https://user-images.githubusercontent.com/32651506/121487991-50781580-c9db-11eb-8612-b5822c322b05.png)

**Comment by demicus** [comment]
its work for me
snk!

**Comment by 111blackjack111** [comment]
Thx. all is working

**Comment by lgzcoollg** [comment]
> > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/6629393/termsrv.zip)
> 
> As i said in my last comment – my solution is already exists
> Just use my ini
> Always look at the tremsrv.dll version. Not Windows version! (File=>Properties)
> ![Снимок экрана 2021-06-10 в 11 00 05](https://user-images.githubusercontent.com/32651506/121487991-50781580-c9db-11eb-8612-b5822c322b05.png)

I Use ur .dll and ur .ini as below. I get fully supported but not listening! 
:https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/autogenerated/10.0.19041.1023-autogenerated.in

![image](https://user-images.githubusercontent.com/48668011/121632195-23973180-cab3-11eb-9b75-eeea4319a601.png)

**Comment by sebaxakerhtc** [comment]
> supported but not listening!

Restart your PC.
Better way for resolving problems faster -
[telegram](https://t.me/rdpwrap) and [discord](https://discord.gg/N27yFftWP3)

**Comment by sebaxakerhtc** [comment]
> I Use ur .dll

What means your .dll?
I make just .ini – you shouldn't to replace your original termsrv.dll

**Comment by chandansomani** [comment]
I have updated my rdpwrap.ini

![image](https://user-images.githubusercontent.com/23182738/121656282-f3549080-cabc-11eb-971f-e5590693a1a1.png)

Shows all clear 

but RDP-Check is stucked at login screen & also i cant login from other computer

![image](https://user-images.githubusercontent.com/23182738/121656188-dddf6680-cabc-11eb-9c26-edfc0c6538cc.png)

**Comment by ForwardUntoDawn** [comment]
> > @sebaxakerhtc can you help please?
> 
> Of cource. Attach your zipped termsrv.dll
> 
> With fast view Windows 10 Version 10.0.19042.1052 uses termsrv.dll 10.0.19041.1023.
> 
> Solution is here:
> 
> #1420

@sebaxakerhtc -
Working perfectly over here - Thanks for sharing the updated INI.

**Comment by ghost** [comment]
Windows 10 Version 10.0.19043.1052 x64 bit termsrv.dll please

**Comment by sebaxakerhtc** [comment]
> Windows 10 Version 10.0.19043.1052 x64 bit termsrv.dll please

look latest comment. Don't look Windows version. Look termsrv.dll versiin

**Comment by robertodan** [comment]
I used the ini, got Fully supported, but "Not listening"... Restart didn't help. What else can I try? 

Thanks

**Comment by sebaxakerhtc** [comment]
> I used the ini, got Fully supported, but "Not listening"... Restart didn't help. What else can I try?
> 
> Thanks

Download modded version of autoupdate from my discord or official telegram group

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1420
