### ISSUE TITLE
10.0.19041.1023 32bits SO

### ISSUE THREAD

**Issue by dreddArg** [stascorp/rdpwrap#1428]
Hi, 

Does anyone know the x86 offsets?

I leave termsrv.dll 32bits version
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6633901/termsrv.zip)

**Comment by ghost** [comment]
x64 termsrv.dll please

**Comment by contras2k** [comment]
[10.0.19041.1023]
LocalOnlyPatch.x86    =1
LocalOnlyOffset.x86   =B6419
LocalOnlyCode.x86     =jmpshort
SingleUserPatch.x86   =1
SingleUserOffset.x86  =3BD35
SingleUserCode.x86    =nop
DefPolicyPatch.x86    =1
DefPolicyOffset.x86   =3E8A9
DefPolicyCode.x86     =CDefPolicy_Query_eax_ecx
SLInitHook.x86        =1
SLInitOffset.x86      =68598
SLInitFunc.x86        =New_CSLQuery_Initialize

LocalOnlyPatch.x64    =1
LocalOnlyOffset.x64   =89C51
LocalOnlyCode.x64     =jmpshort
SingleUserPatch.x64   =1
SingleUserOffset.x64  =0CB22
SingleUserCode.x64    =Zero
DefPolicyPatch.x64    =1
DefPolicyOffset.x64   =18A15
DefPolicyCode.x64     =CDefPolicy_Query_eax_rcx
SLInitHook.x64        =1
SLInitOffset.x64      =1DFDC
SLInitFunc.x64        =New_CSLQuery_Initialize

[10.0.19041.1023-SLInit]
bServerSku.x86        =D1A08
bRemoteConnAllowed.x86=D1A1C
bFUSEnabled.x86       =D1A28
bAppServerAllowed.x86 =D1A14
bMultimonAllowed.x86  =D1A20
lMaxUserSessions.x86  =D1A0C
ulMaxDebugSessions.x86=D1A24
bInitialized.x86      =D1A04

bInitialized.x64      =107108
bServerSku.x64        =10710C
lMaxUserSessions.x64  =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64  =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64       =10712C

**Comment by dreddArg** [comment]
> 
> 
> [10.0.19041.1023]
> LocalOnlyPatch.x86 =1
> LocalOnlyOffset.x86 =B6419
> LocalOnlyCode.x86 =jmpshort
> SingleUserPatch.x86 =1
> SingleUserOffset.x86 =3BD35
> SingleUserCode.x86 =nop
> DefPolicyPatch.x86 =1
> DefPolicyOffset.x86 =3E8A9
> DefPolicyCode.x86 =CDefPolicy_Query_eax_ecx
> SLInitHook.x86 =1
> SLInitOffset.x86 =68598
> SLInitFunc.x86 =New_CSLQuery_Initialize
> 
> LocalOnlyPatch.x64 =1
> LocalOnlyOffset.x64 =89C51
> LocalOnlyCode.x64 =jmpshort
> SingleUserPatch.x64 =1
> SingleUserOffset.x64 =0CB22
> SingleUserCode.x64 =Zero
> DefPolicyPatch.x64 =1
> DefPolicyOffset.x64 =18A15
> DefPolicyCode.x64 =CDefPolicy_Query_eax_rcx
> SLInitHook.x64 =1
> SLInitOffset.x64 =1DFDC
> SLInitFunc.x64 =New_CSLQuery_Initialize
> 
> [10.0.19041.1023-SLInit]
> bServerSku.x86 =D1A08
> bRemoteConnAllowed.x86=D1A1C
> bFUSEnabled.x86 =D1A28
> bAppServerAllowed.x86 =D1A14
> bMultimonAllowed.x86 =D1A20
> lMaxUserSessions.x86 =D1A0C
> ulMaxDebugSessions.x86=D1A24
> bInitialized.x86 =D1A04
> 
> bInitialized.x64 =107108
> bServerSku.x64 =10710C
> lMaxUserSessions.x64 =107110
> bAppServerAllowed.x64 =107118
> bRemoteConnAllowed.x64=107120
> bMultimonAllowed.x64 =107124
> ulMaxDebugSessions.x64=107128
> bFUSEnabled.x64 =10712C

thank you!
