### ISSUE TITLE
Version 10.0.19041.1023 of Tetmsrv.dll 32 bits 

### ISSUE THREAD

**Issue by SamuFr** [stascorp/rdpwrap#1429]
I updated Rdpwrap.ini with Autoupdater from Asmtron.
With Termsrv.dll 32 bits 10.0.19041.1023 I have "listening" and "supported" but it is not possible to open more than one session (if a session is already open locally, I get "Another user is signed in ... ").
It is likely that Rdpwrap.ini has a wrong address in the x86 section ...

Who would have the solution ?

**Comment by contras2k** [comment]
See issues https://github.com/stascorp/rdpwrap/issues/1428 or https://github.com/stascorp/rdpwrap/issues/1420

**Comment by SamuFr** [comment]
Thank you so much, Contras2k, for the code. Now it's OK with Win 32 bits.
In fact, the whole 32-bit sections for 10.0.19041.1023 were missing.
I don't understand why "listening" and "supported" could be green without these sections...

**Comment by dionelfer** [comment]
alguien tiene el .ini de la version 10.0.19041.1023 para el windows Home 64 bits ??

**Comment by dreddArg** [comment]
> 19041.1023
@dionelfer
probaste este? https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini

**Comment by sebaxakerhtc** [comment]
applicable to https://github.com/stascorp/rdpwrap/issues/1420
