### ISSUE TITLE
Win10 Pro 19043.1055 - not working

### ISSUE THREAD

**Issue by mrkaktuz** [stascorp/rdpwrap#1432]
Need rdpwrap.ini for 19043.1055.
How can I help for a quick solution?

**Comment by dcbasso** [comment]
I need too!

**Comment by dreddArg** [comment]
guys, attach termsvr.dll

**Comment by mrkaktuz** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6652923/termsrv.zip)

**Comment by ghost** [comment]
@mrkaktuz not working :(  Win10 Pro x64 bit 19043.1055

**Comment by mrkaktuz** [comment]
@emrahsari44, it's an original file from 19043.1055. I upload it for @dreddArg

**Comment by dreddArg** [comment]
hey @contras2k could you help this guy please?

**Comment by ghost** [comment]
termsvr.dll 64 bit ?

**Comment by mrkaktuz** [comment]
> termsvr.dll 64 bit ?

Yes, [here](https://github.com/stascorp/rdpwrap/issues/1432#issuecomment-861170052) is archive with original termsrv.dll from Win10 Pro 19043.1055 64 bit.

**Comment by contras2k** [comment]
@mrkaktuz definitly not - attached termsrv.dll is version 19041.1023 x64

**Comment by talynone** [comment]
> @mrkaktuz definitly not - attached termsrv.dll is version 19041.1023 x64

I think the confusion is that Windows 10 1943.1055 uses version 19041.1023 of the termsrv.dll (At least that's true in my Windows installation).

**Comment by contras2k** [comment]
Highly likely. In such a case adding a section from #1420 should solve the problem.

**Comment by talynone** [comment]
> Highly likely. In such a case adding a section from #1420 should solve the problem.

Yep, using the ini from : 
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

And restarting rdp wrapper with the command:
RDPWInst.exe -r

worked for me.

**Comment by mrkaktuz** [comment]
> Windows 10 1943.1055 uses version 19041.1023 of the termsrv.dll

Indeed, I have the same)


> section from #1420 should solve the problem
> Yep, using the ini from

Yes, it worked for me too.


Thanks everyone for the help!
