### ISSUE TITLE
window 10 Home  x86 - 19041.1023 - not listening

### ISSUE THREAD

**Issue by juliomgm** [stascorp/rdpwrap#1435]
I was able to get it supported using:
#1420

But i am unable to get it to listening state.

![rdp](https://user-images.githubusercontent.com/34062888/122038038-1b016c80-cdcd-11eb-9f12-5b3edc1f3c3a.png)

My termsrv.dll - [termsrv.zip](https://github.com/stascorp/rdpwrap/files/6654904/termsrv.zip)

Thanks.

**Comment by juliomgm** [comment]
I replace the termsrv.dll with the one on:  #1428

and it works.

**Comment by oauthul** [comment]
How did you replace the file? Whenever I try to replace the file it keeps showing the file is being used in another program.
Thanks for your help.

**Comment by juliomgm** [comment]
You need to stop remote desktop service and take ownership of the file.

**Comment by sebaxakerhtc** [comment]
applicable to https://github.com/stascorp/rdpwrap/issues/1420
