### ISSUE TITLE
10.0.19041.1023 fully supported but cannot rdp multiple times  =( 

### ISSUE THREAD

**Issue by XoRoNioX** [stascorp/rdpwrap#1436]
Updated the rdpwrap.ini as per suggest - rdpconf shows fully supported. All green  rdp works for 1 login, but multiple logins give the sign out other user message as per the screen shot below. Any advice?  Tried uninstalling and reinstalling the rdpwrap as admin, no help. Also am logged in as admin.  
![Capture](https://user-images.githubusercontent.com/86011883/122252627-831d8480-ce99-11eb-803c-2d45934be754.JPG)

**Comment by sebaxakerhtc** [comment]
Which version of rdpwrap are you use?

**Comment by XoRoNioX** [comment]
1.6.2 I believe - where do I check?

**Comment by XoRoNioX** [comment]
Looks like my OS build changed after a restart & pending update change.  Dont know if that matters at all?  Still shows fully supported.

![Capture](https://user-images.githubusercontent.com/86011883/122257995-9121d400-ce9e-11eb-9df8-2c01b7d3c02d.JPG)

**Comment by sk-lau** [comment]
I think I have the same problem

I will attached the termsrv.dll zipped format

Still no concurrently rdp although supported
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6667461/termsrv.zip)

**Comment by wsbao** [comment]
> 
> 
> Looks like my OS build changed after a restart & pending update change. Dont know if that matters at all? Still shows fully supported.
> 
> ![Capture](https://user-images.githubusercontent.com/86011883/122257995-9121d400-ce9e-11eb-9df8-2c01b7d3c02d.JPG)

I have similar situation as you. I just restarted the computer, and then the multi-user login works.

**Comment by mikopia** [comment]
i'm having the same issue on 32 bit.
any suggestions?

**Comment by satriyoshinobi** [comment]
[RDPWrap windows 10 pro 20h2 19042.1052.zip](https://github.com/stascorp/rdpwrap/files/6699588/RDPWrap.windows.10.pro.20h2.19042.1052.zip)
I can, please try. for termsrv.ini try copy & replace to windows\system32
I hope this helps

**Comment by JDavey59** [comment]
Looks to me like x86 entry are missing. Are developers only interested in 64 bit now? I suspect that the rdpconf is picking up the 64 bit config and thinks that everything is hunky dorey. 

Or am I totally wrong. I have the same issue. Termsrv 10.0.19041.1023 shows Listening [Fully Supported] but only allows a single RDP session at a time. Can someone put a working ini in the autoupdate path so us mere mortals can get back to using RDPWrapper again.

**Comment by sebaxakerhtc** [comment]
applicable to https://github.com/stascorp/rdpwrap/issues/1420
