### ISSUE TITLE
19043.1055 not supported

### ISSUE THREAD

**Issue by Melnick704** [stascorp/rdpwrap#1438]

**Comment by Melnick704** [comment]
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/6668004/rdpwrap.zip)
It's work for 19043.1055

**Comment by Zykov-Alexey** [comment]
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/6668004/rdpwrap.zip)
> It's work for 19043.1055

It's work for me!

**Comment by xpc0938** [comment]
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/6668004/rdpwrap.zip)
> It's work for 19043.1055

Thank you! It's ok for me.[10.0.19043.1055]

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1420
