### ISSUE TITLE
install.bat "Access is denied."

### ISSUE THREAD

**Issue by i32stG** [stascorp/rdpwrap#1440]
I get the error "Access is denied" in cmd when i run the install.bat file (both normally and as an admin).
Consequently RDPconf.exe shows "wrapper state" as not installed.
Any assistance would be appreciated.
Thanks

**Comment by redneck-f25** [comment]
Try to install surun and select "Start as administrator" from the context
menu.

https://kay--bruns-de.translate.goog/wp/software/surun/?_x_tr_sch=http&_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=ajax,nv

i32stG ***@***.***> schrieb am Do., 17. Juni 2021, 20:36:

**Comment by i32stG** [comment]
Yes i tried to run as administrator as stated in my original post.
This is now solved - the issue was with windows defender blocking the installer from running.
Fix was to right click the install.bat file and "scan with microsoft defender", then allow the app through defender in there.
