### ISSUE TITLE
10.0.19043.1052 can't work

### ISSUE THREAD

**Issue by icetomato** [stascorp/rdpwrap#1441]
10.0.19043.1052 can't work

![image](https://user-images.githubusercontent.com/13519059/122529016-91150600-d04f-11eb-9d1d-3f74e898124d.png)

**Comment by oauthul** [comment]
Same problem, don't know how to fix.

**Comment by pudizhen** [comment]
me too.

**Comment by nbsoftware** [comment]
I have been able to make it work with https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1420
