### ISSUE TITLE
Not working on 21h1 - 19043.1052

### ISSUE THREAD

**Issue by BrenoFariasdaSilva** [stascorp/rdpwrap#1442]
Anyone has the fix for this version?

**Comment by sashaqwert** [comment]
https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

**Comment by alfonsoramirzz** [comment]
Thank you @sashaqwert, it works for me

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1420
