### ISSUE TITLE
can't start listener on 19042.631

### ISSUE THREAD

**Issue by ShengzhenFu** [stascorp/rdpwrap#1445]
@ksmyth my windows 10 version is 19042.631
kindly help to add support on `rdpwrap.ini` thanks

![image](https://user-images.githubusercontent.com/30173222/122691801-46200c00-d264-11eb-9533-6b08121f7047.png)
![image](https://user-images.githubusercontent.com/30173222/122691806-51733780-d264-11eb-96b6-0f8594798661.png)

**Comment by sashaqwert** [comment]
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by rbutleg** [comment]
> https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

Thank you!!!

**Comment by ShengzhenFu** [comment]
it works, thank you man. really appreciated. give you a star
