### ISSUE TITLE
Primary mouse scrolling over RDP client

### ISSUE THREAD

**Issue by batero2000** [stascorp/rdpwrap#1448]
Hi everyone, so I'm having an issue on version 19043.1052 (or 19041.1052 as some people indicate), so that when the primary PC is been used, the mouse scrolling over that PC scrolls my client PC as well, but not viceversa 🤷‍♂️, that's weird. Anyways now I've discovered this wrapper I'm not uninstalling it, I use it every day for work and studying with a crappy PC 'cause everyone needs the primary one, is great!

**Comment by sebaxakerhtc** [comment]
Not an rdpwrapper issue. Same with embeded RDP solution
