### ISSUE TITLE
19043.1081 win 21H1 - Not Supported

### ISSUE THREAD

**Issue by giordan-net** [stascorp/rdpwrap#1449]
Wrapper state: Installed - ver. 1.5.0.0
Service state: Runnig - ver. 10.0.19041.1081
Listener state: Listening - NOT SUPPORTED

Can anyone solve not supported state, plz

**Comment by XilinWang0108** [comment]
It worked on my device.
[https://github.com/stascorp/rdpwrap/issues/1447](url) , the seccond method
or
[https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini](url)
or, this file
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/6698720/rdpwrap.zip)
![1](https://user-images.githubusercontent.com/76676235/123031613-2250f780-d417-11eb-8495-8f30928ffc6d.jpg)


> Wrapper state: Installed - ver. 1.5.0.0
> Service state: Runnig - ver. 10.0.19041.1081
> Listener state: Listening - NOT SUPPORTED
> 
> Can anyone solve not supported state, plz

**Comment by djdoolky76** [comment]
> It worked on my device.
> [https://github.com/stascorp/rdpwrap/issues/1447](url) , the seccond method
> or
> [https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini](url)
> or, this file
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/6698720/rdpwrap.zip)
> ![1](https://user-images.githubusercontent.com/76676235/123031613-2250f780-d417-11eb-8495-8f30928ffc6d.jpg)
> 
> > Wrapper state: Installed - ver. 1.5.0.0
> > Service state: Runnig - ver. 10.0.19041.1081
> > Listener state: Listening - NOT SUPPORTED
> > Can anyone solve not supported state, plz

thank you so much, it worked 
![image](https://user-images.githubusercontent.com/30578879/123032482-993ac000-d418-11eb-9be0-3e36056470b5.png)

**Comment by E-Nonso** [comment]
Mine is not working. How did you do it?

**Comment by ghost** [comment]
It worked. Thanks.

**Comment by giordan-net** [comment]
It works with new file
rdpwrap.zip
thank you all
