### ISSUE TITLE
Cant connect on Win 8.1 SL

### ISSUE THREAD

**Issue by antonvavi** [stascorp/rdpwrap#145]
When i try to connect to PC with win 8.1. single language with rdp wrapper, it displays a message that the user is not a member of the group Remote Desktop Control. How to add user to this group if in this windows edition have no gpedit? I tried NET LOCALGROUP "Пользователи удаленного рабочего стола" User /ADD but it useless. Thnx.

**Comment by enviromine-user** [comment]
перезагрузи эвм и проверь в группе ли ты

**Comment by antonvavi** [comment]
пробовал перегружать
сообщение:
https://pp.vk.me/c604620/v604620367/3a94/Q8Ozm_lxRv8.jpg

**Comment by enviromine-user** [comment]
покажи скрин RDPConf
типо этого [https://cloud.mail.ru/public/CPuu/JNLJjnGmX]

**Comment by enviromine-user** [comment]
на целевом хосте есть учётка User ?

**Comment by antonvavi** [comment]
В общем разобрался тип учётной записи был Обыкновенная, поменял на Администратор всё заработало. Администратор видимо по умолчанию состоит в группе Пользователи удаленного рабочего стола.

**Comment by antonvavi** [comment]
Есть ли для домашних редакций win легальная альтернатива gpedit?

**Comment by enviromine-user** [comment]
Нет, гугли как добраться до нужного тебе параметра через реестр ОС.

**Comment by binarymaster** [comment]
В `README.md` описано, как добавить группу "Пользователи удаленного рабочего стола".

В редакции Single Language этой группы изначально нет.
