### ISSUE TITLE
Disconnected every 5 minutes

### ISSUE THREAD

**Issue by xoom** [stascorp/rdpwrap#1450]
Hi, I need urgent help, I'm running win 10 pro build 10.0.19041.1023. About 5 minutes after connecting I am disconnected. This started about 2 weeks ago with a windows update. Have not had any issues prior to that update.
![image](https://user-images.githubusercontent.com/81209386/123106717-38dd6a00-d47c-11eb-91fe-a35971f547ab.png)

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1509
