### ISSUE TITLE
10.0.19041.1081 windows 10 x86 home not listening

### ISSUE THREAD

**Issue by 0142929** [stascorp/rdpwrap#1451]
![231406](https://user-images.githubusercontent.com/896793/123162147-eea6b980-d478-11eb-8470-83ff7eff5056.png)

**Comment by 0142929** [comment]
still can not find a solution, does anyone have 10.0.19041.1081 working?

**Comment by Fangfang6606** [comment]
restart?😂

**Comment by RobertRoberts2020** [comment]
I need this too

**Comment by dreddArg** [comment]
me too

i'm attaching termsrv.dll x86 for my hero @contras2k , could you help us? :)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6779563/termsrv.zip)

**Comment by rtasisto** [comment]
Yo descargue el ini que pasaron y lo renombré a rpdwrap_new.ini en una
carpeta afuera del RDP Wrap.   Lo copio sin pegar aún.
Ejecuto el autoupdate.bat y ni bien veo que descargó el rdpwrap_new.ini le
doy pegar y sustituir archivo.
El autoupdate hace todo el trabajo sin tener que parar servicios
manualmente o reiniciar servidor.

**Comment by contras2k** [comment]
@dreddArg, actually there is no need to attach .dl for me, I've got a handful of 32bit systems.

So here is full section:

[10.0.19041.1081]
LocalOnlyPatch.x86   =1
LocalOnlyOffset.x86  =B66B9
LocalOnlyCode.x86    =jmpshort
SingleUserPatch.x86  =1
SingleUserOffset.x86 =3BD25
SingleUserCode.x86   =nop
DefPolicyPatch.x86   =1
DefPolicyOffset.x86  =3E899
DefPolicyCode.x86    =CDefPolicy_Query_eax_ecx
SLInitHook.x86       =1
SLInitOffset.x86     =68809
SLInitFunc.x86       =New_CSLQuery_Initialize

LocalOnlyPatch.x64   =1
LocalOnlyOffset.x64  =89D81
LocalOnlyCode.x64    =jmpshort
SingleUserPatch.x64  =1
SingleUserOffset.x64 =0CB26
SingleUserCode.x64   =Zero
DefPolicyPatch.x64   =1
DefPolicyOffset.x64  =19105
DefPolicyCode.x64    =CDefPolicy_Query_eax_rcx
SLInitHook.x64       =1
SLInitOffset.x64     =1E98C
SLInitFunc.x64       =New_CSLQuery_Initialize

[10.0.19041.1081-SLInit]
bInitialized.x86      =D1A04
bServerSku.x86        =D1A08
lMaxUserSessions.x86  =D1A0C
bAppServerAllowed.x86 =D1A14
bRemoteConnAllowed.x86=D1A1C
bMultimonAllowed.x86  =D1A20
ulMaxDebugSessions.x86=D1A24
bFUSEnabled.x86       =D1A28

bInitialized.x64      =107108
bServerSku.x64        =10710C
lMaxUserSessions.x64  =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64  =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64       =10712C

**Comment by freecall23** [comment]
I am also facing the same issue on Windows 10 Home 10.0.18363 Build 18363. When I run RDP Wrapper Configuration, it says, 

> Wrapper state: Installed

> Service state: Running

> Listner state: Not Listening

I tried to follow lot of instructions including https://github.com/stascorp/rdpwrap/issues/1473, but it didn't work.

**Comment by freecall23** [comment]
> I am also facing the same issue on Windows 10 Home 10.0.18363 Build 18363. When I run RDP Wrapper Configuration, it says,
> 
> > Wrapper state: Installed
> 
> > Service state: Running
> 
> > Listner state: Not Listening
> 
> I tried to follow lot of instructions including #1473, but it didn't work.

WOW, amazing! it started working successfully. I made a big mistake while extracting content. I extracted content in another directory, and then copied to C drive. By doing so, even if I run scripts with administrator rights, it didn't work. 

But then, I started 7zip program with administrator rights, and then I extracted content to required folder in C drive. Then after running the batch files with admin rights, gave me Listener state as Listening. I did exactly the same steps mentioned in this link: https://github.com/stascorp/rdpwrap/issues/1473

**Comment by hspahk** [comment]
How about this solution?
https://www.gitmemory.com/issue/stascorp/rdpwrap/1454/875980377

**Comment by yousingdog** [comment]
> > I am also facing the same issue on Windows 10 Home 10.0.18363 Build 18363. When I run RDP Wrapper Configuration, it says,
> > > Wrapper state: Installed
> > 
> > 
> > > Service state: Running
> > 
> > 
> > > Listner state: Not Listening
> > 
> > 
> > I tried to follow lot of instructions including #1473, but it didn't work.
> 
> WOW, amazing! it started working successfully. I made a big mistake while extracting content. I extracted content in another directory, and then copied to C drive. By doing so, even if I run scripts with administrator rights, it didn't work.
> 
> But then, I started 7zip program with administrator rights, and then I extracted content to required folder in C drive. Then after running the batch files with admin rights, gave me Listener state as Listening. I did exactly the same steps mentioned in this link: #1473

Run install.bat with the Administrator Right is the key to solve this problem "not listening". Thanks a lot.

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
