### ISSUE TITLE
Win 10 x64 - 10.0.17763.1971 Compilation 17763.1999 - Not Supported

### ISSUE THREAD

**Issue by zekecarter** [stascorp/rdpwrap#1452]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6679743/termsrv.zip)
Windows 10 LTSC x64
10.0.17763.1971
compilation 17763.1999
Not working
i try your fix but not working
![login error](https://user-images.githubusercontent.com/83554130/122626423-24f6ca00-d070-11eb-8128-e2b41ba71c30.png)

**Comment by Maresoft** [comment]
Hello, @zekecarter 
Did you solve the problem ?

**Comment by zekecarter** [comment]
> Hello, @zekecarter
> Did you solve the problem ?

Sorry, and you ?

**Comment by varlock9k** [comment]
@zekecarter @Maresoft
I used rdpwrap.ini & termsrv.dll from 10.0.17763.292
https://github.com/stascorp/rdpwrap/issues/699#issuecomment-473434247
It works!

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1415
