### ISSUE TITLE
Ver 1971

### ISSUE THREAD

**Issue by Maresoft** [stascorp/rdpwrap#1456]
The software is updated to the latest version of termsrv.dll ver. 1971 (present in the May 2021 updates)?

**Comment by sebaxakerhtc** [comment]
> The software is updated to the latest version of termsrv.dll ver. 1971 (present in the May 2021 updates)?

https://github.com/sebaxakerhtc/rdpwrap.ini/commit/7c949f80f3a3f5732258788ff421c1343a758b9c

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1415
