### ISSUE TITLE
Cumulative Update for Windows Server 2019 for x64-based Systems (​KB5003646)

### ISSUE THREAD

**Issue by rchavezh762** [stascorp/rdpwrap#1457]
![WhatsApp Image 2021-06-18 at 1 38 19 PM](https://user-images.githubusercontent.com/86683113/123848089-eb7a5600-d8dc-11eb-8b66-9f4c664b6797.jpeg)

after uninstalling Cumulative Update for Windows Server 2019 for x64-based Systems (KB5003646) 

![WhatsApp Image 2021-06-18 at 3 18 00 PM](https://user-images.githubusercontent.com/86683113/123848226-182e6d80-d8dd-11eb-8556-f3b66a94101d.jpeg)

**Comment by sebaxakerhtc** [comment]
> Cumulative Update

https://github.com/sebaxakerhtc/rdpwrap.ini/commit/7c949f80f3a3f5732258788ff421c1343a758b9c

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1415
