### ISSUE TITLE
Any update for 10.0.19043.1083

### ISSUE THREAD

**Issue by phanuelmutuma** [stascorp/rdpwrap#1463]
**Hello,**

**There is a windows update that installed today and I can't seem to find a new configuration for the update.**

**Anyone with the config?**

**Comment by phanuelmutuma** [comment]
For 10.0.19043.1083
**Works with 10.0.19041.1081**

[Full RDP Wrap ini File Link Here](https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini)

Thank You **GABE** from Telegram

**Comment by nattlip** [comment]
is there a solution, you closed the case, ?

**Comment by phanuelmutuma** [comment]
I have shared the link with the RDP wrapper ini file that works.

**Comment by nattlip** [comment]
thanks , it works

**Comment by softc-1400** [comment]
when i connect to a client it will be log out at first . is there any solution for this problem ?
