### ISSUE TITLE
Configuration for INI file for vin ver 10.0.19042.1083

### ISSUE THREAD

**Issue by juanwrs** [stascorp/rdpwrap#1464]
Please could you share us configuration files for windows version 10.0.19042.1083 ? Thank you!

**Comment by phanuelmutuma** [comment]
Try the one for 10.0.19041.1081

Seems to work with 10.0.19043.1083

[https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini](https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini)

**Comment by dnmartel** [comment]
A reinstall with this file works for me, in version 10.0.19042.1083

**Comment by guilhermer2000** [comment]
work for me in 19042.1083. TKS!

**Comment by abozhchenko** [comment]
10.0.19041.1081 - works good!

**Comment by gmissiatto** [comment]
> Try the one for 10.0.19041.1081
> 
> Seems to work with 10.0.19043.1083
> 
> https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

I used this file in version 19042.1083, but it didn't work. I reinstalled it and it still didn't work out.

**Comment by gmissiatto** [comment]
> work for me in 19042.1083. TKS!

What process did you run? I took the test on mine and it didn't work out.

**Comment by yong93** [comment]
> > Try the one for 10.0.19041.1081
> > Seems to work with 10.0.19043.1083
> > https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini
> 
> I used this file in version 19042.1083, but it didn't work. I reinstalled it and it still didn't work out.

19041.1083 is not working for multiple user, any idea how to fix?

**Comment by gitgotgone** [comment]
Worked for me too! 
For n00bs like me:
1. Download rdpwrap.ini configuration file: follow link above, click "raw", right-click save-as, and strip out .txt suffix.
2. Open cmd as admin and enter "net stop TermService"
3. Go to C:\Program Files\RDP Wrapper folder and rename rdpwrap.ini configuration file.
4. Move new file to C:\Program Files\RDP Wrapper folder.
5. In cmd enter "net start TermService"

**Comment by chandansomani** [comment]
> Worked for me too!
> For n00bs like me:
> 
> 1. Download rdpwrap.ini configuration file: follow link above, click "raw", right-click save-as, and strip out .txt suffix.
> 2. Open cmd as admin and enter "net stop TermService"
> 3. Go to C:\Program Files\RDP Wrapper folder and rename rdpwrap.ini configuration file.
> 4. Move new file to C:\Program Files\RDP Wrapper folder.
> 5. In cmd enter "net start TermService"

Tried This method also but not working for me
![image](https://user-images.githubusercontent.com/23182738/124864461-8d352d80-dfd6-11eb-87c3-e5529e15aa3f.png)

![image](https://user-images.githubusercontent.com/23182738/124864503-a2aa5780-dfd6-11eb-8c24-a8a42514253b.png)

Stucked at login window

**Comment by yong93** [comment]
> > > Try the one for 10.0.19041.1081
> > > Seems to work with 10.0.19043.1083
> > > https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini
> > 
> > 
> > I used this file in version 19042.1083, but it didn't work. I reinstalled it and it still didn't work out.
> 
> 19041.1083 is not working for multiple user, any idea how to fix?

i solve it by restarting the PC and it's work!!!

**Comment by chandansomani** [comment]
Tried uninstalling reinstalling, autoupdate

I think Jump Address are not correct , because shows working but stucked at Login window
![image](https://user-images.githubusercontent.com/23182738/124922480-297f2480-e017-11eb-9eda-705969649d5a.png)

Can someone please show, how can we atleast restore back to the version which microsoft provided with update so atleast one user can use at a time  until next working patch is avialable
(stepswise for noob)

**Comment by Xaviermarq** [comment]
Please We need the update to Windows Version 20h2 10.0.19042.1083 can someone help us?

**Comment by Juannette11** [comment]
I have the windows version 10.0.19042.1083 It has worked for me to replace the rdpwrap.ini of the Sebaxakerhtc version 1081

attached .ini

change .odt for .ini 

https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini
[rdpwrap.odt](https://github.com/stascorp/rdpwrap/files/6785785/rdpwrap.odt)

**Comment by everdominguez** [comment]
> > > Try the one for 10.0.19041.1081
> > > Seems to work with 10.0.19043.1083
> > > https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini
> > 
> > 
> > I used this file in version 19042.1083, but it didn't work. I reinstalled it and it still didn't work out.
> 
> 19041.1083 is not working for multiple user, any idea how to fix?

Have you found how to fix it?

**Comment by Juannette11** [comment]
@everdominguez For me it has worked, remember that before replacing the .ini file you must stop the remote service, make the change of .ini and activate remote service and restart the computer this last is important

**Comment by everdominguez** [comment]
> @everdominguez For me it has worked, remember that before replacing the .ini file you must stop the remote service, make the change of .ini and activate remote service and restart the computer this last is important

Thanks for your reply. Do you work with multiple users simultaneously or just one?

**Comment by Xaviermarq** [comment]
Sorry, IT didn't work for me...

If you have any New idea, I'll preciate that...

Regards!

JM

**Comment by Edgetheguy** [comment]
Same result for me, stopped service. Replaced the .ini and started service. Rebooted. It's showing green but only 1 session at a time.

![rdpwrap](https://user-images.githubusercontent.com/87157462/125007996-64348d00-e016-11eb-9eb0-0d812c16c6f4.PNG)

Credit gitgotgone You have to click raw and save it as text then back to INI, trying to save the ini directly did not work for concurrent.

![save raw](https://user-images.githubusercontent.com/87157462/125008556-9692ba00-e017-11eb-8129-c49f7b5a5461.PNG)

**Comment by Juannette11** [comment]
I have more than 15 users working simultaneously. I have created a download link to share the RDPWrap-v1.6.2.1 that I am using and I have only replaced the rdpwrap.ini from the path C: \ Program Files \ RDP Wrapper and it worked for me.

https://mega.nz/folder/RDgxHCoR#lMvwb_t9ct8TvYq5Q6Za1w

<img width="635" alt="Captura de Pantalla 2021-07-08 a la(s) 8 46 21 p  m" src="https://user-images.githubusercontent.com/87140329/125012991-aff43000-e030-11eb-9ca0-7aa0916a6b2e.png">

**Comment by girikulkrd** [comment]
Juannette11 it shows fully supported but actually it is not working for multiple logins


chandansomani just from control panel uninstall cumulative update of KB5004549 use previous rdpwrap.ini file i am shearing just rename to ini and use
![rdpwrap](https://user-images.githubusercontent.com/87161432/125018725-4bb68800-e093-11eb-9b13-748bd5498f10.GIF)

**Comment by demicus** [comment]
only I have ransomware .venus after this instruction?

**Comment by gmissiatto** [comment]
> Worked for me too!
> For n00bs like me:
> 
> 1. Download rdpwrap.ini configuration file: follow link above, click "raw", right-click save-as, and strip out .txt suffix.
> 2. Open cmd as admin and enter "net stop TermService"
> 3. Go to C:\Program Files\RDP Wrapper folder and rename rdpwrap.ini configuration file.
> 4. Move new file to C:\Program Files\RDP Wrapper folder.
> 5. In cmd enter "net start TermService"

working perfectly..

**Comment by Xaviermarq** [comment]
![image](https://user-images.githubusercontent.com/87134981/125081117-a354f380-e093-11eb-9f71-30611063805e.png)

Nothing, It doesn´t work...

**Comment by Xaviermarq** [comment]
![image](https://user-images.githubusercontent.com/87134981/125082554-5eca5780-e095-11eb-972d-e1dcc2f5ccd0.png)

**Comment by mdreece** [comment]
Not sure if anyone else experiences this, to get more than one connection working at a time I would need to confirm a connection with RDPCheck. Then I could connect multiple devices.

**Comment by everdominguez** [comment]
Hi, where did you do the setup to confirm a connection? Sin más por el momento quedo de Usted,Cordiales Saludos--C.P. Ever S. Domínguez Erives | Agente de ViajesAvintur Agencia de Viajes, S.
  de R.L. de C.V.C. 25 #901 Col. Santo Niño
  C.P. 31200Teléfono Oficina (614) 2966546www.avintur.com ---- On vie, 09 jul 2021 08:43:27 -0600  ***@***.***  wrote ----
Not sure if anyone else experiences this, to get more than one connection working at a time I would need to confirm a connection with RDPCheck. Then I could connect multiple devices.

**Comment by paulspehar** [comment]
I had an autoupdater enabled from an old helper dir running on startup.  This was replacing my new ini file on windows restarts.  I had to run helper\autoupdate__disable_autorun_on_startup.bat as admin to get past this. Mentioning just in case anyone else gets caught up by this. 

` Directory of C:\Program Files\RDP Wrapper\helper

12/02/2020  06:25 PM    <DIR>          .
12/02/2020  06:25 PM    <DIR>          ..
08/11/2019  06:48 PM               197 autoupdate__disable_autorun_on_startup.bat
08/11/2019  04:23 PM               191 autoupdate__enable_autorun_on_startup.bat
08/13/2019  10:14 AM             2,033 autoupdate__info.txt
               3 File(s)          2,421 bytes
               2 Dir(s)  129,121,976,320 bytes free`

**Comment by chandansomani** [comment]
> Juannette11 it shows fully supported but actually it is not working for multiple logins
> 
> chandansomani just from control panel uninstall cumulative update of KB5004549 use previous rdpwrap.ini file i am shearing just rename to ini and use
> ![rdpwrap](https://user-images.githubusercontent.com/87161432/125018725-4bb68800-e093-11eb-9b13-748bd5498f10.GIF)


TRIED UNINSTALLING UPDATE KB5004945 BUT DOEST HELP , SAME PROBLEM PERSIST STUCKED AT LOGIN WINDOWS, 

WAITING EGARLY FOR WORKING PATCH ,

**Comment by zekecarter** [comment]
> ![image](https://user-images.githubusercontent.com/87134981/125081117-a354f380-e093-11eb-9f71-30611063805e.png)
> 
> Nothing, It doesn´t work...

[10.0.19042.1083]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=89D81
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB26
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=19105
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1E98C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19042.1083-SLInit]
bInitialized.x64      =107108
bServerSku.x64        =10710C
lMaxUserSessions.x64  =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64  =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64       =10712C

add, save and just restart your pc. enjoy

**Comment by everdominguez** [comment]
> > ![image](https://user-images.githubusercontent.com/87134981/125081117-a354f380-e093-11eb-9f71-30611063805e.png)
> > Nothing, It doesn´t work...
> 
> [10.0.19042.1083]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=89D81
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CB26
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=19105
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1E98C
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.19042.1083-SLInit]
> bInitialized.x64 =107108
> bServerSku.x64 =10710C
> lMaxUserSessions.x64 =107110
> bAppServerAllowed.x64 =107118
> bRemoteConnAllowed.x64=107120
> bMultimonAllowed.x64 =107124
> ulMaxDebugSessions.x64=107128
> bFUSEnabled.x64 =10712C
> 
> add, save and just restart your pc. enjoy

Doesn't work for me.

**Comment by everdominguez** [comment]
Hi Everyone,

In this link helps to the update to multi session.
https://github.com/stascorp/rdpwrap/pull/1160#issuecomment-877580848

I've tested and it works fine!

**Comment by chandansomani** [comment]
> > ![image](https://user-images.githubusercontent.com/87134981/125081117-a354f380-e093-11eb-9f71-30611063805e.png)
> > Nothing, It doesn´t work...
> 
> [10.0.19042.1083]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=89D81
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CB26
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=19105
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1E98C
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.19042.1083-SLInit]
> bInitialized.x64 =107108
> bServerSku.x64 =10710C
> lMaxUserSessions.x64 =107110
> bAppServerAllowed.x64 =107118
> bRemoteConnAllowed.x64=107120
> bMultimonAllowed.x64 =107124
> ulMaxDebugSessions.x64=107128
> bFUSEnabled.x64 =10712C
> 
> add, save and just restart your pc. enjoy

please share your DLL version

**Comment by zekecarter** [comment]
> > > ![image](https://user-images.githubusercontent.com/87134981/125081117-a354f380-e093-11eb-9f71-30611063805e.png)
> > > Nothing, It doesn´t work...
> > 
> > 
> > [10.0.19042.1083]
> > LocalOnlyPatch.x64=1
> > LocalOnlyOffset.x64=89D81
> > LocalOnlyCode.x64=jmpshort
> > SingleUserPatch.x64=1
> > SingleUserOffset.x64=0CB26
> > SingleUserCode.x64=Zero
> > DefPolicyPatch.x64=1
> > DefPolicyOffset.x64=19105
> > DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> > SLInitHook.x64=1
> > SLInitOffset.x64=1E98C
> > SLInitFunc.x64=New_CSLQuery_Initialize
> > [10.0.19042.1083-SLInit]
> > bInitialized.x64 =107108
> > bServerSku.x64 =10710C
> > lMaxUserSessions.x64 =107110
> > bAppServerAllowed.x64 =107118
> > bRemoteConnAllowed.x64=107120
> > bMultimonAllowed.x64 =107124
> > ulMaxDebugSessions.x64=107128
> > bFUSEnabled.x64 =10712C
> > add, save and just restart your pc. enjoy
> 
> please share your DLL version

ok... 
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6804903/termsrv.zip)

**Comment by chandansomani** [comment]
problem solved 
It was NLA mode that worked

my ini version is "Updated=2021-07-08"
author name is not available
(downloaded many of the them to try)

**Comment by sebaxakerhtc** [comment]
applicable to https://github.com/stascorp/rdpwrap/issues/1447

**Comment by helloobaby** [comment]
work for me
