### ISSUE TITLE
RDP not working ?

### ISSUE THREAD

**Issue by Sm982** [stascorp/rdpwrap#1466]
Hey!

I just found about this program, and I see that it says (Listener State: Not Listening, Not Supported), I've looked around the github and have found no fix yet for me. Was wondering if anyone could help me out. My winver is attached, the winver in the rdpconfig is different though.. Thanks if someone could help me that'd be appreciated.
![image](https://user-images.githubusercontent.com/53702116/124920096-1e87bc80-e036-11eb-8d81-0cfd095b9cd4.png)

![image](https://user-images.githubusercontent.com/53702116/124919935-f13b0e80-e035-11eb-91eb-665246faaa69.png)

**Comment by mdreece** [comment]
Try: https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

Download rdpwrap.ini configuration file: follow link above, click "raw", right-click save-as, and strip out .txt suffix.
Open cmd as admin and enter "net stop TermService"
Go to C:\Program Files\RDP Wrapper folder and rename rdpwrap.ini configuration file.
Move new file to C:\Program Files\RDP Wrapper folder.
In cmd enter "net start TermService"

(Steps originally posted by gitgotgone)

**Comment by vdovin1981** [comment]
Same problem. Used ini file from this topic/ It says "Fully Support", but only one session works.
<img width="319" alt="rdpwrapjuly2021" src="https://user-images.githubusercontent.com/77384322/125060745-58e46e80-e0b5-11eb-970f-cebe0cab14f0.png">

**Comment by thijijs** [comment]
i have the same problem, only one session works, since a couple of days, before it used to work

**Comment by Drugar123** [comment]
Had the same problem today. I looked at Windows Updates and seen that KB5004945 had been installed last night for the PrinterNightmare fix. I uninstalled KB5004945, rebooted computer and re-ran RDP auto-update. Resolved my issue and users are able to connect. I turned off auto update for 7 days so it doesn't try to re-install the patch until Windows releases a better fix.

**Comment by DougShaner** [comment]
My Windows version is 19042.1110 and RDP wrapper recently stopped working. I replaced the INI file with the one provided in this thread and it appears to have resolved the trouble.

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1420
