### ISSUE TITLE
No x86 solution for 10.0.17762.1971, only x64

### ISSUE THREAD

**Issue by polkrono** [stascorp/rdpwrap#1467]
Autoupdate does not work with Win32, I note that only appears x64 solution, not x86.

Help would be appreciated...

**Comment by asmtron** [comment]
please upload the termsrv.dll for 10.0.17762.1971 Win32...

**Comment by polkrono** [comment]
> please upload the termsrv.dll for 10.0.17762.1971 Win32...

Sorry... I forget it.. 

It would be attached but the mail blocks the file. 

Tnx

**Comment by tetas26** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6796032/termsrv.zip)

**Comment by polkrono** [comment]
Thanks @tetas26 , it is a good idea...


[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6799388/termsrv.zip)

**Comment by tetas26** [comment]
Would very much appreciate a 32 bit version.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1415
Do not create issue with the same version, better leave your question there

**Comment by sebaxakerhtc** [comment]
Added support for Windows 10 LTSC x86
17763.1971 and 17763.2213
