### ISSUE TITLE
cant log in my session with rdp

### ISSUE THREAD

**Issue by UltimateDash** [stascorp/rdpwrap#1469]
Hey, so i have followed a tutorial to install rdp wrap (this one : https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)

It worked, rdp say that it is listening and working properly, 
![image](https://user-images.githubusercontent.com/62153772/125296969-1a55ea80-e327-11eb-9c7e-c712117921e5.png)

but when i try to check with RDPCheck it look like this
![image](https://user-images.githubusercontent.com/62153772/125296877-0316fd00-e327-11eb-9908-7dc2bf205bfe.png)

any idea?

**Comment by Eriick100** [comment]
Prueba con la opción "Network Level Authentication" y aplica los cambios.

**Comment by chandansomani** [comment]
> Hey, so i have followed a tutorial to install rdp wrap (this one : https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)
> 
> It worked, rdp say that it is listening and working properly,
> ![image](https://user-images.githubusercontent.com/62153772/125296969-1a55ea80-e327-11eb-9c7e-c712117921e5.png)
> 
> but when i try to check with RDPCheck it look like this
> ![image](https://user-images.githubusercontent.com/62153772/125296877-0316fd00-e327-11eb-9908-7dc2bf205bfe.png)
> 
> any idea?


if you found the solution please share the solution I m also facing the problem, my winver is 19043.1083

**Comment by sashaqwert** [comment]
@chandansomani Please, do uot use Network Level Authentification with RDPCheck!
Use mstsc --> 127.0.0.2

OR

Use magic RDP file (only if NLA enabled): 
[ThisWork.zip](https://github.com/stascorp/rdpwrap/files/6803911/ThisWork.zip)

**Comment by bartlettD** [comment]
I'm having this exact issue on 21H1(19043.1110) and even with the updated ini from asmtron's fork #1475 I still get this screen.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1447
