### ISSUE TITLE
slow win10

### ISSUE THREAD

**Issue by shippj** [stascorp/rdpwrap#147]
I don't think this is a flaw with rdpwrap, but I can't think of a better place to bring this topic up because I expect it effects a lot of rdpwrap users.  Maybe it will end up in the wiki or in the readme section if it gets a good answer.

It's always sluggish when I'm remoted into a windows 10 computer.  It doesn't matter what client OS i'm connecting from.  I use RDP to connect to about 100 computers.  Some over LAN, some over WAN.  Some joined to active directory, some workgroup.  I never have this issue when I RDP into windows 7 computers.  I don't have any windows 8/8.1 computers to test it with.  These same windows 10 computers are fast when I'm using the console.  Most of them have SSDs and i3 or better.  The older ones are literally unusable with RDP because they can take 30 seconds or more just for the start menu to appear, and 30 more seconds just to start a tiny program like notepad, where using the console would only take 1 or 2 seconds.  It's like windows 10 is running terminal services as low priority or something.  I'm surprised I can't find anybody else talking about this.

**Comment by gireeshcc** [comment]
I am also facing the same problem , but I was using ver 1.6.0 now I am going to try 1.6.1 may be if remote clients work OK with this new RDPwrapper version. I will report it within week.

**Comment by deafwing** [comment]
Any thoughts on your experiences with slowness guys?

**Comment by shippj** [comment]
I have discovered I can go into the advanced system settings, performance settings, advanced, processor scheduling, and change it from PROGRAMS to BACKGROUND SERVICES and it seems to make it faster, but I still think it's slower than win7.
