### ISSUE TITLE
Is there a session manager I can use with RDP Wrap?

### ISSUE THREAD

**Issue by dsteinschneider** [stascorp/rdpwrap#1471]
I would like to be able to control sessions as you could with Terminal Services Manager. Is there a way to accomplish the same in Windows 10 with RDP Wrap?

Thanks

**Comment by sashaqwert** [comment]
Yes.
This works with RDP Wrapper 
If you use one PC, you can add server 127.0.0.1

**Comment by dsteinschneider** [comment]
I tried using the one from Server 2003 but it closes upon launch. Which one can I use and do I need to copy other files or create/edit registry keys/values?

Thanks

**Comment by sashaqwert** [comment]
https://lizardsystems.com/terminal-services-manager/
1. Install
2. Get free license
3. Activate
4. Enjoy

**Comment by dsteinschneider** [comment]
Thanks - it's working great
