### ISSUE TITLE
RDPwrapper not supported on 10.0.19041.84

### ISSUE THREAD

**Issue by mrjoli021** [stascorp/rdpwrap#1473]
Hello,

I have followed all the instructions on the site below and the RDP wrapper still shows up as unsupported.

http://woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/

Please help me.  I have attached my termsrv.dll file.

thanks,
[termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/6826686/termsrv.dll.zip)

**Comment by sashaqwert** [comment]
https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

**Comment by mrjoli021** [comment]
Got it working.  Thanks a million.  Final question.  Is it OK to do windows updates or should I avoid updating Windows?  I dont want to break this feature.

**Comment by sashaqwert** [comment]
Yes! you can update Windows.
If you will get [Not supported], then you need run Autoupdate again.

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
