### ISSUE TITLE
RDP wrapper fully support but not listening on 19041.1081

### ISSUE THREAD

**Issue by AliZe198** [stascorp/rdpwrap#1474]
![image](https://user-images.githubusercontent.com/87623275/126085631-a2a21c81-8757-4d27-b1cb-ea649b53b423.png)

I've already replaced the rdpwrap.ini with https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

![image](https://user-images.githubusercontent.com/87623275/126085707-aa0b90b5-c8e5-41f3-91a1-919ad925a80f.png)

Now it's fully supported but not listening. Please help!

**Comment by georgemaxx** [comment]
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
this .ini file works for me.

1. copy this file into RDPWrap-v1.6.2
2. then run RDPConf.exe, if occur not listening, you can first uninstall, then install again
3. then run RDPConf.exe, you will find listener state is listening(green)

this method works.

**Comment by AliZe198** [comment]
> https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
> this .ini file works for me.
> 
> 1. copy this file into RDPWrap-v1.6.2
> 2. then run RDPConf.exe, if occur not listening, you can first uninstall, then install again
> 3. then run RDPConf.exe, you will find listener state is listening(green)
> 
> this method works.

![image](https://user-images.githubusercontent.com/87623275/126146493-c0b95c44-9b2e-4b48-9d32-581a13dfa669.png)
I just tried. But it doesn't seem to work. 

This is what I got when I tried to uninstall. Just wondering if it's due to these two errors. 
![image](https://user-images.githubusercontent.com/87623275/126146948-3a6f1385-03c4-48a2-b256-08550b48fa00.png)

**Comment by flybeye** [comment]
for Installing, I would use asmtron's version of the autoupdate.bat, install.bat, uninstall,bat, etc.
https://github.com/asmtron/rdpwrap/tree/master/bin

run the files as Administrator


for updating for working on 19041.1081... i did the following:

mine is working with the one from asmtron fork
https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini
![image](https://user-images.githubusercontent.com/22753145/126696465-f8c3737a-05ca-4fab-babd-bbdd182e5060.png)


Might need to stop Term Services: net stop TermService
update the ini file from above, into your RDPWrapper directory (C:\Program Files\RDPWrapper)
then restart Term Services: net start TermService

or if your RDP wrapper is from asmtron Github, then you can run the autoupdate.bat as Administrator since asmtron has already
updated his repo.

**Comment by sausix** [comment]
After testing a lot of ini files, this worked finally for 1081.

Stop the service, extract only the ini file in the download there:
https://github.com/stascorp/rdpwrap/issues/1464#issuecomment-876859785
Then start the service again.

Don't install and run unknown binary files.

**Comment by songfuqiangcn** [comment]
更新了一个ini文件
然后重启了一下 
>net stop termservice

**Comment by songfuqiangcn** [comment]
>net start  termservice

**Comment by songfuqiangcn** [comment]
更新了一个ini文件
然后重启了一下

net stop termservice
net start termservice
![image](https://user-images.githubusercontent.com/65161482/129296575-b0607bbc-c548-471c-8093-422d09d267c9.png)

**Comment by minvisible** [comment]
> https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
> this .ini file works for me.
> 
> 1. copy this file into RDPWrap-v1.6.2
> 2. then run RDPConf.exe, if occur not listening, you can first uninstall, then install again
> 3. then run RDPConf.exe, you will find listener state is listening(green)
> 
> this method works.

**Comment by minvisible** [comment]
> https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
> this .ini file works for me.
> 
> 1. copy this file into RDPWrap-v1.6.2
> 2. then run RDPConf.exe, if occur not listening, you can first uninstall, then install again
> 3. then run RDPConf.exe, you will find listener state is listening(green)
> 
> this method works.

so cool~~~~~ this file works for me. thanks.
just follow the upper steps, if not worked, just try to uninstall and then install again.
use this command :   RDPConf.exe -r  in the cmd, it will work.

**Comment by mauro-miatello** [comment]
I've tried both ini files but none works
also, if I put autoupdate in "program files" the enable/disable bat works, but not the autoupdate.bat
if I put in "program files (x86)" none of them works

EDIT: solved, I removed all files and services, re-install in "program files" and used asmtron version, now all options are green but I connect only one user at once. Solved with https://github.com/anhkgg/SuperRDP

**Comment by hezhanbang** [comment]
> > https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
> > this .ini file works for me.
> > 
> > 1. copy this file into RDPWrap-v1.6.2
> > 2. then run RDPConf.exe, if occur not listening, you can first uninstall, then install again
> > 3. then run RDPConf.exe, you will find listener state is listening(green)
> > 
> > this method works.
> 
> so cool~~~~~ this file works for me. thanks.
> just follow the upper steps, if not worked, just try to uninstall and then install again.
> use this command : RDPConf.exe -r in the cmd, it will work.

it work for me. thank you.  

my steps:
1. run cmd as admin,  then net stop TermService
2. uninstall.bat and install.bat
3. copy https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini into C:\Program Files\RDP Wrapper
4. net start TermService
5. RDPConf.exe -r 

my computer version:
![1](https://user-images.githubusercontent.com/5327771/130409315-2ea6308a-098e-4ebe-a62d-aa9f32766c81.png)

config:
![2](https://user-images.githubusercontent.com/5327771/130385387-2ff4565d-b381-46b1-a310-f9ad993a61ae.png)

**Comment by Inewcoming** [comment]
@ songfuqiangcn， My windows version is 10.0.19043.1165,and I update the  .ini file. It works! Thanks! 
[rdpwrap_10.0.19043.1110.zip](https://github.com/stascorp/rdpwrap/files/7076253/rdpwrap_10.0.19043.1110.zip)

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447

**Comment by kappa057002** [comment]
my version is 10.0.19041.1387 and it dont work can someone help me plz!
