### ISSUE TITLE
Keep remote windows login screen open when not signing in.

### ISSUE THREAD

**Issue by len-ny** [stascorp/rdpwrap#1476]
I use "GUI authentication only' configuration for rdpwrap .
When I connect from microsoft remote desktop application without the user name & password, it brings me to the windows login screen of the computer (which rdpwrap run). This is good because it displays all user accounts for selection. Problem is, if I didn't login within 30 seconds, it closed the login screen. How to keep the login screen open/connected without signing in?

Secondly, when I signed out from the remote desktop, it straight away closed the screen. How to make it goes back to the windows login screen (with user accounts list) instead of closing the screen? It should remain connected until I manually click the close button at title bar to close the screen.

**Comment by sebaxakerhtc** [comment]
Not an rdpwrap issue
