### ISSUE TITLE
Svchost.exe 100%

### ISSUE THREAD

**Issue by MircoBatt91** [stascorp/rdpwrap#148]
Hi,
I'm Italian, so sorry if my English is not so good.
I've update Windows 10 to annyversary update and installed rdp wrap 1.6.1.
But, after some minutes, svchost goes to 100% and also task manager freezes.
I didn't have the same problem with win 10 1507.
P.S.: There are 15 client that connects in the pc in the same time.
Thank you.

**Comment by leszekw83** [comment]
How much RAM do you have? 15 clients that's a lot.

**Comment by MircoBatt91** [comment]
It has 8 gb of ram. It Always worked in last 2 years using about 60% of ram, but the problem now is svchost that goes to 100% (sometimes after 2 minutes, sometimes after 30) and pc freezes. Never appened before. Also when a client open a new rdp session, Windows Defender says that new virus is found. I disabled it from Group policy but nothing changed.
It seem like some loop processes that going to crash svchost.

**Comment by binarymaster** [comment]
You may use [Process Hacker](http://processhacker.sourceforge.net/) to see which service and what thread exactly eats your CPU cycles.

**Comment by MircoBatt91** [comment]
Yesterday I tried with Process Explorer and I've seen a lot of "brokerinfrastructure" processes in svchost. Later I'll try with process hacker. I didn't write that svchost goes to 100% also if clients doesn't use the pc, but only logins and it doesn't appenned if they are only 2/3. I'm starting to hate Windows 10.

**Comment by MircoBatt91** [comment]
I've installed Process Hacker, and just now i've svchost al 100%. What should I watch?

**Comment by binarymaster** [comment]
Double click on process, and see `Threads` tab.

**Comment by MircoBatt91** [comment]
![wp_20160831_11_31_28_pro](https://cloud.githubusercontent.com/assets/21348695/18123569/bf182c5e-6f6e-11e6-9c71-b2a1fb905757.jpg)
![Uploading WP_20160831_11_31_48_Pro.jpg…]()
Here you are. I can't did screenshot because system was not stable. Do you find anything wrong?

**Comment by MircoBatt91** [comment]
![wp_20160831_11_31_48_pro](https://cloud.githubusercontent.com/assets/21348695/18123847/122cf450-6f70-11e6-882f-89e87d157afc.jpg)

**Comment by binarymaster** [comment]
Double click on `svchost.exe 852`, switch to `Threads` tab and make photo again.

**Comment by MircoBatt91** [comment]
Done!
![wp_20160831_12_05_49_pro](https://cloud.githubusercontent.com/assets/21348695/18124625/4ccd109c-6f73-11e6-9da3-c5d99b482f24.jpg)

**Comment by binarymaster** [comment]
As you can see on the photo, the problem is in the `LSM` service.

**Comment by MircoBatt91** [comment]
I've seen. Any suggestion?

**Comment by binarymaster** [comment]
Well, I actually don't know LSM service stands for, since I'm using Windows 7 (it doesn't have LSM service).

Maybe there's something in the event log. Also you may try to contact MS support.

**Comment by jdunn0** [comment]
A quick Google Search shows that LSM stands for "Local Session Manager".
It's a built-in service in Window 7 and up that manages all the user's local sessions.

**Comment by MircoBatt91** [comment]
I never had problem with win 8, 8.1, 10 rtm, 10 1511.. But now it crashes. Someone else has win 10 Anniversary with rdp wrap?

**Comment by binarymaster** [comment]
@jdunn0 in Windows 7 it exists but doesn't installed as system service.

**Comment by jdunn0** [comment]
@binarymaster: Yeah, I found that out after I posted my reply and I edited my post to point that out.
It's a little confusing that in Windows 7 the description for lsm.exe is "Local Session Manager Service" even though it's not actually a Windows Service.
