### ISSUE TITLE
rdpconf and rdpcheck crashing

### ISSUE THREAD

**Issue by maucoimbra** [stascorp/rdpwrap#1480]
Hello,

my rdpcheck and rdpconf is crashing, it only opens in the taskbar and nothing appears on the screen, does anyone know how to solve it?

I've reinstalled several times

Thanks

**Comment by thomtsib** [comment]
Check if your win version is mentioned into .ini file

**Comment by sebaxakerhtc** [comment]
> Hello,
> 
> my rdpcheck and rdpconf is crashing, it only opens in the taskbar and nothing appears on the screen, does anyone know how to solve it?
> 
> I've reinstalled several times
> 
> Thanks

Turn off your antivirus.
