### ISSUE TITLE
RD wrapper fully supported and Listening But not working concurrent connections

### ISSUE THREAD

**Issue by shinojali** [stascorp/rdpwrap#1484]
My RDP Wrapper is working but no concurrent connections supported. windows 10 x64  19042.1110

**Comment by sashaqwert** [comment]
Please, download modded version or ask your question here: https://discord.gg/N27yFftWP3

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
