### ISSUE TITLE
Config doesn't listen and says not supported on Windows 10 Home Computer

### ISSUE THREAD

**Issue by navincodesalot** [stascorp/rdpwrap#1486]
When I run the check it says socket failed. It says "Not listening" and "Not Supported"
![image](https://user-images.githubusercontent.com/67123306/127885656-29598335-e725-403a-a636-acf3536c46d0.png)

**Comment by stuaxo** [comment]
Same here, not sure if it's because I'm running windows under kvm though.

**Comment by bitchecker** [comment]
I have the same issue with a bare metal install.

**Comment by sebaxakerhtc** [comment]
applicable to https://github.com/stascorp/rdpwrap/issues/1447
