### ISSUE TITLE
Win 10 x64 - 10.0.17763.2061 Compilation 17763.2061 - Not Supported

### ISSUE THREAD

**Issue by Pingvinytko** [stascorp/rdpwrap#1487]
![Screenshot_1](https://user-images.githubusercontent.com/88425106/128140900-0c0af49a-621e-4752-95f6-d0662fe8321d.png)

**Comment by Pingvinytko** [comment]
Sorry... Win 10 was updates, and RDP doesn't work.. 
I need rdpwrap.ini with new data

**Comment by Pingvinytko** [comment]
Uffff. 1971 works for 17763.2061

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1415
