### ISSUE TITLE
Connects to computer but crashes on login "Socket error"

### ISSUE THREAD

**Issue by kspizzle** [stascorp/rdpwrap#149]
Hi guys,

So this works on my two windows 10 machines just fine, but when I am attempting it on two Windows 7 machines it is failing. I can check that the service is running and working fine, then when I either RDP to the machine or use the RDPCheck, it shows the local user login page, I enter the password and then it crashes out with "Socket error".

Whenever this happens, the Remote Desktop Services service then stops and requires manual restart. 

Any help appreciated.

**Comment by binarymaster** [comment]
Make sure you have original unmodified system files, especially `termsrv.dll`.

**Comment by adfnekc** [comment]
i have a same problem with you in win10,and i have replaced the termsrv.dll,😫

**Comment by ClaudMarques** [comment]
I recommend you restore Windows Firewall settings to default.

Press the key on the Windows.
Type Windows Firewall, after click restore defaults.
Return to the Default settings of windows (All Firewall permissions settings will be lost).
Go to > allow a program or feature through Windows Firewall.
Enable file and printer sharing
-Network discovery
-SSTP (Secure Socket Tunneling Protocol)
Then in Windows Services Check the following services
-DNS Client,
-Discovery Resource Publication,
-SSDP Discovery Discovery
-UPnP Device Host
If any of them is disabled put on automatic and start the service.


If it persists, I recommend you try to reinstall the system.
