### ISSUE TITLE
dll update - 21H1 19043.1165

### ISSUE THREAD

**Issue by lokasunder-vr** [stascorp/rdpwrap#1490]

**Comment by 4R3B3LatH34R7** [comment]
21H1 19043.1165
rdpconfig shows it is using termserv.dll 19041.1081
all 3 green in rdpconfig
on concurrent login, currently logged in account got locked out
rdpcheck works fine with concurrent login working
on using another computer, taskmgr shows 2 users logged in but host machine user got screenlocked
may be 19043.1165 single user offset got changed!
please help

**Comment by mattgphoto** [comment]
I'm seeing the same thing: 
![image](https://user-images.githubusercontent.com/26942853/129458568-1cb66935-792a-42f9-83bc-ef0ce1dcc98e.png)

**Comment by Wolfoff-Giro** [comment]
21H1 19043.1165 32bit
rdpconfig shows it is using termserv.dll 19041.1081
need help

![Снимок экрана 2021-08-15 101638](https://user-images.githubusercontent.com/88961806/129470370-3c02ba8f-4889-4ac4-94ff-9586fbd47572.png)
![Снимок экрана 2021-08-15 101733](https://user-images.githubusercontent.com/88961806/129470376-c4790f5e-692c-4a47-aba9-7843eb90e641.png)

**Comment by varlock9k** [comment]
@NLYinMaung @mattgphoto @Wolfoff-Giro 

I installed w10 pro 21H1 10.0.19043.1165
Took rdpwrap.ini for version 10.0.19041.1081
https://github.com/stascorp/rdpwrap/issues/1474#issuecomment-882274805
It works

You can also try this:
https://github.com/stascorp/rdpwrap/issues/1483#issuecomment-890400120

**Comment by 4R3B3LatH34R7** [comment]
> 
> 
> @NLYinMaung @mattgphoto @Wolfoff-Giro
> 
> I installed w10 pro 21H1 10.0.19043.1165
> Took rdpwrap.ini for version 10.0.19041.1081
> [#1474 (comment)](https://github.com/stascorp/rdpwrap/issues/1474#issuecomment-882274805)
> It works
> 
> You can also try this:
> [#1483 (comment)](https://github.com/stascorp/rdpwrap/issues/1483#issuecomment-890400120)

My rdpwrap.ini also contains 19041.1081 and it is working and all green, rdpcheck also works fine.
What I am saying is that, concurrent login is NOT.

**Comment by varlock9k** [comment]
> 
> 
> > @NLYinMaung @mattgphoto @Wolfoff-Giro
> > I installed w10 pro 21H1 10.0.19043.1165
> > Took rdpwrap.ini for version 10.0.19041.1081
> > [#1474 (comment)](https://github.com/stascorp/rdpwrap/issues/1474#issuecomment-882274805)
> > It works
> > You can also try this:
> > [#1483 (comment)](https://github.com/stascorp/rdpwrap/issues/1483#issuecomment-890400120)
> 
> My rdpwrap.ini also contains 19041.1081 and it is working and all green, rdpcheck also works fine.
> What I am saying is that, concurrent login is NOT.

1.6.2?

**Comment by 4R3B3LatH34R7** [comment]
> 
> 
> > > @NLYinMaung @mattgphoto @Wolfoff-Giro
> > > I installed w10 pro 21H1 10.0.19043.1165
> > > Took rdpwrap.ini for version 10.0.19041.1081
> > > [#1474 (comment)](https://github.com/stascorp/rdpwrap/issues/1474#issuecomment-882274805)
> > > It works
> > > You can also try this:
> > > [#1483 (comment)](https://github.com/stascorp/rdpwrap/issues/1483#issuecomment-890400120)
> > 
> > 
> > My rdpwrap.ini also contains 19041.1081 and it is working and all green, rdpcheck also works fine.
> > What I am saying is that, concurrent login is NOT.
> 
> 1.6.2?

install.bat is 1.6.2 yes.
rdpconfig shows that Wrapper State : Installed with ver. 1.5.0.0
Service state : Running with ver. 10.0.19041.1081
Listener state: Listening with [fully supported]

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
