### ISSUE TITLE
rdpwrap doesn't work though supported

### ISSUE THREAD

**Issue by exx8** [stascorp/rdpwrap#1494]
I've edited the ini file so the software will be supported:
![image](https://user-images.githubusercontent.com/8540180/130199585-2b0943ba-306d-48c2-889f-faa5f343d95f.png)

Though I'm still getting this error while trying connect with 2 user simultaneously. anyone knows why? 
![image](https://user-images.githubusercontent.com/8540180/130199736-6b0043ba-82f0-4a76-9416-a5879165ed01.png)

thanks!

**Comment by mauro-miatello** [comment]
me too, solved with https://github.com/anhkgg/SuperRDP

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
