### ISSUE TITLE
Attempt on termsrv.dll version 10.0.19041.1081   关于 termsrv.dll 版本10.0.19041.1081的尝试

### ISSUE THREAD

**Issue by nvdkzyp** [stascorp/rdpwrap#1497]
我的电脑系统是【Windows 10 教育版】，操作系统内部版本是【19042.1165】，使用【RDP Configuration Program】设置多用户同事登陆的时候【Listener state】报错【[not supported]】，尝试了【update.bat】，窗口闪过，无用。经过各种查询，后来找到个办法是直接使用【Tiny Hexer】修改【termsrv.dll】文件。以下是尝试的结果记录（因为之前成功过一次，后来莫名其妙登录不上，一看【termsrv.dll】恢复原样了，所以在这里记录一下。标题中英文在前只是为了方便检索，我可是纯汉人。）

首先是【Tiny Hexer】，百度来的绿色版，解压直接用。

找到【termsrv.dll】文件，因为权限问题太麻烦，所以直接单个文件更改权限，然后复制到新的文件夹操作。

使用【Tiny Hexer】打开【termsrv.dll】后按照网友的方法查找【39 81 3C 06 00】（16位），在我的【termsrv.dll】中找到了唯一一条，显示为：【39 813C 0600 000F 84DB 6101 00】，也就是【39 81 3C 06 00 00 0F 84 DB 61 01 00】，将这一条修改为：【B8 00 01 00 00 89 81 38 06 00 00 90】（一定不要输错了），保存，重启电脑。

Machine translation, please forgive me.

My computer system is [Windows 10 Education Edition], and the internal version of the operating system is [19042.1165]. When using [RDP Configuration Program] to set multi-user colleagues to log in, [Listener state] prompts an error [[not supported]], I tried [ update.bat], the window flashes and is useless. After various queries, I found a way to modify the [termsrv.dll] file directly using [Tiny Hexer]. The following is a record of the result of the attempt (because I succeeded once before, but I couldn’t log in inexplicably, I saw [termsrv.dll] restored to its original shape, so record it here. The title Chinese and English are only for easy retrieval, I am a pure Chinese .)

The first is [Tiny Hexer], a green version from Baidu, which can be used directly after decompression.

Find the [termsrv.dll] file, because the permission problem is too troublesome, so directly change the permission of a single file, and then copy it to a new folder.

Use [Tiny Hexer] to open [termsrv.dll] and search for [39 81 3C 06 00] (16 bits) according to the method of netizens, and find the only one in my [termsrv.dll], which is displayed as: [39 813C 0600 000F 84DB 6101 00], which is [39 81 3C 06 00 00 0F 84 DB 61 01 00], modify this entry to: [B8 00 01 00 00 89 81 38 06 00 00 90] (make sure you don’t make a mistake) , Save, restart the computer.

**Comment by hezhanbang** [comment]
what are you talking about?

**Comment by AdorableGhost** [comment]
可以使用吗？

**Comment by nvdkzyp** [comment]
> 可以使用吗？

我的win10系统成功的开启了多用户同时登录

**Comment by nvdkzyp** [comment]
> 你在说什么？

what do you need?

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
