### ISSUE TITLE
RDP Wrapper stopped working with 19042.1165

### ISSUE THREAD

**Issue by dancingniki** [stascorp/rdpwrap#1498]
Hello everybody,

does anyone have a fix for this version?

**Comment by JungsonStone** [comment]
I've already replaced the rdpwrap.ini with https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
please reference the version 19041.1081 #1474

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
