### ISSUE TITLE
RDP wrapper seems to be running but shown Not Installed on 19041.1081

### ISSUE THREAD

**Issue by abm4** [stascorp/rdpwrap#1500]
RDP wrapper was running ok. After update to 19041.1081 it shows in the configurator **Not Installed** though it looks like rdpwrapper.dll is running (as files are locked - dll and ini).
Installer is not working with error **Access Denied** (seems this is an issue with Defender blocking RDPWinst.exe locked even after added into exceptions list).
![2021-08-25_15-57-49](https://user-images.githubusercontent.com/20446847/130804335-a0f77e31-e1cc-450e-bb6d-bf7ef0c0afbd.jpg)

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447

**Comment by creeeeeds** [comment]
I have the same problem, did you fix it yet?

**Comment by binarymaster** [comment]
This is a bug tracker, for questions and support use Telegram chat (badge in readme).
