### ISSUE TITLE
rdpwrap.ini offsets for 10.0.19041.1081 x86

### ISSUE THREAD

**Issue by bdmauer** [stascorp/rdpwrap#1501]
For anyone using x86 instead of x64, here are the offsets for 10.0.19041.1081 x86:

[10.0.19041.1081]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B66B9
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3BD25
SingleUserCode.x86=nop
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E899
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
SLInitHook.x86=1
SLInitOffset.x86=68809
SLInitFunc.x86=New_CSLQuery_Initialize

[10.0.19041.1081-SLInit]
bInitialized.x86      =D1A04
bServerSku.x86        =D1A08
lMaxUserSessions.x86  =D1A0C
bAppServerAllowed.x86 =D1A14
bRemoteConnAllowed.x86=D1A1C
bMultimonAllowed.x86  =D1A20
ulMaxDebugSessions.x86=D1A24
bFUSEnabled.x86       =D1A28

**Comment by affinityv** [comment]
[INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file updated.

**Comment by sebaxakerhtc** [comment]
compare to https://github.com/stascorp/rdpwrap/issues/1447
