### ISSUE TITLE
rdwrap.ini for 10.0.19041.84

### ISSUE THREAD

**Issue by marianeitor** [stascorp/rdpwrap#1502]
Need rdwrap.ini file for 10.0.19041.84

**Comment by sashaqwert** [comment]
https://github.com/asmtron/rdpwrap/blob/master/binary-download.md
https://t.me/rdpwrap/31499

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
