### ISSUE TITLE
Win 10 ver 19042.1165 not working

### ISSUE THREAD

**Issue by billy-sg** [stascorp/rdpwrap#1506]
Hi still shows not supported! any help will be appreciated.

screenshot attached:

![rdpwrap ini](https://user-images.githubusercontent.com/89935330/131718013-5b175eaf-e76d-4d10-a6a3-38137ad96806.PNG)

thanks

**Comment by billy-sg** [comment]
![rdpwrap ini](https://user-images.githubusercontent.com/89935330/131718013-5b175eaf-e76d-4d10-a6a3-38137ad96806.PNG)

See snip attached

**Comment by affinityv** [comment]
[See this](https://github.com/stascorp/rdpwrap/issues/1507)

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
