### ISSUE TITLE
Win 10 ver 19042.1165 not supported

### ISSUE THREAD

**Issue by escapelord** [stascorp/rdpwrap#1507]
I tried version 19041.1081 not working.

I would be very grateful if you could share an ini file or solution for version 19042.1165.

Thank you from now

**Comment by affinityv** [comment]
Copy in this [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini)
Then `RDPWInst.exe -r` as an admin, or just do a restart with the new INI ready in place.

I believe you are using "Windows Version 19042.1165", which is different to the version of the "termsrv.dll" file.

**Comment by escapelord** [comment]
it worked thank you very much.

**Comment by Kevinmain** [comment]
> Copy in this [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini)
> Then `RDPWInst.exe -r` as an admin, or just do a restart with the new INI ready in place.
> 
> I believe you are using "Windows Version 19042.1165", which is different to the version of the "termsrv.dll" file.

Thank you so much!!

**Comment by jjloljj** [comment]
Great work, its working on 1165 restart pc need it in the end!

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
