### ISSUE TITLE
Not Listening ver 10.0.19041.1081

### ISSUE THREAD

**Issue by BrysonHowe** [stascorp/rdpwrap#1510]
Please help me I have tried so much I have been trying for 3 days straight. I have tried different ini files uninstalling reinstalling different installers and changed settings lots. I seriously don't know what to do anymore. 
Here is my version and what it looks like
![RDP CONFIG](https://user-images.githubusercontent.com/60513820/131950290-77e7d6aa-a37b-422f-8422-46d428be4846.PNG)
Here is my windows OS build
![OS BUILD](https://user-images.githubusercontent.com/60513820/131950312-882c1aab-a1ff-4349-9d9d-22639e1520c9.PNG)

**Comment by BrysonHowe** [comment]
and everytime because of this i instantly get access denied :(

**Comment by BrysonHowe** [comment]
https://user-images.githubusercontent.com/60513820/131956436-d3a63245-d097-4ba3-af55-e1140d269f51.MOV this is what happens when I say it gives me access denied

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
