### ISSUE TITLE
RDP wrapper is all green but did't work concurrent

### ISSUE THREAD

**Issue by chinjungmaruko** [stascorp/rdpwrap#1513]
I have installed RDP wrapper and status is fully supported and Listening But it did not work concurrent connections 

Help me please

Window 10 pro 19042.1165

**Comment by chinjungmaruko** [comment]
I can fixed it.

**Comment by nattlip** [comment]
how ?

**Comment by chinjungmaruko** [comment]
> how ?

I go to discord group and install mod version from that group.

Ref. https://github.com/stascorp/rdpwrap/issues/1484#issuecomment-889879016
