### ISSUE TITLE
View 19043.1165 not support.

### ISSUE THREAD

**Issue by xyh0107** [stascorp/rdpwrap#1518]
View 19043.1165 not supported.

**Comment by sashaqwert** [comment]
You have specified the Windows version (19043.XXX)
The termsrv.dll versions for this version are 10.0.19041.XXX

Please attach a screenshot of RDPConf.

**Comment by Howeverz** [comment]
![image](https://user-images.githubusercontent.com/84467084/133473259-342a66a5-2e67-40ef-bf1c-e0c005ccf140.png)
![image](https://user-images.githubusercontent.com/84467084/133473305-388dee9d-3c97-44ea-91f3-74a41d8f1088.png)
![image](https://user-images.githubusercontent.com/84467084/133473431-832b6180-1275-4eb0-974c-e5e075594199.png)


can help with this it only appear blank when i try to open rdpcheck

**Comment by Howeverz** [comment]
![image](https://user-images.githubusercontent.com/84467084/133473533-b8869896-c7a8-4075-8bcf-74d0f7bae9a3.png)
![image](https://user-images.githubusercontent.com/84467084/133473550-7ad51d68-0ad4-4009-b3fc-12ae70dffdaa.png)
![image](https://user-images.githubusercontent.com/84467084/133473570-8b02eb7d-ae73-43f2-af3f-8a7d6bccea41.png)


can help with this if anyone have the correct ini file that can work and support for 19043.1165

**Comment by sashaqwert** [comment]
@Howeverz 
1. RDPConf is obsolete. Do not use this
2. Set network level authentication in RDPConf and system settings
3. Reboot
4. Use `mstsc --> 127.0.0.2` to check

If not work try migrate from Microsoft account to local account.

**Comment by Howeverz** [comment]
> @Howeverz
> 
> 1. RDPConf is obsolete. Do not use this
> 2. Set network level authentication in RDPConf and system settings
> 3. Reboot
> 4. Use `mstsc --> 127.0.0.2` to check
> 
> If not work try migrate from Microsoft account to local account.

i've try mstsc before also with network level authentication and it same only appear blank like that with mstsc

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
