### ISSUE TITLE
Does't support UDP port on RDP 8.0

### ISSUE THREAD

**Issue by quyanwei** [stascorp/rdpwrap#152]
Does't support UDP port on RDP 8.0 and above?

**Comment by binarymaster** [comment]
Never heard that RDP can work over UDP.

**Comment by nkrepo** [comment]
You can try the solution suggested at http://blog.chrischua.net/2015/10/15/rdp-8-0-udp-vs-pcoip/ and you may be able to connect.

**Comment by art567** [comment]
@binarymaster would you add this option as checkbox in RDPConf ?

**Comment by binarymaster** [comment]
@art567 since this feature is optional and not available in any RDP versions, I doubt about it.

**Comment by quyanwei** [comment]
Thank you very much！
----- 原始邮件 -----
发件人：binarymaster <notifications@github.com>
收件人：stascorp/rdpwrap <rdpwrap@noreply.github.com>
抄送人：quyanwei <quyanwei@sina.com>,  Author <author@noreply.github.com>
主题：Re: [stascorp/rdpwrap] Does't support UDP port on RDP 8.0 (#152)
日期：2016年09月08日 19点23分

@art567 since this feature is optional and not available in any RDP versions, I doubt about it.

&mdash;

**Comment by Porgi** [comment]
@binarymaster UDP is default in RDP, if the UDP port is blocked it falls back to TCP

**Comment by sebaxakerhtc** [comment]
Closed as not actual
