### ISSUE TITLE
Solution for 19043.1237

### ISSUE THREAD

**Issue by cahebebe** [stascorp/rdpwrap#1520]
For: 2021-09 Update for Windows 10 Version 21H1 for x64-based Systems (KB5005565)

Just append these lines into your rdpwrapper.ini file and execute "RDPWInst.exe -r":

[10.0.19043.1237]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=89D81
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB26
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=19105
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1E98C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19043.1237-SLInit]
bInitialized.x64 =107108
bServerSku.x64 =10710C
lMaxUserSessions.x64 =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64 =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64 =10712C

**Comment by alanscordoba** [comment]
Hello, I did the steps indicated, but it still does not work

![image](https://user-images.githubusercontent.com/42641954/133437435-5b9253be-ab42-4d98-9df8-325d4d5ea5e6.png)

**Comment by pascualdas** [comment]
Just verify os version show by RDPConf.exe in field ver. in front of Service State and replace between [xxx].

[10.0.19041.1202]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=89D81
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB26
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=19105
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1E98C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.1202-SLInit]
bInitialized.x64 =107108
bServerSku.x64 =10710C
lMaxUserSessions.x64 =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64 =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64 =10712C

**Comment by SquawkWoof** [comment]
@cahebebe: this did not work for me.  Updated INI file and ran `RDPWInst.exe -r`.  Still doesn't work after a reboot.

**Comment by gitgotgone** [comment]
@cahebebe: Running 10.0.19043.1237, appending did not work for me either. BTW, it's rdpwrap.ini not rdpwrapper.ini. 
:-(
Renamed ini to txt and uploaded it for your perusal to see if there is something else that needs to be edited out for it to work.

[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/7170777/rdpwrap.txt)

**Comment by cahebebe** [comment]
[rdpwrap.ini.txt](https://github.com/stascorp/rdpwrap/files/7170809/rdpwrap.ini.txt)
![2021-09-15 09 18 07](https://user-images.githubusercontent.com/16362456/133450594-4edf71e7-ce9b-4c4c-a073-66ade6bea087.jpg)

**Comment by SquawkWoof** [comment]
@cahebebe: I tried using your INI file, still not really working.

Tested on one system, still says `[not supported]`.

Tested on a second system, it shows `[fully supported]` but doesn't allow concurrent sessions.

Both are running Win10 Pro 21H1 19043.1237

**Comment by jbark25** [comment]
@cahebebe I'm also running into [not supported] after taking the necessary steps.

@pascualdas trying your method, I get the below. I'm assuming it is because my OS version number does not match what the tool is expecting? Any suggestions on this front?

![image](https://user-images.githubusercontent.com/82134038/133474576-d580c071-07b1-421e-a071-f1c63c57fab2.png)


Also, my version of windows is 19043.1237

**Comment by SquawkWoof** [comment]
@jbark25 are you able to use concurrent RDP sessions or concurrent RDP/onsite sessions?

**Comment by flybeye** [comment]
@jbark25 /@SquawkWoof ... Using cahebebe additions, I updated the rdpwrap.ini without the RDPWInst.exe -r, which will pull the ini if updated from the repository, 

1-Stop Remote desktop service, termservice, via Services.msc, or command line with admin, net stop termservice
2-Update rdpwrap.ini
3-Start Remote desktop service, termservice, via Services.msc, or command line with admin, net start termservice

![image](https://user-images.githubusercontent.com/22753145/133500040-75b52689-5aab-47c6-8203-d5ec5bc221e4.png)

**Comment by SquawkWoof** [comment]
@flybeye thanks, that seems to be the trick.   I guess the original procedure was the incorrect order?

**Comment by paulspehar** [comment]
Got it going with the ini from @cahebebe .  thanks

**Comment by gitgotgone** [comment]
Worked running 1237 using @cahebebe ini file (reposted below), not appending per initial instructions, and using @flybeye instructions with admin cmd net stop/start termservice. (Just don't make my noob mistake of running net stop termservice through an RDP session, lol.)

@flybeye seems to be correct that running update will overwrite ini file with one that currently doesn't work. That includes the autoupdate.bat file.

Thanks everyone!

[rdpwrap.ini.txt](https://github.com/stascorp/rdpwrap/files/7175010/rdpwrap.ini.txt)

**Comment by vsdotnetguy** [comment]
@jbark25 Hello, did you get this to work?  I'm getting the exact same results in RDP Wrapper Configuration as you.  The only difference is my Windows version is 10.0.19041.1237 not 10.0.19043.1237.  It's saying [fully supported], but the termservice will not not stay up and running.

Is anyone seeing the same behavior?

**Comment by paulspehar** [comment]
@vsdotnetguy 
I have it working with 10.0.19041.1202.  Although that's a different build than either mentioned here, I am not finding 10.0.19041.1237 in the ini from cahebebe .  10.0.19043.1237 and my build are both in the cahebebe ini

I used the same steps as flybeye with ini from cahebebe 

I attempted to edit the ini myself and had no luck. 

![image](https://user-images.githubusercontent.com/52802297/133821533-271c3807-820c-4f7b-bb01-8b07a9a1897a.png)


I am guessing you need something like this

```
[10.0.19041.1237]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=89D81
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB26
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=19105
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1E98C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.1237-SLInit]
bInitialized.x64 =107108
bServerSku.x64 =10710C
lMaxUserSessions.x64 =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64 =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64 =10712C
```

**Comment by vsdotnetguy** [comment]
@paulspehar Yes, I used the same steps as @flybeye with the ini from @cahebebe.  I'm using 10.0.19041.1237 in the ini file.  That fixed the [fully supported], however, I'm still seeing same as @jbark25, with service stopped and not listening.  For reference my Windows version is 10.0.19041.1237.

**Comment by vsdotnetguy** [comment]
@paulspehar @cahebebe @flybeye @pascualdas @jbark25 I meant to say I'm using [10.0.19014.1202] in the ini file which is giving me [fully supported] in the RDP Wrapper Configuration results.  However, the service starts but will not stay up for more than a few seconds

**Comment by paulspehar** [comment]
It's a familiar issue I have run into here myself.  Maybe something is borked with the file. Diff your ini to a fresh cahebabe download and see if anything jumps out at you as a problem. Winmerge is a handy diff tool and available on ninite.com for convenience.

**Comment by egenchen** [comment]
> [rdpwrap.ini.txt](https://github.com/stascorp/rdpwrap/files/7170809/rdpwrap.ini.txt)
> ![2021-09-15 09 18 07](https://user-images.githubusercontent.com/16362456/133450594-4edf71e7-ce9b-4c4c-a073-66ade6bea087.jpg)

![image](https://user-images.githubusercontent.com/506664/133879552-6b8155bc-78ec-4a79-b8d7-27400fb7aaf3.png)
thanks, this config works for me.
after replace the ini, run:

```
RDPWInst.exe -u
RDPWInst.exe -i
RDPWInst.exe -r
```

then check with ```RDPConf.exe```

**Comment by mrjoecastellon** [comment]
> [rdpwrap.ini.txt](https://github.com/stascorp/rdpwrap/files/7170809/rdpwrap.ini.txt)
> ![2021-09-15 09 18 07](https://user-images.githubusercontent.com/16362456/133450594-4edf71e7-ce9b-4c4c-a073-66ade6bea087.jpg)

I had tried so many things, but using your ini file finally got my RDP Wrapper working properly again! I have concurrent users and everything. 

Thank you!!
![image](https://user-images.githubusercontent.com/91094235/134070929-109a6a93-d3c9-42c6-9476-77bee78e9153.png)

**Comment by jbark25** [comment]
This also worked for me! I used @cahebebe .ini file and ran the below commands after changing directory to where I downloaded RDPwrap

RDPWInst.exe -u
RDPWInst.exe -i
RDPWInst.exe -r

**Comment by priyadarshanparida** [comment]
> [rdpwrap.ini.txt](https://github.com/stascorp/rdpwrap/files/7170809/rdpwrap.ini.txt)
> ![2021-09-15 09 18 07](https://user-images.githubusercontent.com/16362456/133450594-4edf71e7-ce9b-4c4c-a073-66ade6bea087.jpg)

Thank you @cahebebe for sharing the file. This worked for me.
Edition Windows 10 Home
Version 21H1
OS build 19043.1237

I have posted detailed steps here: https://github.com/stascorp/rdpwrap/issues/1530

**Comment by priyadarshanparida** [comment]
> @jbark25 /@SquawkWoof ... Using cahebebe additions, I updated the rdpwrap.ini without the RDPWInst.exe -r, which will pull the ini if updated from the repository,
> 
> 1-Stop Remote desktop service, termservice, via Services.msc, or command line with admin, net stop termservice
> 2-Update rdpwrap.ini
> 3-Start Remote desktop service, termservice, via Services.msc, or command line with admin, net start termservice
> 
> ![image](https://user-images.githubusercontent.com/22753145/133500040-75b52689-5aab-47c6-8203-d5ec5bc221e4.png)

Thank you @flybeye. The steps you shared worked for me.

Edition Windows 10 Home
Version 21H1
OS build 19043.1237

I have posted detailed steps here: https://github.com/stascorp/rdpwrap/issues/1530

**Comment by famzah** [comment]
@binarymaster, can you commit in the dist INI file here with @cahebebe data? Other people and I confirm that it's working.

**Comment by songfuqiangcn** [comment]
thinks

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1509
