### ISSUE TITLE
Remote desktop setting do not appear 

### ISSUE THREAD

**Issue by wellingtonboots** [stascorp/rdpwrap#1521]
Hi,
I recently installed RDPwrapper and it works well, I can connect to it locally and remotely.
However I noticed that despite it working I cannot see remote desktop setting on the system properties under remote
![image](https://user-images.githubusercontent.com/74498415/133480260-0f117e86-1dad-4735-96aa-8012193f5067.png)

So I can only see remote assistance part but I should be able to see the remote desktop part as well according to https://www.windowscentral.com/how-use-remove-desktop-app-connect-pc-windows-10-0

I mainly want to access this so I can term remote desktop on and off. I am afraid of leaving it open when I'm not using it. 
If there is another way to do this please let me know.

**Comment by sebaxakerhtc** [comment]
Not an rdpwrapper issue
