### ISSUE TITLE
Version 10.0.18362.1766 Not Supported

### ISSUE THREAD

**Issue by ZhenhongDu** [stascorp/rdpwrap#1522]
Hello,

Can someone please provide the rdpwrap.ini file (or patch) for Windows 10 version 10.0.18362.1766?The supported radwrap.ini file cannot be found.

Thank you

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/7174622/termsrv.zip)

**Comment by lenih** [comment]
Windows 10 version 10.0.18362.1766 not support(( plz help

**Comment by 090media** [comment]
Yep. Time for a new INI. Fun times. Thanks, Microsoft!!

**Comment by josfuq** [comment]
For me this worked — editing termsrv.dll in Windows/system32 with Hex editor:
1) Stop Remote Desktop Services in Services
2) Find piece contains
39 81 3C 06 00 00 XX XX XX XX XX XX
3) Replace with
B8 00 01 00 00 89 81 38 06 00 00 90
4) Reboot

**Comment by thijijs** [comment]
so what do we have to do?
maybe uninstall latest windows update or something, sorry im not really expert but would like it to work again

thank you

**Comment by LiranSX** [comment]
also waiting for this

**Comment by alanscordoba** [comment]
Hello, I am also waiting for the solution, thank you very much in advance.

**Comment by thijijs** [comment]
i got it working again using this post: https://github.com/stascorp/rdpwrap/issues/194#issuecomment-323564111
copied the rfxvmt.dll to windows\system32 and uninstalled rdpwrap, and reinstalled it, and behold it was working again yay 
(not sure if all steps are needed, or why it is working again, but im happy)

**Comment by ZhenhongDu** [comment]
> i got it working again using this post: [#194 (comment)](https://github.com/stascorp/rdpwrap/issues/194#issuecomment-323564111)
> copied the rfxvmt.dll to windows\system32 and uninstalled rdpwrap, and reinstalled it, and behold it was working again yay
> (not sure if all steps are needed, or why it is working again, but im happy)

This seems does not work for my computer....

**Comment by alanscordoba** [comment]
> i got it working again using this post: [#194 (comment)](https://github.com/stascorp/rdpwrap/issues/194#issuecomment-323564111)
> copied the rfxvmt.dll to windows\system32 and uninstalled rdpwrap, and reinstalled it, and behold it was working again yay
> (not sure if all steps are needed, or why it is working again, but im happy)

This solution didn't work for me either. Please help.

**Comment by thijijs** [comment]
maybe try reinstalling it like that with one of the new ini files? 

https://github.com/stascorp/rdpwrap/issues/1520#issuecomment-922229056
after replace the ini, run:

RDPWInst.exe -u
RDPWInst.exe -i
RDPWInst.exe -r

then check with RDPConf.exe

**Comment by alanscordoba** [comment]
> tal vez intente reinstalarlo así con uno de los nuevos archivos ini?
> 
> [# 1520 (comentario)](https://github.com/stascorp/rdpwrap/issues/1520#issuecomment-922229056)
> después de reemplazar el ini, ejecute:
> 
> RDPWInst.exe -u
> RDPWInst.exe -i
> RDPWInst.exe -r
> 
> luego verifique con RDPConf.exe

I tried it, but it still doesn't work.

**Comment by im03lg** [comment]
removed the last update and everything worked. 
Version 10.0.18362.1766 -> 10.0.18362.1533

**Comment by HumMan** [comment]
> Hello,
> 
> Can someone please provide the rdpwrap.ini file (or patch) for Windows 10 version 10.0.18362.1766?The supported radwrap.ini file cannot be found.
> 
> Thank you
> 
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/7174622/termsrv.zip)

Can you try [this](https://git.ixarea.com/backup/rdpwrap.ini/src/branch/master/autogenerated/10.0.18362.1766-autogenerated.ini) config file? It shows "fully supported" for me

**Comment by ZhenhongDu** [comment]
> > Hello,
> > Can someone please provide the rdpwrap.ini file (or patch) for Windows 10 version 10.0.18362.1766?The supported radwrap.ini file cannot be found.
> > Thank you
> > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/7174622/termsrv.zip)
> 
> Can you try [this](https://git.ixarea.com/backup/rdpwrap.ini/src/branch/master/autogenerated/10.0.18362.1766-autogenerated.ini) config file? It shows "fully supported" for me

It works well, thank you!

> > Hello,
> > Can someone please provide the rdpwrap.ini file (or patch) for Windows 10 version 10.0.18362.1766?The supported radwrap.ini file cannot be found.
> > Thank you
> > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/7174622/termsrv.zip)
> 
> Can you try [this](https://git.ixarea.com/backup/rdpwrap.ini/src/branch/master/autogenerated/10.0.18362.1766-autogenerated.ini) config file? It shows "fully supported" for me

It works well, thank you!

**Comment by colapsys** [comment]
Signing in using your GitHub account without a pre-existing GitLab account is not allowed. 

i try to connect with my github account ... no luck ... can someone plz share the config file ?

Thank you.

**Comment by fire717** [comment]
> 

Same error, too.

**Comment by kevindd992002** [comment]
So is this project dead?
