### ISSUE TITLE
How to modify the termsrv.dll file directly in the new version, and where and what values need to be modified

### ISSUE THREAD

**Issue by pacolala** [stascorp/rdpwrap#1523]
yufei8051 said: Open termsrv.dll with a hexadecimal editor, find "39 81 3C 06 00 00 0f 84" and any subsequent four bytes (A18F0100 in 17763.1697 version), replace it with "B8 00 01 00 89 81 38 06 00 90", and replace the file after saving.

ReFerence Issue:https://github.com/stascorp/rdpwrap/issues/1373#issuecomment-858293128_

It works in version 17763.1697,but not work in the newer Versions

How to modify the termsrv.dll file directly in the new version, and How can i know where and what values need to be modified

Thx~!

**Comment by binarymaster** [comment]
This project is not about modifying binaries.
