### ISSUE TITLE
I need the INI configuration file for 17763.107

### ISSUE THREAD

**Issue by chahbzck** [stascorp/rdpwrap#1525]
谁能告诉我哪里可以找到17763.107的ini配置文件
谢谢！

**Comment by chahbzck** [comment]
Who can tell me where to find the INI configuration file of 17763.107

thank you!

**Comment by sebaxakerhtc** [comment]
> Who can tell me where to find the INI configuration file of 17763.107
> 
> thank you!

Attach a screenshot of rdpconf and your termsrv.dll
Is your Windows x86 or x64?

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
