### ISSUE TITLE
Not Listening ver 10.0.19041.1202  x86

### ISSUE THREAD

**Issue by IljaM13** [stascorp/rdpwrap#1526]
I dont know why the prev. issue was closed!!!

x86 ist still missed.

**Comment by rm-2021** [comment]
Same issue after latest update.  I removed the update and working again.  Additionally I paused updates until October 21 (which is the max allowed at the time).   Hopefully there is a fix.

**Comment by aralfer** [comment]
installing autoupdater downloaded a new INI that supports 1202 but I cant get it to work. I swear I tried everything.

https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

**Comment by aralfer** [comment]
https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

**Comment by aralfer** [comment]
I rolled back the update, but no way. It still shows 1081 as fully supported but nothing. it just does not work :(

when connecting from another PC it disconnects local session, and rdpcheck just switchs users.

**Comment by IljaM13** [comment]
> installing autoupdater downloaded a new INI that supports 1202 but I cant get it to work. I swear I tried everything.
> 
> https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

Autoupdate does not concider x86 because the author only updates x64

**Comment by aralfer** [comment]
I use x64

Ariel Fernández
Director
[AFER IT & Internet Solutions]

**Comment by rm-2021** [comment]
After removing the update, I ran the unistall.bat file and did the install procedure again.  I just checked if I can log in remotely and is working.  Also make sure to add the rdpwrap directory to the exception list of anit-virus program.

**Comment by aralfer** [comment]
Yeah, no luck. :(

Ariel Fernández
Director
[AFER IT & Internet Solutions]

**Comment by rm-2021** [comment]
If the local session is being kicked out when logging in remotely then sound like  single session per user.   Uncheck the box  in rdpconf.exe

**Comment by aralfer** [comment]
The local session gets kicked out when anyone logs in, that box is
unchecked.

I did saw it working before the update.

**Comment by Jamskijam** [comment]
https://github.com/stascorp/rdpwrap/issues/1509#issuecomment-921345297

**Comment by Jamskijam** [comment]
Copy from x86 section [10.0.19041.1081] to [10.0.19041.1202]. This is working on 32bit 10.0.19041.1202!!!
Yes, author ignore x86 in updates.

**Comment by Jamskijam** [comment]
[10.0.19041.1202]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=89D81
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0D212
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=19105
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1E98C
SLInitFunc.x64=New_CSLQuery_Initialize
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B66B9
LocalOnlyCode.x86=jmpshort
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E899
DefPolicyCode.x86=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=68809
SLInitFunc.x86=New_CSLQuery_Initialize

[10.0.19041.1202-SLInit]
bInitialized.x64      =107108
bServerSku.x64        =10710C
lMaxUserSessions.x64  =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64  =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64       =10712C
bInitialized.x86      =D1A04
bServerSku.x86        =D1A08
lMaxUserSessions.x86  =D1A0C
bAppServerAllowed.x86 =D1A14
bRemoteConnAllowed.x86=D1A1C
bMultimonAllowed.x86  =D1A20
ulMaxDebugSessions.x86=D1A24
bFUSEnabled.x86       =D1A28

**Comment by IljaM13** [comment]
> Copy from x86 section [10.0.19041.1081] to [10.0.19041.1202]. This is working on 32bit 10.0.19041.1202!!!
> Yes, author ignore x86 in updates.

Thanks! That works!

**Comment by affinityv** [comment]
Best to submit the 32 bit (x86) DLL and have it assessed properly; only the 64 bit (x64) DLL had been submitted.

But really, it's about time everyone used 64 bit these days; why would anybody install 32 bit Windows now, are there some kind of edge cases out there that won't work with 64 bit Windows?

As less and less people use 32 bit Windows, this is likely to be a problem going forward; that is, unless someone whom continues to use 32 bit Windows is happy to keep submitting their termsrv.dll when it is updated (and perhaps more than one person as there are variations of releases/builds as well.

**Comment by affinityv** [comment]
> [10.0.19041.1202]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=89D81
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0D212
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=19105
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1E98C
> SLInitFunc.x64=New_CSLQuery_Initialize
> LocalOnlyPatch.x86=1
> LocalOnlyOffset.x86=B66B9
> LocalOnlyCode.x86=jmpshort
> DefPolicyPatch.x86=1
> DefPolicyOffset.x86=3E899
> DefPolicyCode.x86=CDefPolicy_Query_eax_rcx
> SLInitHook.x86=1
> SLInitOffset.x86=68809
> SLInitFunc.x86=New_CSLQuery_Initialize
> 
> [10.0.19041.1202-SLInit]
> bInitialized.x64 =107108
> bServerSku.x64 =10710C
> lMaxUserSessions.x64 =107110
> bAppServerAllowed.x64 =107118
> bRemoteConnAllowed.x64=107120
> bMultimonAllowed.x64 =107124
> ulMaxDebugSessions.x64=107128
> bFUSEnabled.x64 =10712C
> bInitialized.x86 =D1A04
> bServerSku.x86 =D1A08
> lMaxUserSessions.x86 =D1A0C
> bAppServerAllowed.x86 =D1A14
> bRemoteConnAllowed.x86=D1A1C
> bMultimonAllowed.x86 =D1A20
> ulMaxDebugSessions.x86=D1A24
> bFUSEnabled.x86 =D1A28

btw that INI above is missing these three entries:
  SingleUserPatch.x86 
 SingleUserOffset.x86
 SingleUserCode.x86

**Comment by affinityv** [comment]
I will publish a new ini tomorrow to incorporate the sections in full from https://github.com/stascorp/rdpwrap/issues/1501
(it will cover both x86 sections for each of 10.0.19041.1081 and 10.0.19041.1202 on the basis that the issue 1501 reports it as working and that both x64 versions were identical for these builds)

**Comment by affinityv** [comment]
[INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file updated as promised

**Comment by Jamskijam** [comment]
> Best to submit the 32 bit (x86) DLL and have it assessed properly; only the 64 bit (x64) DLL had been submitted.
> 
> But really, it's about time everyone used 64 bit these days; why would anybody install 32 bit Windows now, are there some kind of edge cases out there that won't work with 64 bit Windows?
> 
> As less and less people use 32 bit Windows, this is likely to be a problem going forward; that is, unless someone whom continues to use 32 bit Windows is happy to keep submitting their termsrv.dll when it is updated (and perhaps more than one person as there are variations of releases/builds as well.

Old PC with 2gb ram in organisation, updated to Windows 10 32 bit

**Comment by affinityv** [comment]
> Old PC with 2gb ram in organisation, updated to Windows 10 32 bit

Really, I know that there is a labor cost in setting up a new PC, but a newer PC would cost peanuts with more RAM and a better CPU (amongst other things).  I could understand if there was a hardware component that is legacy and wouldn't work in a newer PC.

**Comment by mymobilmail** [comment]
Remove KB5005565, it helped me

**Comment by aralfer** [comment]
My friends,

I could not wait anymore so I ended up adding 2 old Athlon 250 x2 CPU.

But I agree on removing that one KB, it also breaks shared printers.

Ariel Fernández
Director
[AFER IT & Internet Solutions]

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1509
