### ISSUE TITLE
I need the INI configuration file 10.0.19041.1202 x64

### ISSUE THREAD

**Issue by huanhaishijie** [stascorp/rdpwrap#1527]

**Comment by huanhaishijie** [comment]
I need the INI configuration file for 10.0.19041.1202 x64

**Comment by ufxpri** [comment]
maybe this comment would help you
[https://github.com/stascorp/rdpwrap/issues/1520#issuecomment-920577168](https://github.com/stascorp/rdpwrap/issues/1520#issuecomment-920577168)
he uploaded his ini file with 10.0.19041.1201 in there

**Comment by huanhaishijie** [comment]
thank you！

**Comment by Tonk2415** [comment]
thank you

**Comment by sebaxakerhtc** [comment]
duplicate of https://github.com/stascorp/rdpwrap/issues/1509
