### ISSUE TITLE
rdpwrap-v1.6.2.zip is empty and msi-file is invalid

### ISSUE THREAD

**Issue by Goethinger** [stascorp/rdpwrap#1529]
Hi,
Today I downloaded the files rdpwrap-v1.6.2.zip and .msi.
Zip-file seems to be empty, msi-file is invalid.
Firefox and Chrome marked the files as infected.
Tested on two different PC´s.

Where is the problem?
Regards

**Comment by sebaxakerhtc** [comment]
> Firefox and Chrome marked the files as infected. Tested on two different PC´s.
> 
> Where is the problem?

Turn off yopur antivirus as mentioned at readme.md
