### ISSUE TITLE
Change Config from CMD

### ISSUE THREAD

**Issue by dtraboulsi24** [stascorp/rdpwrap#153]
Hello,
I was wondering if you could change the settings in the RDP Wrapper Configuration from command line. I tried to manually change these settings through regedit before and after installation of the RDPWrapper, but it still shows the 3389 port even though I am using a different port. Thanks in advance!

**Comment by binarymaster** [comment]
You may change Terminal Services configuration using registry and `reg` command.

Use this command for port changing:

`reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v PortNumber /t REG_DWORD /d 3389 /f`

Note that it will require to disable and re-enable RDP to apply changes.
