### ISSUE TITLE
10.0.19041.1023 all looks good but not working!!! 

### ISSUE THREAD

**Issue by BALAHLOP** [stascorp/rdpwrap#1531]
Everything worked good until the last windows update, i updated the ini file, status went to fully suported but i still can't connect to computer, ask me to log out from main computer to give posibility to the other computer to connect to him. What can be the problem? maybe i missed a file
![rdpwrap](https://user-images.githubusercontent.com/79150938/134004105-0b55e0c8-533f-45c2-b447-daa2cbbf51c7.jpg)
?

**Comment by philipejapa** [comment]
HELLO FRIEND, I'M USING THIS FILE TRY IT
[rdpwrap.TXT](https://github.com/stascorp/rdpwrap/files/7203660/rdpwrap.TXT)

**Comment by philipejapa** [comment]
COPY THE CONTENT AND SAVE IT TO YOUR RDPWRAP.INI REMEMBERING THAT YOU MUST DISCONNECT FROM THE NETWORK TO MAKE THE CHANGE

**Comment by zekecarter** [comment]
> Everything worked good until the last windows update, i updated the ini file, status went to fully suported but i still can't connect to computer, ask me to log out from main computer to give posibility to the other computer to connect to him. What can be the problem? maybe i missed a file
> ![rdpwrap](https://user-images.githubusercontent.com/79150938/134004105-0b55e0c8-533f-45c2-b447-daa2cbbf51c7.jpg)
> ?

try this [Video in spanish](https://www.youtube.com/watch?v=hH4iaRAFALE) , but works

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1420
