### ISSUE TITLE
10.0.20348.143 (Server 2022)

### ISSUE THREAD

**Issue by BrianDouglasSage** [stascorp/rdpwrap#1532]
There appears to be an entry for this version but it doesn't work

![image](https://user-images.githubusercontent.com/77943577/134193171-1b5d1bdd-85f8-4bac-af8a-fafaad6718c1.png)

[10.0.20348.143]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=97231
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=08A32
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1B7A5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22600
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.20348.143-SLInit]
bInitialized.x64      =11EEAC
bServerSku.x64        =11EEB0
lMaxUserSessions.x64  =11EEB4
bAppServerAllowed.x64 =11EEBC
bRemoteConnAllowed.x64=11EEC4
bMultimonAllowed.x64  =11EEC8
ulMaxDebugSessions.x64=11EED0
bFUSEnabled.x64       =11EED4

**Comment by sebaxakerhtc** [comment]
> There appears to be an entry for this version but it doesn't work

RDP Wrapper is not installed
