### ISSUE TITLE
RDP wrap

### ISSUE THREAD

**Issue by ateeqshafiq** [stascorp/rdpwrap#1535]
Hello, thanks for sharing the wrapper. Unfortunately the solution doesn't work for me. Details are as follows:
Edition: Windows 10 Home
Version: 21H1
OS Build: 19043.1237
This is what I see on running rdpconf (as an administrator)
Wrapper state: Installed ver. 1.5.0.0
Service state: Running ver. 10.0.19041.1202
Listener state: Not listening [Not supported]
Any suggestion?

**Comment by zekecarter** [comment]
> Hello, thanks for sharing the wrapper. Unfortunately the solution doesn't work for me. Details are as follows:
> Edition: Windows 10 Home
> Version: 21H1
> OS Build: 19043.1237
> This is what I see on running rdpconf (as an administrator)
> Wrapper state: Installed ver. 1.5.0.0
> Service state: Running ver. 10.0.19041.1202
> Listener state: Not listening [Not supported]
> Any suggestion?

try this [https://www.youtube.com/watch?v=hH4iaRAFALE](https://www.youtube.com/watch?v=hH4iaRAFALE)

**Comment by ateeqshafiq** [comment]
thankyou
