### ISSUE TITLE
HEPL VERSION 10.0.14393.3383

### ISSUE THREAD

**Issue by Ulimamalon** [stascorp/rdpwrap#1538]
HELP!!
I NEED RDPWRAP.INI FOR TERMSRV VERSION 10.0.14393.3383

**Comment by sebaxakerhtc** [comment]
> HELP!! I NEED RDPWRAP.INI FOR TERMSRV VERSION 10.0.14393.3383

Attach a screenshot of rdpconf and your termsrv.dll
Is your Windows x86 or x64?

**Comment by sebaxakerhtc** [comment]
Closed because of missibg answer
