### ISSUE TITLE
Windows 10 Enterprise (10.0. 18363 Build 18363) Supported but not working

### ISSUE THREAD

**Issue by solidraj123** [stascorp/rdpwrap#1539]
![image](https://user-images.githubusercontent.com/91308730/134628191-8137cf33-26e2-460c-ba17-d81933eaa94a.png)

![image](https://user-images.githubusercontent.com/91308730/134628308-b45bb6af-5259-4507-bf24-57fd24d4d1b9.png)

Please support

**Comment by sebaxakerhtc** [comment]
> Please support

Still you have the issue?

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
