### ISSUE TITLE
x86 c++ code

### ISSUE THREAD

**Issue by mehmetgoksu** [stascorp/rdpwrap#154]
hı am a new c and c++ coder and looking for create my own build but your source is ı think russian can you update and can you tell how to use it dll ?

**Comment by binarymaster** [comment]
Readme file in C++ folder was autogenerated by Visual Studio, which was installed on system with russian localization.

But the source code is english, you shouldn't have problems with it.

**Comment by mehmetgoksu** [comment]
actually ı want to know that ı have a my own project and ı dont know how to use this dll with my project there is no document for this

**Comment by binarymaster** [comment]
I think there are no such use cases. Which way do you want to use it, and what's your project?

**Comment by mehmetgoksu** [comment]
ı want to use it static not dll my project is basic rdp connection when ı away from home

**Comment by binarymaster** [comment]
Well, this application doesn't implement such things. It's just a wrapper between SCM and TS, and it will work only in conjunction with them.

You can't build an arbitary application with RDP protocol, using this code.

**Comment by mehmetgoksu** [comment]
ı will use windows rdp and ı want to use wrapper because this allow to use multi session(when connect dont log off current user) ı know its for TS thats already what ı want .but ı dont know how to use it

**Comment by binarymaster** [comment]
Just install and use it, see releases section.

If you want to build it from source, open Visual Studio solution and build the DLL, this also will help:
http://stackoverflow.com/questions/32281940/how-to-publish-or-export-x86-and-x64-c-version-of-rdpwrap

**Comment by mehmetgoksu** [comment]
yeah i did it this dll and now what should ı do ? loadlibrary ?

**Comment by binarymaster** [comment]
You actually can do `LoadLibrary` but what next?

**Comment by mehmetgoksu** [comment]
this is what ı am asking :) how to use dll

**Comment by binarymaster** [comment]
Oh... the answer is very simple.

You can use it, but can't. Because it doesn't implement any functions that can be used probably in any project.

As you can see, there are two exported functions, `ServiceMain` and `SvchostPushServiceGlobals`:

https://github.com/stascorp/rdpwrap/blob/59b1924af9f4d510a6974baa7f6d9fd99e61a060/src-x86-x64-Fusix/RDPWrap.cpp#L853

https://github.com/stascorp/rdpwrap/blob/59b1924af9f4d510a6974baa7f6d9fd99e61a060/src-x86-x64-Fusix/RDPWrap.cpp#L862

They are triggered by a `svchost.exe` process when starting a service. These function calls are processed and then redirected into `termsrv.dll` by wrapper. And that's all.

**Comment by mehmetgoksu** [comment]
so in my home project ı should call this function ?

**Comment by binarymaster** [comment]
You may try to call it, but I think you'll got nothing. It will work only in the context of the svchost.

**Comment by mehmetgoksu** [comment]
would you mind if you can give me example code how to use dll please ?

**Comment by binarymaster** [comment]
Unfortunately I don't have such code.

**Comment by mehmetgoksu** [comment]
ı dont understnd clearly .. there is two function but how ı will use them really dont know

**Comment by mehmetgoksu** [comment]
ı searched a bit and cant find nything cause if ı should use dll and lib ı need more.. ı have to use header but your project dont has header to use for call dll

**Comment by mehmetgoksu** [comment]
?
