### ISSUE TITLE
RDP Wrapper dejó de Funcionar W10 21H1 (19043.1165)

### ISSUE THREAD

**Issue by Mhalvarez75** [stascorp/rdpwrap#1543]
Hola a todos, escribo por este medio porque desde hace 3 días ha dejado de funcionar el RDP Wrapper en mi sistema, y no me permite conexiones de escritorio remoto simultáneas.

![Rdp Wrapper](https://user-images.githubusercontent.com/86836143/135134176-564ce55c-f0f0-412b-933e-559c4f34a15b.JPG)

![Version Windows](https://user-images.githubusercontent.com/86836143/135134213-d88ce16a-8946-412e-99db-bccdbf5c18dc.JPG)

Agradezco mucho si alguien pudiera ayudarme a resolver esta situación. Muchas Gracias.-

**Comment by gtd0949** [comment]
let's me

**Comment by zekecarter** [comment]
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7268210/rdpwrap.zip)
try this one, remember to stop the remote desktop service before replacing it otherwise you will cause a failure at login time
![Sin título](https://user-images.githubusercontent.com/83554130/135643867-d183907f-b717-4a0e-9508-34591cd68a06.png)

**Comment by Mhalvarez75** [comment]
@zekecarter Muchas Gracias por tu colaboración. Quedó funcionando Perfecto. 
@zekecarter Thank you very much for your cooperation. It worked Perfect.

**Comment by Mhalvarez75** [comment]
@zekecarter Muchas Gracias por tu colaboración. Quedó funcionando Perfecto.
@zekecarter Thank you very much for your cooperation. It worked Perfect.

**Comment by ojeda8417** [comment]
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7268210/rdpwrap.zip) pruebe este, recuerde detener el servicio de escritorio remoto antes de reemplazarlo, de lo contrario, provocará una falla al momento de iniciar sesión ![Sin título](https://user-images.githubusercontent.com/83554130/135643867-d183907f-b717-4a0e-9508-34591cd68a06.png)

hola amigo detuve el servicio escritorio remoto arroja no me deja inciiar sesion
