### ISSUE TITLE
Need 1909 ini file or just help

### ISSUE THREAD

**Issue by daddyDinosaur** [stascorp/rdpwrap#1546]
Does anyone have the INI file for windows 10, version 1909 os build 18363.1801, I cant seem to find it anywhere, (on winconf it says ver 10.0.17763.1, I cant seem to find it anywhere and iv been looking everywhere. Thanks in advance! (Btw I have it saying [fully supported] but not listening)

**Comment by sebaxakerhtc** [comment]
> Does anyone have the INI file for windows 10, version 1909 os build 18363.1801, I cant seem to find it anywhere, (on winconf it says ver 10.0.17763.1, I cant seem to find it anywhere and iv been looking everywhere. Thanks in advance! (Btw I have it saying [fully supported] but not listening)

Is your Windows x86 or x64? Still you have this issue?
