### ISSUE TITLE
All items is green but the screen is dim.

### ISSUE THREAD

**Issue by Raytow** [stascorp/rdpwrap#1548]
The RDPConf.exe shows  Listening and Fully supported.
And RDPCheck.exe could shows linked, but the screen is dim.
The login box is disappeared.
10.0.17763.1697

![image](https://user-images.githubusercontent.com/45890913/136032407-718b7bf2-d24a-4f75-9f91-9763b2e8b6c7.png)
![image](https://user-images.githubusercontent.com/45890913/136032454-aeae7a21-8907-43bf-b3cd-a3ea1f51c3f2.png)

**Comment by B-CCCPcekca-HET** [comment]
In this case, restarting the TERMSERVICE slave on the remote host helped me

**Comment by sebaxakerhtc** [comment]
> The RDPConf.exe shows Listening and Fully supported. And RDPCheck.exe could shows linked, but the screen is dim. The login box is disappeared. 10.0.17763.1697
> 
> ![image](https://user-images.githubusercontent.com/45890913/136032407-718b7bf2-d24a-4f75-9f91-9763b2e8b6c7.png) ![image](https://user-images.githubusercontent.com/45890913/136032454-aeae7a21-8907-43bf-b3cd-a3ea1f51c3f2.png)

Do you still have this issue?

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
