### ISSUE TITLE
Multiple session with the same Microsoft Account in Windows 11 Enterprise

### ISSUE THREAD

**Issue by gkl1368** [stascorp/rdpwrap#1550]
In windows 11 Enterprise, I can't login by different device which use the same microsoft account at the same time. Pls help.

**Comment by sebaxakerhtc** [comment]
> I can't login by differe

I'm not shure, should it work by this cneanrio at all.
Does it work with Local user?

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
