### ISSUE TITLE
RDP no longer works after restarting the RDS service.

### ISSUE THREAD

**Issue by DESKTOPGOOOSE** [stascorp/rdpwrap#1551]
I'm making a public Windows 11 (22000.132) RDP, I had to restart Remote Desktop Services, When I restarted, I attempted to reconnect and it didn't work.

Am I screwed?
Port: 3398

**Comment by DESKTOPGOOOSE** [comment]
![image](https://user-images.githubusercontent.com/77574002/136680073-fc4eb775-6f25-4fe5-91ee-2527a0ef7ac9.png)

**Comment by DESKTOPGOOOSE** [comment]
![image](https://user-images.githubusercontent.com/77574002/136680100-84a93942-8f05-4e16-93a3-4b90d46a9ead.png)
It works on the actual machine, though.

**Comment by sebaxakerhtc** [comment]
> I'm making a public Windows 11 (22000.132) RDP, I had to restart Remote Desktop Services, When I restarted, I attempted to reconnect and it didn't work.
> 
> Am I screwed? Port: 3398

Do you still have any problem? If no – please, close the issue
