### ISSUE TITLE
not supported with the newest win11 pro - 10.0.22000.258

### ISSUE THREAD

**Issue by marciifee** [stascorp/rdpwrap#1554]
i am looking for a new rdpwrap.ini file for the version:
10.0.22000.258 aka showed as 10.0.22000.1 but it is the .258

looking forward for a premade ini or a tip how to make itself.

**Comment by BlackRule** [comment]
Does it work? Where u downloaded it from?

**Comment by BlackRule** [comment]
@marciifee
