### ISSUE TITLE
Win 10 ver 19042.1288 not supported

### ISSUE THREAD

**Issue by specky-geek** [stascorp/rdpwrap#1557]
Edition	Windows 10 Pro
Version	20H2
Installed on	‎9/‎3/‎2021
OS build	19042.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by specky-geek** [comment]
The following worked for me. Give it a try if you face this  issue.

1. Replacing some files 
C:\Windows\System32\termsrv.dll with this file
[termsrv_patched_windows_10_20h2.zip](https://github.com/stascorp/rdpwrap/files/7347084/termsrv_patched_windows_10_20h2.zip)

2. Changes in Services.
![image](https://user-images.githubusercontent.com/74464210/137339841-a7cd0b40-1290-4042-9cca-8e9784021f37.png)

**Comment by SquawkWoof** [comment]
@specky-geek: this did not work for me.  Service just fails to start.  Windows also seems to delete the file after a reboot (automatic integrity check?)

Edit: worked after updating the INI again.
