### ISSUE TITLE
10.0.17763.2213 not supported

### ISSUE THREAD

**Issue by tarin3** [stascorp/rdpwrap#1558]
Termserv version not supported. Was updated just recently. How do you find
 the necessary values in the ini file for a specific termserv version?

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/7348972/termsrv.zip)

**Comment by micsutka** [comment]
please use the search box before posting new issues
https://github.com/stascorp/rdpwrap/issues/1534

**Comment by Cosmits** [comment]
[10.0.17763.2213-SLInit]
; no x86 section

bServerSku.x64        =F3AC8
bRemoteConnAllowed.x64=F3AD8
bFUSEnabled.x64       =F3AE4
bAppServerAllowed.x64 =F3AD4
bMultimonAllowed.x64  =F3ADC
lMaxUserSessions.x64  =F3ACC
ulMaxDebugSessions.x64=F3AE0
bInitialized.x64      =F3AC4

[10.0.17763.2213]
; no x86 section

LocalOnlyPatch.x64    =1
LocalOnlyOffset.x64   =7E281
LocalOnlyCode.x64     =jmpshort
SingleUserPatch.x64   =1
SingleUserOffset.x64  =13619
SingleUserCode.x64    =Zero
DefPolicyPatch.x64    =1
DefPolicyOffset.x64   =181D5
DefPolicyCode.x64     =CDefPolicy_Query_eax_rcx
SLInitHook.x64        =1
SLInitOffset.x64      =2148C
SLInitFunc.x64        =New_CSLQuery_Initialize

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1534
