### ISSUE TITLE
10.0.14393.4704 not working

### ISSUE THREAD

**Issue by Prakhov** [stascorp/rdpwrap#1560]
![image](https://user-images.githubusercontent.com/49492863/137791633-b359286b-3e53-4772-984e-55dc8e71d10b.png)

Do you have any medicine for this?

**Comment by aclar** [comment]
https://github.com/stascorp/rdpwrap/issues/1555

**Comment by Prakhov** [comment]
Thanks a lot!

**Comment by Th0rules** [comment]
Great Works !! tnx man.

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1555
