### ISSUE TITLE
这怎么装不好？

### ISSUE THREAD

**Issue by minhongqi** [stascorp/rdpwrap#1561]
![image](https://user-images.githubusercontent.com/71131967/137836145-af7ebfa8-3b55-4153-8339-a786b606fdfe.png)
![image](https://user-images.githubusercontent.com/71131967/137836205-528756ee-410f-44b8-ae59-ba194f7586d1.png)
![image](https://user-images.githubusercontent.com/71131967/137836237-8717ca9b-074e-4261-a516-45ddf675de5d.png)

**Comment by lalinking** [comment]
你只差一步了。
rdpwrap.ini 改一下，内容用下面的覆盖：
https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini
用 notepad++ 之类能以管理员权限运行的编辑器去改，不然会提示权限问题；另外改之前停掉 remote service 那个服务，不然会提示文件被占用。

**Comment by minhongqi** [comment]
> 你只差一步了。 rdpwrap.ini 改一下，内容用下面的覆盖： https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini 用 notepad++ 之类能以管理员权限运行的编辑器去改，不然会提示权限问题；另外改之前停掉 remote service 那个服务，不然会提示文件被占用。

![image](https://user-images.githubusercontent.com/71131967/137842793-54598ca4-fe1e-4324-b8e8-f6010dfdf1bf.png)
谢谢你的回复，但是，现在成这样了是怎么回事？

**Comment by minhongqi** [comment]
> 你只差一步了。 rdpwrap.ini 改一下，内容用下面的覆盖： https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini 用 notepad++ 之类能以管理员权限运行的编辑器去改，不然会提示权限问题；另外改之前停掉 remote service 那个服务，不然会提示文件被占用。

重新操作了一下，弄好啦！谢谢！

**Comment by 17633974050** [comment]
> > 你只差一步了。[https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini.ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini)
> 
> 重新操作了一下，弄好啦！谢谢！

不知道为什么，我打不开这个链接

**Comment by minhongqi** [comment]
> > > 你只差一步了。[https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini.ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini)
> > 
> > 
> > 重新操作了一下，弄好啦！谢谢！
> 
> 不知道为什么，我打不开这个链接

能打开的，把打开后看到的的代码全复制到rdpwrap.ini，全替换之前的内容就行，如果还不行，就在结尾加上10.0.19041.1202的配置脚本，这在10.0.19041.1202对应的issue下边有具体的代码

**Comment by lalinking** [comment]
> > > 你只差一步了。[https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini.ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini)
> > 
> > 
> > 重新操作了一下，弄好啦！谢谢！
> 
> 不知道为什么，我打不开这个链接

应该是你本地网络受dns污染了，这经常出现的问题。有梯子就爬梯子吧。

**Comment by 17633974050** [comment]
谢大佬，爬梯子解决打不开的问题了，现在三项全绿啦。然后就又出现了新问题，我在手机端输入查到的ipv4地址一直显示查询不到，试着用内网穿透也不行，一直显示无法发现pc端
![E31FBE3DAA50B9102C4612D80BA88C58](https://user-images.githubusercontent.com/92776435/138031041-b55292dc-14d6-4944-9d0b-ccc57fe2a1a4.jpg)

**Comment by 17633974050** [comment]
> 谢大佬，爬梯子解决打不开的问题了，现在三项全绿啦。然后就又出现了新问题，我在手机端输入查到的ipv4地址一直显示查询不到，试着用内网穿透也不行，一直显示无法发现pc端 ![E31FBE3DAA50B9102C4612D80BA88C58](https://user-images.githubusercontent.com/92776435/138031041-b55292dc-14d6-4944-9d0b-ccc57fe2a1a4.jpg)

不知道是不是因为我电脑连的是校园网的问题

**Comment by lalinking** [comment]
> > 谢大佬，爬梯子解决打不开的问题了，现在三项全绿啦。然后就又出现了新问题，我在手机端输入查到的ipv4地址一直显示查询不到，试着用内网穿透也不行，一直显示无法发现pc端 ![E31FBE3DAA50B9102C4612D80BA88C58](https://user-images.githubusercontent.com/92776435/138031041-b55292dc-14d6-4944-9d0b-ccc57fe2a1a4.jpg)
> 
> 不知道是不是因为我电脑连的是校园网的问题

校园网很复杂我也不会弄，我是家宽带公网ip的试过了可以正常连接。
你试试本机那个check程序能不能连上，如果check能连成功那就不是rdpwrap的问题了。

**Comment by 17633974050** [comment]
emmm这个check能打开，但是输入密码以后显示拒绝访问
![image](https://user-images.githubusercontent.com/92776435/138124213-96b3d88d-f726-4bbd-99ae-7448e7c82e34.png)



> > > 谢大佬，爬梯子解决打不开的问题了，现在三项全绿啦。然后就又出现了新问题，我在手机端输入查到的ipv4地址一直显示查询不到，试着用内网穿透也不行，一直显示无法发现pc端 ![E31FBE3DAA50B9102C4612D80BA88C58](https://user-images.githubusercontent.com/92776435/138031041-b55292dc-14d6-4944-9d0b-ccc57fe2a1a4.jpg)
> > 
> > 
> > 不知道是不是因为我电脑连的是校园网的问题
> 
> 校园网很复杂我也不会弄，我是家宽带公网ip的试过了可以正常连接。 你试试本机那个check程序能不能连上，如果check能连成功那就不是rdpwrap的问题了。

**Comment by sebaxakerhtc** [comment]
duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Comment by prymetheus** [comment]
![image](https://user-images.githubusercontent.com/36073146/142555971-f3ac0e85-f4e7-4472-b7d9-09cfaf489294.png)
how to resolve it,I have open 3389 port

**Comment by sebaxakerhtc** [comment]
> how to resolve it,

Listener state is a terminal service.
It not started. Restart it or restart your PC

**Comment by hidakafinzelz** [comment]
> emmm这个check能打开，但是输入密码以后显示拒绝访问 ![image](https://user-images.githubusercontent.com/92776435/138124213-96b3d88d-f726-4bbd-99ae-7448e7c82e34.png)
> 
> > > > 谢大佬，爬梯子解决打不开的问题了，现在三项全绿啦。然后就又出现了新问题，我在手机端输入查到的ipv4地址一直显示查询不到，试着用内网穿透也不行，一直显示无法发现pc端 ![E31FBE3DAA50B9102C4612D80BA88C58](https://user-images.githubusercontent.com/92776435/138031041-b55292dc-14d6-4944-9d0b-ccc57fe2a1a4.jpg)
> > > 
> > > 
> > > 不知道是不是因为我电脑连的是校园网的问题
> > 
> > 
> > 校园网很复杂我也不会弄，我是家宽带公网ip的试过了可以正常连接。 你试试本机那个check程序能不能连上，如果check能连成功那就不是rdpwrap的问题了。

我也遇到了，请问如何解决的?
