### ISSUE TITLE
10.0.17763.1697 not supported

### ISSUE THREAD

**Issue by yybinpitaya** [stascorp/rdpwrap#1562]
10.0.17763.1697 not supported

**Comment by sebaxakerhtc** [comment]
> 10.0.17763.1697 not supported

Is your version of Windows x86 or x64?

**Comment by auliarahmed** [comment]
omg, same version here, not supported, any solution?

**Comment by auliarahmed** [comment]
> > 10.0.17763.1697 not supported
> 
> Is your version of Windows x86 or x64?

64 bit, any solution sir?

**Comment by sebaxakerhtc** [comment]
> > > 10.0.17763.1697 not supported
> > 
> > 
> > Is your version of Windows x86 or x64?
> 
> 64 bit, any solution sir?

https://github.com/sebaxakerhtc/rdpwrap.ini/commit/2738288a7abd7f62026b085442f2f7920fcbdd25

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1276
