### ISSUE TITLE
Configuration for INI file for vin ver 22000.194

### ISSUE THREAD

**Issue by jcalem14** [stascorp/rdpwrap#1564]
Not working on 21H2 Windows 11. Help need it please.
![Screenshot 2021-10-20 115138](https://user-images.githubusercontent.com/92876362/138128350-1ce03b9e-bb00-4f6a-9845-9743c891690b.jpg)
![Screenshot 2021-10-20 115043](https://user-images.githubusercontent.com/92876362/138128356-5b0a0cc1-ee3d-4cc3-8a1e-659a2652f1fb.jpg)

**Comment by sebaxakerhtc** [comment]
[10.0.22000.1]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=98C11
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=088C2
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1BB75
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=26AD0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22000.1-SLInit]
bInitialized.x64      =11FECC
bServerSku.x64        =11FED0
lMaxUserSessions.x64  =11FED4
bAppServerAllowed.x64 =11FEDC
bRemoteConnAllowed.x64=11FEE4
bMultimonAllowed.x64  =11FEE8
ulMaxDebugSessions.x64=11FEF0
bFUSEnabled.x64       =11FEF4

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1455
