### ISSUE TITLE
10.0.17763.2268 not supported

### ISSUE THREAD

**Issue by zzelalex** [stascorp/rdpwrap#1565]
The question. And the answer. Enjoy.

`[10.0.17763.2268]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=7E291
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=13879
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18435
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=2179C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.17763.2268-SLInit]
bInitialized.x64      =F3AC4
bServerSku.x64        =F3AC8
lMaxUserSessions.x64  =F3ACC
bAppServerAllowed.x64 =F3AD4
bRemoteConnAllowed.x64=F3AD8
bMultimonAllowed.x64  =F3ADC
ulMaxDebugSessions.x64=F3AE0
bFUSEnabled.x64       =F3AE4
`

**Comment by ElenaXb9** [comment]
Doesn't work, can anyone help?

**Comment by Sametor** [comment]
Worked like a charm! Thank you!

**Comment by ElenaXb9** [comment]
Still not working for me.
![screenshot_1](https://user-images.githubusercontent.com/69768194/138609129-7fe61892-2d31-4ddf-bccd-ed6d62c8bc1e.jpg)
As solved at this moment: replace termsrv.dll ver.10.0.17763.2268 at ver.10.0.17763.2213
![screenshot_2](https://user-images.githubusercontent.com/69768194/138609194-43a77043-b7c5-43cc-9115-eaa369d943ed.jpg)
[termsrv.dll_10.0.17763.2268.zip](https://github.com/stascorp/rdpwrap/files/7406098/termsrv.dll_10.0.17763.2268.zip)
[termsrv.dll_10.0.17763.2213.zip](https://github.com/stascorp/rdpwrap/files/7406099/termsrv.dll_10.0.17763.2213.zip)

Hope it helps someone

**Comment by jmassisi** [comment]
[10.0.17763.2268] is working fine on Windows server 2019 essentials.
Thanks!

**Comment by sebaxakerhtc** [comment]
> Still not working for me. ![screenshot_1](https://user-images.githubusercontent.com/69768194/138609129-7fe61892-2d31-4ddf-bccd-ed6d62c8bc1e.jpg) As solved at this moment: replace termsrv.dll ver.10.0.17763.2268 at ver.10.0.17763.2213 ![screenshot_2](https://user-images.githubusercontent.com/69768194/138609194-43a77043-b7c5-43cc-9115-eaa369d943ed.jpg) [termsrv.dll_10.0.17763.2268.zip](https://github.com/stascorp/rdpwrap/files/7406098/termsrv.dll_10.0.17763.2268.zip) [termsrv.dll_10.0.17763.2213.zip](https://github.com/stascorp/rdpwrap/files/7406099/termsrv.dll_10.0.17763.2213.zip)
> 
> Hope it helps someone

The BUG was fixed
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/82a1a5e41bf3ac7b754aa55866cbfa2032030a63
