### ISSUE TITLE
10.0.19041.1288 ini?

### ISSUE THREAD

**Issue by N-Storm** [stascorp/rdpwrap#1567]
Anyone got ini section for 10.0.19041.1288 ?

**Comment by kostyanp95** [comment]
> Anyone got ini section for 10.0.19041.1288 ?

Here is the working version. Close Issue please.
https://github.com/stascorp/rdpwrap/issues/1559#issuecomment-945560176

**Comment by N-Storm** [comment]
Fixed in contributed update.
