### ISSUE TITLE
ini for ver 10.0.19041.1021

### ISSUE THREAD

**Issue by imanhernantest** [stascorp/rdpwrap#1568]
Hi I'm using Ghost Spectre Pro 21h1 version of windows. I would like to ask if the RDP wrapper of this one will work?

![image](https://user-images.githubusercontent.com/93025165/138543464-3bb4e416-0b7b-4c77-b207-db78486e78a4.png)

**Comment by sebaxakerhtc** [comment]
> I would like to ask if the RDP wrapper of this one will work?

Hi.
Is your Windows x86 or x64? Please attach your zip compressed termsrv.dll, so we can help you.
Thank you!

**Comment by leechor** [comment]
> > I would like to ask if the RDP wrapper of this one will work?
> 
> Hi. Is your Windows x86 or x64? Please attach your zip compressed termsrv.dll, so we can help you. Thank you!

the same problem.
[termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/7441221/termsrv.dll.zip)

**Comment by sebaxakerhtc** [comment]
> the same problem.

Answer the question about x64 or x86 first

**Comment by leechor** [comment]
> > the same problem.
> 
> Answer the question about x64 or x86 first

x64

**Comment by sebaxakerhtc** [comment]
> the same problem.
> [termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/7441221/termsrv.dll.zip)

Your termsrv.dll version is 19041.1202
I have values for this version in my ini
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/7274f1a40f3293d21ed3383d1740e8b428fcae39

**Comment by leechor** [comment]
thank you, it's worked.

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer

**Comment by wlmh110** [comment]
Hi, we have the same problem, could you help us?
X64 win10 system, version is 10.0.19041.1021
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/7819395/termsrv.zip)

**Comment by wlmh110** [comment]
@sebaxakerhtc

**Comment by sebaxakerhtc** [comment]
> Hi, we have the same problem, could you help us? X64 win10 system, version is 10.0.19041.1021 [termsrv.zip](https://github.com/stascorp/rdpwrap/files/7819395/termsrv.zip)

I will try it after one hour

**Comment by sebaxakerhtc** [comment]
> Hi, we have the same problem, could you help us? X64 win10 system, version is 10.0.19041.1021 [termsrv.zip](https://github.com/stascorp/rdpwrap/files/7819395/termsrv.zip)

Look here https://github.com/stascorp/rdpwrap/issues/1568#issuecomment-954671416

**Comment by sebaxakerhtc** [comment]
wrong duplicate mark

**Comment by sashaqwert** [comment]
> Closed because of missing answer

Answer in https://github.com/stascorp/rdpwrap/issues/2173

**Comment by sashaqwert** [comment]
> Duplicate of #1509

Wrong duplicate mark...
