### ISSUE TITLE
Add support for version 10.0.10586.589

### ISSUE THREAD

**Issue by SIMBaIrk** [stascorp/rdpwrap#157]
After update win 10, in RDConf Listening [not supported]
version termsrv.dll 10.0.10586.589
can't upload .zip
[termsrv.txt](https://github.com/stascorp/rdpwrap/files/471539/termsrv.txt)

**Comment by ahmadod** [comment]
I have the same issue

**Comment by mastersatboy** [comment]
Me also,any solution?Thnx!

**Comment by ahmadod** [comment]
i've tried too many things and my problem has been solved , may be removing some security update has fixed the issue

**Comment by mastersatboy** [comment]
Ahmadod you said that you removed some security updates and has resolved the problem?

**Comment by ahmadod** [comment]
Yeah , and somebody sent me a patch which i don't know patched or not , i have done both and it's working now

**Comment by mastersatboy** [comment]
Ahmadod please can you send me to email the patch and what exactly hawe you done which security update hawe you deleteted.....Please!!

**Comment by ahmadod** [comment]
I've deleted all security updates that has been installed today , this file is suspected to have virus by gmail , send me your email address

**Comment by ahmadod** [comment]
Sent you the email mastersatboy

**Comment by mastersatboy** [comment]
My email its: mastersatboy@yahoo.it   Thnx my friend!!

**Comment by ceeronne** [comment]
Could You please send me that patch to

**Comment by binarymaster** [comment]
Stop flaming and wait until I update the INI file.

**Comment by rebroad** [comment]
@binarymaster you deserve a tip/donation for your patience and perseverance. Do you have a donation address (e.g. bitcoin)?

**Comment by binarymaster** [comment]
@rebroad here's my bitcoin address: `1Fzra1BDxAze1guWcdwLcGUVpasovwsdeS`
