### ISSUE TITLE
Ini for ver 19043.1288

### ISSUE THREAD

**Issue by maniootek** [stascorp/rdpwrap#1570]
Can anyone provide me ini file for ver 19043.1288?

**Comment by sashaqwert** [comment]
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini (Only x64)

**Comment by nattlip** [comment]
https://github.com/stascorp/rdpwrap/issues/1556  ?

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Comment by RodolfoBigues** [comment]
Al the items are green so i show you in the pic
![Captura de pantalla 2021-11-03 003044](https://user-images.githubusercontent.com/92989780/140006577-308b9a5f-e653-4b22-968e-3bce03363281.png)
but whe I use RDPCheck.exe I can´t login and apear this isue 
![Captura de pantalla 2021-11-03 003126](https://user-images.githubusercontent.com/92989780/140006730-876b4c01-3234-4e4c-8e8f-11364a586b05.png)
How can I fix it
