### ISSUE TITLE
limit is 30 connections

### ISSUE THREAD

**Issue by alex173ul** [stascorp/rdpwrap#1576]
Windows 10. The limit is 30 connections. Why? how to fix?

**Comment by sashaqwert** [comment]
~~Please, taskmgr-->Users or qwinsta screenshot. Usernames can be glossed over.~~

I was aware of the 15 session limit before.
More in https://github.com/stascorp/rdpwrap/issues/192

**Comment by saurav-biswas** [comment]
> Windows 10. The limit is 30 connections. Why? how to fix?

Increase the RAM and the processor. I tested it on 60 users and its working.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/192

**Comment by Sadhiq42** [comment]
how can i restrict the number of connections to two?

**Comment by sebaxakerhtc** [comment]
> how can i restrict the number of connections to two?

Try to play with group policy restriction (number of connections)

**Comment by Sadhiq42** [comment]
Hi 
We edited the group policy settings set the RDP connection limit to 3 but still, we can connect more than 3 devices.
Attaching screenshots for your reference.
![rdp eeror 2](https://user-images.githubusercontent.com/97108710/148176358-9cbf539a-1ff7-4d89-bac6-b4d3c0a170ea.png)
![rdp error 1](https://user-images.githubusercontent.com/97108710/148176362-819e1b10-0247-4e35-9417-cc9144efc0e1.png)

**Comment by sebaxakerhtc** [comment]
> We edited the group policy settings set the RDP connection limit to 3 but still, we can connect more than 3 devices.

Did you restart your PC to apply new polices?

**Comment by Sadhiq42** [comment]
We restarted the PC and still there is the same issue.

**Comment by s4bre1** [comment]
> Windows 10. O limite é de 30 conexões. Porque? como consertar?

did you find out how to solve this?
