### ISSUE TITLE
Windows 11 Version 10.0.22000.1

### ISSUE THREAD

**Issue by HBastet** [stascorp/rdpwrap#1578]
Hello, I'm testing windows 11 version 21h2 build 22000.282.
In RDP Wrapper Configuration, it is version 10.0.22000.1
![image](https://user-images.githubusercontent.com/21291769/139585929-e6bf6fe5-328d-40a0-9d57-864521547ba0.png)
I don't know how to modify rdpwrap.ini for these version.
Thanks for helping

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1455

**Comment by HBastet** [comment]
Ok thanks Excuse me :)
