### ISSUE TITLE
Issues with multisession 

### ISSUE THREAD

**Issue by Daniel2git** [stascorp/rdpwrap#1579]
As soon as a user has opened several sessions under the same account, different programs can no longer be used.
For example:
- Visual Studio Code always starts in the first session in which it was started, even if it should be started later in a different session.
- Outlook always shows the following error: 

![grafik](https://user-images.githubusercontent.com/93496594/139605336-176fc2e9-3aa4-4f4f-86d1-92efd381d3c1.png)

![grafik](https://user-images.githubusercontent.com/93496594/139605392-6af7eaf3-7811-449f-a156-2a35a6fceea1.png)

Thank you for any assistance!

**Comment by sebaxakerhtc** [comment]
> As soon as a user has opened several sessions under the same account, different programs can no longer be used

It's a normal behavior for most of software. Not an RDPWrapper issue, and not a multisession issue.
