### ISSUE TITLE
10.0.19041.1202 is not supported. My kernel version is 10.0.19042.1288

### ISSUE THREAD

**Issue by BDfdsb123c** [stascorp/rdpwrap#1580]
10.0.19041.1202 is not supported. My kernel version is 10.0.19042.1288. I can only find the 10.0.19043.1288 kernel version on the Internet. I can't find 10.0.19042.1288. The system is Windows Home Edition.

**Comment by sebaxakerhtc** [comment]
Same as https://github.com/stascorp/rdpwrap/issues/1509

**Comment by BDfdsb123c** [comment]
> 同#1509

There is still no way to use this

**Comment by sebaxakerhtc** [comment]
> There is still no way to use this

It works perfect.
Can you share more info?
Is your version x86 or x64?
RDPWrapper screenshot?

**Comment by BDfdsb123c** [comment]
> > 仍然没有办法使用这个
> 
> 它完美无缺。 你能分享更多信息吗？ 你的版本是 x86 还是 x64？ RDPWrapper 截图？

The system version is x64

OS 名称:          Microsoft Windows 10 家庭中文版
OS 版本:          10.0.19042 暂缺 Build 19042
[termsrv64.zip](https://github.com/stascorp/rdpwrap/files/7454091/termsrv64.zip)

**Comment by BDfdsb123c** [comment]
> > There is still no way to use this
> 
> It works perfect. Can you share more info? Is your version x86 or x64? RDPWrapper screenshot?

I just tried it again and it succeeded. Thank you very much. It’s because I added an extra -o parameter when I installed it.

**Comment by sebaxakerhtc** [comment]
> Thank you very much

You're welcome 🙂
