### ISSUE TITLE
All stuff in green but sill have a problem in Windows 10 Pro 21H1 comp 19043.1288

### ISSUE THREAD

**Issue by RodolfoBigues** [stascorp/rdpwrap#1583]
I used a lot of time RDPWarp, and every time that windows 10 Pro get a new version I have no problem, but now it´s a mind broker
I give  you a Pic that you can see all stuf in a nice green as its seems to work...
![Captura de pantalla 2021-11-03 003044](https://user-images.githubusercontent.com/92989780/140007663-58d784f7-f688-432e-8748-c9c05848b6b6.png)
But when I use the tool to check if I can used, I can put my password, but ther apears this screen. 
![Captura de pantalla 2021-11-03 003126](https://user-images.githubusercontent.com/92989780/140007783-e008055b-495a-44a6-b633-67fa83585049.png)
I do not want to change any dll cos the last time I do it my customer want to kill me cos this PC act like a server. I don´t wanna loose my job. So how coud I fix it whitout changing any .dll ?

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/192

**Comment by RodolfoBigues** [comment]
> Applicable to #192

this is no the isue and I don´t find it cos #192 is form 2017 and my problem is form 2021 whith this Windows version 19043.1288

**Comment by sebaxakerhtc** [comment]
>  #192 is form 2017 and my problem is form 2021

You have a limit of connections. The version is doesn't matter. Read carefuly

**Comment by RodolfoBigues** [comment]
> > #192 is form 2017 and my problem is form 2021
> 
> You have a limit of connections. The version is doesn't matter. Read carefuly

You are rigth thank you now work finaly I used de gpedit put user 999999 and work somthly. You are my hero
