### ISSUE TITLE
win 11 22483 not supported

### ISSUE THREAD

**Issue by BEOILYEN** [stascorp/rdpwrap#1584]
Hello! Tryed autoupdate and auto-generated ini. Not supported state at any ini and service does not starts at auto-generated

**Comment by binarymaster** [comment]
Please attach RDPConf screenshot to confirm your build number.

**Comment by BEOILYEN** [comment]
![rdp1](https://user-images.githubusercontent.com/88021718/140435386-a8bba8f3-b7e6-4fd6-bb60-fc5c7699d91e.png)
this is with generated ini

**Comment by BEOILYEN** [comment]
![rdp2](https://user-images.githubusercontent.com/88021718/140435543-82e26a6a-e76c-44dc-88d2-24649fddb215.png)
this is with default/autoupdate

**Comment by BEOILYEN** [comment]
[trm.zip](https://github.com/stascorp/rdpwrap/files/7479609/trm.zip)
my termsrv.dll

**Comment by BEOILYEN** [comment]
Problem Solved! Reason: while trying different versions, I didn't restart RDP Wrapper Configuration. After running autoupdate one more time and restarted app, it is showing full support! Thanks!

**Comment by binarymaster** [comment]
Ok, so basically duplicate of #1572.
