### ISSUE TITLE
10.0.19041.1202 no listening but fully supported

### ISSUE THREAD

**Issue by 2414466154** [stascorp/rdpwrap#1586]
![image](https://user-images.githubusercontent.com/38528977/140493701-522ae6a8-4fc7-4315-a67c-f035ecd8d4ef.png)

my system is win10  * 64

**Comment by 2414466154** [comment]
You have a solution

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1509
