### ISSUE TITLE
everything is supported but my pc is not listening. 

### ISSUE THREAD

**Issue by LookingforRDPhelp** [stascorp/rdpwrap#1589]
i cant open up rdpwlnst either. my version build is 19043.1288 if that has to do with it.

**Comment by LookingforRDPhelp** [comment]
also my antivirus has quarantined rdpwnst before so that might have something to do with that but i still wouldnt know how to fix it

**Comment by LookingforRDPhelp** [comment]
now i restarted my computer everything is green but when i go into the actual rdp everything is blurry and is not possible to see. please help if you can

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/1509
