### ISSUE TITLE
Installer executable not found.

### ISSUE THREAD

**Issue by yioye** [stascorp/rdpwrap#1592]

**Comment by sashaqwert** [comment]
RDPWinst.exe exists in current directory?

**Comment by elfhunt** [comment]
I also had that problem when using Chrome for download. In the zip file, only the .bat files were in subfolder ".\bin".

In my case: 
1. Chrome's SafeBrowsing prevents download 
2. In download status bar below, push 'delete' button (my failed case didn't perform this step)
3. Change Chrome's SafeBrowsing setting
4. Download again
5. Success

Good luck!

**Comment by masterAllen** [comment]
I have this problem too. Downloading from Firefox and Chrome are both failed.

**Comment by masterAllen** [comment]
Well, it's all my fault. Download zip file from Releases instead of branch :)

**Comment by sebaxakerhtc** [comment]
> _No description provided._

Check your antivirus
