### ISSUE TITLE
Fully supported but not working

### ISSUE THREAD

**Issue by danigal1** [stascorp/rdpwrap#1593]
Hi,

I have installed the RDP Wrapper Library several times and I have had problem it's in a state 'not listening' or 'not supported', and I know how to solve those problems, but I have a different situation now.

Everything is OK in the RDPConf but the RDC not working:

![image](https://user-images.githubusercontent.com/93907926/140709503-e35a5867-3167-4bd5-b22d-d69464fdb26b.png)

![image](https://user-images.githubusercontent.com/93907926/140709637-d2c5831f-9c5b-44c8-b8ce-61e8c2d1ec1f.png)

The message is in Croatian, it seys that i already have one session.
RDPConf was in the state 'Not supported' but i resolved that with autoupdate.

I already enabled policy “Limit number of connections” in the Local Group Policy Editor (gpedit.msc):

![image](https://user-images.githubusercontent.com/93907926/140709856-2b5529f1-46e6-4139-9cd8-791088dec535.png)

**Do you have any other suggestions?**

Windows version:

![image](https://user-images.githubusercontent.com/93907926/140711424-b87f8d44-b114-48cb-a709-c7ff6f783fce.png)

**Comment by shasmine** [comment]
Reboot PC or Restart RDP

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/1420

**Comment by danigal1** [comment]
> Acceptable to #1420

It's working. Thanks.
