### ISSUE TITLE
Support for Windows 19042.1288?

### ISSUE THREAD

**Issue by Jaybish2407** [stascorp/rdpwrap#1594]
Is this windows version currently supported since had to update windows and can't seem to get it to work now.
![IMG-ff0699763a8e0dd0d8e74abaa3f0e1fe-V](https://user-images.githubusercontent.com/93984618/140920659-68437f9c-b78f-497a-87ed-365776fd2cf1.jpg)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1509
