### ISSUE TITLE
10.0.14393.4770 Not Support

### ISSUE THREAD

**Issue by lanparty** [stascorp/rdpwrap#1600]

**Comment by sebaxakerhtc** [comment]
Attach your termsrv.dll
Is your Windows x86 or x64?

**Comment by ibegemoth** [comment]
![изображение](https://user-images.githubusercontent.com/46316390/141194701-2fa4975a-bd4d-431d-91d7-23febf10cead.png)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/7515988/termsrv.zip)

**Comment by sebaxakerhtc** [comment]
> termsrv.zip

In progress...

**Comment by sebaxakerhtc** [comment]
> 
> 
> _No description provided._

Values added.
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/1d24e8cbbb9306c647681dc23e62a9cc8f0d2b1f#diff-9e5bbfbeae79b59b305dda13323ba2b041f30f4887a84120392c479e1f7bba33

**Comment by zekecarter** [comment]
> > _No description provided._
> 
> Values added. [sebaxakerhtc/rdpwrap.ini@1d24e8c#diff-9e5bbfbeae79b59b305dda13323ba2b041f30f4887a84120392c479e1f7bba33](https://github.com/sebaxakerhtc/rdpwrap.ini/commit/1d24e8cbbb9306c647681dc23e62a9cc8f0d2b1f#diff-9e5bbfbeae79b59b305dda13323ba2b041f30f4887a84120392c479e1f7bba33)

the update does not work for this version of windows 10, not listening.

I uninstalled and reinstalled rdpwrapper 1.6.2, disabled the remote desktop, pasted the rdpwrap.ini file, re-enabled the desktop and when testing it shows not listening. Please Help

![imagen1](https://user-images.githubusercontent.com/83554130/145103532-7d37f81c-e7f2-4488-a7a1-058880e626f0.png)
![imagen2](https://user-images.githubusercontent.com/83554130/145103534-204ad8b7-7f78-4ab6-a9fe-92da57f272d4.png)
![imagen3](https://user-images.githubusercontent.com/83554130/145103535-b365f954-c5da-4a30-80a7-d8fc1dce1d4a.png)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/7671508/termsrv.zip)

**Comment by sebaxakerhtc** [comment]
> does not work for this version of windows 10, not listening.

Restart termservice

**Comment by zekecarter** [comment]
> > does not work for this version of windows 10, not listening.
> 
> Restart termservice

I have restarted the service and it did not work.

![WhatsApp Image 2021-12-07 at 4 38 24 PM](https://user-images.githubusercontent.com/83554130/145110199-d25f5ce4-fb9f-4552-ad32-c93cc0aa6bb3.jpeg)

**Comment by sebaxakerhtc** [comment]
> I have restarted the service and it did not work.

Try to restart your PC, check antivirus

**Comment by sebaxakerhtc** [comment]
> did not work

I just double checked the offsets. Thanks to you, I found a BUG in the Single Session per User offset, but you don't use it, so for you it should work without problems.
![4770](https://user-images.githubusercontent.com/32651506/145182669-fa4538a5-8a95-4984-b647-e96694562010.png)

**Comment by zekecarter** [comment]
> > did not work
> 
> I just double checked the offsets. Thanks to you, I found a BUG in the Single Session per User offset, but you don't use it, so for you it should work without problems. ![4770](https://user-images.githubusercontent.com/32651506/145182669-fa4538a5-8a95-4984-b647-e96694562010.png)

Unfortunately after rebooting the problem continued. I have been following you for a long time because I use your updates for 3 computer models, 1 touch computer with windows 10 x64 ltsb 2016 enterprise (not working), a laptop windows 10 x64 home (working) and a desktop windows 10 x64 professional (working).

I only have problems with the touch computer that is the problem that does not listen and the service is disabled, that is why I have shown you the problem I have, I have sent you the termsvr.dll file of the computer with which I have problem I hope you can help 😊

**Comment by sebaxakerhtc** [comment]
> I have sent you the termsvr.dll file of the computer with which I have problem I hope you can help

As i said - i already double checked this version. There's no errors in values - the offsets are correct. You can check it with a new installation for test. I do that and send you a screenshot.
From now you can check your filesystem and recover it by using 
```
chkdsk
sfc /scannow
dism /Online /Cleanup-Image /RestoreHealth
```
etc
You can try [my modded version](https://github.com/sebaxakerhtc/rdpwrap/releases), but i think you should fix your OS, because it not work just for you and only on your PC.

**Comment by zekecarter** [comment]
> > I have sent you the termsvr.dll file of the computer with which I have problem I hope you can help
> 
> As i said - i already double checked this version. There's no errors in values - the offsets are correct. You can check it with a new installation for test. I do that and send you a screenshot. From now you can check your filesystem and recover it by using
> 
> ```
> chkdsk
> sfc /scannow
> dism /Online /Cleanup-Image /RestoreHealth
> ```
> 
> etc You can try [my modded version](https://github.com/sebaxakerhtc/rdpwrap/releases), but i think you should fix your OS, because it not work just for you and only on your PC.

effectively friend, after using your last version of the rdpwrapper mod 1.8.6.1, the equipment worked perfectly, with the version rdpwrapper 1.6.2 does not work is strange but I have solved with your new version, I will replace the other teams to work with your version I like more is simpler, apart that the update.bat file when I run it download the updates that you have integrated in the rdpwrap.ini, I am very grateful for the support you have given me.
