### ISSUE TITLE
Why does this happen

### ISSUE THREAD

**Issue by Srcphy** [stascorp/rdpwrap#1603]
![image](https://user-images.githubusercontent.com/70329655/141139359-2a028b50-3eae-47d7-b0b7-4b1b9d5f1917.png)

**Comment by ghost** [comment]
同问

**Comment by Srcphy** [comment]
> 同问

解决了，在登陆选项中关掉 通过Windows Hello登陆Microsoft账号就好了

**Comment by sebaxakerhtc** [comment]
Close as solved
