### ISSUE TITLE
Version 6.3.9600.20165 not supported

### ISSUE THREAD

**Issue by sbdman** [stascorp/rdpwrap#1604]
I'd kindly appreciate if someone could give the offsets for an ini file for Termsrv.dll version 6.3.9600.20165.
This is my HTPC running a digital cable card for TV viewing on Windows 8 Pro.
RDPWrapper is an absolute necesity - thanks in advance!

**Comment by sashaqwert** [comment]
Original DLL: https://t.me/rdpwrap/37768

**Comment by sbdman** [comment]
Sorry, just saw this is originally in #1597.
I'll wait for the new offsets in that post.

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1597
