### ISSUE TITLE
10.0.17763.1697 says fully supported but not able to connect

### ISSUE THREAD

**Issue by test2a** [stascorp/rdpwrap#1605]
i got the fully supported all green in the rdpconf. when i use rdpcheck, it says limited number of connections. so i checked gpedit where i set limit to 99999 but that also didnt help

a remote user is being asked that only one user can log in

**Comment by test2a** [comment]
i have used multiple rdpwrap.ini files and i do get fully supported but it is either problem with limit of connections or the ini file itself

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1562

**Comment by test2a** [comment]
@Sebaxakerhtc I used INI file from the same issue before starting a fresh one. Before applying the fix you gave, I was seeing another user is trying to login. After, it says limited connections

**Comment by test2a** [comment]
Should I share my termsrv DLL ? Would that be the issue?

**Comment by test2a** [comment]
@sebaxakerhtc
![Capture](https://user-images.githubusercontent.com/39449563/141239842-4746bc38-bd73-44e5-b762-eb85929c99b7.JPG)

this security update KB5007206 is the problem. it got installed yesterday and that is why the system was saying number of connections. 
i uninstalled it and the problem went away.

i say  this KB5007206 update needs to be adjusted in the DLl or in the ini file.
