### ISSUE TITLE
19042.1348 not working

### ISSUE THREAD

**Issue by redmayor09** [stascorp/rdpwrap#1606]
OS BUILD 19042.1348

**Comment by wendaoshenyang** [comment]
同有问题

**Comment by zjli-2019** [comment]
Same build, same issue.

Solved by updating to the latest version of rdpwrap.ini (https://github.com/sebaxakerhtc/rdpwrap.ini)

Now everything works like a charm.

**Comment by redmayor09** [comment]
zjli-2019 Thanks! Its now working
