### ISSUE TITLE
windows 10 21h1 19043.1348 Not Support

### ISSUE THREAD

**Issue by bcbatva01** [stascorp/rdpwrap#1608]
![rdp](https://user-images.githubusercontent.com/94092877/141228792-69041c45-5fa0-4d0e-be9e-8383a2adb027.jpg)
windows 10 21h1 19043.1348 Not Support

**Comment by zekecarter** [comment]
> ![rdp](https://user-images.githubusercontent.com/94092877/141228792-69041c45-5fa0-4d0e-be9e-8383a2adb027.jpg) windows 10 21h1 19043.1348 Not Support

solved!!! https://github.com/stascorp/rdpwrap/issues/1595#issuecomment-964643800

**Comment by vdovin1981** [comment]
Tried - not work for me

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595#issuecomment-964643800

**Comment by bcbatva01** [comment]
> Duplicate of [#1595 (comment)](https://github.com/stascorp/rdpwrap/issues/1595#issuecomment-964643800)

thk. it work!
![Screenshot_37](https://user-images.githubusercontent.com/94092877/141265210-a6d9c27c-1502-4a71-a0b0-e0d94047df73.jpg)

**Comment by bcbatva01** [comment]
> ![rdp](https://user-images.githubusercontent.com/94092877/141228792-69041c45-5fa0-4d0e-be9e-8383a2adb027.jpg) windows 10 21h1 19043.1348 Not Support

https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini  <<<<<< It Work !!!
