### ISSUE TITLE
10240.19119

### ISSUE THREAD

**Issue by allysell** [stascorp/rdpwrap#1609]

**Comment by sebaxakerhtc** [comment]
No description, not clear x86 or x64, no screenshot from rdpconf, no termsrv.dll attached
What are you waiting for?

**Comment by allysell** [comment]
Thx. It works 

![image](https://user-images.githubusercontent.com/45504155/141434227-87775dea-0ac6-4f32-b753-c1d39f7e3d32.png)

**Comment by cdw-brendenmorgenthaler** [comment]
Does anyone have the ini for 10.0.10240.19119 x64?

**Comment by bmorgenthaler** [comment]
Does anyone have the ini for 10.0.10240.19119 x64?
