### ISSUE TITLE
21H1,19043.1348

### ISSUE THREAD

**Issue by molamolaheng** [stascorp/rdpwrap#1613]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/7524667/termsrv.zip)

**Comment by mispl-2021** [comment]
after replace this term file but its not working

**Comment by mispl-2021** [comment]
if there any changes in .ini file

**Comment by ohforest** [comment]
> after replace this term file but its not working

me too

**Comment by LeeWiu** [comment]
Same here https://github.com/stascorp/rdpwrap/issues/1607#issuecomment-966192500

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595
