### ISSUE TITLE
Uninstaller not uninstalling the rdp wrapper

### ISSUE THREAD

**Issue by alirz1** [stascorp/rdpwrap#1615]
uninstal wont work on windows 10. Need to upgrade pc to windows 11 but this rdp wrapper is coming as unsupported and is blocking upgrade. How to uninstall?

**Comment by sebaxakerhtc** [comment]
> uninstal wont work on windows 10. Need to upgrade pc to windows 11 but this rdp wrapper is coming as unsupported and is blocking upgrade. How to uninstall?

You can do that with my modded version.

**Comment by sebaxakerhtc** [comment]
> 
> 
> uninstal wont work on windows 10. Need to upgrade pc to windows 11 but this rdp wrapper is coming as unsupported and is blocking upgrade. How to uninstall?

How did you install it?

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
