### ISSUE TITLE
Using latest INI and everything seems fine but can't use more than 1 session

### ISSUE THREAD

**Issue by amanjn16** [stascorp/rdpwrap#1624]
Hi 

Following is the screenshot of RDP Wrapper Application. 

![image](https://user-images.githubusercontent.com/41580079/142569400-91d72164-a946-489c-abba-3563a60cbba3.png)

Everything seems to be fine but when I run RDPCheck:

Using local account on host to connect to:
![image](https://user-images.githubusercontent.com/41580079/142569476-bb726bb3-d865-4f44-bd64-5419e545c310.png)

Getting the following error:

![image](https://user-images.githubusercontent.com/41580079/142569560-c94582b9-052d-497c-8b29-246d683983fa.png)

Please help.
Have tried setting GPO Policy too, but that isn't helping.

![image](https://user-images.githubusercontent.com/41580079/142569737-137945c6-5bb9-4c45-a83f-579b72c3573e.png)

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1595
