### ISSUE TITLE
Win10 X64 Enterprise 2016 LTSB 10.0.14393.4770 Not Listener, Service Stopped

### ISSUE THREAD

**Issue by zekecarter** [stascorp/rdpwrap#1625]
Win10 X64 Enterprise 2016 LTSB 10.0.14393.4770 Not Support
Fully Support but not listener and services stopped 
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/7573124/termsrv.zip)

I have tried this program but it does not work:

[10.0.14393.4770]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8CEE1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=23CC8
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=29825
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=CA40
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.14393.4770-SLInit]
bInitialized.x64      =E7470
bServerSku.x64        =E63D0
lMaxUserSessions.x64  =E63D4
bAppServerAllowed.x64 =E63D8
bRemoteConnAllowed.x64=E7474
bMultimonAllowed.x64  =E7478
ulMaxDebugSessions.x64=E747C
bFUSEnabled.x64       =E7480

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1600
