### ISSUE TITLE
rdpwrap enables multimonitor support for win 7 pro rdp host

### ISSUE THREAD

**Issue by clarity99** [stascorp/rdpwrap#163]
This is not an issue, but it seems undocumented feature. When you install RDPWrap on Win 7 pro machine, the machine can now be connected to with fullmultimon rdp support (use all monitors) without the /span flag that is usually needed. Might be helpful to add that somewhere in the readme? 

And thanks, this solved a huge pain point for me!

**Comment by phx-qorvo** [comment]
This has been a life saver, thank you!
