### ISSUE TITLE
RDP Blurry

### ISSUE THREAD

**Issue by C2usjb01** [stascorp/rdpwrap#1632]
Wrapper is functional, but my RDP is blurry. I've tried everything. Any Suggestions?

![RDP Blurry](https://user-images.githubusercontent.com/94012901/143075944-a142402f-9bf5-4e5d-a895-836a84619180.jpg)

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/1509

**Comment by C2usjb01** [comment]
Ive already appended 10.0.19041.1202. 
What else are you suggesting I do?

**Comment by vslee** [comment]
Turn on password use by removing the requirement to use Windows Hello https://superuser.com/a/1715548
