### ISSUE TITLE
 10.0.19042.1348 not supported 

### ISSUE THREAD

**Issue by ZhangJT0127** [stascorp/rdpwrap#1633]
help!  thank you

**Comment by elduke1098** [comment]
buen dia,

por el momento no hay actualización para es versión 

la solución que me funciono es desinstalar la actualización de Windows 10 en mi caso fue la actualización KB5006365

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Comment by davispuh** [comment]
FYI, this is not duplicate.
`[10.0.19041.1348]` is present but `10.0.19042.1348` is not :P notice the 41 vs 42

**Comment by sebaxakerhtc** [comment]
Really?
Look your termsrv.dll properties => version

чт, 25 нояб. 2021 г., 23:28 Dāvis ***@***.***>:

**Comment by davispuh** [comment]
Okay indeed LOL. I got confused that `winver` says `10.0.19042.1348` but actual `termsrv.dll` is `10.0.19041.1348` so all good :ok_hand:
