### ISSUE TITLE
Help Windows 10 Version 20H2 OS Build 19042.1348 listener state: Listening but [not supported]

### ISSUE THREAD

**Issue by bryandavis1970** [stascorp/rdpwrap#1634]

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Comment by sidiosidi** [comment]
Not duplicate, It's 19042.1348 not 19041.1348

**Comment by sebaxakerhtc** [comment]
Look at your termsrv.dll version!

вт, 30 нояб. 2021 г., 12:00 sidiosidi ***@***.***>:
