### ISSUE TITLE
Win10 Home Edition

### ISSUE THREAD

**Issue by zaxiaowang** [stascorp/rdpwrap#1636]
My win10 home edition can be used for remote desktop through RDP wrapper, but it can not be used remotely through remoteapptool. The main problem is that there is no response or prompt after entering the account and password. Please consult us. Is there any way?

**Comment by sashaqwert** [comment]
In your INI exists this line?

    TerminalServices-RemoteConnectionManager-AllowAppServerMode=1

If exists, then this is a flaw in the RDP Wrapper

**Comment by zaxiaowang** [comment]
![1](https://user-images.githubusercontent.com/86713233/144233302-27767968-1309-4e5c-81f2-f836bfc2df82.png)
你是指这个吗？

**Comment by zaxiaowang** [comment]
有没有什么解决办法呢？

**Comment by sashaqwert** [comment]
> 有没有什么解决办法呢？

You can write this suggestion to the developer of the modified version of the RDP Wrapper on [Discord](https://discord.gg/N27yFftWP3).
those. ask to add RemoteApp support to home.

**Comment by zaxiaowang** [comment]
OK, thank you very much for your reply

**Comment by sebaxakerhtc** [comment]
> OK, thank you very much for your reply

If your issue was solved, please close it

**Comment by sebaxakerhtc** [comment]
Closed as solved
