### ISSUE TITLE
get all state green in RDPconf.exe, but cannot see login window in RDPCheck.exe

### ISSUE THREAD

**Issue by OwenLiang1987** [stascorp/rdpwrap#1637]
![image](https://user-images.githubusercontent.com/61648540/143404478-13787db4-67e2-468f-910e-93bef02a429e.png)
![image](https://user-images.githubusercontent.com/61648540/143404640-7c396626-ef19-4c52-a6c4-2b67bbe29fc8.png)

**Comment by OwenLiang1987** [comment]
I am using RDPWrap-v1.6.2, please help check, thanks a lot

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1595
