### ISSUE TITLE
not supported srv 2022: 10.0.20348.380

### ISSUE THREAD

**Issue by vadim2853** [stascorp/rdpwrap#1638]

**Comment by monta990** [comment]
Same

**Comment by bashinator** [comment]
same here, that would be nice.. if srv 2022 got be supported!! Needed

**Comment by sebaxakerhtc** [comment]
Supported https://github.com/sebaxakerhtc/rdpwrap.ini/commit/19e5361c58372d4158ba1299a21c650704cdceaf
