### ISSUE TITLE
Missing Audio support

### ISSUE THREAD

**Issue by sjackson0109** [stascorp/rdpwrap#1639]
Can we include one-way (or possibly two-way) audio into/out of the RDP/console session?

This would be an amazing IT Support tool. Does it also have command line arguments?

**Comment by sebaxakerhtc** [comment]
The project is abandoned. So, you can do it by yourself if it really needed

**Comment by sjackson0109** [comment]
Why has this simply been closed?
No comments, no explaination, no justification.
#badPractice

**Comment by sebaxakerhtc** [comment]
> No comments, no explaination, no justification.

Read again:
"The project is abandoned"
But you still can do it by yourself!
Clone this project and start this work.
Create the same issue and maybe together we can do it
