### ISSUE TITLE
10.0.22000.318 not listening and not supported

### ISSUE THREAD

**Issue by mohamadjavith1** [stascorp/rdpwrap#1640]
im using Windows 11 Home build 22000.348. RDP Wrapper listener status is showing "not listening" and "not supported" after upgrading to windows 11 from windows 10. i was using RDP Wrapper in windows 10 home and it was working perfectly. i tried editing ini file but no luck.
![Screenshot (9)](https://user-images.githubusercontent.com/95121720/143674049-0020f437-6950-48dc-97c8-272da2b2610b.png)

**Comment by ANJ-Projects** [comment]
Agree, totally broken. 
Wasted a ton of time on this many times over many months until just giving up and using Anydesk.
Considering upgrading older PC's to Win Pro just for this. Since RDP from Microsoft is just wastly superior.

Sucks that the maintainers for this that they have not updated this to deprecated

**Comment by mohamadjavith1** [comment]
@ANJ-Projects yeah you are right. but, it is not supported by my TV and other devices

**Comment by sashaqwert** [comment]
![изображение](https://user-images.githubusercontent.com/24974508/143904049-f25afb9c-8ca1-40bf-aa19-b5336e4459c0.png)

Solution: https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
Please, rename your issue as `10.0.22000.318 not listening and not supported`

**Comment by sebaxakerhtc** [comment]
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/ab5abbce62326dde4f19044409e558f511d8d287#diff-9e5bbfbeae79b59b305dda13323ba2b041f30f4887a84120392c479e1f7bba33

**Comment by mohamadjavith1** [comment]
@sashaqwert  thankyou so much for your help. its working now. one again thanks 😊😊😊😃

**Comment by BenW12341** [comment]
hi im on windows 11, i jus installed RDP Wrap and my program shows this: 
![image](https://user-images.githubusercontent.com/101014030/156893804-bb237c08-b261-4d93-8158-4b0e4fd77696.png)
At first it was not supported but i fiddled around and got that to work however im unsure on how to change the not listening part. Any help would be appreciated
