### ISSUE TITLE
socket connection failed

### ISSUE THREAD

**Issue by Ignareo** [stascorp/rdpwrap#1642]
My system is Win10  20H2. 
I've installed rdp "RDP Wrapper Library v1.6.2  Installer v2.5"
but my RDP check is "Socket connection failed"

( there was one similar issue in this Issues before, but the solution is lost)

**Comment by moinulsk22** [comment]
y system is Win10 21H1.
I've installed rdp "RDP Wrapper Library v1.6.2 Installer v2.5"
but my RDP check is "Socket connection failed"

**Comment by sashaqwert** [comment]
RDPConf screenshot, please!

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer

**Comment by Constant-Vathorst** [comment]
Same issue here.
Installed RDP Wrapper Library v1.6.2
Screenshot:
![image](https://github.com/stascorp/rdpwrap/assets/77919605/91e7acb7-127e-4777-bd38-622c32a90f7a)

**Comment by sashaqwert** [comment]
> Screenshot

Please, search issue with your version 10.0.19...

This issue is very old...
