### ISSUE TITLE
19042  not supported

### ISSUE THREAD

**Issue by sidiosidi** [stascorp/rdpwrap#1643]
Hello,

Please support, anyone has the INI file?

My win Info: Build 19042

Thanks
![image](https://user-images.githubusercontent.com/43525317/144021825-9b0adb6e-9074-4ed9-b9d0-312feb8a1d2f.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595
