### ISSUE TITLE
Only 2 connections - Server 2019

### ISSUE THREAD

**Issue by schwupp** [stascorp/rdpwrap#1645]
I have a Server 2019 vm lab-installation with only two concurrent logins, what is default. I installed wrapper, copied latest ini, restarted box and got fully supported status. But nothing changed, i only can login two times at once.

Removing "single session per user" gives me permission to log in with same user again, what shows that "something" is working. But it keeps stopping at 3rd login.

While playing around, i noticed, that the two users can be local (i.e. 1 local console, 2 rdp, 3 denied) or rdp only (1 rdp, 2 rdp, 3 denied). I read about this a few times, but no real solution. Am i missing something here?

![2](https://user-images.githubusercontent.com/65828289/144611349-4775d362-fb37-4098-b3dd-8858cf9ee30d.JPG)
![1](https://user-images.githubusercontent.com/65828289/144611366-c1513d0c-396b-4062-9b89-f65d7d1c28c5.JPG)

**Comment by sashaqwert** [comment]
Rebooted server?

**Comment by schwupp** [comment]
sure, rebooted few times.

**Comment by sebaxakerhtc** [comment]
> Am i missing something here?

Yes, this
![rdp_limit](https://user-images.githubusercontent.com/32651506/150340715-32da305f-3420-4413-a2d2-94c422650d4c.png)

**Comment by schwupp** [comment]
thanks for the hint, but i already configured unlimited connections in GPO. 
![image](https://user-images.githubusercontent.com/65828289/150381202-4ff192dd-f29c-4c7e-aae5-52e0f1f4df92.png)

Server is part of a domain and i edited local GPO, but that should be no problem, shouldn't it?

**Comment by sebaxakerhtc** [comment]
> thanks for the hint, but i already configured unlimited connections in GPO.

Tomorrow I'll try it, but I'm sure it'll work on a clean installed Windows Server

**Comment by sebaxakerhtc** [comment]
I can't reproduce your issue even on the latest version. 
All works fine
![server2019](https://user-images.githubusercontent.com/32651506/151983610-47c04215-28a4-485e-8580-8c8c7ceac603.png)

**Comment by schwupp** [comment]
quite interesting. per accident i saw this issue which replaced rdpwarp.ini with a smaller one and voila, it worked like a charm.

https://github.com/stascorp/rdpwrap/issues/1379

what's the trick here?
