### ISSUE TITLE
not suoptersd

### ISSUE THREAD

**Issue by keerthir99** [stascorp/rdpwrap#1647]
![Screenshot (4)](https://user-images.githubusercontent.com/94477131/144808780-b4a505aa-2ea4-44bc-90c8-d28cb615efb3.png)
![Screenshot (5)](https://user-images.githubusercontent.com/94477131/144808782-113d0e89-09ba-4b79-8041-e579a0029e95.png)

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630
