### ISSUE TITLE
Access denied during installation

### ISSUE THREAD

**Issue by Dannebey** [stascorp/rdpwrap#1653]
![image](https://user-images.githubusercontent.com/57216764/145121602-786f62cd-638c-4838-83dd-26e8b6530b56.png)
![image](https://user-images.githubusercontent.com/57216764/145121667-49009ee6-2347-4cc4-8e64-0c5d96acdb6f.png)
Executed this command as administrator
reg add HKLM\SYSTEM\CurrentControlSet\Services\TermService\Parameters /v ServiceDll /t REG_EXPAND_SZ /d "%SystemRoot%\system32\termsrv.dll" /f
the problem is not solved

**Comment by Dannebey** [comment]
My windows is in Russian 
"Отказано в доступе" - Access denied

**Comment by sashaqwert** [comment]
Please, executive this as Administrator!

**Comment by sebaxakerhtc** [comment]
> the problem is not solved

Вы видите надпись "Администратор" в окне cmd?
Запустите от имени Администратора!
