### ISSUE TITLE
Full support in RDPconf but in login screens dont apears user

### ISSUE THREAD

**Issue by RodolfoBigues** [stascorp/rdpwrap#1654]
I have this issue that i need to fix asap
![Captura de pantalla 2021-12-09 172531](https://user-images.githubusercontent.com/92989780/145470759-6ad4a25b-cb9f-4ae4-9911-e863f75acf67.png)

**Comment by xanax** [comment]
Create a local local user admin account

**Comment by sebaxakerhtc** [comment]
> I have this issue that i need to fix asap

As said  @xanax 

> Create a local local user admin account

Did you solve your problem?

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
