### ISSUE TITLE
[not supported] ver. 10.0.19043.1348

### ISSUE THREAD

**Issue by geckonapper** [stascorp/rdpwrap#1656]
Can this be fixed?

![2021-12-12](https://user-images.githubusercontent.com/39681595/145757359-aa956227-4d0c-4a47-9a92-0d8fbd0cbdd4.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Comment by geckonapper** [comment]
I see that, sorry and thanks.
