### ISSUE TITLE
version:10.0.19041.1202 not supported

### ISSUE THREAD

**Issue by 73u38** [stascorp/rdpwrap#1657]
![image](https://user-images.githubusercontent.com/6307962/146022681-9c3983dc-c678-4fe8-acac-75852cd1a796.png)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/7712566/termsrv.zip)

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1509
