### ISSUE TITLE
RDPWRAP not working for multiple users after Windows 10 Update - only single user

### ISSUE THREAD

**Issue by NA6T** [stascorp/rdpwrap#166]
Hi All,
I've been using RDPWrap v1.61 for about 2 weeks and the older version before that. Since an update to Windows 10 home only 1 user is able to log into RDT . If another person trys it , the 'log off person or don't sign in' message is shown.

RDPWrap works great but I'd sure like to make it available for multiple users. Any hints? Also, if you need any files or pictures I can provide them also.  Pictures that might help are attached.  

thanks,

Bob Smith
NA6T
Northern California
![before update](https://cloud.githubusercontent.com/assets/22463174/18861527/c5c50bc2-843a-11e6-9bc4-36397fc5cd21.jpg)
![running](https://cloud.githubusercontent.com/assets/22463174/18861534/cffe2e8e-843a-11e6-9eb0-4c80cb3b8884.jpg)
![windows version 10 pro](https://cloud.githubusercontent.com/assets/22463174/18861536/d39ceb48-843a-11e6-8a6a-4c76b268a202.jpg)

**Comment by binarymaster** [comment]
![running](https://cloud.githubusercontent.com/assets/22463174/18861534/cffe2e8e-843a-11e6-9eb0-4c80cb3b8884.jpg)

On this screenshot RDP Wrapper is not installed. See diagnostics message.

**Comment by NA6T** [comment]
I saw the diference between the install before the update with (fully supported) on the config sheet.  I did the install with the installl.bat and the (fully supported) wasn't showing.  How do I get that to been seen??
As I said I used the install.bat and not seeing the (fully Supported) I ran the update.bat.  What am I doing wrong, or missing??
Thanks,

Bob

**Comment by binarymaster** [comment]
Please provide an installation log (full `install.bat` output).

**Comment by NA6T** [comment]
Today everything works.... I logged into the computer, ran the install.bat again to get you a copy of the log and then saw that the log wasn't in the folder were I ran the install.bat from.  So, I checked the config and it shows 'fully supported'.  I had another person log into the Win10 Pro computer locally and then I logged on via RDT and it worked.  Then I had her log on via RDT while I was still logged on with RDT and we both were using the computer successfully.  I didn't do anything but run the install.bat while logged on via RDT, I was disconnected, I connected back via RDT and everything is working correctly.  I''ve attached a picture of the config for you.,  This program is great and it sure makes it easy for my client to work with her supervisors connected also.   Thanks for the great program .  I'll keep track of everything and be sure to get you any info you need.. OH,  were would the install.log be saved?:?  let me know and I'll get you a copy... thanks again from Northern California...

Bob Smith
NA6T
![09-28-2016 -- 8-20pm](https://cloud.githubusercontent.com/assets/22463174/18940056/4c474c52-85ba-11e6-8e45-93ca800d3d66.jpg)

**Comment by NA6T** [comment]
sorry, I pressed the wrong icon....

it's still open

**Comment by sretlow** [comment]
I do have the same problem after the most recent update. Again not working. Hope there will be a solution soon...

**Comment by binarymaster** [comment]
@NA6T

> OH, were would the install.log be saved?

The installation log is not a file. It's an output of `install.bat` (like on your [first screenshot](https://cloud.githubusercontent.com/assets/22463174/18861527/c5c50bc2-843a-11e6-9bc4-36397fc5cd21.jpg)).

> everything is working correctly

Since everything is alright, I'm closing the issue. :)

----

@sretlow

> I do have the same problem after the most recent update. Again not working.

Keep track on issue #168, it obviously related to you.

**Comment by nitstak** [comment]
how to solve vhn wrapper shows fully supported but multiple user cant run

**Comment by nitstak** [comment]
i m trying from mrng but i dont get proper result
