### ISSUE TITLE
ini for ver 10.0.19044.1415?

### ISSUE THREAD

**Issue by DonoDayZ** [stascorp/rdpwrap#1662]
my rdp stoped after win update

**Comment by DrDroner92** [comment]
https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini

It helps to me. 
![image](https://user-images.githubusercontent.com/96225460/146321302-b802d63e-7f6e-4632-b61e-c4209e31949f.png)

**Comment by DonoDayZ** [comment]
![image](https://user-images.githubusercontent.com/37817874/146417219-e3cd1ac6-c375-475e-bbed-bb9633453361.png)
For me not work.

**Comment by DonoDayZ** [comment]
![image](https://user-images.githubusercontent.com/37817874/146419939-f361f091-4cf6-484d-8730-1424ba9c0d17.png)

**Comment by DrDroner92** [comment]
Try to reboot your pc after changing rdpwrap.ini and check it again.

As you see it [fully supported]

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Comment by fudingyu** [comment]
It work for me. My OS version is Win 10 Home 19042.1415.

**Comment by candemonjelo-ui** [comment]
Necesito una ayuda. Necesito el archivo rdpwrap ini de la versión 6937. Mí rdpwrap es versión 6926 pero mí compu 6937 y eso me marca error. Que debería hacer?
