### ISSUE TITLE
access denied 

### ISSUE THREAD

**Issue by RuggedSteak** [stascorp/rdpwrap#1665]
rdpwrap is still giving me access denied,after giving account admin privilege's.

**Comment by zekecarter** [comment]
> rdpwrap is still giving me access denied,after giving account admin privilege's.

**Try this solution**
https://github.com/stascorp/rdpwrap/issues/1666#issuecomment-997305288

**Comment by sebaxakerhtc** [comment]
> rdpwrap is still giving me access denied,after giving account admin privilege's.

Account should be in RDP group,. Admin privileges are not necessary
