### ISSUE TITLE
Windows 10 32-bit version 10.0.19041.1387 not working

### ISSUE THREAD

**Issue by Ronus1978** [stascorp/rdpwrap#1669]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/7744702/termsrv.zip)

**Comment by dlh2** [comment]
Answered in #1630 

> > x86 10.0.19044.1387
> 
> Values added [sebaxakerhtc/rdpwrap.ini@9a55a24](https://github.com/sebaxakerhtc/rdpwrap.ini/commit/9a55a24dbae7624a361032155f1b26e672ac01af)

**Comment by Ronus1978** [comment]
Thanks a lot!!!!!
