### ISSUE TITLE
windows 10  64bit  21h2 not supported version 19044.1288

### ISSUE THREAD

**Issue by Lsunny2021** [stascorp/rdpwrap#1674]
![image](https://user-images.githubusercontent.com/96612545/147626318-fbb21366-9af4-4156-ae03-240d2e234420.png)

**Comment by Lsunny2021** [comment]
ok。
The ini data come from: https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sebaxakerhtc** [comment]
> ok。 The ini data come from: https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

Is your Windows x86 or x64?

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1509
