### ISSUE TITLE
Is this project no longer in active development?

### ISSUE THREAD

**Issue by WoodpeckerBaby** [stascorp/rdpwrap#1677]
Does it still work on the latest version of Windows? Can I expect it will continue to work before trying to install?

**Comment by sebaxakerhtc** [comment]
The project is abandoned, but it still work trough autoupdate.bat from [asmtron](https://github.com/asmtron/rdpwrap) or using [my MOD](https://github.com/sebaxakerhtc/rdpwrap/releases)

**Comment by Berque** [comment]
> The project is abandoned, but it still work trough autoupdate.bat from [asmtron](https://github.com/asmtron/rdpwrap) or using [my MOD](https://github.com/sebaxakerhtc/rdpwrap/releases)

How to use them? Any tutorial for beginners?

**Comment by sebaxakerhtc** [comment]
Modded version download and run, about autoupdate.bat look at repo

чт, 20 янв. 2022 г., 15:15 Berque ***@***.***>:

**Comment by dimonpanik** [comment]
> The project is abandoned, but it still work trough autoupdate.bat from [asmtron](https://github.com/asmtron/rdpwrap) or using [my MOD](https://github.com/sebaxakerhtc/rdpwrap/releases)

Have you fixed the issue with RDP printing?

**Comment by sebaxakerhtc** [comment]
Not an issue with RDPWrapper
