### ISSUE TITLE
RDPconf.exe Crashed

### ISSUE THREAD

**Issue by C00LVansh** [stascorp/rdpwrap#1682]
I just opened the exe and it opened and closed immediately,
anyway to fix it?

**Comment by sebaxakerhtc** [comment]
> anyway to fix it?

It 100% worked. Check your OS health

**Comment by subham-sd** [comment]
10.0.19041.1682 not supported #1838

**Comment by sebaxakerhtc** [comment]
> 10.0.19041.1682 not supported #1838

https://github.com/sebaxakerhtc/rdpwrap.ini/blob/ba102245988a547754f9e0bb55b2bb3f5feaa36d/rdpwrap.ini#L5029
