### ISSUE TITLE
rdp 10.0.16299.1087 listening

### ISSUE THREAD

**Issue by MaikKirito** [stascorp/rdpwrap#1683]
no listening y service stopped si alguien tiene alguna solucion se lo agradeceria

**Comment by MSI-Toby** [comment]
Prueba esto. (Lo siento, me espanol no es bueno)
[https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini](url)

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1093
