### ISSUE TITLE
10.0.22000.466

### ISSUE THREAD

**Issue by UMU618** [stascorp/rdpwrap#1687]
https://github.com/UMU618/rdpwrap.ini/

.text:0000000180099220 sub_180099220
.text:00000001800992B1                 jz      short loc_1800992F7

.text:00000001800088B0 sub_1800088B0
.text:00000001800088C0                 mov     r14d, 1
41 BE 01 00 00 00
.text:00000001800088C6                 cmp     cs:dword_18011FECC, edi

.text:000000018001BB75                 cmp     [rcx+63Ch], eax

.text:0000000180026D20 sub_180026D20   proc near               ; CODE XREF: sub_1800088B0:loc_18002A3A6↓p
.text:0000000180026D20                                         ; sub_180008908:loc_18002A550↓p ...
.text:0000000180026D20
.text:0000000180026D20 var_528         = qword ptr -528h
.text:0000000180026D20 var_520         = qword ptr -520h
.text:0000000180026D20 var_518         = qword ptr -518h
.text:0000000180026D20 var_510         = qword ptr -510h
.text:0000000180026D20 var_508         = dword ptr -508h
.text:0000000180026D20 var_504         = dword ptr -504h
.text:0000000180026D20 var_500         = dword ptr -500h
.text:0000000180026D20 var_4FC         = dword ptr -4FCh
.text:0000000180026D20 var_4F8         = dword ptr -4F8h
.text:0000000180026D20 var_4F4         = dword ptr -4F4h
.text:0000000180026D20 var_4F0         = dword ptr -4F0h
.text:0000000180026D20 var_4EC         = dword ptr -4ECh
.text:0000000180026D20 var_4E8         = dword ptr -4E8h
.text:0000000180026D20 var_4E4         = dword ptr -4E4h
.text:0000000180026D20 var_4E0         = dword ptr -4E0h
.text:0000000180026D20 var_4DC         = dword ptr -4DCh
.text:0000000180026D20 var_4D8         = dword ptr -4D8h
.text:0000000180026D20 var_4D4         = byte ptr -4D4h
.text:0000000180026D20 var_4D0         = dword ptr -4D0h
.text:0000000180026D20 var_4CC         = byte ptr -4CCh
.text:0000000180026D20 var_4C8         = dword ptr -4C8h
.text:0000000180026D20 var_4C4         = byte ptr -4C4h
.text:0000000180026D20 var_4C0         = dword ptr -4C0h
.text:0000000180026D20 var_4BC         = byte ptr -4BCh
.text:0000000180026D20 var_4B8         = dword ptr -4B8h
.text:0000000180026D20 var_4B4         = byte ptr -4B4h
.text:0000000180026D20 var_4B0         = dword ptr -4B0h
.text:0000000180026D20 var_4AC         = byte ptr -4ACh
.text:0000000180026D20 var_4A8         = dword ptr -4A8h
.text:0000000180026D20 var_4A4         = byte ptr -4A4h
.text:0000000180026D20 var_4A0         = dword ptr -4A0h
.text:0000000180026D20 var_49C         = byte ptr -49Ch
.text:0000000180026D20 var_498         = dword ptr -498h
.text:0000000180026D20 var_494         = byte ptr -494h
.text:0000000180026D20 var_490         = dword ptr -490h
.text:0000000180026D20 var_48C         = byte ptr -48Ch
.text:0000000180026D20 var_488         = dword ptr -488h
.text:0000000180026D20 var_484         = byte ptr -484h
.text:0000000180026D20 var_480         = qword ptr -480h
.text:0000000180026D20 var_478         = qword ptr -478h
.text:0000000180026D20 var_470         = qword ptr -470h
.text:0000000180026D20 var_468         = qword ptr -468h
.text:0000000180026D20 var_460         = qword ptr -460h
.text:0000000180026D20 var_458         = qword ptr -458h
.text:0000000180026D20 var_450         = qword ptr -450h
.text:0000000180026D20 var_448         = qword ptr -448h
.text:0000000180026D20 var_440         = qword ptr -440h
.text:0000000180026D20 var_438         = qword ptr -438h
.text:0000000180026D20 var_430         = qword ptr -430h
.text:0000000180026D20 var_428         = qword ptr -428h
.text:0000000180026D20 var_420         = qword ptr -420h
.text:0000000180026D20 var_418         = qword ptr -418h
.text:0000000180026D20 var_410         = qword ptr -410h
.text:0000000180026D20 var_408         = qword ptr -408h
.text:0000000180026D20 var_400         = qword ptr -400h
.text:0000000180026D20 var_3F8         = qword ptr -3F8h
.text:0000000180026D20 var_3F0         = qword ptr -3F0h
.text:0000000180026D20 var_3E8         = qword ptr -3E8h
.text:0000000180026D20 var_3E0         = qword ptr -3E0h
.text:0000000180026D20 var_3D8         = qword ptr -3D8h
.text:0000000180026D20 var_3D0         = qword ptr -3D0h
.text:0000000180026D20 var_3C8         = qword ptr -3C8h
.text:0000000180026D20 var_3C0         = qword ptr -3C0h
.text:0000000180026D20 var_3B8         = qword ptr -3B8h
.text:0000000180026D20 var_3B0         = qword ptr -3B0h
.text:0000000180026D20 var_3A8         = qword ptr -3A8h
.text:0000000180026D20 var_3A0         = qword ptr -3A0h
.text:0000000180026D20 var_398         = qword ptr -398h
.text:0000000180026D20 var_390         = qword ptr -390h
.text:0000000180026D20 var_388         = qword ptr -388h
.text:0000000180026D20 var_380         = qword ptr -380h
.text:0000000180026D20 var_378         = qword ptr -378h
.text:0000000180026D20 var_370         = qword ptr -370h
.text:0000000180026D20 var_368         = qword ptr -368h
.text:0000000180026D20 var_360         = qword ptr -360h
.text:0000000180026D20 var_358         = qword ptr -358h
.text:0000000180026D20 var_350         = qword ptr -350h
.text:0000000180026D20 var_348         = qword ptr -348h
.text:0000000180026D20 var_340         = qword ptr -340h
.text:0000000180026D20 var_338         = qword ptr -338h
.text:0000000180026D20 var_330         = qword ptr -330h
.text:0000000180026D20 var_328         = qword ptr -328h
.text:0000000180026D20 var_320         = qword ptr -320h
.text:0000000180026D20 var_318         = qword ptr -318h
.text:0000000180026D20 var_310         = qword ptr -310h
.text:0000000180026D20 var_308         = qword ptr -308h
.text:0000000180026D20 var_300         = qword ptr -300h
.text:0000000180026D20 var_2F8         = qword ptr -2F8h
.text:0000000180026D20 var_2F0         = qword ptr -2F0h
.text:0000000180026D20 var_2E8         = qword ptr -2E8h
.text:0000000180026D20 var_2E0         = qword ptr -2E0h
.text:0000000180026D20 var_2D8         = qword ptr -2D8h
.text:0000000180026D20 var_2D0         = qword ptr -2D0h
.text:0000000180026D20 var_2C8         = qword ptr -2C8h
.text:0000000180026D20 var_2C0         = qword ptr -2C0h
.text:0000000180026D20 var_2B8         = qword ptr -2B8h
.text:0000000180026D20 var_2B0         = qword ptr -2B0h
.text:0000000180026D20 var_2A8         = qword ptr -2A8h
.text:0000000180026D20 var_2A0         = qword ptr -2A0h
.text:0000000180026D20 var_298         = qword ptr -298h
.text:0000000180026D20 var_290         = qword ptr -290h
.text:0000000180026D20 var_288         = byte ptr -288h
.text:0000000180026D20 var_280         = byte ptr -280h
.text:0000000180026D20 var_278         = byte ptr -278h
.text:0000000180026D20 var_270         = byte ptr -270h
.text:0000000180026D20 var_268         = byte ptr -268h
.text:0000000180026D20 var_260         = byte ptr -260h
.text:0000000180026D20 var_258         = byte ptr -258h
.text:0000000180026D20 var_250         = byte ptr -250h
.text:0000000180026D20 var_248         = byte ptr -248h
.text:0000000180026D20 var_240         = byte ptr -240h
.text:0000000180026D20 var_238         = byte ptr -238h
.text:0000000180026D20 var_230         = byte ptr -230h
.text:0000000180026D20 var_228         = byte ptr -228h
.text:0000000180026D20 var_220         = byte ptr -220h
.text:0000000180026D20 var_218         = byte ptr -218h
.text:0000000180026D20 var_210         = byte ptr -210h
.text:0000000180026D20 var_208         = byte ptr -208h
.text:0000000180026D20 var_200         = byte ptr -200h
.text:0000000180026D20 var_1F8         = byte ptr -1F8h
.text:0000000180026D20 var_1F0         = byte ptr -1F0h
.text:0000000180026D20 var_1E8         = byte ptr -1E8h
.text:0000000180026D20 var_1E0         = byte ptr -1E0h
.text:0000000180026D20 var_1D8         = byte ptr -1D8h
.text:0000000180026D20 var_1D0         = byte ptr -1D0h
.text:0000000180026D20 var_1C8         = byte ptr -1C8h
.text:0000000180026D20 var_1C0         = byte ptr -1C0h
.text:0000000180026D20 var_1B8         = byte ptr -1B8h
.text:0000000180026D20 var_1B0         = byte ptr -1B0h
.text:0000000180026D20 var_1A8         = byte ptr -1A8h
.text:0000000180026D20 var_1A0         = byte ptr -1A0h
.text:0000000180026D20 var_198         = byte ptr -198h
.text:0000000180026D20 var_190         = byte ptr -190h
.text:0000000180026D20 var_188         = byte ptr -188h
.text:0000000180026D20 var_180         = byte ptr -180h
.text:0000000180026D20 var_178         = byte ptr -178h
.text:0000000180026D20 var_170         = byte ptr -170h
.text:0000000180026D20 var_168         = byte ptr -168h
.text:0000000180026D20 var_160         = byte ptr -160h
.text:0000000180026D20 var_158         = byte ptr -158h
.text:0000000180026D20 var_150         = byte ptr -150h
.text:0000000180026D20 var_148         = byte ptr -148h
.text:0000000180026D20 VersionInformation= _OSVERSIONINFOW ptr -138h
.text:0000000180026D20 var_1E          = byte ptr -1Eh
.text:0000000180026D20 var_18          = qword ptr -18h

**Comment by cnoim** [comment]
thanks a lot

**Comment by sebaxakerhtc** [comment]
Is it question or answer? Hide it at spoiler and provide a description of what you want

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer

**Comment by UMU618** [comment]
answer

**Comment by sebaxakerhtc** [comment]
> answer

So a good idea is to hide a long text at spoiler and neme the issue, for example [SOLVED] 10.0.22000.466 not supported
