### ISSUE TITLE
RDP fails to connect after uninstalling RDPWrap

### ISSUE THREAD

**Issue by terelldunn** [stascorp/rdpwrap#169]
I installed RDPWrap to try to fix an issue I was having with RDP. I decided to do some more troubleshooting, so I uninstalled RDPWrap to remove that variable in my troubleshooting. 

Now, unless RDPWrap is installed, I can no longer connect to the work station. 

When RDPWrap was installed, I only toggled the Authentication Mode and Session Shadowing Mode settings. 

My attempts to fix:
I reinstalled RDPWrap, toggled the settings back to default, and uninstalled RDPWrap again. 

I would appreciate any ideas.

Thanks,
Terell

**Comment by terelldunn** [comment]
I stumbled across Issue #106 . RDPWrap was not returning my settings back to their default. It was disallowing remote connections.

**Comment by binarymaster** [comment]
> RDPWrap was not returning my settings back to their default. It was disallowing remote connections.

In the fresh Windows installation RDP is disabled by default.

**Comment by terelldunn** [comment]
I had RDP enabled prior to installing RDPWrap.

**Comment by binarymaster** [comment]
Installer couldn't set settings on uninstall which were before the installation. It resets all settings to their system defaults.

However you can specify the uninstall to keep the settings (see #106).

**Comment by terelldunn** [comment]
That makes sense. So far, RDPWrap is great. Nice work.
