### ISSUE TITLE
Service state version ver. N/A on Windows 11

### ISSUE THREAD

**Issue by smallerxie** [stascorp/rdpwrap#1690]
Hello guys,
I have this problem with RDP Wrapper after installing Windows 11 (all-new-install). Winodws 11 Education (same as Professional) Version 21H2 22000.434 with its termsev.dll version 10.0.22000.318.
The installation of RDPWrap seems normal but the RDPConf program shows something wrong (see pic.).
![service-state-N-A-RDPConf](https://user-images.githubusercontent.com/19313471/149972545-62af2b1d-5a27-40c4-aca5-c3e832f0ad34.jpg)

I have also tried RDPWInst.exe -r, 
```
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Restarting...
[+] TermService found (pid 2464).
[*] No shared services found.
[*] Terminating service...
[*] Starting TermService...
[-] StartService error (code 1056).
[+] Done.
```

However, when I tried "`net start termservice`", it returns that the service has already been started.

I also paste the RDPCheck snapshot if it helps: 
![service-state-N-A-RDPCheck](https://user-images.githubusercontent.com/19313471/149973562-af5dd75b-c939-4bb9-9076-3dc94a7056f5.jpg)

The replacement of rdpwrap.ini has no effect as (I think) the problem is with the RDPWrap installation or something wrong with the windows 11 OS.

Thanks a lot if you can help!

**Comment by sebaxakerhtc** [comment]
Your antivirus blocked rdpwrap.dll
You should recover this file from antivirus.
Disable antivirus when you install rdpwrapper and add its folder to exclusions

**Comment by Early0v0** [comment]
I met the same problem in Windows 11 Education Version 21H2 22000.438.

I've checked my antivirus but found nothing.

Now my temporary solution is to fill the username here and retry:
![snapshot](https://user-images.githubusercontent.com/44915258/150143321-1ec070b8-1aab-4d12-b901-1ee86a345e69.png)

It worked in my computer.

**Comment by GDLiuYuXin** [comment]
![image](https://user-images.githubusercontent.com/52062796/151658181-9cf79ead-1cc4-40bb-abb2-acd2ed3583fc.png)
I tried to adjust the configuration and finally passed
我尝试调整了配置后终于可以通过
