### ISSUE TITLE
2 users at this same time

### ISSUE THREAD

**Issue by dawidmosk** [stascorp/rdpwrap#1691]
2 users at this same time, local and remote on one computer, RDP session in background.

**Comment by sebaxakerhtc** [comment]
> 2 users at this same time, local and remote on one computer, RDP session in background.

Is it a question?
rdpconf screenshot please

**Comment by dawidmosk** [comment]
maybe issue or "requests". Its good future. Local user using normally computer and other working via network with this.
![image](https://user-images.githubusercontent.com/60958552/150353678-c6ac96c4-9e71-4e02-af64-9833aefcbf7e.png)

**Comment by sebaxakerhtc** [comment]
> Its good future. Local user using normally computer and other working via network with this.

That works perfect without issues. Try manually replace [rdpwrapper.ini ](https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini) and restart your PC

Applicable to https://github.com/stascorp/rdpwrap/issues/1599

**Comment by dawidmosk** [comment]
Still dont work (with this ini), my local user cant use this computer. Remontly connecting user changing sigin user to own. Its possible to work with two and more external users (always something from external is on local screen - its ok if this is server) but cant work local and external at this same time.
