### ISSUE TITLE
version:10.0.19044.1320

### ISSUE THREAD

**Issue by BlitheLe** [stascorp/rdpwrap#1692]
How to edit the rdpwrap.ini to make RDPConf available?

**Comment by sashaqwert** [comment]
Please, attach rour RDPConf screenshot.
You can get this in [RDPWrap ZIP (release 1.6.2)](https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip) --> RDPConf.exe

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1574
