### ISSUE TITLE
Downloading ini.file?

### ISSUE THREAD

**Issue by Berque** [stascorp/rdpwrap#1693]
Hello, quick question.
As far as i have read, a latest version of an .ini file is needed to be downloaded while installing. 
( I got the instructions from here[Here](https://www.helpwire.app/blog/allow-multiple-remote-desktop-connections-windows-10/) )

The problem is i am using rdp only in internal network, there is no internet access and i am not supposed to connect those computers to internet at all. 

So i downloaded the installation files to a usb for travelling around devices. 

How do i manually download the ini file and put it correct place?
 Thanks!

**Comment by sebaxakerhtc** [comment]
> How do i manually download the ini file and put it correct place?

You can use my [Modded version](https://github.com/sebaxakerhtc/rdpwrap/releases/tag/v1.8.6.1) which include rdpwrap.ini up to 08 dec 2021 or 
Download redpwrap.ini from source you want (my is [here](https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini)) and then
net stop termservice
Replace rdpwrap.ini in c:\Program Files\RDP Wrapper directory
net start termservice

**Comment by sebaxakerhtc** [comment]
Closed as solved
