### ISSUE TITLE
rdp wrapper not supported

### ISSUE THREAD

**Issue by jaleedraja1** [stascorp/rdpwrap#1699]
rdp wrapper is showing not supported
my windows os is 19043.1466

**Comment by sashaqwert** [comment]
> my windows os is 19043.1466

This is not a ```termsrv.dll``` version.
RDPConf screenshot, please!

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630
