### ISSUE TITLE
RDP remote desktop users not working error code 1075

### ISSUE THREAD

**Issue by Gnanama** [stascorp/rdpwrap#1701]
RDP remote desktop users not working error code 1075

**Comment by sebaxakerhtc** [comment]
Clearify your steps to reproduce it. Does it work without rdpwrapper?

**Comment by Gnanama** [comment]
How to this error solving sir

**Comment by sebaxakerhtc** [comment]
> How to this error solving sir

What are the steps to reproduce your issue?
Which termsrv.dll version?
Rdpwrapper version?
Rdpconf screenshot?

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
