### ISSUE TITLE
RDP users service not working error so

### ISSUE THREAD

**Issue by Gnanama** [stascorp/rdpwrap#1702]
remote server error 1075 the dependency service does not exist or has been marked for deletion

**Comment by Gnanama** [comment]
Windows server 2016

**Comment by sashaqwert** [comment]
Please, restore backup of registry from clean system.

Backup from LTSC 2019 (I'm don't know this from client or server): 
[TerminalService_1809_LTSC.zip](https://github.com/stascorp/rdpwrap/files/7963181/TerminalService_1809_LTSC.zip)
Original: https://t.me/rdpwrap/41015

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1701
