### ISSUE TITLE
not listening Windows 10 Pro 21H1, 19043.1466

### ISSUE THREAD

**Issue by Milosport007** [stascorp/rdpwrap#1703]
I have a problem the RDP Wrapper Configuration

Listener state: Not Listening     [Fully Supported]

I have tried several options but I have not been able to turn the listener state green

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1630
Look [this ](https://github.com/stascorp/rdpwrap/issues/1251#issuecomment-747427005) solution

**Comment by anatsri** [comment]
my listener state: listening 
but not supported 
what to do to resolve the issue of not supported?
![Screenshot (37)](https://user-images.githubusercontent.com/79005748/153594880-4c00a00a-5546-4a81-82d0-cc252f6c652a.png)

**Comment by sebaxakerhtc** [comment]
> my listener state: listening but not supported what to do to resolve the issue of not supported? ![Screenshot (37)](https://user-images.githubusercontent.com/79005748/153594880-4c00a00a-5546-4a81-82d0-cc252f6c652a.png)

Use my ini file or my modded version
