### ISSUE TITLE
10.0.19042.1415 Not Supported

### ISSUE THREAD

**Issue by bkoyip** [stascorp/rdpwrap#1705]
10.0.19042.1415 Not Supported - Windows 10 20H2, Dec 2021 Windows Update.
Please update the ini to support this version.
Attached with termsrv.zip on this build.
Thank you.
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/7990176/termsrv.zip)
.

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630
