### ISSUE TITLE
10.0.19041.1503 X86

### ISSUE THREAD

**Issue by yorchwa** [stascorp/rdpwrap#1709]
Anybody has the rdwrap.ini for 10.0.19041.1503 x86. Thanks

**Comment by sebaxakerhtc** [comment]
> Anybody has the rdwrap.ini for 10.0.19041.1503 x86. Thanks

Please attach your termsrv.dll
Applicable to https://github.com/stascorp/rdpwrap/issues/1697

**Comment by yorchwa** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8009776/termsrv.zip)
Find it attached.
Thanks

**Comment by sebaxakerhtc** [comment]
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/8009776/termsrv.zip) Find it attached. Thanks

Values added, thank you!
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/36ef9d6d627cd4cea4880a1809b898005620ceab
