### ISSUE TITLE
How to modify the original INI file to adapt to the current system version?

### ISSUE THREAD

**Issue by Shicc** [stascorp/rdpwrap#1710]
After the system is upgraded, the originally supported INI files cannot be used again, and how to modify the original INI file to adapt to the current system version?

**Comment by sebaxakerhtc** [comment]
> After the system is upgraded, the originally supported INI files cannot be used again, and how to modify the original INI file to adapt to the current system version?

net stop termservice
edit ini
net start termservice

Applicable to https://github.com/stascorp/rdpwrap/issues/1693
