### ISSUE TITLE
Access is Denied

### ISSUE THREAD

**Issue by undead2cold** [stascorp/rdpwrap#1712]
i have updated my Ini servers and downloaded the Modded RDP Wraspper and its all running and listening but it wont let me log in...

**Comment by undead2cold** [comment]
![Capture](https://user-images.githubusercontent.com/25470936/153328783-e469cbcc-d5e9-43d8-b2a8-137a5f52cdca.PNG)

**Comment by evgeshock** [comment]
Excuse me, do you need to update ini file manually if you use modded wrapper?

**Comment by undead2cold** [comment]
> Excuse me, do you need to update ini file manually if you use modded wrapper?

no you should be able to just install it and go but right now there is an issus with it i guess

**Comment by evgeshock** [comment]
so, you think that ini file updates automatically? i, m not shure

**Comment by sebaxakerhtc** [comment]
> i have updated my Ini servers and downloaded the Modded RDP Wraspper and its all running and listening but it wont let me log in...

Try to use Network Level Authentication and reboot your PC

Applicable to https://github.com/stascorp/rdpwrap/issues/1697

**Comment by undead2cold** [comment]
it still doesnt allow me to have more then one session per user. i've done a full reset on my pc and still doesnt work.
