### ISSUE TITLE
only one session allowed 10.0.19041.1503

### ISSUE THREAD

**Issue by vdovin1981** [stascorp/rdpwrap#1713]
Hi. I updated rdpwrap.ini from (https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini)
No It says Fully Supported, but only one session allowed, as its not supported
![rdp_wrap](https://user-images.githubusercontent.com/77384322/153350341-f08b3181-fc25-4ccb-baec-16695b9d6d30.png)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8038610/termsrv.zip)

Need help. Thx

**Comment by Diverti** [comment]
Have the same issue, but here it says not supported
![image](https://user-images.githubusercontent.com/24979584/153354705-41feee4e-c9d3-4f9c-934f-1dc9ac2e5d9a.png)

**Comment by devenhala** [comment]
Does the windows ver 10.0.19044.1526 ?
Try to update the fresh ini profile. And reboot.

https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini

**Comment by Diverti** [comment]
I tried the @vdovin1981 's ini and after a reboot, everything worked for me.
Also, i selected default RDP auth. at the autentication mode.

**Comment by vdovin1981** [comment]
Same result - only one client can join
Does the windows ver 10.0.19044.1526 ? Yes its my windows version

**Comment by Demon-i** [comment]
I've found KB5010342 installed yesterday. Deleting does not help. Rolling back to restore point from feb 8 for now.

**Comment by vdovin1981** [comment]
still need help

**Comment by Demon-i** [comment]
> I've found KB5010342 installed yesterday. Deleting does not help. Rolling back to restore point from feb 8 for now.

Rollback worked for me. Its a production mashine. Can't experiment on it for now.

**Comment by vveljk** [comment]
I have the same situation as vdovin1981.

Help would be much appreciated.

**Comment by sinagumus11** [comment]
Same situation with me. There is no problem in the rdp conf settings, but only one person can connect.

**Comment by ForwardUntoDawn** [comment]
> Does the windows ver 10.0.19044.1526 ? Try to update the fresh ini profile. And reboot.
> https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini

This updated INI sorted me out for the windows version listed above.
Thanks for providing a link to the update @devenhala!  Rock on.

**Comment by FranceBB** [comment]
Using the updated ini works for me, thanks.

**Comment by vveljk** [comment]
> > Does the windows ver 10.0.19044.1526 ? Try to update the fresh ini profile. And reboot.
> > https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini
> 
> This updated INI sorted me out for the windows version listed above. Thanks for providing a link to the update @devenhala! Rock on.

Tried that one already and it is not working for me.

**Comment by vdovin1981** [comment]
Tried different late rdpwrap.ini, results are same - Fully Support, but only one session works

**Comment by vdovin1981** [comment]
May be I need to update termsrv.dll?

**Comment by vdovin1981** [comment]
Just checked another computer with same windows version. And I have same results

**Comment by SNM1966** [comment]
> Using the updated ini works for me, thanks.

Same here on 21H1 19043.1526

**Comment by kainago** [comment]
Dont work for me to

**Comment by vdovin1981** [comment]
I just checked my third computer. It has same problem. 
![rdp_wrap](https://user-images.githubusercontent.com/77384322/153472078-1c29b2cf-14d8-4ab8-b65e-b9e2e22aa3b0.png)

**Comment by vdovin1981** [comment]
<img width="967" alt="rdpwrap10-02" src="https://user-images.githubusercontent.com/77384322/153472134-712dba79-30d6-4d4b-a04f-9445947a7587.png">
Just checked third computer. It has same problem

**Comment by undead2cold** [comment]
yea same happend to me, i only can have one session person account. anyone got a fix yet?

**Comment by qmxlf** [comment]
![1644541175(1)](https://user-images.githubusercontent.com/99453666/153522128-a15835ff-5aa7-4f40-b392-fd27a8c04125.png)
i got the same problem...
the ver shows N/A

**Comment by DarkHelmet2020** [comment]
![image](https://user-images.githubusercontent.com/99455371/153524290-58577cbe-318d-45b4-b376-3b47020ff803.png)

Same issue here - tried using the latest rdpwrap.ini that was provided above, but still can only have one simultaneous login (local or RDP) at a time as of a day or so ago.  

Any help is greatly appreciated!

**Comment by fibustos** [comment]
same problem here!

> ![image](https://user-images.githubusercontent.com/99455371/153524290-58577cbe-318d-45b4-b376-3b47020ff803.png)
> 
> Same issue here - tried using the latest rdpwrap.ini that was provided above, but still can only have one simultaneous login (local or RDP) at a time as of a day or so ago.
> 
> Any help is greatly appreciated!

**Comment by KINGVON1** [comment]
same problem here!
too！

**Comment by fibustos** [comment]
I solved the problem by reboot mi pc! lol

**Comment by DarkHelmet2020** [comment]
> I solved the problem by reboot mi pc! lol

Can confirm restarting did not fix the issue for me - but glad you got it resolved.

Anyone else have any assistance they can offer?

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1697
![1](https://user-images.githubusercontent.com/32651506/153605620-995f913e-2103-43d8-aac1-1bcd696a2bf3.png)

It's strange... Try to log in localy and then remotely

**Comment by vdovin1981** [comment]
Still need help.

**Comment by sebaxakerhtc** [comment]
> Still need help.

Can you try my modded installer?

**Comment by DarkHelmet2020** [comment]
I removed RDP Wrapper altogether, rebooted, redownloaded v1.6.2 (https://github.com/stascorp/rdpwrap/releases) and installed using install.bat, stopped remote desktop services, replaced rdpwrap.ini with this one (https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini), restarted services, and this resolved my issue.

**Comment by sinagumus11** [comment]
> I removed RDP Wrapper altogether, rebooted, redownloaded v1.6.2 (https://github.com/stascorp/rdpwrap/releases) and installed using install.bat, stopped remote desktop services, replaced rdpwrap.ini with this one (https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini), restarted services, and this resolved my issue.

This is how I solved it too. Thanks

**Comment by Smokeisop** [comment]
> Hi. I updated rdpwrap.ini from (https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini) No It says Fully Supported, but only one session allowed, as its not supported ![rdp_wrap](https://user-images.githubusercontent.com/77384322/153350341-f08b3181-fc25-4ccb-baec-16695b9d6d30.png) [termsrv.zip](https://github.com/stascorp/rdpwrap/files/8038610/termsrv.zip)
> 
> Need help. Thx

Hey how did you get yours to say listening mine is not listening and i can't seem to fix it, do you know why its red❔

**Comment by sebaxakerhtc** [comment]
> Hey how did you get yours to say listening mine is not listening and i can't seem to fix it, do you know why its red❔

As admin in cmd:
net start termservice
