### ISSUE TITLE
10.0.19041.1503 not supported, not listening

### ISSUE THREAD

**Issue by Smokeisop** [stascorp/rdpwrap#1730]
First of all it was not supported so i looked at someone's issue and gotta another script\ coding and replaced that with the original rdpwrap file and got it to be fully supported, Before that it wasn't fully supported or listening then as i said i got that script and replaced it to be fully supported then after that my " listener state " was the same not listening, Can someone please help me out with this idk if need another coding\script or what to do.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1697
