### ISSUE TITLE
is there a problem with my termsrv

### ISSUE THREAD

**Issue by undead2cold** [stascorp/rdpwrap#1732]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8100309/termsrv.zip)

my service still isnt working.

**Comment by sashaqwert** [comment]
Your DLL version is 10.0.19041.1503.
Please, do not change DLL to ZIP.
Please, pack your DLL in ZIP archive...

# Duplicate of https://github.com/stascorp/rdpwrap/issues/1697
