### ISSUE TITLE
19041.1566 win 21H2 - Not Supported

### ISSUE THREAD

**Issue by giordan-net** [stascorp/rdpwrap#1734]
Wrapper state: Installed - ver. 1.5.0.0
Service state: Runnig - ver. 10.0.19041.1566 
Listener state: Listening - NOT SUPPORTED

Can anyone solve not supported state, plz

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Comment by robertodan** [comment]
Used the ini file. Thanks! 

Fully supported but "not listening"... restarted the service, restarted the pc. Didn't work. 

What am I missing? Thank you!
