### ISSUE TITLE
19042.1526 ini

### ISSUE THREAD

**Issue by Mozharova** [stascorp/rdpwrap#1739]
Good mornibg
I need: 19042.1526 ini, thanks/

**Comment by sashaqwert** [comment]
RDPConf (or RDP_CnC) screenshot, please!

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1697

**Comment by Mozharova** [comment]
![image](https://user-images.githubusercontent.com/92950657/155021477-91ac0b31-62c2-4e4a-94cf-2ab5482ffab8.png)

**Comment by Mozharova** [comment]
i found ini here/ thanks
