### ISSUE TITLE
RDP wrapper stopped working

### ISSUE THREAD

**Issue by DeteG** [stascorp/rdpwrap#174]
I have win10 running (14393.321). RDP wrapper worked fine until some days ago. 
Now it does not change the number of possible connetions any more.
It looks like some automatic windows updates made on the 18th of October have affected the operation.
The updates are: KB3199209, KB3176937, KB3176935
Uninstalling the second and the third did not help uninstalling the first is not possible.

Is there any idea how to get it running again?

**Comment by binarymaster** [comment]
You tried to uninstall updates, but didn't tried to reinstall RDP Wrapper. Why?

Since there is no diagnostics screenshot, I have no idea.

**Comment by DeteG** [comment]
I was not aware o fthe need to reinstall RDP Wrapper. It works now.

Thank you for telling me to reinstall
