### ISSUE TITLE
Not Supported 10.0.22000.469

### ISSUE THREAD

**Issue by guimatheus92** [stascorp/rdpwrap#1747]
On `RDPConf` it's showing:

![image](https://user-images.githubusercontent.com/11640754/155867296-69b4b2d5-49e1-431f-bf70-f5e75b673643.png)

On my windows details is: `1000.22000.527.0`

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1698
