### ISSUE TITLE
Fully supported, but local + remote user conflict

### ISSUE THREAD

**Issue by danieltuzes** [stascorp/rdpwrap#1749]
I have Windows 10.0.19041.1503, and used the ini from https://github.com/stascorp/rdpwrap/issues/1697
I can log in remotely multiple times, but I cannot log in locally and remotely. If I try to log in remotely, it halts at
"Securing remote connection"
![Screenshot 2022-02-28 091229](https://user-images.githubusercontent.com/6088393/155955979-03043c06-8de1-426e-b047-244a701d5737.png)

Any ideas for further debugging?

**Comment by sashaqwert** [comment]
Please, uncheck "Single session per user" in RDPConf.

**Comment by danieltuzes** [comment]
I try to connect to a different user than who is logged in.

**Comment by sashaqwert** [comment]
If replacing the INI from https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini does not help, then I can suggest checking the integrity of the system (```sfc /scannow```) or using [Windows 10 Enterprise for virtusal desktops](https://github.com/stascorp/rdpwrap/issues/1478#issuecomment-886222080)...

**Comment by danieltuzes** [comment]
Thanks!
