### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by ugurguzel** [stascorp/rdpwrap#1750]
I get the error "The number of incoming connections to this computer is limited".

![Error](https://user-images.githubusercontent.com/80459483/156131803-15382da0-1653-4b79-992d-ab917d29a85f.JPG)

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/1697

**Comment by ugurguzel** [comment]
I tried the ini file, still the same.

https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by ugurguzel** [comment]
Ok, i rebooted and it worked. Thanks.
