### ISSUE TITLE
Not supported Version	10.0.19041.1503

### ISSUE THREAD

**Issue by aneubau** [stascorp/rdpwrap#1751]

**Comment by sebaxakerhtc** [comment]
No rdpconf screenshot, no correct version

**Comment by aneubau** [comment]
RDPconf: 1.5.0.0 updated via iunternet

**Comment by aneubau** [comment]
After reinstall RDPCheck: shows following message:
the number of connections to this computer is limited, and all connections are currently used

**Comment by sebaxakerhtc** [comment]
> After reinstall RDPCheck: shows following message: the number of connections to this computer is limited, and all connections are currently used

Look at first issue
Duplicate of https://github.com/stascorp/rdpwrap/issues/1697

**Comment by aneubau** [comment]
Thanks, works now.
Sorry for my sloppy review of the open issues
