### ISSUE TITLE
resolution 640x480

### ISSUE THREAD

**Issue by saperex** [stascorp/rdpwrap#1752]
how can I change the resolution of rdpchecker, this is the only utility that allows you to use the connection of a second user via Parsec, on a second PC over a local network, but alas, the resolution is too low 640x480, although there are drivers and a video card on the PC

**Comment by sebaxakerhtc** [comment]
> how can I change the resolution of rdpchecker, this is the only utility that allows you to use the connection of a second user via Parsec, on a second PC over a local network, but alas, the resolution is too low 640x480, although there are drivers and a video card on the PC

No functionality. Try my modded version or use mstsc 127.0.0.2
