### ISSUE TITLE
unable install for 10.0.19041.1023

### ISSUE THREAD

**Issue by Bryanyun** [stascorp/rdpwrap#1753]
![image](https://user-images.githubusercontent.com/100750080/156302774-24597f08-e8f2-4e3b-908c-ad9027b0a543.png)

**Comment by sebaxakerhtc** [comment]
RDPConf screenshot please

**Comment by Bryanyun** [comment]
![image](https://user-images.githubusercontent.com/100750080/156520698-453a8d53-4183-4c59-8d69-35cae683c4b2.png)

**Comment by sebaxakerhtc** [comment]
> ![image](https://user-images.githubusercontent.com/100750080/156520698-453a8d53-4183-4c59-8d69-35cae683c4b2.png)

Disable your antivirus and try again

**Comment by Bryanyun** [comment]
Uninstalled the antivirus software even disable all the Wins10 firewall and antivirus already but still the same

**Comment by sebaxakerhtc** [comment]
> Uninstalled the antivirus software even disable all the Wins10 firewall and antivirus already but still the same

Fully reinstall rdpwrapper and replace files or use my modded installer.
Then add rdpwrapper folder to exclusions

**Comment by Bryanyun** [comment]
Settled, thanks
