### ISSUE TITLE
rdp

### ISSUE THREAD

**Issue by gautamroy993** [stascorp/rdpwrap#1755]
hi I INSTALLED RDP V1.6.2. ITS DEFAULT RDPWARP.IN DATE IS 2018-10-10. IN THIS CONDATION MULTIUSER IS NOT WORKIN BUT LOCAL PRINTER IS REDIRACTING. WHEN I AM CHANGING RDPWARP.INN FILE FOR MULTI SESSION THAN MULTI USER IS WORKING BUT LOCAL PRINTER IS NOT REDIRACTING. SO WHAT I DO 
![WhatsApp Image 2022-03-03 at 2 34 32 PM](https://user-images.githubusercontent.com/100797182/156536548-c4f45d44-33a0-44ff-a3ec-7e5f06e03844.jpeg)
![WhatsApp Image 2022-03-03 at 2 40 21 PM](https://user-images.githubusercontent.com/100797182/156536561-1c244da2-1b59-4b8f-bd1e-32ba763e8232.jpeg)
![WhatsApp Image 2022-03-03 at 2 57 12 PM](https://user-images.githubusercontent.com/100797182/156536562-c6129d6a-a064-4584-904c-41eaeaba718f.jpeg)

**Comment by sashaqwert** [comment]
> BUT LOCAL PRINTER IS NOT REDIRACTING.

known issue.

Please, use Windows 10/11 Enterprise multi-session (ServerRdsh) for this (without RDP Wrapper).

<details>
<summary>More... (Offtopic)</summary>
ServerRdsh is not available on LTS.
To upgrade from non-LTS use command

```
slmgr.vbs /ipk CPWHC-NT2C7-VYW78-DHDB2-PG3GK
```

This works on Pro, enterprise, pro for..., 


</details>

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/504
