### ISSUE TITLE
wrapper state: not running

### ISSUE THREAD

**Issue by andychallis** [stascorp/rdpwrap#176]
found my Rdp wrapper was no longer working in the last few weeks so I have installed the latest 1.6.1 ver but when I run RDPConf I am still getting that rdp wrapper: not installed as below 
![image](https://cloud.githubusercontent.com/assets/22994624/19618108/93a60926-9839-11e6-9206-6d6e89e400a1.png)

**Comment by binarymaster** [comment]
Provide an installation log.

**Comment by andychallis** [comment]
where would this be ?- I have looked in the Program files\RDP Wrapper   folder .

**Comment by binarymaster** [comment]
Installation log is not a file, it's an output of installation process. Run installer and copy the log from command line.

**Comment by andychallis** [comment]
It doesn't seem to write any log data.
C:\Users\AdminAndy\Desktop\RDPWrap-v1.6.1>install
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

Press any key to continue . . .

C:\Users\AdminAndy\Desktop\RDPWrap-v1.6.1>

**Comment by binarymaster** [comment]
> It doesn't seem to write any log data.

True. This can be problem regarding your antivirus software.

**Comment by binarymaster** [comment]
So, the problem of this issue is installer not accessible (not starting).

@andychallis any news?

**Comment by andychallis** [comment]
Hi – I haven’t got the antivirus running at the moment. This is really annoying as it worked lovely when I came across this excellent patch utility at the start of the year – is it to do with the anniversary win 10 upgrade patch ?  looks like I will need to somehow manually patch the Termsvr file directly. 

 

Andrew

**Comment by binarymaster** [comment]
Try running the installer directly, without batch file:

`RDPWInst.exe -i -o`

**Comment by andychallis** [comment]
Thanks – it is working fine now .

 

Andrew

**Comment by f1sol** [comment]
> Try running the installer directly, without batch file:
> 
> `RDPWInst.exe -i -o`

**_Its Working 100% 
Thanks_**

**Comment by Michel-Araujo22** [comment]
> > Try running the installer directly, without batch file:
> > `RDPWInst.exe -i -o`
> 
> **_Its Working 100% Thanks_**

Saved me, thanks! Still working 100%
