### ISSUE TITLE
Not supported 19044.1586

### ISSUE THREAD

**Issue by ermannog** [stascorp/rdpwrap#1763]
After Windows Update on March 8, 2022—KB5011487. Thank you for your support in fixing this :-)

**Comment by gsvano** [comment]
https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Comment by ermannog** [comment]
Many thanks!

**Comment by ermannog** [comment]
Many thanks, I confirm that the ini file works!
