### ISSUE TITLE
Not supported on 10.0.19043.1586

### ISSUE THREAD

**Issue by Alien-ru323** [stascorp/rdpwrap#1767]
On Windows 10 21H1 OS assembly 19043.1586

**Comment by sashaqwert** [comment]
RDPConf screenshot, please!
You specified the Windows version instead of the version of `termsrv.dll`.  It can be found in RDPConf.

**Comment by Alien-ru323** [comment]
![image](https://user-images.githubusercontent.com/101459854/158062960-71f2e003-b06f-48c7-a0d9-cbe4e40c3e9d.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Comment by Alien-ru323** [comment]
Thanks!
