### ISSUE TITLE
win11 ver. 10.0.22000.469 only work locally 127.0.0.2 but unable access from another computer

### ISSUE THREAD

**Issue by guan7008** [stascorp/rdpwrap#1768]
win11 ver. 10.0.22000.469 only work locally 127.0.0.2 but unable access from another computer

**Comment by sashaqwert** [comment]
Please, check your firewall.
If your RDP port **≠** 3389, then you need open port manually.

**Comment by sebaxakerhtc** [comment]
Not a RDPWrapper issue. Check your firewall/network settings
