### ISSUE TITLE
10.0.19041.1566 Cant Open Searchbar and Microsoft Programs

### ISSUE THREAD

**Issue by zLight69** [stascorp/rdpwrap#1769]
10.0.19041.1566 Cant Open Searchbar and Microsoft Programs,like Ark from Xbox App

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1725

**Comment by sebaxakerhtc** [comment]
How RDPWrapper is applicable to this?

**Comment by zLight69** [comment]
I updatet all on my pc but it doenst work.
