### ISSUE TITLE
full supported but not listening

### ISSUE THREAD

**Issue by zzh8002** [stascorp/rdpwrap#1770]
update rdpwrap.ini at [#1022](https://github.com/stascorp/rdpwrap/issues/1022)， but still not working，execute "RDPWInst -r" shows "StartService error (code 1056)"
![image](https://user-images.githubusercontent.com/11305581/158095078-9905b4b4-f387-40dd-a732-531ce10ae21d.png)
![image](https://user-images.githubusercontent.com/11305581/158095113-351a916d-8cb9-4b1e-bcff-6d2d93f1ea28.png)

**Comment by sebaxakerhtc** [comment]
net start termservice
Try reboot. If termservice still not work - check your windows installation (chkdsk, etc)

**Comment by sebaxakerhtc** [comment]
This will helpful 
https://github.com/stascorp/rdpwrap/issues/1251#issuecomment-747427005
Not a RDPWrapper issue

**Comment by zzh8002** [comment]
> This will helpful [#1251 (comment)](https://github.com/stascorp/rdpwrap/issues/1251#issuecomment-747427005) Not a RDPWrapper issue

still not working...
![image](https://user-images.githubusercontent.com/11305581/158805780-22366197-03b8-4e11-97d9-b46bca58275d.png)
![image](https://user-images.githubusercontent.com/11305581/158805822-60c7bb6d-ad43-4a2b-8801-2c61f988b693.png)
