### ISSUE TITLE
Windows 10 Version 10.0.19041.1618 Not Supported

### ISSUE THREAD

**Issue by mz8080** [stascorp/rdpwrap#1772]
Please update the ini file for Windows 10 version 10.0.19041.1618

**Comment by sebaxakerhtc** [comment]
> Please update the ini file for Windows 10 version 10.0.19041.1618

Please attach your termsrv.dll

**Comment by mz8080** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8251496/termsrv.zip)

**Comment by sebaxakerhtc** [comment]
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/8251496/termsrv.zip)

There's no PDB file from M$

**Comment by sebaxakerhtc** [comment]
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/8251496/termsrv.zip)

Try it and let me know if it work for you
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/3a4c8451540d073851b62e894de0102461975929

**Comment by mz8080** [comment]
No it did not work, it is different from 10.0.19041.1566, however, I've restored the old termsrv.dll (version 1566) as a workaround and it's now working until 1618 is supported

**Comment by sebaxakerhtc** [comment]
> No it did not work, it is different from 10.0.19041.1566, however, I've restored the old termsrv.dll (version 1566) as a workaround and it's now working until 1618 is supported

I think you do something wrong.
Update your termsrv.dll to original one, replace your ini with my and show us rdpconf screenshot

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
