### ISSUE TITLE
RDP Wrapper 21h2 19042.1586

### ISSUE THREAD

**Issue by forms-Ali** [stascorp/rdpwrap#1774]
Do you have some update?
![image](https://user-images.githubusercontent.com/101677853/158488699-06331eb5-a168-493d-903b-9e8553785bca.png)

**Comment by ptomebr** [comment]
I also had this same problem after an update today

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725
