### ISSUE TITLE
New build Windows 10 Version 19044.1568 Not Supported

### ISSUE THREAD

**Issue by Stefpls** [stascorp/rdpwrap#1775]
The new Windows 10 build 19044.1568 is not supported. "rdpwrap.ini" file from dear sir sebaxakerhtc no longer works

**Comment by martnbee** [comment]
could it be 19044.1586  ?

**Comment by sebaxakerhtc** [comment]
> The new Windows 10 build 19044.1568 is not supported. "rdpwrap.ini" file from dear sir sebaxakerhtc no longer works

Rdpconf screenshot please

**Comment by sebaxakerhtc** [comment]
Looks like duplicate of https://github.com/stascorp/rdpwrap/issues/1725
But with error in Version

**Comment by Stefpls** [comment]
> could it be 19044.1586 ?

Yes! 19044.1586!
