### ISSUE TITLE
New build Windows 10 Version 19044.1586 Not Supported

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#1776]
Hi

I updated today to 19044.1586 version and it's not working.

I attach termsrv.dll file

Thanks
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8263357/termsrv.zip)
!

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725
