### ISSUE TITLE
10.0.19041.1566  ver. N/A

### ISSUE THREAD

**Issue by kwbj2212** [stascorp/rdpwrap#1777]
WHY
![1647517994(1)](https://user-images.githubusercontent.com/101806435/158803082-fcdbe6ea-0a73-43f5-9e93-f06ebd7e8151.png)

**Comment by Leao9203** [comment]
duplicate issue with #1725

**Comment by sashaqwert** [comment]
Does the `C:\Windows\System32\termsrv.dll` file exist?

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1725
