### ISSUE TITLE
RDP doesn't work  after update

### ISSUE THREAD

**Issue by SurenJaher** [stascorp/rdpwrap#1779]
Hi. I did everything as it was written earlier (changed rdpwrapper.ini ver.2022-03-17a and termsrv.dll) but it still doesn't work.
![Untitled](https://user-images.githubusercontent.com/101930300/159120004-c0207614-5806-45f8-984e-bdab6ab60cdf.jpg)

could you please help me

**Comment by sebaxakerhtc** [comment]
Recover your system, because on the 1586 you should have 1566 termsrv.dll. I think you replaced termsrv.dll manualy
Applicable to https://github.com/stascorp/rdpwrap/issues/1725
