### ISSUE TITLE
RDP WRAPPER CONFIG

### ISSUE THREAD

**Issue by MrDOntDIe** [stascorp/rdpwrap#1780]
![image](https://user-images.githubusercontent.com/101935753/159124146-2aa2a10f-0534-4292-ab36-351c7eb449c4.png)
 it wont listen and it isnt supported?

**Comment by MrDOntDIe** [comment]
well now the service state is green but nothin else

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725
