### ISSUE TITLE
Win10 X64 10.0.19041.1620 Not Supported

### ISSUE THREAD

**Issue by zekecarter** [stascorp/rdpwrap#1783]
**Added [termsrv.zip](https://github.com/stascorp/rdpwrap/files/8328767/termsrv.zip)**

![1](https://user-images.githubusercontent.com/83554130/159601229-265365e5-a7fb-452b-aca4-5b59dc985f83.png)

**Comment by ghost** [comment]
same here. autoupdate.bat is not updating it properly. i'm finished if i don't find this fix in 8 hours or so. help. please
![capture](https://user-images.githubusercontent.com/43813712/159610560-d5d2f664-2b91-472f-a691-ac23aca63f80.PNG)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8329154/termsrv.zip)
.

**Comment by ghost** [comment]
i got away with it uninstalling the new updates, and using the older one.

**Comment by sebaxakerhtc** [comment]
The offsets was added
No changes after 19041.1618
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/764d345ca3e3d90ac88fa43ba8b2b75ff64130a0

**Comment by ghost** [comment]
thanks a lot

**Comment by zekecarter** [comment]
Solved!!!
Thanks **sebaxakerhtc**

**Comment by ghost** [comment]
many thanks to all!
