### ISSUE TITLE
Cannot enable remote desktop after some days installed

### ISSUE THREAD

**Issue by phamlong1111** [stascorp/rdpwrap#1785]
Hello,
Now I'm facing the issue: "Remote Desktop can't connect to the remote computer for one of these reasons" from the client's PC after a few days installed rdpwrap and used normally.
I wonder this happened because windows update and made rdpwrap not work anymore or something went wrong in my network setting?
I tried all solutions I know as disabled firewall. change the remote port or even reinstall remote desktop service. But nothing worked.
Can someone help me? Thanks for advance
![error rdp](https://user-images.githubusercontent.com/47200890/159862711-85e58c20-89b5-4908-a3ec-d2901268a17a.JPG)
.

**Comment by sebaxakerhtc** [comment]
> Can someone help me?

Show us connection to 127.0.0.2, not to vmware

**Comment by phamlong1111** [comment]
> > Can someone help me?
> 
> Show us connection to 127.0.0.2, not to vmware

Thanks for your information. I realize there's an unstable switch inside the network. After reboot. everything fine

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - please reopen it
