### ISSUE TITLE
Fully Supported but Notlistening Windows 10 Ver 19041.1620 after update 

### ISSUE THREAD

**Issue by saivedasree** [stascorp/rdpwrap#1792]
![image](https://user-images.githubusercontent.com/102572944/160535649-85084e51-1626-485d-baec-c28310cacc29.png)
![image](https://user-images.githubusercontent.com/102572944/160535799-cbe191f1-7de8-426a-8c55-de0268b70b52.png)
**Please help this issue**

**Comment by sebaxakerhtc** [comment]
cmd as admin:
net start termservice
Applicable to https://github.com/stascorp/rdpwrap/issues/1786
