### ISSUE TITLE
Can't enable gpu hardware encoding

### ISSUE THREAD

**Issue by meowmeoe** [stascorp/rdpwrap#1795]
I'm using this since I'm on Windows 10 Home.  I'm trying to optimize RDP to get 60 fps, which can supposedly be done with Group Policy.  I managed to install gpedit on Home, but the Remote Desktop Service is missing from administrative templates.

![screenshot](https://user-images.githubusercontent.com/53866672/160737603-2fb0576b-ef38-4c6e-8f7a-204237c6308e.PNG)

Some people have said that it's actually under Terminal Services but it's not there either.

I have a Ryzen 5 3600 + RX560.

If it helps, I'm following these instructions from Linus Tech Tips:

What you need to do is enable some settings to activate the use of the hardware GPU instead of the default RDP emulated display software driver for RDP connections.

Computer Configuration -> Administrative Templates -> Windows Components -> Remote Desktop Services -> Remote Desktop Session Host -> Remote Session Environment

Set the following policies to Enable, to enable the use of the AVC/H.264 codec :

Configure H.264/AVC hardware encoding for Remote Desktop connections
Prioritize H.264/AVC 444 Graphics mode for Remote Desktop connections
Use the hardware default graphics adapter for all Remote Desktop Services sessions
Specifically, Use the hardware default graphics adapter for all Remote Desktop Services sessions will activate DirectX/OpenGL and the GPU over RDP

**Comment by sashaqwert** [comment]
Please, try launch Minecraft **JAVA** edition. This game is not works without gpu hardware encoding.

H.264 is Enabled by default with [modded RDP Wrapper](https://github.com/sebaxakerhtc/rdpwrap).

**Comment by sebaxakerhtc** [comment]
Not an rdpwrapper issue
Use google search on how to do that.
All works fine with this settings
![Снимок экрана 2022-03-30 в 11 47 31](https://user-images.githubusercontent.com/32651506/160791314-3fd21f87-941a-4023-94a9-67821cda8574.png)
You should just import these settings to Home version

**Comment by meowmeoe** [comment]
@sebaxakerhtc
I've searched everywhere on Google to find the Administrative Policy Templates.  I can't find the one for remote desktop.  What you're showing in your screenshot is what I'm looking for, but I don't know where those files are.  You already have them because you have Windows 10 Pro, but I don't.

**Comment by sebaxakerhtc** [comment]
> you have Windows 10 Pro, but I don't.

Install a clean Windows Pro in virtual machine, make changes you need, reboot.
Then backup group policy and restore in your Home version
