### ISSUE TITLE
Windows 10 10.0.19041.789 not support

### ISSUE THREAD

**Issue by chenyuxiangg** [stascorp/rdpwrap#1797]
Listener state: Not listening Not supported
Please add support for
Windows 10 10.0.19041.789

**Comment by sebaxakerhtc** [comment]
https://github.com/sebaxakerhtc/rdpwrap.ini/blob/8f4d2935fb544bce01b2c4ad32a9b8ecf8e40c68/rdpwrap.ini#L4616

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317
