### ISSUE TITLE
Win 11 Pro - 22000.593 Error

### ISSUE THREAD

**Issue by Razuken** [stascorp/rdpwrap#1800]
''the number of connections to this computer is limited'' this is the error
![1](https://user-images.githubusercontent.com/102856653/161378564-5e151fae-0711-4fd2-bed6-328de0be7744.png)

what .ini should i use to solve the problem ?

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1698
