### ISSUE TITLE
Windows 11 Home Edition ni_release 10.0.22579.1 DEV

### ISSUE THREAD

**Issue by AstralFlare-owo** [stascorp/rdpwrap#1802]
I'm finding about the rdpwrap.ini for Windows 11 Home Edition ni_release 10.0.22579.1.
Here's my "termsrv.ini" -> [termsrv.zip](https://github.com/sebaxakerhtc/rdpwrap.ini/files/8426767/termsrv.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1781

**Comment by sebaxakerhtc** [comment]
> Duplicate of #1781
