### ISSUE TITLE
RDP connections limit.

### ISSUE THREAD

**Issue by yokese01** [stascorp/rdpwrap#1806]
I have a Windows 10 ver. 21H2 - 19044.1620 and I need to open 20 RDP connections but it only lets me open 10 connections, when I try to open more than 10, I get the following error:

![RDP ERROR](https://user-images.githubusercontent.com/103435074/162841986-20a3ee82-8bdb-4c50-a7f1-9af098221444.png)

What am I doing wrong? It is not for insufficient resources, it is a Ryzen 5950X, 32GB and 3060TI 8GB. On my old PC with windows 7 I can open 20 RDP connections without problems and my old PC only has 8GB RAM with an i7-4930k and GTX 560TI.

I need to get over that limit of 10 connections, how do I do it? Thank you very much!!

**Comment by sebaxakerhtc** [comment]
There is a link to issue in the readme 
https://github.com/stascorp/rdpwrap/issues/192
