### ISSUE TITLE
not supported Win 10 21H1 19043.1645

### ISSUE THREAD

**Issue by xuxunjiang** [stascorp/rdpwrap#1808]
windows 10  19043.1645, request the latest version  [RDPwrap .ini],  thanks.

**Comment by sashaqwert** [comment]
RDPConf screenshot, please!

Your version is 10.0.1904**1**.XXX.
Please, see this in RDPConf and rename your issue.

**Comment by gasl20** [comment]
![2022-04-14_09h27_37](https://user-images.githubusercontent.com/66622710/163400842-a550b88a-8390-491a-b864-fa995d5d45b4.png)
![2022-04-14_09h27_17](https://user-images.githubusercontent.com/66622710/163400847-b3a98950-8b85-4035-9989-aaba7bc2025e.png)

**Comment by gasl20** [comment]
this helping for me
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1786

**Comment by sebaxakerhtc** [comment]
> Duplicate of #1786

**Comment by Jorge888812** [comment]
> this helping for me https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

tankyou
