### ISSUE TITLE
19043 1586 Service state: Unknown, wrapper state:3th party Issue

### ISSUE THREAD

**Issue by Alexxx79** [stascorp/rdpwrap#1809]
Today after upgrade Win 10 to version 19043 1645 RDP stop working, and I tried to delete and again install rdp wrapper folder, and now I have this issue. 
![image](https://user-images.githubusercontent.com/55318907/163357705-250c5ea0-c8a7-4d48-9097-0660143236ad.png)

Do You have suggestion what to do to repair again RDP? 
I have remotely few pc, and only for this one I have issue after upgrade. For others I just click on auto update and problem was solved.....

**Comment by sashaqwert** [comment]
RDP Wrapper deleted by antivirus.


try restore backup from original (clean) OS
Windows 10 21H1 [here](https://t.me/rdpwrap/38026)
Windows 11 21H2 [here](https://t.me/rdpwrap/40042)
Windows 10 LTSC 1809 [here](https://t.me/rdpwrap/41015)

**Comment by sashaqwert** [comment]
Most likely related to https://github.com/stascorp/rdpwrap/issues/1595

**Comment by CesarGRG** [comment]
I have de sam problema, somebody can help me? What is the process to restablish?

**Comment by Alexxx79** [comment]
> RDP Wrapper deleted by antivirus.
> 
> try restore backup from original (clean) OS Windows 10 21H1 [here](https://t.me/rdpwrap/38026) Windows 11 21H2 [here](https://t.me/rdpwrap/40042) Windows 10 LTSC 1809 [here](https://t.me/rdpwrap/41015)

I tried with registry changes, and now the situation is
![image](https://user-images.githubusercontent.com/55318907/163527248-241d4788-ef7c-4a90-aa3c-a233fd3aa4f0.png)
****

After that I tried to insert two files dll and Ini files from other PC and situation is
![image](https://user-images.githubusercontent.com/55318907/163527508-f8b43ee3-9342-4e0e-bcaf-db37d26fab40.png)

Rebooted PC, tried autoupdate, but nothing,autoupdate doesnt work, same situation as on preview screenshot.

After that, tried uninstall and it said
![image](https://user-images.githubusercontent.com/55318907/163529301-fa9226a5-dc3f-4ac6-a03b-9b722a1c4e08.png)
 So, I can not uninstall.....

**Comment by LeeWiu** [comment]
Exactly same issue here
![Screenshot 2022-04-15 142153](https://user-images.githubusercontent.com/1405188/163565446-92e1010e-abe3-44be-98bb-e9937d2e26eb.png)
![Screenshot 2022-04-15 142242](https://user-images.githubusercontent.com/1405188/163565449-d1e71e25-c992-429a-a6ec-cb0c0e37de56.png)
![Screenshot 2022-04-15 142323](https://user-images.githubusercontent.com/1405188/163565450-22cae8e3-9eb6-405e-85bd-7ec95f69acba.png)
![Screenshot 2022-04-15 142419](https://user-images.githubusercontent.com/1405188/163565453-9041fad8-2356-43b5-838d-c0457098a5f1.png)

**Comment by sebaxakerhtc** [comment]
You should to disable your antivirus before downloading and installing this software. 
Now you need to recover your system.
Not an RDPWrapper issue

**Comment by sashaqwert** [comment]
@TeHashX 

> Exactly same issue here

Please, use right click --> Run **as Administrator**

**Comment by LeeWiu** [comment]
I tryed running as admin, same.
I had whitelisted Rdp Wrapper in Bitdefender AntiVirus.
Which files was deleted? Can I copy / paste from another windows instalation?

**Comment by sebaxakerhtc** [comment]
> I tryed running as admin, same. I had whitelisted Rdp Wrapper in Bitdefender AntiVirus. Which files was deleted? Can I copy / paste from another windows instalation?

Yes. Write in official telegram

**Comment by Alexxx79** [comment]
> 

I have Bitdefender too on few pc and Rdpwrap is exluded and on white list. But only on one PC I got this specific issue. Probably Bitdefender made this issue in system with Teamservice.....

**Comment by jeinjhon2022** [comment]
Im same fail
![image](https://user-images.githubusercontent.com/103796488/163656342-bae4ce1a-37c4-48f8-a08f-1e29620966d2.png)

**Comment by Mashpi2022** [comment]
step 1

disable bitdefeder or any antivirus.

Step 2
the most important

Download the registers

Windows 10 21H1 here
Windows 11 21H2 here
Windows 10 LTSC 1809 here

the latter works with windows server 2016 / 2019

or restore the registers from a clean OS with rdpwrapp INSTALLED.

export and import on damaged OS


step 3
paste the rdpwrap.dll CLEAM

C:\Program Files\RDP Wrapper

now reboot the OS

Step 4

Check in services that the Terminal services is running, if not right click start

step 5

create the exception of the in the antivirus PATH

now rdpwrap is working, update the .ini file

and enjoy

**Comment by JJRoteG** [comment]
step 1

disable bitdefeder or any antivirus.

Step 2
the most important

Download the registers

Windows 10 21H1 here
Windows 11 21H2 here
Windows 10 LTSC 1809 here

the latter works with windows server 2016 / 2019

or restore the registers from a clean OS with rdpwrapp INSTALLED.

export and import on damaged OS


step 3
paste the rdpwrap.dll CLEAM

C:\Program Files\RDP Wrapper

now reboot the OS

Step 4

Check in services that the Terminal services is running, if not right click start

step 5

create the exception of the in the antivirus PATH

now rdpwrap is working, update the .ini file

and enjoy

**Comment by sashaqwert** [comment]
@JJRoteG 

> Download the registers
>
>Windows 10 21H1 [here](https://t.me/rdpwrap/38026)
Windows 11 21H2 [here](https://t.me/rdpwrap/40042)
Windows 10 LTSC 1809 [here](https://t.me/rdpwrap/41015)

Links are not saved.  Inserted in quote.
