### ISSUE TITLE
10.0.19044.1645 not supported

### ISSUE THREAD

**Issue by Saibot420** [stascorp/rdpwrap#1810]
[Termsrv.dll](https://drive.google.com/file/d/1Y9Gt58uiyWP1aFuPYppSFT7ZOE4Rzuwv/view?usp=sharing)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1808

**Comment by sebaxakerhtc** [comment]
> Duplicate of #1808
