### ISSUE TITLE
Apost Today's windows update stopped working

### ISSUE THREAD

**Issue by leonardo3dp** [stascorp/rdpwrap#1812]
A connection limit message appears
what do i need to do to get it working again

**Comment by sebaxakerhtc** [comment]
RDPConf screenshot? Version?

**Comment by UMU618** [comment]
Any one working on rdpwrap 10.0.22000.651?

**Comment by lvillalta10** [comment]
![issue with 19044 1645](https://user-images.githubusercontent.com/78506731/163678859-b5304e49-78f0-4d63-bf45-388360c11423.jpg)

It is the version of windows 19044.1645

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
