### ISSUE TITLE
10.0.22000.651

### ISSUE THREAD

**Issue by UMU618** [stascorp/rdpwrap#1815]
Still NOT work. Correct me:

```
[10.0.22000.651]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=991E1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=07144
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1BA15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=26E50
SLInitFunc.x64=New_CSLQuery_Initialize
```

**Comment by WeiguangYoung** [comment]
fully supported is ok, but listener state is not listening.

**Comment by sashaqwert** [comment]
@WeiguangYoung 

> listener state is not listening

Try `net start termService`

**Comment by WeiguangYoung** [comment]
I did it,and service state is running
![微信图片_20220417202306](https://user-images.githubusercontent.com/54520178/163714153-13a99341-6546-4f8f-b823-8f0e3691422a.png)
.

**Comment by UMU618** [comment]
It‘s working now

```
[10.0.22000.651]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=991E1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=18F22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1BA15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=26E50
SLInitFunc.x64=New_CSLQuery_Initialize
```

https://github.com/UMU618/rdpwrap.ini

**Comment by JosePeich** [comment]
With the new file the term service cannot start.

`[10.0.22000.651]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=991E1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=18F22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1BA15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=26E50
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22000.651-SLInit]
bInitialized.x64      =11FECC
bServerSku.x64        =11FED0
lMaxUserSessions.x64  =11FED4
bAppServerAllowed.x64 =11FEDC
bRemoteConnAllowed.x64=11FEE4
bMultimonAllowed.x64  =11FEE8
ulMaxDebugSessions.x64=11FEF0
bFUSEnabled.x64       =11FEF4`

**Comment by UMU618** [comment]
![image](https://user-images.githubusercontent.com/1729732/163770301-f8524796-f149-4e9b-8c55-fea1bbc46c1b.png)

**Comment by JosePeich** [comment]
I added the [10.0.22000.651-SLInit] part and then I try to restart terminal services. Terminal services won't restart. Maybe I'm doing something wrong...

<img width="761" alt="Captura de Pantalla 2022-04-18 a las 9 33 15" src="https://user-images.githubusercontent.com/1215017/163773959-faf4ffbd-583a-44f4-9641-abcaeafd170e.png">
.

**Comment by sebaxakerhtc** [comment]
> With the new file the term service cannot start

Attach your termsrv.dll - i will find the right offsets

**Comment by chbartel** [comment]
Was working fine until past few days, probably from a windows update.  I used the new ini file mentioned above, but I still get the error "the number of connections to this computer is limited and all connections are in use right now".  I pulled up the configuration program, everything looks to be fine??
![Screenshot - 4_18_2022 , 12_54_27 PM](https://user-images.githubusercontent.com/2926855/163843156-ba01da39-3a2b-4fc6-afe0-d64875234f68.png)

**Comment by chbartel** [comment]
I realized many of these are running windows 10.  I am running windows 11 and apparently, the DLL is different.  Here is mine from my system


[termsrv (2).zip](https://github.com/stascorp/rdpwrap/files/8508720/termsrv.2.zip)

**Comment by UMU618** [comment]
https://github.com/UMU618/rdpwrap.ini/blob/main/rdpwrap.ini

**Comment by UMU618** [comment]
1. Open Powershell as Administrators
2. Kill TermService
![image](https://user-images.githubusercontent.com/1729732/163955633-d2a98fea-8d32-4860-89bb-96f01731de09.png)
3. Download <https://raw.githubusercontent.com/UMU618/rdpwrap.ini/main/rdpwrap.ini> and replace your old rdpwrap.ini.
4. Start-Service TermService

**Comment by chbartel** [comment]
still same issue.  I used the first rdpwrap.ini file linked by umu618 and then the 2nd one linked with instructions, still getting same error message
![Screenshot - 4_19_2022 , 11_10_56 AM](https://user-images.githubusercontent.com/2926855/164036412-7e7bf192-c715-492c-b064-d8417c33d04d.png)
.

**Comment by UMU618** [comment]
![image](https://user-images.githubusercontent.com/1729732/164187170-cbfe583a-2f6e-4d76-9524-53dd18da5a21.png)

Should be the same

**Comment by UMU618** [comment]
> Was working fine until past few days, probably from a windows update. I used the new ini file mentioned above, but I still get the error "the number of connections to this computer is limited and all connections are in use right now". I pulled up the configuration program, everything looks to be fine?? ![Screenshot - 4_18_2022 , 12_54_27 PM](https://user-images.githubusercontent.com/2926855/163843156-ba01da39-3a2b-4fc6-afe0-d64875234f68.png)

Should use Default RDP Authentication or Network Level Authentication, GUI Authentication Only is insecure!

**Comment by UMU618** [comment]
@chbartel Would you try setting exactly the same as me?
![https://github.com/stascorp/rdpwrap/issues/1815#issuecomment-1101164367](https://user-images.githubusercontent.com/1729732/163770301-f8524796-f149-4e9b-8c55-fea1bbc46c1b.png)

**Comment by chbartel** [comment]
just bizarre, I tried running as you have setup, same error message.  Here is screen shot of my termsrv.dl
![Screenshot - 4_20_2022 , 9_37_10 AM](https://user-images.githubusercontent.com/2926855/164243115-2616fb0c-5547-4084-bb14-127f9b89ba48.png)
l

**Comment by chbartel** [comment]
I ran the uninstall file, rebooted, reinstalled from command line to see what errors if any came up.  It came up with termserver error, probably because of the old ini file?  I stopped desktop services, installed the new ini file in program files directly, restarted services, still same error.

**Comment by chbartel** [comment]
I don't know if this matters or not, but I am trying to log in as a different user on the same machine I am on.  No issues doing that until the past few weeks after the windows 11 update.
