### ISSUE TITLE
The ver. is N/A

### ISSUE THREAD

**Issue by resistzzz** [stascorp/rdpwrap#1817]
![image](https://user-images.githubusercontent.com/23613588/163960093-fa53b235-0bdd-4f28-a955-518c1981af31.png)

**Comment by sebaxakerhtc** [comment]
Check if file termsrv.dll was deleted by your antivirus

**Comment by resistzzz** [comment]
> Check if file termsrv.dll was deleted by your antivirus

I have checked that the file termsrv.dll is under the path C:\Windows\System32 as follows:
![image](https://user-images.githubusercontent.com/23613588/164033581-5ca1e79e-6dfe-4c16-8263-e6db025877a9.png)
Windows 10 was updated the other day.  I feel this is the reason, but I don't know how to solve it.

**Comment by sebaxakerhtc** [comment]
> Windows 10 was updated the other day. I feel this is the reason, but I don't know how to solve it.

Try reboot

**Comment by resistzzz** [comment]
> 
I have tried several times, It didn't work.

**Comment by lkhjzw** [comment]
I have a same problem.And The same result after replacing the termsrv.dll file

**Comment by sebaxakerhtc** [comment]
> I have checked that the file termsrv.dll is under the path C:\Windows\System32

Can you attach your termsrv.dll?

**Comment by resistzzz** [comment]
> Of course! Thank you very much! Since uploading the .dll file is not supported,  I copy the contents of termsrv.dll into the termsrv.txt file as follows:
[termsrv.txt](https://github.com/stascorp/rdpwrap/files/8526889/termsrv.txt)

**Comment by resistzzz** [comment]
> I have a same problem.And The same result after replacing the termsrv.dll file
Have you solved the problem yet?

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1814

**Comment by lkhjzw** [comment]
> > I have a same problem.And The same result after replacing the termsrv.dll file
> > Have you solved the problem yet?

Not yet. I think 我们还是用中文吧，微信加一个？以后有问题可以聊聊？

**Comment by lytning98** [comment]
I have the same problem and just solved by checking the version from output given by `install.bat`. Run this script (with admin) and there will be a line like `Terminal version 10.x.x.xxxxx` in the output. Get the `rdpwrap.ini` file corresponding to this version makes the wrapper work fine. Though it still shows `N/A` version (check the screenshot below).

<img width="329" alt="image" src="https://user-images.githubusercontent.com/23375707/167339266-7021d57a-b710-4992-bed1-9d4d4062adae.png">

Hope that can help you guys. @resistzzz  @lkhjzw

**Comment by ariexlin** [comment]
> I have the same problem and just solved by checking the version from output given by `install.bat`. Run this script (with admin) and there will be a line like `Terminal version 10.x.x.xxxxx` in the output. Get the `rdpwrap.ini` file corresponding to this version makes the wrapper work fine. Though it still shows `N/A` version (check the screenshot below).
> 
> <img alt="image" width="329" src="https://user-images.githubusercontent.com/23375707/167339266-7021d57a-b710-4992-bed1-9d4d4062adae.png">
> 
> Hope that can help you guys. @resistzzz @lkhjzw

you are right, thanks for your help.
