### ISSUE TITLE
All RDP Wrapper gone after update

### ISSUE THREAD

**Issue by xenan33** [stascorp/rdpwrap#1818]
Hi Guys,

Anyone having issues with RDPWrapper after the update.

Diagnostic shows:
Wrapper State: not installed
Service state: stopped
Listener state: not listening
Ver: N/A
Ver: 10.0.19041.1566

When attemping to run the install.bat it gives an error:
[-] StartService error (code 1053).
[-] Failed to set up TermService. Unknown error.

Anyone encounter like this?

Current Win 10 Ver 21H2

We've tried a lot of troubleshooting, checked forums on how to fix this but wondering if anyone has any luck in resolving this?
When starting Remote desktop service we get "error 1053 the service did not respond to the start or control request in a timely fashion"

Also replaced the Termservc.dll of the machine with another Termservc.dll from another working machine that has the same Windows version, only difference is we just recently install RDPWrapper on the other machine for testing..

Any help would be appreciated.

PS, no AV, no firewall is on the machine, we've removed and disable them for testing
Update:
We managed to make the Wrapper state and the version green but we're still not able to make the service state and listener state to work..

![image](https://user-images.githubusercontent.com/79400803/164254922-84f1e963-016d-4416-b52c-5c703405b62c.png)

**Comment by mrvanity** [comment]
I am facing the same issue.
 Please check if under services you see a service called "Remote Desktop Services" exists 
 and if the registry key 
 Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService
is missing.

**Comment by mrvanity** [comment]
I was missing Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService

I recreated it with the following.

Open notepad and save the following as "TermService.reg"
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService]
"DependOnService"=hex(7):52,00,50,00,43,00,53,00,53,00,00,00,00,00
"Description"="@%SystemRoot%\\System32\\termsrv.dll,-267"
"DisplayName"="@%SystemRoot%\\System32\\termsrv.dll,-268"
"ErrorControl"=dword:00000001
"FailureActions"=hex:80,51,01,00,00,00,00,00,00,00,00,00,03,00,00,00,14,00,00,\
  00,01,00,00,00,60,ea,00,00,01,00,00,00,60,ea,00,00,00,00,00,00,60,ea,00,00
"ImagePath"=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,\
  74,00,25,00,5c,00,53,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,73,\
  00,76,00,63,00,68,00,6f,00,73,00,74,00,2e,00,65,00,78,00,65,00,20,00,2d,00,\
  6b,00,20,00,4e,00,65,00,74,00,77,00,6f,00,72,00,6b,00,53,00,65,00,72,00,76,\
  00,69,00,63,00,65,00,00,00
"ObjectName"="NT Authority\\NetworkService"
"RequiredPrivileges"=hex(7):53,00,65,00,41,00,73,00,73,00,69,00,67,00,6e,00,50,\
  00,72,00,69,00,6d,00,61,00,72,00,79,00,54,00,6f,00,6b,00,65,00,6e,00,50,00,\
  72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,53,00,65,00,41,00,75,\
  00,64,00,69,00,74,00,50,00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,\
  00,00,53,00,65,00,43,00,68,00,61,00,6e,00,67,00,65,00,4e,00,6f,00,74,00,69,\
  00,66,00,79,00,50,00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,\
  53,00,65,00,43,00,72,00,65,00,61,00,74,00,65,00,47,00,6c,00,6f,00,62,00,61,\
  00,6c,00,50,00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,53,00,\
  65,00,49,00,6d,00,70,00,65,00,72,00,73,00,6f,00,6e,00,61,00,74,00,65,00,50,\
  00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,53,00,65,00,49,00,\
  6e,00,63,00,72,00,65,00,61,00,73,00,65,00,51,00,75,00,6f,00,74,00,61,00,50,\
  00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,00,00
"ServiceSidType"=dword:00000001
"Start"=dword:00000003
"Type"=dword:00000020

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters]
"ServiceDll"=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,\
  00,74,00,25,00,5c,00,53,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,\
  74,00,65,00,72,00,6d,00,73,00,72,00,76,00,2e,00,64,00,6c,00,6c,00,00,00
"ServiceDllUnloadOnStop"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Performance]
"Close"="CloseTSObject"
"Collect"="CollectTSObjectData"
"Collect Timeout"=dword:000003e8
"Library"="C:\\Windows\\System32\\perfts.dll"
"Open"="OpenTSObject"
"Open Timeout"=dword:000003e8
"InstallType"=dword:00000001
"PerfIniFile"="tslabels.ini"
"First Counter"=dword:00000e80
"Last Counter"=dword:00000e80
"First Help"=dword:00000e81
"Last Help"=dword:00000e81
"Object List"="3712"

Import it , and reboot

**Comment by xenan33** [comment]
> I was missing Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService
> 
> I recreated it with the following.
> 
> Open notepad and save the following as "TermService.reg" Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService] "DependOnService"=hex(7):52,00,50,00,43,00,53,00,53,00,00,00,00,00 "Description"="@%SystemRoot%\System32\termsrv.dll,-267" "DisplayName"="@%SystemRoot%\System32\termsrv.dll,-268" "ErrorControl"=dword:00000001 "FailureActions"=hex:80,51,01,00,00,00,00,00,00,00,00,00,03,00,00,00,14,00,00, 00,01,00,00,00,60,ea,00,00,01,00,00,00,60,ea,00,00,00,00,00,00,60,ea,00,00 "ImagePath"=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00, 74,00,25,00,5c,00,53,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,73, 00,76,00,63,00,68,00,6f,00,73,00,74,00,2e,00,65,00,78,00,65,00,20,00,2d,00, 6b,00,20,00,4e,00,65,00,74,00,77,00,6f,00,72,00,6b,00,53,00,65,00,72,00,76, 00,69,00,63,00,65,00,00,00 "ObjectName"="NT Authority\NetworkService" "RequiredPrivileges"=hex(7):53,00,65,00,41,00,73,00,73,00,69,00,67,00,6e,00,50, 00,72,00,69,00,6d,00,61,00,72,00,79,00,54,00,6f,00,6b,00,65,00,6e,00,50,00, 72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,53,00,65,00,41,00,75, 00,64,00,69,00,74,00,50,00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00, 00,00,53,00,65,00,43,00,68,00,61,00,6e,00,67,00,65,00,4e,00,6f,00,74,00,69, 00,66,00,79,00,50,00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00, 53,00,65,00,43,00,72,00,65,00,61,00,74,00,65,00,47,00,6c,00,6f,00,62,00,61, 00,6c,00,50,00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,53,00, 65,00,49,00,6d,00,70,00,65,00,72,00,73,00,6f,00,6e,00,61,00,74,00,65,00,50, 00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,53,00,65,00,49,00, 6e,00,63,00,72,00,65,00,61,00,73,00,65,00,51,00,75,00,6f,00,74,00,61,00,50, 00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,00,00 "ServiceSidType"=dword:00000001 "Start"=dword:00000003 "Type"=dword:00000020
> 
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters] "ServiceDll"=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f, 00,74,00,25,00,5c,00,53,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00, 74,00,65,00,72,00,6d,00,73,00,72,00,76,00,2e,00,64,00,6c,00,6c,00,00,00 "ServiceDllUnloadOnStop"=dword:00000001
> 
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Performance] "Close"="CloseTSObject" "Collect"="CollectTSObjectData" "Collect Timeout"=dword:000003e8 "Library"="C:\Windows\System32\perfts.dll" "Open"="OpenTSObject" "Open Timeout"=dword:000003e8 "InstallType"=dword:00000001 "PerfIniFile"="tslabels.ini" "First Counter"=dword:00000e80 "Last Counter"=dword:00000e80 "First Help"=dword:00000e81 "Last Help"=dword:00000e81 "Object List"="3712"
> 
> Import it , and reboot

I tried that, still getting that weird 1053 error when starrting remote desktop services service, the diagnost on config still shows the same :/

**Comment by ashkannrz** [comment]
well, there is a bad news 
there is no way to repair 
registry import not work
windows repair not work
DLL check not work 

the 1053 error is like blue screen 

I work with it since last week and there is no way 
only way is to reset pc or re install windows

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1814

**Comment by rtomik** [comment]
have the same issue did anyone fix it?

**Comment by xenan33** [comment]
> have the same issue did anyone fix it?

You just need to go to the Microsoft Website. Download the Media Creation Tool to create ISO file for the Windows Repair. 

This is the link https://www.microsoft.com/en-us/software-download/windows10?msclkid=a81c9052c12111ec9196f7a3aee6bd0e 


Download Windows 10
https://www.microsoft.com

**Comment by Doublix** [comment]
@ahskan21 : it possible to repair without reinstalling. It seems you have done point 1 & 2, so check point 3.

1. Solve the problem with the antivirus : put rdpwrap.dll as an exception (see https://github.com/stascorp/rdpwrap/issues/18)

2. If the termservice service has disapeared (no termservice in services.msc), follow the advice of  mrvanity : add the missing keys in the registry that mrvanity has given above (or you can download them here : https://www.tenforums.com/attachments/tutorials/92506d1469658281-services-restore-default-services-windows-10-a-remote_desktop_services.reg).

3. Check also the two following keys where termservice may have disappeared :

a)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Svchost
This key has a value "Networkservice". The data for this value should be : 
CryptSvc WinRM WECSVC DHCP TermService DNSCache Tapisrv
If Termservice is missing, add it to the list

b)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Svchost
This key has a value "Networkservice". The data for this value should be : 
CryptSvc nlasvc lanmanworkstation WinRM WECSVC dosvc MapsBroker DHCP TermService DNSCache Tapisrv
If Termservice is also missing, add it to the list.

And Restart.

**Comment by ashkannrz** [comment]
> @ahskan21 : it possible to repair without reinstalling. It seems you have done point 1 & 2, so check point 3.
> 
> 1. Solve the problem with the antivirus : put rdpwrap.dll as an exception (see [Strange intermittent "hanging" issue #18](https://github.com/stascorp/rdpwrap/issues/18))
> 2. If the termservice service has disapeared (no termservice in services.msc), follow the advice of  mrvanity : add the missing keys in the registry that mrvanity has given above (or you can download them here : https://www.tenforums.com/attachments/tutorials/92506d1469658281-services-restore-default-services-windows-10-a-remote_desktop_services.reg).
> 3. Check also the two following keys where termservice may have disappeared :
> 
> a)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Svchost This key has a value "Networkservice". The data for this value should be : CryptSvc WinRM WECSVC DHCP TermService DNSCache Tapisrv If Termservice is missing, add it to the list
> 
> b)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Svchost This key has a value "Networkservice". The data for this value should be : CryptSvc nlasvc lanmanworkstation WinRM WECSVC dosvc MapsBroker DHCP TermService DNSCache Tapisrv If Termservice is also missing, add it to the list.
> 
> And Restart.

this works verywell thanks

**Comment by rtomik** [comment]
> @ahskan21 : it possible to repair without reinstalling. It seems you have done point 1 & 2, so check point 3.
> 
> 1. Solve the problem with the antivirus : put rdpwrap.dll as an exception (see [Strange intermittent "hanging" issue #18](https://github.com/stascorp/rdpwrap/issues/18))
> 2. If the termservice service has disapeared (no termservice in services.msc), follow the advice of  mrvanity : add the missing keys in the registry that mrvanity has given above (or you can download them here : https://www.tenforums.com/attachments/tutorials/92506d1469658281-services-restore-default-services-windows-10-a-remote_desktop_services.reg).
> 3. Check also the two following keys where termservice may have disappeared :
> 
> a)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Svchost This key has a value "Networkservice". The data for this value should be : CryptSvc WinRM WECSVC DHCP TermService DNSCache Tapisrv If Termservice is missing, add it to the list
> 
> b)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Svchost This key has a value "Networkservice". The data for this value should be : CryptSvc nlasvc lanmanworkstation WinRM WECSVC dosvc MapsBroker DHCP TermService DNSCache Tapisrv If Termservice is also missing, add it to the list.
> 
> And Restart.

thanks it works

**Comment by techinova-ti** [comment]
> @ahskan21 : it possible to repair without reinstalling. It seems you have done point 1 & 2, so check point 3.
> 
> 1. Solve the problem with the antivirus : put rdpwrap.dll as an exception (see [Strange intermittent "hanging" issue #18](https://github.com/stascorp/rdpwrap/issues/18))
> 2. If the termservice service has disapeared (no termservice in services.msc), follow the advice of  mrvanity : add the missing keys in the registry that mrvanity has given above (or you can download them here : https://www.tenforums.com/attachments/tutorials/92506d1469658281-services-restore-default-services-windows-10-a-remote_desktop_services.reg).
> 3. Check also the two following keys where termservice may have disappeared :
> 
> a)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Svchost This key has a value "Networkservice". The data for this value should be : CryptSvc WinRM WECSVC DHCP TermService DNSCache Tapisrv If Termservice is missing, add it to the list
> 
> b)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Svchost This key has a value "Networkservice". The data for this value should be : CryptSvc nlasvc lanmanworkstation WinRM WECSVC dosvc MapsBroker DHCP TermService DNSCache Tapisrv If Termservice is also missing, add it to the list.
> 
> And Restart.

Thanks!

**Comment by groupe-itc** [comment]
Thanks for the steps to reinstall the service! Worked really well!

**Comment by Feriwa** [comment]
> @ahskan21 : it possible to repair without reinstalling. It seems you have done point 1 & 2, so check point 3.
> 
> 1. Solve the problem with the antivirus : put rdpwrap.dll as an exception (see [Strange intermittent "hanging" issue #18](https://github.com/stascorp/rdpwrap/issues/18))
> 2. If the termservice service has disapeared (no termservice in services.msc), follow the advice of  mrvanity : add the missing keys in the registry that mrvanity has given above (or you can download them here : https://www.tenforums.com/attachments/tutorials/92506d1469658281-services-restore-default-services-windows-10-a-remote_desktop_services.reg).
> 3. Check also the two following keys where termservice may have disappeared :
> 
> a)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Svchost This key has a value "Networkservice". The data for this value should be : CryptSvc WinRM WECSVC DHCP TermService DNSCache Tapisrv If Termservice is missing, add it to the list
> 
> b)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Svchost This key has a value "Networkservice". The data for this value should be : CryptSvc nlasvc lanmanworkstation WinRM WECSVC dosvc MapsBroker DHCP TermService DNSCache Tapisrv If Termservice is also missing, add it to the list.
> 
> And Restart.

Thanks it worked. Bitdefender killed my Term Service...

**Comment by osmicro3301** [comment]
> This key has a value "Networkservice". The data for this value should be :
> CryptSvc WinRM WECSVC DHCP TermService DNSCache Tapisrv
> If Termservice is missing, add it to the list

Mate what does this part mean? I can't see any values that match any of these under this key?

**Comment by Doublix** [comment]
@osmicro3301 - Hello. The registry keys listed are correct for Windows 10 64 bits (either pro and home). You can look at the attached picture.
![Registry](https://user-images.githubusercontent.com/104534343/183771373-8b532f99-f952-4496-9787-ee9fd7064189.JPG)
.

**Comment by osmicro3301** [comment]
> @osmicro3301 - Hello. The registry keys listed are correct for Windows 10 64 bits (either pro and home). You can look at the attached picture. ![Registry](https://user-images.githubusercontent.com/104534343/183771373-8b532f99-f952-4496-9787-ee9fd7064189.JPG) .

I love you! You have just saved us a 300km trip to re format this machine! It worked! Thank you very very much!

**Comment by warning0810** [comment]
> @ahskan21 : it possible to repair without reinstalling. It seems you have done point 1 & 2, so check point 3.
> 
>     1. Solve the problem with the antivirus : put rdpwrap.dll as an exception (see [Strange intermittent "hanging" issue #18](https://github.com/stascorp/rdpwrap/issues/18))
> 
>     2. If the termservice service has disapeared (no termservice in services.msc), follow the advice of  mrvanity : add the missing keys in the registry that mrvanity has given above (or you can download them here : https://www.tenforums.com/attachments/tutorials/92506d1469658281-services-restore-default-services-windows-10-a-remote_desktop_services.reg).
> 
>     3. Check also the two following keys where termservice may have disappeared :
> 
> 
> a)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Svchost This key has a value "Networkservice". The data for this value should be : CryptSvc WinRM WECSVC DHCP TermService DNSCache Tapisrv If Termservice is missing, add it to the list
> 
> b)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Svchost This key has a value "Networkservice". The data for this value should be : CryptSvc nlasvc lanmanworkstation WinRM WECSVC dosvc MapsBroker DHCP TermService DNSCache Tapisrv If Termservice is also missing, add it to the list.
> 
> And Restart.

Thank you man! You are great :)

**Comment by sightkick** [comment]
> > @ahskan21 : it possible to repair without reinstalling. It seems you have done point 1 & 2, so check point 3.
> > 
> > 1. Solve the problem with the antivirus : put rdpwrap.dll as an exception (see [Strange intermittent "hanging" issue #18](https://github.com/stascorp/rdpwrap/issues/18))
> > 2. If the termservice service has disapeared (no termservice in services.msc), follow the advice of  mrvanity : add the missing keys in the registry that mrvanity has given above (or you can download them here : https://www.tenforums.com/attachments/tutorials/92506d1469658281-services-restore-default-services-windows-10-a-remote_desktop_services.reg).
> > 3. Check also the two following keys where termservice may have disappeared :
> > 
> > a)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Svchost This key has a value "Networkservice". The data for this value should be : CryptSvc WinRM WECSVC DHCP TermService DNSCache Tapisrv If Termservice is missing, add it to the list
> > b)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Svchost This key has a value "Networkservice". The data for this value should be : CryptSvc nlasvc lanmanworkstation WinRM WECSVC dosvc MapsBroker DHCP TermService DNSCache Tapisrv If Termservice is also missing, add it to the list.
> > And Restart.
> 
> Thanks it worked. Bitdefender killed my Term Service...

Bitdefender killed mine, too. This reg file helped and everything works again. Did you find any way to get Bitdefender work with an exclusion? I deleted it and use defender now. But that´s not the right way

**Comment by accnetdev** [comment]
Hi,
I use RDP Wrapper (last sebaxakerhtc version) a very handy and reliable tool.

Today I noticed there is no longer the termservice on this PC under Windows 11.
I'm on Microsoft Windows [version 10.0.22631.4602] my Antivirus ESET EndPoint Security 12.0.2038.0 is OK (nothing in history related to TermService or RDPWrapper) but I found several "Incomplete update" in Defender history related to the TermService.

I suppose that Defender has deleted my TermService after several detections of HackTool:Win32/RemoteAdmin!MSR, it's new because before dec 16 2024 there was no problem with this kind of detections.

My problem is : how to restore my TermService that has disapeared?
My OS is Windows 11 Pro 23H2 (18/11/2022 - 22631.4602) can you give the registry item to add/restore for Win11?

Thanks for your help.

**Comment by accnetdev** [comment]
To help the community the reg (for Win10) in this topic is OK for Windows 11 (upto my actual version).
I applied/import the reg + reboot the TermService is now in services.msc.
I reinstalled seba/rdpwrapper and all is OK now.
Be careful Defender is probably the cause even if you use another antimalware like me ESET as the main AV...
