### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by TashaSkyUp** [stascorp/rdpwrap#182]
The RDPCheck.exe program works but connecting via RDP.exe does not.
nevermind it looks like it setup the rdp to listen on 127.0.0.2 Why? And how would I know?

**Comment by binarymaster** [comment]
Don't know what is `RDP.exe` application you mentioned.

> nevermind it looks like it setup the rdp to listen on 127.0.0.2 Why? And how would I know?

RDP listens on 0.0.0.0 by default. You can use `netstat -an` to see actual listening interface.
