### ISSUE TITLE
Service state Stopped & Listener State Not Listening in Windows 11

### ISSUE THREAD

**Issue by kkm5848** [stascorp/rdpwrap#1820]
![image](https://user-images.githubusercontent.com/28168589/164783205-cefb286e-58f5-448b-9433-3384bc441607.png)

I ran sc query termservice and got the following error

SERVICE_NAME: TermService
TYPE : 30 WIN32
STATE : 1 STOPPED
WIN32_EXIT_CODE : 126 (0x7e)
SERVICE_EXIT_CODE : 0 (0x0)
CHECKPOINT : 0x0
WAIT_HINT : 0x0

I am running Windows 11 21H2 OS Build 22000.613

I have run sfc /scannow and it found no integrity violations.  I ran a "Quick Scan" in Windows Defender and found no issues as well.

I tried manually turning on windows terminal services but was unable to.  

![image](https://user-images.githubusercontent.com/28168589/164783307-b7dfec54-03fc-4dbc-b737-16860ba88f24.png)

I also can't uninstall it:
![image](https://user-images.githubusercontent.com/28168589/164783445-1d0f9dc3-a46c-48c6-9e07-97eb5227e584.png)

**Comment by kkm5848** [comment]
BTW, this was working 2 days ago...but stopped working after windows crashed last night and rebooted.

**Comment by xenan33** [comment]
> BTW, this was working 2 days ago...but stopped working after windows crashed last night and rebooted.

Had that exact issue on win 10, I had to download a latest iso that contains current or latest feature and do an in-place update, and it work.

**Comment by kkm5848** [comment]
I don't understand what that means.  I tried downloaded the Dell recovery USB image and it did nothing.  Window's doesn't find any errors as well.  

Did you update the overall OS or did you find a way to get the termsrv.dll and reinstall just that part or something else?

**Comment by kkm5848** [comment]
I found the following in the Terminal Services-LocalSessionManager Operational event log:
![image](https://user-images.githubusercontent.com/28168589/165194531-13704181-1b08-4ba0-b4c2-2fe61a59dba6.png)

**Comment by sebaxakerhtc** [comment]
Looks like you haven't Network Devices, but choose NLA

**Comment by kkm5848** [comment]
I don't understand...the screenshot above (settings dialog) shows NLA is not clicked.

**Comment by sebaxakerhtc** [comment]
> I don't understand...the screenshot above (settings dialog) shows NLA is not clicked.

Check if your antivirus software blocked/deleted files of rdpwrapper.
On your screenshot wrapper state is N/A

**Comment by xenan33** [comment]
> I don't understand what that means. I tried downloaded the Dell recovery USB image and it did nothing. Window's doesn't find any errors as well.
> 
> Did you update the overall OS or did you find a way to get the termsrv.dll and reinstall just that part or something else?

Wait, before I answer, can you check if your remote desktop service services is disabled on services.msc? and can you confirm if you are getting 1053 error when you run it?

**Comment by kkm5848** [comment]
I get error 126.
![image](https://user-images.githubusercontent.com/28168589/165798696-fea5235a-49b1-46d6-9d84-5f06bc67a8aa.png)

**Comment by kkm5848** [comment]
Any thoughts @xenan33 ?

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1883

**Comment by kkm5848** [comment]
The fix on https://github.com/stascorp/rdpwrap/issues/1883 worked for me !

**Comment by kkm5848** [comment]
Did you have to just ‘repair’ windows?

Krishna


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amandhanawat** [comment]
> ![image](https://user-images.githubusercontent.com/28168589/164783205-cefb286e-58f5-448b-9433-3384bc441607.png)
> 
> I ran sc query termservice and got the following error
> 
> SERVICE_NAME: TermService TYPE : 30 WIN32 STATE : 1 STOPPED WIN32_EXIT_CODE : 126 (0x7e) SERVICE_EXIT_CODE : 0 (0x0) CHECKPOINT : 0x0 WAIT_HINT : 0x0
> 
> I am running Windows 11 21H2 OS Build 22000.613
> 
> I have run sfc /scannow and it found no integrity violations. I ran a "Quick Scan" in Windows Defender and found no issues as well.
> 
> I tried manually turning on windows terminal services but was unable to.
> 
> ![image](https://user-images.githubusercontent.com/28168589/164783307-b7dfec54-03fc-4dbc-b737-16860ba88f24.png)
> 
> I also can't uninstall it: ![image](https://user-images.githubusercontent.com/28168589/164783445-1d0f9dc3-a46c-48c6-9e07-97eb5227e584.png)

Same issue please help

**Comment by amandhanawat** [comment]
Same issue please help
