### ISSUE TITLE
RDPWrapper was Working - Windows stack update 19041.1603 (and/or Bitdefender) stopped RDP service

### ISSUE THREAD

**Issue by makdee88** [stascorp/rdpwrap#1821]
My windows 10 server was working fine until 14th April. When a windows update happened and it created a nightmare for me.
![image](https://user-images.githubusercontent.com/11515433/164887313-332cf09a-aca7-464b-b867-e44900662243.png)

The RDP stopped working. RDP service itself is not starting.

```
C:\Windows\system32>sc query TermService

SERVICE_NAME: TermService
        TYPE               : 30  WIN32
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0

C:\Windows\system32>
```
I tried to find the error in event viewer, the furthest I can find is the below error:
**In systems log:**
_The Remote Desktop Services service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion._

**In TermServices-LocalSessionManager log:**
_Remote Desktop Service start failed. The relevant status code was 0x8007041D._

**Finally, I have done SFC scan.**

```
C:\Windows\system32>sfc /scannow

Beginning system scan.  This process will take some time.

Beginning verification phase of system scan.
Verification 100% complete.

Windows Resource Protection did not find any integrity violations.

C:\Windows\system32>
C:\Windows\system32>
```

Cherry on the top, Bitdefender decided to quarantine RDPWrap.dll from RDPWrapper folder inside Programs File.
I have tried restoring the DLL from Bitdefender quarantine. It got restored but issue did not got fixed.
Now install.bat, uninstall.bat does not work either. Refer the output below.

```
C:\Users\starm\Downloads\RDPWrap-v1.6.2>install.bat
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.19041.1620
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[*] Configuring TermService...
[*] Starting TermService...
[-] StartService error (code 1053).
[-] Failed to set up TermService. Unknown error.
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

Press any key to continue . . .

C:\Users\starm\Downloads\RDPWrap-v1.6.2>update.bat
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] RDP Wrapper Library is not installed.

Press any key to continue . . .

C:\Users\starm\Downloads\RDPWrap-v1.6.2>
C:\Users\starm\Downloads\RDPWrap-v1.6.2>RDPWInst -w
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] RDP Wrapper Library is not installed.

C:\Users\starm\Downloads\RDPWrap-v1.6.2>
```

I was going trough countless documents in past 7-10 days to find whats causing this. Could not understand it.
I have changed: Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters to %SystemRoot%\System32\termsrv.dll in the hope that RDPWrapper is causing the problem.
![image](https://user-images.githubusercontent.com/11515433/164887366-326fd378-8c54-41fb-84f9-5f82c49bde9e.png)
![image](https://user-images.githubusercontent.com/11515433/164887374-5b955fe5-22d9-49b3-9c7e-366a0b3d0bd6.png)

**Comment by makdee88** [comment]
Can anyone help me? I am in desperate need.

**Comment by GeorgiTz** [comment]
Hi, I have just the same issue. I think the problem was generated by Bitdefender cause I use the same program. I think that Bitdefender deleted some registry entries so the termsrv,dll can't start. My key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService was erased and I restored the content from internet. Now I'm trying to restore functionality.

**Comment by makdee88** [comment]
You are right on point. I have restored the entries in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService from the internet as well(forgot to mention). It seems to me Bitdefender is the culprit here.

Attaching the reg keys. I have also verified all keys with a system where the RDP service works fine. Could not see a difference. 

[win10reg.txt](https://github.com/stascorp/rdpwrap/files/8555174/win10reg.txt)

**Comment by GeorgiTz** [comment]
I found just the same keys so my registry show the same lines. Now I'll make backup of Windows and will try restore point from 13.04.2022. Other thing is to try DISM /Online /Cleanup-Image /RestoreHealth
This is next to read - https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/troubleshoot/rdp-error-general-troubleshooting

**Comment by makdee88** [comment]
```
C:\Windows\system32>DISM /Online /Cleanup-Image /CheckHealth

Deployment Image Servicing and Management tool
Version: 10.0.19041.844

Image Version: 10.0.19044.1645

No component store corruption detected.
The operation completed successfully.

C:\Windows\system32>DISM /Online /Cleanup-Image /ScanHealth

Deployment Image Servicing and Management tool
Version: 10.0.19041.844

Image Version: 10.0.19044.1645

[==========================100.0%==========================] No component store corruption detected.
The operation completed successfully.
C:\Windows\system32>DISM /Online /Cleanup-Image /RestoreHealth

Deployment Image Servicing and Management tool
Version: 10.0.19041.844

Image Version: 10.0.19044.1645

[==========================100.0%==========================] The restore operation completed successfully.
The operation completed successfully.

C:\Windows\system32>
```

**Comment by makdee88** [comment]
Tried to restore HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-tcp from a working windows 10 machine. Still same error.
![image](https://user-images.githubusercontent.com/11515433/165120037-487cdc8a-89ce-4c14-be63-abc276935fb0.png)

**Comment by GeorgiTz** [comment]
Same things with me. May be some permitions are lost?

**Comment by makdee88** [comment]
Probably. Could not find where?

**Comment by GeorgiTz** [comment]
I lost on this stupid case too much time. First of all disable BitDefender. Second i made a restore to 13.04.2022. After 5 unsuccessful attempts I found the key to restore - do it under SAFE MODE. So now remote desktop works again and I uninstall BitDefender. (Sorry guys but now I don't like your service). Microsoft system restore sucks too. It took to me 2 hours to fight all of their stupid errors.
makdee88, I Hope you can find your way against that problem!

**Comment by makdee88** [comment]
Okay. Unfortunately I don't have a restore point to go back to. I am stuck.

**Comment by cisco1012** [comment]
I'm having this same issue and have tried the troubleshoot steps listed above. I also had BitDefender installed. I don't have a restore point. Any more progress on getting your service to start?

**Comment by Loggsie** [comment]
I recently run into this issue on Windows 11 Pro 10.0.22000.652 believing it to be a recent Stack Update. 

Remote Desktop Service would fail with error 126 - module missing.

All required DLL's and registry entries in tact. 

DISM Online Cleanup Restore Health - did not work
SFC /Scannow - did not work

If you have RDP Wrapper installed the RD Service will attempt to call C:\Program Files\RDP Wrapper\rdpwrap.dll

You can not start the service and/or uninstall RDP Wrapper as uninstalling requires the termsrv.dll to be terminated. 

Solution was to ensure rdpwrap.dll was present within this location and not within any sub folders - C:\Program Files\RDP Wrapper\rdpwrap.dll

After which RD Service will start successfully, if needed you can then update .ini and/or uninstall RDP Wrapper.

**Comment by makdee88** [comment]
Could be related to stack update. But I have tried keeping C:\Program Files\RDP Wrapper\rdpwrap.dll in the correct place. 
Also tried updating the reg key to point to actual termsrv.dll, but none worked.
![image](https://user-images.githubusercontent.com/11515433/165507231-bbfd0ec1-484e-4d82-bc55-9e3ed07f1819.png)

**Comment by Loggsie** [comment]
> Could be related to stack update. But I have tried keeping C:\Program Files\RDP Wrapper\rdpwrap.dll in the correct place. 
> Also tried updating the reg key to point to actual termsrv.dll, but none worked.
> ![image](https://user-images.githubusercontent.com/11515433/165507231-bbfd0ec1-484e-4d82-bc55-9e3ed07f1819.png)
> 
> 

Create a system restore point and try manually removing the servicing stack update causing you the issue.

https://www.thewindowsclub.com/uninstall-windows-updates-without-uninstall-option

**Comment by makdee88** [comment]
Tried that, there is no uninstall option on the servicing stack. :(

**Comment by cisco1012** [comment]
I no longer have the rdpwrap.dll file and am unable to reinstall. Does anyone have a known good copy of that file that I can put back in place to see if it fixes the service startup issue?

**Comment by makdee88** [comment]
I have this copy. However not sure if this works or not. Does not work for me.
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/8572262/rdpwrap.zip)

**Comment by makdee88** [comment]
> > Could be related to stack update. But I have tried keeping C:\Program Files\RDP Wrapper\rdpwrap.dll in the correct place.
> > Also tried updating the reg key to point to actual termsrv.dll, but none worked.
> > ![image](https://user-images.githubusercontent.com/11515433/165507231-bbfd0ec1-484e-4d82-bc55-9e3ed07f1819.png)
> 
> Create a system restore point and try manually removing the servicing stack update causing you the issue.
> 
> https://www.thewindowsclub.com/uninstall-windows-updates-without-uninstall-option

I have a few KB installed on top of it. If I try to uninstall them, it shows uninstalled. Post reboot it's back in. Typical Windows I tell you.

**Comment by GeorgiTz** [comment]
> I have this copy. However not sure if this works or not. Does not work for me. [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/8572262/rdpwrap.zip)

I checked yours rdpwrap, it's exactly the same with mine (working). The problem is somewhere at other place.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1786

**Comment by makdee88** [comment]
> Applicable to #1786

I have gone through it. The issue is different. It did not solve this perticular problem.

**Comment by sebaxakerhtc** [comment]
> ```
> C:\Windows\system32>DISM /Online /Cleanup-Image /CheckHealth
> 
> Deployment Image Servicing and Management tool
> Version: 10.0.19041.844
> 
> Image Version: 10.0.19044.1645
> 
> No component store corruption detected.
> The operation completed successfully.
> 
> C:\Windows\system32>DISM /Online /Cleanup-Image /ScanHealth
> 
> Deployment Image Servicing and Management tool
> Version: 10.0.19041.844
> 
> Image Version: 10.0.19044.1645
> 
> [==========================100.0%==========================] No component store corruption detected.
> The operation completed successfully.
> C:\Windows\system32>DISM /Online /Cleanup-Image /RestoreHealth
> 
> Deployment Image Servicing and Management tool
> Version: 10.0.19041.844
> 
> Image Version: 10.0.19044.1645
> 
> [==========================100.0%==========================] The restore operation completed successfully.
> The operation completed successfully.
> 
> C:\Windows\system32>
> ```

Image version is 1645 which have termsrv.dll version 1620
Something wrong with your installation/tersrv.dll version. Isn't it?

If not - reopen the issue

**Comment by makdee88** [comment]
Okay. How do I verify the version of my system termsrv.dll. How do I find and replace the correct version of termsrv.dll. Any help is appreciated.

**Comment by sebaxakerhtc** [comment]
> Okay. How do I verify the version of my system termsrv.dll. How do I find and replace the correct version of termsrv.dll. Any help is appreciated.

I installed yesterday 1645 and there's a termsrv.dll version 1620.
You can try to download and install whole 1645 update manually.
Or i will send you a termsrv.dll file.
Is your version x86 or x64?

**Comment by GeorgiTz** [comment]
I think that I found something, may be the solution. There is error at this key->

> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters]
> "ServiceDll"=hex(2):25,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,46,00,69,\
>   00,6c,00,65,00,73,00,25,00,5c,00,52,00,44,00,50,00,20,00,57,00,72,00,61,00,\
>   70,00,70,00,65,00,72,00,5c,00,72,00,64,00,70,00,77,00,72,00,61,00,70,00,2e,\
>   00,64,00,6c,00,6c,00,00,00
You use the wrong dll -> %SystemRoot%\System32\termsrv.dll
The real path is %ProgramFiles%\RDP Wrapper\rdpwrap.dll because the wrapper must start before termsrv.
So edit the key and change the record to >>> %ProgramFiles%\RDP Wrapper\rdpwrap.dll
May be after that restart machine. Success!

**Comment by sebaxakerhtc** [comment]
So many issues with bitdefender... It often delete registry and necessary files with rdpwrapper.

**Comment by makdee88** [comment]
> > Okay. How do I verify the version of my system termsrv.dll. How do I find and replace the correct version of termsrv.dll. Any help is appreciated.
> 
> I installed yesterday 1645 and there's a termsrv.dll version 1620. You can try to download and install whole 1645 update manually. Or i will send you a termsrv.dll file. Is your version x86 or x64?

Version: x64. Is there a way I can download and install new update from Microsoft? Which will replace the correct termsrv.dll

**Comment by sebaxakerhtc** [comment]
> Is there a way I can download and install new update from Microsoft?

https://support.microsoft.com/en-us/topic/april-12-2022-kb5012599-os-builds-19042-1645-19043-1645-and-19044-1645-548cc67c-7f12-46fd-878e-589ba81ac2f5

**Comment by makdee88** [comment]
> I think that I found something, may be the solution. There is error at this key->
> 
> > [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters]
> > "ServiceDll"=hex(2):25,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,46,00,69,
> > 00,6c,00,65,00,73,00,25,00,5c,00,52,00,44,00,50,00,20,00,57,00,72,00,61,00,
> > 70,00,70,00,65,00,72,00,5c,00,72,00,64,00,70,00,77,00,72,00,61,00,70,00,2e,
> > 00,64,00,6c,00,6c,00,00,00
> > You use the wrong dll -> %SystemRoot%\System32\termsrv.dll
> > The real path is %ProgramFiles%\RDP Wrapper\rdpwrap.dll because the wrapper must start before termsrv.
> > So edit the key and change the record to >>> %ProgramFiles%\RDP Wrapper\rdpwrap.dll
> > May be after that restart machine. Success!

I changed service dll parameter manually. As uninstall.bat was failing. RDPwrapper shows uninstalled if servicedll is set to termsrv.dll (which is default if RDPwrapper is not installed).

Right now I want RDP service to start without any patches. Then I can install RDPwrapper from scratch.

**Comment by GeorgiTz** [comment]
These are registry keys which are found connected to termsvr in working Win10 [SYSTEM]:
[RegistryTermsvr_x64_W10workingFull.txt](https://github.com/stascorp/rdpwrap/files/8575430/RegistryTermsvr_x64_W10workingFull.txt)

**Comment by makdee88** [comment]
Installing April 25, 2022—KB5011831. Lets see if that changes anything.
No luck. Update completed 19041.1677. All DLL files(including termsrv.dll) in system32 got updated. 
![image](https://user-images.githubusercontent.com/11515433/165732811-49eb1610-9e74-466a-a624-2b88d82a9151.png)

Still same error while starting RDP service. Seems some thing is not right in my registry entries.

**Comment by makdee88** [comment]
Its very sad, there is no way to get the error due to which RDP service is not starting.

**Comment by GeorgiTz** [comment]
Did you try to change the dll path ?
![TermsvrDllLocation](https://user-images.githubusercontent.com/104362477/165740255-4159491c-6e49-4e08-91fe-680be6d347ea.png)
?

**Comment by makdee88** [comment]
> Did you try to change the dll path ? ![TermsvrDllLocation](https://user-images.githubusercontent.com/104362477/165740255-4159491c-6e49-4e08-91fe-680be6d347ea.png) ?

Yes. I tried it now again.
![image](https://user-images.githubusercontent.com/11515433/165747478-086abb83-61fb-4027-8136-4ddc0eaddb56.png)
Here are contents for RDP Wrapper folder in Program Files
![image](https://user-images.githubusercontent.com/11515433/165747649-7471f5b5-9cd7-4994-beea-fc117df2e091.png)

Still:
![image](https://user-images.githubusercontent.com/11515433/165747774-6e406998-6378-452d-abd9-07a867ddfa7e.png)

**Comment by GeorgiTz** [comment]
> These are registry keys which are found connected to termsvr in working Win10 [SYSTEM]: [RegistryTermsvr_x64_W10workingFull.txt](https://github.com/stascorp/rdpwrap/files/8575430/RegistryTermsvr_x64_W10workingFull.txt)

Did you check all of this keys exist at your registry?

**Comment by makdee88** [comment]
I checked and found HKEY_LOCAL_MACHINE\SOFTWARE\RDP-Wrapper and HKEY_LOCAL_MACHINE\SYSTEM\Setup\FirstBoot to be missing from my registry. Not sure how do I restore it back. Rest seems Ok to me at-least.

[export_termservice_key.txt](https://github.com/stascorp/rdpwrap/files/8629915/export_termservice_key.txt)

**Comment by GeorgiTz** [comment]
You can try mine keys, I think they are universal. Change termsrv.dll version with yours and verify paths to files.

[HKEY_LOCAL_MACHINE\SOFTWARE\RDP-Wrapper]

[HKEY_LOCAL_MACHINE\SOFTWARE\RDP-Wrapper\Autoupdate]
"termsrv.dll"="10.0.19041.1566"

[HKEY_LOCAL_MACHINE\SYSTEM\Setup\FirstBoot\Services\TermService]
"ServiceName"="TermService"
"Dependencies"=hex(7):52,00,50,00,43,00,53,00,53,00,00,00,00,00
"Path"="C:\\windows\\System32\\svchost.exe -k NetworkService"
"Path.Org"="%SystemRoot%\\System32\\svchost.exe -k NetworkService"
"Path.Win32"="C:\\Program Files\\RDP Wrapper\\rdpwrap.dll"
"StartName"="NT Authority\\NetworkService"
"DisplayName"="Remote Desktop Services"
"Type"=dword:00000020
"StartType"=dword:00000003
"ErrorControl"=dword:00000001
"LoadOrderGroup"=""
"TagId"=dword:00000000

**Comment by yossijo** [comment]
What worked for me is.  I turned off bitdefender.  Removed rdp wrapper folder & rdp wrapper scheduled task.  

Reinstall with iso & choosing to keep everything.    

(Could be not all steps are needed

**Comment by crazyboy24** [comment]
Was facing the same problem. This worked for me https://github.com/stascorp/rdpwrap/issues/1818#issuecomment-1111555812

**Comment by makdee88** [comment]
Following fixed the issue, DAMN Bitdefender. It took 3 months.

a)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Svchost 
This key has a value "Networkservice". The data for this value should be : 
CryptSvc WinRM WECSVC DHCP TermService DNSCache Tapisrv 

If Termservice is missing, add it to the list

b)Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Svchost 
This key has a value "Networkservice". The data for this value should be : 
CryptSvc nlasvc lanmanworkstation WinRM WECSVC dosvc MapsBroker DHCP TermService DNSCache Tapisrv 

If Termservice is also missing, add it to the list.

**Comment by motormat** [comment]
@makdee88 thank you so much, for us appears that the only differaCE WAS "dosvc" missing from the line.
