### ISSUE TITLE
Not support 10.0.19041.1620

### ISSUE THREAD

**Issue by panmyuan** [stascorp/rdpwrap#1824]
setting
![image](https://user-images.githubusercontent.com/48192787/165433522-313070af-de64-4cd7-9f03-f77bb6488265.png)

**Comment by sashaqwert** [comment]
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1786

**Comment by davidvieira13** [comment]
I have the same problem

**Comment by sebaxakerhtc** [comment]
> Duplicate of #1786
