### ISSUE TITLE
Incorrect .ini pull path in autoupdate.bat

### ISSUE THREAD

**Issue by Loggsie** [stascorp/rdpwrap#1825]
Changing line 30 to

set rdpwrap_ini_update_github_1="https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini"

Running batch causes an outdated .ini to be pulled from a redudant repository located at 

https://raw.githubusercontent.com/stascorp/rdpwrap/master/res/rdpwrap.ini

**Comment by sebaxakerhtc** [comment]
Autoupdate.bat is not a part of rdpwrapper.
Create an issue at right place
