### ISSUE TITLE
the version of 10.0.22000.469 is 'Not listening'

### ISSUE THREAD

**Issue by fang0king** [stascorp/rdpwrap#1826]
The version of 10.0.22000.469 is' Not listening '

**Comment by fang0king** [comment]
Who can help me?  thanks a lot!
<img width="720" alt="AB61F941-E651-48BB-81B4-99F4ADD3E2F0" src="https://user-images.githubusercontent.com/19279633/165767558-dba97eb5-7a6a-487c-a511-16a4ebd14f08.png">

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1698
