### ISSUE TITLE
Not supported also not listening OS build 19044.1645

### ISSUE THREAD

**Issue by dYbIRitz** [stascorp/rdpwrap#1831]
Hello I am having a problem with the rdp not listening/not supported. I am very new at this like of stuff, and not sure what to do.

Version 21H2 (OS Build 19044.1645)

![Screenshot 2022-05-02 212722](https://user-images.githubusercontent.com/104805265/166392084-5a550b61-835a-4bc5-b869-47b6df210de3.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1786

**Comment by sebaxakerhtc** [comment]
> Duplicate of #1786

**Comment by Natanaelb906** [comment]
alguma solução pra esse problema??
