### ISSUE TITLE
Which version should I choose for the patch ?

### ISSUE THREAD

**Issue by paolosezart** [stascorp/rdpwrap#1832]
Which version should I choose for the patch :
![image](https://user-images.githubusercontent.com/38177890/166560152-7f989fdf-e2b1-4358-9374-d16ef2771f91.png)

I mean, to search for the version number in rdpwrap.ini. And how can I get the windows version using a bat script into a variable or a text file? Only the version, without unnecessary information.

**Comment by sashaqwert** [comment]
>Which version should I choose for the patch 

You need to use the version from RDPConf.

Your issue is https://github.com/stascorp/rdpwrap/issues/1786

Please, do not patch `termsrv.dll`. You need to replace the `rdpwrap.ini`.

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1786

**Comment by paolosezart** [comment]
In that case, how do I get the version (which is displayed in RDPConf) into a text file?

**Comment by sashaqwert** [comment]
@paolosezart 

> how do I get the version (which is displayed in RDPConf) into a text file?

Also, the version is in the `C:\Windows\System32\termsrv.dll` file properties.

**Comment by paolosezart** [comment]
> Also, the version is in the `C:\Windows\System32\termsrv.dll` file properties.

Found a way to get the version termsrv.dll from the command line. This is much faster than opening a folder with a file and looking for file properties there.
`wmic datafile where name="c:\\windows\\system32\\termsrv.dll" get version`
