### ISSUE TITLE
Work locally but not remotely 10.0.19041.1620

### ISSUE THREAD

**Issue by OmarLopez18** [stascorp/rdpwrap#1833]
All states are green and I’m able to connect locally to the PC, but when trying to connect outside the network doesn’t work. I have configure every thing(ports on router etc.) but it doesn’t work. Please if someone knows a solution let me know.

**Comment by OmarLopez18** [comment]
![image](https://user-images.githubusercontent.com/14249252/167006159-7e01d7a7-689a-4732-8e58-83efcc2c5bdf.png)

**Comment by sebaxakerhtc** [comment]
Check you firewall
Applicable to https://github.com/stascorp/rdpwrap/issues/1786

**Comment by OmarLopez18** [comment]
The problem doesn't appear to be the firewall. I configure both the routers and the pc. I tried turning the firewalls off, yet nothing happened.

**Comment by OmarLopez18** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8648751/termsrv.zip)

**Comment by lusinqui** [comment]
![RDPWrapper](https://user-images.githubusercontent.com/10750871/167888192-d6e93b8a-2e5f-4fb6-99d8-97effea59f0c.png)
@OmarFive5 not yet :'(
