### ISSUE TITLE
Not Supported 10.0.22610.1

### ISSUE THREAD

**Issue by dungmn** [stascorp/rdpwrap#1835]
![image](https://user-images.githubusercontent.com/28902802/167112689-6823af2d-4eff-48f0-9366-faed06322d07.png)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8639242/termsrv.zip)
Plz help me!

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1830
