### ISSUE TITLE
Not Supported 10.0.22616.1

### ISSUE THREAD

**Issue by whitemonday** [stascorp/rdpwrap#1836]

**Comment by sebaxakerhtc** [comment]
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/0055f4ad4ffa2b162e1b2f4dfc8162975b926ce6

**Comment by wxpanada** [comment]
https://github.com/anhkgg/SuperRDP
You can set the checkbox AutoSupport， then SuperRDP2 will automatically support the new version
