### ISSUE TITLE
Not listening on 10.0.19041.1202 win10-x86

### ISSUE THREAD

**Issue by rejoice999** [stascorp/rdpwrap#1839]
Works on win10-x64 21H2, termsrv.dll version is 10.0.19041.1202
But Not listening on win10-x86 21H2, termsrv.dll version is 10.0.19041.1202 too
[termsrv_from_win10home_21H2_x86.zip](https://github.com/stascorp/rdpwrap/files/8649081/termsrv_from_win10home_21H2_x86.zip)
.

**Comment by sebaxakerhtc** [comment]
> Not listening on win10-x86

https://github.com/sebaxakerhtc/rdpwrap.ini/commit/2e49090699f2e3461eb56ef576688bf7dd24d399
The offsets was added
https://github.com/stascorp/rdpwrap/issues/1509

**Comment by rejoice999** [comment]
It works well, thanks !
