### ISSUE TITLE
rdpWrap no longer works on my win10 :(  - RDPCheck shows black screen with no errors

### ISSUE THREAD

**Issue by clinrewn** [stascorp/rdpwrap#184]
Win 10 Pro 1607 14393.447
rdpWrap 1.6.1
Wrapper state: Installed
Service state: Running
Listener state: Listening
ver. 1.5.0.0
ver. 10.0.14393.0

**RDPCheck shows black screen with no errors :(**

I tried:
restart
reinstall rdpWrap
remove, add users from RemoteDesktop
No antyvirus instaled

**Any ideas ?**

**Comment by binarymaster** [comment]
Try waiting until logon screen is showed. If it disconnects you, try connecting again.

This seems to be machine-specific issue, not related to RDP Wrapper directly.
