### ISSUE TITLE
Not supported 21H2 19044.1682

### ISSUE THREAD

**Issue by MinecraftXZS** [stascorp/rdpwrap#1840]
The word [Not supported] appears when using Windows Professional 21H2 19044.1682, and the update is invalid.

**Comment by MinecraftXZS** [comment]
The word [Not supported] appears when using Windows Professional 21H2 19044.1682, and the update is invalid.

**Comment by sashaqwert** [comment]
~~RDPConf screenshot, please!~~

Duplicate of https://github.com/stascorp/rdpwrap/issues/1823

**Comment by MinecraftXZS** [comment]
Thank youuuuu!
