### ISSUE TITLE
Not Supported 10.0.22000.675

### ISSUE THREAD

**Issue by shiroamada** [stascorp/rdpwrap#1845]
10.0.22000.675 not working, can help?

**Comment by demicus** [comment]
10.0.22000.675 and me please((

**Comment by ZOAR05** [comment]
Me  three. please  help.

**Comment by jodkiam** [comment]
how to do friends 10.0.22000.675

**Comment by Raoniq** [comment]
same here, not supported :(

**Comment by Raoniq** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8702944/termsrv.zip)

if anyone is interesting on helping us :D pleeeeeeease

**Comment by phiclin** [comment]
10.0.22000.675 and me please help

**Comment by wxpanada** [comment]
https://github.com/anhkgg/SuperRDP
You can set the checkbox AutoSupport， then SuperRDP2 will automatically support the new version

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1843

**Comment by Raoniq** [comment]
No one ? :(

**Comment by sebaxakerhtc** [comment]
> No one ? :(

All works fine. Look upper https://github.com/stascorp/rdpwrap/issues/1845#issuecomment-1132602432
