### ISSUE TITLE
Service state Stopped & Listener State Not Listening

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#1847]
Windows 11 Pro
Everything was working fine until windows 11 pro downloaded updates now after updated RDP stopped working. Also won't let me uninstall.

![RDP-WRAP](https://user-images.githubusercontent.com/39812113/168097887-39011a17-1c7c-4ca8-bfda-ce957d5b6aa4.jpg)

**Comment by sebaxakerhtc** [comment]
> windows 11 pro downloaded updates

Yor termsrv.dll version have nothing in common with Windows 11 at all.
Repair your system
Not an RDPWrapper issue
