### ISSUE TITLE
19044.1706无法支持

### ISSUE THREAD

**Issue by TimTse2020** [stascorp/rdpwrap#1848]
19044.1706无法支持

**Comment by sebaxakerhtc** [comment]
Any description?
Screnshot of rdpconf?

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer

**Comment by dingjinfeng** [comment]
you can use [10.0.19041.1682_x64](https://github.com/sebaxakerhtc/rdpwrap.ini/commit/58fbef4be644439a2c27b3bffd2ef450c4810f10)

**Comment by TimTse2020** [comment]
sdfg 

> 你可以使用[10.0.19041.1682_x64](https://github.com/sebaxakerhtc/rdpwrap.ini/commit/58fbef4be644439a2c27b3bffd2ef450c4810f10)
![QQ截图20220517161056](https://user-images.githubusercontent.com/105480183/168762734-dff929e7-b079-49b2-b1e3-f1d7835e24d2.png)

不可以

**Comment by TimTse2020** [comment]
![Uploading QQ截图20220517161056.png…]()
> 有什么说明吗？ rdpconf 的截图？

![QQ截图20220517161358](https://user-images.githubusercontent.com/105480183/168763154-a483cb8e-cffe-491f-85a7-4967607d2a9b.png)

**Comment by TimTse2020** [comment]
> rdpconf 的截图？
![Uploading QQ截图20220517161056.png…]()

**Comment by TimTse2020** [comment]
> rdpconf 的截图？

![QQ截图20220517161056](https://user-images.githubusercontent.com/105480183/168763465-ecee517c-f132-4635-81ef-ba34c8c7a58e.png)
