### ISSUE TITLE
Fully supported 10.0.19041.1682  concurrent connections not working

### ISSUE THREAD

**Issue by TwizalBG** [stascorp/rdpwrap#1850]
![10 0 19041 1682](https://user-images.githubusercontent.com/105510043/168324621-29d42f98-91f9-4736-bcfd-695e1ea6aa27.png)

Cannot login multiple times ( create multiple sessions ) with single user account.

Also try to change following settings in group policy without success:
Restrict Remote Desktop Services users to a single Remote Desktop Services session value: Disabled
Remote Desktop Maximum Connections allowed to 999999

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823

Try reboot.

**Comment by TwizalBG** [comment]
Will continue in #1823
