### ISSUE TITLE
Windows 10 ver. 19044.1706 listener is not supported

### ISSUE THREAD

**Issue by witolo-genuine** [stascorp/rdpwrap#1851]
As in issue tittle.

**Comment by sashaqwert** [comment]
RDPConf screenshot, please!

**Comment by photor** [comment]
I have the same problem:
![图片](https://user-images.githubusercontent.com/50810677/168461202-96393123-d95e-4829-8b6b-1482e7edc598.png)

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823
