### ISSUE TITLE
Not Supported 10.0.19041.1682

### ISSUE THREAD

**Issue by chberta** [stascorp/rdpwrap#1852]
Here it doesn't work follow termsrv
[termsrv.txt](https://github.com/stascorp/rdpwrap/files/8693827/termsrv.txt)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823

**Comment by Marcos0gral** [comment]
As @sashaqwert  said, its duplicate.
Here in #1823 https://github.com/stascorp/rdpwrap/issues/1823#issuecomment-1126929742
i found the ini file working for me

**Comment by sebaxakerhtc** [comment]
> Duplicate of #1823
