### ISSUE TITLE
10.0.19043.1706 NOT SUPPORTED

### ISSUE THREAD

**Issue by snow-to-earth** [stascorp/rdpwrap#1853]

**Comment by snow-to-earth** [comment]
termsrv

**Comment by snow-to-earth** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8701159/termsrv.zip)

**Comment by mateuscdor** [comment]
@sebaxakerhtc

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823
