### ISSUE TITLE
Build ( 19044. 1706) not suported

### ISSUE THREAD

**Issue by Etezinho** [stascorp/rdpwrap#1854]
Pessoal essa versão nao quer funcionar. Ta escrito sem suporte. Poderiam me ajudar?

**Comment by mateuscdor** [comment]
@sebaxakerhtc

**Comment by sebaxakerhtc** [comment]
> @sebaxakerhtc

RDPconf screenshot?

**Comment by Etezinho** [comment]
Deu certo ja, obrigado
