### ISSUE TITLE
Not Supported 10.0.19041 1682

### ISSUE THREAD

**Issue by Bovemax** [stascorp/rdpwrap#1856]
![rdpwrapscreenshot](https://user-images.githubusercontent.com/86031692/168706353-60f7ee66-0558-4f24-96a8-1d23225a8ffa.png)

**Comment by TimTse2020** [comment]
不支持 
![QQ截图20220517161056](https://user-images.githubusercontent.com/105480183/168762998-ddacd999-47a2-47a9-8b27-ca54d935662d.png)
![QQ截图20220517161358](https://user-images.githubusercontent.com/105480183/168763049-eaac34fb-279d-45d6-b298-6d7a0710c44c.png)

**Comment by sashaqwert** [comment]
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini#L5015
https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini#L9292

**Comment by Bovemax** [comment]
Спасибо, но теперь он говорит следующее:
Thanks, but now it says this:
![rdp](https://user-images.githubusercontent.com/86031692/168891937-1eb32923-d7da-482c-ad6d-5af75df90570.png)

**Comment by wxpanada** [comment]
https://github.com/anhkgg/SuperRDP
You can set the checkbox AutoSupport， then SuperRDP2 will automatically support the new version

**Comment by Bovemax** [comment]
@wxpanada thanks
