### ISSUE TITLE
Recommended SuperRDP：Automatically support the new version of Window Remote Desktop Service 推荐仓库自动支持最新版本

### ISSUE THREAD

**Issue by wxpanada** [stascorp/rdpwrap#1858]

**Comment by wxpanada** [comment]
https://github.com/anhkgg/SuperRDP

**Comment by phiclin** [comment]
10.0.22000.675  version still not supported

**Comment by wxpanada** [comment]
You should set the checkbox AutoSupport， then SuperRDP2 will automatically support the new version

**Comment by sebaxakerhtc** [comment]
Not an rdp wrapper issue
Stop spamming or you'll be blocked
