### ISSUE TITLE
Rdp wrapper listener state not supported and is not listening 

### ISSUE THREAD

**Issue by jchawk8** [stascorp/rdpwrap#1859]
Rdp wrapper listener state not supported and is not listening is there a fix to this issue 
![image](https://user-images.githubusercontent.com/105763942/168947292-4951752a-bf1a-4fae-a76e-2c181f60141b.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1843

**Comment by sebaxakerhtc** [comment]
> Duplicate of #1843
