### ISSUE TITLE
Not supported 19041.1682

### ISSUE THREAD

**Issue by manyui** [stascorp/rdpwrap#1860]
I hava update the rdpwrap.ini, but still cannot work. ![3A BFYIPA`X R4YW I$)LRX](https://user-images.githubusercontent.com/50876541/169044408-25de2c73-0feb-4436-824a-e93d0ba392b8.png)

**Comment by Koaalah** [comment]
I have the same problem, yesterday I spent all day trying to solve it, exchanging files, installing and reinstalling and nothing

**Comment by wxpanada** [comment]
https://github.com/anhkgg/SuperRDP
You can set the checkbox AutoSupport， then SuperRDP2 will automatically support the new version

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823
