### ISSUE TITLE
https://github.com/anhkgg/SuperRDP

### ISSUE THREAD

**Issue by Natanaelb906** [stascorp/rdpwrap#1862]
https://github.com/anhkgg/SuperRDP
You can set the checkbox AutoSupport， then SuperRDP2 will automatically support the new version

_Originally posted by @wxpanada in https://github.com/stascorp/rdpwrap/issues/1860#issuecomment-1131152970_

servir para a versão 21h2 Compilação 19044.1645?

**Comment by sebaxakerhtc** [comment]
Not an RDPWrapper issue
