### ISSUE TITLE
ver 10.0.72000.706 not supported

### ISSUE THREAD

**Issue by chbartel** [stascorp/rdpwrap#1865]
just got newest update for windows 11..

**Comment by sashaqwert** [comment]
RDPConf screenshot, please!

**Comment by UMU618** [comment]
https://github.com/UMU618/rdpwrap.ini

Updated to support 10.0.72000.706

**Comment by sebaxakerhtc** [comment]
> just got newest update for windows 11..

Attach your termsrv.dll, so i can help you

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
