### ISSUE TITLE
Mi envoltura rdp funciona "totalmente compatible", pero no me permite hacer una conexión simultánea

### ISSUE THREAD

**Issue by scrcrivera** [stascorp/rdpwrap#1866]
My rdp Wrapper is working "fully supported", but it won't let me make simultaneous connection
![IMG_3551](https://user-images.githubusercontent.com/79241063/168228833-02244e9e-85e5-455f-99a8-70c842f9a952.jpg)
s

_Originally posted by @scrcrivera in https://github.com/stascorp/rdpwrap/issues/1823#issuecomment-1125720556_

**Comment by just4id** [comment]
Me too,  Windows 11 OS of version 10.0.22621.1

**Comment by lusinqui** [comment]
Dont allow access Two o more user in the same Time.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1883

**Comment by JEmlay** [comment]
I have the same problem.  Will not allow more than one user to log in at a time.  Scrcrivera & just4id & lusinqui, were you able to get it working with anything in #1883 ?  I wasn't.  If so , can you explain exactly what fixed it?  If not then this should also be reopened along with mine.

**Comment by sebaxakerhtc** [comment]
> should also be reopened

Just one issue for the same problem can be opened.
By rule - the first one. So i will search the first one, and will close all other with link to the first one
