### ISSUE TITLE
termsrv.dll unsupported

### ISSUE THREAD

**Issue by staley99** [stascorp/rdpwrap#187]
I got the following Error:

[-] This version of Terminal Services is not supported.
Send your termsrv.dll to project developer for support.

Here it the dll: 

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/658814/termsrv.zip)

**Comment by staley99** [comment]
And a second unsopported dll:

[termsrv2.zip](https://github.com/stascorp/rdpwrap/files/658819/termsrv2.zip)

Both are from Windows 10 home machines

**Comment by binarymaster** [comment]
Both versions `10.0.10586.0` and `10.0.14393.0` are already supported.

Obviously you're using old release.
