### ISSUE TITLE
Windows 10 termsrv v10.0.19041.1739

### ISSUE THREAD

**Issue by jatindersangha** [stascorp/rdpwrap#1872]
Hi,

Does anyone have the config for Windows 10, termsrv.dll v10.0.19041.1739?

Or alternatively, can someone build the update please?

Thanks,
--Jatinder

**Comment by sebaxakerhtc** [comment]
> Hi,
> 
> Does anyone have the config for Windows 10, termsrv.dll v10.0.19041.1739?
> 
> Or alternatively, can someone build the update please?
> 
> Thanks, --Jatinder

Rdpconf screenshot, please

**Comment by jatindersangha** [comment]
Here's the screenshot.

![image](https://user-images.githubusercontent.com/62962154/170770282-3a72061d-63db-44c1-82c2-47aacd10cede.png)

**Comment by sebaxakerhtc** [comment]
Please attach your zipped termsrv.dll

**Comment by jatindersangha** [comment]
[termsrv.dll.gz](https://github.com/stascorp/rdpwrap/files/8789088/termsrv.dll.gz)

termsrv.dll uploaded (compressed using gzip)

**Comment by sebaxakerhtc** [comment]
> [termsrv.dll.gz](https://github.com/stascorp/rdpwrap/files/8789088/termsrv.dll.gz)
> 
> termsrv.dll uploaded (compressed using gzip)

Sorry, there's no pdb file for this version.
Monday i can try to find the offsers manualy

**Comment by jatindersangha** [comment]
OK. Thanks for your help.

**Comment by sebaxakerhtc** [comment]
> OK. Thanks for your help.

https://github.com/sebaxakerhtc/rdpwrap.ini/commit/21bbe95c434e5f8791d47a1a670a544adea5e323
The offsets was added

**Comment by jatindersangha** [comment]
Thanks - that worked perfectly.

Anywhere to give donations?

--Jatinder

**Comment by sebaxakerhtc** [comment]
> Thanks - that worked perfectly.
> 
> Anywhere to give donations?
> 
> --Jatinder

Thank you.
There is a link in my profile

**Comment by jatindersangha** [comment]
Thanks,
--Jatinder
