### ISSUE TITLE
Listening and supported yet not working

### ISSUE THREAD

**Issue by JEmlay** [stascorp/rdpwrap#1873]
After updating to Windows 10 LTSC 21H2 everything was working fine.  As usual when updates roll down I have to update the INI, no big deal.  So when I wasn't able to login as the local admin to a machine that a user was using I figured time to update the INI.  Except RDPConf says everything is good.  I have machines on version 19041.1503 and .1682.  Neither of them work.  Only one user can be logged in at a time.

As you can see I updated the INI anyway and also tried uninstalling, reboot, reinstall, reboot.  Still no good.

INI File - Updated=2022-05-17

<img width="299" alt="Capture" src="https://user-images.githubusercontent.com/1591895/170760712-029481ab-39e7-40b2-86d2-2f3bfec8ea59.PNG">

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8788728/termsrv.zip)

**Comment by sebaxakerhtc** [comment]
Reboot your PC

**Comment by JEmlay** [comment]
> As you can see I updated the INI anyway and also tried uninstalling, reboot, reinstall, reboot. Still no good.

**Comment by sebaxakerhtc** [comment]
Try to switch to Network level authentication

**Comment by ghost** [comment]
I have the same problem. It's all green after updating the INI to Windows 11 10.0.22000.708 and even using Network Level Authentication it only accepts 1 user at a time.

**Comment by JEmlay** [comment]
Unfortunately the same thing...

<img width="472" alt="Capture" src="https://user-images.githubusercontent.com/1591895/170773503-8069f01d-e3bd-4e91-a456-86b898a430c3.PNG">

**Comment by sebaxakerhtc** [comment]
> I have the same problem. It's all green after updating the INI to Windows 11 10.0.22000.708 and even using Network Level Authentication it only accepts 1 user at a time.

Did you try my mod yet?
https://github.com/sebaxakerhtc/rdpwrap/releases/tag/v1.8.8.7

**Comment by ghost** [comment]
> Did you try my mod yet? https://github.com/sebaxakerhtc/rdpwrap/releases/tag/v1.8.8.7

Same problem.

**Comment by JEmlay** [comment]
> Did you try my mod yet? https://github.com/sebaxakerhtc/rdpwrap/releases/tag/v1.8.8.7

What is this?  A fork?  I could try this on a single machine but that wouldn't help the hundreds of machines on my floor :(

**Comment by ghost** [comment]
This problem seems to have already been reported here #1866 and so far no solution.

**Comment by JEmlay** [comment]
So it's affecting Windows 10 and 11 and my machines that are .1503 haven't been updated for many months.  That would have to be a seriously wide spread problem.

EDIT:
With the exception of Defender updates.  I wonder if this is an oddball AV issue that's not presenting itself on the surface.   I have both C:\Program Files\RDP Wrapper and C:\Program Files\RDP Wrapper\rdpwrap.dll excluded.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1883

**Comment by JEmlay** [comment]
Unfortunately 1883 did not help.  As stated earlier, the folder, file and process were already excluded from Defender.  So the DLL file was fine.  In case the registry was messed with I went ahead and:

Uninstalled RDP with the included BAT file.
Made sure all previous files were removed (INI and DLL), they were.
Delete my existing Registry key for TermSrv completely.
Applied the mentioned Reg File in #1883.
Rebooted to make sure TermSrv continued to work as normal.  It Did.
Re-installed RDP Wrapper.  Applied new INI.
Rebooted just to be thorough.

I can only login once.

Restarted the Service just to be thorough.

Again, I can only login once.

**Comment by JEmlay** [comment]
This needs to be reopened.  It was not applicable to #1883

**Comment by sebaxakerhtc** [comment]
> This needs to be reopened. It was not applicable to #1883

Applicable. Look at notes at the end of 1st message.
We solved this thousands times for many people. That's why we create one FAQ for this.

**Comment by sebaxakerhtc** [comment]
> Again, I can only login once.

It's normal behavor. On your screenshot you have checked one session per user

**Comment by JEmlay** [comment]
No, you don't understand how this works.  That setting is PER USER.  My users log in with their domain account.  I'm trying to login with the local admin account.  That is a DIFFERENT user.  That setting is on by default and should remain on as it would be horrible if users remoting in kept hitting X to close their session and kept logging back in with new sessions.

I don't know what 1st message you are referring to however I literally explained everything I did regarding issue #1883 and it still does not work.  Honestly I don't care about other people.  It's not working for me and it;s not working for the other people that have stated it's not working for them.  Can we please stop talking about other people and get to the issue at hand?

Are there any logs that can be turned on or anything to look at to get a clue here as to what is going on?  I cannot get two DIFFERENT users logged in at the same time and NOTHING in issue #1883 worked for me.

Thank You!

**Comment by sebaxakerhtc** [comment]
> you don't understand how this works

Ok. Please reopen the issue and wait for answer from people who understand more than me.

**Comment by JEmlay** [comment]
> > you don't understand how this works
> 
> Ok. Please reopen the issue and wait for answer from people who understand more than me.

I can't reopen it because you closed it.  I can only reopen issues that I created and I closed myself.  Have auths changed recently?  I don't see the option anywhere.

**Comment by JEmlay** [comment]
Thank you for reopening it.

**Comment by sebaxakerhtc** [comment]
Reopened the first issue with the same problem - so all other will link to it.
https://github.com/stascorp/rdpwrap/issues/353
