### ISSUE TITLE
10.0.19041.1737

### ISSUE THREAD

**Issue by jagarop** [stascorp/rdpwrap#1876]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8801010/termsrv.zip)

![image](https://user-images.githubusercontent.com/8181801/171068879-340423ed-a195-4e68-bea7-6f4151330b69.png)

**Comment by sebaxakerhtc** [comment]
Solved [here](https://github.com/sebaxakerhtc/rdpwrap.ini/issues/115)
