### ISSUE TITLE
Service Stopped & Not Listening

### ISSUE THREAD

**Issue by PHASE1N** [stascorp/rdpwrap#1878]
Hi...

Can anyone help please?

On my RDP wrapper for Service Stopped & Not Listening... 
After my antivirus cleaned RDP Wrapper by accident... 
-Removed Antivirus
-Recopied required files. 
-Updated PC

But now shows this after:

![RDP1](https://user-images.githubusercontent.com/106717676/171532934-d933d3b7-cbb1-4d44-8d72-02db7b946754.PNG)

My setup is on:  
64bit Win10 Pro, updated w/ latest Windows updates.

**Comment by sashaqwert** [comment]
rdpwrap.dll deleted by antivirus.

Try this command in CMD as Administrator:

```
reg add HKLM\SYSTEM\CurrentControlSet\Services\TermService\Parameters /v ServiceDll /t REG_EXPAND_SZ /d "%SystemRoot%\system32\termsrv.dll" /f
```

After this - reboot PC and install RDP Wrapper again. **Do not forgot add exclusion!!!**

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1883

**Comment by PHASE1N** [comment]
DAMN you are the MAN!!! Fixed!!
