### ISSUE TITLE
10.0.19044.1706 service ver N/A

### ISSUE THREAD

**Issue by zongcong233** [stascorp/rdpwrap#1879]
![image](https://user-images.githubusercontent.com/68262545/171583663-690f3afa-13f5-4e40-adda-82aa08e8c5d3.png)

termsrv.dll exist

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1865

**Comment by remember2011** [comment]
> ![image](https://user-images.githubusercontent.com/68262545/171583663-690f3afa-13f5-4e40-adda-82aa08e8c5d3.png)
> 
> termsrv.dll exist

Thanks, it works!
