### ISSUE TITLE
Cannot disable Multiple Sessions per user in Windows 7

### ISSUE THREAD

**Issue by issue-causer** [stascorp/rdpwrap#188]
I am facing a problem on my Windows 7 machine that even though in RDP Wrapper Configuration I have selected Single session per user, multiple sessions are enabled and new remote connections start their own session for the same user.
I think some configuration or setting in my machine is causing this issue.
To check this I created a Virtual Machine with Windows 7 and used then RDP Wrapper but faced no issue in it.
This shows that there is some specific problem in Windows on my real machine which is overriding RDP Wrapper's Configuration Settings.

**Comment by binarymaster** [comment]
Try searching in the system registry for the value `fSingleSessionPerUser`, it should be equal to 1 to disable multiple sessions per user.

By default it's located at `HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server`.

Wondering if this value can be in some other registry keys.

**Comment by issue-causer** [comment]
Thank you it's fixed now.
I had previously checked the value of `fSingleSessionPerUser` at
`HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server` and it was set to 1.

But as you suggesting searching the whole registry for copies of this value so I found many copies and some of them were set to 0, by changing all values of `fSingleSessionPerUser` to 1 my problem was solved.

But now there is another small problem which I am encountering and that is that now I cannot enable Multiple Sessions per user through the RDP Wrapper Configuration.

I will be able to do so by editing the registry and changing all `fSingleSessionPerUser` values to 0.
It is as if RDP Wrapper's Settings has no effect whatsoever. I want to know that what should be default settings in the registry to allow RDP Wrapper Setting to be enabled.

**Comment by binarymaster** [comment]
Some of values you've just changed overrides the value on default registry path.

Please provide registry paths where you found each `fSingleSessionPerUser` value. I have some assumptions but not sure enough.

**Comment by issue-causer** [comment]
These are the registry values which are in a fresh copy of Windows 7 by default:

`[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Terminal Server]
"fSingleSessionPerUser"=dword:00000001`

`[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet002\Control\Terminal Server]
"fSingleSessionPerUser"=dword:00000001`

`[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server]
"fSingleSessionPerUser"=dword:00000001`


And these are extra values specific to my current Windows:
`[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Group Policy Objects\{0FD2AB9D-4447-4B1E-8C71-E85B13002C5C}Machine\Software\Policies\Microsoft\Windows NT\Terminal Services]
"fSingleSessionPerUser"=dword:00000001`

`[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services]
"fSingleSessionPerUser"=dword:00000001`

On deleting these 2 extra values RDP Wrapper was able to work properly.

**Comment by binarymaster** [comment]
I thought so, that value was set by local and group policies.

Thanks!
