### ISSUE TITLE
VERSION 19042.1586

### ISSUE THREAD

**Issue by MartinTenorio** [stascorp/rdpwrap#1880]
Buenos días, alguien presenta el error que no soporta en esta versión de windows 19042.1586
Si alguien me puede ayudar se los agradecería mucho
Adjunto imagenes Gracias.
![rdp joel 1](https://user-images.githubusercontent.com/106760344/171663990-3b778c94-2afe-4799-a104-5f659c8b6162.png)
![rdp joel](https://user-images.githubusercontent.com/106760344/171663996-f043ee83-382b-4060-9822-23c67c1d0273.png)

**Comment by sashaqwert** [comment]
RDP Wrapper and termService deleted by antivirus.

try restore backup from original (clean) OS
Windows 10 21H1 [here](https://t.me/rdpwrap/38026)Windows 11 21H2 [here](https://t.me/rdpwrap/40042)
Windows 10 LTSC 1809 [here](https://t.me/rdpwrap/41015)Restoring a registry branch from a backup:
1. Download `.reg` file
2. Open this (dual left click)
3. Press yes
4. Reboot

After following these instructions, you need to reinstall RDP Wrapper.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1883
