### ISSUE TITLE
Not supported [10.0.19041.1741] x86 (32 bits)

### ISSUE THREAD

**Issue by r-troncoso** [stascorp/rdpwrap#1882]
Not supported [10.0.19041.1741] x86 (32 bits)

Thank you

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8830896/termsrv.zip)

**Comment by r-troncoso** [comment]
![2022-06-03 105225](https://user-images.githubusercontent.com/104627081/171822542-4b486d88-6f48-40ef-bb47-b4700b09edce.jpg)

**Comment by sebaxakerhtc** [comment]
The offsets was added
Applicable to https://github.com/stascorp/rdpwrap/issues/1881
