### ISSUE TITLE
[NOT SUPPORTED]

### ISSUE THREAD

**Issue by zenusop** [stascorp/rdpwrap#1888]
**Hi, I need help with RDP Wrapper.** 

When I open RDP Wrapper it says [Not Supported] in the states. I'm using winver 21H2 Ver 19044.1741
. Does anybody know how to fix it? or have the updated ini file.

Or does somebody have the ini file for a newer version of windows I can have.

Another issue i'm facing is that when i do open Remote Desktop it lets me sign in, but then it says acsess denied. I think that might be because the first issue i'm facing.

**Comment by sebaxakerhtc** [comment]
> **Hi, I need help with RDP Wrapper.**
> 
> When I open RDP Wrapper it says [Not Supported] in the states. I'm using winver 21H2 Ver 19044.1645. Does anybody know how to fix it? or have the updated ini file.
> 
> Or does somebody have the ini file for a newer version of windows I can have.
> 
> Another issue i'm facing is that when i do open Remote Desktop it lets me sign in, but then it says acsess denied. I think that might be because the first issue i'm facing.

Attach you RDPConf screenshot, please

**Comment by zenusop** [comment]
Okay. I wil in a bit I'm busy at the moment, but with do asap. btw thank you for helping me :)

**Comment by zenusop** [comment]
![Screenshot 2022-06-04 145323](https://user-images.githubusercontent.com/75637878/172025160-e54be365-98bb-4138-93df-b17e3175d070.png)

I actually have windows 10 version 19044.1741 also i have a 64x bit cpu if that matters at all

**Comment by sebaxakerhtc** [comment]
> I actually have windows 10 version 19044.1741

You have luck - your version is supported
https://github.com/stascorp/rdpwrap/issues/1881
