### ISSUE TITLE
10.0.17763.2989 not listened

### ISSUE THREAD

**Issue by 0Zaporozhec0** [stascorp/rdpwrap#1889]
please help! new update windows 10 ltsc, and didnt work 2989 (((
![Безымянный](https://user-images.githubusercontent.com/106913100/172049329-50fe028e-11ce-4067-97ab-309ef4463742.jpg)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1869

**Comment by sebaxakerhtc** [comment]
> Duplicate of #1869
