### ISSUE TITLE
No ver. is detected and support level issue

### ISSUE THREAD

**Issue by warminwinter2025** [stascorp/rdpwrap#1895]
Hi，Experts.

   My computer RDP checks no ver. and support level
   How to solve it?

![image](https://user-images.githubusercontent.com/102196877/173267562-1c834110-d5b7-43af-9589-bcdb3ef60663.png)

![image](https://user-images.githubusercontent.com/102196877/173268199-c7ff514b-66f6-4141-87a5-6f776d5321b0.png)

**Comment by guoming1987** [comment]
the same

**Comment by sashaqwert** [comment]
Your issue is https://github.com/stascorp/rdpwrap/issues/1883

`rdpwrap.ini` also deleted by antivirus.

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/1883

**Comment by rabbit-dayi** [comment]
I managed to fix this following a guide from a CSDN blog<https://blog.csdn.net/m0_53401243/article/details/126150791> post. Here is the summary for anyone facing the same issue:

**The Issue:**

* **Service state:** `ver. N/A`
* **Listener state:** `not listening [support level]`

**The Solution:**

The core issue is usually a missing or mismatched configuration for your specific Windows version.

0. run
```bash
dism /online /cleanup-image /restorehealth
sfc /scannow
```

1. **Find your specific version:**
* Run `uninstall.bat`.
* Run `install.bat`.
* **Watch the console output closely.** Look for a "Terminal Services not supported" error. It will list a specific version number (e.g., `10.0.22000.708`). Note this down.


2. **Update Configuration (Method 1 - Service Restart):**
* Go to `services.msc` and stop **Remote Desktop Services**.
* Get the latest `rdpwrap.ini` content (make sure your version number from Step 1 exists in the file).
* Replace the content of `C:\Program Files\RDP Wrapper\rdpwrap.ini` with the new content.
* Manually start the **Remote Desktop Services**.
* Check `RDPConf.exe`.


3. **Update Configuration (Method 2 - Offline Install):**
* *If Method 1 fails.*
* Copy the latest `rdpwrap.ini` content into the `rdpwrap.ini` file located in your installation folder (same folder as `install.bat`).
* Run `uninstall.bat`.
* **Disconnect your Internet** (Crucial: prevents the installer from fetching the old 2017 config).
* Run `install.bat`.
* Reconnect Internet.


4. **Result:**
* It is now working!
* **Note:** It might still show `[support level]` in the status, but `RDPCheck.exe` connects successfully.
* Regarding the `[support level]` display issue, refer to #1883.



*(Source/Credit: [https://blog.csdn.net/m0_53401243/article/details/126150791](https://blog.csdn.net/m0_53401243/article/details/126150791))*
