### ISSUE TITLE
Não suportado WIN10 21H2 19044.1741

### ISSUE THREAD

**Issue by fernandohcmelo** [stascorp/rdpwrap#1896]
Olá, alguém teria essa versão atualizada ?

**Comment by fernandohcmelo** [comment]
![not](https://user-images.githubusercontent.com/61550415/173351374-7a8c8eaa-dfcb-42aa-bab4-50c0fc5f26d0.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by MKKLR21** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8907813/termsrv.zip)
Here's the termsrv.dll

**Comment by sebaxakerhtc** [comment]
> Duplicate of #1881
