### ISSUE TITLE
ver. 10.0.190.41.1741 Listening but not supported

### ISSUE THREAD

**Issue by CHSsamchan** [stascorp/rdpwrap#1902]
I have found a solution in #1881 are same case to me, yet replacing the rdpwrap.ini doesn't work.

I am sure the rdpwrap.ini including the above ver.'s setting.

I have checked the latest released rdpwrap.ini by [sebaxakerhtc](https://github.com/sebaxakerhtc), yet still no help.

Enclosed attached termsrv.dll for reference.

![10 0 1904 1741](https://user-images.githubusercontent.com/107601801/173990598-cbad1c06-2d48-4714-b074-6b27966b50df.png)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8915643/termsrv.zip)

**Comment by sebaxakerhtc** [comment]
> I have checked the latest released rdpwrap.ini by [sebaxakerhtc](https://github.com/sebaxakerhtc), yet still no help.

It's impossible. At least you should see "fully supported". Replace the file after stopping termservice or use my modded version.
Applicable to https://github.com/stascorp/rdpwrap/issues/1881

**Comment by CHSsamchan** [comment]
It's really not supported until now.

I have go through with your guideline(net start termserivce -> replaced  rdpwrap.ini -> net start termserivce), yet doesn't help.

Even pass over the update process to the autoupdate task, still not work.
Enclosed attached the log of the autoupdate services.
It showed the rdpwrap.ini is up-to-date also yet the configuration still show not supported.
![autoupdate](https://user-images.githubusercontent.com/107601801/174056504-44453cf7-63c4-4ccd-a11d-c955cb2c6be8.png)

There's some trouble this morning, I don't know is it related to this problem.
The service state is showed unknown this morning.
I tried to uninstall or reinstall the library in vain, it would stop and showed term service can not found.

Then after serval hours with reboot times and times, it becomes Running again, yet it showed not supported until now.
I can reinstall the library right now but it doesn't help.

rdpwrap.ini is updated to 2022-06-16, and I double checked the ver. 10.0.19041.1741 is on list.

**Comment by sebaxakerhtc** [comment]
> rdpwrap.ini is updated to 2022-06-16, and I double checked the ver. 10.0.19041.1741 is on list.

Did you try reboot?
Do you have the same in after reboot?

**Comment by CHSsamchan** [comment]
> > rdpwrap.ini is updated to 2022-06-16, and I double checked the ver. 10.0.19041.1741 is on list.
> 
> Did you try reboot? Do you have the same in after reboot?

Yes, I have tried reboot in following step:

net stop -> replace ini -> net start -> reboot = no help
net stop -> replace ini -> reboot -> = termservice auto re-run and no help
net stop -> run autoupdate.bat and update.bat with admin rights -> net start -> reboot = no help
net stop -> run autoupdate.bat and update.bat with admin rights -> reboot = termservice auto re-run and no help

**Comment by LehtinenLab** [comment]
I am experiencing the same issue as @CHSsamchan. I have also tried fully uninstalling and reinstalling rdpwrap overall, in addition to the permutations of replacing ini and rebooting mentioned above.

![image](https://user-images.githubusercontent.com/69822120/174353728-8cf4f633-6b21-4e76-936e-5768f492a9c2.png)

**Comment by sebaxakerhtc** [comment]
> tried fully uninstalling and reinstalling

Just try my mod then

**Comment by CHSsamchan** [comment]
> > tried fully uninstalling and reinstalling
> 
> Just try my mod then

Tried your mod and fixed! Thanks a lot.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1881
