### ISSUE TITLE
RDP Checker works but has no Login Page found

### ISSUE THREAD

**Issue by warminwinter2025** [stascorp/rdpwrap#1903]
RDP Checker works,

There is no login page to enter password into the Desktop. 

Only the bottom in  the red box can works

![image](https://user-images.githubusercontent.com/102196877/174005692-dfcc02fe-8488-4e86-befd-04aa0b2ef01f.png)

**Comment by sebaxakerhtc** [comment]
RDPChecker is buggy. Please use mstsc 127.0.0.1 instead

**Comment by sashaqwert** [comment]
You need to [convert your Microsoft account to local account](https://www.windowscentral.com/how-switch-local-account-microsoft-account-windows-10).
