### ISSUE TITLE
No login possible

### ISSUE THREAD

**Issue by teckau** [stascorp/rdpwrap#1905]
Hi!

I have 10.0.22000.708 and patched the ini. I get a "fully supported". Though I cannot use mstsc to connect. I get a login-like display with power on/off but no login. After a while the window closes. I guess I am just missing something here, what should I do?

**Comment by iainheng** [comment]
I am having the same issue on Windows 10 

Edition	Windows 10 Pro
Version	21H1
Installed on	‎9/‎19/‎2020
OS build	19043.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by sashaqwert** [comment]
> I get a login-like display with power on/off but no login. After a while the window closes. 

You need to [convert your Microsoft Account to a local account](https://support.microsoft.com/en-us/windows/switch-your-windows-10-device-to-a-local-account-eb7e78a9-88ee-9bc3-8f06-831b56e339fd).

winlogon auto-disconnect RDP timeout (without any actions) = 30 seconds.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1868
