### ISSUE TITLE
Not Supported 10.0.22000.739

### ISSUE THREAD

**Issue by myoldcat** [stascorp/rdpwrap#1906]

**Comment by huray11** [comment]
the same problem

**Comment by sashaqwert** [comment]
Your version is 10.0.22000.708

<details>
<summary>termsrv.dll version != Windows version</summary>

![изображение](https://user-images.githubusercontent.com/24974508/174432451-bd453da8-0bb1-48ad-9e8b-7e0872d52a38.png)

</details>

Duplicate of https://github.com/stascorp/rdpwrap/issues/1868

**Comment by ZOAR05** [comment]
Same  here.  10.0.22000.739 
RDP version is 10.0.22000.708
STATUS fully supported.
But  still can't use multiple users.

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1868
