### ISSUE TITLE
Norton reporting virus and deleting files when I extract all on 1.6.1

### ISSUE THREAD

**Issue by wolfsonga** [stascorp/rdpwrap#191]
Hi,
  I just downloaded v1.6.1 and when I extracted all, norton deletes two of the executables as being infected. Is this the case or is this a false positive and I need to disable norton during the extract all process?
=gerry=

**Comment by binarymaster** [comment]
Hello!

If you're downloaded the release from official [releases section](https://github.com/stascorp/rdpwrap/releases), then it is a false positive.
