### ISSUE TITLE
RDP 3389

### ISSUE THREAD

**Issue by LinkPro666** [stascorp/rdpwrap#1910]
Подскажите пожалуйста на порте 3389 все работает отлично, только я ставлю любой другой порт нет подключения, но при этом RDPConf показывает что все хорошо, RDPCheck на локальной машине тоже работает , но даже внутри сети я не могу подключиться к серверу в самом RDP Wrapper соответственно стоит порт  какой мне нужен (новый). Перезагрузка не помогает ....куда копать возможно сталкивался кто-то

**Comment by sashaqwert** [comment]
В брандмаузере Windows изначально открыт порт 3389.
Для любого другого нужно [самостоятельно создать правила](http://wiki.amperka.ru/articles:net-port-opening?ysclid=l4p9m0ji0381998017) TCP/UDP аналогично тем, что уже имеются для порта 3389.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/86
