### ISSUE TITLE
10.0.19043.1766  Not supported

### ISSUE THREAD

**Issue by shaozhuyong** [stascorp/rdpwrap#1911]
10.0.19043.1766  Not supported 

![image](https://user-images.githubusercontent.com/20103939/174937576-c588c595-d4ef-4bf1-ae7f-d3d25cbe85b1.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881
