### ISSUE TITLE
rdpconf service ver N/A HELP!

### ISSUE THREAD

**Issue by ariexlin** [stascorp/rdpwrap#1913]
I updated my win11 into ver: 22000.739, rdpwrap service goes wrong, ver. N/A. 
I have tried to place the new rdpwrp ini 10.0.22000.708  - it still can't work..
How to fix it, thank you so much!

![rdp的副本](https://user-images.githubusercontent.com/108053863/175241111-1e0d3972-a9ed-4742-b719-5584946e065f.png)
﻿

**Comment by sebaxakerhtc** [comment]
The answer is here https://github.com/stascorp/rdpwrap/issues/1883

**Comment by nanbeichao** [comment]
I have the same problem with you,@win11.  #1833 failed to solve this problem, may I ask how you deal with it, have you solved it?

**Comment by ariexlin** [comment]
Run install file as administrator..

----- 原始邮件 -----
发件人：nanbeichao ***@***.***>
收件人：stascorp/rdpwrap ***@***.***>
抄送人：ariexlin ***@***.***>,  Author ***@***.***>
主题：Re: [stascorp/rdpwrap] rdpconf service ver N/A HELP! (Issue #1913)
日期：2022年07月16日 18点44分


I have the same problem with ***@***.***  #1833 failed to solve this problem, may I ask how you deal with it, have you solved it?

**Comment by nanbeichao** [comment]
Thank you for your advice！ I tried, but the problem persisted. Now I have restored Windows 10 and everything is working fine in Windows 10.



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 27, 2022 15:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [stascorp/rdpwrap] rdpconf service ver N/A HELP! (Issue #1913)




 
 Run install file as administrator..
 
 ----- 原始邮件 -----
 发件人：nanbeichao ***@***.***&gt;
 收件人：stascorp/rdpwrap ***@***.***&gt;
 抄送人：ariexlin ***@***.***&gt;,  Author ***@***.***&gt;
 主题：Re: [stascorp/rdpwrap] rdpconf service ver N/A HELP! (Issue #1913)
 日期：2022年07月16日 18点44分
 
 
 I have the same problem with ***@***.***  #1833 failed to solve this problem, may I ask how you deal with it, have you solved it?
