### ISSUE TITLE
10.0.14393.4169 Not Supported

### ISSUE THREAD

**Issue by Th0rules** [stascorp/rdpwrap#1914]
Its fine but no works ! ! 
![rdpwar](https://user-images.githubusercontent.com/38351478/175347566-71886aad-4470-4d25-b4d4-b012207e3100.png)
!

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1511

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1511
