### ISSUE TITLE
Installation Error OpenKeyReadOnly error (code 0)

### ISSUE THREAD

**Issue by NetworkGuy149** [stascorp/rdpwrap#1915]
I get this error when trying to install.  
**OpenKeyReadOnly error (code 0)**

I have turned off BitDefender and run the bat with Admin privileges. I also tried adding exceptions to BitDefener, but that did not seem to help.

Suggestions?

**Comment by sashaqwert** [comment]
> Suggestions?

Solution here https://github.com/stascorp/rdpwrap/issues/1883

**Comment by NetworkGuy149** [comment]
My issue does not match any of the above.
![RDPWrap 1](https://user-images.githubusercontent.com/22349492/175769939-d19b9ee9-05a7-4ac8-b812-dba6019a3e0c.png)

**Comment by sashaqwert** [comment]
Try solution from problem 2

**Comment by NetworkGuy149** [comment]
The reg entry for TermServices was damaged. I restored it and ran the installer again and got this result.
![RDPWrap 2](https://user-images.githubusercontent.com/22349492/175772350-b13e4724-1c9a-4908-9583-574774f3dbfc.png)
![RDPWrap 3](https://user-images.githubusercontent.com/22349492/175772352-8effce88-2b6f-413f-96c5-e5c1bd46a444.png)

**Comment by sashaqwert** [comment]
Rebooted PC (after restoring)?
RDPConf screenshot, please!

**Comment by NetworkGuy149** [comment]
Here is the sequence of what I just did:

1) Restored Registry entry from the downloaded zip
2) Rebooted PC 
3) Checked Services for Remote Desktop Services, It was stopped so I tried to start it and got this error.
![RDPWrap 11](https://user-images.githubusercontent.com/22349492/175776033-dbb8843b-ddcc-4514-ba7e-7db3821ce991.png)

4) Checked TermService in Registry
![RDPWrap 12](https://user-images.githubusercontent.com/22349492/175776084-2e53fdef-2ce3-40ed-941a-7cc308ffe4fa.png)

5) Checked RDPWConf
![RDPWrap 13](https://user-images.githubusercontent.com/22349492/175776106-51284a4b-4be9-49c9-ac5d-f1adb79a3a03.png)

6) Ran Install.bat as administrator
![RDPWrap 14](https://user-images.githubusercontent.com/22349492/175776130-1307841e-1b17-4de8-ba1a-e7064170c4fd.png)

7) Checked RDPWInst
![RDPWrap 15](https://user-images.githubusercontent.com/22349492/175776147-3ec14943-95d5-426a-83a6-7e2f48768367.png)


I am an IT guy. It looks like it is not installing for some reason. I changed security on the directory to ensure R/W access. The only other different. I think it might be related to the fact that I am not able to start TermService from the services tab. 

Thanks for your help.

**Comment by sashaqwert** [comment]
see https://github.com/stascorp/rdpwrap/issues/1821

**Comment by NetworkGuy149** [comment]
This is totally frustrating. I have RDS working on another Windows 11 machine, so I exported the registry entries for TermService.

Following the steps in #1821 on the problem machine i did the following:
- I first totally uninstalled BitDefender. 
- Rebooted PC.
- Imported the registry entries from the working machine.
- From elevated cmd, ran **SFC /scannow**
- Rebooted PC.
- Used services to try to manually start TermService 

And I still get the error that it will not start. 
![RDPWrap 21](https://user-images.githubusercontent.com/22349492/175779975-0b072b09-8dc7-4188-ac20-2a5c032515d9.png)

Other than reinstalling Windows, I am not sure where to go next. :-(

**Comment by sebaxakerhtc** [comment]
> Other than reinstalling Windows, I am not sure where to go next. :-(

Restore point. Or no way

**Comment by NetworkGuy149** [comment]
This is not my day. It is a new system and when they configured it, they did not turn on Restore Points.

**Comment by sebaxakerhtc** [comment]
> This is not my day. It is a new system and when they configured it, they did not turn on Restore Points.

So... Don't use BitDefender and add exclusions for RDPWrapper

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/1883
