### ISSUE TITLE
rdp in windows 10 home is not enabled , why?

### ISSUE THREAD

**Issue by mohammed-sec2010** [stascorp/rdpwrap#1917]
Hi 
I attached my termsrv 

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8986582/termsrv.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823
