### ISSUE TITLE
10.0.19041.1741 NOT SUPPORT

### ISSUE THREAD

**Issue by EnigmAze** [stascorp/rdpwrap#1918]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9012007/termsrv.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881
