### ISSUE TITLE
miss ver 

### ISSUE THREAD

**Issue by ozone521** [stascorp/rdpwrap#1919]
![image](https://user-images.githubusercontent.com/38352004/176985785-3f425f6f-0ab8-4df5-8516-8d3ebde772ef.png)
I can't find ver

**Comment by sashaqwert** [comment]
Please, check your antivirus.
Try `sfc /scannow`.

Is RDP Wrapper works for you? (multi-session works?)

**Comment by sashaqwert** [comment]
Try solutions from https://github.com/stascorp/rdpwrap/issues/1883

Without reply this will closed tomorrow.

**Comment by ozone521** [comment]
scf is closed



---- Replied Message ----
| From | Alexandr ***@***.***> |
| Date | 07/02/2022 15:25 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [stascorp/rdpwrap] miss ver (Issue #1919) |

Please, check your antivirus.
Try sfc /scannow.

Is RDP Wrapper works for you? (multi-session works?)

**Comment by sashaqwert** [comment]
As Administrator?

**Comment by ozone521** [comment]
yes



---- Replied Message ----
| From | Alexandr ***@***.***> |
| Date | 07/02/2022 15:55 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [stascorp/rdpwrap] miss ver (Issue #1919) |

As Administrator?

**Comment by sashaqwert** [comment]
If sfc does not work on your system (in CMD or Powershell), then your Windows is corrupted.
You need to install Windows from original ISO or build from UUP.

The original images can be downloaded here: https://www.microsoft.com/en-us/software-download/

**Comment by sashaqwert** [comment]
Partially applicable to https://github.com/stascorp/rdpwrap/issues/1883

Closed because systems that fail integrity for unknown reasons are not supported.
