### ISSUE TITLE
10.0.19041.1023 all green but dosen't work

### ISSUE THREAD

**Issue by taoz66** [stascorp/rdpwrap#1920]
![image](https://user-images.githubusercontent.com/100069971/177269405-334de63e-fe6a-4e73-9f27-d3b49b11ddda.png)
All look good but dosen't work.
I have already replaced the rdpwrap.ini and then Diagnotics all turned green. 
![image](https://user-images.githubusercontent.com/100069971/177269711-5a47520b-bc58-4fa2-8d24-aa897c858db4.png)
I have restarted the remote desktop service. But it still says it is inaccesible.

**Comment by taoz66** [comment]
it works!! although the check.exe says inaccissable. but it works on my ipad. thanks.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1420
