### ISSUE TITLE
10.0.19043.1766 Not supported

### ISSUE THREAD

**Issue by xnicox123** [stascorp/rdpwrap#1921]
10.0.19043.1766 Not supported

**Comment by xnicox123** [comment]
Microsoft Windows [Versión 10.0.19043.1766]
(c) Microsoft Corporation. Todos los derechos reservados.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881
