### ISSUE TITLE
6.1.7601.24402 supported partially

### ISSUE THREAD

**Issue by MisterDuval** [stascorp/rdpwrap#1922]
![image](https://user-images.githubusercontent.com/66914/177738119-38387aa4-51ba-43d8-b97c-eb986d114f76.png)
You'll find termsrv.dll attached, thank you!
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9062141/termsrv.zip)

**Comment by sebaxakerhtc** [comment]
> You'll find termsrv.dll attached, thank you!

Please try these 3 configs and let me know if it work for you.
Start from 0
[configs.zip](https://github.com/stascorp/rdpwrap/files/9063253/configs.zip)

**Comment by MisterDuval** [comment]
well, the rdpwrap.ini was not updated in C:\Program Files\RDP Wrapper\, after getting it from the github repo, it is Fully Supported. Thanks for your help.
