### ISSUE TITLE
Logged off when the credentials are saved

### ISSUE THREAD

**Issue by 154945583** [stascorp/rdpwrap#1924]
Windows 10 Enterprise
I found a workaround.
When I login with the same user (IP:127.0.0.2 User:Dade,the current logon user is Dade) .I do not give the password. So it take me to the login screen at the computer . At that screen I give the password and it opens a new session even if that user(Dade) is alredy logon localy.Now All is work well

But If the credentials are saved (after checking 'remember me' while logging in).When I login with the same user (IP:127.0.0.2 User:Dade,the current logon user is Dade),then the console sessions disconnects and logged off

Is there any solution？

**Comment by sashaqwert** [comment]
The issue described is a known limitation of RDP Wrapper in client SKUs.
The problem is not observed on Windows Server.

> Is there any solution？

Alternative (offtopic): use Windows 10/11 Enterprise multi-session (ServerRdsh). You can find the keys on Google.
