### ISSUE TITLE
19044.1826 Not Supported

### ISSUE THREAD

**Issue by jikeidea** [stascorp/rdpwrap#1928]
help me

**Comment by jikeidea** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9101501/termsrv.zip)

**Comment by jikeidea** [comment]
![image](https://user-images.githubusercontent.com/43924085/178721888-2d42855b-aea6-4df5-adaa-b98e6e1f496f.png)

**Comment by jikeidea** [comment]
When I use this ini, it is fully supported in RDPConf, but only one user is allowed to be online remotely。
[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/9101596/rdpwrap.txt)

**Comment by binarymaster** [comment]
Duplicate of #1881.

**Comment by jikeidea** [comment]
I use the ini of #1881, but it doesn't work

**Comment by zldlhn** [comment]
> I use the ini of #1881, but it doesn't work

Have you found a solution? I have encountered the same problem
