### ISSUE TITLE
10.0.18362.267 not supported

### ISSUE THREAD

**Issue by littleyanglovegithub** [stascorp/rdpwrap#1932]
10.0.18362.267 not supported

**Comment by sashaqwert** [comment]
~~Please, attach your RDPConf screenshot and `termsrv.dll`.~~

**Comment by sashaqwert** [comment]
Offsets here: https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

I can't find first issue with correct title.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/871
