### ISSUE TITLE
win10  21H1 ver. 19043.1826 is not supported? #1826  is not listening. 

### ISSUE THREAD

**Issue by fernandokosta** [stascorp/rdpwrap#1937]
Hi!
win10  21H1 ver. 19043.1826 is not supported? #1826  is not listening. 

Thanks

**Comment by sashaqwert** [comment]
RDPConf screenshot, please!

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881
