### ISSUE TITLE
Win 10 Ver 21H2 (OS Build 19044.1826)

### ISSUE THREAD

**Issue by jpass022** [stascorp/rdpwrap#1938]
Need configuration for this Windows build. attached is termserv.dll...
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9161091/termsrv.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by jpass022** [comment]
Installed your "RDP Wrapper Library mod v1.8.8.7", doesn't allow multiple users simultaineously...

**Comment by jpass022** [comment]
got it, had to deactivate AV while installing... thanks...

**Comment by sashaqwert** [comment]
@jpass022 
> Installed your "RDP Wrapper Library mod v1.8.8.7"

This is a @sebaxakerhtc mod.

> doesn't allow multiple users simultaineously...

Try reboot or restart service.
