### ISSUE TITLE
is 26 juli 2022 previeuw update win10 KB5015878    

### ISSUE THREAD

**Issue by nattlip** [stascorp/rdpwrap#1943]
is 1904(3,2,1).1865 already supprorted , or is there no termsrv.dll update in it ?

**Comment by sashaqwert** [comment]
RDPConf screenshot, please!

**Comment by sashaqwert** [comment]
Closed because there is not enough information to determine the version `termsrv.dll`.
Without this information, it is very difficult to determine whether your version of termsrv is supported or not.

**Comment by nattlip** [comment]
i ask this before i install the new kb, maybe someone did and has the missing info
