### ISSUE TITLE
can't connect again after disconnect / working in windows 10 pro

### ISSUE THREAD

**Issue by youssfreda** [stascorp/rdpwrap#1946]
after I connect for first time if I disconnect I can't connect again

**Comment by sashaqwert** [comment]
RDPConf screenshot, please!

**Comment by youssfreda** [comment]
![aa](https://user-images.githubusercontent.com/56658455/182028540-ecfd30eb-abe0-41f4-9492-4ea2b6afd762.jpeg)
@sashaqwert

**Comment by sashaqwert** [comment]
Try `sfc /scannow` (in CMD as Administrator)
or restart service after error.

If your OS is using for RDP users only - try Windows 10/11 Enterprise multi-session (without RDP Wrapper)

```
slmgr.vbs /ipk CPWHC-NT2C7-VYW78-DHDB2-PG3GK
```

**Comment by youssfreda** [comment]
@sashaqwert 
okay thanks a lot

**Comment by sashaqwert** [comment]
One `termsrv.dll` version = one opened issue --> closed.

This version discussed in https://github.com/stascorp/rdpwrap/issues/1881
