### ISSUE TITLE
how to fix not listening / service state stopped

### ISSUE THREAD

**Issue by mroook** [stascorp/rdpwrap#1947]
![image](https://user-images.githubusercontent.com/110442940/182289755-2732688b-e52d-4664-b5ee-ad568c27f76c.png)

**Comment by mroook** [comment]
when i try to start termservice it shows System error 126 has occurred. and that the spectied module could not be found how to fix

**Comment by sashaqwert** [comment]
What is your version of `RDPWrap.dll` (`1.5.0.0` or `N/A`)?

**Comment by mroook** [comment]
wdym by that

**Comment by mroook** [comment]
the probblem is i cant get the rdpwrap dll anymore also the ini

**Comment by mroook** [comment]
but i used the 
RDPWrap-v1.6.2

**Comment by sashaqwert** [comment]
> the probblem is i cant get the rdpwrap dll anymore also the ini

solution in https://github.com/stascorp/rdpwrap/issues/1883

**Comment by mroook** [comment]
yesterday i delted erverything also the rdp wrapper folder when i try to reinstall im not getting the rdp folder with the ini file and dll anymore so can i still use it

**Comment by mroook** [comment]
![image](https://user-images.githubusercontent.com/110442940/182411342-2adaa6b8-a1e9-4081-9765-f4931d811500.png)

**Comment by mroook** [comment]
what to do ?

**Comment by sashaqwert** [comment]
> what to do ?

Please, execute `install.bat` as Administrator.

**Comment by mroook** [comment]
![image](https://user-images.githubusercontent.com/110442940/182412255-36d9a73b-13d1-431f-a718-4ec4e9c79ffd.png)

**Comment by mroook** [comment]
so now it say this but i cant find the folder with the dll and the ini

**Comment by sashaqwert** [comment]
> so now it say this but i cant find the folder with the dll and the ini

Do this and reboot https://github.com/stascorp/rdpwrap/issues/384#issuecomment-355833698

**Comment by mroook** [comment]
ok what now

**Comment by mroook** [comment]
![image](https://user-images.githubusercontent.com/110442940/182414695-1bc19189-5e28-41ac-990a-81525a92fa0f.png)

**Comment by mroook** [comment]
for some reasons i cant drag this in the othere folder

**Comment by mroook** [comment]
![image](https://user-images.githubusercontent.com/110442940/182416700-0ed37f98-c942-4f7e-b2ca-5f10e17dcb5d.png)

**Comment by mroook** [comment]
how fix?

**Comment by mroook** [comment]
![image](https://user-images.githubusercontent.com/110442940/182419407-44af64ee-42a1-4693-a228-cc8d2b191d81.png)

**Comment by mroook** [comment]
ok well this is idk what donno how to get that

**Comment by sashaqwert** [comment]
> how fix?

You need to update INI https://github.com/stascorp/rdpwrap/issues/1881

> ok well this is idk what donno how to get that

CMD as Administrator --> `net start termService`.

**Comment by sashaqwert** [comment]
This discussion is long.
[Telegram chat](https://t.me/rdpwrap) is recommended for this.

**Comment by sashaqwert** [comment]
> > the probblem is i cant get the rdpwrap dll anymore also the ini
> 
> solution in #1883

Closed (but not locked for comments)

**Comment by duduzai2019** [comment]
> net start termService

hi, how i can deal the service state to runing
![image](https://user-images.githubusercontent.com/96464964/187972770-df8bc430-e8e6-441a-9b04-3d2a525222aa.png)

**Comment by sashaqwert** [comment]
> > net start termService
> 
> hi, how i can deal the service state to runing
> ![image](https://user-images.githubusercontent.com/96464964/187972770-df8bc430-e8e6-441a-9b04-3d2a525222aa.png)
> 

https://github.com/stascorp/rdpwrap/issues/1883 --> problem 1

**Comment by duduzai2019** [comment]
> > > net start termService
> > 
> > 
> > hi, how i can deal the service state to runing
> > ![image](https://user-images.githubusercontent.com/96464964/187972770-df8bc430-e8e6-441a-9b04-3d2a525222aa.png)
> 
> #1883 --> problem 1

thank you your answer, i already solve it
