### ISSUE TITLE
question about getting RDP enabled on Windows 10 Home

### ISSUE THREAD

**Issue by gartha1** [stascorp/rdpwrap#1948]
Hi

I'm trying to get RDP enabled on Windows 10 Home

I tried running the MSI installation and something flashed up then I restarted but I see from ipconfig | findstr 3389 that windows remote desktop isn't started.

Then I looked here https://github.com/stascorp/rdpwrap/issues/885

It has a bunch of steps including extracting a zip and renaming an ini file, though there's no ini file in the zip.

I  look at the zip, it has an install.bat  I try that, still no listening on port 3389.

I try update.bat still no

I restart

still no

I try rdpconf.exe

https://i.imgur.com/vT7XWOt.png

wrapper state- installed
server state-running
listener state- not listening

also it says "[not supported]"

**Comment by gartha1** [comment]
okay got it, I had to extract it to C:\program files\RDPWrap  and put autoupdate.bat with it run that and then it was fine.

**Comment by sashaqwert** [comment]
Closed as solved.
