### ISSUE TITLE
Multiple user login after restart

### ISSUE THREAD

**Issue by suro7** [stascorp/rdpwrap#1951]
Hello. Is it possible to start more than one user session automatically after reboot? 
So system starts with user1 by default, and user2 is also logged in automatically.

Thanks

**Comment by sashaqwert** [comment]
Not RDP Wrapper issue. This problem also exists on RDS.

Solution:
bat script:

```
mstsc /v:127.0.0.2 ...
```
For correct arguments execute

```
mstsc /?
```

P.S: 127.0.0.2, 127.0.0.3, ... also localhost.
