### ISSUE TITLE
10.0.19041.1741 [Not supported] 

### ISSUE THREAD

**Issue by christian-westbrook** [stascorp/rdpwrap#1954]
File upload: [termsrv.zip](https://github.com/stascorp/rdpwrap/files/9278379/termsrv.zip)

**Comment by christian-westbrook** [comment]
Hello! GitHub says that it doesn't support .dll files. I'd like to upload my termsrv.dll file as requested under other issues.

Edit: Uploaded as a .zip!

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881
