### ISSUE TITLE
not listening not supported

### ISSUE THREAD

**Issue by Murdom42** [stascorp/rdpwrap#1955]
im on windows 10 home 21h2 19044.1889 

rdpwrap used to work for me before but today i tryed it and its not working

**Comment by sashaqwert** [comment]
RDPConf screenshot, please!

**Comment by lukmay** [comment]
I am facing the same problem. Here is the screenshot of my RDPConf.
![image](https://user-images.githubusercontent.com/86775313/184666141-762c7509-939f-4c90-b08d-1d852fa317a5.png)

**Comment by lukmay** [comment]
> im on windows 10 home 21h2 19044.1889
> 
> rdpwrap used to work for me before but today i tryed it and its not working

You can find the fix here.
https://github.com/stascorp/rdpwrap/issues/1881#issuecomment-1157218547
