### ISSUE TITLE
22000.778 [Not supported]

### ISSUE THREAD

**Issue by UshakovMa** [stascorp/rdpwrap#1956]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9310089/termsrv.zip)

**Comment by sashaqwert** [comment]
<details>
<summary>termsrv.dll info</summary>

![изображение](https://user-images.githubusercontent.com/24974508/184288541-c2add089-df33-43ef-89c7-9aff0fff5c15.png)

</details>

This will be closed (info in next comment)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1868
