### ISSUE TITLE
10.0.22000.856 [Not supported]

### ISSUE THREAD

**Issue by IsArsh** [stascorp/rdpwrap#1957]

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sebaxakerhtc** [comment]
> RDPConf screenshot

termsrv.dll version 22000.708
Looks like a duplicate of https://github.com/stascorp/rdpwrap/issues/1868

**Comment by sashaqwert** [comment]
> termsrv.dll version 22000.708
Looks like a duplicate of https://github.com/stascorp/rdpwrap/issues/1868
