### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by HugoYaw22** [stascorp/rdpwrap#1961]
hi, i follow the instruction and i think everyting is ok

![a](https://user-images.githubusercontent.com/80502098/184936272-a2eb9fa1-ff19-4508-b149-3f2752c986a7.png)

but when i test login with other user, windows still restrict me

![b](https://user-images.githubusercontent.com/80502098/184936417-56a3956b-3c60-4f15-9de4-4468108efdba.png)

what should i check?
thx before

**Comment by HugoYaw22** [comment]
i try to check with RDPCheck too, and it show same thing too
![c](https://user-images.githubusercontent.com/80502098/184937385-e7b065b2-2cc4-473f-be4c-a0efd05002e4.png)

**Comment by HugoYaw22** [comment]
https://github.com/stascorp/rdpwrap/issues/1815#issuecomment-1102253272

hey guys, its work. thx bro

**Comment by sashaqwert** [comment]
Closed as solved.
