### ISSUE TITLE
win 10 19043.1826 [not listening] and [not supported]

### ISSUE THREAD

**Issue by Imdyh** [stascorp/rdpwrap#1962]
win 10 19043.1826 [not listening] and [not supported] !
please help me ,thanks

![795d58684714d497b05ee5abaaf255e](https://user-images.githubusercontent.com/34771268/185030123-c6a2e838-66f1-4dd0-8444-7065933e82a5.jpg)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881
