### ISSUE TITLE
10.0.19041.964 not supported

### ISSUE THREAD

**Issue by TukangM** [stascorp/rdpwrap#1964]
![image](https://user-images.githubusercontent.com/91467886/185798165-4550db68-38d0-45fb-8767-0f6e205295ba.png)

windows 10 ghost spectre

**Comment by TukangM** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9389439/termsrv.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1384

**Comment by TukangM** [comment]
> Duplicate of #1384

thanks
![image](https://user-images.githubusercontent.com/91467886/186406234-65a9dd0f-a435-4af2-a40a-c8a4d03beda2.png)
