### ISSUE TITLE
10.0.18362.836 not supported

### ISSUE THREAD

**Issue by Gans2308** [stascorp/rdpwrap#1966]

**Comment by Gans2308** [comment]
I writted file, I have support, but connection was failed. Continue only  1 user((

**Comment by sashaqwert** [comment]
RDPConf screenshot, please!

Also this issue will closed tomorrow.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

I know, thet original issue has incorrect title.
