### ISSUE TITLE
I dont know what to do

### ISSUE THREAD

**Issue by Ttron420** [stascorp/rdpwrap#1969]
![image](https://user-images.githubusercontent.com/112292907/187053810-bc98c211-4c5a-4d45-bc2d-0ac327b87888.png)

**Comment by sashaqwert** [comment]
Try this command in CMD as Administrator

```
net start termService
```

**Comment by sashaqwert** [comment]
Solution in https://github.com/stascorp/rdpwrap/issues/1883 --> Problem 1
