### ISSUE TITLE
add option to allow standard users on W7 Home Premium to be logged into remotely

### ISSUE THREAD

**Issue by SimJoSt** [stascorp/rdpwrap#197]
With rdpwrap it's possible to make remote connections to a Windows 7 Home Premium Edition, even though RDP is normally not available on such systems.
Unfortunately, only admin users are permitted to receive remote connections. Even with a retrofitted gpedit.msc and making the needed security adjustments, to also let standard users accept remote connections, it did not work.

It would be great if rdpwrap made this configurable in the program. I have no idea how to implement this and have a strong feeling this is totally out of scope for the project, but atleat I wanted to suggest it.

**Comment by binarymaster** [comment]
See #107.
