### ISSUE TITLE
RDP is lagging from time to time

### ISSUE THREAD

**Issue by tr1pplexgod** [stascorp/rdpwrap#1971]
Hey, rdp session is lagging sometimes, one time it is flying, the other time it is lagging

**Comment by tr1pplexgod** [comment]
it doesn't matter what I'm doing, whether finding something in the browser or using the desktop

**Comment by sashaqwert** [comment]
Not a RDP Wrapper issue

**Comment by sashaqwert** [comment]
Try modify RDP graphics settings ([Enable/disable H.264](https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.TerminalServer::TS_SERVER_AVC_HW_ENCODE_PREFERRED), etc...)

Using H.264 will shift some of the work of rendering frames from the processor to the server's video card.

**Comment by tr1pplexgod** [comment]
> Try modify RDP graphics settings ([Enable/disable H.264](https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.TerminalServer::TS_SERVER_AVC_HW_ENCODE_PREFERRED), etc...)
> 
> 
> 
> Using H.264 will shift some of the work of rendering frames from the processor to the server's video card.

Thanks, i'll try it

**Comment by tr1pplexgod** [comment]
can't find this option
