### ISSUE TITLE
10.0.25188.1000 [not supported]

### ISSUE THREAD

**Issue by SinhoMoeme** [stascorp/rdpwrap#1975]

**Comment by sashaqwert** [comment]
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by SinhoMoeme** [comment]
> https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
Not working. It said "The number of connections to this computer is limited and all connections are in use right now."
I have set the number to 999999 via gpedit.msc.
![QQ截图20220901220258](https://user-images.githubusercontent.com/112635703/187934068-a53b0b92-a146-49a2-b369-a331a13d010b.png)
@sashaqwert

**Comment by sashaqwert** [comment]
Try restart termService

```
net stop termService
net start termService
```

Or reboot

**Comment by SinhoMoeme** [comment]
> Try restart termService
> 
> ```
> net stop termService
> net start termService
> ```
> 
> Or reboot

@sashaqwert This time, listener state is "Not listening".

**Comment by sashaqwert** [comment]
> This time, listener state is "Not listening".

After reboot same issue?

**Comment by SinhoMoeme** [comment]
> > This time, listener state is "Not listening".
> 
> After reboot same issue?

@sashaqwert Yes. Not listening.

**Comment by sashaqwert** [comment]
Try Autoupdate from https://github.com/stascorp/rdpwrap/pull/1160

**Comment by SinhoMoeme** [comment]
> Try Autoupdate from #1160

Not working again.

**Comment by sashaqwert** [comment]
Try modded version by sebaxakerhtc https://github.com/sebaxakerhtc/rdpwrap/releases

https://youtu.be/vtJ4Uqsa8fA

**Comment by SinhoMoeme** [comment]
> Try modded version by sebaxakerhtc https://github.com/sebaxakerhtc/rdpwrap/releases
> 
> https://youtu.be/vtJ4Uqsa8fA

I found that after updating rdpwrap.ini and restart termService, termService would crash and couldn't run correctly. However, after uninstalling RDP Wrapper, termService would run correctly. I don't know why.
