### ISSUE TITLE
Windows 10 64-bit version 10.0.19041.1741 not working

### ISSUE THREAD

**Issue by GeneXiao** [stascorp/rdpwrap#1979]
![rdpwrap](https://user-images.githubusercontent.com/100252418/188305664-07f44275-4b1b-459a-949e-e19ac6ed2bfe.png)

**Comment by QuentinBubu** [comment]
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881
