### ISSUE TITLE
Limit connected users #192

### ISSUE THREAD

**Issue by GARCIREPROMA** [stascorp/rdpwrap#198]
In reference to query # 192 I want to comment that I am not sure that it is a ram problem. I have installed 16 Gb
![imagen](https://cloud.githubusercontent.com/assets/25063497/22106528/5a96507c-de49-11e6-90aa-afda05c23f5a.png)
I have tried removing a memory card and left the computer in 8 GB. And still connect fifteen users (obviously the computer goes slower, but connect the same users as with 16 gb). 
I have seen that Rdpwraper only allows that number of connections and I have tried to uninstall Rdp wraper and try out the method of patching the termsrv.dll. But I still have the same problem. I have thought that it may be some limitation that has the windows registry. Any opinions on this?

**Comment by binarymaster** [comment]
First of all, you don't need to create issue duplicates. Just reopen existing.

If this is a software limitation, then it's placed somewhere else, and I doubt about registry.

Reopened #192.
