### ISSUE TITLE
Windows 10 Pro x 64 21H2 19044.1889 Fully supported but not working

### ISSUE THREAD

**Issue by jamaimac** [stascorp/rdpwrap#1981]
![rdp](https://user-images.githubusercontent.com/113380478/189723337-e1d0b5a1-c971-40a3-a479-764bc8c85f45.jpg)

when I want to log in another user appears:

![error2](https://user-images.githubusercontent.com/113380478/189723753-401898f1-d9f4-4801-888e-d95849598686.jpg)

I already tried modifying the maximum number of simultaneous connections to 999999 in GPEDIT, but the error continues, I appreciate any help

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by sashaqwert** [comment]
The connection problem described in this issue is resolved by restarting the service or rebooting.

**Comment by jamaimac** [comment]
> The connection problem described in this issue is resolved by restarting the service or rebooting.

I already restarted the computer and the service and still with the same problem.

I also tried reinstalling the RDP Wrapper, but that didn't work either.

Thank you

**Comment by wangchong33333** [comment]
you may install rdpwrap from https://github.com/sebaxakerhtc/rdpwrap/releases, not this repo

**Comment by eymenbilisim** [comment]
Windows 10 Pro x 64 21H2 19044.1889 oky.....
