### ISSUE TITLE
Switching between users freeze session

### ISSUE THREAD

**Issue by didli** [stascorp/rdpwrap#1983]
Hi to you all and first, thanks for RDPWrap.
While I've been able to install and use RDPWrap in Windows 11 pro lastest version 9xx something (still, conf says : not supported), I have an issue I'm not too sure where to start looking. I've created 2 admin users, and I'm starting 2 rdp sessions concurrently using port 3392 (I'm already wondering if it's not an issue to use the same port for the 2 sessions ?). 
As the 2nd session is opening, everything's fine, but if i switch back to the 1st user rdp session, everything is frozen, and I can't do anything except to disconnect.

Any idea what I'm doing wrong please ? Maybe there's an option I forgot to check ?
Thanks for your help !

**Comment by sashaqwert** [comment]
> conf says : not supported)

RDPConf screenshot, please!

> I have an issue I'm not too sure where to start looking.

You need `termsrv.dll` version from RDPConf not Windows version).

**Comment by didli** [comment]
hmm... oups. Everything pretty much solved.
- rdpconfig shows fully supported now :
![rdpwrap](https://user-images.githubusercontent.com/3301204/190523197-79cb7784-230c-4afb-b084-94a8d52245a6.png)
- the "freeze" issue is related to a strange behavior from remmina (linux remote desktop app) : the frozen session switch issue is still there but as a workaround, if I minimize and then maximize the rdp session window again, everything is fine. So it has nothing to do with Windows, much less RDPWrap ^^´.
Sorry for the noise. I'm closing this issue. Thank you for your answer !
