### ISSUE TITLE
having issues running the autoupdate.bat

### ISSUE THREAD

**Issue by payfast8898** [stascorp/rdpwrap#1984]
NOT found "termsrv.dll" version entry [10.0.19041.1949] in file "C:\Program Files\RDP Wrapper\rdpwrap.ini"!

keeps repeating waiting for network connection but it is connected to the network

**Comment by payfast8898** [comment]
We have had 5 computers now that can't update after the windows update so we have to restore them  back before the update

**Comment by sashaqwert** [comment]
> keeps repeating waiting for network connection but it is connected to the network

Not an RDP Wrapper issue. You can disable network check via editing the `.bat` file.

Discussion recommended in https://github.com/stascorp/rdpwrap/pull/1160
