### ISSUE TITLE
你的凭据不起作用  登录没有成功

### ISSUE THREAD

**Issue by wangji666666** [stascorp/rdpwrap#2000]
已经出现三个绿色，而且能够正常显示登录框了，但是用账号显示“你的凭据不起作用 “， WIN11登录用的本地系统账户，不是微软账户。如何解决登录问题？系统是WIN11家庭版，无法设置pgedit

**Comment by sashaqwert** [comment]
The title and first message must be only on English or Russian.

If you want to use other languages, please, use English or Russian in top. Another language can be added to the end of the message.

**Comment by sashaqwert** [comment]
Try connect via mstsc

Username: `PC-NAME\username`
Password: `your password`.

**Comment by wangji666666** [comment]
> Try connect via mstsc
> 
> Username: `PC-NAME\username` Password: `your password`.

i use this name and password ,but it no work, the message is same "你的凭据不起作用"  @sashaqwert

**Comment by wangji666666** [comment]
i change the username, but "DefaultAccount " username no change .so i user "DefaultAccount " username ,it works . thanks.
