### ISSUE TITLE
Does not work with Windows 11 10.0.25206

### ISSUE THREAD

**Issue by brendoncdrew** [stascorp/rdpwrap#2001]
OS Name:                   Microsoft Windows 11 Pro Insider Preview
OS Version:                10.0.25206 N/A Build 25206
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Checking for updates...
[*] Current update date: 2018.10.10
[*] Latest update date:  2018.10.10
[*] Everything is up to date.

Up to date but still doesn't work :(

**Comment by sashaqwert** [comment]
RDPConf screenshot, please!

**Comment by sashaqwert** [comment]
The version of termsrv.dll is not specified, without which it is difficult to answer the question without having the same version of Windows.

--> closed as incomplete.
