### ISSUE TITLE
need help not supported

### ISSUE THREAD

**Issue by THill246** [stascorp/rdpwrap#2007]
my rdp wrapper says not supported and when i try log in it says access denied can someone point me in the right direction on what to do cheers

**Comment by sashaqwert** [comment]
> my rdp wrapper says not supported

RDPConf screenshot, please!

**Comment by THill246** [comment]
![Desktop Screenshot 2022 10 01 - 10 25 05 33](https://user-images.githubusercontent.com/114803646/193402717-42494bc3-fc7e-496b-be7c-29a2adadc715.png)

**Comment by THill246** [comment]
> > my rdp wrapper says not supported
> 
> RDPConf screenshot, please!

![](https://user-images.githubusercontent.com/114803646/193402717-42494bc3-fc7e-496b-be7c-29a2adadc715.png)

**Comment by sashaqwert** [comment]
Your solution in https://github.com/stascorp/rdpwrap/issues/1968

You need to update the `rdpwrap.ini`
