### ISSUE TITLE
Question: why IDA says pdb not found sometimes, and how to deal with this

### ISSUE THREAD

**Issue by EdiTurn** [stascorp/rdpwrap#201]
Sometimes when I open termsrv.dll in IDA, it shows this error: 
![2017-01-21_14-32-36](https://cloud.githubusercontent.com/assets/5492805/22172599/7f5c8860-dfe6-11e6-9f67-85d70b115a3d.png)

And then the function names are like this: 
![2017-01-21_14-29-47](https://cloud.githubusercontent.com/assets/5492805/22172602/8c50bbea-dfe6-11e6-88ae-513ab800ef13.png)

Last week when I updated to 15007, I open the termsrv.dll (15007) and got this problem. 
After I update to 15014, I can open the old file from 15007 normally. But I get this problem again when I open termsrv.dll from 15014. 
So is there any way to solve this problem?

**Comment by binarymaster** [comment]
Try to use PDB downloader:
https://github.com/rajkumar-rangaraj/PDB-Downloader/releases

And place downloaded .pdb file in the same directory within .dll
