### ISSUE TITLE
10.0.17763.771 pls~

### ISSUE THREAD

**Issue by ygt1233211** [stascorp/rdpwrap#2011]
10.0.17763.771 pls~

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by BadAss-King** [comment]
Problem with Same Version

![image](https://user-images.githubusercontent.com/66208715/194580417-401cd5e3-ccd4-4000-9365-5ca4af69925b.png)

termsrv.dll>> https://we.tl/t-K1g1m837If

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1994

**Comment by sashaqwert** [comment]
> Problem with Same Version

`termsrv.dll` version ≠ Windows version.

If you think that it was closed by mistake, then attach the DLL and a screenshot of exactly the version that is in the name of isdue.
