### ISSUE TITLE
Need help with 10.0.17763.1369

### ISSUE THREAD

**Issue by EronHou** [stascorp/rdpwrap#2013]
![微信图片_20221011000618](https://user-images.githubusercontent.com/45758981/194909071-4b850dad-7f71-4ecb-ae78-413d37799f91.png)

**Comment by tetas26** [comment]
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1953
