### ISSUE TITLE
How do I install Termsrv.dll?  

### ISSUE THREAD

**Issue by ServerSheila** [stascorp/rdpwrap#2014]
I have been unable to get it to work.  
![image](https://user-images.githubusercontent.com/98594614/194935334-e93a49eb-8f40-4f99-ab13-98ec6f0a4d40.png)

Tried using autoupdater now I cannot start the service:
![image](https://user-images.githubusercontent.com/98594614/194935480-7a752101-2ba7-4e44-be88-8a931d630505.png)

**Comment by ServerSheila** [comment]
Manually updated ini file:
![image](https://user-images.githubusercontent.com/98594614/194935633-37b72686-b730-4ddb-9638-6645c7da0aae.png)

**Comment by tetas26** [comment]
Make sure both rdpwrap.dll and rdpwrap.ini are in the RDP Wrapper folder in Program Files

**Comment by sashaqwert** [comment]
Solution in https://github.com/stascorp/rdpwrap/issues/1883
