### ISSUE TITLE
10.0.22621.674

### ISSUE THREAD

**Issue by xiwuyun** [stascorp/rdpwrap#2018]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9782012/termsrv.zip)
Need help with 10.0.22621.674
Thank you

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006
Look at termsrv.dll version, not the Windows version

**Comment by xiwuyun** [comment]
> Duplicate of #2006 Look at termsrv.dll version, not the Windows version

Thank you
