### ISSUE TITLE
10.0.19041.2075 Fully supported, но не работает...

### ISSUE THREAD

**Issue by accountnujen** [stascorp/rdpwrap#2019]
![Снимок экрана 2022-10-14 135619](https://user-images.githubusercontent.com/91395439/195847306-ae80d469-f5d1-4d47-b743-3ca3516dd609.png)
делал по этому видео:
https://www.youtube.com/watch?v=3FsVZu5e9Js
Что я должен сделать ещё?

**Comment by sashaqwert** [comment]
Пользователь добавлен в группу "Администраторы" или "Пользователи удалённого рабочего стола"?

**Comment by accountnujen** [comment]
@sashaqwert у меня один пользователь... Admin...

короче говоря, я не понял, как эта фигня работает, поэтому возникли трудности. я думал будет по принципу TeamViewer и Anydesk, когда все, кто подключился - видят одно и тоже. По факту, создал нового пользователя и подключился на другой рабочий стол к тому же компьютеру. Всё у мера работает, но не так, как я предполагал...

Знающие, скажите пожалуйста, как сделать, чтобы одновременно и AnyDesk работает и я по RDP был подключён? Когда я подключён по RDP, а другой пользователь пытается зайти через AnyDesk, то **я не вижу** запрос на подключение. А если выдать пароль для AnyDesk, то при подключении через AnyDesk пользователь видит экран входа в систему. И если он входит, то меня выкидывает из RDP. Единственный вариант - оба подключены через AnyDesk, но это не так удобно... Есть варианты?

**Comment by sashaqwert** [comment]
> короче говоря, я не понял, как эта фигня работает, поэтому возникли трудности. я думал будет по принципу TeamViewer и Anydesk

Нет, это по принципу терминального сервера Windows Server, когда на одном компьютере сидит одновременно 123 человека и выполняют разные программы от имени одного или нескольких пользователей, при этом не мешая друг-другу.

>  По факту, создал нового пользователя и подключился на другой рабочий стол к тому же компьютеру.

Да. Так и предполагалось.

> как сделать, чтобы одновременно и AnyDesk работает и я по RDP был подключён?

Проблема RDP Wrapper заключается в том, что он просто запускает службу `termService` с параметрами, как у Windows Server с установленной ролью RDS, но другие компоненты системы об этом не знают (из-за чего, возможно, проблема с AnyDesk).

В Windows есть штатный аналог - [RDS shadow](https://winitpro.ru/index.php/2014/02/12/rds-shadow-v-windows-2012-r2/), который позволяет управлять сеансами в рамках той же машины или той же локальной сети. В качестве GUI можно использовать Terminal Services manager (для личного использования).

<details>
<summary>shadow подключение не из локальной сети</summary>

1. Подключиться по RDP как администратор
2. Запустить CMD от администратора
3. Ввести `qwinsta`
4. Найти ID нужной сессии
5. Ввести `mstsc /shadow ID` (`/v` в рамках одной машины не указывается)

</details>

Если нужен именно AnyDesk, то лучше рассмотреть смену редакции Windows, например на Windows 10/11 Enterprise multi-session (есть тема на ru-board). На той редакции RDP Wrapper не нужен и она имеет поведение серверной ОС.

**Comment by sashaqwert** [comment]
Этот issue изначально назван:
> 10.0.19041.2075 Fully supported, но не работает...

Что без учёта дальнейшего контекста должно было бы означать: Дубликат https://github.com/stascorp/rdpwrap/issues/1992.

Но, в данном случае закрыто, как решённое.

> Знающие, скажите пожалуйста, как сделать, чтобы .......

Для похожих вопросов лучше использовать Telegram чат (ссылка в README репозитория).
