### ISSUE TITLE
Tried to Install on Windows Server 2003 now RDP Broken

### ISSUE THREAD

**Issue by haney1981** [stascorp/rdpwrap#202]
I tried to install rdpwrap on a computer with Windows Server 2003 with fully reading the instructions that says it will not be supported. Now I cannot use Windows Remote Desktop to get into the computer at all. I uninstalled rdpwrap but now I have no I idea what to do to restore RDP on this computer. And yes I realize this is all my fault but any advice will be helpful. Please let me know what info is needed to help get this resolved.

**Comment by binarymaster** [comment]
Try to execute these commands:
```sh
reg add "HKLM\SYSTEM\CurrentControlSet\Services\TermService\Parameters" /v ServiceDll /t REG_EXPAND_SZ /d "%SystemRoot%\system32\termsrv.dll" /f 
reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
sc config termservice start= auto
sc start termservice
netsh firewall set service type = remotedesktop mode = enable
```

**Comment by binarymaster** [comment]
According to the commit https://github.com/stascorp/rdpwrap/commit/121f893c0c9adbcbc098628cc2c0822230386465 RDP Wrapper will no more install on incompatible systems.

**Comment by sskras** [comment]
@binarymaster, can I read somewhere what's the most difficult issues are when supporting compatibility with XP/S2003 ? I mean: is it just formal drop (due to theoretical increase in vulnerabilities) or maybe behaviour of some Windows component are getting harder to work around and if so, then what such behaviour / exact components are?

**Comment by binarymaster** [comment]
`termsrv.dll` logic is completely different in NT 5.x
