### ISSUE TITLE
RDPWrapper not support 19044.2130

### ISSUE THREAD

**Issue by EthanChenLi** [stascorp/rdpwrap#2024]
![image](https://user-images.githubusercontent.com/6337626/196669603-71c0df1b-d350-4b7b-b7aa-86892e01a694.png)

**Comment by maralboga** [comment]
now use installer to update INI file
https://github.com/stascorp/rdpwrap

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Comment by sashaqwert** [comment]
@maralboga 
> now use installer to update INI file
https://github.com/stascorp/rdpwrap

This version is not supported now officially --> MSI installer not support this version.
