### ISSUE TITLE
Not listening / Wrong version

### ISSUE THREAD

**Issue by mroook** [stascorp/rdpwrap#2028]

**Comment by mroook** [comment]
i need the ini for the new version

**Comment by mroook** [comment]
![image](https://user-images.githubusercontent.com/110442940/197358362-425e639c-7fa7-4ac2-ae6b-29efb050ce03.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992
