### ISSUE TITLE
RD client allow limits?

### ISSUE THREAD

**Issue by klabacita** [stascorp/rdpwrap#2029]
Hello guys.

I had a system that runs RDWrapper, but with 17+ windows start closing sessions, won't allow more that 16.
Exist a limit?
The machine has enough resources to manage that qty of users.

240GB RAM.

Some with more that 20+ running under windows  10 pro?

Regards!!!

**Comment by sashaqwert** [comment]
> I had a system that runs RDWrapper, but with 17+ windows start closing sessions, won't allow more that 16.
Exist a limit?

Link from issue in README https://github.com/stascorp/rdpwrap/issues/192

> The machine has enough resources to manage that qty of users.
>
> 240GB RAM.

In such a case, try installing Windows 10/11 Enterprise multi-session / Enterprise for Virtual desktops / ServerRdsh on this machine and check the hardware limitations.

Where to get an ISO or how to convert from another edition can be easily found on Google or on the My Digital Life forum.

**Comment by sashaqwert** [comment]
> Some with more that 20+ running under windows 10 pro?

From README:

> Up to [15 concurrent sessions](https://github.com/stascorp/rdpwrap/issues/192) (the actual limitation depends on your hardware and OS version)

Closed.

**Comment by ruixingchen** [comment]
my windows server 2022 datacenter reach a 52 user limit, 52 users logged in and just one RDP session allive, but windows does not allow me to login more users with RDP, but I can login more users with a physical mouse and keyboard connected to the server directly
