### ISSUE TITLE
32bit compatibility ?

### ISSUE THREAD

**Issue by alex-c3** [stascorp/rdpwrap#2032]
Not sure it's the place to post this question.

I need to run 16bit apps through RDP for multiple users, with WoW16 only being available on 32bit editions of W10.

RDPWrap works flawlessly on my 64bit system but every connection kicks out the previously logged user when trying on a 32bit VM of W10.

Is RDPWrap theoretically 32bit comptatible ? (All indicators are green, like in 64bit version which works - I'm using the appropriate latest .ini, or again, one that works in 64bit edition).

**Comment by sashaqwert** [comment]
> I need to run 16bit apps through RDP for multiple users, with WoW16 only being available on 32bit editions of W10.

Yes, RDP Wrapper support 32 bit (x86) Windows.

Please, send the RDPConf screenshot.

**Comment by alex-c3** [comment]
![image](https://user-images.githubusercontent.com/14188468/197722506-db5e113b-217c-4ad6-ad36-40095d84d359.png)

**Comment by sashaqwert** [comment]
Your version now supports x86

You can check this for any `termsrv.dll` version manually:

1. Open any INI (example https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini)
2. Press CTRL + F
3. Enter version
4. If you see a mention of x86 in the corresponding block, then there is support for this version in x86 (32 bit) systems.

```
[10.0.19041.789]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B59D9
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F41
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3BC45
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=0CA4C
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E7C9
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=67BF8
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize
```

As you can see above, x86 offsets are created for your version --> support will be.

**Comment by alex-c3** [comment]
Alright, thanks.

Do you know why I can't have multiple sessions then, as everything lights green ? Is there something else I must check ?

(EDIT: Note that it's an unactivated version of W10 Pro, although Windows does not yet complain about it !)

**Comment by sashaqwert** [comment]
> Do you know why I can't have multiple sessions then, as everything lights green ? Is there something else I must check ?

Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by alex-c3** [comment]
It works that way ! Thanks.

**Comment by sashaqwert** [comment]
Closed as solved.
