### ISSUE TITLE
10.0.19044.2130

### ISSUE THREAD

**Issue by harley-davidson-spb** [stascorp/rdpwrap#2034]
Unfortunately not working on Windows 10 Home
Version 21H2 (build 10.0.19044.2130)

![image](https://user-images.githubusercontent.com/70148481/198066125-0dcc8742-be51-421d-a475-ed4ce56dfe0c.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Comment by sashaqwert** [comment]
`termsrv.dll` version != Windows version!

Версия `termsrv.dll` и версия Windows это разные версии. Для поиска решения нужно использовать веррсию `termsrv.dll`, которая отображается в RDPConf.
