### ISSUE TITLE
Use RDPWrapper with Apache Guacamole

### ISSUE THREAD

**Issue by Bossxer** [stascorp/rdpwrap#2035]
Hello, Im trying to add an rdp connection to Apache Guacamole and I opened the port 3389 on my computer ip and im trying to add it as a connection on Apache Guacamole and it isnt working i tried my public ip and my computer ip nothing is working is it something with Apache Guacamole or RDPWrapper

**Comment by sashaqwert** [comment]
Your problem has to do with understanding how the RDP protocol itself works. RDP Wrapper is a wrapper over the `termsrv.dll` system library that allows you to remove license restrictions on the number of connections.

If your Apache Guacamole server is running on Windows, then first understand how the RDP protocol works.

Closed as not an issue with RDP Wrapper.
