### ISSUE TITLE
WIN 11可以帮做一个rdpwrwp.ini吗

### ISSUE THREAD

**Issue by zhenjianli** [stascorp/rdpwrap#2037]
WIN 11可以帮做一个rdpwrwp.ini吗

**Comment by zhenjianli** [comment]
WIN 11可以帮做一个rdpwrap.ini吗

**Comment by sashaqwert** [comment]
1. Wrong language in title and first message
2. What is your `termsrv.dll` version (Where RDPConf screenshot?)
