### ISSUE TITLE
RDP not listening, not supported, version - 1.5.0.0 and 10.0.19041.2075

### ISSUE THREAD

**Issue by Wcuhh** [stascorp/rdpwrap#2038]
RDP is not listening and its also not supported.
![image](https://user-images.githubusercontent.com/117530284/200128190-e02a3d62-c1c9-4779-9fb4-edeb63f259dc.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992
