### ISSUE TITLE
not listening

### ISSUE THREAD

**Issue by Wcuhh** [stascorp/rdpwrap#2039]
![image](https://user-images.githubusercontent.com/117530284/200133238-d8ae954e-fd48-4af7-af18-27f5258ee63c.png)
i need help

**Comment by sashaqwert** [comment]
One `termsrv.dll` version = one opened issue!!!

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992
