### ISSUE TITLE
It doesnt works for version 21h1 19043.2130

### ISSUE THREAD

**Issue by MeMikkhael** [stascorp/rdpwrap#2050]
Dont know why but it always gives the message: "wrong password" or says that all conections are being used.

**Comment by MeMikkhael** [comment]
ive searched in site and found another issue report, sorry for the double.

**Comment by MeMikkhael** [comment]
Dont know why but it always gives the message: "wrong password" or says that all conections are being used. (i've reopen cause the another issue report doesnt solved my problem.

**Comment by MeMikkhael** [comment]
![image](https://user-images.githubusercontent.com/79809114/203541613-1153b987-c81d-4d43-aa3e-bd64d2c54d2e.png)


[termsrv.zip](https://github.com/stascorp/rdpwrap/files/10075216/termsrv.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Comment by MeMikkhael** [comment]
Thank you @sashaqwert, i've found the asnwer in the #1992
