### ISSUE TITLE
19041.1741 fully supported but [ Not Listening]

### ISSUE THREAD

**Issue by songzenghui** [stascorp/rdpwrap#2053]
![Snipaste_2022-11-26_17-28-42](https://user-images.githubusercontent.com/25813311/204081937-14ab6997-a7ec-4fa5-8689-fb5a746abf55.png)

I have try replace ini file from [here](https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini),
and try `stop/start termservice` ,but it not worked

**Comment by sashaqwert** [comment]
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by sashaqwert** [comment]
> 10.0.19041.1741

One `termsrv.dll` version = ONE opened issue -->duplicate...

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by songzenghui** [comment]
thx, it worked
