### ISSUE TITLE
Windows 11 22621.819

### ISSUE THREAD

**Issue by Phreezi** [stascorp/rdpwrap#2054]
I get Access denied when using the RDPCheck.

RDPConf image below
![image](https://user-images.githubusercontent.com/119139017/204112921-6e8c79db-19b5-4fcb-a8d3-7590a5d44c54.png)

**Comment by gitgotgone** [comment]
I just installed it on fresh Win11.
You need to use the autoupdate to get the most recent ini

Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

![image](https://user-images.githubusercontent.com/19944415/204121553-87cf6840-600c-4612-8729-bc96e0f4a4b6.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006
