### ISSUE TITLE
Windows 10 Session Shadowing not working

### ISSUE THREAD

**Issue by mukowman** [stascorp/rdpwrap#206]
I am unable to get session shadowing working with Windows 10.
I have the below settings;
![rdp](https://cloud.githubusercontent.com/assets/1369447/22764742/a99e42ba-eec0-11e6-9241-f14d476c6734.png)

For testing I log into the console of the PC and then login via RDP using the same user, the console session gets kicked out and then if I log into the console the RDP session gets kicked.

I have tried with and without the user permission but I receive no prompt to allow shadowing.

**Comment by sharich** [comment]
Just disable single session by user and it will work.

**Comment by mukowman** [comment]
I removed this checkbox but now I have multiple sessions for the same user, definitely not shadowing the session.

**Comment by binarymaster** [comment]
@mukowman you're just doing it wrong. To shadow another active session you need to use `mstsc` with special parameters, see `README.md` for links.
