### ISSUE TITLE
Need help: 10.0.22621.900

### ISSUE THREAD

**Issue by SnowUnderwater** [stascorp/rdpwrap#2065]
Need rdpwrap.ini .

**Comment by SnowUnderwater** [comment]
Thank you.

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
`termsrv.dll` version != Windows version.

![изображение](https://user-images.githubusercontent.com/24974508/206903637-88365eb8-336f-470e-a554-a29414cf957b.png)

Your version: 10.0.22621.608

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Comment by SnowUnderwater** [comment]
Thank you. It can run now!
That's right:
![](http://22c-files-1.wdfiles.com/local--files/files%3Ahelloosme/rdp-termsrv)
