### ISSUE TITLE
Version wont work

### ISSUE THREAD

**Issue by JulianBorghuis** [stascorp/rdpwrap#2066]
![image](https://user-images.githubusercontent.com/40545968/207132936-af1d5203-9629-4dd2-aee7-3db6d3c1c958.png)
Can i get an version for this?

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
`termsrv.dll` version != Windows version.
![Снимок экрана 2022-12-13 150247](https://user-images.githubusercontent.com/24974508/207313280-98d8505c-b896-4ee7-b379-2dd31eddb73b.png)

10.0.19045.2311 is your windows version (not termsrv)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992
