### ISSUE TITLE
Window server 2016 stopped working after an update

### ISSUE THREAD

**Issue by patzko** [stascorp/rdpwrap#2072]
Guys help.
RDPWRAP 1.6.2 stopped working after the latest update of win server 2016. What to do?
Ver 1607, OS Build 14393.5582

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2067
