### ISSUE TITLE
USB Licnese key (physical usb device like flashdrive but for license)

### ISSUE THREAD

**Issue by RED993** [stascorp/rdpwrap#2075]
Hello,
I have one USB License key and one PC (it is physical usb device like flashdrive but for licensing).
When I connect to rdp wrapper it is working for per user profile but USB device is not presented per profile.
I mean when I use windows server RDS and one license usb device it is presented as individual key for each user profile and session.So I can use one USB key and run one software individually per profile with license.
Is it possible to do that with rdp wrapper?

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/91
