### ISSUE TITLE
listener state: Not listening [not supported] on Windows 10 home x64 10.0.19041

### ISSUE THREAD

**Issue by deepakpaneri** [stascorp/rdpwrap#2077]
I am facing not listening not supported issue 
screenshot attached.
![image_2022-12-25_22-32-13](https://user-images.githubusercontent.com/74428876/209665743-90b6a722-f95c-40d3-a42d-97595ddc2206.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992
