### ISSUE TITLE
Please help me for 10.0.19041.2075, thanks!

### ISSUE THREAD

**Issue by zk36** [stascorp/rdpwrap#2079]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/10330196/termsrv.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Comment by zk36** [comment]
Thank you!

There is solution that helped me:

Put new rdpwrap.ini in the same folder as rdpwinst.exe
Open command line
rdpwinst -u -k
rdpwinst -i
