### ISSUE TITLE
Could you help with 10.0.19041.1949 / i386 ?

### ISSUE THREAD

**Issue by MattiZescu** [stascorp/rdpwrap#2085]
![Capture](https://user-images.githubusercontent.com/122643556/212410368-8f8e93da-8cef-4a7b-aad5-024002713466.PNG)

Thank you very much
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/10415036/termsrv.zip)

**Comment by MattiZescu** [comment]
Never mind ! The solution was already found !
Thank you

**Comment by sashaqwert** [comment]
https://github.com/stascorp/rdpwrap/issues/1968#issuecomment-1231281660

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1968
