### ISSUE TITLE
Windows 11 failing to install

### ISSUE THREAD

**Issue by thepearking** [stascorp/rdpwrap#2087]
I don't know much about what to do but i need some help getting this set up. When runnint the install.bat as admin it gives me the output in the first image and when checking the config (second pic) it says it isn't installed.

![image](https://user-images.githubusercontent.com/85383676/212491933-b8401a19-3092-483e-8c04-f9cdf857f811.png)
![image](https://user-images.githubusercontent.com/85383676/212491949-96e99ad1-3090-4d90-9bff-15353d30f721.png)

**Comment by PearKing05** [comment]
SOLUTION: you need to make sure that windows defender allows the installer to run as i will silently block it

**Comment by thepearking** [comment]
SOLUTION: you need to make sure that windows defender allows the installer to run as i will silently block it
