### ISSUE TITLE
10.0.19045.2545 is not supported

### ISSUE THREAD

**Issue by luckyEason** [stascorp/rdpwrap#2089]

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.
Also this issue will closed as incorrect.

**Comment by hosseinadib-hub** [comment]
I have same problem
![image](https://user-images.githubusercontent.com/663815/212761919-746ca25f-8bb4-41ee-9b21-99f53cbcc5bf.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992
