### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by EliezerBee** [stascorp/rdpwrap#2090]
Is Windows 11 (Pro, latest build) supported? I only see mentions through Windows 10.

**Comment by sashaqwert** [comment]
Yes, supported.
Official INI is not support any Windows 11 build, but you can replace `rdpwrap.ini` and get support for your build.

For more information:
1. Download RDP Wrapper 1.6.2
2. Execute RDPConf
3. Open issue section in this repository
4. Type in search your `termsrv.dll` version (from RDPConf). Example `10.0.XXX.YYY`
