### ISSUE TITLE
to sign in remotely you need the right to sign in through remote desktop services, by default, members of the remote desktop users group have this right. if the group you're in doesnt have this right, or if the right has been removed from remote desktop desktop users group, you need to be granted this right manually

### ISSUE THREAD

**Issue by KrisWare1** [stascorp/rdpwrap#2092]
This is what i get when i try using thin client RDPWRAP
with terminal Share
[to sign in remotely you need the right to sign in through remote desktop services, by default, members of the remote desktop users group have this right. if the group you're in doesnt have this right, or if the right has been removed from remote desktop desktop users group, you need to be granted this right manually](https://www.google.com/search?q=to+sign+in+remotely+you+need+the+right+to+sign+in+through+remote+desktop+services,+by+default,+members+of+the+remote+desktop+users+group+have+this+right.+if+the+group+you%27re+in+doesnt+have+this+right,+or+if+the+right+has+been+removed+from+remote+desktop+desktop+users+group,+you+need+to+be+granted+this+right+manually&spell=1&sa=X&ved=2ahUKEwigqZCGn9b8AhV2h_0HHTNFANgQkeECKAB6BAg3EAE)

**Comment by sashaqwert** [comment]
> to sign in remotely you need the right to sign in through remote desktop services

Not an RDP Wrapper issue.
Please, add your RDP users to "Remote Desktop users" group or Administrators.
