### ISSUE TITLE
Windows 10 22H2 not supported and Listener state not listening

### ISSUE THREAD

**Issue by WhoIsEv** [stascorp/rdpwrap#2094]
I tried updating the .ini file but nothing works, is there any file code I can replace with the old code in the ini file? Hopefully I can get it running. 
I'm running Microsoft Windows 10 Home Version 22H2 Build 19045.2486

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992
