### ISSUE TITLE
Suggestion to modify RDPWrap to avoid triggering AVs

### ISSUE THREAD

**Issue by EliezerBee** [stascorp/rdpwrap#2095]
I think this would be a great idea, actually. That's easy enough to document and for users of RDPWrap to do. And it would make people calmer since every AV wouldn't be alarming.

              Well, maybe if I change the behaviour of installer not to enable RDP by default after installation, it will be more secure, and those AVs would be more quiet.

_Originally posted by @binarymaster in https://github.com/stascorp/rdpwrap/issues/277#issuecomment-314020583_

**Comment by sashaqwert** [comment]
If you want to emphasize that this problem is of interest to you, then please leave a comment in the original issue, and do not create new ones...

This issue will be marked as duplicate and closed :)

**Comment by sashaqwert** [comment]
Duplicate of #277
