### ISSUE TITLE
My rdp will load the back ground but wont load user

### ISSUE THREAD

**Issue by Adamiscool110** [stascorp/rdpwrap#2098]
hello I just got rdp and it wont load after the back ground any help?
![image](https://user-images.githubusercontent.com/123514436/214430624-43950829-aeb5-4b96-91a5-526fc6f1ad6b.png)
![image](https://user-images.githubusercontent.com/123514436/214430732-0a81d443-9988-405d-8ded-77520864059e.png)

**Comment by sashaqwert** [comment]
You need to [convert your Microsoft Account to a local account](https://www.itechtics.com/change-account-type/)

**Comment by sashaqwert** [comment]
If you have other issues with this version, use https://github.com/stascorp/rdpwrap/issues/1992
