### ISSUE TITLE
rdp is not working after installation and show this massages and either reinstall nor install 

### ISSUE THREAD

**Issue by 9780919786** [stascorp/rdpwrap#2100]
![WhatsApp Image 2023-01-26 at 7 23 17 AM](https://user-images.githubusercontent.com/123652681/214875618-6c50bb98-833a-455f-ab71-275aa26ec438.jpeg)
![WhatsApp Image 2023-01-26 at 7 23 18 AM (1)](https://user-images.githubusercontent.com/123652681/214875638-786a4425-7b54-42d8-ab80-46b3fecedd30.jpeg)
![WhatsApp Image 2023-01-26 at 7 23 18 AM](https://user-images.githubusercontent.com/123652681/214875640-94821021-35c1-454e-8878-07958231592a.jpeg)

**Comment by sashaqwert** [comment]
Solution in https://github.com/stascorp/rdpwrap/issues/1883 --> Problem 2
