### ISSUE TITLE
Service state: Stopped and listener state: Not listening. Help me pls

### ISSUE THREAD

**Issue by vermeapenas** [stascorp/rdpwrap#2102]
![i need help](https://user-images.githubusercontent.com/123763589/215155027-78a73b07-087c-4987-9056-1fa9bc3ce891.png)

**Comment by sashaqwert** [comment]
try `net start termService`

If this is not works, please, search answer in https://github.com/stascorp/rdpwrap/issues/1883

Your build supported officially: https://github.com/stascorp/rdpwrap/blob/master/res/rdpwrap.ini#L1310
