### ISSUE TITLE
Win32/Mamson.A!AC detected using RDP sebaxakerhtc version

### ISSUE THREAD

**Issue by terrencew13** [stascorp/rdpwrap#2107]
Win32/Mamson.A!AC detected using RDP sebaxakerhtc version

Windows defender is detecting this as sever risk virus.  Is this a false positive?

**Comment by sashaqwert** [comment]
> RDP sebaxakerhtc version

This issues section for official RDP Wrapper (by Stas'M).

Issues for nod here: https://github.com/sebaxakerhtc/rdpwrap.ini

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/277
