### ISSUE TITLE
rdp

### ISSUE THREAD

**Issue by zzzzzzzzzda** [stascorp/rdpwrap#2108]
help 
![image](https://user-images.githubusercontent.com/124941507/217964858-68981e29-01b9-4aad-8a28-118cb235dc8b.png)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1883

**Comment by sashaqwert** [comment]
Discussion about your version: https://github.com/stascorp/rdpwrap/issues/1992
