### ISSUE TITLE
Physical monitor suddenly reports "No signal"

### ISSUE THREAD

**Issue by RudolfSta** [stascorp/rdpwrap#2109]
Suddenly my local physical monitor reports "No signal". I tried another monitor, same result. 
But, fortunately, I can still log in remotely from another system by using RDPwrapper.
Could this monitor problem be caused by RDPwrapper?

termsrv.dll Version is 10.0.22000.1042
and there is a section for that in the rdpwrap.ini file that I am using.

 
![RDPconf2023-02-10](https://user-images.githubusercontent.com/125031519/218085849-2f6c8843-712e-4177-b966-632c0e7064d7.png)

My version of Windows 11 Home is 21H2, OS Build 22000.**1455**, so this has a different build number.
The last Windows update that the system has done was KB4023057.

I'm afraid to try myself whether the problem comes from RDPwarpper by uninstalling it, because that might result in a system that I can't reach.

Regards, Rudolf

**Comment by sashaqwert** [comment]
> Could this monitor problem be caused by RDPwrapper?

No.
RDP Wrapper only launch `termsrv.dll` with other options.

If you want check this try uninstall RDP Wrapper and convert your OS to Enterprise multi-session (use Google and My Digital Life forum).

Closed...
