### ISSUE TITLE
RDP Wrapper + LoL

### ISSUE THREAD

**Issue by asdfgurke** [stascorp/rdpwrap#2110]
Hey, i tried to play League (on User A) while using another user with rdp wrapper (User B).
Everything is fine, i can play League without Problems on user A.
Until i start a game in my case its BDO, my League game on user A will crash everytime untill i shut down User B.

I would like to know if there is a fix for that

![league-of-legends-critical-error-message-750x430](https://user-images.githubusercontent.com/106699857/218335372-29ffb07b-6a73-4361-a36a-70c652a4f47a.jpg)

**Comment by sashaqwert** [comment]
> Until i start a game in my case its BDO, my League game on user A will crash everytime untill i shut down User B.
> 
> I would like to know if there is a fix for that

RDP Wrapper only execute original `termsrv.dll` with other options. This is not RDP Wrapper issue.
You can check this by using Windows Server or Windows 10/11 Enterprise multi-session (ServerRdsh) on same machine.
