### ISSUE TITLE
KB5022842 RDP Wrapper not work on Windows Server 2022 Datacenter 21H2

### ISSUE THREAD

**Issue by Delux-1990** [stascorp/rdpwrap#2116]
After installing the KB5022842 update on Windows Server 2022 Datacenter 21H2, I received a standard connection limit for 2 RDP users.
After removing the KB5022842 update, the limit disappeared and the application works fine again on build 20348.1487 
Please tell me if you can update the application to remove the connection limit after installing the KB5022842 update?

**Comment by sashaqwert** [comment]
> After installing the KB5022842 update on Windows Server 2022 Datacenter 21H2, I received a standard connection limit for 2 RDP users.

Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
Closed, because opened correct issue https://github.com/stascorp/rdpwrap/issues/2117

This issue is invalid.
