### ISSUE TITLE
Termserv not working 10.0.19041.1949

### ISSUE THREAD

**Issue by Barisha70** [stascorp/rdpwrap#2118]
Need help....

All installed,look OK ,but no multiple connection.

![pic01](https://user-images.githubusercontent.com/105888372/219250456-5a87fb82-66cb-4c9b-ab07-4e297c276ad8.jpg)
![pic02](https://user-images.githubusercontent.com/105888372/219250461-2cd0fd64-5978-45a8-9733-79b17a4310b3.jpg)

**Comment by sashaqwert** [comment]
Try restart service or reboot.

One `termsrv.dll` version = one opened issue!

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1968

**Comment by Barisha70** [comment]
Solved...
Tnx for advice.
After secund replacing in system32,work now.

Thanks.
