### ISSUE TITLE
RDP Wrapper Library  doesnt installed

### ISSUE THREAD

**Issue by uykuda** [stascorp/rdpwrap#2121]
![image](https://user-images.githubusercontent.com/81591768/219785186-49840132-c513-4f37-b80f-763542df3452.png)
![image](https://user-images.githubusercontent.com/81591768/219785213-b03b668e-ae37-41e0-b9de-020b3661c221.png)

TermService
![image](https://user-images.githubusercontent.com/81591768/219785354-68e89931-7503-4241-8735-f9f3b9ea60b5.png)

**Comment by uykuda** [comment]
I fixed.

The Files;

[RDP Wrapper.zip](https://github.com/stascorp/rdpwrap/files/10771845/RDP.Wrapper.zip)

![image](https://user-images.githubusercontent.com/81591768/219798831-6ec76b4e-9fa7-4d97-8c2d-5ea40ffab51c.png)

**Comment by sashaqwert** [comment]
Closed as solved.
