### ISSUE TITLE
Windows 11 22H2 22621.1265(Windows Feature Experience Pack 1000.22638.1000.0) not supported

### ISSUE THREAD

**Issue by Zyjkjuejej** [stascorp/rdpwrap#2122]
help me please

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Comment by sashaqwert** [comment]
![изображение](https://user-images.githubusercontent.com/24974508/219933136-962d4801-3bfd-49ff-b359-70f2308607cd.png)
