### ISSUE TITLE
Rdp wrapper

### ISSUE THREAD

**Issue by Orif4on** [stascorp/rdpwrap#2124]
После установки RDP Wrapper не могу исправить проблему. Подскажите пожалуйста.
Число разрешенных подключений к этому компьютеру ограничено и все подключений уже используются. Попробуйте подключиться позже или обратитесь к системному администратору.
Лимит 2 пользователя могут зайти.

**Comment by sashaqwert** [comment]
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory (только не в `C:\Program Files\RDP Wrapper`).
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131
