### ISSUE TITLE
win10, shadow 0 mode, how use it?

### ISSUE THREAD

**Issue by radepol** [stascorp/rdpwrap#213]
Hi, please, help. win10, shadow 0 mode, how use it?

**Comment by binarymaster** [comment]
What exactly means "shadow 0 mode"? Registry value?

**Comment by radepol** [comment]
"Shadow 0 mode" is the connection mode, described in more detail here
https://habrahabr.ru/post/147273/

**Comment by binarymaster** [comment]
0 is not mode, it's a session ID number.

0 is default console session on Windows XP and Server 2003 only. On Vista+ the default console session is 1. But better to use `qwinsta` command to see actual console session ID.

**Comment by radepol** [comment]
I want to say that the way "shadow" does not work at all in win10

**Comment by binarymaster** [comment]
Beginning with Windows 8 (i.e. NT 6.2) you need to use `MSTSC` instead of `SHADOW`.

See README, follow this link:
![image](https://cloud.githubusercontent.com/assets/578406/23816478/0d82b438-05fe-11e7-950f-d8e4782f64cd.png)

**Comment by radepol** [comment]
Many thanks! Everything works, a more convenient way to connect via scripts from here moonlightsoft.blogspot.ru/2016/05/microsoft-windows-remote-desktop.html

**Comment by binarymaster** [comment]
That's good!
