### ISSUE TITLE
Windows 10 10.0.19045 support missing

### ISSUE THREAD

**Issue by CodeAnthem** [stascorp/rdpwrap#2130]
Hello, could you help me to get this version supported? Thanks 

Edit:
Running latest version and update.bat didn't work.

Version 10.0.19045.2604

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Comment by sashaqwert** [comment]
> Version 10.0.19045.2604

19041 - 19045 - one core 19041. termsrv.dll is `10.0.19041.XXX`
Original issue detected via previous duplicate https://github.com/stascorp/rdpwrap/issues/2127
