### ISSUE TITLE
RemoteFX USB redirection not working

### ISSUE THREAD

**Issue by xhafan** [stascorp/rdpwrap#2135]
When I don't have RDP Wrapper installed, Remote FX USB redirection works fine and I can see the USB redirection icon in the connection bar : ![image](https://user-images.githubusercontent.com/13038902/222714098-6bd53713-9243-43ff-86ec-2724e408353e.png) When I install RDP wrapper with the latest rdpwrap.ini from https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini , the RemoteFX USB redirection:

- worked initially and briefly on Windows 10 Pro 22H2 OS build 19045.2006, RDP wrapper service state 10.0.19041.1949 (![image](https://user-images.githubusercontent.com/13038902/222714871-58398340-01ea-4243-b0fe-c27ed81e613c.png), but after couple of RD connections it stopped working and the icon in the connection bar does not appear any more
- on Windows 10 Pro 22H2 OS build19045.2486, RDP wrapper service state 10.0.19041.2075 
![image](https://user-images.githubusercontent.com/13038902/222715648-e2805c5d-611c-4c74-ae84-ee6b84d3db28.png) the icon in the connection bar never appeared

When I uninstall RDP Wrapper, RemoteFX USB redirection works again.

Any idea how to make it work with RDP Wrapper? Cheers.

**Comment by sashaqwert** [comment]
> When I don't have RDP Wrapper installed, Remote FX USB redirection works fine and I can see the USB redirection icon in the connection bar :  When I install RDP wrapper with the latest rdpwrap.ini from https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini , the RemoteFX USB redirection:

Known RDP Wrapper issue. USB redirection is not working with RDP Wrapper.
You can find secret solution from pinned message in sebaxakerhtc's Discord server. https://discord.gg/N27yFftWP3

**Comment by xhafan** [comment]
@sashaqwert I went through the Discord messages, but sadly could not find the secret solution 🙂 Could you please point me more closely to the secret solution? Cheers 😅

**Comment by xhafan** [comment]
Found it 😉 Cheers

**Comment by Da3mem** [comment]
> Found it 😉 Cheers

I can't find the secret solution ? please help me

**Comment by sskras** [comment]
I see these pinned messages in channel #main:
![image](https://github.com/stascorp/rdpwrap/assets/7887758/1987fffb-9629-4475-8b2b-3d1bbd154c78)
(and other channels has no pinned messages at all)

But none of the messages mention RemoteFX or USB.

**Comment by sskras** [comment]
@sashaqwert, @xhafan: I see these pinned messages in channel #main:

![image](https://github.com/stascorp/rdpwrap/assets/7887758/1987fffb-9629-4475-8b2b-3d1bbd154c78)
(and other channels has no pinned messages at all)

But none of the messages mention RemoteFX or USB.

**Comment by sashaqwert** [comment]
> But none of the messages mention RemoteFX or USB.

Enterprise multi-session support all this features.
You need elso enable USB redirection in your RDP client.
