### ISSUE TITLE
rdpwrap.ini for Windows 10 Pro 22H2 120.2212.4190.0

### ISSUE THREAD

**Issue by ouroboros93** [stascorp/rdpwrap#2137]
need this version of rdpwrap

**Comment by ouroboros93** [comment]
not supported for this version

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
> Windows 10 Pro 22H2 120.XXX.XXX.XXX

Your issue is invalid.

If you want to reopen this, please, send link to this build info on Microsoft website.
