### ISSUE TITLE
17763.4010 not working

### ISSUE THREAD

**Issue by pcwerxnow** [stascorp/rdpwrap#2138]
Does anyone have a .ini for 17763.4010 ? it does not work

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by pcwerxnow** [comment]
I needed to get it running so I rolled the server 2019 back to 17763.3165 and it works again.  I will test after hours to get the info

**Comment by paranormalific** [comment]
> Please, attach your RDPConf screenshot and `termsrv.dll`.
Добрый. Можете помочь с  версией Windows 10 21H2 19041.2075 [not supported]  ?  

![QIP Shot - Screen 051](https://user-images.githubusercontent.com/35814891/225212723-d4cae9cc-1177-4c18-9b5d-c1d7081ae9ca.png)


![QIP Shot - Screen 052](https://user-images.githubusercontent.com/35814891/225212639-0cccddb7-99a1-47aa-abc5-921777a00c7c.png)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/10976213/termsrv.zip)

**Comment by sashaqwert** [comment]
@paranormalific 

Your version of `termsrv.dll` does not match the issue name.

**Comment by sashaqwert** [comment]
The `termsrv.dll` is not attached long time.

> 17763.4010

Closed as invalid.
