### ISSUE TITLE
Unable to connect to computer using built-in client when running logged in locally.

### ISSUE THREAD

**Issue by R030t1** [stascorp/rdpwrap#214]
Hello,

Having installed rdpwrap and confirmed it works for hosts trying to externally access the computer, I tried to connect to the computer I was already logged in to using the built-in RDP client. This fails with the message that I already have a local session.

The utility included to check successful installation works properly. I suppose this check is built in to the Windows RDP client and this may not be fixable.

**Comment by binarymaster** [comment]
Try connecting 127.0.0.2

**Comment by R030t1** [comment]
A connection to 127.0.0.2 succeeds. Connections to 127.0.0.1 and to the LAN IP fail with the dialog telling me I already have a session in progress.

Since it seems you have already encountered this, why does this happen and why is there no way to connect to 127.0.0.1 or the LAN address?

**Comment by binarymaster** [comment]
![image](https://cloud.githubusercontent.com/assets/578406/23816151/514983c4-05fc-11e7-9545-eb392bd497f5.png)

Actually this is software limitation in MSTSC. There is already added info in README.

But all addresses in range 127.0.0.0/8 are routed to the localhost.
