### ISSUE TITLE
With new ini get [fully supported] but not working: 10.0.19041.2075

### ISSUE THREAD

**Issue by jobdiogenes** [stascorp/rdpwrap#2140]
I get the ini version for 10.0.19041.2075
in RDP Wrapper Config. say that are running [fully supported] 
But, when try to access say "will close another user"

What I can do?
Someone get this behavior?

Thanks

**Comment by watapac123** [comment]
Same issue here

**Comment by drummerglen** [comment]
Same issue here too

**Comment by skadaddle44** [comment]
anyone get a resolution for  10.0.19041.2075 showing supported but still can't connect with multiple users?
