### ISSUE TITLE
[Version 10.0.19045.2728]

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#2144]
![Screenshot 2023-03-17 110902](https://user-images.githubusercontent.com/7907829/225943459-f8907525-23e5-4575-9d53-96b437c906ec.png)

Any help would be great thanks.

**Comment by Just-zy** [comment]
I have the same question, help!

**Comment by rlSun1** [comment]
me too!

**Comment by shufudehaosi** [comment]
19041.2673

**Comment by rlSun1** [comment]
I have found a solution: https://github.com/anhkgg/SuperRDP

**Comment by Just-zy** [comment]
Thank you. I have solved the question. I tried many rdp.ini but failed and so I reinstalled rdp.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2125
