### ISSUE TITLE
Service state Stopped & Listener State Not Listening

### ISSUE THREAD

**Issue by AeroDynam1C** [stascorp/rdpwrap#215]
Server: Windows server 2008 R2 Enterprise
Hyper-V: VM: Windows10 Pro

Everything was working fine until windows 10 pro downloaded updates now after updated RDWW stopped working.  

Here is the scope, I am already running 1.6.1, If i uninstall RDPW and run the RDPwconfig both Service and Listener are working they show green.

as soon as I install RDPWrapper  the Wrapper state says Installed  but the service goes to Stopped and the Listener state go to Not Listening  [Fully supported]

I have done everything for the love of god and still cant get it all green. 
where i stand now is the RDP works for one user only when wrapper is not installed.
when wrapper is installed it all is disabled.

I have tried to run the services manually but that doesnt make the wrapper show green.

any ideas?

here is a screen shot:
https://gyazo.com/b64c611329a32693b0f57890492f0403
![rdpwrapper](https://cloud.githubusercontent.com/assets/26335765/23815632/8f7bdbfe-05ae-11e7-8ab2-f488b1550593.PNG)

**Comment by AeroDynam1C** [comment]
everyhting is up to date with RDPwrapper:
![rdpwrapper2](https://cloud.githubusercontent.com/assets/26335765/23815674/c06fb334-05ae-11e7-965c-76078a199296.PNG)

**Comment by binarymaster** [comment]
Try enable logging for RDP Wrapper.

Create empty file `/rdpwrap.txt` at your root system disk. Then reboot / restart TermService with `RDPWInst -r`

**Comment by AeroDynam1C** [comment]
Just did that and file is empty
![rdpwrapper4](https://cloud.githubusercontent.com/assets/26335765/23815934/a428386c-05af-11e7-905a-ca19f15ae43f.PNG)

**Comment by binarymaster** [comment]
This could mean only one thing - terminal service is not started at all, maybe due to Anti-Virus software or something like that.

**Comment by binarymaster** [comment]
Run `sc query TermService` and see the output for error codes

**Comment by AeroDynam1C** [comment]
I uninstalled all antivirus and disabled windows firewall

C:\Users\Administrator\Desktop\RDPWrap-v1.6.1>sc query TermService

SERVICE_NAME: TermService
        TYPE               : 20  WIN32_SHARE_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\Users\Administrator\Desktop\RDPWrap-v1.6.1>

**Comment by AeroDynam1C** [comment]
right now wrapper is not installed
let me install it and run query

**Comment by AeroDynam1C** [comment]
Ok just installed it. 
Next step run query.
![rdpwrapper5](https://cloud.githubusercontent.com/assets/26335765/23816172/fe57ec50-05b0-11e7-98d1-0cf291762679.PNG)

**Comment by AeroDynam1C** [comment]
Ok query run here is the result:

![rdpwrapper6](https://cloud.githubusercontent.com/assets/26335765/23816213/2dbfa30c-05b1-11e7-93ed-8c89a4a7ce3e.PNG)

**Comment by binarymaster** [comment]
Win32 exit code is 5 which means "Access denied".

**Comment by AeroDynam1C** [comment]
it was working before the update perhaps update changed permissions on a file?
if so what file do i need to change permissions? I am full Local and Domain Admin so it should not deny access right?

**Comment by binarymaster** [comment]
The `NT AUTHORITY\SYSTEM` must have access to the `C:\Program Files\RDP Wrapper\` directory and all files in it.

If Access Control List to the directory and files is configured correctly, then it's still anti-virus problem (try disabling integrated Smart Screen and Windows Defender services).

**Comment by AeroDynam1C** [comment]
ok disabled smartscreen, disabled win defender, 
disabled firewall 
checked permissions on folder  c:\Program Files\ RDP Wapper\

SYSTEM had zero permissions in folder
Gave permissions
Now ITs running
 
THANK YOU!

**Comment by AeroDynam1C** [comment]
![rdpwrapper7](https://cloud.githubusercontent.com/assets/26335765/23816928/332d836e-05b5-11e7-88cc-ea5ab886ea12.PNG)

**Comment by binarymaster** [comment]
> SYSTEM had zero permissions in folder
Gave permissions
Now ITs running

I'm glad you're solved the issue!

I'll add this to FAQ in README later.

**Comment by Zenida89** [comment]
I've the same problem from today morning.
I Always worked with Windows 10 pro, Windows smartscreen and firewall enabled, Kaspersky Internet Security enabled.

Now it stops working without a reason. I disabled everything and exit from kaspersky, I checked permission of SYSTEM in the folder... but nothing... Service State is always Stopped!

**Comment by binarymaster** [comment]
> Now it stops working without a reason. I disabled everything and exit from kaspersky, I checked permission of SYSTEM in the folder... but nothing... Service State is always Stopped!

`sc query TermService`

**Comment by Zenida89** [comment]
it says status is stopped, and exit_code 5.
Sometimes I got it working trying uninstaling and installing in different ways, such as in system32 folder... but when I restart it brokes again

**Comment by binarymaster** [comment]
> it says status is stopped, and exit_code 5.

This is antivirus problem, add RDP Wrapper folder to exclusions (or system32).

**Comment by Zenida89** [comment]
Maybe... but it's not so clear and I'm going to explain why:

- I always had KIS installed and I always had RDP in whitelist
- Nothing has changed (except for some antivirus DB update)
- I tried with KIS, Windows Defender and firewall disabled, but no success.

While, if I delete rdp config in system folder and repeat the installation, even with KIS enabled, it start to works again... but not forever.

Probably is Kaspersky's fault, but I can't understand its behavior

**Comment by andhan83** [comment]
Thank you so much, worked for me to!!
In my case not the permission of the Folder, but the permission to rdpwrap.ddl was the Problem.

**Comment by IvanGubarev** [comment]
Hi all,Thank you! the problem decided to set the permissions rdpwrap.dll, the right to give the SERVICE. Then the termservice is started.

**Comment by a-singer** [comment]
Hello,

just for fun, I ran sc query termservice and got the following

SERVICE_NAME: termservice
        TYPE               : 20  WIN32_SHARE_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

I hope this is of some use.

**Comment by TiredFerreira** [comment]
Hello, I'm having the same issue.
Already disabled anti-virus, checked permissions in RDP folder and tried to manually start TermService, when rdpwrap is installed it gives me error code 5, when it's uninstalled it starts fine.
I can't find rdpwrap.dll or rdpwrap.ini to check their permissions tho.
Running windows 10 pro, 1803 build (already downloaded the rfxvmt.dll and put it in System32, still can't start the service)

**Comment by sayagit** [comment]
Hello,
When I executed "RDPCheck.exe", it showed my PC's login screen,
then entered with my password, it showed "My access was refused".

RDP Wrapper Configuration is all green:
 Wrapper state: Installed
 Service state: Running
 Listener state: Listening
 
My OS is Windows 10 Home edition, version 1803 (OS Build 17134.112)

I tried following:
・I set all the permissions of SYSTEM, Administrators and  read and write of NETWORK SERVICE of the folders "C:\Program Files\RDP Wrapper" and "C:\Users\...\Desktop\RDPWrap-v1.6.2"
・I ran this command "sc query TermService" and got :
SERVICE_NAME: TermService
        TYPE               : 30  WIN32
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

What should I do? sorry for my English.
Hello,
When I executed "RDPCheck.exe", it showed my PC's login screen,
then entered with my password, it showed "My access was refused".

RDP Wrapper Configuration is all green:
 Wrapper state: Installed
 Service state: Running
 Listener state: Listening
 
My OS is Windows 10 Home edition, version 1803 (OS Build 17134.112)

I tried following:
・I set all the permissions of SYSTEM, Administrators and  read and write of NETWORK SERVICE of the folders "C:\Program Files\RDP Wrapper" and "C:\Users\...\Desktop\RDPWrap-v1.6.2"
・I ran this command "sc query TermService" and got :
SERVICE_NAME: TermService
        TYPE               : 30  WIN32
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

What should I do? Sorry for my English.

**Comment by DuncanZGlw** [comment]
Hi Guys,

Been going round in circles for over a week now.  Any suggestions would be appreciated.

It's a VM, using the same ISO on physical works OK but every time in virtual 3389 is missing and a few others.


W10 Enterprise 1803 17134.165

Slainthe

https://user-images.githubusercontent.com/41112076/42565386-3077251e-84fb-11e8-93cb-6f96433bf62c.png)

**Comment by rtbweb** [comment]
Also a solution with the most recent .168 update of windows 10 pro;) thanks!!

**Comment by pawelelert** [comment]
> Thank you so much, worked for me to!!
> In my case not the permission of the Folder, but the permission to rdpwrap.ddl was the Problem.

This has solved my issue. Many thanks

**Comment by knd894gj** [comment]
Hi Guys

I also have similar problem, but I did not have seen similar  number in WIN_32_EXIT_CODE = 1067.

Could you provide me with information how to fix this issue :/

![błąd](https://user-images.githubusercontent.com/51210132/58654042-57adb880-8317-11e9-9d2b-7c5f2f17c9e9.png)

**Comment by Evesain** [comment]
Im running into the same issue as above but the service fails to start
![image](https://user-images.githubusercontent.com/11574971/80913512-0420c780-8d3d-11ea-813f-64575015b5f6.png)

**Comment by knd894gj** [comment]
Hey i didnt solved this it you will find solution let me know ^^

niedz., 3 maj 2020, 13:53 użytkownik Evesain | Matt <
notifications@github.com> napisał:

**Comment by PC2289** [comment]
I ran sc query termservice and got the following error

SERVICE_NAME: TermService
        TYPE               : 30  WIN32
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 126  (0x7e)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

**Comment by kkm5848** [comment]
I have the same problem.  It was working prior to a reboot yesterday...so I assume a system update must have applied.

I am running Windows 11
