### ISSUE TITLE
cannot connect to RDP, wrapper fully supported, error : The graphics display components in the remote session failed to start up

### ISSUE THREAD

**Issue by jay-sync** [stascorp/rdpwrap#2161]
installed and replaced the conf file (wrapper fully supported)
<https://github.com/stascorp/rdpwrap/issues/1883>
<img width="377" alt="image" src="https://user-images.githubusercontent.com/63868998/228920118-9fdd3751-06e0-4bde-bf4c-f0d7ea51dfb4.png">

disabled WDDM
<https://github.com/stascorp/rdpwrap/issues/858#issuecomment-523192537>
<img width="834" alt="image" src="https://user-images.githubusercontent.com/63868998/228920480-21f03ba0-7ea9-44ce-92c4-baaaef1e1bf9.png">

when connecting get the error : The graphics display components in the remote session failed to start up
<img width="292" alt="image" src="https://user-images.githubusercontent.com/63868998/228919521-4f76816c-f5e1-41be-a8ad-292f34363ac8.png">

**Comment by sashaqwert** [comment]
Not an RDP Wrapper issue.

Solutions in https://serverfault.com/questions/1090540/windows-server-2022-rdp-connection-fails-with-error-0x3-extended-error-0x11

**Comment by sashaqwert** [comment]
You can ask this in Telegram chat or in [Discord by sebaxakerhtc](https://discord.gg/N27yFftWP3)
