### ISSUE TITLE
RDP Config does not open Correctly

### ISSUE THREAD

**Issue by mohday** [stascorp/rdpwrap#2166]
the rdp Config and rdp Check opened but not visible, its goes to task bar but just a grey window showed when i hover mouse on its icon in task bar.
i terid blows:
Allow apps for rdp config and rdp check
turn off firewall
change port to 3390
change windows
but still problem not solved

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2103
