### ISSUE TITLE
Session Shadowing Mode RDP Wrapper Configuration

### ISSUE THREAD

**Issue by SalmonSays** [stascorp/rdpwrap#2174]
I'm trying to determine whether my particular use-case makes sense, and whether RDP Wrapper can help with this- I am able to access my machine after setting up RDP Wrapper in my Windows 11 host for shadowing using "mstsc.exe /v:192.168.1.x /shadow:1 /noConsentPrompt /control /prompt" on the client, but it doesn't appear possible to shadow the same session more than once. Is this something RDP Wrapper can fix? I would like to be able to have multiple machines controlling or at least viewing the same Windows session. RDP doesn't seem capable of this, as unticking single session per user results in a duplicate user that can't open certain programs while they're active on the original session. Ticking it results in the original user being kicked off.

**Comment by sashaqwert** [comment]
> but it doesn't appear possible to shadow the same session more than once. Is this something RDP Wrapper can fix?

RDP Wrapper can't fix this. This is a RDP protocol limit (not Windows edition limit)

RDP Wrapper only enabling concurrent sessions.
