### ISSUE TITLE
RDP Multiple Session Same User

### ISSUE THREAD

**Issue by SalmonSays** [stascorp/rdpwrap#2176]
While RDP Wrapper is enabled and running multiple concurrent sessions with one user account, some software will open on an initial desktop and then re-open on the same desktop when launched from the other desktops. This can result in a scenario where one client is actively using something like VSCode, another client is trying repeatedly to launch VSCode, and new VSCode windows keep popping up on the original client while nothing appears for the following ones. Is there a way to address this such that software generally works/launches on each client even for the same user?

**Comment by sashaqwert** [comment]
See https://github.com/stascorp/rdpwrap/issues/1952#issuecomment-1206289659

**Comment by sashaqwert** [comment]
> concurrent sessions with one user account, some software will open on an initial desktop and then re-open on the same desktop when launched from the other desktops.

This is not an RDP Wrapper issue.
This is your app issue.

**Comment by SalmonSays** [comment]
> 
> This is not an RDP Wrapper issue. This is your app issue.

That may be the case, but are there any known workarounds for official apps such as Microsoft VSCode? This is a uniquely RDP-Wrapper-enabled issue as no other method can make it possible to be logged in on one user twice that I know of. I have neither the ability to change native launch methodology of VSCode as I don't work for Microsoft, nor the skill to modify it post-facto right now. This seems like the only place I can ask if there are known methods for fixing this *type* of problem, or at least understanding why it happens in the first place enough to *attempt* a third-party solution.

**Comment by sashaqwert** [comment]
> This is a uniquely RDP-Wrapper-enabled issue as no other method can make it possible to be logged in on one user twice that I know of.

You are wrong. RDP Wrapper is not the only solution that allows multiple sessions from the same user at the same time.

Here is a list of solutions from Microsoft:

- Windows Server (no RDS role) - 2 session limit
- Windows Server (with RDS role) - the limit depends on the number of purchased licenses and their type. Trial period (unlimited) 120 days
- Windows 10/11 Enterprise multi-session (Enterprise for Virtual desktops / ServerRdsh) - no restrictions (except for very old versions).

On the above editions of Windows, you can allow multiple RDP sessions from the same user using Group Policy: https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.TerminalServer::TS_SINGLE_SESSION
