### ISSUE TITLE
rdpwrap.ini for Windows 10 10.0.19041.2913 Not work

### ISSUE THREAD

**Issue by Celeroncillo** [stascorp/rdpwrap#2182]
I need the ini file for this windows version, at my windows version show: 19045.2913.

Thanks

**Comment by AntSanDev** [comment]
> I need the ini file for this windows version, at my windows version show: 19045.2913.
> 
> Thanks

There is already an [issue opened](https://github.com/stascorp/rdpwrap/issues/2180) for that version.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180
