### ISSUE TITLE
10.0.22000.1817 Not Supported

### ISSUE THREAD

**Issue by maxshic** [stascorp/rdpwrap#2184]

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
See https://github.com/sebaxakerhtc/rdpwrap.ini/issues/229#issuecomment-1525971437

--> Duplicate

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2126
