### ISSUE TITLE
请问RDPCheck.exe运行之后出现 not supported,如何解决呀版本是：10.0.18362.267

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#2185]
/

**Comment by ghost** [comment]
![{E356E78F-DD8D-448A-9A7F-CB192C4846BF}](https://user-images.githubusercontent.com/72814023/235300167-5bdcf0b7-b085-4c10-87e0-79930f2cc03b.png)

**Comment by sashaqwert** [comment]
Offsets available here: https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/871
