### ISSUE TITLE
Is it compatible with Passwordless Authentication?

### ISSUE THREAD

**Issue by huangsijun17** [stascorp/rdpwrap#2186]
The Microsoft account in my computer is authenticated without a password. Can one manage to Remote Desktop connect to a Passwordless authenticated user?

**Comment by sashaqwert** [comment]
Not an RDP Wrapper issue. Closed.

Please, read https://learn.microsoft.com/en-us/answers/questions/594630/remote-desktop-via-microsoft-account-with-no-passw

If this works without RDP Wrapper but not works with it, i can reopen this issue.
