### ISSUE TITLE
Please, support Win 10 19045.2965

### ISSUE THREAD

**Issue by etonocolia** [stascorp/rdpwrap#2197]
The RDPWrapper bad

**Comment by etonocolia** [comment]
Help me, please
Win 22H2 
19045.2965

I need .ini

Thanks

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by jpewpew** [comment]
Jumping in because i have the same issue

![image](https://github.com/stascorp/rdpwrap/assets/133163478/973e76bf-9412-4e43-9087-35f54bbec898)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11445615/termsrv.zip)

**Comment by sashaqwert** [comment]
Thanks! Solution in my next comment

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180

**Comment by etonocolia** [comment]
![Captura](https://github.com/stascorp/rdpwrap/assets/8352283/ff9a8900-1b6c-4c7e-b7df-c6fd015c95f3)

**Comment by etonocolia** [comment]
![image](https://github.com/stascorp/rdpwrap/assets/8352283/6c0509b5-3153-4186-9e50-dd3937bede62)

**Comment by sashaqwert** [comment]
@etonocolia 

Are you replaced rdpwrap.ini file from https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by kelitonnunes** [comment]
> @etonocolia
> 
> Você substituiu o arquivo rdpwrap.ini de https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

Parabéns resolveu o caso aqui.

**Comment by etonocolia** [comment]
Yes, worked

Many thanks

👍👍👍

**Comment by susl16c** [comment]
19045.6456 is there no solution for such an assembly?
