### ISSUE TITLE
RDPWrap

### ISSUE THREAD

**Issue by Orif4on** [stascorp/rdpwrap#2199]
После обновления windows RDPWrap перестал работать.
![Снимок](https://github.com/stascorp/rdpwrap/assets/54934522/e0483171-db14-4502-aa3b-e1ebc72f2da0)

**Comment by sashaqwert** [comment]
Issue закрыт автором, значит для него проблема решена.
Название issue неправильное.
ПереЗАКРЫТО, как дубликат

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180
