### ISSUE TITLE
Remote Control Results in Protocol Error Win7

### ISSUE THREAD

**Issue by moonbug** [stascorp/rdpwrap#220]
When I remote control a user from Task Manager, it disconnects admin RDP session and shows 
"Because of protocol error, the session will be disconnected"
Using Win 7 Pro
Session Shadowing Mode: Full access without user permission

**Comment by binarymaster** [comment]
Try to update your RDP client, maybe this helps.

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.
