### ISSUE TITLE
Question on session limit relating to GPU memory

### ISSUE THREAD

**Issue by rrduivenvoorden** [stascorp/rdpwrap#2202]
I am running RDP wrapper on a sizeable machine (48 cores, ~750GB RAM, Window 10 Enterprise 21H2 19044.2846). Despite the sizeable CPU and RAM available, I've ran into the issue where RDP would no longer connect a session when more than 5-6 sessions were already connected (giving only a black screen or the image below). When that happens, currently disconnected users are also often locked out, until someone logs in locally. RDP Config shows in all cases that the build is supported and the client is listening.

![image](https://github.com/stascorp/rdpwrap/assets/88586209/1b9d6542-6272-4bf6-9723-58ced4495485)

Based on issue #192 I think the problem could be related to resources running out, particularly the memory of our undersized GPU (which only has 2GB of dedicated memory). It is mentioned there that RDP consumes GPU memory and it running out might be the reason for a session limit.

I have checked that there is no limit of connections in gpedit.msc. I've also since deactivated GPU acceleration in gpedit, which seems to have solved the problem for now. To get ahead of future issues, however, I was wondering whether RDP would only care about the dedicated GPU memory available, or whether it will work fine if only virtual GPU memory is available. Due to the amount of RAM available on the machine, we have plenty of virtual GPU memory so this would hardly ever become an issue. If RDP requires availability of dedicated GPU memory, I will know to upgrade the GPU.

Thanks in advance for your insight!

**Comment by sashaqwert** [comment]
> I am running RDP wrapper on a sizeable machine (48 cores, ~750GB RAM, Window 10 Enterprise 21H2 19044.2846). Despite the sizeable CPU and RAM available, I've ran into the issue where RDP would no longer connect a session when more than 5-6 sessions

Try uninstall RDP Wrapper and switch your SKU to ServerRdsh (Enterprise for Virtual desktops). You can find GVLK key in Google.
This Edition is RDS role without RDS CAL licenses.

If this problem is not seen on ServerRdsh, but it is on Enterprise with RDP Wrapper, then it is most likely an RDP Wrapper problem.

> I have checked that there is no limit of connections in gpedit.msc. I've also since deactivated GPU acceleration in gpedit, which seems to have solved the problem for now.

--> Not an RDP Wrapper issue. --> closed...
