### ISSUE TITLE
Shadow without permission not working

### ISSUE THREAD

**Issue by jqrs** [stascorp/rdpwrap#2208]
Session shadowing mode without permission (View only or Full access) seem to have no effect. The session user is still asked to grant permission to allow the shadow connection. Everything else works fine.

How can I fix this?
Wrapper ver. 1.7.4.0
termsrv ver. 10.0.14393.0

**Comment by sashaqwert** [comment]
> How can I fix this?

Try

```
mstsc /shadow:SESSION_ID_HERE /v:HOSTNAME_OR_IP /prompt /control /noConsentPrompt
```

`/v` is not needed in same computer.

**Comment by jqrs** [comment]
I was missing /noConsentPrompt, thanks!
