### ISSUE TITLE
need suport windows 11 22621.1485 

### ISSUE THREAD

**Issue by davidvieira13** [stascorp/rdpwrap#2209]
I'm trying to install and the error appears - openkeyreadonly error (code 0)

I'm running as administrator

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
Closed as no actibity

**Comment by davidvieira13** [comment]
I will send, I'm not near the pc that is windows

**Comment by sashaqwert** [comment]
> I will send, I'm not near the pc that is windows

OK. Without this information (version of `termsrv.dll`), the issue is invalid....
