### ISSUE TITLE
Doubt: Creation of DLL and INI files

### ISSUE THREAD

**Issue by espeditomelo** [stascorp/rdpwrap#221]
My PC was off line (without inernet access) and when i performed the "install.bat" two files (rdpwrap.dll and rdpwrap.ini) was created on "C:\Program Files\RDP Wrapper", and in my folder with the file installers did not have any dll or ini file.
Can you please explain how to these files (dll and ini) was created on "C:\Program Files\RDP Wrapper" folder?

**Comment by binarymaster** [comment]
The installer is hybrid, it supports both online and offline installation.
