### ISSUE TITLE
Issue with RDP Wrapper on windows 11

### ISSUE THREAD

**Issue by realaintreal** [stascorp/rdpwrap#2210]
Hello,

I'm hoping someone can help me solve this issue. Basically when I open the RDPcheck.exe and log into the user it says, "access denied"

How can I fix this issue?

I'm on windows version 22621.1702

**Comment by sashaqwert** [comment]
> I open the RDPcheck.exe and log into the user it says, "access denied"

Try add your RDP users to the "Remote desktop users" group. Or see https://github.com/stascorp/rdpwrap/issues/101
