### ISSUE TITLE
everything is all working but when i open the rdp check the log in window screen is blurry so cant put in details 

### ISSUE THREAD

**Issue by THill246** [stascorp/rdpwrap#2211]
everything is all working but when i open the rdp check the log in window screen is blurry so cant put in details

**Comment by THill246** [comment]
![gl](https://github.com/stascorp/rdpwrap/assets/114803646/92f3b026-45fb-4c2b-a19d-a78b1ed2b8eb)

**Comment by sashaqwert** [comment]
You need to [convert your Microsoft account to local account](https://www.itechtics.com/change-account-type/).

**Comment by vslee** [comment]
Or turn enable password login by turning off the requirement for Windows Hello https://superuser.com/a/1715548
