### ISSUE TITLE
Autoupdate Error: NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference]

### ISSUE THREAD

**Issue by alexlovar** [stascorp/rdpwrap#2218]
hello, the auto update bat is returning the follo error on windows 10 .
`Add-MpPreference : Se produjo el siguiente error en la operación: 0x800106ba. Operación: MpPreference. Destino:
ConfigListExtension.
En línea: 1 Carácter: 1
+ Add-MpPreference -ExclusionPath ('C:\Program Files\RDP Wrapper\rdpwra ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0x800106ba,Add-MpPreference

Add-MpPreference : Se produjo el siguiente error en la operación: 0x%1!x!
En línea: 1 Carácter: 1
+ Add-MpPreference -ExclusionPath ('C:\Program Files\RDP Wrapper\rdpwra ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0x800106ba,Add-MpPreference`
    
    
![image](https://github.com/stascorp/rdpwrap/assets/20868783/c06aaad3-14e3-4144-9f77-f9c18932a9f3)

**Comment by sashaqwert** [comment]
> N/A and installed

Solution in https://github.com/stascorp/rdpwrap/issues/1883
