### ISSUE TITLE
10.0.19045.2965+termsrv.dll termsrv.dll is broken, please give me 10.0.19045.2965+termsrv.dll, thanks

### ISSUE THREAD

**Issue by kenetkang** [stascorp/rdpwrap#2219]

**Comment by sashaqwert** [comment]
> please give me 10.0.19045.2965+termsrv.dll

The version of `termsrv.dll` you're asking for doesn't exist and never has existed... Of course, you can pay Microsoft several billion dollars to release this version of `termsrv.dll` especially for you :).

# Your `termsrv.dll` version is `10.0.19041.2913`

For remember: the version of `termsrv.dll` very rarely matches the version of Windows.

For Windows versions `10.0.19041.XXX` - `10.0.19045.XXX` the version of the Remote Desktop Services Library will be `10.0.19041.ZZZ`.

# Broken???

> termsrv.dll is broken

You can always restore original `termsrv.dll` via `sfc /scannow` command.

# Where this closed by me?

1) Closed as answered.
2) If you have a question with your `termsrv.dll` version, please, see https://github.com/stascorp/rdpwrap/issues/2180

**Comment by kenetkang** [comment]
windows 10.0.19045.2965 termsrv.dll version:10.0.19041.2913 
sorry, now I know, different termsrv.dll is not same windows version
