### ISSUE TITLE
Windows 11 vers. 10.0.22621.608 Not Listening but Fully Supported

### ISSUE THREAD

**Issue by FoxCT2023** [stascorp/rdpwrap#2220]
Hi all,
With latest .ini I get Fully Supported but Not Listening.
Any Help Please ?
Thanks!

**Comment by FoxCT2023** [comment]
Here my termsrv.dll on WIndows System32

**Comment by FoxCT2023** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11576372/termsrv.zip)

Here

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006
