### ISSUE TITLE
How can I improve the frame rate of the remote desktop and optimize the smoothness

### ISSUE THREAD

**Issue by cimpapa** [stascorp/rdpwrap#2222]
Used on a LAN, gigabit network. Want to reduce latency and improve response level, implement the function of a cloud host.
![Snipaste_2023-05-27_15-15-10](https://github.com/stascorp/rdpwrap/assets/67214548/dfa95088-afa4-49da-ba09-3d5c0fc7b823)

**Comment by sashaqwert** [comment]
> How can I improve the frame rate of the remote desktop and optimize the smoothness

Not an RDP wrapper issue.

You can read:

- https://learn.microsoft.com/en-US/troubleshoot/windows-server/remote/frame-rate-limited-to-30-fps
- https://learn.microsoft.com/en-us/azure/virtual-desktop/rdp-bandwidth
