### ISSUE TITLE
Windows 11 10.0.22621.1702 not supported

### ISSUE THREAD

**Issue by lbbenson** [stascorp/rdpwrap#2229]
![image](https://github.com/stascorp/rdpwrap/assets/134986755/3871686f-9727-4f9e-a480-01b8cae6bd54)
![image](https://github.com/stascorp/rdpwrap/assets/134986755/ce06236b-c7f6-421e-b8a7-204dc9d6e135)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11595295/termsrv.zip)
thank you very much  :)

**Comment by lbbenson** [comment]
https://github.com/stascorp/rdpwrap/issues/2213#issuecomment-1562450834
works!

**Comment by sashaqwert** [comment]
> [#2213 (comment)](https://github.com/stascorp/rdpwrap/issues/2213#issuecomment-1562450834) works!

Closed as solved.

**Comment by sashaqwert** [comment]
Duplicate of #2213
