### ISSUE TITLE
win 10 ver. 10.0.19041.2913 remote not working

### ISSUE THREAD

**Issue by Namasivaya** [stascorp/rdpwrap#2232]
Above mentioned version remote not working.
![Capture](https://github.com/stascorp/rdpwrap/assets/135208771/8dcc7504-f3a4-4221-9179-1e848651c485)
![Capture 1](https://github.com/stascorp/rdpwrap/assets/135208771/1e951a06-0aec-44a3-a90c-2831d95d9fcb)

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180
