### ISSUE TITLE
windows 11 Pro 1000.22642.1000.0 

### ISSUE THREAD

**Issue by SanaNazari** [stascorp/rdpwrap#2233]
Hi, My config says supported 
![Screenshot 2023-06-01 122743](https://github.com/stascorp/rdpwrap/assets/60878123/e79cafbc-1c78-4a4e-b35e-8ad27ac30ca3)

But when I try to connect I get this:
![Screenshot 2023-06-01 122844](https://github.com/stascorp/rdpwrap/assets/60878123/053dd3d6-47b9-48ed-8faa-ebd19734c7b8)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11624093/termsrv.zip)

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2213

**Comment by SanaNazari** [comment]
I'm still facing this issue even after adding the latest init file
