### ISSUE TITLE
same user is able logged in 

### ISSUE THREAD

**Issue by kk2703** [stascorp/rdpwrap#2239]
I  have installed rdp wrapper, and I have changed come setting in group policy and some here and there (I can't remember). Now for eg. user 1  is logged in the main pc, it can also be logged in via rdp to another. How to stop that?

**Comment by sashaqwert** [comment]
1. https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.TerminalServer::TS_SINGLE_SESSION
2. Check "Single session per user" in RDPConf.
