### ISSUE TITLE
rdpwrap Windows 10 10.0.19041.2913 no work

### ISSUE THREAD

**Issue by dark5d** [stascorp/rdpwrap#2243]
Не работает rdpwrap в начале писал
![image](https://github.com/stascorp/rdpwrap/assets/136099254/5d55a7e1-61bf-46cb-808f-63a252bcf8c7)
Я обновил конфиг после чего появилась надпись о полной поддержки, но упала служба "Удалённых рабочих столов", сервис и листининг ушли в красное. Если возвращаю конфиг снова получаю отсутствие проблемы и так по кругу.
С чем это может быть связано, работаю под админом, всё запускал под админом установка вроде корректно проходит, после загрузки конфига и перезагрузки rdpwrap всё становиться зелёным, но не работает, если ребутнуть ПК отваливаются сервис и листининг.

**Comment by dark5d** [comment]
![image](https://github.com/stascorp/rdpwrap/assets/136099254/21e3313b-f5dc-4409-8ebe-06168eb40179)
![image](https://github.com/stascorp/rdpwrap/assets/136099254/692e7f9b-a6d6-4806-a693-6f11e4a1efa6)

[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/11707431/rdpwrap.zip)

**Comment by sashaqwert** [comment]
На одну версию `termsrv.dll` одной разрядности допускается не более одного открытого issue..... :)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180
