### ISSUE TITLE
Windows 11.0 10.0.22621.1848 not supported

### ISSUE THREAD

**Issue by NTTITON** [stascorp/rdpwrap#2246]
Need a new configuration file generated:

termsrv attached

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11749246/termsrv.zip)

**Comment by Natotela** [comment]
> Need a new configuration file generated:
> 
> termsrv attached
> 
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/11749246/termsrv.zip)

shouldn't there be a change in the INI file?
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
which currently does not cater the HEX of build 22621.1848
