### ISSUE TITLE
Windows 10 Pro 10.0.19041.84 Not supporter

### ISSUE THREAD

**Issue by Ghost-729** [stascorp/rdpwrap#2247]
Hello, 

My OS is not supported, can you help-me to solved the problem ?

![image](https://github.com/stascorp/rdpwrap/assets/136717315/cbcc311c-be06-4fc8-98ca-ee9eda50d299)

Regards

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1004
