### ISSUE TITLE
Unable to connect to Windows 10 Home from Mac OS Sierra 

### ISSUE THREAD

**Issue by saitankaghar** [stascorp/rdpwrap#225]
Unable to connect to Windows 10 Home on a Lattepanda box from Mac Os Sierra 10.12.4 
Always getting an error saying Connection refused. ( Attached screenshot)
<img width="267" alt="screen shot 2017-03-31 at 6 26 53 pm" src="https://cloud.githubusercontent.com/assets/5488350/24546908/e88fa99a-163f-11e7-843b-0a6480039a1b.png">

**Comment by binarymaster** [comment]
NT version / edition? Diagnostics screenshot?

**Comment by macieks72** [comment]
I have the same problem after updated windows 10 to the Creators Update.

**Comment by binarymaster** [comment]
Since no technical details are provided from issuer, closing as inactive.
