### ISSUE TITLE
W11 Pro - 22H2 - 22621.1848

### ISSUE THREAD

**Issue by Razuken** [stascorp/rdpwrap#2250]
the issue is ;
the number of connections to this computer is limited and all connections are in use right now.

**Comment by sashaqwert** [comment]
~~Please, attach your RDPConf screenshot and `termsrv.dll`.~~

**Comment by sashaqwert** [comment]
`termsrv.dll` version != Windows version!

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/30614d9d-4f90-4998-b6fe-ad255143a409)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2213
