### ISSUE TITLE
Windows 10 19045.2965 Not listening and not supported

### ISSUE THREAD

**Issue by hsjang95** [stascorp/rdpwrap#2251]
plz help

![rdp](https://github.com/stascorp/rdpwrap/assets/3667437/5e129d62-5fcc-4e8a-b19e-9939d743f0b0)

[termmgr.zip](https://github.com/stascorp/rdpwrap/files/11785104/termmgr.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992
