### ISSUE TITLE
Windows 10 10.0.19045.3086 not supported

### ISSUE THREAD

**Issue by iconquestion** [stascorp/rdpwrap#2253]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11808460/termsrv.zip)
![屏幕截图 2023-06-21 065042](https://github.com/stascorp/rdpwrap/assets/39425011/4004cc22-5209-47de-bb9b-eefb128b9e1a)
Thanks!!!!!!!!!!!!

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180
