### ISSUE TITLE
Windows 10 19045.3086 not supported

### ISSUE THREAD

**Issue by andreiyv** [stascorp/rdpwrap#2256]
[termsrv.zip](https://disk.yandex.ru/d/GelSiOhLusGWTA)

**Comment by sashaqwert** [comment]
> [termsrv.zip](https://disk.yandex.ru/d/GelSiOhLusGWTA)

Your version is 10.0.19041.2913

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180
