### ISSUE TITLE
Session rdp qui s'ouvre directement sur le poste servant de serveur

### ISSUE THREAD

**Issue by Laurent70190** [stascorp/rdpwrap#2262]
Bonjour
J'ai installé le rdpwrapper sur un windows 10
Le rdpcheck est parfait ainsi que l'ini mais
quand j'ouvre une session a distance avec un utilisateur du bureau a distance, cette session s'ouvre egalement le poste de base
Auriez vous une explication et une solution ?
Merci d'avance

**Comment by sashaqwert** [comment]
Please, use English or Russian language in title and first message.

If you want to use another language, you can paste a message in it next to the Russian or English version or in the next message.

CLOSED.
