### ISSUE TITLE
Windows 11 10.0.23493.1000 not supported

### ISSUE THREAD

**Issue by IsArsh** [stascorp/rdpwrap#2264]

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
Closed as invalid (No `termsrv.dll` file attached)

**Comment by Jayziv86** [comment]
<img width="308" alt="1f3fda2265165cd4df792d040fec30e" src="https://github.com/stascorp/rdpwrap/assets/129610017/a7588e49-226b-4096-a9a4-d51a9aa7e39c">
thanks
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11931577/termsrv.zip)

**Comment by Jayziv86** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11931578/termsrv.zip)

**Comment by sashaqwert** [comment]
Opened correct issue in https://github.com/stascorp/rdpwrap/issues/2266
