### ISSUE TITLE
Creation of rdpwrap.dll

### ISSUE THREAD

**Issue by espeditomelo** [stascorp/rdpwrap#227]
Please, can you explane how to "rdpwrap.dll" is created throught the "rdpwinst.exe".
I not found it in the source code and I found this very cool.

**Comment by binarymaster** [comment]
Specifically here:
https://github.com/stascorp/rdpwrap/blob/49770e6bb8bbb78f09679421c6294a6613519ed5/src-installer/RDPWInst.dpr#L673

**Comment by espeditomelo** [comment]
More one info, please:
the file "resource.res" is in hexadecimal code?
How to i can read it and find the information about creation of "rdpwrap.dll" ?

**Comment by binarymaster** [comment]
> the file "resource.res" is in hexadecimal code?

It is a compiled binary resources file.

> How to i can read it

http://www.angusj.com/resourcehacker/

> and find the information about creation of "rdpwrap.dll" ?

It is compiled from another project file.
