### ISSUE TITLE
Can't update to 1.6.2. Ini's supported, but clill have only one session.

### ISSUE THREAD

**Issue by Demon-i** [stascorp/rdpwrap#2272]
I've tried everything. Deleted. Cleaned out folders. Installed via MSI and via EXE. Rebooted the system. 
I found a bug. Uninstall does not return path to termservice. 

Please help. Canceling updates to 2 month already. Need to fix

Screenshot

![Screenshot_1](https://github.com/stascorp/rdpwrap/assets/3864183/f25f9f20-1778-4964-bf5b-cce490d9ca57)

Можно на русском

**Comment by Demon-i** [comment]
It still puts me 1.5.0 from somewere. Could you check your version and upload 1.6.2 ?
![image](https://github.com/stascorp/rdpwrap/assets/3864183/674277ec-048f-41a0-a131-ac93b270232e)

**Comment by sashaqwert** [comment]
1.5.0.0 is a latest version of `rdpwrap.dll`.
1.6.2 is latest version of installer.

`rdpwrap.dll` has not changed since installer version 1.5.
