### ISSUE TITLE
10.0.22621.1928 not supported

### ISSUE THREAD

**Issue by faoggor** [stascorp/rdpwrap#2273]
Hello

![image](https://github.com/stascorp/rdpwrap/assets/139246585/430c557a-f19d-4fde-9ee6-7c899eac0e07)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12015946/termsrv.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2258
