### ISSUE TITLE
10.0.22621.1992 aint supported

### ISSUE THREAD

**Issue by ZhaoyangHan04** [stascorp/rdpwrap#2276]

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
Your `termsrv.dll` version is `10.0.22621.1928`

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/75f45832-dc18-4441-ad16-ed8b7a9ab00b)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2258
