### ISSUE TITLE
RDP Wrapper x64 10.0.19041.1387 not supported

### ISSUE THREAD

**Issue by wahyurc** [stascorp/rdpwrap#2280]
![Capture](https://github.com/stascorp/rdpwrap/assets/43108387/f1cdd83c-03d6-49cd-be34-6f5f35699f8c)

Please help, 10.0.19041.1387 not supported, 

termsrv attached below. many thanks before.

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12064532/termsrv.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630
