### ISSUE TITLE
10.0.19044.2846

### ISSUE THREAD

**Issue by tiger8877** [stascorp/rdpwrap#2285]

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
> 10.0.19044.2846

See https://github.com/stascorp/rdpwrap/issues/1992#issuecomment-1507198724

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2125
