### ISSUE TITLE
Service state in invinity Starting status

### ISSUE THREAD

**Issue by Dorimelat13** [stascorp/rdpwrap#2288]
After Windows update, rdp wrap stopped starting and the service status hovered in the infinite startup position. I couldn't find any solution, please help!
![photo_2023-07-25_15-48-32](https://github.com/stascorp/rdpwrap/assets/49652574/92e7d4be-5997-4fce-997b-4b183ccefeef)

**Comment by sashaqwert** [comment]
Discussion about your version in https://github.com/stascorp/rdpwrap/issues/2277

See also https://github.com/stascorp/rdpwrap/issues/1883
