### ISSUE TITLE
Windows 11 PRO - 22H2 22621.1992 not supported

### ISSUE THREAD

**Issue by TheMazoo** [stascorp/rdpwrap#2292]
I sadly don't have mutch knowledge as to how this whole thing works, but i hope someone can help me
![Windows 11 not supported](https://github.com/stascorp/rdpwrap/assets/140702552/dd4dd7d1-fdfe-42c9-9f6e-f0836359ecfe)
![Win Ver](https://github.com/stascorp/rdpwrap/assets/140702552/9e90f977-e7e2-4faa-b5f8-9ddeabea104e)

**Comment by binarymaster** [comment]
Duplicate of #2258.

**Comment by TheMazoo** [comment]
> Duplicate of #2258.
Hello, thanks for letting me know. I downloaded the mentioned ini file, but without any prevail. I am not exactly sure how to use or integrate the ini file into the Wrapper. Could you help me please?

**Comment by sashaqwert** [comment]
> how to use or integrate the ini file into the Wrapper

https://github.com/stascorp/rdpwrap/issues/2258#issuecomment-1653913324
