### ISSUE TITLE
不支持windows11 10.0.22000.2176

### ISSUE THREAD

**Issue by qwerrevge** [stascorp/rdpwrap#2297]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12215914/termsrv.zip)

**Comment by sashaqwert** [comment]
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/12215914/termsrv.zip)

Your `termsrv.dll` version is `10.0.22000.2124`

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/a378ab7e-c3e0-4567-b9d5-2f3e7dabeb43)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2263
