### ISSUE TITLE
RDP wrapper fully support but not listening on 19041.3155

### ISSUE THREAD

**Issue by MrBear2018** [stascorp/rdpwrap#2298]
I use the ini file from this issues,  https://github.com/stascorp/rdpwrap/issues/2257
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/29e6876e4fff72f8d75a7633a4ad0b50c6be36bd

I have tried uninstall and install , but it not work. 

wrapper state : installed, ver : 1.5.0.0
service state : running, ver : 10.0.19041.3155
listener state: not listening   [fully supported]

**Comment by sashaqwert** [comment]
> I use the ini file from this issues, #2257 [sebaxakerhtc/rdpwrap.ini@29e6876](https://github.com/sebaxakerhtc/rdpwrap.ini/commit/29e6876e4fff72f8d75a7633a4ad0b50c6be36bd)
> 
> I have tried uninstall and install , but it not work.

One `termsrv.dll` version = ONE opened issue --> DUPLICATE.

This rule is being followed now. Nothing will change until Stas'M resumes INI support.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2257

**Comment by Malkov008** [comment]
Я не понимаю что с этим делать
![Screenshot_1](https://github.com/user-attachments/assets/fd287833-fc47-4dc4-8804-cdee55fa6025)
