### ISSUE TITLE
Cannot shadow desktop

### ISSUE THREAD

**Issue by markreg** [stascorp/rdpwrap#230]
Where `TARGETSERVER` is replaced with an ip address of a remote machine which I can successfully rdp to.
Shadowing the console or any other session does not work unless I shadow from within an rdp session to the same machine.

`mstsc /v:TARGETSERVER /shadow:1 /noConsentPrompt`

It gets stuck on the Remote Desktop Connection window: `Connecting to: TARGETSERVER`.

**Comment by binarymaster** [comment]
This method works only when `TARGETSERVER` is running Windows 8 (Server 2012) or higher.

**Comment by markreg** [comment]
The target and client machines are both running Windows 10 x64 Enterprise.

**Comment by binarymaster** [comment]
Well, maybe it uses some other port for remote shadowing, I actually not tested this.

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.
