### ISSUE TITLE
RDP logon window prompts connection to previously disconnected session(s)

### ISSUE THREAD

**Issue by markreg** [stascorp/rdpwrap#231]
Sometimes, when logging into a 3rd or 4th session on the same account, rdp shows the login screen of the remote machine with previously disconnected sessions.

I've unchecked the `Single session per user` setting in RDPConf.

I also have Computer Configuration group policy set to delete disconnected sessions from the server in 5 minutes and disconnect idle sessions in 3 hours.

I'm not sure why I cannot login to an unlimited number of sessions per user without having to connect to a previously disconnected user (that will eventually be deleted anyway).

**Comment by binarymaster** [comment]
This is normal behaviour of Terminal Services, RDP Wrapper can't change it.
