### ISSUE TITLE
Windows 11 PRO - 22H2 22621.2134 not supported

### ISSUE THREAD

**Issue by Bkindazgrs** [stascorp/rdpwrap#2310]
I tried the .ini file on issue [# 2290](https://github.com/stascorp/rdpwrap/issues/2290) it does not work for Windows 11 PRO - 22H2 22621.2134 

Please help.

![image](https://github.com/stascorp/rdpwrap/assets/142029069/ac430994-7ff6-43c6-9a46-a99e4f5aa60f)
![image](https://github.com/stascorp/rdpwrap/assets/142029069/02fa3929-f4f6-438d-b834-378e66926cf1)

RDP Wrap check and conf are in a separate directory than installed files.

**Comment by Bkindazgrs** [comment]
Added termsrvdll.zip
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12322491/termsrv.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2290
