### ISSUE TITLE
need supports for windows 10.0.19045.2728  

### ISSUE THREAD

**Issue by nsnail** [stascorp/rdpwrap#2312]
![image](https://github.com/stascorp/rdpwrap/assets/1327344/2e70d753-055b-4cbb-b33c-b7124d1a3041)

![image](https://github.com/stascorp/rdpwrap/assets/1327344/ba333999-9efa-4f68-a386-9764fefe278b)
There are 2 termsrv.dll with different byte sizes.
![image](https://github.com/stascorp/rdpwrap/assets/1327344/aca95512-e04f-497f-96ab-5b417ee8cf52)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12384770/termsrv.zip)

**Comment by sashaqwert** [comment]
RDP Wrapper deleted by antivirus. See https://github.com/stascorp/rdpwrap/issues/1883
