### ISSUE TITLE
There are 19045.3324 rdpwrap.ini files ？

### ISSUE THREAD

**Issue by gzlj007** [stascorp/rdpwrap#2314]
There are 19045.3324 rdpwrap.ini files ？

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sebaxakerhtc** [comment]
@sashaqwert 
https://github.com/sebaxakerhtc/rdpwrap.ini/issues/278

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2257

**Comment by gzlj007** [comment]
> Duplicate of #2257

Thank you very much. I couldn't copy the ini link you provided directly. I searched for the version you provided in the project and reinstalled it. Thank you again

**Comment by gzlj007** [comment]
> Duplicate of #2257

How can I determine which version of ini to use based on the DLL?
