### ISSUE TITLE
please 10.0.17763.4010 doesn't work

### ISSUE THREAD

**Issue by hou0030** [stascorp/rdpwrap#2316]
anyone who has 10.0.17763.4010 please share your termsrv.dll

**Comment by hou0030** [comment]
![image](https://github.com/stascorp/rdpwrap/assets/142816838/430d22a6-ebac-4cf0-b248-934847fb661b)

**Comment by sashaqwert** [comment]
`termsrv.dll` version ≠ Windows version!

Please, use `termsrv.dll` version in issue title.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2041
