### ISSUE TITLE
idk just help me 

### ISSUE THREAD

**Issue by wewewewe1313** [stascorp/rdpwrap#2319]

**Comment by wewewewe1313** [comment]
![image](https://github.com/stascorp/rdpwrap/assets/142930510/37fd9b27-6ebd-48fe-ba6a-dda666b92c43)

**Comment by wewewewe1313** [comment]
i cant redownload all the othere stuff
like the dll
and idk what to do as i tryed to unistall and redownload everything

**Comment by wewewewe1313** [comment]
![image](https://github.com/stascorp/rdpwrap/assets/142930510/6f491613-43b6-4aaf-8faa-80ed9dabda8d)
 like it just shows this

**Comment by wewewewe1313** [comment]
new issue everything is fixed i cant conecct it says acces denied

**Comment by sashaqwert** [comment]
> ![image](https://user-images.githubusercontent.com/142930510/262439197-37fd9b27-6ebd-48fe-ba6a-dda666b92c43.png)

Solution in https://github.com/stascorp/rdpwrap/issues/1883

**Comment by sashaqwert** [comment]
> new issue everything is fixed i cant conecct it says acces denied

You need add your RDP users to Administrators or "Remote desktop users" group
