### ISSUE TITLE
Windows 11 PRO - 22H2 10.0.19045.3393 not supported

### ISSUE THREAD

**Issue by machi67** [stascorp/rdpwrap#2321]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12446694/termsrv.zip)

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2289
