### ISSUE TITLE
Problem with multiuser with same username not working. Session is taken over when user with same username login

### ISSUE THREAD

**Issue by mucfun** [stascorp/rdpwrap#2322]
I disabled Single session per user but if a user with same username and password logs in the first session of the same username  is taken over. With different usernames everything works fine but i want that more then one user with the same name can use on special profile. The computer is not member of an  active directory. Wrapper and ini is up to date. OS is windows 10 22H2. Any idea whats the problem?

**Comment by sashaqwert** [comment]
See https://github.com/stascorp/rdpwrap/issues/1952
