### ISSUE TITLE
Broken since Windows 10 Creators Update

### ISSUE THREAD

**Issue by maxborn** [stascorp/rdpwrap#233]
Hi Guys, first, nice work with RDPwrapper, Thank! Jut one comment, though, RDP wrapper v1.6.1 is not working since the Creators update (April 2017). The update is not officially out yet, it will be on April 11, but as a Windows Insider I already got W10 build 15063 installed (likely the official Creators update), and RDPwrapper is not working.
I know you probably want to wait for the official Creators update to be out to troubleshoot and fix the problem, but if you work on it in advance of April 11, then by the time the problem strikes most RDPwrapper users, the updated RDPwrapper will be out, minimizing disrruptions.
Think about it. And thanks again.
To install the Creators update in advance, without having to register as a windows insider, just download and run the W10 update tool: https://go.microsoft.com/fwlink/?linkid=845981
Regards.
Max.

**Comment by binarymaster** [comment]
Known issue, see https://github.com/stascorp/rdpwrap/issues/229#issuecomment-292485948.
