### ISSUE TITLE
opening rdp and i cant see anything 

### ISSUE THREAD

**Issue by SkylarN0601** [stascorp/rdpwrap#2331]
when i open rdp its just a blue screan i got it to be supported after a while idk what to do now

**Comment by SkylarN0601** [comment]
![Rdp help1](https://github.com/stascorp/rdpwrap/assets/144587101/b0dc2b4e-a5ab-4fce-ab6d-b5fa44ffe944)

**Comment by SkylarN0601** [comment]
![Rdp help2](https://github.com/stascorp/rdpwrap/assets/144587101/08eff623-803d-40e8-a3a9-c133e2992984)
![Rdp help3](https://github.com/stascorp/rdpwrap/assets/144587101/09252504-6ebc-46fa-b246-19e907cf8f5b)

**Comment by SkylarN0601** [comment]
i dont know what to do

**Comment by sashaqwert** [comment]
You need to [convert your Microsoft account to local account](https://www.itechtics.com/change-account-type/).
