### ISSUE TITLE
Prompt 'Unable to verify identity' when connecting

### ISSUE THREAD

**Issue by LanYangYang-114** [stascorp/rdpwrap#2338]
My English is terrible, I use translation software to translate what I want to say into English

Starting from a certain day, this prompt will appear when connecting to my laptop, regardless of which computer it is. After clicking 'Yes', you will enter a login interface without a login button and cannot perform any operations. Attempting to uninstall and reinstall RDPwrap is invalid. You must specify a username before connecting to the remote desktop to successfully log in, which is too cumbersome. How to effectively solve this problem (except for reinstalling the system)

Here is my system information：
Version Windows 11 Home Chinese Version
Version 22H2
Installation date: November 2nd, 2022
Operating system version 22621.2283
Experience Windows Feature Experience Pack 1000.22662.1000.0

![系统信息](https://github.com/stascorp/rdpwrap/assets/84030410/e8a2daeb-b294-4edb-b435-c3dbf0a118b9)
![屏幕截图 2023-09-21 102939](https://github.com/stascorp/rdpwrap/assets/84030410/2bcbb0ff-e402-4ed1-87fe-410491574fb6)
![屏幕截图 2023-09-21 103008](https://github.com/stascorp/rdpwrap/assets/84030410/2d8ecffd-4264-459a-9506-4c76d1c2ac37)

**Comment by sashaqwert** [comment]
> Unable to verify identity

You need use `Network level authentication` or `Default RDP authentication` in RDPConf.

> After clicking 'Yes', you will enter a login interface without a login button and cannot perform any operations.

You need to [convert your Microsoft account to local account](https://www.digitalcitizen.life/switch-to-local-account-from-microsoft-windows-11/).
