### ISSUE TITLE
acess denied

### ISSUE THREAD

**Issue by ImsorryPopi** [stascorp/rdpwrap#2339]
says acess denied i have made sure the profile is admin and earthing dont know what to do 
![reeeee](https://github.com/stascorp/rdpwrap/assets/144615639/06696a39-d9a3-4804-9899-6a06786c5829)

**Comment by ImsorryPopi** [comment]
and now i have no audio sound when trying to troubleshoot can someone walk me through?

**Comment by sashaqwert** [comment]
> says acess denied i have made sure the profile is admin and earthing dont know what to do

See https://github.com/stascorp/rdpwrap/issues/101

**Comment by sashaqwert** [comment]
> and now i have no audio sound when trying to troubleshoot can someone walk me through?

Not in this thread. If you think this is related to RDP Wrapper, you can ask in Telegram chat (link in README of the repository)
