### ISSUE TITLE
Cannot Listen while running newest windows 10 creators update 

### ISSUE THREAD

**Issue by miekshreds** [stascorp/rdpwrap#234]
Hello, I am having an issue trying to connect to my windows 10 home client with the rdp wrapper installed due to the newest update of windows 10 home. Every other part of the program works besides the listening . I can ping to the client but I cannot rdp into the client. Is there any easy way around the newest update?
Thanks in advance-Mike

**Comment by miekshreds** [comment]
![fml](https://cloud.githubusercontent.com/assets/6694023/24848768/69ab2e52-1d96-11e7-857b-67f8d4cfe6d0.png)

**Comment by binarymaster** [comment]
Known issue, see https://github.com/stascorp/rdpwrap/issues/229#issuecomment-292485948.
