### ISSUE TITLE
Windows 10 Pro 19045.3448 Not support

### ISSUE THREAD

**Issue by SteveCodeFox** [stascorp/rdpwrap#2340]
![image](https://github.com/stascorp/rdpwrap/assets/85626499/8c54102a-1b64-44e9-af22-11f7f0075e01)
![image](https://github.com/stascorp/rdpwrap/assets/85626499/a3a47d77-86f6-4f96-8f4e-7fddbd341311)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2289
