### ISSUE TITLE
Do you support udp？

### ISSUE THREAD

**Issue by ifeif** [stascorp/rdpwrap#2342]
Does udp transfer of remote desktop be supported?

**Comment by sashaqwert** [comment]
> Does udp transfer of remote desktop be supported?

Yes, supported. You need add firewall rule manually. (Copy TCP rule and change protocol to UDP)

**Comment by ifeif** [comment]
> > Does udp transfer of remote desktop be supported?
> 
> Yes, supported. You need add firewall rule manually. (Copy TCP rule and change protocol to UDP)

Thank you for your answer
