### ISSUE TITLE
Windows 11 22H2 Build 10.0.22621.2134 not supported

### ISSUE THREAD

**Issue by smilima** [stascorp/rdpwrap#2347]
Edition	Windows 11 Education
Version	22H2
Installed on	‎9/‎7/‎2023
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

![image](https://github.com/stascorp/rdpwrap/assets/24381908/be216fa4-ad2e-498c-9d37-aae636f5bf43)

**Comment by smilima** [comment]
I found it in the .ini.  I must be doing something wrong.

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2290
