### ISSUE TITLE
Windows 10 Pro 22H2 19045.3448 not supported

### ISSUE THREAD

**Issue by caixeta1979** [stascorp/rdpwrap#2348]
![Capturar](https://github.com/stascorp/rdpwrap/assets/146453438/023ba1f2-8482-4225-9456-f94b4e393895)

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2289

**Comment by JVMM25** [comment]
hola... se me actualizo el Windows necesito el código para esta versión. Windows 10 pro 22h2 19045.3448 por favor.
