### ISSUE TITLE
Windows 10 RDP patch file not supported plz help. 

### ISSUE THREAD

**Issue by aniket950840** [stascorp/rdpwrap#2353]

**Comment by aniket950840** [comment]
![IMG_20231007_061711_841.jpg](https://github.com/stascorp/rdpwrap/assets/145317098/227d6574-16e9-4942-86b8-85ce4f482f0c)

**Comment by sashaqwert** [comment]
`termsrv.dll` patches is offtopic here!

RDP Wrapper was created with the goal of avoiding termsrv.dll patches.

RDP Wrapper runs the standard termsrv.dll library with different parameters.
