### ISSUE TITLE
Windows 10 Pro for Workstations 19045.3448 not Supported

### ISSUE THREAD

**Issue by DriftingStarry** [stascorp/rdpwrap#2355]
![screenshot](https://github.com/stascorp/rdpwrap/assets/140683007/1e31a1b3-473f-4dc1-9ac1-814313bbd738)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12846952/termsrv.zip)

**Comment by sashaqwert** [comment]
Your `termsrv.dll` version is 10.0.19041.3271. See issue https://github.com/stascorp/rdpwrap/issues/2289

Your `termsrv.dll` version is not displayed in RDPConf. You needed to repair your OS. See also https://github.com/stascorp/rdpwrap/issues/1883

**Comment by DriftingStarry** [comment]
thanks!!!!! 
it does works
