### ISSUE TITLE
10.0.190.3570 not supported not listening

### ISSUE THREAD

**Issue by crossover277** [stascorp/rdpwrap#2357]
I installed everything and followed the directions but am still getting not listening not supported

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12860927/termsrv.zip)
![Capture1](https://github.com/stascorp/rdpwrap/assets/147542497/335f71f0-05cd-41dd-8acf-56435d63057c)

**Comment by affinityv** [comment]
@sebaxakerhtc 

[termsrv--Win10--2023-10-11--10.0.19041.3570--64bit.zip -- with pdb](https://github.com/stascorp/rdpwrap/files/12861642/termsrv--Win10--2023-10-11--10.0.19041.3570--64bit.zip)

**Comment by anpaulus** [comment]
@affinityv still can't login altough capture screen is listening

**Comment by gczhangyb** [comment]
[10.0.19041.3570]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=C3299
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3FDC7
SingleUserCode.x86=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=41999
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
SLInitHook.x86=1
SLInitOffset.x86=70E18
SLInitFunc.x86=New_CSLQuery_Initialize
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=92AF1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=11E12
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1F315
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=2866C
SLInitFunc.x64=New_CSLQuery_Initialize


[10.0.19041.3570-SLInit]
bInitialized.x86      =E498C
bServerSku.x86        =E4990
lMaxUserSessions.x86  =E4994
bAppServerAllowed.x86 =E499C
bRemoteConnAllowed.x86=E49A4
bMultimonAllowed.x86  =E49A8
ulMaxDebugSessions.x86=E49AC
bFUSEnabled.x86       =E49B0
bInitialized.x64      =125074
bServerSku.x64        =125078
lMaxUserSessions.x64  =12507C
bAppServerAllowed.x64 =125084
bRemoteConnAllowed.x64=12508C
bMultimonAllowed.x64  =125090
ulMaxDebugSessions.x64=125094
bFUSEnabled.x64       =125098

**Comment by tigger2888** [comment]
> [10.0.19041.3570] LocalOnlyPatch.x86=1 LocalOnlyOffset.x86=C3299 LocalOnlyCode.x86=jmpshort SingleUserPatch.x86=1 SingleUserOffset.x86=3FDC7 SingleUserCode.x86=Zero DefPolicyPatch.x86=1 DefPolicyOffset.x86=41999 DefPolicyCode.x86=CDefPolicy_Query_eax_ecx SLInitHook.x86=1 SLInitOffset.x86=70E18 SLInitFunc.x86=New_CSLQuery_Initialize LocalOnlyPatch.x64=1 LocalOnlyOffset.x64=92AF1 LocalOnlyCode.x64=jmpshort SingleUserPatch.x64=1 SingleUserOffset.x64=11E12 SingleUserCode.x64=Zero DefPolicyPatch.x64=1 DefPolicyOffset.x64=1F315 DefPolicyCode.x64=CDefPolicy_Query_eax_rcx SLInitHook.x64=1 SLInitOffset.x64=2866C SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.19041.3570-SLInit] bInitialized.x86 =E498C bServerSku.x86 =E4990 lMaxUserSessions.x86 =E4994 bAppServerAllowed.x86 =E499C bRemoteConnAllowed.x86=E49A4 bMultimonAllowed.x86 =E49A8 ulMaxDebugSessions.x86=E49AC bFUSEnabled.x86 =E49B0 bInitialized.x64 =125074 bServerSku.x64 =125078 lMaxUserSessions.x64 =12507C bAppServerAllowed.x64 =125084 bRemoteConnAllowed.x64=12508C bMultimonAllowed.x64 =125090 ulMaxDebugSessions.x64=125094 bFUSEnabled.x64 =125098


HOW TO APPLY THIS SIR? (I'm new just know only replacing rdpwarp.ini)

**Comment by gczhangyb** [comment]
add the config to rdpwarp.ini
![image](https://github.com/stascorp/rdpwrap/assets/147575666/b964f58d-27ba-45a8-b0fb-cf42222ee038)
![image](https://github.com/stascorp/rdpwrap/assets/147575666/6a980855-6349-4991-bcd2-05723ec0c2d7)

**Comment by tigger2888** [comment]
> add the config to rdpwarp.ini ![image](https://user-images.githubusercontent.com/147575666/274134220-b964f58d-27ba-45a8-b0fb-cf42222ee038.png) ![image](https://user-images.githubusercontent.com/147575666/274134271-6a980855-6349-4991-bcd2-05723ec0c2d7.png)


IT'S WORK!! 
Thank you so muuuuuch! <3

**Comment by seng5899** [comment]
After adding the code,but now still not listening,but is fully supported~How to fix it?

**Comment by sashaqwert** [comment]
@crossover277 Please, rename your issue to 10.0.19041.3570 (fix typo in title)

Otherwise, I will close this issue with an indication of the first one with the correct name.  (They created a lot of them today...)

**Comment by sashaqwert** [comment]
This issue has been absorbed https://github.com/stascorp/rdpwrap/issues/2359
