### ISSUE TITLE
Windows 11 10.0.22621.2361 Not listening

### ISSUE THREAD

**Issue by 4zur-0312** [stascorp/rdpwrap#2360]
![image](https://github.com/stascorp/rdpwrap/assets/126742910/0698db95-4415-41be-baa0-b22916788dde)

After update windows, RDP Wrapper don't work

**Comment by sashaqwert** [comment]
One `termsrv.dll` version = ONE opened issue!

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2345

**Comment by sashaqwert** [comment]
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131
