### ISSUE TITLE
Not supported 10.0.17763.4644 Help 

### ISSUE THREAD

**Issue by hknclk34** [stascorp/rdpwrap#2363]
![image](https://github.com/stascorp/rdpwrap/assets/95570730/434ea331-d327-45fb-8427-94577570fac5)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12868587/termsrv.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2274
