### ISSUE TITLE
cant do remote desktop connection

### ISSUE THREAD

**Issue by SistemasFb1** [stascorp/rdpwrap#2365]
Hi, just updated Windows 11 version and now can´t do a remote desktop connection. All the labels on rdp.config appear on green (supported, listening, etc), i can even ping just fine with the server but at the moment i try to do a remote connection i get this error (image above).
![RDP-connection-failed](https://github.com/stascorp/rdpwrap/assets/147656760/fa23730b-e698-4f6e-9288-37baf4a8e7c1)

**Comment by sashaqwert** [comment]
If you changed RDP port you need to open this port in firewall.

> All the labels on rdp.config appear on green

No RDPConf attached. Closed as invalid :)
