### ISSUE TITLE
Windows 10 version 19045.3570 not supported

### ISSUE THREAD

**Issue by machi67** [stascorp/rdpwrap#2368]

**Comment by sashaqwert** [comment]
`termsrv.dll` version != Windows version!

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2359

**Comment by JVMM25** [comment]
tengo el mismo problema. necesito el código para la versión Windows 10 19045.3570

**Comment by sashaqwert** [comment]
> 10 19045.3570

# What is your `termsrv.dll` version?

https://t.me/rdpwrap

**Comment by JVMM25** [comment]
> > 10 19045.3570
> 
> # ¿Cuál es tu `termsrv.dll`versión?
> https://t.me/rdpwrap
![z](https://github.com/stascorp/rdpwrap/assets/149393979/0b60a52d-55b9-43b9-87e4-8351d0dcfd89)

**Comment by sashaqwert** [comment]
@JVMM25 

https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
