### ISSUE TITLE
RDP Wrapper Library v1.6.2 detected with Bladabindi.Backdoor.Bot.DDS? 

### ISSUE THREAD

**Issue by jimboat63** [stascorp/rdpwrap#2373]
MALWAREBYTES advises that RDP Wrapper Library v1.6.2 is detected with Bladabindi.Backdoor.Bot.DDS? 

is this new?

is RDP Wrapper Library v1.6.2 safe?

**Comment by sashaqwert** [comment]
Threat about viruses is https://github.com/stascorp/rdpwrap/issues/277

> Bladabindi.Backdoor.Bot.DDS

The issue I mentioned does not mention this virus, but you can write a message about it there.
