### ISSUE TITLE
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/12919284/rdpwrap.zip)

### ISSUE THREAD

**Issue by tapareajit** [stascorp/rdpwrap#2374]
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/12919284/rdpwrap.zip)

_Originally posted by @Sianmung in https://github.com/stascorp/rdpwrap/issues/2362#issuecomment-1764842877_
            
![Capture](https://user-images.githubusercontent.com/58855753/277094536-9818a915-d587-4408-8122-879aace1ccd9.PNG)

But 2nd user not able to login

**Comment by sashaqwert** [comment]
> Originally posted by @Sianmung in [#2362 (comment)](https://github.com/stascorp/rdpwrap/issues/2362#issuecomment-1764842877)

But this link to locked as off-topic thread --> this also off-topic... (c) @binarymaster 

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/ded7b4d4-5e0f-4a2b-a468-58d36a23f1a1)
