### ISSUE TITLE
Update.bat Not working and Cant find VPNWrap.INI to make file changes

### ISSUE THREAD

**Issue by joannpot** [stascorp/rdpwrap#238]
After downloading and running the Update.bat as suggested, I keep getting an error that the .INI cant be read. I tried to update the .INI manually but cant find the .INI file to update or rewrite. Please i need help on how to locate the .INI file. It keep showing Not Supported. What else can be done for me to be able to updat it automatically. Please help

**Comment by binarymaster** [comment]
See this: https://github.com/stascorp/rdpwrap/issues/215#issuecomment-285806630

**Comment by binarymaster** [comment]
Also try to reinstall it cleanly (uninstall first, then install latest version).

**Comment by joannpot** [comment]
Thanks for your @binarymaster, I forgot to add that I'm using Windows 10. i uninstall and reinstall as you suggested but keep getting the same error. here is the screenshot maybe this would help. Please note that I"m not a newbie to computers and software so I'm quite sure of what I'm doing. I want to know if there's anything I'm missing or didnt get right. I need your help so badly. Thanks
<img width="408" alt="install" src="https://cloud.githubusercontent.com/assets/27995326/25496897/aff1c21e-2b50-11e7-9aae-d68eff4c88ae.PNG">
<img width="213" alt="capture" src="https://cloud.githubusercontent.com/assets/27995326/25496902/b566b5b0-2b50-11e7-915d-b7804dbbe074.PNG">
<img width="306" alt="first shot" src="https://cloud.githubusercontent.com/assets/27995326/25496905/b7c1997e-2b50-11e7-9dc8-0150c89eb6f8.PNG">

**Comment by binarymaster** [comment]
> <img width="408" alt="install" src="https://cloud.githubusercontent.com/assets/27995326/25496897/aff1c21e-2b50-11e7-9aae-d68eff4c88ae.PNG">

You did not uninstalled it.

**Comment by joannpot** [comment]
really, I have checked my control panel and coulnd't find it, where else can i find it to uninstall please

**Comment by binarymaster** [comment]
You did not run `uninstall.bat`

**Comment by joannpot** [comment]
Yes i uninstalled it and reinstall the new version as you suggested but each time i try to config it shows me the same messages..

**Comment by joannpot** [comment]
Each time i uninstall.bat it log me off automatically and now i can't login from my office right now.. here is the screenshot maybe you could understand wnat I'm talking about. 

<img width="433" alt="capture" src="https://cloud.githubusercontent.com/assets/27995326/25497539/f83e021a-2b52-11e7-917b-93629aa6a91e.PNG">

**Comment by binarymaster** [comment]
Please provide `uninstall.bat` output log for the details. And use something other except RDP for maintenance, like Telnet or PSExec.
