### ISSUE TITLE
10.0.17763.4737 Not Support

### ISSUE THREAD

**Issue by ShefaRu** [stascorp/rdpwrap#2380]
Microsoft Windows [版本 10.0.17763.4737]
OS 名称:          Microsoft Windows Server 2019 Standard
OS 版本:          10.0.17763 暂缺 Build 17763
OS 制造商:        Microsoft Corporation

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment]
File not attached. Closed.
