### ISSUE TITLE
RDP wont access Desktop?

### ISSUE THREAD

**Issue by MarcusSubiran** [stascorp/rdpwrap#2385]
I am having issues with rdp connecting, but not allowing me into my desktop. It is stuck at this.
![Screenshot 2023-10-27 233337](https://github.com/stascorp/rdpwrap/assets/101434347/21b24b06-7bdf-4a86-985c-bd0025d42e1e)

**Comment by sashaqwert** [comment]
You need to [convert your Microsoft account to local account](https://www.digitalcitizen.life/switch-to-local-account-from-microsoft-windows-11/).
