### ISSUE TITLE
 My firewall is open

### ISSUE THREAD

**Issue by 2414466154** [stascorp/rdpwrap#2388]
My firewall is open

![6132f73e179d05f5804ac894df9a432](https://github.com/stascorp/rdpwrap/assets/38528977/5a8f85f6-4bda-42d8-bff6-9bf3df93a492)

**Comment by sashaqwert** [comment]
> My firewall is open

?????

**Comment by sashaqwert** [comment]
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by 2414466154** [comment]
> Try:
> 
> 1. Download RDP Wrapper 1.6.2 and extract this to any directory.
> 2. Place `rdpwrap.ini` in the same directory.
> 3. Open CMD as administrator
> 4. Execute this commands
> 
> ```
> cd C:\path\to\directory\
> rdpwinst -u -k
> rdpwinst -i
> ```
> 
> 5. Enjoy!
> 
> Original message: https://t.me/rdpwrap/49131

My problem has been resolved
https://github.com/sebaxakerhtc/rdpwrap.ini/issues/297
Just download the corresponding version of the. dll file and overwrite it
