### ISSUE TITLE
Windows Update KB3150513 

### ISSUE THREAD

**Issue by DeteG** [stascorp/rdpwrap#239]
When Windows "compatibility definition update" KB3150513 is installed RDP wrapper conifg shows everything fine (listening, fully supported) even RDPcheck appears to be functioning (may be did not test long enough).
First remote desktop connection after a restart of teh PC works for half a minute and gets lost afterwards, not allowing any connection any more until the PC is restarted again.
Deinstallation of KB3150513 and restarting the PC helps: Remote Desktop is accessible again.
Unfortunately the update reinstalls automatically and will get active again after the next restart.

Any permanent Solution known?

**Comment by paulmann** [comment]
1. Deinstall of KB3150513 
2. Disable Autoinstall windows updates
3. Check new updates
4. Right click on KB3150513 and press "Hide update"
5. Enable Autoupdate

**Comment by YisroelAdler** [comment]
In Windows 10 you cannot hide updates from the Windows Update interface. You need to use a special tool from Microsoft for that. 

See details in this Microsoft help guide https://support.microsoft.com/en-us/help/3073930/how-to-temporarily-prevent-a-driver-update-from-reinstalling-in-windows-10

**Comment by binarymaster** [comment]
Try restarting `TermService` service, and see Event Log for any errors. This looks like a bug from Microsoft.

**Comment by binarymaster** [comment]
Closing as inactive.
