### ISSUE TITLE
Listener state not listening [fully supported] 

### ISSUE THREAD

**Issue by Harmfoo** [stascorp/rdpwrap#2392]
![image](https://github.com/stascorp/rdpwrap/assets/149838628/aba72c2c-5d36-4521-b423-0ea72bc5421b)
![image](https://github.com/stascorp/rdpwrap/assets/149838628/7464aa32-167e-4efb-a640-0ddb98fc0dca)

I'm thinking its because my term service doesnt match my windows version? I have looked everywhere and tried manual solutions multiple times to no avail, hoping someone here can help me out

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2390

**Comment by sashaqwert** [comment]
Read from here https://t.me/rdpwrap/63551

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2359
