### ISSUE TITLE
Wrapper state: Unknown Ver 10.0.19041.3636

### ISSUE THREAD

**Issue by liran1115** [stascorp/rdpwrap#2393]
Hi,

In configuration file I saw wrapper state & service state unknow.
Listener state: not listening.
Ver 10.0.19041.3636

I use the install file. Someone know why?
When I opened the install file, its written in CMD:
"You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program"

I have Win 10 Home addition, 22H2 1000.19053.1000.0

Regards,
Liran.

**Comment by sashaqwert** [comment]
> In configuration file I saw wrapper state & service state unknow.

Solution in https://github.com/stascorp/rdpwrap/issues/1883


> Ver 10.0.19041.3636

After repair see https://github.com/stascorp/rdpwrap/issues/2381
