### ISSUE TITLE
 10.0.22631.2428 not supported ?

### ISSUE THREAD

**Issue by huake521** [stascorp/rdpwrap#2396]

**Comment by huake521** [comment]
![截图11月11_22 22 38](https://github.com/stascorp/rdpwrap/assets/55798180/d5bbba3e-b352-4820-b019-677c98b01343)

**Comment by huake521** [comment]
[Uploading termsrv.dll.txt…]()

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2345
