### ISSUE TITLE
Console/Admin session

### ISSUE THREAD

**Issue by mobamoba** [stascorp/rdpwrap#240]
I'm not really sure if this is a bug or something I'm doing wrong, but how do you connect to the console/admin session, i.e. the current logged-on session? For example using Microsoft RDP app in Android has and "admin" switch to allow connection to the current running session, but this doesn't work with RDP Wrapper. Instead, a new session opens. So is there a way to enable this in RDP Wrapper? Thanks.

**Comment by binarymaster** [comment]
Enable single session per user in config.

**Comment by mobamoba** [comment]
I actually meant is there a way to access the console session with multiple sessions enabled?

**Comment by binarymaster** [comment]
Use `tscon` console utility (if it doesn't exist, google it), it allows to connect to existing sessions.

**Comment by mobamoba** [comment]
Sure but tscon is a Windows program. When RDP-ing using Microsoft's own Android RDP app - which has an "Admin" option (meaning console session) - you still can't connect to the console session, just a new session. There's something with RDPWrap and multiple sessions enabled that somehow isn't "respecting" the Admin/console login request from non-Windows apps including Microsoft's own.

**Comment by binarymaster** [comment]
You need to enable "Single Session Per User" option in order to do that. There's no other solution.

If this is disabled, then you'll always get a new session.

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.
