### ISSUE TITLE
win 11 issue

### ISSUE THREAD

**Issue by tonythecodeur** [stascorp/rdpwrap#2400]
cant make it work on win 11 home edition

RDPWInst-v1.6.2.msi (windows doesnt let it opening, invalid installer)
![image](https://github.com/stascorp/rdpwrap/assets/12103196/182e525d-016b-4c93-81ac-e2e33f8bd77d)

**Comment by tonythecodeur** [comment]
fixed with the new .ini file

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2345
