### ISSUE TITLE
10.0.19041.3636 not supported

### ISSUE THREAD

**Issue by JEST28** [stascorp/rdpwrap#2407]
![image](https://github.com/stascorp/rdpwrap/assets/150926597/c64f9fa6-95d3-419b-b4fe-ab6d4487a533)

**Comment by fweb** [comment]
rdpwrap.ini from this https://github.com/stascorp/rdpwrap/issues/2406 fixed it for me. maybe you can try?

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381
