### ISSUE TITLE
concurrent sessions not working anymore

### ISSUE THREAD

**Issue by hallo9** [stascorp/rdpwrap#241]
Hi, I used the latest Version and ini file on Windows 10 PRO Creators Update 10.0.15063. Connection itself is working and looks good in rdpconfig. And I can connect remotely, thats´s good, too.

But I can´t login as a concurrent sessions when someone else is already logged in localy. This worked for years with many Windows versions, but now with latest Windows Update it is not working anymore.

Tried on a bunch of Computers.

Any ideas and help ? 

Would be great, thank you.

**Comment by instinctualjealousy** [comment]
Might be related to issue #194, since something has changed fundamentally with how RDP works in insider builds from January up to now with RTM Creator's. Don't take my word for it though, I don't have RDPWrap installed on this pro machine here and haven't tested it.
