### ISSUE TITLE
rdp wrapper x64 10.0.19041.3271 not supported on win10 

### ISSUE THREAD

**Issue by 17886365143** [stascorp/rdpwrap#2413]

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2289

**Comment by sashaqwert** [comment]
![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/b2e68a8d-63a1-4e0d-9e65-f084f9f00132)
