### ISSUE TITLE
TermService is hosted in a custom application (BeTwin, etc.>unsupported

### ISSUE THREAD

**Issue by zyk014** [stascorp/rdpwrap#2416]
![wenti](https://github.com/stascorp/rdpwrap/assets/61350008/da8d6184-1c39-41e7-b937-21a8c7d7e48a)
The following error occurred during the installation of server 2012R2. Requesting help

**Comment by sashaqwert** [comment]
Solution in https://github.com/stascorp/rdpwrap/issues/1883
