### ISSUE TITLE
It’s Supported but not working

### ISSUE THREAD

**Issue by hovanaz** [stascorp/rdpwrap#2419]
It's have been worked with https://github.com/.../INI-RDPWRAP/blob/master/rdpwrap.ini , but yesterday it's say Not Supported, so I change new file .ini . Then it's supported but not work
![IMG_6933](https://github.com/stascorp/rdpwrap/assets/65497218/4df45a3f-a4e7-41c5-bf82-02f35aadae7b)

**Comment by hovanaz** [comment]
![image](https://github.com/stascorp/rdpwrap/assets/65497218/e4534331-0106-4a23-9854-ef08cad9f521)

**Comment by hovanaz** [comment]
window 10pro

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381

**Comment by sashaqwert** [comment]
> window 10pro

The Windows edition does not matter. Only the version of `termsrv.dll` and its architecture are important.
