### ISSUE TITLE
OpenGL support goes weird in Win10 Home edition

### ISSUE THREAD

**Issue by 4321qasdfv** [stascorp/rdpwrap#242]
It is known that mstsc graphic driver doesn't support opengl. When opening a game which needs opengl, it can not succeed in creating a window. You will get a error message like this.

Error launch application
Can't create gl window
More info:
GLFWError #65542 Happen, WGL: The driver does not appear to support OpenGL

(Something wrong when updating the screenshot, so I typed the error message here)

However, when I am using rdpwrap in Win10 Home edition, the window is successfully created in the remote session. I wonder how it happened, and if Pro edition can do something to support opengl.

**Comment by binarymaster** [comment]
Does your remote OpenGL application work correctly, or it only creates a window and no more?

**Comment by jsganga** [comment]
I get the same error message using the glfw library. It does not create the window.

To repro:
```python
import glfw
glfw.init()
window = glfw.create_window(50, 50, "Test OpenGL Window", None, None)
```

**Comment by RobertSpir** [comment]
OpenGL support depends on graphics card. Intel and AMD support opengl without problems, NVIDIA support opengl through remote desktop only on expensive Quadro cards. On desktop cards it is blocked.

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.
