### ISSUE TITLE
Find a tutorial video about "How to find offsets for new termsrv.dll versions" on a new website instead of youtube

### ISSUE THREAD

**Issue by davidcao2000** [stascorp/rdpwrap#2420]
I can't access youtube in my country, anybody may help me to find a way to watch this video "How to find offsets for new termsrv.dll versions"? I will appreciate it very much.
youtube link: http://www.youtube.com/watch?v=FiD86tmRBtk

someone did it before,  see as: https://github.com/stascorp/rdpwrap/issues/1335 (https://we.tl/t-XimTZqTAUN)
but the link has expired and is not available any more

**Comment by sashaqwert** [comment]
> youtube link: http://www.youtube.com/watch?v=FiD86tmRBtk

https://disk.yandex.ru/i/U22TLNXTHc4uTw
