### ISSUE TITLE
Zip file is missing. RDPWrap-v1.6.2.zip

### ISSUE THREAD

**Issue by ameesami** [stascorp/rdpwrap#2422]
Can anyone re-upload the zip file.
 [RDPWrap-v1.6.2.zip]
(https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip)

URL is empty.

**Comment by sashaqwert** [comment]
> URL is empty.

No. I'm tested now. Closed as invalid.
