### ISSUE TITLE
cant uninstall rdp wrapper and im newer to pc i got no clue what to do.

### ISSUE THREAD

**Issue by Jdog424211** [stascorp/rdpwrap#2424]
It was working fine then my power went out then it all stopped working, I messing with somethings and now I cant uninstall and it and this shows up, HELP PLEASE.
![rdp](https://github.com/stascorp/rdpwrap/assets/151907074/39572efc-f655-421c-90b6-db71476d9bb6)

**Comment by sashaqwert** [comment]
> and now I cant uninstall

You need execute `uninstall.bat` as Administrator.
