### ISSUE TITLE
Desktop screen cannot be synchronized

### ISSUE THREAD

**Issue by Rooney0317** [stascorp/rdpwrap#2428]
The remote end has been confirmed to be able to connect normally, but when the two computers are connected, the screen is out of sync.

![image](https://github.com/stascorp/rdpwrap/assets/150777645/aa3fe132-ad40-4680-91a0-06b6202b5bf9)
![image](https://github.com/stascorp/rdpwrap/assets/150777645/3c189b11-a088-40c3-b566-de47a028a9d1)

**Comment by sashaqwert** [comment]
This is not an RDP Wrapper issue. Please, read about session shadow mode: https://woshub.com/rds-shadow-how-to-connect-to-a-user-session-in-windows-server-2012-r2/

If you need sync screen, please use Any-desk, Team-viewer, etc...
