### ISSUE TITLE
Not supported 10.0.19041.3636

### ISSUE THREAD

**Issue by Sighrp** [stascorp/rdpwrap#2429]
![image](https://github.com/stascorp/rdpwrap/assets/152167039/0de5333d-4582-4f10-af3d-1616b07ff1a5)
![10 0 19041 3636](https://github.com/stascorp/rdpwrap/assets/152167039/b40131f5-8779-4537-bd53-99c976bb1f65)

**Comment by Sighrp** [comment]
hi please Helf to resolve this.

**Comment by vgraba** [comment]
Hello, the same for me.  Would be great if you could provide a solution. Thanks.

**Comment by gongjiaxing123** [comment]
Hello, the same for me. Would be great if you could provide a solution. Thanks.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381
