### ISSUE TITLE
Windows 11 home requiring access to Remote Desktop Services?

### ISSUE THREAD

**Issue by watrworld** [stascorp/rdpwrap#2431]
This is a new one for me, everything from an RDPWrap perspective works great.

![RemoteRPC](https://github.com/stascorp/rdpwrap/assets/16058918/c778abe9-835b-4076-8f00-908a0d6e3d14)

I also have another user connected to Outlook, but cannot seem to see it or select it.

Anyone know how to solve that one on Windows 11 Home? Never had this issue on Windows 10 Home.

Thanks

**Comment by sashaqwert** [comment]
> Anyone know how to solve that one on Windows 11 Home?

On Windows Home editions RDP access available only for Administrators.

If you need non-admin access, you need to create the `Remote desktop users` group (see links in README.)
