### ISSUE TITLE
配置好了，但是还是远程不了。“与此计算机的连接数量是有限的，现在已经使用所有连接。请尝试稍后连接或与系统管理员联系。”

### ISSUE THREAD

**Issue by Guohairui6** [stascorp/rdpwrap#2434]
![image](https://github.com/stascorp/rdpwrap/assets/135523508/6d940492-bf48-44c6-9dd0-0278ea73ca2f)
“与此计算机的连接数量是有限的，现在已经使用所有连接。请尝试稍后连接或与系统管理员联系。”
![image](https://github.com/stascorp/rdpwrap/assets/135523508/873650e0-b2d5-42ae-875b-1e45ada720ea)

**Comment by Guohairui6** [comment]
截至今天上午，又出现了下图所示的错误
![image](https://github.com/stascorp/rdpwrap/assets/135523508/8ef69dde-9e95-474e-92ea-cfb5d8413ab8)

**Comment by sashaqwert** [comment]
One `termsrv.dll` version = ONE opened issue!

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2359

**Comment by wherefrom** [comment]
the same issue
