### ISSUE TITLE
10.0.19045.3693

### ISSUE THREAD

**Issue by NICOLEJINJIN** [stascorp/rdpwrap#2435]
![1](https://github.com/stascorp/rdpwrap/assets/152598185/3dbdd2b7-6bdb-423d-b2fe-3e5209db698d)
![2](https://github.com/stascorp/rdpwrap/assets/152598185/21f6f7cd-4f2a-4551-a7ad-a81887ae262c)

**Comment by sashaqwert** [comment]
ver = N/A. You need repair your OS...

Try upgrade to same version via original ISO. See also https://github.com/stascorp/rdpwrap/issues/1883
