### ISSUE TITLE
10.0.19041.3570依然无法连接

### ISSUE THREAD

**Issue by Guohairui6** [stascorp/rdpwrap#2436]
![image](https://github.com/stascorp/rdpwrap/assets/135523508/e7f7d98d-ee66-4ff9-ae94-5d832e15eb3f)

**Comment by sashaqwert** [comment]
Unknown language and no RDPConf attached --> CLOSED...

---------

Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by loyejaotdiqr47123** [comment]
> ![图像](https://private-user-images.githubusercontent.com/135523508/287677958-e7f7d98d-ee66-4ff9-ae94-5d832e15eb3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMDkwMDEsIm5iZiI6MTcxMjMwODcwMSwicGF0aCI6Ii8xMzU1MjM1MDgvMjg3Njc3OTU4LWU3ZjdkOThkLWVlNjYtNGZmOS1hZTk0LTVkODMyZTE1ZWIzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQwOTE4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzU1N2M1ZDA4MTAzNjQzZGU1NDI4NGNmYzE3MDcyZjdmM2EwZmU2ZGE2MWQ5OTIxZTdlMzY1MmI4NDNmZWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5b-_89AWSFf6k_TOJyaMxMcr4uEeKjYUwrlWOw1xioM)

[RDPWrap-v1.8.2.zip](https://github.com/stascorp/rdpwrap/files/14882818/RDPWrap-v1.8.2.zip)
尝试先运行1.6.2的uninstall.bat，然后再运行1.8.2的install.bat

**Comment by loyejaotdiqr47123** [comment]
> Unknown language and no RDPConf attached --> CLOSED...
> 
> Try:
> 
> 1. Download RDP Wrapper 1.6.2 and extract this to any directory.
> 2. Place  in the same directory.`rdpwrap.ini`
> 3. Open CMD as administrator
> 4. Execute this commands
> 
> ```
> cd C:\path\to\directory\
> rdpwinst -u -k
> rdpwinst -i
> ```
> 
> 5. Enjoy!
> 
> Original message: https://t.me/rdpwrap/49131

This language is Chinese
