### ISSUE TITLE
Can't use with Radmin VPN

### ISSUE THREAD

**Issue by dangkhoa1612** [stascorp/rdpwrap#2437]
It works perfect in LAN network (windows 11 single language)
But I can't remote control the PC via Radmin VPN like windows 11 pro.

Can you fix this problem?
Thank you very much.

**Comment by sashaqwert** [comment]
Currently this project is almost not supported by Stas'M.

> But I can't remote control the PC via Radmin VPN like windows 11 pro.

Now VPNs is offtopic here. Check that your OS allows incoming RDP connections through this VPN (Windows firewall, firewall included in antivirus ...)

**Comment by sashaqwert** [comment]
Faster replies at https://t.me/rdpwrap
