### ISSUE TITLE
Is https://github.com/sebaxakerhtc/rdpwrap safe to use?

### ISSUE THREAD

**Issue by funky123** [stascorp/rdpwrap#2438]
i cant post issues at https://github.com/sebaxakerhtc/rdpwrap and any AV Claims a Virus

it it save? who is useing it?

**Comment by sashaqwert** [comment]
> i cant post issues at https://github.com/sebaxakerhtc/rdpwrap

Use https://github.com/sebaxakerhtc/rdpwrap.ini/issues for MOD-ONLY issues.

> any AV Claims a Virus

See also https://github.com/stascorp/rdpwrap/issues/277

> it it save? who is useing it?

You can ask this in official Telegram chat (you can find link in repository README)
