### ISSUE TITLE
RDP access broken after uninstall

### ISSUE THREAD

**Issue by lord-emperor** [stascorp/rdpwrap#244]
RDP Wrapper Library v1.6.1
Windows 10 x64

Steps to reproduce:
Installed via install.bat
Used RDPWrapper (works) but ultimately decided it was unnecessary.
Uninstalled via unisntall.bat
Now unable to connect via RDP, as if the service isn't running.

**Comment by binarymaster** [comment]
This is by design. Do not use `uninstall.bat`, if you need to keep RDP settings, use `RDPWInst -u -k`.
