### ISSUE TITLE
ver. 10.0.19041.3636 [not supported]

### ISSUE THREAD

**Issue by Henzato** [stascorp/rdpwrap#2440]
having trouble unfortunately 

![image_2023-12-10_163652543](https://github.com/stascorp/rdpwrap/assets/153467238/530dd37d-6255-4123-90f5-abf2780ba132)

**Comment by Henzato** [comment]
using windows 10 pro btw

**Comment by DnsZhou** [comment]
Duplicated with https://github.com/stascorp/rdpwrap/issues/2381 , see https://github.com/stascorp/rdpwrap/issues/2381#issuecomment-1782856121 for the fix.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381
