### ISSUE TITLE
23H2 (22631.2861)

### ISSUE THREAD

**Issue by eladavron** [stascorp/rdpwrap#2445]
I've only seen 226**2**1.2861, not 226**3**1.2861

**Comment by eladavron** [comment]
Turns out it's the same thing, and despite having a different version number, the DLL is the same.
![image](https://github.com/stascorp/rdpwrap/assets/5508836/5bba5c98-3293-4f59-8763-accd7082405e)

**Comment by gamma-577** [comment]
> Turns out it's the same thing, and despite having a different version number, the DLL is the same. 

Can confirm works with 23H2, as the dll version is same. Thank you!

-Gamma
