### ISSUE TITLE
McAffee flags the installer as a virus

### ISSUE THREAD

**Issue by mattcbro** [stascorp/rdpwrap#2447]
At this date 12/13/2023,  the MacAfee anti virus software is flagging the installer as a virus.  Is this a problem?

**Comment by sashaqwert** [comment]
Known issue. See https://github.com/stascorp/rdpwrap/issues/277

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/277
