### ISSUE TITLE
Windows 10 10.0.19045.3803 support missing

### ISSUE THREAD

**Issue by machi67** [stascorp/rdpwrap#2448]
please update rdpwrap.ini

**Comment by XIronMan0220** [comment]
same problem, this is what I got
![image](https://github.com/stascorp/rdpwrap/assets/53851245/b2f637eb-0334-419b-9bed-1e0ff962477a)

**Comment by sashaqwert** [comment]
ver is N/A. Please, repair your OS.

See https://github.com/stascorp/rdpwrap/issues/1883

**Comment by simonmadsen** [comment]
@sashaqwert by closing it as not planned you mean i can never get it working?
it contradicts with your last comment though.
see my pic please
![image](https://github.com/stascorp/rdpwrap/assets/1309524/c536495e-939f-4338-85c7-410cb05ea967)

**Comment by sashaqwert** [comment]
> i can never get it working?

No. You can get it working. On-topic issue for your ternsrv.dll version is https://github.com/stascorp/rdpwrap/issues/2381

For a more guaranteed solution, it is better to write the project chat in Telegram: https://t.me/rdpwrap (the link to it is in the README on GitHub)

**Comment by simonmadsen** [comment]
ill try telegram, the post is not clear to me what exactly to do
________________________________
