### ISSUE TITLE
23h2 not supported

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#2449]
![Screenshot 2023-12-14 135527](https://github.com/stascorp/rdpwrap/assets/153830907/31b8cfc4-f19e-4f0b-a21c-3e9f904d5fb0)

**Comment by Plawasan** [comment]
https://github.com/stascorp/rdpwrap/issues/2443

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2443
