### ISSUE TITLE
how to enable tls ?

### ISSUE THREAD

**Issue by hetong12345** [stascorp/rdpwrap#2451]
I already have a ddns domain name and obtained the tls certificate for this domain name
Execute the commands according to other articles on the Internet, and an error message will be reported.
need help

Below are my attempts and errors
----
$thumbprint = "证书指纹" # 替换为您的证书指纹
$rdpListener = Get-CimInstance -ClassName Win32_TSGeneralSetting -Namespace root/CIMv2/TerminalServices
Set-CimInstance -InputObject $rdpListener -Property @{SSLCertificateSHA1Hash="$thumbprint"}

Get-CimInstance : 无效命名空间
所在位置 行:1 字符: 16
+ ... pListener = Get-CimInstance -ClassName Win32_TSGeneralSetting -Namesp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root/CIMv2/Term...SGeneralSetting:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x8004100e,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

**Comment by hetong12345** [comment]
windows version 10.0.22621.2861

**Comment by sashaqwert** [comment]
RDP Wrapper is a project that allows you to run the Windows built-in termsrv.dll library with different parameters, which allows you to bypass the limits on the number of simultaneous sessions set by the policy of your edition of Windows.

The purpose of RDP Wrapper is to unlock the capabilities of concurrent sessions and enable the RDP server in editions where this is not possible.

> I already have a ddns domain name and obtained the tls certificate for this domain name
Execute the commands according to other articles on the Internet, and an error message will be reported.
need help

The certificate problem you mentioned is a problem with the implementation of the RDP protocol in Windows itself and, therefore, this is offtopic here.

CLOSED...
