### ISSUE TITLE
openkeyreadonly error code 0

### ISSUE THREAD

**Issue by funky123** [stascorp/rdpwrap#2456]
i can't install or uninstall the rdp wrapper.

```
RDP Wrapper Library v1.7.4
Installer v2.6
Copyright (C) Stas'M Corp. 2018
Mod by sebaxakerhtc 2021

[-] OpenKeyReadOnly error (code 0).
```

![image](https://github.com/stascorp/rdpwrap/assets/12056510/5b7dc96b-1822-43b5-9cf3-a638003cb234)

The AV Protection May Removed something?

**Comment by funky123** [comment]
Update: Seems that the TerminService Service got deleted by AV - any idears how to revert and start over ?

**Comment by sashaqwert** [comment]
> Seems that the TerminService Service got deleted by AV

YES!!!

> any idears how to revert and start over ?

Solution in https://github.com/stascorp/rdpwrap/issues/1883
