### ISSUE TITLE
【Problem solve】when rdpwrapper.dll is missing, rdp termsrv service report unkonwn error

### ISSUE THREAD

**Issue by snail1126** [stascorp/rdpwrap#2457]
When rdpwrapper.dll is missing (usually killed by anti-virus), RDPWrap install or unintall will not be worked,
and rdp service will report unkonwn error.
Here is problem solving step
1. run regedit, recover \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters\ServiceDll to %SystemRoot%\System32\termsrv.dll
2. reinstall RDPWrap (close anti-virus recommended)
Problem solved.
This works with windows 11 22H

**Comment by sashaqwert** [comment]
https://github.com/stascorp/rdpwrap/issues/1883 --> Problem 3

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/1883

**Comment by jhairtelloar** [comment]
> When rdpwrapper.dll is missing (usually killed by anti-virus), RDPWrap install or unintall will not be worked, and rdp service will report unkonwn error. Here is problem solving step
> 
> 1. run regedit, recover \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters\ServiceDll to %SystemRoot%\System32\termsrv.dll
> 2. reinstall RDPWrap (close anti-virus recommended)
>    Problem solved.
>    This works with windows 11 22H

> It Works with Windows 10 22 H 08/08/24

**Comment by boraleclerc** [comment]
i dont get the 1. part what do i do
