### ISSUE TITLE
10.0.22631.2861

### ISSUE THREAD

**Issue by GitYeJiaWei** [stascorp/rdpwrap#2458]
10.0.22631.2861

**Comment by GitYeJiaWei** [comment]
Request support for this version

**Comment by sashaqwert** [comment]
> 10.0.22631.2861

This is not a `termsrv.dll` version. `termsrv.dll` version != Windows version!

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2443
