### ISSUE TITLE
Help - New Version

### ISSUE THREAD

**Issue by LeloBelo** [stascorp/rdpwrap#246]
Please help us, a new version of termsrv.dll has been updated: 10.0.14393.1198
RDPWRAP does not work ..

**Comment by binarymaster** [comment]
Support for `10.0.14393.1198` was already added in https://github.com/stascorp/rdpwrap/commit/890006de99625c194aa48dfd27c5c9a53bdb656e.

Run `update.bat`.

**Comment by quicken2k** [comment]
So, it will work with The Creators Update on Windows 10 Home??

**Comment by binarymaster** [comment]
No.
