### ISSUE TITLE
version 10.0.19041.3636 not supported (Win 10 Home)

### ISSUE THREAD

**Issue by cegruenberg** [stascorp/rdpwrap#2464]
version 10.0.19041.3636 Windows 10 Home fully patched ( Microsoft Windows [Version 10.0.19045.3930] )

![image](https://github.com/stascorp/rdpwrap/assets/73325665/d584d2b4-fc8f-4758-93ca-9d557e0b0f16)

DLL included -- [termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/13924126/termsrv.dll.zip)

Thank you.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381
