### ISSUE TITLE
Windows 11 service ver. N/A

### ISSUE THREAD

**Issue by Timmoc4645** [stascorp/rdpwrap#2467]
-- issue removed --

**Comment by Timmoc4645** [comment]
I tried many things, and I got this:
![image](https://github.com/stascorp/rdpwrap/assets/94282564/301328f1-481f-4e5d-b725-5fb257dcc52b)
it's still N/A, but Listening.
and connect successfully.

Those two things I think are the most important:
![image](https://github.com/stascorp/rdpwrap/assets/94282564/a91f628f-e389-4250-b398-cddb8afc046b)
And I read other issues and then replaced my termsrv.dll with one that was recently listed as "add build" by someone else's.

the two steps are tried at the same time, and then I reboot the computer, it works!
the service ver. is still N/A, but the connection is success.
But you are right, replace the termsrv.dll is not a good idea and it cause many little problems.
so I replace it to the backup, it still works. and that is what you can see at the top of the comment.
I don't know why the wrapper can work without geting the right version of the service.
![image](https://github.com/stascorp/rdpwrap/assets/94282564/d8779641-b661-4612-b758-8b7cca2f0308)
But this version is indeed supported.

**Comment by sashaqwert** [comment]
> But this version is indeed supported.

And N/A

You needed to upgrade Windows to same version via original ISO
