### ISSUE TITLE
Windows Server 2019 Ver 10.0.17763.292 not listening 

### ISSUE THREAD

**Issue by dijo12** [stascorp/rdpwrap#2471]
![wrapper](https://github.com/stascorp/rdpwrap/assets/89067086/b513dd42-da4b-45a3-8a04-17236662866f)
Getting this error but cant find any answers 

please help thanks

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/972

**Comment by sashaqwert** [comment]
Commit: https://github.com/sebaxakerhtc/rdpwrap.ini/commit/daecc6bc8da08ce20cd23917dd60ee43c22bbce6

https://github.com/sebaxakerhtc/rdpwrap.ini/blob/daecc6bc8da08ce20cd23917dd60ee43c22bbce6/rdpwrap.ini#L3674
https://github.com/sebaxakerhtc/rdpwrap.ini/blob/daecc6bc8da08ce20cd23917dd60ee43c22bbce6/rdpwrap.ini#L6121
