### ISSUE TITLE
Windows 11 Pro 22H2 build 22621.3007 - NOT SUPPORTED

### ISSUE THREAD

**Issue by jerryjmitchell** [stascorp/rdpwrap#2478]
Hi! I get this message when I open the RDPConf file.

![image](https://github.com/stascorp/rdpwrap/assets/10886643/4bed47c5-249c-479a-88ab-ae2b337219d6)

Can you please help me?

Thanks!

**Comment by sashaqwert** [comment]
You need repair your OS.

> Windows 11 Pro 22H2 build 22621.3007 - NOT SUPPORTED

and

> 10.0.17763.5328

This DLL is wrong!
