### ISSUE TITLE
10.0.17763.5206

### ISSUE THREAD

**Issue by herrComputerVision** [stascorp/rdpwrap#2480]
Requesting for this build. Thanks!

**Comment by sashaqwert** [comment]
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by herrComputerVision** [comment]
Hi! please find the win_ver, RDPconfig and termsrv,dll file!

Thanks!!
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14209227/termsrv.zip)
![win_ver](https://github.com/stascorp/rdpwrap/assets/79802181/4584ed0a-959e-42bf-b647-e92d6069b16e)
![rdp_config](https://github.com/stascorp/rdpwrap/assets/79802181/811cfe61-30a2-4261-a277-e9732740f7f5)

**Comment by sashaqwert** [comment]
Thanks! Solution in https://github.com/stascorp/rdpwrap/issues/2404

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2404
