### ISSUE TITLE
10.0.22621.2861

### ISSUE THREAD

**Issue by LovelyRua** [stascorp/rdpwrap#2487]
![image](https://github.com/stascorp/rdpwrap/assets/81335837/762915ca-631f-4d23-975f-476dfcadcec4)
Windows 11 Version 23H2 (OS Build 22631.3007) Enterprise Edition
after auto update

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14277487/termsrv.zip)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2443
