### ISSUE TITLE
RDPWrap not listening - Windows Home 10 Creators Update (10.0.15063.0)

### ISSUE THREAD

**Issue by swatts7605** [stascorp/rdpwrap#249]
Any updates on this? Windows 10 Home 64-bit Edition with termsrv.dll version 10.0.15063.0. Worked fine before Creators Update. I've downloaded the latest RDPWrapper binary (1.6.1) and the latest files from the GitHub repository. I'll gladly donate $$$ if the developer can fix this issue.

**Comment by binarymaster** [comment]
This issue is already open: #194.
