### ISSUE TITLE
rdp not doing anything

### ISSUE THREAD

**Issue by QOl1234** [stascorp/rdpwrap#2493]
Hey i just set up my rdp and when i start the program it just shows me a blurry screen where i cant do anything i have been looking araind on yt ect to find a solution i cant find it. 
![image](https://github.com/stascorp/rdpwrap/assets/160330921/88c69f5d-5956-4ee5-83b7-6053a8c0930a)
![image](https://github.com/stascorp/rdpwrap/assets/160330921/d7a60774-ab89-41fe-a069-1c68efce52b9)

**Comment by sashaqwert** [comment]
You need to [convert your Microsoft account to local account](https://www.digitalcitizen.life/switch-to-local-account-from-microsoft-windows-11/).
