### ISSUE TITLE
10.0.17763.10022 not supported

### ISSUE THREAD

**Issue by AltsecDEV** [stascorp/rdpwrap#2494]
![1](https://github.com/stascorp/rdpwrap/assets/15349560/cac9bbca-e397-48a5-9a06-84a8fbee5137)

Me need help, i don`t know assemblers code =(
DLL this build

Thanking you very much!!!

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14344955/termsrv.zip)

**Comment by sashaqwert** [comment]
Please, rename your issue to `10.0.17763.10021 not supported`

**Comment by sashaqwert** [comment]
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/a383142a9cc4d251d551bf4dcbb49af0ae194937

**Comment by sashaqwert** [comment]
Closed, because incorrect title (see my comment above).

Current title: 10.0.17763.10022 not supported<br>
Correct title: 10.0.17763.10021 not supported
