### ISSUE TITLE
10.0.19045.2006   [support level]

### ISSUE THREAD

**Issue by 763a** [stascorp/rdpwrap#2496]

**Comment by loyejaotdiqr47123** [comment]
Please upload termsrv.dll.

**Comment by sashaqwert** [comment]
> [support level]

This message means that RDPConf was unable to determine your version of termsrv.dll. You need to update Windows using the original ISO from Microsoft. If this update does not help, a clean reinstallation of Windows is necessary.

**Comment by sashaqwert** [comment]
> 10.0.19045.2006

This is your Windows version, need `termsrv.dll` version!!!
