### ISSUE TITLE
RDP Wrap -- Has Microsoft ruined it again?

### ISSUE THREAD

**Issue by PortlandPaw** [stascorp/rdpwrap#250]
With the latest Windows 10 update my RDP Wrap has failed.  Currently using 1.6.1, is there an update on the way, or what do I do to get it running again?  The error on RDPcheck is "Socket Connection Failed."  Please help!

**Comment by binarymaster** [comment]
Which is your termsrv version?

**Comment by combatreadiness** [comment]
yes, we all have same problem.

**Comment by TuxBel** [comment]
I have also the same problem since the update to release 15063.296, version 1703 of Windows 10 Home.
Listener doesn't listen anymore...
Impossible to connect...

**Comment by PortlandPaw** [comment]
termsrv.dll is 6.1.7601.18637 modified 11/11/2014

**Comment by binarymaster** [comment]
Build `6.1.7601.18637` was already added into INI file, provide diagnostics screenshot (run RDPConf).

**Comment by PortlandPaw** [comment]
![image](https://cloud.githubusercontent.com/assets/28850758/26330250/01b793d6-3f19-11e7-818a-d1e0f8adcde6.png)

**Comment by jaggeri** [comment]
First time install of RDP wrapper with Win 10 ver 1703.
I have same result as PortlandPaw above, RDPCheck with 127.0.0.2 fails.
I will roll back to previous version and see if that is part of the problem.

**Comment by jaggeri** [comment]
ok, I rolled back to Win 10 Home  ver  1607
Uninstalled and reinstalled RDPWrapper 1.6.1. RDP Wrapper Configuration now says 10.0.14393.0 and all is working again.

You know, I wouldn't be surprised if this forum is being watched by giggling MS programmers

**Comment by binarymaster** [comment]
@PortlandPaw your issue is the same as #194, so I close this as duplicate.
