### ISSUE TITLE
Windows 11 rdp version 10.0.22621.1778  down sessions issue..

### ISSUE THREAD

**Issue by fluxion1908** [stascorp/rdpwrap#2500]
rdp-tcp#22        usr16                    25  Active
 rdp-tcp#23        usr15                    26  Active
 rdp-tcp#25        usr12                    27  Active
                                                        28  Down
                                                        29  Down
                                                        30  Down

I see this Down sessions on cmd using command query session and i cannot enter to another user without logout a user 
also after 30 sessions i need to logout a user to login to others

**Comment by sashaqwert** [comment]
Check "Single session per user in RDPConf".

**Comment by fluxion1908** [comment]
yes i have check that 
![image](https://github.com/stascorp/rdpwrap/assets/107484023/d033b54b-9eb1-44c7-ad71-c68dfa6935cf)

**Comment by sashaqwert** [comment]
First user will be disconnected. Sexond and others will OK.

**Comment by fluxion1908** [comment]
im afraid the problem is windows 11, i will install windows 10..
