### ISSUE TITLE
10.0.19041.3636 not supported windows 10 pro 22H2

### ISSUE THREAD

**Issue by abubakarnawaz670** [stascorp/rdpwrap#2501]
![yttt](https://github.com/stascorp/rdpwrap/assets/161370559/2b800942-7134-499f-912b-2f21bc3228e1)
please give me solution

**Comment by siaunibit** [comment]
The same problem!

**Comment by qwertynull** [comment]
Up. I also have same problem.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381
