### ISSUE TITLE
222621.3235 not working windows 11 23h2

### ISSUE THREAD

**Issue by lucky1luc** [stascorp/rdpwrap#2506]
![image](https://github.com/stascorp/rdpwrap/assets/33922423/325c08e2-15af-4900-b3f2-6ca487fe2d19)

**Comment by lucky1luc** [comment]
see https://github.com/stascorp/rdpwrap/issues/2504#issue-2162486215

**Comment by WANGKUOWEI** [comment]
![20240301-10](https://github.com/stascorp/rdpwrap/assets/42328451/0c9e503d-defa-48d0-afa0-a75ecda12bd6)

**Comment by lucky1luc** [comment]
> ![20240301-10](https://private-user-images.githubusercontent.com/42328451/309205377-0c9e503d-defa-48d0-afa0-a75ecda12bd6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODYxMDEsIm5iZiI6MTcwOTI4NTgwMSwicGF0aCI6Ii80MjMyODQ1MS8zMDkyMDUzNzctMGM5ZTUwM2QtZGVmYS00OGQwLWFmYTAtYTc1ZWNkYTEyYmQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA5MzY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MjNiMDI3YTM4ZTJmODc5OTFjM2Y0NjU1ZjZkMWFhN2ZlNzY0YjQzN2RiNzMzNmVmN2I5MmEwZWJkNmE0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ai9LtlOkPVuuBoazXTbEpW-pj4___fFoH_fe9CtA5kM)

see https://github.com/stascorp/rdpwrap/issues/2504#issuecomment-1972832069

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2504

**Comment by Prabhu2392** [comment]
issue not resolved after following above steps
