### ISSUE TITLE
WIN11 10.0.22621.3235

### ISSUE THREAD

**Issue by JackLoko** [stascorp/rdpwrap#2508]
Tenho um Dell G15 i1100-A30P.
Comprei o windows 11 pro o arquivo esta tudo ok, porem fala que o numero de conexoes e limitada. Nao consigo resolver.
![Screenshot_12](https://github.com/stascorp/rdpwrap/assets/161896592/75188e82-b820-4a09-97c5-caca734d5760)

**Comment by sashaqwert** [comment]
You need add your RDP users to Administrators or "Remote desktop users" group.
