### ISSUE TITLE
10.0.22621.3155

### ISSUE THREAD

**Issue by Hunihoon** [stascorp/rdpwrap#2509]
Maybe it's because the OS build version is not right...
It still doesn't work.

![45tg45g54](https://github.com/stascorp/rdpwrap/assets/115488198/d148ad2e-dc2b-40d9-b0cb-429e76671a7e)
![56y5564](https://github.com/stascorp/rdpwrap/assets/115488198/e8eb6ecb-4093-4915-a6ef-0cb2ef5906f8)

**Comment by sashaqwert** [comment]
This is normal for Home edition. This works!

Try:

1. Open Remote desktop client (mstsc)
2. Try connect from other PC or same PC.

If you trying from same PC, use `127.0.0.2` as "remote" PC.

**Comment by sashaqwert** [comment]
Your version discussion in https://github.com/stascorp/rdpwrap/issues/2469

**Comment by Hunihoon** [comment]
Thanks for your reply
![t54t54](https://github.com/stascorp/rdpwrap/assets/115488198/cb992141-7a35-462c-a44f-e53ebfaed499)
![45y45](https://github.com/stascorp/rdpwrap/assets/115488198/a0d8ddd0-5d8c-4aa7-94cd-00ec8ad6753e)

But it's still not working.

**Comment by Hunihoon** [comment]
and my OS bulid 
![4r958y4546](https://github.com/stascorp/rdpwrap/assets/115488198/0c5e3aee-b926-45dd-b18b-4bda6f9dde10)

**Comment by sashaqwert** [comment]
Is 127.0.0.2 works?

Please, check your local IP:

1. Open CMD
2. Enter ipconfig
3. Try find `95.111.240.9` in output :)

**Comment by Hunihoon** [comment]
> 3\. 95.111.240.9

Too hard for a computer newbie, bro

I was actually trying to run a VPS, but my computer couldn't connect remotely,
so I used a friend's computer and it worked.

Now "127.0.0.2" looks like this.
And "95.111.240.9" is the IP of the VPS server I want to control remotely.
![56UY4679U](https://github.com/stascorp/rdpwrap/assets/115488198/5c8b2cdd-65c7-48d5-bed0-e2ede6548c77)

**Comment by sashaqwert** [comment]
> Now "127.0.0.2" looks like this.

Try solutions from https://woshub.com/rdp-black-screen-windows-remote-desktop/

> And "95.111.240.9" is the IP of the VPS server I want to control remotely.

If you need remote control of a VPS, and not your computer, then RDP Wrapper needs to be installed on the VPS, and not on the client’s computer.
