### ISSUE TITLE
Remote audio not working using rdpwrap

### ISSUE THREAD

**Issue by austgori** [stascorp/rdpwrap#251]
Everything works flawless when using the remote desktop feature with my Macbook Pro Except for When I am in the remote session (on my Mac) and the remote audio doesn't work. When I go to test the audio using a playback tone, it says failure to launch test audio. 

I am accessing my windows 10 home desktop using my Macbook Pro.

**Comment by binarymaster** [comment]
This is a duplicate of issue #74.
