### ISSUE TITLE
RDP NOT SUPORTED -N10.0.19041.3636

### ISSUE THREAD

**Issue by Kgmondal** [stascorp/rdpwrap#2510]
You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.
![Screenshot (3)](https://github.com/stascorp/rdpwrap/assets/162407306/679c4a76-efa1-4aea-962e-6f82a554629f)

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381
