### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sptinik** [stascorp/rdpwrap#2513]
everything looks good and all, when i try RDPCheck it works perfectly but when I try use windows 10 RDC it says your computer could not connect to another ![Screenshot_1](https://github.com/stascorp/rdpwrap/assets/77354065/a2c2053e-6284-4a10-8a94-640f53a064c5). anyone know how to fix this? as stated when opening RDPCheck i can log on to another user and use it there

**Comment by sashaqwert** [comment]
https://www.repairwin.com/fix-your-computer-could-not-connect-to-another-console-session-because-you-already-have-a-console-session-in-progress/
