### ISSUE TITLE
Limited to 7 Remote Desktops

### ISSUE THREAD

**Issue by Apatrux** [stascorp/rdpwrap#2514]
Hello! I always fail connecting to my 8th remote desktop. 

The rough translation is
"Remote Desktop Services has ended.
The Connection to the remote desktop was interrupted, probably due to network issues. Try connecting to the remote desktop again. Contact systemadmin or customer support if the issue persists."

I've looked around, and haven't seen this exact message. I might just be blind. I have a pretty good processor and 64GB or RAM.

![image](https://github.com/stascorp/rdpwrap/assets/162841832/03b9c00c-a725-4ca8-bed0-fc30cfca987b)

**Comment by Apatrux** [comment]
Forgot to mention that i have set my maximum connections through gpedit to 999999.

**Comment by loyejaotdiqr47123** [comment]
Try it this offsets
[10.0.19041.3636]
SingleUserPatch.x64=1
SingleUserOffset.x64=182FB
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1F315
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=92AF1
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=2866C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.3636-SLInit]
bServerSku.x64=125078
bRemoteConnAllowed.x64=12508C
bFUSEnabled.x64=125098
bAppServerAllowed.x64=125084
bMultimonAllowed.x64=125090
lMaxUserSessions.x64=12507C
ulMaxDebugSessions.x64=125094
bInitialized.x64=125074

**Comment by Apatrux** [comment]
This is something I add to the bottom of the .ini file correct? It did not seem to fix the issue

**Comment by loyejaotdiqr47123** [comment]
No.You'll need to remove the offset value about this version, and then add the

**Comment by Apatrux** [comment]
Alright, Ive done that but the problem still exists. I am using sebaxakerhtcs modded version. When connecting the the 8th RD, the 8th RD turns black, and after about a minute, it closes down. So I guess thats progress? Still only accessing 7 RDs

**Comment by Apatrux** [comment]
![image](https://github.com/stascorp/rdpwrap/assets/162841832/70134289-a33e-425f-8b45-b00ce245f0ff)
Update. The error still appears, but not every time anymore

**Comment by sashaqwert** [comment]
See https://github.com/stascorp/rdpwrap/issues/192

Try change RDP graphics settings:

* https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.TerminalServer::TS_SERVER_AVC_HW_ENCODE_PREFERRED
* https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.TerminalServer::TS_SERVER_WDDM_GRAPHICS_DRIVER

**Comment by sashaqwert** [comment]
You can also ask this in Telegram chat (see link in repository README)

**Comment by Apatrux** [comment]
Another question - could upgrading from windows home to windows pro have impact on how many RD connections I can have? Seeing as its maxed out at 7 now.

Another thing - not sure if this is normal, but my OS Build is not the same as the one RDPwrapper's terms is. 
![image](https://github.com/stascorp/rdpwrap/assets/162841832/1996e619-298c-4a60-9038-520a983c7405)
![image](https://github.com/stascorp/rdpwrap/assets/162841832/f6c20fff-2f1d-4b93-9c20-eb887f304774)
 Just looking for solutions to the max RDs, probably reaching a bit
