### ISSUE TITLE
Windows 11 10.0.22621.3374 not supported

### ISSUE THREAD

**Issue by ToniHogan** [stascorp/rdpwrap#2531]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14772593/termsrv.zip)
После обновления не поддерживается. Termsrv приложено.

**Comment by asdphantom** [comment]
![2024-03-27_14-53-26](https://github.com/stascorp/rdpwrap/assets/71166595/8e85e8e4-b0c2-4cd1-a7ec-643c33a32ea1)

**Comment by loyejaotdiqr47123** [comment]
Duplicate of #2528

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2528
