### ISSUE TITLE
after windows update on a version 10.0.19045.4239, listener state is not suported

### ISSUE THREAD

**Issue by cevanou** [stascorp/rdpwrap#2532]
hello, do you have any idea why not works after the windows 10 update 10.0.19045.4239, (KB5035941 (versiunea sistemului de operare 19045.4239))
  thank you

**Comment by affinityv** [comment]
It's the termsrv.dll version that counts, not the Windows version, see [this](https://github.com/stascorp/rdpwrap/issues/2529)
I have updated my [rdpwrap.ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) with sections for both x86 and x64
- termsrv.dll version 10.0.19041.4239 as reported by `RDPConf.exe`

**Comment by sashaqwert** [comment]
> * termsrv.dll version 10.0.19041.4239

--> Duplicate...

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2529
