### ISSUE TITLE
10.0.22631.3374 service state stopped

### ISSUE THREAD

**Issue by elonmusk1218** [stascorp/rdpwrap#2535]
i just added the 10.0.22631.3374 rdwrap.ini and listener state says [fully supported]
however when i start the remote desktop services, it just starts for 2-3 seconds and stops.
![Screenshot 2024-03-29 211733](https://github.com/stascorp/rdpwrap/assets/78806835/a6c005c7-e1ab-493b-acb2-a75454ad74a7)

**Comment by loyejaotdiqr47123** [comment]
Run RDPWInst.exe -r

**Comment by elonmusk1218** [comment]
still stops
![Screenshot 2024-03-29 213922](https://github.com/stascorp/rdpwrap/assets/78806835/b3c11b2e-4ce6-4b56-af18-73c1914112d4)

**Comment by loyejaotdiqr47123** [comment]
[RDPWrap-v1.8.2.zip](https://github.com/stascorp/rdpwrap/files/14808933/RDPWrap-v1.8.2.zip)
Try running uninstall.bat then running install.bat

**Comment by dn2182** [comment]
You guys are generating the .ini file wrong, you need to paste the offsets in order check what numbers goes after...
Here is my .ini file easily generated with https://github.com/llccd/RDPWrapOffsetFinder/releases
Just use this file and you should be good, but keep in mind the order of where the offset goes next time!
[rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/14811204/rdpwrap.ini.zip)

**Comment by sashaqwert** [comment]
Problems with each version of `termsrv.dll` are best discussed in the corresponding issue. This is discussed at https://github.com/stascorp/rdpwrap/issues/2528
