### ISSUE TITLE
10.0.26090.112

### ISSUE THREAD

**Issue by bowjacon** [stascorp/rdpwrap#2538]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14831894/termsrv.zip)

**Comment by bowjacon** [comment]
I tried the latest version of the ini file, but the following problem still occurred
![image](https://github.com/stascorp/rdpwrap/assets/99178447/69ca16ba-3d5d-4386-8f7f-3ffece0aeffb)

**Comment by loyejaotdiqr47123** [comment]
Duplicate of #2534

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2534
