### ISSUE TITLE
Unsupported Version

### ISSUE THREAD

**Issue by LuDdk** [stascorp/rdpwrap#254]
Hello. I'm on Windows 10 Pro. 16199.1000, already updated INI file, but i still receive not_supported and the rdp do not works.
What can i do?
Thanks in advance.

**Comment by binarymaster** [comment]
> What can i do?

Please share/upload your `termsrv.dll` file so I can add it to INI file.

**Comment by LuDdk** [comment]
Thank you very much.
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1034500/termsrv.zip)

**Comment by LuDdk** [comment]
You are awesome. Its working.
Thnks
