### ISSUE TITLE
Ayuda con version 10.0.19041.4239

### ISSUE THREAD

**Issue by MaozFlores** [stascorp/rdpwrap#2541]
Hola tengo instalada la version 1.6.2 del sistema, pero no me deja ingresar mas de un usuario

![sistema](https://github.com/stascorp/rdpwrap/assets/165872392/45938ef7-a004-48a3-9342-cfe794d43294)

pero solo me deja 1 solo usuario

help

**Comment by loyejaotdiqr47123** [comment]
Intente ejecutar RDPWInst -r

**Comment by MaozFlores** [comment]
Ya intente, me sale esto 

![rdpwinst](https://github.com/stascorp/rdpwrap/assets/165872392/ababaad2-f89f-4ef5-adff-f5ad1be87d25)

**Comment by loyejaotdiqr47123** [comment]
[RDPWrap-v1.8.2.zip](https://github.com/stascorp/rdpwrap/files/14852673/RDPWrap-v1.8.2.zip)
Intenta ejecutar uninstall.bat y luego ejecuta install.bat

**Comment by MaozFlores** [comment]
excelente Gracias ya quedo, super

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2529
