### ISSUE TITLE
Unable to shutdown or reboot. (Help Wanted)

### ISSUE THREAD

**Issue by Lakr233** [stascorp/rdpwrap#2542]
My computer sucks at black screen when reboot from start menu or using command `shutdown -r -t 0`. I will need to hold power button and do a force restart.

I'm using newest windows version x86 ent version and has already run the autoupdate from a fork #1160. The graphic card is 3090 with newest Game Ready Driver using HDMI output to a TV.

I have already searched around but didnt find anything helpful. Anyone had the same problem?

**Comment by sashaqwert** [comment]
We kindly ask you to first try to remove RDP Wrapper and check without it, and write only after this check.

Let me remind you that RDP Wrapper is a wrapper over `termsrv.dll`, which simply launches it with other parameters.

**Comment by Lakr233** [comment]
Yes I have tried many times. If I remove the termsrv.dll and do the reboot, every reboot works fine after a reboot.

I understand it sounds more like a BIOS problem or a driver issue or hardware probably, but I found this problem by updating Windows to an unsupported version to notice. The problem is confusing me for month and it suddenly went off this time. Once I update the dll using the autoupdate script, the problem went back.

It is also wired that the problem still exists even if I dont connect via rdp at all.

I'll get back to you if I found any solution. I'm currently trying serval scripts. Thanks for your time.

**Comment by Lakr233** [comment]
I am now 100% percent sure about this problem.

Following script at boot and shutdown effectively resolved my problem, unable to reboot, which was added using gpedit.msc.

Script for boot:

```boot.bat
@echo off

"%~dp0\RDPWInst.exe" -i
"%~dp0\autoupdate.bat"

echo.
```

Script for shutdown:

```shutdown.bat
@echo off
if not exist "%~dp0\RDPWInst.exe" goto :error

if not exist "%~dp0\shutdown.res" mkdir "%~dp0\shutdown.res"
copy /y "%~dp0\rdpwrap.ini" "%~dp0\shutdown.res\rdpwrap.ini"
copy /y "%~dp0\rdpwrap.dll" "%~dp0\shutdown.res\rdpwrap.dll"

"%~dp0\RDPWInst.exe" -u -k

copy /y "%~dp0\shutdown.res\rdpwrap.ini" "%~dp0\rdpwrap.ini"
copy /y "%~dp0\shutdown.res\rdpwrap.dll" "%~dp0\rdpwrap.dll"

echo.
goto :out

:error
echo [-] Installer executable not found.
echo Please extract all files from the downloaded package or check your anti-virus.

:out
```


I'm not sure if I can help with the error, but I'll do my best if any log or sys diag resource you need me to provide. If you don't mind, please reopen this issue.

**Comment by Lakr233** [comment]
User on Twitter is encountering similar problem: https://twitter.com/cryous/status/1776813534841856479

**Comment by sashaqwert** [comment]
Please, ask this in official Telegram chat https://t.me/rdpwrap

Link also available in repository README.
