### ISSUE TITLE
10.0.19041.4239 - Listener state "Listening" but not Suported

### ISSUE THREAD

**Issue by tic-campingjoan** [stascorp/rdpwrap#2545]
Hello i have a problem with rdpwraper, i installed the last version 1.6.2, the service is running, the Listener state says "Listening" but that indicate "not supported" i tried to reinstall the package with uninstall.bat and install.bat, but the problem persists.

![image](https://github.com/stascorp/rdpwrap/assets/86075289/0d781a85-b10e-4b07-b6fc-299865e4d0d9)

Anyone can help me to fix this problem? I don't know to determine what's the problem.

Thank you in advance!

**Comment by loyejaotdiqr47123** [comment]
Duplicate of #2529

**Comment by tic-campingjoan** [comment]
Thank you for your help, and sorry for duplicate the problem, it was fixed with the related resource.
Thank you!!
