### ISSUE TITLE
Full update but not supported

### ISSUE THREAD

**Issue by fjecp** [stascorp/rdpwrap#2547]
I get a "not supported" message from RDPConf, tried to update and message of "everything updated" message, then suggestion of sending the "termserv.dll" to developper for support, so, how can I send it? Zipped attached to this?

System is Windows 10 Pro 22H2 with lastest updates.

Thanks for your help

**Comment by loyejaotdiqr47123** [comment]
No termsrv.dll file uploaded, no screenshot of rdpconf uploaded

**Comment by loyejaotdiqr47123** [comment]
[RDPWrap-v1.8.2.zip](https://github.com/stascorp/rdpwrap/files/14918207/RDPWrap-v1.8.2.zip)
Rty running update.bat

**Comment by fjecp** [comment]
.dll files are not in the set of authorized files to upload, so, thus my question about how to do it, maybe zipped? I will do in some minutes both, .dll and screen capture of rdpconf.

 

De: bobo ***@***.*** 
Enviado el: martes, 9 de abril de 2024 13:58
Para: stascorp/rdpwrap
CC: fjecp; Author
Asunto: Re: [stascorp/rdpwrap] Full update but not supported (Issue #2547)

 

No termsrv.dll file uploaded, no screenshot of rdpconf uploaded

**Comment by fjecp** [comment]
In the website my RDPWrap 1.6.2 was the most recent versión, I will try with this one before to send the .dll of the screen capture.

 

Thanks

 

De: bobo ***@***.*** 
Enviado el: martes, 9 de abril de 2024 13:59
Para: stascorp/rdpwrap
CC: fjecp; Author
Asunto: Re: [stascorp/rdpwrap] Full update but not supported (Issue #2547)

 

RDPWrap-v1.8.2.zip <https://github.com/stascorp/rdpwrap/files/14918207/RDPWrap-v1.8.2.zip> 
Rty running update.bat

**Comment by fjecp** [comment]
Hi, I uninstalled 1.6.2 that I had and installed 1.8.2 you sent me... Now everything works as expected. Thanks so much for your help.

My question.. Why 1.8.2 is not found in the releases page? (1.6.2 is there as the latest)

Regards.

Javier

**Comment by loyejaotdiqr47123** [comment]
> Hi, I uninstalled 1.6.2 that I had and installed 1.8.2 you sent me... Now everything works as expected. Thanks so much for your help.
> 
> My question.. Why 1.8.2 is not found in the releases page? (1.6.2 is there as the latest)
> 
> Regards.
> 
> Javier

This is not the official version.
[https://github.com/loyejaotdiqr47123/rdpwrap/releases](https://github.com/loyejaotdiqr47123/rdpwrap/releases)

**Comment by sashaqwert** [comment]
> No termsrv.dll file uploaded

**Comment by fjecp** [comment]
I didn't upload the termsrv.dll first time because .dll was not a file allowed to upload and before I could try as zipped, I tested the 1.8.2 update and this solved the problem, so, this issue can be closed as solved.

Thanks so much

**Comment by sashaqwert** [comment]
@fjecp 

> I didn't upload the termsrv.dll

You can pack this to ZIP archive.

**Comment by fjecp** [comment]
But, my question, is it really needed once the problem has been solved with 1.8.2? If it is, I will upload it, of course.

**Comment by sashaqwert** [comment]
If question solved, then not needed.

**Comment by TungAngbro** [comment]
> [RDPWrap-v1.8.2.zip](https://github.com/stascorp/rdpwrap/files/14918207/RDPWrap-v1.8.2.zip) Try running update.bat

how did u find there link?

**Comment by sashaqwert** [comment]
@TungAngbro 

> > [RDPWrap-v1.8.2.zip](https://github.com/stascorp/rdpwrap/files/14918207/RDPWrap-v1.8.2.zip) Try running update.bat
> 
> how did u find there link?

**Latest official version is 1.6.2 !!!**

The 1.**8**.2 dos NOT exists officially.
