### ISSUE TITLE
Issues with automatic login

### ISSUE THREAD

**Issue by BaseofGrace** [stascorp/rdpwrap#255]
Having a few problems since the latest update - the remote desktop connection is not automatically logging in it takes us to the windows login screen and we have to reenter the password - this is on windows 10 professional.

Thanks

**Comment by binarymaster** [comment]
Please specify what exactly you're meaning with automatic login:
- [Sysinternals Autologon for Windows](https://technet.microsoft.com/en-us/sysinternals/autologon.aspx)
- Automatic relogin on session interruption / reconnection

**Comment by BaseofGrace** [comment]
Hi, this is with remote desktop connection using RDP wrapper.  I have explained it I think above.  We used to have the credentials saved on the local computer and then it would log you into the remote connection automatically.
Since the update we have to log into the connection and then log into the remote computer again?

**Comment by binarymaster** [comment]
Try setting your security mode to "Network Level Authentication".

**Comment by BaseofGrace** [comment]
Yes!  Thats worked.  Thanks so much
