### ISSUE TITLE
10.0.22621.3447

### ISSUE THREAD

**Issue by kkruselj** [stascorp/rdpwrap#2552]
Please help with 10.0.22621.3447.
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14928398/termsrv.zip)
Thx, Kristijan

**Comment by hetong12345** [comment]
same version ,please

**Comment by kkruselj** [comment]
[10.0.22621.3447]
SingleUserPatch.x64=1
SingleUserOffset.x64=C3F3
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C2E5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9D661
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=29ED0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.3447-SLInit]
bServerSku.x64=12BF50
bRemoteConnAllowed.x64=12BF64
bFUSEnabled.x64=12BF74
bAppServerAllowed.x64=12BF5C
bMultimonAllowed.x64=12BF68
lMaxUserSessions.x64=12BF54
ulMaxDebugSessions.x64=12BF70
bInitialized.x64=12BF4C

**Comment by gamma-577** [comment]
Working well. Thank you! :-)

-Gamma

**Comment by DF87SE** [comment]
> [10.0.22621.3447] SingleUserPatch.x64 = 1 SingleUserOffset.x64 = C3F3 SingleUserCode.x64 = Zero DefPolicyPatch.x64 = 1 DefPolicyOffset.x64 = 1C2E5 DefPolicyCode.x64 = CDefPolicy_Query_eax_rcx LocalOnlyPatch.x64 = 1 LocalOnlyOffset.x 64=9D661 LocalOnlyCode.x64=jmpshort SLInitHook.x64=1 SLInitOffset.x64=29ED0 SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.22621.3447-SLInit] bServerSku.x64=12BF50 bRemoteConnAllowed.x64=12BF64 bFUSEnabled.x64=12BF74 bAppServerAllowed.x64=12BF5C bMultimonAllowed.x64=12BF68 lMaxUserSessions.x64=12B F54 ulMaxDebugSessions.x64 =12BF70 bInitialized.x64=12BF4C

NÃO FUNCIONA

**Comment by DF87SE** [comment]
não permiti multiplos usuarios simultaneamente

**Comment by nevusZ** [comment]
hy, can anyone provide a full rdpwrap.ini file please?
or tell me where to put these 2 sections in the  ini?

**Comment by kkruselj** [comment]
Find and it works https://github.com/stascorp/rdpwrap/issues/2549

[10.0.22621.3447]
SingleUserPatch.x64=1
SingleUserOffset.x64=C3F3
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C2E5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9D661
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=29ED0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.3447-SLInit]
bServerSku.x64=12BF50
bRemoteConnAllowed.x64=12BF64
bFUSEnabled.x64=12BF74
bAppServerAllowed.x64=12BF5C
bMultimonAllowed.x64=12BF68
lMaxUserSessions.x64=12BF54
ulMaxDebugSessions.x64=12BF70
bInitialized.x64=12BF4C[
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/14932236/rdpwrap.zip)
](url)

**Comment by ccdiego5** [comment]
isnot working

**Comment by DF87SE** [comment]
> Encontre e funciona #2549
> 
> [10.0.22621.3447] SingleUserPatch.x64=1 SingleUserOffset.x64=C3F3 SingleUserCode.x64=Zero DefPolicyPatch.x64=1 DefPolicyOffset.x64=1C2E5 DefPolicyCode.x64=CDefPolicy_Query_eax_rcx LocalOnlyPatch.x64=1 LocalOnlyOffset. x64=9D661 LocalOnlyCode.x64=jmpshort SLInitHook.x64=1 SLInitOffset.x64=29ED0 SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.22621.3447-SLInit] bServerSku.x64=12BF50 bRemoteConnAllowed.x64=12BF64 bFUSEnabled.x64=12BF74 bAppServerAllowed.x64=12BF5C bMultimonAllowed.x64=12BF68 lMaxUserSessions.x64 =12 BF54 ulMaxDebugSessions.x64 =12BF70 bInitialized.x64=12BF4C[ [rdpwrap. zip](https://github.com/stascorp/rdpwrap/files/14932236/rdpwrap.zip) ](url)

My RDPWRAP is supported and updated for sure, but it only allows one connection per user, that is, for a user to access they have to log in! Do you have a solution for this too?
