### ISSUE TITLE
10.0.22621.3447 not supported

### ISSUE THREAD

**Issue by polpo84** [stascorp/rdpwrap#2553]
can someone help me?
thanks

**Comment by lucky1luc** [comment]
see https://github.com/stascorp/rdpwrap/issues/2552 and https://github.com/stascorp/rdpwrap/issues/2549

**Comment by loyejaotdiqr47123** [comment]
Duplicate of #2549

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2549
