### ISSUE TITLE
Service state : Running, Listener state : listening but still not supported

### ISSUE THREAD

**Issue by dotari13** [stascorp/rdpwrap#2558]
![Capture1](https://github.com/stascorp/rdpwrap/assets/166683148/d647117b-31ff-4d6e-8b6c-e7e3be25d1a0)

I updated new version of wrapper and tried again but still not supported.

What should i do for support

**Comment by warning0810** [comment]
This worked for me:
[autoupdate_v1.2.zip](https://github.com/stascorp/rdpwrap/files/14942739/autoupdate_v1.2.zip)
Place in rdpwrap folder and open as administrator,after finish restart the pc

**Comment by dotari13** [comment]
Thank you so much :))

**Comment by loyejaotdiqr47123** [comment]
Duplicate of #2529

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2529

**Comment by draj92** [comment]
come out error not supported
