### ISSUE TITLE
Update rdpwrap

### ISSUE THREAD

**Issue by KrabikKostya** [stascorp/rdpwrap#2559]
Hi, can someone help me, which parameters should be changed in rdpwrap.ini so that it starts working on the new version of Windows 11 ?

**Comment by Lupino1** [comment]
Hello,
scroll in this article ed search the file "rdpwrap.zip" and finally restart the rdp services.

see https://github.com/stascorp/rdpwrap/issues/2552 and https://github.com/stascorp/rdpwrap/issues/2549

**Comment by dawang021** [comment]
![image](https://github.com/stascorp/rdpwrap/assets/42695523/d588542d-a17d-48dd-bb2c-156f2ef6a81c)
Mine is looking like this, anyone can help me?

**Comment by dawang021** [comment]
My file is 
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14945101/termsrv.zip)

**Comment by sashaqwert** [comment]
In order to answer this question, you first need to determine your version of `termsrv.dll`. It can be found in RDPConf (it does not require installation of RDP Wrapper).
