### ISSUE TITLE
Win11 22h2 not supported

### ISSUE THREAD

**Issue by Penguk** [stascorp/rdpwrap#2560]
Hello, 

probabbly duplicated but if you could help me with the correct ini file I should use I'd appreciate the help.
![Screenshot_1](https://github.com/stascorp/rdpwrap/assets/65315964/76f197a2-eaaa-47b8-beae-0c36e7ff681a)
[RDP Wrapper.zip](https://github.com/stascorp/rdpwrap/files/14948317/RDP.Wrapper.zip)

**Comment by Penguk** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14948404/termsrv.zip)
Forgot termsrv

**Comment by robyDima21** [comment]
Come si può fare per risolvere questo problma?

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2549
