### ISSUE TITLE
WINDOWS 11 PRO 10.0.22631 BUILD 22631 NOT SUPPORTED

### ISSUE THREAD

**Issue by Preetam2114** [stascorp/rdpwrap#2562]
RDPConf is not showing the version and support level
![image](https://github.com/stascorp/rdpwrap/assets/30361120/500ef149-c05b-4256-9a88-73452346730c)

**Comment by Samuele-Wired** [comment]
![image](https://github.com/stascorp/rdpwrap/assets/106587255/a30b8090-7932-4817-9f6e-e023c80a592d)
I have some problem

**Comment by sashaqwert** [comment]
You need to upgrade Windows to same version via official ISO.

**Comment by Preetam2114** [comment]
Well I am not getting any version details on RDPConf, It's also not displaying support info

**Comment by sashaqwert** [comment]
See `winver`

https://www.microsoft.com/en-us/software-download/windows11
