### ISSUE TITLE
fSingleSessionPerUser not work

### ISSUE THREAD

**Issue by mikeleblank** [stascorp/rdpwrap#2563]
fSingleSessionPerUser is 1 not working last update.
Windows 10 22H2 19045.4291

**Comment by sashaqwert** [comment]
What is your `termsrv.dll` version?

**Comment by mikeleblank** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14962755/termsrv.zip)
10.0.19041.4239

**Comment by loyejaotdiqr47123** [comment]
Duplicate of #2529

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2529

**Comment by sashaqwert** [comment]
Please, ask this in correct thread (see link above)

**Comment by sashaqwert** [comment]
https://t.me/rdpwrap/68769
