### ISSUE TITLE
Windows 11 Pro 10.0.22621.3447 Stopped, Not listening

### ISSUE THREAD

**Issue by manuel231509** [stascorp/rdpwrap#2565]
![Captura de pantalla 2024-04-12 191903_rdpw](https://github.com/stascorp/rdpwrap/assets/75493236/4a4df1a0-6d7f-42b8-9c6f-8324d0c68db0)

![image](https://github.com/stascorp/rdpwrap/assets/75493236/64b7a43a-95ac-479e-8a48-30d93a39a4e0)

**Comment by sashaqwert** [comment]
Last line in `rdpwrap.ini` must be blank!

**Comment by sashaqwert** [comment]
One `termsrv.dll` version = ONE opened issue for ONE architecture.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2549
