### ISSUE TITLE
Find and it works https://github.com/stascorp/rdpwrap/issues/2549

### ISSUE THREAD

**Issue by erasmocanodiaz** [stascorp/rdpwrap#2567]
Find and it works https://github.com/stascorp/rdpwrap/issues/2549

[10.0.22621.3447]
funciona 
muchas gracias 
por su tiempo...

**Comment by sashaqwert** [comment]
Your issue is spam-like, because not contains new information.

**Comment by sashaqwert** [comment]
https://github.com/stascorp/rdpwrap/issues/2549
