### ISSUE TITLE
10.0.22621.3447 not supported & not listening

### ISSUE THREAD

**Issue by JasonYadi** [stascorp/rdpwrap#2568]
![bacc9216-a704-45dc-973a-0c003dce78dd](https://github.com/stascorp/rdpwrap/assets/24763020/8d697b9a-e72d-4be7-baa4-a504ecc57b59)

尝试了 https://github.com/stascorp/rdpwrap/issues/2549 的方法， not supported 没有了，但是 not listening 还是没变。使用的是window 11，上周六更新了 window 自动更新后就连不上去了。

**Comment by JasonYadi** [comment]
rdpwrap.ini 最后一行必须是空行，修改后就可以了。

**Comment by JasonYadi** [comment]
[10.0.22621.3447]
SingleUserPatch.x64=1
SingleUserOffset.x64=C3F3
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C2E5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9D661
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=29ED0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.3447-SLInit]
bServerSku.x64=12BF50
bRemoteConnAllowed.x64=12BF64
bFUSEnabled.x64=12BF74
bAppServerAllowed.x64=12BF5C
bMultimonAllowed.x64=12BF68
lMaxUserSessions.x64=12BF54
ulMaxDebugSessions.x64=12BF70
bInitialized.x64=12BF4C

**Comment by learnselfs** [comment]
> [10.0.22621.3447] SingleUserPatch.x64=1 SingleUserOffset.x64=C3F3 SingleUserCode.x64=Zero DefPolicyPatch.x64=1 DefPolicyOffset.x64=1C2E5 DefPolicyCode.x64=CDefPolicy_Query_eax_rcx LocalOnlyPatch.x64=1 LocalOnlyOffset.x64=9D661 LocalOnlyCode.x64=jmpshort SLInitHook.x64=1 SLInitOffset.x64=29ED0 SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.22621.3447-SLInit] bServerSku.x64=12BF50 bRemoteConnAllowed.x64=12BF64 bFUSEnabled.x64=12BF74 bAppServerAllowed.x64=12BF5C bMultimonAllowed.x64=12BF68 lMaxUserSessions.x64=12BF54 ulMaxDebugSessions.x64=12BF70 bInitialized.x64=12BF4C

🙏
