### ISSUE TITLE
RDP wrapper stopped working after windows update (Windows 11)

### ISSUE THREAD

**Issue by casanjeev** [stascorp/rdpwrap#2571]
Sir, RDP Wrapper stopped working after following windows update

1. 2024-04 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (KB5036893)
2. 2024-04 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 23H2 for x64 (KB5036620)

tried uninstalling RDP wrapper, install again and autoupdate, but no success and listner state showing as not suported and not allowing multiple connections and allowing only single connection.

**Comment by EliezerBee** [comment]
Did you try this?
https://github.com/stascorp/rdpwrap/issues/2549#issuecomment-2046435532

**Comment by sashaqwert** [comment]
Your issue is not contains `termsrv.dll` version.
