### ISSUE TITLE
Not RDP connection attempts but: "The referenced account is currently locked out and may not be logged on to"

### ISSUE THREAD

**Issue by EliezerBee** [stascorp/rdpwrap#2572]
I have all incoming RDP connections to my desktop computer from outside of my network blocked. On that computer, I have RDP Wrap configured and working which I use to connect from other computers within my network.

Sporadically, I'll be home alone - meaning there's no one else who could be even _attempting_ to connect via RDP - and I'll get this:

![sil_top-650x300 1](https://github.com/stascorp/rdpwrap/assets/5578694/00b38296-b9cb-4218-b85d-06a0de2241ba)

How can this be?

**Comment by sashaqwert** [comment]
This is not an RDP Wrapper issue. You are having problems with the failed login counters.

**Comment by EliezerBee** [comment]
> This is not an RDP Wrapper issue. You are having problems with the failed login counters.

Is there a way to get details (like from a log) on the failed login attempts?

**Comment by EliezerBee** [comment]
Per [Reddit](https://www.reddit.com/r/sysadmin/comments/lz1c7y/comment/gq0i4t3/), it should be in the Event Log under Event ID 4740.
