### ISSUE TITLE
10.0.1.19041.4239 Not supported

### ISSUE THREAD

**Issue by 0xwashed** [stascorp/rdpwrap#2577]
![image](https://github.com/stascorp/rdpwrap/assets/167272328/6adad960-708f-423e-946f-607495a52d3f)
![image](https://github.com/stascorp/rdpwrap/assets/167272328/c82b02bf-86df-4a16-8852-4205d550e3d9)

**Comment by HitEmUp** [comment]
same

**Comment by ua4frr** [comment]
> ![image](https://private-user-images.githubusercontent.com/167272328/323056361-6adad960-708f-423e-946f-607495a52d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDU2NDYsIm5iZiI6MTcxMzUwNTM0NiwicGF0aCI6Ii8xNjcyNzIzMjgvMzIzMDU2MzYxLTZhZGFkOTYwLTcwOGYtNDIzZS05NDZmLTYwNzQ5NWE1MmQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwNTQyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWIzZGY5ZWQwYjhmZGVmZWFmNzVkNTYwYTVmNGUzMmViMGEzN2U3OWY5ZmRkOTYzZTYwNDgwYzBiMzgyNWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-OH8MKDU1ae6qtIzz1R7KcCkPEaJY23EGcLH6hA_7zI) ![image](https://private-user-images.githubusercontent.com/167272328/323056448-c82b02bf-86df-4a16-8852-4205d550e3d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDU2NDYsIm5iZiI6MTcxMzUwNTM0NiwicGF0aCI6Ii8xNjcyNzIzMjgvMzIzMDU2NDQ4LWM4MmIwMmJmLTg2ZGYtNGExNi04ODUyLTQyMDVkNTUwZTNkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwNTQyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTAwODUzYmZlZmU0NWMyYTE0MjYzYjBlMmUxNzQwOTRhZmE1ZDU1ZmFiOWY0MDZhZmIxNjU3YzAxZDJmY2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yYKa1O4CMHm8UAfbiSOINp_prCxNrvS4Nq8tQGBIH1g)


**Hello, where did you find version 1.7.4.0? I didn't see this in the official utility repository**

**Comment by ua4frr** [comment]
> Duplicate of #2529

This method never worked for me((
The version in the repository is 1.6.2, and in fact when running the configuration utility it is 1.5.0

**Comment by ua4frr** [comment]
Not support 
Very sad
P.S. I tried all the ways, but I didn't get any results.

**Comment by DF87SE** [comment]
> ![imagem](https://private-user-images.githubusercontent.com/167272328/323056361-6adad960-708f-423e-946f-607495a52d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjMzOTAsIm5iZiI6MTcxMzk2MzA5MCwicGF0aCI6Ii8xNjcyNzIzMjgvMzIzMDU2MzYxLTZhZGFkOTYwLTcwOGYtNDIzZS05NDZmLTYwNzQ5NWE1MmQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxMjUxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjVmNTUzMDAzMjIyNmQyOTk4ZTVjNjk4ZjUwNjE0YzBlNWVkMzFjNTU3YzliNmI5ZWIxOTQ2Yzc1MzBjYjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WJRdhiMvdBuChnWA42k3k3ET5buvinjdeG2Wph-Hlj8) ![imagem](https://private-user-images.githubusercontent.com/167272328/323056448-c82b02bf-86df-4a16-8852-4205d550e3d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjMzOTAsIm5iZiI6MTcxMzk2MzA5MCwicGF0aCI6Ii8xNjcyNzIzMjgvMzIzMDU2NDQ4LWM4MmIwMmJmLTg2ZGYtNGExNi04ODUyLTQyMDVkNTUwZTNkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxMjUxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjUwZGExZDkwMGIzMjcxNWYwYTVmMzkwZjgxY2Y0Yzk3ZDRkMzQwZDQ1MGI5ZjAzYzU1NDc1N2QxZjk4YTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zp7Ibccigpny934t5dy9AYYxj4VCeg60CkBuLJobI_g)

O MEU APARECE SUPORTADO, MAS NÃOPERMITI MULTIPLOS USUARIOS, UM DERRUBA O OUTRO, ALGUÉM PODE ME AJUDAR

**Comment by DF87SE** [comment]
> ![imagem](https://private-user-images.githubusercontent.com/167272328/323056361-6adad960-708f-423e-946f-607495a52d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODI3MDUsIm5iZiI6MTcxMzk4MjQwNSwicGF0aCI6Ii8xNjcyNzIzMjgvMzIzMDU2MzYxLTZhZGFkOTYwLTcwOGYtNDIzZS05NDZmLTYwNzQ5NWE1MmQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxODEzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGQwNzI1NTQ1YTRlY2QxMTc5OGNjZjM0MmU5NGQ0OTg4ZTZmZjNkNDAxZDY1YzEwYjYzMTkxYTI2ZDBiYjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sSh625_BNxoL7YJIeXieHLubiC7Zgrioom-gpC2rFzU) ![imagem](https://private-user-images.githubusercontent.com/167272328/323056448-c82b02bf-86df-4a16-8852-4205d550e3d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODI3MDUsIm5iZiI6MTcxMzk4MjQwNSwicGF0aCI6Ii8xNjcyNzIzMjgvMzIzMDU2NDQ4LWM4MmIwMmJmLTg2ZGYtNGExNi04ODUyLTQyMDVkNTUwZTNkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxODEzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OGE3Mzg1YmQwYTg1OGY0MGM5NWEzYWFjNjVlZTEwMzg2ZTkyMzg5ZDkxYTM1Y2MyNjZmYWQxOTcxMzEzNTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wasGTdSG2a7uZvoq_ypBPPbQbvzN7gjfK2wmUPKjUq8)

My RDPWRAP is supported and updated for sure, but it only allows one connection per user, that is, for a user to access they have to log in! Do you have a solution for this too?
