### ISSUE TITLE
10.0.22621.3447 Not listening not supported

### ISSUE THREAD

**Issue by quryq** [stascorp/rdpwrap#2578]
### what I had done?
1.  Run install.bat  as admin
![image](https://github.com/stascorp/rdpwrap/assets/59192971/297341ad-fcb1-4312-b512-905543a3e4fd)

2. Add the content to rdpwrap.ini  and save it
![image](https://github.com/stascorp/rdpwrap/assets/59192971/4bd157ac-e2fe-4f95-862c-7a993e6f69f8)

3. run RDPConf.exe 
![image](https://github.com/stascorp/rdpwrap/assets/59192971/c7f0f124-63ad-4b05-b405-a2a834d4e224)

### others info

![image](https://github.com/stascorp/rdpwrap/assets/59192971/0fde232c-63a1-468c-b8c7-2c5404360ff0)

[rdpwrap ini file.zip](https://github.com/stascorp/rdpwrap/files/15008552/rdpwrap.ini.file.zip)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/15008563/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment]
[RDPWrap-1.8.3.zip](https://github.com/stascorp/rdpwrap/files/15010893/RDPWrap-1.8.3.zip)
Try this

**Comment by quryq** [comment]
> [RDPWrap-1.8.3.zip](https://github.com/stascorp/rdpwrap/files/15010893/RDPWrap-1.8.3.zip) Try this

thanks for replying...   I run the install.bat as admin, then get this error
![image](https://github.com/stascorp/rdpwrap/assets/59192971/9185e944-da72-4f14-8a53-10475e88da97)

**Comment by loyejaotdiqr47123** [comment]
> > [RDPWrap-1.8.3.zip](https://github.com/stascorp/rdpwrap/files/15010893/RDPWrap-1.8.3.zip) Try this
> 
> thanks for replying... I run the install.bat as admin, then get this error ![image](https://private-user-images.githubusercontent.com/59192971/323218157-9185e944-da72-4f14-8a53-10475e88da97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTg1NTksIm5iZiI6MTcxMzM1ODI1OSwicGF0aCI6Ii81OTE5Mjk3MS8zMjMyMTgxNTctOTE4NWU5NDQtZGE3Mi00ZjE0LThhNTMtMTA0NzVlODhkYTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyNTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMDExNWQ0YmUxZmQ5M2M0NWUwYmUxOTQ2ODU0MTAwN2QwMzI1N2EyMmIzYjQwMmQ2Yzg2ZmQyYjU1OWUxMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G-7UxNBkVnmqnr4jcAIGxdGsvsQ2lMaSgIwEDf3I65o)

得完整重新安装

**Comment by loyejaotdiqr47123** [comment]
> ### what I had done?
> 1. Run install.bat  as admin
>    ![image](https://private-user-images.githubusercontent.com/59192971/323148684-297341ad-fcb1-4312-b512-905543a3e4fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTg5MjMsIm5iZiI6MTcxMzM1ODYyMywicGF0aCI6Ii81OTE5Mjk3MS8zMjMxNDg2ODQtMjk3MzQxYWQtZmNiMS00MzEyLWI1MTItOTA1NTQzYTNlNGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyNTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNTdkMzYwMjNjYTVjZGZkOWQ3ZjJlOTljNzYzOGRjNmY5ZTJhYThmNGU0YWE5ZTFjMGZjNDc5MTViY2JlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BYMLmdk4IbFpqsKr0LAy8f6mTxQA4WRnvtMfPBiHYFY)
> 2. Add the content to rdpwrap.ini  and save it
>    ![image](https://private-user-images.githubusercontent.com/59192971/323149596-4bd157ac-e2fe-4f95-862c-7a993e6f69f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTg5MjMsIm5iZiI6MTcxMzM1ODYyMywicGF0aCI6Ii81OTE5Mjk3MS8zMjMxNDk1OTYtNGJkMTU3YWMtZTJmZS00Zjk1LTg2MmMtN2E5OTNlNmY2OWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyNTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZWU2YzBkMWY5ZGJhMDgwOWI3MjQyNDJlNGFkYzIzNTc2NWIzNjhmMTE3YmY4YWE1MzE0ZjJmODg4NDQyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b8yHad67HDlUn3eqIS3Zk0QM1c-fsGbOLssWQlAls7I)
> 3. run RDPConf.exe
>    ![image](https://private-user-images.githubusercontent.com/59192971/323149973-c7f0f124-63ad-4b05-b405-a2a834d4e224.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTg5MjMsIm5iZiI6MTcxMzM1ODYyMywicGF0aCI6Ii81OTE5Mjk3MS8zMjMxNDk5NzMtYzdmMGYxMjQtNjNhZC00YjA1LWI0MDUtYTJhODM0ZDRlMjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyNTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiOTJkNWExNDg2YzM1YTAzODU5OGNjYjVlNDAyOGQ4OWEzMjU2YThlOGVjZThiMzEzZmIyMWQ1YjcyZWQ2ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ZlFuUDed2y0zBbDb-URM8p2Gk21Qjx-dS27-TK0tS0)
> 
> ### others info
> ![image](https://private-user-images.githubusercontent.com/59192971/323150544-0fde232c-63a1-468c-b8c7-2c5404360ff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTg5MjMsIm5iZiI6MTcxMzM1ODYyMywicGF0aCI6Ii81OTE5Mjk3MS8zMjMxNTA1NDQtMGZkZTIzMmMtNjNhMS00NjhjLWI4YzctMmM1NDA0MzYwZmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyNTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmODhjYmNmNjc3MTNjNmVhYjcyOWU4Njc3MzhkMjY5NzA2YTJjMDkxOWIyM2JkMDhlODM2M2NmOTA2NGIwZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ufMLu8baAJo2tuZ8PIL9moppiMTFiWLCRNg9RXvfUHc)
> 
> [rdpwrap ini file.zip](https://github.com/stascorp/rdpwrap/files/15008552/rdpwrap.ini.file.zip)
> 
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/15008563/termsrv.zip)

你这边偏移添加的是3374哎

**Comment by loyejaotdiqr47123** [comment]
你dll版本不是3447吗？

**Comment by loyejaotdiqr47123** [comment]
@quryq

**Comment by HayoINV** [comment]
I need help please. urgent!
![INI](https://github.com/stascorp/rdpwrap/assets/167323502/23170d34-fdd9-4187-9ac0-c8a02334a35d)

**Comment by HayoINV** [comment]
Since yesterday I have tried to solve it and it has not been possible. Who could help me?

**Comment by HayoINV** [comment]
@quryq

**Comment by HayoINV** [comment]
I COULD NOW SOLVE IT!

STEP 1: https://github.com/sebaxakerhtc/rdpwrap/releases Do all the steps of this crack

STEP 2: To do this we are going to go to where we have our RDP Wrapper installed, which is usually in the C:\ProgramFiles\RDP Wrapper folder. Inside we will have a file called "Uninstall" running it as administrator. You will get a message in the CMD window saying that the libraries have been uninstalled correctly, with this we would have the first step.

STEP 3: We download the version modified by the user sebaxakerhtc which is kept updated and with improvements. Thank you for its continuation since it makes the work much easier as it is an executable as if it were another program, since it allows us to update the .ini file from the same software, which allows us to provide support with RDP.

STEP 4: Since the rdpwrap.ini file is not updated with this version, we have to go to the program's installation path (the one we mentioned at the beginning). We open the notepad as administrator and look for that file, once open we are going to paste the following at the end of the text:

[10.0.22621.3447]
SingleUserPatch.x64=1
SingleUserOffset.x64=C3F3
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C2E5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9D661
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=29ED0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.3447-SLInit]
bServerSku.x64=12BF50
bRemoteConnAllowed.x64=12BF64
bFUSEnabled.x64=12BF74
bAppServerAllowed.x64=12BF5C
bMultimonAllowed.x64=12BF68
lMaxUserSessions.x64=12BF54
ulMaxDebugSessions.x64=12BF70
bInitialized.x64=12BF4C

With this we will once again have the support so that we can continue enjoying simultaneous connections via RDP, I hope it has been of help to you since after a long headache it could help me and I think what I have discovered will benefit me in the future .

This worked for me!

**Comment by quryq** [comment]
> > ### what I had done?
> > 
> > 1. Run install.bat  as admin
> >    ![image](https://private-user-images.githubusercontent.com/59192971/323148684-297341ad-fcb1-4312-b512-905543a3e4fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTg5MjMsIm5iZiI6MTcxMzM1ODYyMywicGF0aCI6Ii81OTE5Mjk3MS8zMjMxNDg2ODQtMjk3MzQxYWQtZmNiMS00MzEyLWI1MTItOTA1NTQzYTNlNGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyNTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNTdkMzYwMjNjYTVjZGZkOWQ3ZjJlOTljNzYzOGRjNmY5ZTJhYThmNGU0YWE5ZTFjMGZjNDc5MTViY2JlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BYMLmdk4IbFpqsKr0LAy8f6mTxQA4WRnvtMfPBiHYFY)
> > 2. Add the content to rdpwrap.ini  and save it
> >    ![image](https://private-user-images.githubusercontent.com/59192971/323149596-4bd157ac-e2fe-4f95-862c-7a993e6f69f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTg5MjMsIm5iZiI6MTcxMzM1ODYyMywicGF0aCI6Ii81OTE5Mjk3MS8zMjMxNDk1OTYtNGJkMTU3YWMtZTJmZS00Zjk1LTg2MmMtN2E5OTNlNmY2OWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyNTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZWU2YzBkMWY5ZGJhMDgwOWI3MjQyNDJlNGFkYzIzNTc2NWIzNjhmMTE3YmY4YWE1MzE0ZjJmODg4NDQyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b8yHad67HDlUn3eqIS3Zk0QM1c-fsGbOLssWQlAls7I)
> > 3. run RDPConf.exe
> >    ![image](https://private-user-images.githubusercontent.com/59192971/323149973-c7f0f124-63ad-4b05-b405-a2a834d4e224.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTg5MjMsIm5iZiI6MTcxMzM1ODYyMywicGF0aCI6Ii81OTE5Mjk3MS8zMjMxNDk5NzMtYzdmMGYxMjQtNjNhZC00YjA1LWI0MDUtYTJhODM0ZDRlMjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyNTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiOTJkNWExNDg2YzM1YTAzODU5OGNjYjVlNDAyOGQ4OWEzMjU2YThlOGVjZThiMzEzZmIyMWQ1YjcyZWQ2ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ZlFuUDed2y0zBbDb-URM8p2Gk21Qjx-dS27-TK0tS0)
> > 
> > ### others info
> > ![image](https://private-user-images.githubusercontent.com/59192971/323150544-0fde232c-63a1-468c-b8c7-2c5404360ff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTg5MjMsIm5iZiI6MTcxMzM1ODYyMywicGF0aCI6Ii81OTE5Mjk3MS8zMjMxNTA1NDQtMGZkZTIzMmMtNjNhMS00NjhjLWI4YzctMmM1NDA0MzYwZmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyNTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmODhjYmNmNjc3MTNjNmVhYjcyOWU4Njc3MzhkMjY5NzA2YTJjMDkxOWIyM2JkMDhlODM2M2NmOTA2NGIwZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ufMLu8baAJo2tuZ8PIL9moppiMTFiWLCRNg9RXvfUHc)
> > [rdpwrap ini file.zip](https://github.com/stascorp/rdpwrap/files/15008552/rdpwrap.ini.file.zip)
> > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/15008563/termsrv.zip)
> 
> 你这边偏移添加的是3374哎

谢谢老哥，解决了！！！  我之前试过很多次，偏移改过很多次了，可能是1.6.2那个版本有哪些信息没设置好。

**Comment by quryq** [comment]
> I COULD NOW SOLVE IT!
> 
> STEP 1: https://github.com/sebaxakerhtc/rdpwrap/releases Do all the steps of this crack
> 
> STEP 2: To do this we are going to go to where we have our RDP Wrapper installed, which is usually in the C:\ProgramFiles\RDP Wrapper folder. Inside we will have a file called "Uninstall" running it as administrator. You will get a message in the CMD window saying that the libraries have been uninstalled correctly, with this we would have the first step.
> 
> STEP 3: We download the version modified by the user sebaxakerhtc which is kept updated and with improvements. Thank you for its continuation since it makes the work much easier as it is an executable as if it were another program, since it allows us to update the .ini file from the same software, which allows us to provide support with RDP.
> 
> STEP 4: Since the rdpwrap.ini file is not updated with this version, we have to go to the program's installation path (the one we mentioned at the beginning). We open the notepad as administrator and look for that file, once open we are going to paste the following at the end of the text:
> 
> [10.0.22621.3447] SingleUserPatch.x64=1 SingleUserOffset.x64=C3F3 SingleUserCode.x64=Zero DefPolicyPatch.x64=1 DefPolicyOffset.x64=1C2E5 DefPolicyCode.x64=CDefPolicy_Query_eax_rcx LocalOnlyPatch.x64=1 LocalOnlyOffset.x64=9D661 LocalOnlyCode.x64=jmpshort SLInitHook.x64=1 SLInitOffset.x64=29ED0 SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.22621.3447-SLInit] bServerSku.x64=12BF50 bRemoteConnAllowed.x64=12BF64 bFUSEnabled.x64=12BF74 bAppServerAllowed.x64=12BF5C bMultimonAllowed.x64=12BF68 lMaxUserSessions.x64=12BF54 ulMaxDebugSessions.x64=12BF70 bInitialized.x64=12BF4C
> 
> With this we will once again have the support so that we can continue enjoying simultaneous connections via RDP, I hope it has been of help to you since after a long headache it could help me and I think what I have discovered will benefit me in the future .
> 
> This worked for me!

Well done, bro.   I had solved with this: https://github.com/stascorp/rdpwrap/issues/2578#issuecomment-2061150077

if get error, then uninstall，and try install again
