### ISSUE TITLE
Unsupported termsrv.dll

### ISSUE THREAD

**Issue by joncodis** [stascorp/rdpwrap#258]
Hi,
I have updated the INI file, and still getting a [not supported] Listener.
This version dated end of April, so not real new, but looks new for you :)
OS: Windows 10
DLL Version: 10.0.15063.296
Looking for an update if you can.
Thanks!!

![screenshot 2017-06-05 10 16 11](https://cloud.githubusercontent.com/assets/4029271/26794811/0c569f2a-49d8-11e7-8c24-f0865a4376a6.png)

Searched all C: drive, and only one termsrv.dll found.
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1052678/termsrv.zip)

**Comment by frost2014** [comment]
same question :(

**Comment by binarymaster** [comment]
Added in https://github.com/stascorp/rdpwrap/commit/f71684aa264d8a04d63aa177ff9bf7ced87b4583. Note that if you have Home Edition, it probably won't work due to issue #194.
