### ISSUE TITLE
Windows 10 22H2 10.0.19041.4239 no es compatible

### ISSUE THREAD

**Issue by Alejafer28** [stascorp/rdpwrap#2582]
Hola, neceisto ayuda porque no puedo hacer funcionar el escritorio remoto., ya desinstale y volvi a instalar, y actualice, pero nada funciona
![rdp](https://github.com/stascorp/rdpwrap/assets/128433557/0e46909b-a8b5-46b3-a226-3a3c00971be3)

**Comment by loyejaotdiqr47123** [comment]
Duplicate of #2529

**Comment by Alejafer28** [comment]
Muchisimasss gracias!!

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2529
