### ISSUE TITLE
windows 10  The login box is not displayed

### ISSUE THREAD

**Issue by vuejshub** [stascorp/rdpwrap#2587]
![image](https://github.com/stascorp/rdpwrap/assets/58390198/be7f05d6-918a-447f-bad9-7265353fbbd1)

![image](https://github.com/stascorp/rdpwrap/assets/58390198/cd120575-87a1-4442-9ba6-f1d2511b4a3f)

**Comment by sashaqwert** [comment]
You need to [convert your Microsoft account to local account](https://web.archive.org/web/20210127142930/https://www.itechtics.com/change-account-type/).
