### ISSUE TITLE
Cannot sign into account on RDPWrap

### ISSUE THREAD

**Issue by floppyspud** [stascorp/rdpwrap#2588]
Been using RDPWrap for a few days now, tried to log into it today and the password says it is incorrect, change password and says the new password is also 'incorrect.'

Sign into account on actual PC, password also wrong (I think it changed from a PIN to a password, not sure how but whatever) but I'm able to change the password and sign into it just fine. Even with newly set password I still cannot sign into the account with RDPWrap, nor change the password.

I heard that saving login information can cause issues and may have accidentally done that. Best to just reinstall?

**Comment by sashaqwert** [comment]
Not an RDP Wrapper issue.
