### ISSUE TITLE
Installing RDPWrap breaks outgoing RDP connections

### ISSUE THREAD

**Issue by cowwoc** [stascorp/rdpwrap#259]
Microsoft Windows [Version 10.0.15063]
RDPWrap 1.6.1 (2017.05.29)
ESET Antivirus 10.0.390.0

If I try establishing an RDP connect to my office with either ESET "Web Access Protection" disabled, or with RDPWrap uninstalled, then the outgoing connection works perfectly.

However, if both of these are enabled then outgoing RDP connections fail claiming that the remote address cannot be reached. This happens whether I connect by hostname or IP address.

**Comment by binarymaster** [comment]
This is ESET problem, try contacting their support. I can't resolve this.
