### ISSUE TITLE
Acesso de multiplos usuários

### ISSUE THREAD

**Issue by DF87SE** [stascorp/rdpwrap#2595]
o meu RDPWRAP está suportado e atualizado certinho, mas só permite uma conexão por usuário, ou seja, para um usuário acessar tem que derrubar o logado! tem a solução para isso tbm?

**Comment by binarymaster** [comment]
Non-english not allowed.

**Comment by DF87SE** [comment]
My RDPWRAP is supported and updated for sure, but it only allows one connection per user, that is, for a user to access they have to log in! Do you have a solution for this too?
