### ISSUE TITLE
10.0.19045.4355 Missing Update?

### ISSUE THREAD

**Issue by BrianA-MN** [stascorp/rdpwrap#2597]
Current WIN10 Pro is running 10.0.19045.4355 described as 22H2 Technical Preview. Is this the same update as 10.0.19041.4355?
Thank you to all the coders making this project available to support small home GNU FOSS personal networks of devices which occasionally need to help the MS Windows users with an issue.  Cheers

**Comment by affinityv** [comment]
The Windows version is not usually the same as the version of the termsrv.dll -- ```RDPConf.exe``` will give you the version of the termsrv.dll that it finds (the one in the normal Windows installation location).  If you have extra copies of termsrv.dll in your path (very unlikely), then it might report on the wrong one.

**Comment by BrianA-MN** [comment]
Thank you, that informed my confusion.  Indeed Win10 OS version 10.0.19045.4355 uses the 10.0.19041.4355 termsrv.dll.
I notice that the basic update.bat file doesn't update the rdpwrapp.ini file. I also downloaded and used the latest rdpwrap autoupdate.bat program, also found here on github.  Everything is now working as expected.

**Comment by BrianA-MN** [comment]
SOLVED
