### ISSUE TITLE
10.0.19045.4291 need support

### ISSUE THREAD

**Issue by a4081675** [stascorp/rdpwrap#2599]
<img width="295" alt="image" src="https://github.com/stascorp/rdpwrap/assets/17973196/5334e3b9-c992-4989-a247-65395f90c1b7">
<img width="348" alt="image" src="https://github.com/stascorp/rdpwrap/assets/17973196/29c0deb2-f538-46eb-8094-eae92e11d0dd">

**Comment by 235623** [comment]
no

**Comment by loyejaotdiqr47123** [comment]
@a4081675 Can you upload termsrv.dll?

**Comment by a4081675** [comment]
> @a4081675您可以上传termsrv.dll吗？

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/15141267/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment]
Duplicate of #1004

**Comment by binarymaster** [comment]
> RDPConf shows "ver. N/A"

Not a serviceable issue, contact chat in Telegram instead.
