### ISSUE TITLE
Hostname no longer works after installing RDPWrap

### ISSUE THREAD

**Issue by JRDeAmicis** [stascorp/rdpwrap#260]
Installed on Windows versions 10.0.15063 Build 15063
RDPWrap-V1.6.1

Before installing RDPWrap host name works fine for connecting users to the machine with RDPWrap. 

After installing RDPWrap the host name no longer works we are only able to connect via IP.

If I uninstall RDPWrap I can get it work again via hostname.

Thoughts?
![20170609103846](https://user-images.githubusercontent.com/18170573/26988208-48c1c7ae-4d03-11e7-9dd7-9141f0a9ed5a.jpg)

**Comment by JRDeAmicis** [comment]
We just figured out that network discovery must be ON for host name to work after installing RDPWrap.

**Comment by sskras** [comment]
If it's true, then IMO the issue is very interesting and should be reopened.
@JRDeAmicis, does the name resolution work for ping (with RDPW installed) ?

@binarymaster , any ideas on why name resolution mechanism changes ?

**Comment by binarymaster** [comment]
This is how firewall works. Network discovery must be ON to allow NetBIOS name resolution.

It's rather a firewall bug that doesn't restrict name resolution when network discovery is disabled.
