### ISSUE TITLE
10.0.22631.2861 not support

### ISSUE THREAD

**Issue by hony-tom** [stascorp/rdpwrap#2602]

**Comment by loyejaotdiqr47123** [comment]
@hony-tom Please uplod termsrv.dll

**Comment by hony-tom** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/15206508/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment]
Duplicate of #2443

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2443
