### ISSUE TITLE
Fully supported but not listening on 22621.3447

### ISSUE THREAD

**Issue by wuwuhechen** [stascorp/rdpwrap#2607]
![微信图片_20240510170811](https://github.com/stascorp/rdpwrap/assets/148519284/eadc6045-245e-41f9-beb1-91b74beeb1dc)

I've already replaced the rdpwrap.ini with https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini

![image](https://github.com/stascorp/rdpwrap/assets/148519284/d4904950-58ed-43d5-a4c3-6133c7707362)

Now it's fully supported but not listening. Please help!

**Comment by Snorfle** [comment]
Exact same issue on my end.  Would love a fix.

**Comment by sashaqwert** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2549

**Comment by sashaqwert** [comment]
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131
