### ISSUE TITLE
10.0.19041.4239 printer redirection is not working

### ISSUE THREAD

**Issue by StarLord66666** [stascorp/rdpwrap#2608]
Hi

Already updated RDP ini to version from  issue 2529.
But unable to redirect printers over RDP. Only embedded (Microsoft PDF, FAX, etc.) are showing.
Please advise.

**Comment by sashaqwert** [comment]
> But unable to redirect printers over RDP

Solution in https://github.com/stascorp/rdpwrap/issues/504

**Comment by StarLord66666** [comment]
It is not solving problem. Could you provide me steps to follow to solve the issue

**Comment by sashaqwert** [comment]
Please, ask in official Telegram chat https://t.me/rdpwrap
