### ISSUE TITLE
Add support for termsrv.dll 10.0.16215.1000

### ISSUE THREAD

**Issue by LuDdk** [stascorp/rdpwrap#261]
Hello,
i use the insider preview, so every week, i got a new release of termsrv, and the program doesn't works anymore.
I actually know a bit of programming, so, if you could teach us, im pretty sure we can help you doing the boring part!
Anyway, im uploading the new file.
Thank you.

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1065863/termsrv.zip)

**Comment by binarymaster** [comment]
Hello.

There's a link to video tutorial in the README that shows how to add new sections into INI file.

See it and you'll be able to do it.

**Comment by LuDdk** [comment]
Gosh, i'll take a week or more to do it, but thnks
hahahah

**Comment by dgadelha** [comment]
@binarymaster after installing RDPWrap in this build, the RDP service fails to start with:

```Error 577: Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be a malicious software from an unknown source.```

Tried disabling completly SmartScreen, Windows Defender, Firewall, but nothing solves it

**Comment by LuDdk** [comment]
@binarymaster. Yes, I just tested and the scenario is the same of @dgadelha

**Comment by LuDdk** [comment]
Even without the update, just installing the wrap.

**Comment by binarymaster** [comment]
Well, it seems like Microsoft introduced this new feature to check digital signature for built-in services.

Try to search how to disable digital signature checking.

**Comment by LuDdk** [comment]
Cant find anything for now :/

**Comment by dgadelha** [comment]
Disabled *driver* digital signature enforcement (there was nothing about softwares/files, just drivers), and, unfortunately, the issue persists

```
C:\WINDOWS\system32>net start termservice
The Remote Desktop Services service is starting.
The Remote Desktop Services service could not be started.

A system error has occurred.

System error 577 has occurred.

Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.
```
Also, tried the following commands after disabling enforcement at boot:
```
C:\WINDOWS\system32>bcdedit /set nointegritychecks on
The operation completed successfully.

C:\WINDOWS\system32>bcdedit /set testsigning on
The operation completed successfully.
```
And, after rebooting, the issue persists.

**Comment by vinzf** [comment]
It seems that in upcoming Windows 10 versions `svchost.exe` will only load signed service dll files.
The question is if any valid code signing certificate will be accepted or only a Microsoft-internal one.
Probably latter, since the svchost subsystem is not intended for "public use" AFAIK.
And even otherwise, nobody will volunteer to sign the wrapper dll with their code signing cert because MS might ban them.

Does this mean this project has come to an end on Windows 10?

**Comment by binarymaster** [comment]
> The question is if any valid code signing certificate will be accepted or only a Microsoft-internal one.

Indeed.

Well, it still works with older Windows 10 builds. There are two major issues now.

**Comment by BiceBolje** [comment]
Microsoft then should offer CAL's for Windows 10 Professional editions... 
I set all my clients that rely on connecting to some remote PC's (it's just POS systems) to Business branch,  365 days of prolonging updates, and 30 days of "quality" updates, which I am scared of. It works with 1703, but when and if they cut us the possibility of connecting concurrent users, I don't see any viable alternative then. It's impractical to have Server versions on POS systems.
