### ISSUE TITLE
Freezing threads... 

### ISSUE THREAD

**Issue by AlexanderSeelen** [stascorp/rdpwrap#264]
Hi,

We have an issue on our server. the threads hang some times with this logging.

```
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x000007FEF1F60000
SvcMain:    termsrv.dll+0x000000000000F6DC
SvcGlobals: termsrv.dll+0x000000000000F2F8
Version:    6.1.7601.18637
Freezing threads...
Hook SLGetWindowsInformationDWORD
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
```

Can anyone help me out?

System: Windows 7 (64) POS Ready

Regards,
Alexander Seelen.

**Comment by binarymaster** [comment]
These log lines are not related, this is normal behaviour.

**Comment by AlexanderSeelen** [comment]
@binarymaster Thanx for your answer, but

The behaviour is that during work time the RDP sessions stop and in a short time period the clients can log in to the system again. 

We would like to prevent this and I assumed that the log as shown was a possible cause. Can you help me out where to look at the system to prevent the stopping of RDP?

Regards, 
Alexander.

**Comment by binarymaster** [comment]
How much clients are connecting to the server at once?

Is RDP server available from the Internet?

And please see Event Log for any events related to `TermService`.

**Comment by AlexanderSeelen** [comment]
At the most there are 8 clients active.
The RDP server is 'not' aviable over the Internet, only internal LAN.
There are nog EventLog items related to 'TermService'. 

Thats why we where looking at the log-file of RDWrapper.

**Comment by binarymaster** [comment]
Well, RDP Wrapper couldn't behave like this, since it only wraps policy functions of the original Terminal Services.

It could be a problem with the network adapter (local connection).

**Comment by AlexanderSeelen** [comment]
Thankx for your advise, we are going to look more at the LAN adapter.
Try to adjust some more settings to prevent the outtake of RDP.

**Comment by binarymaster** [comment]
Closing as inactive.
