### ISSUE TITLE
User Account is Not Authorized for Remote Login

### ISSUE THREAD

**Issue by PatrickPem** [stascorp/rdpwrap#265]
Hello All- I have a perplexing situation. I have RDP Wrapper installed and configured on my Windows 10 HOME computer. It works fine for my user account. However, it's when trying to RDP to the computer as any other user where I have the issue.

When I try any other user, I get the message that the user is not authorized for remote login. Now notice again that I said this was Windows 10 HOME, and not Pro. Obviously, in Pro, all I would have to do would be to go to the remote users area and put those users into that list. However, since this is HOME, I do not have that option.

I get this message if I have RDP Wrapper set to either "**_Default RDP Authentication_**" or "**_Network Level Authentication_**".  If I set it to "GUI Authentication Only", it tells me that I must sign in through Remote Desktop Services (again, my regular user can connect this way, but no other users)

The really confusing thing to me is that the user account that I use all of the time on this computer works fine. It's just the other users. On a side note, it is the working account that installed RDP Wrapper. I imagine that is playing into it somehow.

But the bottom line question is, how do I get other users to be authorized when there is no way to do it in Windows 10 HOME.

Thanks for any help you may be able to provide.

-Patrick

**Comment by binarymaster** [comment]
Why you don't reading `README.md`?

![image](https://user-images.githubusercontent.com/578406/27470151-2d927b56-57fb-11e7-8cbf-33e216aec882.png)
