### ISSUE TITLE
Shadow error: Access is denied

### ISSUE THREAD

**Issue by AmitMY** [stascorp/rdpwrap#267]
First, gotta say thanks for this awesome tool! Saved me from downgrading to win 7.

I followed the readme, and can now remotely login to the PC running Windows 10 (latest update up to 27/06/2017).

However, when trying to shadow the session (`mstsc /shadow:2`) I get a prompt straight up:
> Shadow Error
> Access is denied

In the configuration, all is green, so it is not like: https://github.com/stascorp/rdpwrap/issues/215
It might be similar to https://github.com/stascorp/rdpwrap/issues/247, because I am on the latest update, but again, all green, and a different error message

I would appreciate any help!

**Comment by fidergo-stephane-gourichon** [comment]
No feedback from maintainer?

README.md links to http://woshub.com/rds-shadow-how-to-connect-to-a-user-session-in-windows-server-2012-r2/ which claims:

>     Only server administrator can connect to other sessions. These rights can not be delegated to regular  users
>     RDS Shadow won’t work in the networks based on workgroups

@binarymaster does this apply here? What reason can cause access denied on shadowing? (For example, on Win10 1703 15063.674.)

Thanks.

**Comment by binarymaster** [comment]
For me this just looks like a Windows bug, and almost entire Windows NT 10 looks unstable for me (that's why I still use Windows 7).

Also take look at this: https://github.com/stascorp/rdpwrap/issues/247#issuecomment-338357127

**Comment by binarymaster** [comment]
> Only server administrator can connect to other sessions. These rights can not be delegated to regular  users

Well, this actually makes sense, the user must have some privileges to shadow other sessions.

**Comment by svargh** [comment]
Would like to tell, that shadowing is working  for **Windows 10 20H2 Version 10.0.19042.80**4.

I had to activate shadowing in gpedit.msc -> Computer Configuration >> Administrative Templates >> Windows Components >> Remote Desktop Services >> Remote Desktop Session Host >> Connections -> Set rules for remote control ....' 
After rebooting, shadowing works.

For my computer Windows 10 20H2 Version 10.0.19042.804 seems to be very stable (No problems performing hibernation/standy and resume cycles during  heavy GPU RTX 3090 Cuda Load , Memory load with multiple running VMWare instances)

PS: And huge thanks for providing rdpwrap.

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.

**Comment by Beej126** [comment]
re: shadow access denied see: https://github.com/stascorp/rdpwrap/issues/1512#issuecomment-1575796569
