### ISSUE TITLE
New build of terminal services Windows 8.1  6.3.9600.18692 which is not supported

### ISSUE THREAD

**Issue by Zaebumba** [stascorp/rdpwrap#269]
Good day!
There is a new version of terminal services in Windows 8.1 Pro that is not supported - 6.3.9600.18692

**Comment by johndewood** [comment]
Here is the termsrv.dll 6.3.9600.18692
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1113021/termsrv.zip)
