### ISSUE TITLE
Local printer management

### ISSUE THREAD

**Issue by FilippoBruschi** [stascorp/rdpwrap#270]
Hi,

is it possible to use local printers with RDP Wrapper?
Actually i'm not able to do this.

                                                           Thanks, Filippo

**Comment by shippj** [comment]
local printers work just fine for me.  (win7 server and clients)

**Comment by jaggeri** [comment]
Right Click Edit your RDP Icon.
Select Local Resources Tab
Tick Printers in the Local devices and resources box

![image](https://user-images.githubusercontent.com/28880253/28698407-64cc7c28-7382-11e7-9257-915154525767.png)
