### ISSUE TITLE
Windows 10 Education issues

### ISSUE THREAD

**Issue by ingeniious** [stascorp/rdpwrap#273]
I was wondering if RDPWrapper supports Windows 10 Education edition or if we need to change over to Windows 10 Pro.   Keep having issues with RDP disconnecting users.

**Comment by ingeniious** [comment]
https://partnersupport.microsoft.com/en-us/par_clientsol/forum/par_win/win-10-to-win-10-rdp-connection-fails/8f3628ca-5a6b-42c1-9655-7f4709ce5d06?auth=1
Per the recommended solution I took the mstsc.exe and mstscax.dll files in Windows 10 1607 version, took ownership of the computer being remoted into of these two files, renamed them .bak and then copied the two files from the 1607 Windows 10 in C:\Windows\System32.

That seemed to work for a while but still having issues with people being kicked out.

**Comment by ingeniious** [comment]
I have since tried replacing the termsrv.dll under C:\Windows\System32 with the termsrv.dll from 
bidinhos commented on May 11
"Here is a copy of termsrvtermsrv.dll.zip"

I am hoping this will work but not sure, would appreciate some guidance sir :-)

**Comment by binarymaster** [comment]
I don't know whether Win 10 Education supports RDP out-of-box. If it does support it, then with RDP Wrapper it would behave same as Win 10 Pro.
