### ISSUE TITLE
Not working on Windows build 10.0.16232.1000

### ISSUE THREAD

**Issue by CermakPOI** [stascorp/rdpwrap#275]
Not working on Windows build 10.0.16232.1000
![rdpwrap-10 0 16232 1000](https://user-images.githubusercontent.com/11089205/27992248-d0c93daa-648f-11e7-9ae3-3e04b1b7b0ed.PNG)

**Comment by oywino** [comment]
Not working for me either on Windows 10 Home Edition 10.0.15063.
![rdpconf](https://user-images.githubusercontent.com/18447119/27995927-ff527186-64d6-11e7-9d7e-d440f1c09164.PNG)

![rdpcheck](https://user-images.githubusercontent.com/18447119/27995930-1baf7a04-64d7-11e7-991c-083e11754150.PNG)

**Comment by johneakin** [comment]
I'm also having a connection issue after the latest update to windows10

**Comment by oywino** [comment]
@binarymaster, could you please explain why you deleted my comment??

**Comment by binarymaster** [comment]
@oywino it was offtopic.

**Comment by oywino** [comment]
Hi @binarymaster, thanks for answering.
In what way was it "Off Topic" ??
This thread is about RDPwrap. My post was about RDPwrap. How can that be "Off Topic" ?

**Comment by oywino** [comment]
@binarymaster - So if I had just written "Windows 10" and not stated my Build number (like @johneakin did), it would not have been "Off Topic" ?

**Comment by binarymaster** [comment]
If you have the same build number, then your post was rather non-informative than off-topic, since the problem is already known - issue ticket is here.

Otherwise it's off-topic.

**Comment by oywino** [comment]
@binarymaster, well I found #235 now.....
