### ISSUE TITLE
Not working after update to 16237.1001 build

### ISSUE THREAD

**Issue by ansromanov** [stascorp/rdpwrap#279]
Not working after update to 16237.1001 build

![image](https://user-images.githubusercontent.com/1626964/28093643-f2408b10-66a0-11e7-85e8-bf5be74a9c52.png)

**Comment by lousuan** [comment]
See #194 ?

**Comment by binarymaster** [comment]
@lousuan it is not related. This is new build.

**Comment by ansromanov** [comment]
I saw https://github.com/stascorp/rdpwrap/issues/194 but unfortunately
there are no information related to 16237.1001 build in that thread.

2017-07-12 21:12 GMT+03:00 binarymaster <notifications@github.com>:
