### ISSUE TITLE
RDP from Windows 10 to itself Fails when Password is saved, but succeeds if entered manually

### ISSUE THREAD

**Issue by Driffster** [stascorp/rdpwrap#280]
I am trying to open a remote session directly on the computer (win10 creator update), using port 127.0.0.2. This works fine for all my users, as long as I don't try to save the credentials. If I save the credential, the next login I get this error (which makes no sense):

> The connection was denied because the user account is not authorized for remote login.

Note that saving credentials works fine if I connect from another computer. 

I tried all the tricks for setting authorization, but its not the issue. My problem is similar to this, which is not resolved:
[https://social.technet.microsoft.com/Forums/en-US/6d311c82-f9f4-4514-b1ea-5f1ad0aae890/rdp-from-windows-10-to-windows-10-fails-when-password-is-saved-but-succeeds-if-entered-manually?forum=win10itpronetworking]()

**Comment by princekream** [comment]
When I first read this, I thought there was something odd with your install.

Then I tried it. And I’m getting the exact same behavior.

When credentials are saved in rdp file, Windows will return some bogus message. It’s only after I remove credentials and start again that my rdp session starts.

Any insight would be really appreciated.

**Comment by Driffster** [comment]
Well I was never able to find a work around for this and I abandoned this approach for my app. I don't think its an issue with rdpwrap, but with RDP api. 

My end goal is to automate a software through an RDP window. That application  would open to another user session on the same computer and run from that session another application (that can`t be automated except with macros..) this was the only a non obstructive way to the end user that I found. 

I do it right now by passing through a virtual windows on that same PC (huge waste of resource to do that unfortunately, but now on that virtual session I am able to log in as another user on the same pc..

**Comment by JCBuck** [comment]
> 
> 
> Well I was never able to find a work around for this and I abandoned this approach for my app. I don't think its an issue with rdpwrap, but with RDP api.
> 
> My end goal is to automate a software through an RDP window. That application would open to another user session on the same computer and run from that session another application (that can`t be automated except with macros..) this was the only a non obstructive way to the end user that I found.
> 
> I do it right now by passing through a virtual windows on that same PC (huge waste of resource to do that unfortunately, but now on that virtual session I am able to log in as another user on the same pc..

In order to allow this method to work, it seems you must used saved passwords in the rdp file as opposed to the windows credential store for the user. After you remove the saved password from the credential store, it will no longer show that error.

Just add the password line to an rdp file and it will allow loopback connections without asking for a password and logon automatically.  This works even with a scheduled task that starts on boot up.
https://serverfault.com/questions/867467/rdp-file-with-embedded-password-asks-for-password

**Comment by sebaxakerhtc** [comment]
Closed as solved

**Comment by policeman0077** [comment]
> n issue with rdpwrap, but with RDP api.
> 
> My end goal is to automate a software through an RDP window. That application would open to another user session on the same computer and run from that

have same issue here

**Comment by G98oFPsRTYodD5N** [comment]
> Closed as solved

Hello, how did you solve this problem? Can you tell me? I also cannot save RDP login credentials for 127.0.0.2, and I need to enter manually every time, which makes me very upset

**Comment by binarymaster** [comment]
For further discussion use Telegram support chat.
