### ISSUE TITLE
x64

### ISSUE THREAD

**Issue by skorp-0077** [stascorp/rdpwrap#281]
Hello. I need to compile only for x64 OS versions. Assembling under x64 is successful, but when I start .exe I get an "exception eaccessviolation in module": http://i.imgur.com/B1aoeGz.png
Help please!

**Comment by binarymaster** [comment]
Which Delphi version you use? I didn't tried to compile installer for x64 platform.

**Comment by skorp-0077** [comment]
Delphi XE8 22.0.19027.8951 Lite 11.0

Which version would you recommend?
