### ISSUE TITLE
Logs in and then immediately kicks me out then unable to log in locally

### ISSUE THREAD

**Issue by hoveeman** [stascorp/rdpwrap#282]
Windows 10 Pro Version 1703 Build 15063.483

I can RDP into the machine successfully for a few hours or days, and then randomly it will not let me log in any more. I will launch RDP which i have successfully connected from previously and it will connect and then instantly kick me out. I had RDPWrap 1.6.1 installed with the latest update from the batch file and was experiencing this. I uninstalled RDPWrap and am still experiencing this behavior. I looked through the Windows event logs and found these errors below when I try to connect and it kicks me off.

The only way I can get back in to the system is to hard power it off. I will even try to sign in from the keyboard and mouse at the machine and it will sit there and spin. The machine is still working properly, as I have my plex server on there and I can still access it successfully from other devices.

It sounds similar to this issue:
https://github.com/stascorp/rdpwrap/issues/146

`The Windows logon process has unexpectedly terminated.`

```
- System 

  - Provider 

   [ Name]  Microsoft-Windows-Winlogon 
   [ Guid]  {DBE9B383-7CF3-4331-91CC-A3CB16A3B538} 
   [ EventSourceName]  Winlogon 
 
  - EventID 4005 

   [ Qualifiers]  49152 
 
   Version 0 
 
   Level 2 
 
   Task 0 
 
   Opcode 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2017-07-16T03:36:44.589817800Z 
 
   EventRecordID 13054 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  0 
   [ ThreadID]  0 
 
   Channel Application 
 
   Computer
 
   Security 
 

- EventData 

   05400080 


--------------------------------------------------------------------------------

Binary data:


In Words

0000: 80004005    


In Bytes

0000: 05 40 00 80               .@.

```

`A timeout (60000 milliseconds) was reached while waiting for a transaction response from the NlaSvc service.`

```
- System 

  - Provider 

   [ Name]  Service Control Manager 
   [ Guid]  {555908d1-a6d7-4695-8e1e-26931d2012f4} 
   [ EventSourceName]  Service Control Manager 
 
  - EventID 7011 

   [ Qualifiers]  49152 
 
   Version 0 
 
   Level 2 
 
   Task 0 
 
   Opcode 0 
 
   Keywords 0x8080000000000000 
 
  - TimeCreated 

   [ SystemTime]  2017-07-12T18:31:40.094587100Z 
 
   EventRecordID 10313 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  1008 
   [ ThreadID]  11164 
 
   Channel System 
 
   Computer
 
   Security 
 

- EventData 

  param1 60000 
  param2 NlaSvc 
```

`A timeout (60000 milliseconds) was reached while waiting for a transaction response from the iphlpsvc service.`
```
 System 

  - Provider 

   [ Name]  Service Control Manager 
   [ Guid]  {555908d1-a6d7-4695-8e1e-26931d2012f4} 
   [ EventSourceName]  Service Control Manager 
 
  - EventID 7011 

   [ Qualifiers]  49152 
 
   Version 0 
 
   Level 2 
 
   Task 0 
 
   Opcode 0 
 
   Keywords 0x8080000000000000 
 
  - TimeCreated 

   [ SystemTime]  2017-07-12T18:32:40.103032500Z 
 
   EventRecordID 10314 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  1008 
   [ ThreadID]  11164 
 
   Channel System 
 
   Computer 
 
   Security 
 

- EventData 

  param1 60000 
  param2 iphlpsvc 
```

**Comment by binarymaster** [comment]
This looks like Windows bug problem.

However, restarting Terminal Services using `RDPWInst.exe -r` command could help.

**Comment by hoveeman** [comment]
Thanks for the reply! I will give that a try when it pops up again.

**Comment by jaffster123** [comment]
I've spent the last 2 hours scouring the web trying to identify what the issues are with my home NAS/Plex server.

I finally landed here and I have EXACTLY the same issue. I actually completely forgot about my install & uninstall of RDPWrap until I came here and read this thread. I also suffer with the black screen issue, it seems to happen every few days - Everything runs fine and then it will randomly no longer work - I RDP in and it just hangs at a black screen and then kicks me out. I then inevitably end up on the phone with my girlfriend at home and she has to physically restart the computer to get everything back up and running.

Did you get anywhere with this?

**Comment by hoveeman** [comment]
@jaffster123 Unfortunately I never could figure out a fix. I eventually gave up and re-installed Windows 10. Thankfully the WIndows 10 reinstall features are very nice. After the reinstall, all of my User accounts, settings, and files were still on my computer. The only thing missing were the Applications. I had to reinstall those and then I was back up and running. I'm on Windows 10 Pro, so the only functionality I really lost by not having RDPWrap was concurrent users. 

To do this, go to Settings and then Reset my pc. Not necessarily recommending this, but I got tired of troubleshooting and I knew this would fix the issue.

**Comment by appiekap653** [comment]
I have also the same problem. I also have Plex server running on the pc i try to remote connect to through rdp.

**Comment by jaffster123** [comment]
@appiekap653 It is 100% an issue with RDPWrap. 

When originally uninstalled some remnants of it must have remained somewhere. I re-installed the latest version and then uninstalled it again and didn't have the issue ever again.

**Comment by FoldZero** [comment]
I also have the random black screen causing me to have to restart the machine.
It usually happens with the first login each day, subsequent logins are then OK.

I have Windows 10 creators update.
rfxvmt.dll - ver. 10.0.15063.0

**Comment by jaffster123** [comment]
@FoldZero 

Uninstall RDPWrap properly, then re-install it. It worked for me.

**Comment by sebaxakerhtc** [comment]
Closed as solved
