### ISSUE TITLE
3 user at the same time... how to do?

### ISSUE THREAD

**Issue by christiande2000** [stascorp/rdpwrap#283]
Hi 

I have a problem. If I am logged in locally with username : station1 and then a remote machine trys to connect with username: station3 it  warns me that another user is already logged-in. If the remote user logs-in then the local user will log-off .   

How to set up rdpwrap that 2 or more diffrent user can use the machine at the same time??? Can somebody help me?

Best regards
Christian

**Comment by binarymaster** [comment]
Please provide diagnostics `RDPConf` screenshot.

**Comment by christiande2000** [comment]
Hi

![grafik](https://user-images.githubusercontent.com/30258944/28573233-47a86826-714a-11e7-93cb-61a4bd9cb5db.png)

Here is the screen of the config.
I also have tried different kind and combination of the config but it has never solved the problem.

Wehere is the mistake?

Yours Sicerly Christian

**Comment by binarymaster** [comment]
According to build `10.0.15063.0`, your issue duplicates #233 and #194, so I'm closing this issue.
