### ISSUE TITLE
10.0.22621.1928 fully supported but not working

### ISSUE THREAD

**Issue by Dassie2019** [stascorp/rdpwrap#2834]
![Screenshot (14)](https://github.com/stascorp/rdpwrap/assets/54889477/415c5f54-41bd-4036-a354-1867a24fa974)
RDP wrapper showing fully supported but still can't connect multiple users

Please help.

**Comment by loyejaotdiqr47123** [comment]
@Dassie2019 Please upload termsrv.dll

**Comment by binarymaster** [comment]
Duplicate of #2258.
