### ISSUE TITLE
Add support for build 6.3.9600.18708 (KB4025335)

### ISSUE THREAD

**Issue by mascarasnake66** [stascorp/rdpwrap#285]
Hello, I just want to convey some information for you that may be of assistance.

After applying MS update KB4025335 to Windows 8.1, RDP Wrapper stopped working. Not certain at this time what the reason is. I'm conveying it to your team as a head's up. 

My quick fix was to uninstall the update, so I am back. Some people are reporting that this update breaks "certificate based computer authentication", which sounds like it potentially could be a problem with RDP. People running 2012 server report this problem.

Recent MS updates for Windows 7 have not broken anything. I do not run Windows 10.

Anyway, I am just reporting it to you, if you need any help from me please feel free to reach out.

Regards,
mark

**Comment by binarymaster** [comment]
What is your `termsrv` build version?

**Comment by mascarasnake66** [comment]
After uninstalling, I'm at 6.3.9600.18692

As mentioned, I uninstalled the KB and now I am working. It's no big deal reapplying the KB, I can do that and report back if there is a new version installed if you think that will help.

Regards,
Mark

**Comment by jdewood1** [comment]
Here is the dll for 6.3.9600.18708
[termsrv_dll_6.3.9600.18708.zip](https://github.com/stascorp/rdpwrap/files/1173405/termsrv_dll_6.3.9600.18708.zip)

**Comment by KipFun** [comment]
and on Win8.1 build 9600.18730 , wrapper not working, new ddl in attach.
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1179741/termsrv.zip)
