### ISSUE TITLE
Listener is not working, error 1056

### ISSUE THREAD

**Issue by ok1mgj** [stascorp/rdpwrap#287]
Hello, RDP wrapper is not working on my win 10 Home 1703 build 15063.483.
After update are things same as before.
https://drive.google.com/file/d/0B_St_EUz2VvdVEVEVkg1WmxrQU0/view

any idea?
thanks for any help.
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1188450/termsrv.zip)

**Comment by binarymaster** [comment]
This issue duplicates #235, closing.
