### ISSUE TITLE
Windows 2012 R2 latest termsrv.dll, version 6.3.9600.17095 not supported

### ISSUE THREAD

**Issue by aenaon** [stascorp/rdpwrap#289]

**Comment by binarymaster** [comment]
Support for build `6.3.9600.17095` was already added long time ago. Run `update.bat`.

**Comment by aenaon** [comment]
Thank you for the prompt reply.
Did install (error: This version of Terminal Services is not supported.)
Run update.bat, version 2017.07.30, everything is up to date.
Run RDPWinst.exe -w, the same.

Yet the systray notification is still counting down days to deactivation.

Am I missing something here?

**Comment by binarymaster** [comment]
Run `RDPConf` and see diagnostics.

**Comment by aenaon** [comment]
[Screenshot](http://imgur.com/ZUw7W9v)

**Comment by binarymaster** [comment]
Your build is `6.3.9600.18708`, not `6.3.9600.17095`.

Anyway, this one is already supported too.

**Comment by aenaon** [comment]
Ok, great :) But why do I get the countdown notification? Or it doesn't matter?

**Comment by binarymaster** [comment]
Which countdown notification?

**Comment by aenaon** [comment]
[Screenshot](http://imgur.com/a/P8and)

**Comment by binarymaster** [comment]
To avoid this thing, you'll need to switch Terminal Services into remote administering mode (I don't remember exactly how this option is named).

**Comment by aenaon** [comment]
Ok, thanks a lot for you help :D
