### ISSUE TITLE
Session-based deployment vs VDI-base deployment in win2012r2

### ISSUE THREAD

**Issue by aenaon** [stascorp/rdpwrap#290]
Noticed that this really cool wrapper takes care of termsrv.dll, but not of the licensing service.
To be precise, using version `6.3.9600.18708` of the dll allows numerous RD and RemoteApp connections, but the server counts down from 120 days until it stops permitting the use of RDS or you reset the grace period.
A fact that may be relevant is that installation gives the error `This version of Terminal Services is not supported.`
My question is, are there plans to patch the RD licensing service so to make this wrapper a full "set it and forget it" solution?

**Comment by binarymaster** [comment]
> My question is, are there plans to patch the RD licensing service so to make this wrapper a full "set it and forget it" solution?

No, there are no plans for wrapping anything else but TermService.

**Comment by sskras** [comment]
@aenaon and you can find a skilled developer / analytic of windows internals so he makes you a nice fork of the RDPWr.
