### ISSUE TITLE
Windows 10 Creators Update has killed RDP Wrapper

### ISSUE THREAD

**Issue by v-mwalk** [stascorp/rdpwrap#291]
Hi Guys,

Since being forced to install the Windows 10 Creators Update I cannot get RDP Wrapper working.  I've seen other issues raised on here with the same problem but they've been closed as 'duplicates'; I've followed the line of duplicates back but cant find the fix?

I'm Windows 10 Pro (not home).

Am i missing something? :-)

**Comment by WashingtonJunior** [comment]
It's working on Win10 Pro, even after Windows 10 Creators Update. Several people are upgrading their Home version to Pro, to continue to use RDP Wrapper.

**Comment by v-mwalk** [comment]
This is 100% my 'user error'!

If other folk are having this issue after Windows 10 Creators Update **execute the RDPWrapper 'update.bat'** batch file.

This fixes the 'problem' (which is not actually a problem).

Apologies to Stascorp n co .  I raised the issue before trying the 'update.bat' - doh!
