### ISSUE TITLE
10.0.15063.0 - Home 32 Bit - Listener not working

### ISSUE THREAD

**Issue by timi35** [stascorp/rdpwrap#294]
Hi binarymaster,

I have seen that you have closed all issues with this problem, but the problem still exists.

Yesterday I got the creators update on my Windows 10 Home 32 bit.
I tried an update of your software but the listener shows only "not listening - full supported".

Before you'll close my request, could you give a hint, how I can use rdpwrap again?

Thanks a lot!
Tim

**Comment by tjgng** [comment]
https://github.com/stascorp/rdpwrap/issues/194

**Comment by binarymaster** [comment]
> I have seen that you have closed all issues with this problem, but the problem still exists.

Stop creating new issues about the same, this will not speed up the things.

> Before you'll close my request, could you give a hint, how I can use rdpwrap again?

Roll back to `10.0.14986.1000` or install Windows 7.
