### ISSUE TITLE
I loose RDP wrapper function when correcting for computer not sleeping

### ISSUE THREAD

**Issue by actanner** [stascorp/rdpwrap#295]
The Creator's Update (1703) upgrade apparently introduced a problem with the  "sleep"  function.  It seems that when an RDP session occurs and is finished on a computer, then thereafter the computer will not go into the sleep mode.  You can read about this problem and some proposed work-arounds here:  
https://social.technet.microsoft.com/Forums/en-US/6321ddfe-6a35-4770-8485-a294ca06082e/windows-10-creators-edition-will-not-sleep-after-an-rdp-session-has-connected-to-the-machine-even?forum=win10itprogeneral
  A work-around that seems to put the computer back in the proper state involves executing a batch file with the following instructions in it:
     net stop UmRdpService
     net stop TermService
     net start TermService
  I have tried this and it seems to put the computer back in a state which allows it to "sleep", but it has the undesired side effect of breaking my RDP wrapper features.  In fact, I am not even able to log in remotely after this.  So I log in locally, uninstall RDP wrapper, re-install RDP wrapper, and re-install the update, and then it works again.
      It seems like I should be able to add something to the batch file to "refresh" RDP wrapper so that I don't lose its functionality, but I have no idea how to do this.  Can anyone help?   THANKS!

**Comment by Juesto** [comment]
Sleep is usually a problematic feature....
you can probably do this via task scheduler somehow...
Sleep shutdowns the network. it's likely a bug in remote desktop itself thus not caused by the wrapper.

**Comment by sebaxakerhtc** [comment]
Not an rdpwrapper issue
Microsoft recommendations to disable sleep when you want to use rdp
