### ISSUE TITLE
It does not work in Windows 10

### ISSUE THREAD

**Issue by PhilipOrleans** [stascorp/rdpwrap#297]
I just installed the latest version on Windows 10 Creators Update, version 1703, build 16251.0, and it says it installed, but when I did the test, I type my password and it says Access is Denied.

I can give a developer access to my box via Teamviewer if needed.

**Comment by bombcheck** [comment]
Duplicate of #194

**Comment by mccorkle** [comment]
Check out the solution provided by @youjoy  in #194
