### ISSUE TITLE
Installing 1.6

### ISSUE THREAD

**Issue by Moonage62** [stascorp/rdpwrap#298]
No matter what I do, or what I download, whenever I install rdpwrap it shows version 1.5.  Please advise.  Here's system info:

OS Name	Microsoft Windows 10 Home
Version	10.0.15063 Build 15063
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	ANTHONY-PC
System Manufacturer	ZOTAC
System Model	NM10
System Type	x64-based PC
System SKU	To Be Filled By O.E.M.
Processor	Intel(R) Atom(TM) CPU D525   @ 1.80GHz, 1796 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 080016, 12/23/2010
SMBIOS Version	2.6
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	ZOTAC
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.15063.502"
User Name	Anthony-PC\Anthony
Time Zone	Eastern Daylight Time
Installed Physical Memory (RAM)	4.00 GB
Total Physical Memory	3.99 GB
Available Physical Memory	1.41 GB
Total Virtual Memory	7.99 GB
Available Virtual Memory	5.05 GB
Page File Space	4.00 GB
Page File	C:\pagefile.sys
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not InstantGo, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	No
Hyper-V - Second Level Address Translation Extensions	No
Hyper-V - Virtualization Enabled in Firmware	No
Hyper-V - Data Execution Protection	Yes

**Comment by mccorkle** [comment]
@Moonage62 I believe there is an answer in the README that one of the DLLs no longer gets updated with the new versions.  Check around the bottom of the front page of this repo: https://github.com/stascorp/rdpwrap

**Comment by Moonage62** [comment]
Found it.  Thanks.  My issue is I am running a server here.  Version 1.5 was not playing nice with 15063.  Was told to make sure I had 1.6.1, which is what I installed.  I really don't want to install 15063 on the server until I know this won't get broken.  ( I am using Windows Professional, so SHOULD be good? )

**Comment by Juesto** [comment]
the DLL is still versioned 1.5
do not worry about it
