### ISSUE TITLE
Add new ini  to the install folder

### ISSUE THREAD

**Issue by shubell** [stascorp/rdpwrap#300]
Hi, could you maybe add an option to the installer that he would check if there is a new ini file in the installer folder. This is very useful if you deploy rdpwrap via group policy and it has no access to the internet.
Ok you could add some other group policy to update the ini file in the program files rdp wrapper folder but it isn't very elegant.

**Comment by Julien-nl** [comment]
i would love to know how to deploy this using the GPO.

**Comment by shubell** [comment]
computer configuration
policies
windows settings
scripts
startup
\\domainserver\xxxxx\rdpwinst.exe 
don't forget the parameter -i

**Comment by shubell** [comment]
To update the ini file i used another gpo.  
computer configuration,
preferences,
windows settings,
files,
Here i added the file, action = Replace, source file = \\domainserver\xxxxx\rdpwrap.ini, destination file = %programfiles%\RDP Wrapper\rdpwrap.ini

**Comment by beasoscar** [comment]
des someone has the rdwrap.ini for Windows 11? or some updated solution?, thanks

**Comment by jingyu233** [comment]
> des someone has the rdwrap.ini for Windows 11? or some updated solution?, thanks有人有适用于 Windows 11 的 rdwrap.ini？还是一些更新的解决方案？，谢谢

hello,
https://github.com/sebaxakerhtc/rdpwrap.ini
