### ISSUE TITLE
Adjust Service Dependency to match server counterparts

### ISSUE THREAD

**Issue by Juesto** [stascorp/rdpwrap#301]
Not an issue by itself but.
There may be issues with open files and killing unwanted services due to it...
it's because terminal services is assigned to NetworkService group on workstation builds by default.
termsvcs svchost group does exist on workstations like on servers, modifying the ImagePath verifies this.
for install purposes it kind of gives an advantage because it is the only service that uses such group.
Optional tweak for installer. (and if it happens it must happen before the service starts so it takes effect properly. plus optional reversion on uninstall

**Comment by binarymaster** [comment]
When the user installs some updates, Windows can reset Svchost groups, Image Paths, and Service DLLs to their defaults, so this is not reliable approach.

**Comment by Juesto** [comment]
Only RDP updates so it should be completely unaffected!

**Comment by binarymaster** [comment]
Windows **will** reset the group to **NetworkService** (default svchost group for TermService on workstations), according to policy templates, I tested.

**Comment by binarymaster** [comment]
It's possible to make RDP Wrapper update-proof by creating separate own-hosted 3rd-party service, that will start Terminal Services in its own process space.

This also will solve several other issues, like digital certificate signing (#262), scheduled auto-update (#243) and restoring missing DLLs (#194).

**Comment by affinityv** [comment]
You know what would be good?  If the server/listener can detect that it is currently in an unsupported state and to automatically run update by itself just in case an update then makes it supported and retry every 15 minutes until it finds success.  Perhaps, just perhaps, have the updater upload or download other specific files to make things work.... although it might get a bit tricky replacing files on the fly, but if the updater alone can sort it, that would be best (without needing to run it outside manually).
