### ISSUE TITLE
"Because of an error in data encryption, this session will end. Please try connecting to the remote computer again."

### ISSUE THREAD

**Issue by sipi41** [stascorp/rdpwrap#302]
Hello, I'm disconnected every 5 minutes randomly with the msg "Because of an error in data encryption, this session will end. Please try connecting to the remote computer again."... do you have any idea on why this behavior?? please help, thank you!

**Comment by binarymaster** [comment]
RDP Wrapper is not responsible for network protocol management, this could be Terminal Services bug, so contact with MS support.
