### ISSUE TITLE
Max Users with Version 1.6.1 and Windows 10 Pro

### ISSUE THREAD

**Issue by Moonage62** [stascorp/rdpwrap#304]
Windows 10 is pretty much forcing me to do the 15063 update.  Does anyone know for sure if version 1.6.1 has the 15 user limitation using Windows 10 Pro x64?

**Comment by binarymaster** [comment]
RDP Wrapper does not limit this.

**Comment by Moonage62** [comment]
Just a thank you for responding.  I guess I'll run the update this weekend.  I'm not wanting to but Windows is very pushy at this point.
