### ISSUE TITLE
Default Printer becomes unavailable almost every day

### ISSUE THREAD

**Issue by CharlieF2** [stascorp/rdpwrap#305]
I have an issue on Windows 10 Pro running RDP Wrap (the 5 client machines are running plain Windows 10) where at random times the default printers at each client terminal become unavailable (grayed out).  I have a couple of sites using RDP Wrap and this issue only happens at one site in particular.  The solution requires deleting the unavailable printer and re-installing it onto the Windows 10 Pro "server" under each user record.  This behavior is very strange and not repeating at other sites.  I'm wondering if a) anyone else is seeing this behavior and b) does anyone have a suggestion for fixing this issue?  Thanks.

**Comment by binarymaster** [comment]
I don't know how to fix that, this can be bug in Terminal Services, so you should contact MS support.

Closing as inactive about a month.
