### ISSUE TITLE
Add support for build 10.0.16278.1000

### ISSUE THREAD

**Issue by mushroom11** [stascorp/rdpwrap#307]

**Comment by lousuan** [comment]
See #194 ?

**Comment by binarymaster** [comment]
@lousuan so what? It's different issue, this build is not in the INI file yet.

**Comment by azomega** [comment]
so. in 16278.10000 i can use trick rfxvmt.dll becajseitjust not listening. butin 16278, it change to not support and not listening

**Comment by azomega** [comment]
![image](https://user-images.githubusercontent.com/6012815/30067417-f3eef1b2-9284-11e7-9a4e-b20864e31209.png)

**Comment by azomega** [comment]
next i want try tonewbuild16281

**Comment by mushroom11** [comment]
Not sure what the comments above are relating to, I just would like to know when roughly an entry will be put into RDPwrap.INI for build 16278?

**Comment by johndewood** [comment]
Here is the dll for version 10.0.16281.100
[termsrv-10.0.16281.100.zip](https://github.com/stascorp/rdpwrap/files/1281263/termsrv-10.0.16281.100.zip)
