### ISSUE TITLE
Listener is not listening on Win 10 Home (15063.540 64-bit)

### ISSUE THREAD

**Issue by permagnus** [stascorp/rdpwrap#308]
Simular to #194 , but new windows update. Seems like the use of rfxvmt.dll is removed and the solution from #194 does not work

**Comment by johnjelinek** [comment]
The solution in #194 worked for me in Win 10 Home 64-bit (same build number)

**Comment by permagnus** [comment]
Thanks. My Mistake. If I just ran update.bat as well it was alright
