### ISSUE TITLE
Listener State Not listening Windows 10

### ISSUE THREAD

**Issue by mrrfid** [stascorp/rdpwrap#310]
Experiencing the same problem as #40 with v1.6.1 on:
OS Name	Microsoft Windows 10 Home
Version	10.0.15063 Build 15063
Terminal Services version: 10.0.15063.0

RDP Wrapper Configuration ver 1.5.0.0
Listener state: Not listening

Checked firewall - OK.
Check ini - seems OK.  CR + LF on last line.

```
RDPWInst -w <Enter>
RDP Wrapper Library v1.6
Installer v2.3
Copyright (C) Stas'M Corp. 2016

[*] Checking for updates...
[*] Current update date: 2017.09.15
[*] Latest update date:  2017.09.15
[*] Everything is up to date.
```
Rebooted - problem persists.

Attached copy of termsrv.dll.  Date looks like March 18, 2017.

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1306933/termsrv.zip)

**Comment by binarymaster** [comment]
https://github.com/stascorp/rdpwrap/issues/194#issuecomment-323564111
