### ISSUE TITLE
Windows 11 Pro 10.0.22621.3672, Stopped and Not listening!!

### ISSUE THREAD

**Issue by manuel231509** [stascorp/rdpwrap#3103]
![image](https://github.com/stascorp/rdpwrap/assets/75493236/73f31d92-e396-4004-80f5-e0e92982070c)

**Comment by binarymaster** [comment]
Duplicate of #2833.

**Comment by lenkunz** [comment]
> Duplicate of #2833.

Not that duplicate. It said supported which mean they have updated the rdpwrap.ini

I suggest you to copy entire rdpwrap.ini and try again. Seems like wrapper crash at the start.
