### ISSUE TITLE
error connection 

### ISSUE THREAD

**Issue by badr258** [stascorp/rdpwrap#3128]
dont know what proplem here some time every thing ok and some time closed and get error i hope if some one can help me i try many idea from google and youtube and stay have this proplem no proplem if i pay to repire

https://github.com/stascorp/rdpwrap/assets/64976646/278fe4f6-cc47-4961-80a1-cdd6336da49a

**Comment by sashaqwert** [comment]
RDPConf not contains `termsrv.dll` version --> trolling.
