### ISSUE TITLE
Supports Windows Home x64 10.0.15063?

### ISSUE THREAD

**Issue by cdcseacave** [stascorp/rdpwrap#314]
Thanks for this useful software. It used to work fine on this same PC with same windows, but after the recent update that increased the version to 10.0.15063 it does not seem to work anymore. Is it a known problem/incompatibility?

It installs fine, RDPConf reports that it is installed, running, but the listening state is not listening.

**Comment by AlexeiScherbakov** [comment]
duplicate of https://github.com/stascorp/rdpwrap/issues/194

**Comment by cdcseacave** [comment]
sry, didn't see that old issue
