### ISSUE TITLE
Add support for 10.0.16299.15

### ISSUE THREAD

**Issue by ddt321** [stascorp/rdpwrap#316]
windows 10 home ver .10.0.16299.15 . listener state: not listening

**Comment by binarymaster** [comment]
Hello. To add this build to support, please provide both x86 and x64 `termsrv.dll` files.

**Comment by ddt321** [comment]
Hello, see attachment, 10x.
[termsrv_x86.zip](https://github.com/stascorp/rdpwrap/files/1356803/termsrv_x86.zip)

[termsrv_x64.zip](https://github.com/stascorp/rdpwrap/files/1356602/termsrv_x64.zip)

**Comment by sigma2017** [comment]
I understand. Still, I'll stick with 16299.15. I hope You will update soon. Thanks in advance!

**Comment by Titokhan** [comment]
[According to a poster in MDL](https://forums.mydigitallife.net/posts/1377008), the following changes should work on 16299.15 x64:
```
FIND : 39813C0600000F84B17D0200 
REPLACE: B80001000089813806000090

FIND : BB01000000C7 
REPLACE: BB00000000C7

FIND : 007418488D 
REPLACE: 00EB18488D
```

**Comment by priuz** [comment]
I am also getting "not listening". 
The installation script states:
[*] Terminal Services version: 10.0.15063.0
[-] This version of Terminal Services is not supported.
Both termsrv.dll are attached:
[termsrv_x64.zip](https://github.com/stascorp/rdpwrap/files/1367399/termsrv_x64.zip)
[termsrv_x86.zip](https://github.com/stascorp/rdpwrap/files/1367400/termsrv_x86.zip)

**Comment by sigma2017** [comment]
Titokhan, the solution is working perfect, just use HxD in order to edit the strings in hexa mode.
I just attached the modified file for you.
Regards
[termsrv_x64_modified.zip](https://github.com/stascorp/rdpwrap/files/1367535/termsrv_x64_modified.zip)

**Comment by velyar** [comment]
win 10 home 10.0.15063.632 "not listening" (rdpwrap 1.6.1)

**Comment by duppe** [comment]
Is there a 32 patched versjon also ?

**Comment by newfolders** [comment]
@Titokhan @sigma2017 How can I replace termsrv.dll?

**Comment by sigma2017** [comment]
Open services.msc and stop Remote Desktop Services  service

Open cmd as administrator

takeown - f c:\Windows\System32\termsrv.dll

http://qs.lc/sigma/aowx1.png
So, properties on termsrv.dll, add your user (in my case is a live account)
and check full control.

After that copy the modified dll file to over the original one

Start the Remote Desktop Services service back.

That's it!

**Comment by newfolders** [comment]
@sigma2017 Thank you very much!

**Comment by prodigy007** [comment]
not work

**Comment by sagosto** [comment]
I have the same issue. I am running 1.61 and used the X64 modified version posted by sigma2017 on Oct 9 and no workie. Help.

**Comment by prodigy007** [comment]
@sagosto 
Beginning with the Creators Update for Windows 10 Home, RDP Wrapper will no longer work, claiming that the listener is [not listening] because of rfxvmt.dll is missing - more info, download links

https://github.com/stascorp/rdpwrap

**Comment by sagosto** [comment]
Yes -- I just found that adding the missing DLL fixed it immediately.

**Comment by Mindaugas85** [comment]
Help me :( i do not understand after all what i'm doing wrong :(
termsrv 10.0.16299.15
also save with windows 1809 with latest updates
1. Installing fresh W10 Pro 1709 without updating on Hyper-V server as virtual machine.
2. downloading RDP Wrapper 1.6.2
3. extracting and running install as administration
(also tried before run - stop "termservice" in PowerShell (admin)
when installing no errors, even 1056
4. RDPCheck everything is GREEN and supported.
5. Then run RDPCheck and getting blue window: Do you want to allow remote user to connect this machiene?"...
6. Ok, when i'm making copy of termsrv.dll and with Mirkes.de Tiny Hexar changing values 
Find:
39 81 3C 06 00 00 0F 84 B1 7D 02 00
replace with:
B8 00 01 00 00 89 81 38 06 00 00 90 
saving,
running to HBCD and replacing dll file, then restarting again.
and no changes, the same...
whats wrong?

**Comment by Mindaugas85** [comment]
ON Hyper-V machine "RDPWrap" dosent work :(
on local pc everything is ok 
on Linux KVM everything works.
maybe there some issues about Hyper-V VM ? 
Because i could make multiple connections on 1809 till reboot, after this - multisession dosent work anymore and reinstall RDP wrap dosent work anymore too :((((
