### ISSUE TITLE
Multi-monitors not working. 

### ISSUE THREAD

**Issue by joe7dust** [stascorp/rdpwrap#317]
I got this so when using the RD app in android  I can access all monitors in W7 professional, but nothing seems to have changed and it still is only showing me the main monitor.

**Comment by binarymaster** [comment]
This is normal behaviour. You can't access your physical monitors with RDP, it doesn't matter how much of them on the host.

Multi-monitor feature allows to use multiple **client side** monitors - if you have two or more monitors, and connecting to a host via RDP.

An Android device have only one "monitor", so this is normal.
