### ISSUE TITLE
listener state: not listening...after Win 10 Creator update

### ISSUE THREAD

**Issue by CTBarbarin** [stascorp/rdpwrap#319]
Hi.

Thanks so much for this.  I love it...almost a necessity now.

After applying Win 10 Creator update (to Version 1703, OS Build 14063.540), I could not get RDPWrap v1.6 to listen.

I uninstalled v1.6, downloaded and installed v1.6.1...still couldn't get the new version to listen (following instructions for v1.6 found at SoftwareOK.com that I saved)

Please let me know if I am doing something wrong or if you need me to provide any more info.

Thx

**Comment by binarymaster** [comment]
See #194.

**Comment by CTBarbarin** [comment]
Thank you very much.  Worked perfect.

If I may, it took a while to find...I don't know if it is possible to link directly to @youjoy's comment...or if someone can create some instructions from his comment.

Thanks again for all of your work developing RDP Wrapper
