### ISSUE TITLE
Is there any way to connect to another user in the same system?

### ISSUE THREAD

**Issue by love-code-yeyixiao** [stascorp/rdpwrap#3198]

**Comment by binarymaster** [comment]
Use shadowing / shadow connections:
- https://t.me/rdpwrap/53254
- https://t.me/rdpwrap/75147

For more information ask in Telegram chat (not RDP Wrapper issue).

**Comment by love-code-yeyixiao** [comment]
> Use shadowing / shadow connections:
> 
> * https://t.me/rdpwrap/53254
> * https://t.me/rdpwrap/75147
> 
> For more information ask in Telegram chat (not RDP Wrapper issue).

Telegram are banned by certain governments, such as my own. How about we use Slack?
slack.com
