### ISSUE TITLE
10.0.19045.4529

### ISSUE THREAD

**Issue by aidatatech** [stascorp/rdpwrap#3211]
Thanks

**Comment by binarymaster** [comment]
RDPConf screenshot missing, termsrv.dll not attached - no evidence.

**Comment by aidatatech** [comment]
[termsrv.zip](https://github.com/user-attachments/files/15901333/termsrv.zip)

**Comment by binarymaster** [comment]
> termsrv.zip

termsrv.dll version 10.0.19041.4474

Duplicate of #2840.

**Comment by aidatatech** [comment]
Exactly, problem solved, thanks.
