### ISSUE TITLE
10.0.22621.3737not supported

### ISSUE THREAD

**Issue by connie-cc** [stascorp/rdpwrap#3218]
Hi there,
Thanks as always for keep in up the project.
I got not supported for 10.0.22621.3737.
Can you help me?

**Comment by benrojas01** [comment]
![Captura de pantalla 2024-06-28 094610](https://github.com/stascorp/rdpwrap/assets/32991065/dc0e5a26-b861-4f3b-b600-c088f98ce8b6)

**Comment by benrojas01** [comment]
[termsrv.zip](https://github.com/user-attachments/files/16032340/termsrv.zip)

**Comment by binarymaster** [comment]
Cleaned up unrelated messages.

**Comment by loyejaotdiqr47123** [comment]
?
In the system version 19041.3737 the termsrv version is indeed 19041.3672.

**Comment by loyejaotdiqr47123** [comment]
So Duplicate of #2833
