### ISSUE TITLE
Build 10.0.20348.2520 (server 2022 ver. 10348.2527)

### ISSUE THREAD

**Issue by Mariojd1980** [stascorp/rdpwrap#3221]
Buen dia, actualizo windows a la version 10348.2527 de windows server 2022 datacenter y no puedo conectar mas de 2 usuario, alguien podria ayudarme por favor.?

**Comment by loyejaotdiqr47123** [comment]
Please, attach your RDPConf screenshot and termsrv.dll.

**Comment by Mariojd1980** [comment]
ahi adjunto captura y el archivo termsrv
![Sin título](https://github.com/stascorp/rdpwrap/assets/174464448/da6bc55a-a1aa-45e5-9985-3f036718c3d6)
[termsrv.zip](https://github.com/user-attachments/files/16070176/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment]
[https://github.com/sebaxakerhtc/rdpwrap.ini/commit/3ca095924ce99837d8c93d50cec3a9b136736969](https://github.com/sebaxakerhtc/rdpwrap.ini/commit/3ca095924ce99837d8c93d50cec3a9b136736969)

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/3199.

**Comment by Mariojd1980** [comment]
Solucionó el problema, muchas gracias
