### ISSUE TITLE
Access is denied on install.bat.

### ISSUE THREAD

**Issue by saladnoob** [stascorp/rdpwrap#3222]
![lmao help](https://github.com/stascorp/rdpwrap/assets/172288841/a074116b-88b3-40bd-9394-8609122313d9)

idk how stuff like this works but when i try to run install.bat as admin it just said "Access is denied.". Please help :////////////

**Comment by saladnoob** [comment]
this maybe important

![image](https://github.com/stascorp/rdpwrap/assets/172288841/b0821d96-84a0-4c27-b531-0f6f467f87e9)

**Comment by binarymaster** [comment]
Resolve your antivirus problem, not RDP Wrapper issue.

**Comment by Samuel19019** [comment]
I have the same issue di you found a solution (I tried to disable my antivirus but it doesn't work)

**Comment by binarymaster** [comment]
Use Telegram chat for getting support.
