### ISSUE TITLE
July 9th Windows 22621.3880



### ISSUE THREAD

**Issue by wrightflyer** [stascorp/rdpwrap#3227]
M$ released 22621.3880 a few days ago. My miniPC that I use Rdpwrap on is showing signs of trying to download the update. Any chance for a set of JSON settings to add the file so it will continue to work with 3880? Thanks.

**Comment by binarymaster** [comment]
RDPConf screenshot missing, termsrv.dll not attached - no evidence.

**Comment by wrightflyer** [comment]
Hi, sorry but it's not clear what info you need to explore this? There is no question that M$ definitely made a new release of Windows 11 on July 9th.. 

![win11](https://github.com/user-attachments/assets/1e0ef0e0-60d5-4539-a60d-b71f5ec34022)

are you saying I need to let it apply the update and then take a copy of termsrv.dll out of it ? The thing is that my miniPC, that I RDP to, is quite inaccessible and if I let it update and lose RDP then it could be quite tricky to contact it.

**Comment by RalfB66** [comment]
![image](https://github.com/user-attachments/assets/4bef0ec1-811b-40de-ada9-9be18aeee409)
![image](https://github.com/user-attachments/assets/c390377e-7989-4347-a798-1981a45bf13c)
[termsrv.zip](https://github.com/user-attachments/files/18264499/termsrv.zip)
