### ISSUE TITLE
拒绝访问

### ISSUE THREAD

**Issue by zyjjack** [stascorp/rdpwrap#3230]
﻿拒绝访问。
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

请按任意键继续. . .

**Comment by loyejaotdiqr47123** [comment]
?杀软关了没

**Comment by FiendFEARing** [comment]
管理员权限运行

**Comment by binarymaster** [comment]
Duplicate of #1417. Check your antivirus.

Non-english issues not allowed.
