### ISSUE TITLE
Windows 11 Pro 10.0.22621.3880 RDP Wrapp not correctly check win version and not supported

### ISSUE THREAD

**Issue by aarpro** [stascorp/rdpwrap#3233]
RDP Wrapper not correctly checks the version Win11 and not supported
a you help me ?
![2024-07-20_125358](https://github.com/user-attachments/assets/d2660833-a88a-4b30-be0e-6f6184757fed)
![2024-07-20_125334](https://github.com/user-attachments/assets/f00368a4-54d4-4404-8088-7348bc7f7782)

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2833.
