### ISSUE TITLE
10.0.15063.0 not supported

### ISSUE THREAD

**Issue by lenew** [stascorp/rdpwrap#324]
after last auto update i have termsrv of version 10.0.15063.0 installed. RDP Wrapper stops work even after multiple times of update and reinstall.
please help.
-----------------------------------------------------------------
RDP Wrapper Library v1.6
Installer v2.3
Copyright (C) Stas'M Corp. 2016

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.15063.0
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[+] TermService found (pid 2636).
[*] No shared services found.
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[*] Downloading latest INI file...
[+] Latest INI file -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting TermService...
[*] Configuring registry...
[*] Configuring firewall...

[+] Successfully installed.
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1393433/termsrv.zip)

**Comment by binarymaster** [comment]
This duplicates #315.

**Comment by lenew** [comment]
https://github.com/stascorp/rdpwrap/issues/194#issuecomment-323564111
this method work for me
