### ISSUE TITLE
10.0.17763.6054(winver) not supported

### ISSUE THREAD

**Issue by PXXHWJ** [stascorp/rdpwrap#3247]
Hi, please check this version.
![notsupported](https://github.com/user-attachments/assets/7c822af6-9b6f-47c0-bb4b-99402606d582)
[termsrv.zip](https://github.com/user-attachments/files/16454816/termsrv.zip)

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2622.
