### ISSUE TITLE
10.0.19045.4651  not supportad

### ISSUE THREAD

**Issue by kedalin-ya** [stascorp/rdpwrap#3249]
![image](https://github.com/user-attachments/assets/fc65a876-1f55-400f-af8d-13ab107a8f1f)

Hello, I require the rdpwrap.ini file for version 19045.4651. I'm currently unable to locate this specific version. I hope someone can assist me. Thank you.

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2840.
