### ISSUE TITLE
Exception EAccessViolation in module kernel32.dll at 00012114

### ISSUE THREAD

**Issue by MinistrBob** [stascorp/rdpwrap#325]
Windows Server 2008 SE SP2.

Run install.bat

`RDP Wrapper Library v1.6
Installer v2.3
Copyright (C) Stas'M Corp. 2016

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 6.0.6002.19214
[+] This version of Terminal Services is fully supported.
[+] TermService found (pid 832).
[*] Shared services found: CryptSvc, Dnscache, KtmRm, NlaSvc, Wecsvc, WinRM
[*] Extracting files...
[*] Downloading latest INI file...
Exception EAccessViolation in module kernel32.dll at 00012114.
Access violation at address 76812114 in module 'kernel32.dll'. Read of address 0
0184000.

______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.`

**Comment by binarymaster** [comment]
Does the installer work without online mode?

**Comment by MinistrBob** [comment]
Yes, internet is absent

**Comment by MinistrBob** [comment]
Thanks for a suggestive question.
I solved the problem by running the installation as 
`c:\RDPWrap\RDPWInst.exe -i`
in command line

**Comment by sebaxakerhtc** [comment]
Closed as solved
