### ISSUE TITLE
10.0.19045.4780 not supported

### ISSUE THREAD

**Issue by shaoxiao-li** [stascorp/rdpwrap#3254]

**Comment by loyejaotdiqr47123** [comment]
Please, attach your RDPConf screenshot and termsrv.dll.

**Comment by TeFuirnever** [comment]
![image](https://github.com/user-attachments/assets/dbfa8c52-8f00-4603-9e93-58d651fb23de)

**Comment by zicren** [comment]
![RDPConf screenshot](https://github.com/user-attachments/assets/fc794ac5-5ed3-4bb7-836d-d5a1b17c5a53)

**Comment by zicren** [comment]
Hello, this version (10.0.19045.4780) is not supported after latest updates Windows server 2022
[termsrv.zip](https://github.com/user-attachments/files/16649647/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment]
> Hello, this version (10.0.19045.4780) is not supported after latest updates Windows server 2022 [termsrv.zip](https://github.com/user-attachments/files/16649647/termsrv.zip)

Duplicate of #2840
