### ISSUE TITLE
10.0.22621.3672 not supported

### ISSUE THREAD

**Issue by kotarbamateusz** [stascorp/rdpwrap#3256]
Hello, Is there any solution for that?
I'm here from youtube
https://www.youtube.com/watch?v=WQYW1vxv6nI
and stuck on 3:43.

![image](https://github.com/user-attachments/assets/b53603f0-d603-4784-a948-7d05b74f0b8a)

My Windows version.
![image](https://github.com/user-attachments/assets/5f7d79a7-bfa0-4fde-afe9-3fef5ba57692)

**Comment by loyejaotdiqr47123** [comment]
Duplicate of #2833
