### ISSUE TITLE
i need help with my rdp its saying access denied when i try to log in 

### ISSUE THREAD

**Issue by frootloops954** [stascorp/rdpwrap#3257]
![Screenshot 2024-08-19 145012](https://github.com/user-attachments/assets/13531f6b-6673-467e-97f0-9a48d585e7c0)

**Comment by loyejaotdiqr47123** [comment]
Please, attach your termsrv.dll.

**Comment by frootloops954** [comment]
how do i do that?

**Comment by binarymaster** [comment]
Solution is in README: https://github.com/stascorp/rdpwrap/issues/215#issuecomment-285862688
