### ISSUE TITLE
Can't log in with the same session

### ISSUE THREAD

**Issue by iscas-zac** [stascorp/rdpwrap#3259]
Hello, I installed [sebaxakerhtc's rdpwrap](https://github.com/sebaxakerhtc/rdpwrap) for convenience, but recently the RDP stops allowing me to log in with the same session as the remote one, without red lines in the panel. I have to log in with a different session and some software like MS Edge seems not able to open in that session.

Here is the RDPWrap panel with "single session per user" unchecked. The symptom with it checked is similar to https://github.com/stascorp/rdpwrap/issues/3257, where after I enter the password, the session would be stuck at the log-in page and abort the session (or just stuck? I'm away from that remote computer now, and if more information is needed I will post the screenshot for that later).

![image](https://github.com/user-attachments/assets/0bfe88b6-f54c-4dfe-9ac8-8f21d278f98d)

Here is the `termsrv.dll` I obtain from `C:\Windows\System32` (I'm not sure if this is the needed one), with a simple suffix addition `.docx` as the site doesn't allow a `.dll` file.

[termsrv.dll.docx](https://github.com/user-attachments/files/16722624/termsrv.dll.docx)

**Comment by hasnatkhan786** [comment]
Hi, 
My question is not related to this post but the question is related to RDP session time. How can I extend the session time? My RDP last for 40 minutes. I connected NGROK token. [😶](https://balloonslane.com/brooklyn-balloons/)

**Comment by binarymaster** [comment]
@hasnatkhan786 this is a bugtracker, questions unrelated to the ticket must go to RDPWrap Telegram support group.

**Comment by iscas-zac** [comment]
Hello guys, the problem can be solved by toggling 'session shadowing mode' to one of the 'full access' items. Probably I mis-clicked the wrong option before.
