### ISSUE TITLE
Fall creator update new behavior with concurrent sessions

### ISSUE THREAD

**Issue by endmarsfr** [stascorp/rdpwrap#326]
Hello, 

Since I updated my workstation with latest windows 10 (V 1709 16299.19 - Fall creator update)
When I connect to the distant machine, the distant session is disconnected. I succeed to connect to the remote machine, and the distant machine need to reconnect.

Before fall creator update, I was able to  connect to the distant machine without disconnecting the remote host.
I have this new behavior on windows 10 (x64) home and pro versions.
rfxvmt.dll (from my pro version) is versionned now to 10.0.16299.15
I have the same behavior with a previous version of rfxvmt.dll

Of course, fSingleSessionPerUser   is set to 0 
and "single session per user" is uncheked

Is it possible to reverse back to previous behavior with the latest windows 10 upgrade ? 

regards

**Comment by endmarsfr** [comment]
A workaround not fully satisfaying : create an another account and log in

**Comment by XUnderShadow** [comment]
Works if you leave like in pic
![068](https://user-images.githubusercontent.com/33500385/32577640-5c5a924a-c4b9-11e7-8fb2-46c6a992f434.png)

**Comment by endmarsfr** [comment]
Hello XUnderShadow, 

Unfortunatelly, it is not working for me. 

As you can see, I have the same settings in rdpconf gui.
![rdp](https://user-images.githubusercontent.com/21008405/32606764-db58d4f6-c556-11e7-8a88-7a3a93f3a84c.jpg)

But can you please tell me what are your settings in the rdpwrap.ini file.
here are mine :

[Main]
Updated=2017-10-13
LogFile=\rdpwrap.txt
SLPolicyHookNT60=1
SLPolicyHookNT61=1

[SLPolicy]
TerminalServices-RemoteConnectionManager-AllowRemoteConnections=1
TerminalServices-RemoteConnectionManager-AllowMultipleSessions=1
TerminalServices-RemoteConnectionManager-AllowAppServerMode=1
TerminalServices-RemoteConnectionManager-AllowMultimon=1
TerminalServices-RemoteConnectionManager-MaxUserSessions=0
TerminalServices-RemoteConnectionManager-ce0ad219-4670-4988-98fb-89b14c2f072b-MaxSessions=0
TerminalServices-RemoteConnectionManager-45344fe7-00e6-4ac6-9f01-d01fd4ffadfb-MaxSessions=2
TerminalServices-RDP-7-Advanced-Compression-Allowed=1
TerminalServices-RemoteConnectionManager-45344fe7-00e6-4ac6-9f01-d01fd4ffadfb-LocalOnly=0
TerminalServices-RemoteConnectionManager-8dc86f1d-9969-4379-91c1-06fe1dc60575-MaxSessions=1000
TerminalServices-DeviceRedirection-Licenses-TSEasyPrintAllowed=1
TerminalServices-DeviceRedirection-Licenses-PnpRedirectionAllowed=1
TerminalServices-DeviceRedirection-Licenses-TSMFPluginAllowed=1
TerminalServices-RemoteConnectionManager-UiEffects-DWMRemotingAllowed=1

**Comment by XUnderShadow** [comment]
strange
it's working on at least 5 of my machines x64 and x86
try uninstalling rdwrap restart install rdwrap - set as shown - restart

**Comment by XUnderShadow** [comment]
BTW i never touched  rdpwrap.ini

**Comment by endmarsfr** [comment]
Unfortunatelly, it is not working for me even uninstalling / reinstall/reststart :(
