### ISSUE TITLE
Not Able to connect with remote computer after installing RDP Warpper in win11 home

### ISSUE THREAD

**Issue by Yogesh24Guleria** [stascorp/rdpwrap#3265]
Hello everyone cant get the program rdp wrapper to work. I gotten everything to go green on check but not able to connect remote server. 
![Screenshot 2024-09-04 122026](https://github.com/user-attachments/assets/1ed10c81-1723-4a93-b81c-7547aa633384)
![Screenshot 2024-09-04 121451](https://github.com/user-attachments/assets/826d697b-79f7-4d43-8b9f-2363f997f363)

**Comment by binarymaster** [comment]
Does not look like a valid bug report, contact RDPWrap Telegram chat for help instead.
