### ISSUE TITLE
10.0.22631.4037 not supported #3253

### ISSUE THREAD

**Issue by bellodku** [stascorp/rdpwrap#3267]
Windows 11 22631.4037 show not support
it would be updated at 19 July 2024

please help

**Comment by bellodku** [comment]
![image](https://github.com/user-attachments/assets/d01a1529-3ec3-4f18-95b0-381c328004b6)
[termsrv.zip](https://github.com/user-attachments/files/16921953/termsrv.zip)

**Comment by binarymaster** [comment]
Duplicate of #3238.
