### ISSUE TITLE
how to fix?

### ISSUE THREAD

**Issue by isotiredqq** [stascorp/rdpwrap#3271]
![image](https://github.com/user-attachments/assets/c62165a9-9ec1-4e54-ad67-0e4201bbc090)

**Comment by binarymaster** [comment]
> Not installed

Just install the wrapper. Not a valid bug report.

**Comment by isotiredqq** [comment]
![Uploading fix5.png…]()

**Comment by isotiredqq** [comment]
![fix5](https://github.com/user-attachments/assets/024d6599-e183-4a0f-a677-fd2a93718c33)
