### ISSUE TITLE
cannot work on modified windows 11 (26100)

### ISSUE THREAD

**Issue by sodapisuki** [stascorp/rdpwrap#3272]
although i have fixed the Termservice,it still does not work.

-----------------install.bat------------------
[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.26257.5000
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[*] Configuring TermService...
[*] Starting TermService...
[-] StartService error (code 1053).
[-] Failed to set up TermService. Unknown error.

---------------update.bat----------------------
[*] RDP Wrapper Library is not installed.

i am so sorry that i cant provide the system image because of the difficulty of uploading
i will try to do so if you do need it

**Comment by binarymaster** [comment]
Fix your antivirus behavior, not RDP Wrapper problem.

**Comment by sodapisuki** [comment]
but i just installed Edge and VMware
EVEN THE SYSTEM IS NEW-INSTALLED
