### ISSUE TITLE
10.0.19045.4894 on Windows 10 22H2

### ISSUE THREAD

**Issue by JamesWuBest** [stascorp/rdpwrap#3276]
I can't find any ini file info, can anyone got the same winver 10.0.19045.4894 for rdpwrap.ini

**Comment by loyejaotdiqr47123** [comment]
Please, attach your RDPConf screenshot and termsrv.dll.

**Comment by Dywa-Lee** [comment]
![image](https://github.com/user-attachments/assets/0943be91-0814-49bd-8665-7a58d85b7104)

[termsrv.zip](https://github.com/user-attachments/files/17149789/termsrv.zip)

**Comment by Dywa-Lee** [comment]
> Please, attach your RDPConf screenshot and termsrv.dll.
![image](https://github.com/user-attachments/assets/04c1a421-6da7-4ec5-94f8-e37c80c5a60a)

[termsrv.zip](https://github.com/user-attachments/files/17157260/termsrv.zip)

**Comment by JamesWuBest** [comment]
https://github.com/stascorp/rdpwrap/issues/2840

I replaced termsrv.dll according to the content in this article and it can be used

![企业微信截图_17273987251433](https://github.com/user-attachments/assets/9be87119-6981-48bc-8bc0-dfe7f6e85902)

**Comment by Dywa-Lee** [comment]
I think it's better to modify the same termsrv.dll file then to replace it,  will be more stabler?

**Comment by JamesWuBest** [comment]
> I think it's better to modify the same termsrv.dll file then to replace it, will be more stabler?

I think so. but it seems like no support version 10.0.19045.4894, it's too new

**Comment by bhattji** [comment]
> #2840
> 
> I replaced termsrv.dll according to the content in this article and it can be used
> 
> ![企业微信截图_17273987251433](https://private-user-images.githubusercontent.com/92191362/371357479-9be87119-6981-48bc-8bc0-dfe7f6e85902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NTkxNjQsIm5iZiI6MTcyNzc1ODg2NCwicGF0aCI6Ii85MjE5MTM2Mi8zNzEzNTc0NzktOWJlODcxMTktNjk4MS00OGJjLThiYzAtZGZlN2Y2ZTg1OTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDA1MDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMzQ3MmMxZGM4YjQxMTBmY2M1ZTM5Yjk1MTZlYzM0YmY0ZjdmYjQyNTVmYjA3Y2VlMmUyZDIxNDAwNTgxNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0zh4TkClAOjNJ0yLrALQt0qZnVmV4pPCCrlPqX1NzCM)

Can you please give link to download ini file?
