### ISSUE TITLE
Microsoft Windows ver 10.0.19045.4894 Not supported

### ISSUE THREAD

**Issue by nomoneynolife** [stascorp/rdpwrap#3279]
![image](https://github.com/user-attachments/assets/151301ee-ed3b-4644-8571-b101a47847d6)

[rdpwrap.zip](https://github.com/user-attachments/files/17146383/rdpwrap.zip)

thank you!

need new rdpwrap.ini

**Comment by binarymaster** [comment]
Duplicate of #3276.
