### ISSUE TITLE
not supported. win 11 23H2 build 22631

### ISSUE THREAD

**Issue by LLIILLEEDD** [stascorp/rdpwrap#3281]
after optional cumulative update KB5043145 windows build 22631 rdp wrapper does not work. helped to remove the update
![image](https://github.com/user-attachments/assets/a7827b25-c4b8-486f-8ece-9acbd5e316ba)

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/3280.
