### ISSUE TITLE
no working in 22631.4249

### ISSUE THREAD

**Issue by RodolfoBigues** [stascorp/rdpwrap#3282]
RDP Black no Work in 22631.4249 windows 11 pro has update at 03:00 and no support file rdp.ini file update need asap

**Comment by RodolfoBigues** [comment]
retip the compilation version In Windows 11 Pro Version 23H2 (Compilación SO 22631.4249) not supported

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/3280.
