### ISSUE TITLE
 not listening

### ISSUE THREAD

**Issue by rromz** [stascorp/rdpwrap#329]
after update my windows 10 x64 home i couldn't find termsrv.dll in windows\system32

**Comment by rromz** [comment]
update 1703

**Comment by rromz** [comment]
service state 10.0.15063.0

**Comment by rromz** [comment]
no one issuses not work for me

**Comment by binarymaster** [comment]
How I can help you? Search and download that DLL.

**Comment by rromz** [comment]
I finded in Issues this dll and copied into system32 but its not helped me.

**Comment by rromz** [comment]
Maybe there are some other elements to check. The program worked fine until the update. if there were failures, then all the advice from here helped. But not at this time
