### ISSUE TITLE
RDP wrap not listening but is fully supported

### ISSUE THREAD

**Issue by lorenzo-lau** [stascorp/rdpwrap#3291]
I tried uninstalling and reinstalling the RDP and I still can't figure out how to fix it, im not sure how to fix it 
![image](https://github.com/user-attachments/assets/a35a02d2-ba6b-4f08-bb23-e599b0c39e73)

**Comment by loyejaotdiqr47123** [comment]
Please, attach your RDPConf screenshot and termsrv.dll.
