### ISSUE TITLE
Win 11 10.0.22621.4249 supported but not listening

### ISSUE THREAD

**Issue by Illusion97** [stascorp/rdpwrap#3300]
I am having trouble getting it to listen. I got updated INI info from another thread. Have tried running update, restarting services, and restarting computer. I have also attached termsrv.
![image_2024-10-11_105519478](https://github.com/user-attachments/assets/196888bf-a0cc-4dfe-8483-e9a45bab7093)

[termsrv.zip](https://github.com/user-attachments/files/17344222/termsrv.zip)

**Comment by bohaoist** [comment]
this issues may help:  
https://github.com/stascorp/rdpwrap/issues/3280

**Comment by Illusion97** [comment]
> this issues may help: #3280

This is the thread which I got the INI info from. I have also tried putting the exe back into the directory specified but it did not help.

**Comment by bohaoist** [comment]
> > this issues may help: #3280
> 
> This is the thread which I got the INI info from. I have also tried putting the exe back into the directory specified but it did not help.

you put ini in wrong place, it should be replaced the old ini file, which path is "C:\Program Files\RDP Wrapper", and then restart the Remote Desktop Services(or just restart the computer)
you can download new ini here: https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

**Comment by Illusion97** [comment]
> > > this issues may help: #3280
> > 
> > 
> > This is the thread which I got the INI info from. I have also tried putting the exe back into the directory specified but it did not help.
> 
> you put ini in wrong place, it should be replaced the old ini file, which path is "C:\Program Files\RDP Wrapper", and then restart the Remote Desktop Services(or just restart the computer) you can download new ini here: https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

This worked thank you. I suppose I put the new lines in the wrong spot in the file, because the location you mentioned was where I changed the ini. Thanks!
