### ISSUE TITLE
Win 11, ver 10.0.22621.4229 not working

### ISSUE THREAD

**Issue by vc007-git** [stascorp/rdpwrap#3301]
The wrapper did stop 2 days ago. ver 10.0.22621.4229
RDPConf says Not listening and Not supported.
Tried to reinstall with no result.
![rdp](https://github.com/user-attachments/assets/e3dac7b0-3aef-47c1-ab6d-dc2c299153fd)

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/3280.
