### ISSUE TITLE
Windows 11 PRO 24H2 OS BUILD 10.0.26100.2033 - Cannot connect 

### ISSUE THREAD

**Issue by dayspring-dev** [stascorp/rdpwrap#3303]
[rdpwrap_10.0.22621.4249.txt](https://github.com/user-attachments/files/17345635/rdpwrap_10.0.22621.4249.txt)
[termsrv-10.0.26100.2033.zip](https://github.com/user-attachments/files/17345569/termsrv-10.0.26100.2033.zip)
![Window_11_Pro_10 0 26100 2033](https://github.com/user-attachments/assets/b86ea14f-596d-4857-a944-aa67639c0269)
![RDPWrapperConfig](https://github.com/user-attachments/assets/55769fc1-4590-4d93-a598-a186914db0a2)
![LimittedConnectionCannotConnect](https://github.com/user-attachments/assets/0df8afa0-f8a3-44ad-aab8-b73410757b76)

**Comment by binarymaster** [comment]
Attached termsrv.dll archive file doesn't seem to be valid.
