### ISSUE TITLE
Windows 11 PRO 24H2 OS BUILD 10.0.26100.2033 installed latest rdpwrap.ini not working

### ISSUE THREAD

**Issue by dayspring-dev** [stascorp/rdpwrap#3305]
### I installed the new rdpwrap.ini from the link below
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/e358a0441a5c1c965e8889a77256a5e0298c06a8
### I am still seeing this issue
![LimittedConnectionCannotConnect](https://github.com/user-attachments/assets/cde77ead-4baf-44ad-b8d2-14606b06b563)
![Window_11_Pro_10 0 26100 2033](https://github.com/user-attachments/assets/7ce1cb9a-c589-473a-a12b-7dbcb0765cfd)
![RDPWrapperConfig](https://github.com/user-attachments/assets/c3feaa76-c712-4791-9c00-d369017aa1f8)
[termsrv-10.0.26100.2033.zip](https://github.com/user-attachments/files/17347621/termsrv-10.0.26100.2033.zip)

**Comment by binarymaster** [comment]
> Wrapper state: Not installed

How do you expect the software to work if it's not installed?

**Comment by franciscoalcibar** [comment]
[10.0.26100.1882]
SingleUserPatch.x64=1
SingleUserOffset.x64=9778B
SingleUserCode.x64=mov_eax_1_nop_2
DefPolicyPatch.x64=1
DefPolicyOffset.x64=94BAF
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx_jmp
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8ADA1
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=AB430
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.26100.1882-SLInit]
bServerSku.x64=11ADF4
bRemoteConnAllowed.x64=11AE08
bFUSEnabled.x64=11AE18
bAppServerAllowed.x64=11AE00
bMultimonAllowed.x64=11AE0C
lMaxUserSessions.x64=11ADF8
ulMaxDebugSessions.x64=11AE14
bInitialized.x64=11ADF0

**Comment by dayspring-dev** [comment]
It is working now Thank You

**Comment by hckrstudent** [comment]
Mine is still not working. Please help me!
![Screenshot_20241021_084210_Chrome](https://github.com/user-attachments/assets/c055f1cc-5e72-4b49-b8fb-a3d282c4347e)
![Screenshot_20241021_085100_Chrome](https://github.com/user-attachments/assets/50c0230c-3972-4080-aed9-b53f5d5d9ada)

**Comment by TheRulokat** [comment]
> [10.0.26100.1882] SingleUserPatch.x64=1 SingleUserOffset.x64=9778B SingleUserCode.x64=mov_eax_1_nop_2 DefPolicyPatch.x64=1 DefPolicyOffset.x64=94BAF DefPolicyCode.x64=CDefPolicy_Query_eax_rcx_jmp LocalOnlyPatch.x64=1 LocalOnlyOffset.x64=8ADA1 LocalOnlyCode.x64=jmpshort SLInitHook.x64=1 SLInitOffset.x64=AB430 SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.26100.1882-SLInit] bServerSku.x64=11ADF4 bRemoteConnAllowed.x64=11AE08 bFUSEnabled.x64=11AE18 bAppServerAllowed.x64=11AE00 bMultimonAllowed.x64=11AE0C lMaxUserSessions.x64=11ADF8 ulMaxDebugSessions.x64=11AE14 bInitialized.x64=11ADF0

What will I replace this with?

**Comment by laxminmankrishna** [comment]
Dear team plz provide full link of software(code)
windows11 pro-10.0.26100.2033 and updated link

**Comment by laxminmankrishna** [comment]
windows 10 home single also
