### ISSUE TITLE
winver 1607 build 1770

### ISSUE THREAD

**Issue by ukrray** [stascorp/rdpwrap#331]
![213](https://user-images.githubusercontent.com/32977510/31852155-7223e7ee-b67b-11e7-8ffb-f855689e7dde.jpg)
![rdp2](https://user-images.githubusercontent.com/32977510/31852156-7596d45e-b67b-11e7-9b8b-1346776ae8de.jpg)

Update.bat not work

Help pls
New Update

**Comment by binarymaster** [comment]
Follow this tutorial:

http://www.youtube.com/watch?v=W9BpbEt1yJw

**Comment by ukrray** [comment]
Thank you
