### ISSUE TITLE
Windows Server 2022 Datacenter solo admite 2 usuarios

### ISSUE THREAD

**Issue by Mariojd1980** [stascorp/rdpwrap#3319]
Buen dia, necesito ayuda por favor, rdp wrapper esta todo en verte pero no permite conetar mas de 2 usuario, adjunto archivos y capturas. desde ya muchas gracias por la ayuda.
[Archivos.zip](https://github.com/user-attachments/files/17509409/Archivos.zip)

**Comment by binarymaster** [comment]
Duplicate of #3315.
