### ISSUE TITLE
cannt uninstall on windows 10 home, showing access denied.

### ISSUE THREAD

**Issue by possaashton** [stascorp/rdpwrap#332]
![capture 1](https://user-images.githubusercontent.com/33058710/31941720-679c5f4c-b8e0-11e7-944b-059d7e42777f.PNG)
![capture](https://user-images.githubusercontent.com/33058710/31941721-67ee9fb4-b8e0-11e7-9cfe-5fd70811f364.PNG)

please help me.

**Comment by binarymaster** [comment]
Antivirus? Add to exclusions?

**Comment by possaashton** [comment]
sir,
i dont have any idea of this software. yes i have McAfee antivirus.

**Comment by binarymaster** [comment]
If you have no idea how to add something to exclusions, then get a rid of antivirus software.

**Comment by possaashton** [comment]
sir,
i uninstalled the antivirus, still it is showing no access.
can you please connect to my PC via teamviewer and resolve my problem.

**Comment by binarymaster** [comment]
Ok, let's see, give me IDs

**Comment by possaashton** [comment]
ID : 227 102 156
password: 1031

**Comment by possaashton** [comment]
Thankyou soooo much sir.

**Comment by binarymaster** [comment]
Issue resolved, what was done:
1. Disable McAfee antivirus
2. Download the release again and unpack to different folder
3. Install `rfxvmt.dll` (see https://github.com/stascorp/rdpwrap/issues/194#issuecomment-325627235)
4. Re-install RDP Wrapper

**Comment by possaashton** [comment]
thankyou soooooo much sir

**Comment by possaashton** [comment]
sir,
i want to uninstall it from my computer.
and also want to delete the folder, but its not getting deleted

**Comment by binarymaster** [comment]
I think you'll be able to delete it after reboot.

**Comment by possaashton** [comment]
complete OS reboot..?

**Comment by binarymaster** [comment]
Yes. Also try disabling McAfee for longer period (so it doesn't turn on when OS boots).

**Comment by binarymaster** [comment]
If that doesn't help, try granting access and changing permissions on blocked files.

**Comment by possaashton** [comment]
will i have to re install OS again.?

**Comment by binarymaster** [comment]
No.

**Comment by possaashton** [comment]
then i just have to re_start right...?

**Comment by binarymaster** [comment]
Yes. Restart == Reboot

**Comment by possaashton** [comment]
okay after restart what should i do..?

**Comment by binarymaster** [comment]
Use `uninstall.bat` from that second folder.

**Comment by possaashton** [comment]
okay,
i will restart the system and then give you my teamviewer id again.

**Comment by possaashton** [comment]
id : 227 102 156
password : 7123

**Comment by possaashton** [comment]
thankyou sir.

**Comment by binarymaster** [comment]
Wiped out clean.
