### ISSUE TITLE
10.026100.1

### ISSUE THREAD

**Issue by samgh-noob** [stascorp/rdpwrap#3326]
RDP Warper not supported on windows 11 10.026100.1 , Termsrv attached bellow

![image](https://github.com/user-attachments/assets/1e8d8b32-1292-4567-9185-340755a83b05)

[termsrv.zip](https://github.com/user-attachments/files/17601174/termsrv.zip)

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2543.

**Comment by samgh-noob** [comment]
Please reopen it , this issue isn't duplicate anymore 
and before #2543 page was deleted , I changed ini file and didn't work for me
I still have problem with that

**Comment by binarymaster** [comment]
> I changed ini file and didn't work for me
I still have problem with that

Contact Telegram support instead, at this point this is a user problem.
