### ISSUE TITLE
cannnot uninstall RDPwrap, showing access denied.

### ISSUE THREAD

**Issue by possaashton** [stascorp/rdpwrap#333]
![capture 1](https://user-images.githubusercontent.com/33058710/31943648-f502652e-b8e6-11e7-9482-db66316227e1.PNG)
![capture](https://user-images.githubusercontent.com/33058710/31943649-f54e8882-b8e6-11e7-81c6-08a1c5714510.PNG)
 please help me via teamviewer..

**Comment by binarymaster** [comment]
Duplicate of #332.
