### ISSUE TITLE
listener state NOT LISTENING win 11 64bit 10.0.22621.4249

### ISSUE THREAD

**Issue by Hs-33** [stascorp/rdpwrap#3333]
![image](https://github.com/user-attachments/assets/f9938123-4702-497b-ab72-cb407112ec44)

I changed the rdpwrap.ini to the script of matching version so i fixed the [not supported] problem. but the listener state is still NOT LISTENING

**Comment by Hs-33** [comment]
I just fixed this issue. 
i changed Program Files/RDP Wrapper/rdpwrap.ini to [https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini](url)
and rebooted

**Comment by krishnaprabhu2304** [comment]
script not available

**Comment by binarymaster** [comment]
You have done something wrong, this is not covered by GitHub issues, contact Telegram support chat instead.

**Comment by Hs-33** [comment]
> script not available
sorry about the another issue
i got the rdpwwrap.ini file from here
[https://github.com/sebaxakerhtc/rdpwrap.ini.git](url)

**Comment by Hs-33** [comment]
https://github.com/sebaxakerhtc/rdpwrap.ini

idk why the script isn't available.  you should copy and paste this link and get the rdpwrap.ini file. i think this will work
