### ISSUE TITLE
version not supported windows 11  version 23h2 . os build 22631.4317

### ISSUE THREAD

**Issue by krishnaprabhu2304** [stascorp/rdpwrap#3334]
version not supported windows 11  version 23h2 . os build 22631.4317
![Rdwrapper issue](https://github.com/user-attachments/assets/d309b249-bc3d-479f-91ea-aa5b0b84ab9f)

**Comment by binarymaster** [comment]
Issue title does not match termsrv version on screenshot => invalid ticket.

**Comment by ccwb05080** [comment]
那怎么办 有没有大佬
