### ISSUE TITLE
Win11pro 22631.4460 1000.22700.1047.0 Not Supported

### ISSUE THREAD

**Issue by Jamesun921** [stascorp/rdpwrap#3347]
![image](https://github.com/user-attachments/assets/b4491a73-6a34-40d1-9d5d-b133987e1aaa)
[termsrv.zip](https://github.com/user-attachments/files/17770360/termsrv.zip)

**Comment by binarymaster** [comment]
Issue title does not match the version on screenshot => invalid.

10.0.22621.4391 is tracked in https://github.com/stascorp/rdpwrap/issues/3316 => duplicate.
