### ISSUE TITLE
Windows 10 SO 19045.5131 dont work

### ISSUE THREAD

**Issue by Hector-Alvarado** [stascorp/rdpwrap#3357]

**Comment by binarymaster** [comment]
No RDPConf screenshot, no evidence => invalid.

**Comment by Impr0ve** [comment]
![Screenshot 2024-12-05 011628](https://github.com/user-attachments/assets/a040ae23-0961-4ff3-b0d0-204ef3c8c7ad)
![Screenshot 2024-12-05 012649](https://github.com/user-attachments/assets/a9086d41-9d4a-4485-973b-fa85961e61dd)


I can also confirm it's not working for me either when I try to connect I just get a black screen and a error
