### ISSUE TITLE
rdp fully supported but not working

### ISSUE THREAD

**Issue by rukitas12385** [stascorp/rdpwrap#3359]
already uninstall and reinstall all but no working this is my problem.
![Captura de pantalla (3)](https://github.com/user-attachments/assets/c6747ead-160d-4db6-af60-ac2fbde28f32)
![Captura de pantalla (4)](https://github.com/user-attachments/assets/6d963546-944c-442d-add0-9e1e71d43df5)

help me guys ;C

**Comment by binarymaster** [comment]
Not RDP Wrapper problem, contact Telegram support chat.
