### ISSUE TITLE
Not Working: Windows 2012 6.3.9600.18708

### ISSUE THREAD

**Issue by baltimoresports** [stascorp/rdpwrap#336]
I noticed we weren't able to have more than two RDP sessions on our Windows 2012 Servers. It looks like my version of Windows is no longer supported. I verified that we had the latest version of the rdpwrap.ini (2016-07-22). Is there anything I can do to get it working or help to get it supported?

Thanks!

![capture](https://user-images.githubusercontent.com/1420685/32018338-9590ed2a-b997-11e7-87f0-03eadbf7a95a.PNG)

**Comment by binarymaster** [comment]
> I verified that we had the latest version of the rdpwrap.ini (2016-07-22).

You've did it wrong, it's not latest. See here:

https://github.com/stascorp/rdpwrap/blob/master/res/rdpwrap.ini

**Comment by baltimoresports** [comment]
I stand corrected. Fixed. Thanks for the awesome support.
