### ISSUE TITLE
Can Some One help Me

### ISSUE THREAD

**Issue by badr258** [stascorp/rdpwrap#3361]
![Screenshot 2024-11-22 082939](https://github.com/user-attachments/assets/5368b48d-db8f-45f4-a978-0d34854a1167)

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/3285.

**Comment by badr258** [comment]
> Duplicate of #3285.

this not like my proplem bro

**Comment by binarymaster** [comment]
In your case the RDP Wrapper is not even installed.

> Wrapper ver. N/A

Not a valid GitHub issue then.
