### ISSUE TITLE
windows 11 ver 10.0.22621.2506 not supported

### ISSUE THREAD

**Issue by githubanonym** [stascorp/rdpwrap#3363]
![Sans titre](https://github.com/user-attachments/assets/f1308d58-0bd3-4fc9-b1c1-cb7835bffea7)
Hi, i can't make the wrapper work on my computer.
can you point to me what's the process please ?
i used the scripts install.bat and update.bat, but i can't see any ".ini" downloaded althougth the update.bat script tells me everything is up to date

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2383.
