### ISSUE TITLE
Win 11 10.0.22621.4391 supported but not listening

### ISSUE THREAD

**Issue by ssqmeng** [stascorp/rdpwrap#3364]
已经替换最新https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini，还是not Listening
![2024_11_23_22_02_45](https://github.com/user-attachments/assets/a655e6ed-fc90-42c6-9704-e4f4f893ffb6)

**Comment by binarymaster** [comment]
Not RDP Wrapper problem, either INI has been incorrectly modified or you have not restarted the PC.

**Comment by ssqmeng** [comment]
ini直接替换的，也已经重启电脑了

**Comment by Codefans-fan** [comment]
after replace with master one,  work fine
