### ISSUE TITLE
RDP wrapper completely stopped working after 24H2

### ISSUE THREAD

**Issue by trixlexi** [stascorp/rdpwrap#3365]
For some reason the RDP wrapper stopped working after I updated my windows 11 computer to 24H2 yesterday. It stopped listening and says it was unsupported even though ive placed the updated .ini file into the RDPwrapper folder in desktop. If anyone knows any fixes to this please reply to this post i would really appreciate it.

**Comment by binarymaster** [comment]
Contact RDPWrap Telegram support chat.
