### ISSUE TITLE
10.0.22631.4460 Not Supported

### ISSUE THREAD

**Issue by mikutea** [stascorp/rdpwrap#3366]
![(HX)N5UN%)D73OSA 7G2OXJ](https://github.com/user-attachments/assets/fe21fb69-48e4-49c4-a88a-6be536575fac)
![image](https://github.com/user-attachments/assets/3fe98d72-52f3-4846-a29f-0a5d498aebf2)

**Comment by binarymaster** [comment]
Issue title mismatch with RDPConf screenshot => invalid.
