### ISSUE TITLE
Rdp Wrapper not working error 1067

### ISSUE THREAD

**Issue by vannsigma** [stascorp/rdpwrap#3367]
I am tryign to get my RDP Wrapper to work. although the service state wont start and when i try to start it via command prompt and services i get error 1067
![image](https://github.com/user-attachments/assets/e114f801-73f8-4ab6-b2fa-1e95b19a9c43)
![image](https://github.com/user-attachments/assets/d9fc827f-a422-4b39-a8e6-5939491e126d)
![image](https://github.com/user-attachments/assets/1a557ff4-ee38-4f40-b29c-74407b0c60bd)

**Comment by binarymaster** [comment]
Not RDP Wrapper problem, you altered its configuration incorrectly: https://github.com/stascorp/rdpwrap/issues/1332#issuecomment-873441212
