### ISSUE TITLE
RDPWrapper doesn't work when I have 'Samsung easy connection to screen'

### ISSUE THREAD

**Issue by tw0709** [stascorp/rdpwrap#3376]
As I wrote in the title, if I have Samsung easy connection program, RDPWrapper will say 'Not listening'.
Is it just for me?
Anyway, the solution: delete Samsung easy connection program
(I am Korean so I'm poor at English)

**Comment by binarymaster** [comment]
Not RDP Wrapper issue, so I'm going to close this.
