### ISSUE TITLE
Help rdpwrap.ini for Windows 10 Build 19045.5011 is not support

### ISSUE THREAD

**Issue by favouritehu** [stascorp/rdpwrap#3378]
Windows 10 Pro
Version 22H2
OS Build 19045.5131

Help Me
listener State: Listening not supported

**Comment by favouritehu** [comment]
<img width="530" alt="Screenshot 2024-12-10 at 9 44 00 AM" src="https://github.com/user-attachments/assets/c4cec852-ee4d-4c74-983c-726b04512068">
[termsrv.dll.zip](https://github.com/user-attachments/files/18071659/termsrv.dll.zip)
Also attach pleas help me

**Comment by favouritehu** [comment]
[termsrv.dll.zip](https://github.com/user-attachments/files/18071662/termsrv.dll.zip)

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/2840.
