### ISSUE TITLE
Eset screws up RDP Wrapper

### ISSUE THREAD

**Issue by stelgenkamp** [stascorp/rdpwrap#3379]
Have made several exlusions in ESET Anti-virus, still Eset is blocking the working of RDP wrapper. 
I have excluded : 
C:\Program Files\RDP Wrapper\*
Win32/RDPWrap.A
Win64/RDPWrapA
Hash of RDPWInst.exe 

Anyone have this combination working ? 
And can share their config of exclusions?

**Comment by stelgenkamp** [comment]
Uninstalled and Re-Installed, Now Eset reports a Win64/RDPWrap.B detection. 
Created an exclusion for that too, Still not working. 
RDPConf shows all should be working, Still only 1 user is able to logon.

**Comment by binarymaster** [comment]
I'm closing this since we already have this report: https://github.com/stascorp/rdpwrap/issues/277

**Comment by stelgenkamp** [comment]
Sorry ; this is NOT an duplicate issue. 
ESET works diferently then other anti-virus programs ( that is why it is so good ) 
Therefore the duplicate tag is not in order.

**Comment by binarymaster** [comment]
We have a single issue report for all antivirus software related problems, I don't want to advertise anything.
