### ISSUE TITLE
Requiero el código para la versión Windows 11 23H2 (Compilación SO 22631.4602)

### ISSUE THREAD

**Issue by JVMM25** [stascorp/rdpwrap#3380]
Requiero el código para la versión Windows 11 23H2 (Compilación SO 22631.4602)
![1](https://github.com/user-attachments/assets/75d7ff3b-d422-4170-964b-fc22a4da4b06)
![2](https://github.com/user-attachments/assets/30dfb3be-0039-4745-a51f-23d0c341f8cc)

**Comment by binarymaster** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/3354.
