### ISSUE TITLE
10.0.26100.2605 Not Supported

### ISSUE THREAD

**Issue by Le2dw** [stascorp/rdpwrap#3382]
Hello everyone,

Thank you to the RDPWrap team!

I've fully updated RDPWrap and it shows "fully supported" with all indicators normal. It works perfectly when tested with RDPCheck. However, when I try to connect via remote access, it fails to connect.

I’ve tried formatting and reinstalling, but the issue reoccurs right after I update Windows. Has anyone else experienced this issue or found a solution?

Thank you in advance!

**Comment by binarymaster** [comment]
If it works with RDPCheck, then it's not RDP Wrapper problem, investigate your firewall and gateway settings.

**Comment by Le2dw** [comment]
Thank you for your answer.
When I checked, it was a problem caused by not entering the port, and when I opened the port and entered it, it worked normally. Thank you again.

**Comment by Le2dw** [comment]
> If it works with RDPCheck, then it's not RDP Wrapper problem, investigate your firewall and gateway settings.

Thank you for your answer.
When I checked, it was a problem caused by not entering the port, and when I opened the port and entered it, it worked normally. Thank you again.
