### ISSUE TITLE
win11 23H2   22631.4602

### ISSUE THREAD

**Issue by cailei0596** [stascorp/rdpwrap#3384]
![image](https://github.com/user-attachments/assets/5b4cddfe-069e-499d-85be-7344ee67c59e)
[termsrv.zip](https://github.com/user-attachments/files/18133930/termsrv.zip)

**Comment by TOMORI233** [comment]
Hi, how to use this termsrv.dll for an update? Should I just move it to 'C:\Program Files\RDP Wrapper' or else where?

**Comment by binarymaster** [comment]
@cailei0596 "ver. N/A" is not something I can help with, fix your antivirus problem.
