### ISSUE TITLE
26100.2605不支持

### ISSUE THREAD

**Issue by followwind0516** [stascorp/rdpwrap#3385]
最新只更新到26100.2454

**Comment by binarymaster** [comment]
No RDPConf screenshot => invalid.

**Comment by 34LiuNian** [comment]
> No RDPConf screenshot => invalid.

![屏幕截图 2024-12-15 103400](https://github.com/user-attachments/assets/182f9ba2-4199-4908-8b00-30f8c4e0929c)
26100.2454 Unsupported
@binarymaster

**Comment by binarymaster** [comment]
Duplicate of #3353.
