### ISSUE TITLE
RDP wrapper fully support but not listening on 10.0.19041.4474

### ISSUE THREAD

**Issue by m0rf2** [stascorp/rdpwrap#3391]
I've already done everything so that the listening is green, and I changed it .ini and much more, nothing helps please help
![RDP_CnC_4ZeaQnaCZ1](https://github.com/user-attachments/assets/594f0103-0b6f-4c48-b8b3-0409a7ef67bd)

**Comment by binarymaster** [comment]
Try this: https://t.me/rdpwrap/76956

**Comment by binarymaster** [comment]
No response in a week, considering resolved.
