### ISSUE TITLE
Remote Desktop can't connect to the remote computer

### ISSUE THREAD

**Issue by StasDB** [stascorp/rdpwrap#3394]
Does anyone know why this might be happening?
Could it be because I'm using Spectre OS? 
![W7F2ot1REv](https://github.com/user-attachments/assets/15c2efcf-2983-4602-80bb-35383532533b)
![ApplicationFrameHost_Rs7s0fuhRk](https://github.com/user-attachments/assets/d27f3700-4c15-4622-a933-51005181bebc)

**Comment by binarymaster** [comment]
There's nothing to fix on RDP Wrapper side, ask in support chat instead.
