### ISSUE TITLE
Fully supported but second user cannot log into computer

### ISSUE THREAD

**Issue by mgcarnevali** [stascorp/rdpwrap#3395]
All settings are correct but second user cannot log into computer, it asks to disconnect logged user.

Any idea?

![Captura de pantalla 2024-12-22 130226](https://github.com/user-attachments/assets/40e13d4e-bcd8-455a-b242-852ddd89b94b)

**Comment by binarymaster** [comment]
See https://github.com/stascorp/rdpwrap/issues/3394#issuecomment-2557409530 (duplicate)
