### ISSUE TITLE
Add support for Windows 10 Pro 10.0.14393 N/A Build 14393

### ISSUE THREAD

**Issue by JorgePeixinho** [stascorp/rdpwrap#340]
[*] Installing...
[*] Terminal Services version: 10.0.14393.1737
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[+] TermService found (pid 7096).

Running update.bat does not solve issue.
[termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/1421849/termsrv.dll.zip)

**Comment by binarymaster** [comment]
Duplicate of #322.
