### ISSUE TITLE
Help Pleas I'm a noob, could someone tell me what to do?

### ISSUE THREAD

**Issue by felipe1231213212** [stascorp/rdpwrap#3406]
![Screenshot_8](https://github.com/user-attachments/assets/a0f21b1b-0e1b-446d-be79-76a371fe64fb)
![Screenshot_7](https://github.com/user-attachments/assets/13a091b1-074a-489a-bb63-d10cd4cd300f)
the message says: The number of connections to this computer is limited and all connections are currently being used.
I'm a noob, could someone tell me what to do?

**Comment by binarymaster** [comment]
Yes you are, this is bug reporting area, contact Telegram support chat instead.
