### ISSUE TITLE
Can't Shadow Existing Session

### ISSUE THREAD

**Issue by ayseff** [stascorp/rdpwrap#345]
I'm running on Windows 10.  Below is the screenshot of the settings:
![image](https://user-images.githubusercontent.com/564101/32455691-faa96c98-c2f0-11e7-93d4-a8a20f49258f.png)

As shown, shadowing is enabled.  Yet when I RDP into the computer with the same credentials as the one physically logged on, it doesn't shadow the exiting session.  Instead, it creates a new session with those credentials.  So, if the user is John, in Task Manager, under Users, I see you rows with "John",  but I can't interact with the user, as it's a different session.

What am I doing wrong?

Thanks,

**Comment by binarymaster** [comment]
> What am I doing wrong?

Creating the issue that already exists: #247.
