### ISSUE TITLE
shock connection failed when use "RDPCheck"

### ISSUE THREAD

**Issue by Jeremycm** [stascorp/rdpwrap#349]
I just install and use RDPCheck. But it prompt this error message. So that means i fail?
My OS is Window 10 Home. Please help.

**Comment by binarymaster** [comment]
Run `RDPConf`, check your termsrv version and possible related issues that already opened here.

**Comment by Jeremycm** [comment]
![problem](https://user-images.githubusercontent.com/26617868/32669172-941df34e-c67a-11e7-8847-730d7ca0bf42.png)
So i should let the listener listen? But what should i do? 
Thanks.

**Comment by binarymaster** [comment]
Duplicate of #324.

> But what should i do?

Read the `README.md`, known issues section (there's a solution).
