### ISSUE TITLE
Windows Server 2016 Standart limitation

### ISSUE THREAD

**Issue by AndriusJerry** [stascorp/rdpwrap#350]
Hello,
I was trying to install RDPWrap on Windows Server 2016, which in domain. All working nice, but when connect more than 16 concurrence users for other (which more than 16) doesn't working start menu. But on Windows Server 2008R2 all works fine. May bee there is some limitations or other settings?

Thank you for help

**Comment by binarymaster** [comment]
It can be limitation or bug in Win NT 10, this part of system is not managed by RDP Wrapper.

**Comment by AndriusJerry** [comment]
Thank you for answer, tomorrow I will try the same thing on Windows 10 OS, may bee there is working properly.

**Comment by jagilren** [comment]
What version of RDP Wrapper??

**Comment by Porgi** [comment]
@AndriusJerry Please specify the Windows Server 2016 version & build. I'm seeing the same issue in our test environment at work (not related to RDPWrapper)

**Comment by sebaxakerhtc** [comment]
> It can be limitation or bug in Win NT 10, this part of system is not managed by RDP Wrapper.
