### ISSUE TITLE
Windows 7 termsrv.dll Ver. 6.1.7601.23403

### ISSUE THREAD

**Issue by udicomag** [stascorp/rdpwrap#352]
I have installed the wraper and it works but with a two session limit.
Anyn way around that ? Or is there a way to install a HIGHER version of the termsrv.dll that does not have the limit ?

**Comment by binarymaster** [comment]
It should work with more sessions, can you provide a diagnostics (RDPConf) screenshot?

**Comment by udicomag** [comment]
![image](https://user-images.githubusercontent.com/33900669/33130553-083f519c-cf94-11e7-8c44-26031505c259.png)
The Installscreen was:
![image](https://user-images.githubusercontent.com/33900669/33130566-14c00e66-cf94-11e7-9d57-2e4b67f2f985.png)
This is a Win7 64 Bit embedded SP1 w/o internet connection.
The rdpwrap.ini in the isnall folder is the latest dating 2017-10-13

**Comment by udicomag** [comment]
Oh. I just noticed the the ini file is extracted from the exe ?
Is there any way to use a downloaded version w/o internet access ?

**Comment by binarymaster** [comment]
> Is there any way to use a downloaded version w/o internet access ?

Currently no, see #300. However if you can edit executable resources (e.g. with Resource Hacker) you can replace INI file that is stored inside RDPWInst.

**Comment by udicomag** [comment]
Great, that worked like a charm. Many thanks for this fast response!
