### ISSUE TITLE
Remote sessions prompted for Windows password twice

### ISSUE THREAD

**Issue by KevinRoo** [stascorp/rdpwrap#355]
Windows Version 10.0.16299.64   RDPWrap

For a few weeks now, when remote sessions log in to Windows, the login screen goes away and then it comes back as if the password was incorrect, but it was entered correctly and there are no error messages.

With malware, this is an indication of something trying to grab the user's password by presenting a fake logon screen.

Norton doesn't detect any issues, so I'm suspecting it is related to the new version of Windows and rdpwrap?  It never happens on the console, only remote sessions.

Has anyone else experienced this issue?

**Comment by MortenGuldager** [comment]
Jup. I see exactly the same on a win10 pro install. 
I just reinstalled the machine and the "problem" persists. Cant tell for sure  when it has begun, it is new for sure, but I don't use windows that often, only for testing software. (why I didn't hesitate running the reinstall either :)
I'm not perfectly sure which version I'm running. It might be 1.6.1, but rdpconf says 1.5.0.0 and 10.0.16299.15. Probably not the very latest, haven't bothered upgrading for a while.

**Comment by Porgi** [comment]
@KevinRoo & @MortenGuldager 
Can you confirm that you don't use Network Level Authorization?

**Comment by gitgotgone** [comment]
I've been having the same issue, seemed to start with last fall's windows update, and it seems to be worse (more accounts, at least) since the spring update. It seems to happen in situations where the credentials aren't cached. It's mostly an annoyance, but I'd be happy to troubleshoot if there isn't a known solution.

**Comment by RoRoStar** [comment]
Hi, I'm not sure it's the same issue, but I'm using a win7 Pro x64 "as a remote server".  Credentials are saved in .rdp file of users but when connecting to the server it shows the screen with all opened session and doesn't resume existing session (shadow session?), so user has to clic on his login and enter password again.  Any idea how to fix this ?  (we are not  using Network Level Authorization on the server). thanks

**Comment by gitgotgone** [comment]
It stopped for me after changing to NLA. A bit slower for logon, but otherwise works fine.

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.
