### ISSUE TITLE
Can't get multiple sessions with the same user for the first time

### ISSUE THREAD

**Issue by TooYoungTooSimp** [stascorp/rdpwrap#358]
I have installed and upgraded rdpwrap to the newest version with "single session per user" unchecked.
What I am trying is to get multiple sessions with the same user.
But unfortunately, it can't work for the first time.
Here are the steps for me to reproduce it:
1. Login a account in the console.
2. Try to login the same account from another device.

Then the console sessions disconnects and it seems being attached to the remote device.
But when I try to login again from console, a new session starts and the remote session is still running.
Logout from remote device and login again can reproduce it too.

**Comment by binarymaster** [comment]
What is your TermService version?

**Comment by TooYoungTooSimp** [comment]
![image](https://user-images.githubusercontent.com/6648049/33315604-1d3cfac2-d46c-11e7-926c-4638189a98a2.png)

**Comment by deorth-boffin** [comment]
emmmm, why does it work on your machine. I'm on 16299 too but it says 'not listening' and 'fully supported'. 
And your ID? Excited!

**Comment by binarymaster** [comment]
@deorth-boffin 

> I'm on 16299 too but it says 'not listening' and 'fully supported'.

There is a solution in #194.

**Comment by TooYoungTooSimp** [comment]
@deorth-boffin Windows 10 16299.64 Enterprise

**Comment by nikoutsoukos** [comment]
I also have Windows 10  Enterprise with termsrv.dll version 10.016299.15 and it has the same behavior but I found a workaround.
When I login from a remote desktop application I do not give the password. So it take me to the login screen at the remote server. At that screen I give the user and the password and it opens a new session even if that user is alredy open localy.

**Comment by nikoutsoukos** [comment]
You can also force Always to prompts the client for a password upon connection
Right click at start menu abd run gpedit.msc and then you go
Computer Configuration\Administrative Templates\Windows Components\Remote Desktop Services\Remote Desktop Session Host\Security\Always prompts the client for a password upon connection
and you enable it

**Comment by TooYoungTooSimp** [comment]
@nikoutsoukos I have tried what you said.
Well... It is a tricky solution, but it does work.
If the password of the computer in my class were not so long, this would be a great solution.

**Comment by josh900** [comment]
I am also having this issues, 
after updating windows 10 enterprise, version 1709, updating from 15063 to 16299.

It seems to work at sometimes.. but not sure of the details. maybe some type of authentication thing?

I have tested that when connecting over the rdp.exe app,
If the credentials are saved (after checking 'remember me' while logging in) multiple concurrent sessions can be opened with no problem.
Also, as mentioned above, multiple concurrent sessions work if logging in via the standard login, not the rdp.exe prompt.

seems to be related to #353 #326

**Comment by josh900** [comment]
Thought maybe this was related to #194 #373 ?
I tried the script provided in #194, but no changes
I also tried changing the rfxvmt.dll owner to an admin user, but no changes.

I also found that if 2 sessions of the same user are logged in, using one of the methods above to open 2 sessions, then concurrent users are open with no issues. 

Does anyone know what is going on here? or can point to any info? 
Everything was working fine on version 15063, and all the above has started after updating to 16299. Verified on multiple computers.

**Comment by josh900** [comment]
It seems the behavior is, when a new session is opened, if only one session for the user is already opened, it will connect to the existing session. While if more than one existing session is open, then a new session is created.
This seems different than the behavior in previous windows versions, where a new session is opens every time, if multiple concurrent sessions is enabled.

Is there a way to force always create new session.?

I guess a workaround would be to open 2 sessions (rdp/local or  rdp/rdp) on startup or similar, and then multiple concurrence users should open without issue. Obviously not the best option.

**Comment by lolvince** [comment]
same problem here # 513

**Comment by sebaxakerhtc** [comment]
> There is a solution in #194.
