### ISSUE TITLE
ALERT! Stop using RDP Wrapper

### ISSUE THREAD

**Issue by mmd30** [stascorp/rdpwrap#359]
I got all my files encrypted by ransomware which I thought is odd since I never open anything suspicious.
So I reformatted the hard drive, installed windows and add RDP Wrapper back. Today when I wanted to use my computer I noticed I was logged off. I logged on with my password and after a few minutes I got logged off again. When I logged back on I noticed windows opened that I didn't open and also a notification that virus check was disabled. I unplugged the network connection immediately, re enabled virus check, removed RDP wrapper. Problem solved.

**Comment by binarymaster** [comment]
Then your RDP host / server is not properly (securely) configured, this is not RDP Wrapper issue.
