### ISSUE TITLE
Cannot add new remote users

### ISSUE THREAD

**Issue by vic-t** [stascorp/rdpwrap#360]
I'm not sure if this issue is related to the latest Windows 10 update (to version 1709) but I can no longer change remote desktop users. When I click on the button "Select users that can remotely access this PC", nothing happens. Mind you, the button is not greyed out or anything, it's just that no dialog opens when I click it. 

I tried uninstalling RDPWrapper to see if that solves it, i.e. if it lets me change the users, but that removes the remote desktop functionality entirely. 

Any ideas or workarounds?

**Comment by binarymaster** [comment]
Use Computer Management snap-in (`compmgmt.msc`) or command line `net localgroup` utility.

**Comment by vic-t** [comment]
Thanks for the quick reply Stas, that solved it. I could add domain users to the built-in remote desktop users group. Adding users to this group through the ADUC for some reason has not the same effect.
