### ISSUE TITLE
Terminal Services is not supported. 10.0.16299.15

### ISSUE THREAD

**Issue by CZcharlie** [stascorp/rdpwrap#362]
Terminal Services is not supported. 10.0.16299.98

**Comment by binarymaster** [comment]
Please provide RDPConf screenshot.

**Comment by tmknight** [comment]
![image](https://user-images.githubusercontent.com/548588/34011408-e9ca26dc-e0dd-11e7-8da7-56cedb21f07a.png)

**Comment by CZcharlie** [comment]
I apologize to them for my mistake


Charlie

**Comment by binarymaster** [comment]
Duplicate of #316.
