### ISSUE TITLE
Add support for 10.0.16299.15 

### ISSUE THREAD

**Issue by prodigy007** [stascorp/rdpwrap#365]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1536802/termsrv.zip)

I read this topic and took .dll - https://github.com/stascorp/rdpwrap/issues/316

but it did not help, I also updated rdpwrap.ini

**Comment by binarymaster** [comment]
#361

**Comment by prodigy007** [comment]
![default](https://user-images.githubusercontent.com/13364186/33798172-1c648072-dd25-11e7-8cf3-564ddc0c03f8.png)
not work!!
