### ISSUE TITLE
%~dpORDPWInst.exe not found

### ISSUE THREAD

**Issue by dan9126** [stascorp/rdpwrap#366]
Not sure if I am doing it wrong. I have Windows 10 Home patched current. the update and install cannot fine the installer program.  I saw a TechNet note that seem to indicate the .exe indicated in the install/update batch files is no longer in Windows and has been replaced by an alternative mechanism I totally don't understand ( Alas, I am an engineer, not a programmer) I downloaded what I believe is the 6.1 version (?) latest and greatest, but no soap.  

I have a feeling, I'm doing it wrong, but not sure why or what. Thanks for any help you can give.

**Comment by binarymaster** [comment]
Does installer present in your directory?

- **If not**: it was removed by antivirus software - add the folder to exclusions and unpack release again.
- **If yes**: your command line interpretator is misconfigured, you'll need to start it manually, navigate the folder where you unpacked release, and run `RDPWInst.exe -i -o` to install.

**Comment by dan9126** [comment]
Thanks for the response. I will re-download on a different machine where I have control over the AV settings and get the set up that way.  Thank you for your work on this question and this project. Much appreciated!
