### ISSUE TITLE
Не работает поддержка 10.0.16299.15 

### ISSUE THREAD

**Issue by prodigy007** [stascorp/rdpwrap#367]
Прошлая тема:
https://github.com/stascorp/rdpwrap/issues/365
Вот доказательство,  на моем планшете не работает.
![default](https://user-images.githubusercontent.com/13364186/33798188-4fbada34-dd25-11e7-84ae-e3e0a21b479a.png)

Все обновлено, но ничего это не даёт

**Comment by binarymaster** [comment]
See README (`rfxvmt.dll` missing).
