### ISSUE TITLE
Listener is not listened, rfxvmt.dll not helping on Windows 10 x64 Home One Language 10.0.16299

### ISSUE THREAD

**Issue by AlexeiScherbakov** [stascorp/rdpwrap#368]
I get rfxvmt.dll from Windows 10 x64 Pro then copy it to ‪C:\Windows\System32\rfxvmt.dll
Then fix Security for Trusted Installer

rfxvmt.dll SHA1 - 81D4AD81A92177C2116C5589609A9A08A5CCD0F2, MD5 - E3E4492E2C871F65B5CEA8F1A14164E2

But it is not helping. I also try reboot many times with and without fix for Trusted Installer but nothing helped.

![default](https://user-images.githubusercontent.com/8665915/33799560-3fcdb690-dd3f-11e7-9284-3b6117e12759.PNG)

RDPWrap prints version 10.0.16299.15
ver prints version Microsoft Windows [Version 10.0.16299.98]

**Comment by binarymaster** [comment]
Did you tried reinstalling RDP Wrap after you copied that file?

**Comment by AlexeiScherbakov** [comment]
Yes. I tried Install, copy rfxvmt.dll, reinstall
I tried also - reboot, uninstall, reboot, install, update, reboot
But nothing helped.
System is Asus All-In-One PC Windows 10 x64 Home One Language.
May be there is a difference between Home and Home One Language?

I have 3 computers with Windows 10 x64 Pro and 1 with Windows 10 x64 Home One Language. 

Also, I found that, when RDPWrap is running, I cannot delete rfxvmt.dll, so this library is used, but nothing happened

**Comment by AlexeiScherbakov** [comment]
Also, on one computer with Windows 10 x64 Pro I found that rfxvmt.dll in System32 and in SysWOW64 are **different**. But when I copy rfxvmt.dll on my Home system it automatically changed in System32 **and** in SysWOW64

**Comment by binarymaster** [comment]
> But when I copy rfxvmt.dll on my Home system it automatically changed in System32 and in SysWOW64

Probably, that's the reason of your problem. Try monitoring what changes this file.

**Comment by w17** [comment]
If you use 32-bit application to copy file
MS File System Redirector can be a cause
https://msdn.microsoft.com/en-us/library/windows/desktop/aa384187(v=vs.85).aspx

**Comment by binarymaster** [comment]
You should use native version of DLL file (if your system is 64-bit, you must use 64-bit DLL and place it in system32).

**Comment by AlexeiScherbakov** [comment]
**Problem was: I used 32-bit Total Commander to copy files.**
When I use 64-bit all back to normal

I attached new rfxvmt.dll from Windows 10 x64 Pro 10.0.16299.15 from latest update
[dlls.zip](https://github.com/stascorp/rdpwrap/files/1545652/dlls.zip)

Now all is working fine. This is interesting, I don't knew that copy operations to C:\Windows\system32 are redirected for 32-bit process

**Comment by binarymaster** [comment]
> I don't knew that copy operations to C:\Windows\system32 are redirected for 32-bit process

That's WOW64 file redirection at work.

**Comment by AlexeiScherbakov** [comment]
I think, that description of copy operation in 32/64-bit process must be added to readme :-)

In 64-bit OS user must use 64-bit file manager for copy rfxvmt.dll's to system32 & SysWOW64
After it this issue can be marked as solved.

**Comment by XUnderShadow** [comment]
seems like after latest updates to this day the Dll fix isn't working anymore for Home version

**Comment by lars18th** [comment]
Hi,

Fixed! The problem is the incorrect "rfxvmt.dll" privileges. See this post:
http://github.com/stascorp/rdpwrap/issues/194#issuecomment-353029623

Please, close this issue!

**Comment by binarymaster** [comment]
Closed as duplicate of #194.
