### ISSUE TITLE
Win 7 "Your computer could not connect to another console session ..."

### ISSUE THREAD

**Issue by Terpla** [stascorp/rdpwrap#370]
Hello!
I'm not sure if this is a bug or I'm doing something wrong. 
Windows 7 SP1. Downloaded last release rdpwrap, installed, updated.
When i run RDPConf.exe everything green, but if i try to connect using remote desctope i have Errpr:
"Your computer could not connect to another console session on the remote computer because you already have a console session in progress."

![win7sp](https://user-images.githubusercontent.com/24498410/33890033-134740b6-df63-11e7-8915-7760b2e8cfe9.png)

When i try connect by RDPCheck.exe everything ok. When i try connect from other computer everything ok too.

**Comment by binarymaster** [comment]
> I'm not sure if this is a bug or I'm doing something wrong.

You're doing it wrong, since mstsc doesn't allow loopback connections (this is known restriction). You can only use RDPCheck for that.

**Comment by Terpla** [comment]
It seems I do not understand something. In this video, the user connects to his computer but under a different account. And it seems to use mstsc.exe
https://www.youtube.com/watch?v=fi87Xe78YNY
Where is the mistake?

**Comment by binarymaster** [comment]
Different versions of mstsc behave differently.

**Comment by binarymaster** [comment]
> to update

Rather to downgrade, because this limitation is relatively new. Try it yourself.

**Comment by dragonballz2k** [comment]
I was about to install this is loopback connection not going to work on windows 8.1? I thought we could use "127.0.0.2" for loopback?
