### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by JebonLebong** [stascorp/rdpwrap#371]
I've download Rdpwrap Source code (zip). How i can compile it? Using what software? Thanks in advance

**Comment by binarymaster** [comment]
Everything you need is in README document.

Also read this: https://stackoverflow.com/questions/32281940/how-to-publish-or-export-x86-and-x64-c-version-of-rdpwrap

**Comment by JebonLebong** [comment]
Thanks binarymaster for helping me. Thanks

**Comment by satpute-sneha** [comment]
Hello, I have downloaded the rdpwrap but having some issues in running batch  file and I could not find any executable files to install  when i have downloded rdpwrap. Can anyone help me to resolve this  issue?
thanks
![rdpwrap](https://user-images.githubusercontent.com/39690217/42434205-d5327ad6-8384-11e8-995c-b94cbb2cd08a.PNG)
