### ISSUE TITLE
Latest Windows 10 Update rendered this program incompatible.

### ISSUE THREAD

**Issue by rekabis** [stascorp/rdpwrap#372]
Apparently the latest Windows 10 update rendered this program incompatible. I was doing some work on a client's machine, and two windows updates did not install properly, so I downloaded them and conducted manual “offline” installs. Once they were installed, only one person could be connected at a time. This is the current state of the program:

![rdp](https://user-images.githubusercontent.com/7185825/34058061-8ddc47d6-e18e-11e7-802f-e402dad0ab6d.png)

I made sure to grab the latest copy from the site and tried multiple times to get it to re-set itself. The system has also been rebooted in the meantime. Any assistance would be greatly appreciated.

**Comment by binarymaster** [comment]
You didn't run `update.bat`

**Comment by rekabis** [comment]
RDP Wrapper Library v1.6
Installer v2.3
Copyright (C) Stas'M Corp. 2016

[*] Checking for updates...
[*] Current update date: 2017.02.03
[*] Latest update date:  2017.10.13
[+] New update is available, updating...
[+] TermService found (pid 444).
[*] Shared services found: CryptSvc, Dnscache, LanmanWorkstation, NlaSvc
[*] Terminating service...
[*] Starting CryptSvc...
[*] Starting Dnscache...
[-] StartService error (code 1056).
[*] Starting LanmanWorkstation...
[*] Starting NlaSvc...
[-] StartService error (code 1056).
[*] Starting TermService...
[+] Update completed.

Press any key to continue . . .
