### ISSUE TITLE
Strange problem with Windows 10.16299.98

### ISSUE THREAD

**Issue by NMCowboy** [stascorp/rdpwrap#373]
After I install the wrapper it works fine once. If on my computer I log off the remote computer no problem. If I log back on to the remote computer from my computer it logs the remote computer local console session off. If I run a test at the workstation using RDPCheck.exe it works fine multiple times. I have this same version of RDP wrapper working on another remote Windows 10 computer and it works fine. Seems as if it has to be something wrong with the remote computer but I sure can't find it.

**Comment by lars18th** [comment]
Hi,

Me too. The problem is the incorrect "rfxvmt.dll" privileges. See this post:
http://github.com/stascorp/rdpwrap/issues/194#issuecomment-353029623

Please, close this issue as it's fixed.

**Comment by binarymaster** [comment]
Duplicate of #194.

**Comment by NMCowboy** [comment]
This is not the same problem as #194. I am running Windows 10 Professional. The status program shows everything is working correctly with the system listening on 3389. The test program works fine. I have rfxvmt installed and the permissions are correct. The remote user can connect once without logging off the console session. The second time I try to connect the console session is logged off. All the settings in the registry to terminal server are correct. The only difference is that I am running on a domain, but I have another windows 10 machine running on the same domain successfully.

**Comment by binarymaster** [comment]
This sounds more like a Windows (Terminal Services) bug.

**Comment by tvcat** [comment]
I'm having the same problem with Windows 10 home 16299.125.
I fixed it by changing from "Network Level Authentication" to " GUI Authentication Only" in the RDPConf.exe.

**Comment by NMCowboy** [comment]
Well someone else found the problem I was running into. I have multiple batch files and RDP configuration files set up so I just click on the proper batch file and I connect. But as I noticed someone else found out it will not work if you supply the user name and password via the RDP parameter file. That just logs the console session out when you log in. BUT if you check the "prompt for user name and password" but leave the user name in the parameter file you will just get prompted for the password and then you can just give the password and log in without logging the console session off. So binarymaster, while I prefer to have it all automated so I don't have to remember so many passwords this works just file. It also explains why I can pass the wrapper test and log in multiple sessions all with the same user name because in the test I have to manually supply a password for each test session. So consider this one closed.
