### ISSUE TITLE
Strange problem with Windows 10.16299.98  Reopen

### ISSUE THREAD

**Issue by NMCowboy** [stascorp/rdpwrap#374]
This is not the same problem. I am running Windows 10 Professional. The status program shows everything is working correctly with the system listening on 3389. The test program works fine. I have rfxvmt installed and the permissions are correct. The remote user can connect once without logging off the console session. The second time I try to connect the console session is logged off. All the settings in the registry to terminal server are correct. The only difference is that I am running on a domain, but I have another windows 10 machine running on the same domain successfully.

**Comment by binarymaster** [comment]
Do not create new issues, if you want to reopen old, click Reopen button.

**Comment by NMCowboy** [comment]
I have looked for the reopen button for 1 ½  hours. Are you sure there is one?

Pete

On the desert in New Mexico
