### ISSUE TITLE
Local RDP Checker "Socket Connection Failed"

### ISSUE THREAD

**Issue by tecknog33k** [stascorp/rdpwrap#376]
I have a Windows 10 Home and the RDPWrap does not work for me. Plus, every time I use the Local RDP Checker, it just says "Checking..." on the screen, and less than 10 seconds later, it puts "Disconnected." and "Socket Connection Failed." up on the screen. 
I've already used everything possible with both the Remote Desktop and RDPWrap settings, and nothing works.

Here's some information:
![capture](https://user-images.githubusercontent.com/34800596/34323062-191acfa0-e7fe-11e7-9742-b10f1e040cc5.PNG)

OS Name	Microsoft Windows 10 Home
Version	10.0.16299 Build 16299
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	LAPTOP-3BFQDJQ9
System Manufacturer	HP
System Model	HP Pavilion Notebook
System Type	x64-based PC
System SKU	V8L99UAR#ABA
Processor	AMD A4-6210 APU with AMD Radeon R3 Graphics, 1800 Mhz, 4 Core(s), 4 Logical Processor(s)

**Comment by binarymaster** [comment]
Do you see **Not listening** notification? Read README.

**Comment by anamul87** [comment]
Same Issue.
Anyone, please help. Thanks!

**Comment by kailashjoshi7** [comment]
Same issue. Please share experience to solve this

**Comment by vivekjoshi5** [comment]
> Do you see **Not listening** notification? Read README.

Where is this READ ME file ? Can you guide me master ?

**Comment by xoptoi** [comment]
Same issue. Please share experience to solve this. Windows 11 Pro 22H2 22621.1413

![image](https://github.com/stascorp/rdpwrap/assets/75647741/5f05c89e-5c8a-4669-8844-20130a17e506)
![image](https://github.com/stascorp/rdpwrap/assets/75647741/f2099f95-e13e-424d-9ece-c0e3ebede07f)

**Comment by xoptoi** [comment]
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.22621.2361
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[+] TermService found (pid 2356).
[*] No shared services found.
[*] Extracting files...
[+] Extracted config -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[
![image](https://github.com/stascorp/rdpwrap/assets/75647741/17c0a8bc-7222-4d4b-b9ec-da32525176ea)
