### ISSUE TITLE
Build 10.0.17063.1000 RDPCheck fails with Unknown Error 0x4

### ISSUE THREAD

**Issue by jonstanley** [stascorp/rdpwrap#378]
Ran install.bat and then update.bat, RDPConf.exe says everything is okay... connecting with RDPCheck.exe locally will error as per screenshot. RDP-ing from a remote computer will have session terminate whilst connecting.
![rdp](https://user-images.githubusercontent.com/5381136/34411867-9bdf5162-ec14-11e7-9831-830400413a87.jpg)

**Comment by steev666** [comment]
Same problem here

**Comment by steev666** [comment]
Also get those other warnings, maybe it could help.

1.- Rebbot the host and in the first login of the user installed RDPwrapper i got the error: Error en la llamada a procedimiento remoto /  Error in remote procedure call

These warning only giveme once and return to login scrteen, then put again the password and start normaly

2.- On remote computer using RDP connection, i got the firt connection just to the user screen, and sudently lost conection, only once, just before i start a season on the host, then after it only dont fint any route to host, cant connect 
![error de conexion](https://user-images.githubusercontent.com/17465896/34450868-885afd18-ecdb-11e7-8a3e-435d0e5a03a3.png)
![img_20171229_203839](https://user-images.githubusercontent.com/17465896/34450869-886f766c-ecdb-11e7-862a-b622041b26c1.jpg)

**Comment by steev666** [comment]
Additional information, I noticed that the RDP Service stops immediately after trying to login to a user, as long as there is no logon the connection remains alive without problems, it is not until trying to start session which leads me to think that there may be an error in the redirected to RDPWrapper user start and cause the same to close the service

**Comment by iliakonnov** [comment]
Same thing too

**Comment by Kryptonit3** [comment]
Any updates on this? Been running RDPWrapper for months and now my clients get `0x4` error on connection. At the physical computer, get the same thing running `RDPCheck`.

**Comment by sebaxakerhtc** [comment]
Is this issue actual? If no - please close it

**Comment by sebaxakerhtc** [comment]
Closed as not actual
