### ISSUE TITLE
Allow only 1 user (remote and console)

### ISSUE THREAD

**Issue by forfe15** [stascorp/rdpwrap#380]
If a user is logged in physically (console) and then connects remotely (same username), both session remain connected. I would like to have only the remote user connected and only 1 remote user. Is there any way to accomplish this? I changed a few options in the configuration file, but no luck.

The only reason I want to use this application is to allow multiple monitors in Windows 7. If there is another option, please let me know.

P.S.: Great application. Thank you.

**Comment by tvcat** [comment]
Just a google search will land you the answer.
https://technet.microsoft.com/en-us/library/cc753380(v=ws.11).aspx

**Comment by sebaxakerhtc** [comment]
> And seriously this is not an ISSUE
