### ISSUE TITLE
Service stopped, unable to uninstall

### ISSUE THREAD

**Issue by stanosvk** [stascorp/rdpwrap#383]
Hi,

Windows 10 Home, version 1709. I am not able to start service. I have tried to uninstall RDwrap, but also without any success. See my screenshots below. When I try start service manually, I got error 5 - access denied. 

![rdwrap3](https://user-images.githubusercontent.com/35135781/34605754-ff1ad7a8-f20c-11e7-8f86-de77902fc3f5.png)
![rdwrap1](https://user-images.githubusercontent.com/35135781/34605586-743a3c00-f20c-11e7-8bf5-6cb7b07367a7.png)
![rdwrap2](https://user-images.githubusercontent.com/35135781/34605587-745962a6-f20c-11e7-905f-7102044d5545.png)

**Comment by binarymaster** [comment]
Antivirus?

**Comment by stanosvk** [comment]
I tried to switch off antivirus and firewall but didn´t help. 
When I installed it, it works but after reboot it stopped working and showing service state stopped. Then I tried to unninstall, but also isn´t possible to make it.
