### ISSUE TITLE
Another third-party TermService library is installed

### ISSUE THREAD

**Issue by apolyakov2017** [stascorp/rdpwrap#384]
Today I lost access, before everything worked for many months. Now when you run install.bat / uninstall.bat / update.bat:
```
[-] Another third-party TermService library is installed.
[*] ServiceDll: "".
```
Windows version 10.0.16299.125

**Comment by binarymaster** [comment]
Run this command (as admin):
```sh
reg add HKLM\SYSTEM\CurrentControlSet\Services\TermService\Parameters /v ServiceDll /t REG_EXPAND_SZ /d "%SystemRoot%\system32\termsrv.dll" /f
```

**Comment by apolyakov2017** [comment]
Thank you, this is the solution!

**Comment by thefernand** [comment]
Nice, worked for me.!

**Comment by moaeddy** [comment]
Thanks @binarymaster your solution give me relief from headache

**Comment by neymp** [comment]
Thank you. Worked for me in apr/2022.

**Comment by duduzai2019** [comment]
> 运行此命令（以管理员身份）：
> 
> ```shell
> reg add HKLM\SYSTEM\CurrentControlSet\Services\TermService\Parameters /v ServiceDll /t REG_EXPAND_SZ /d "%SystemRoot%\system32\termsrv.dll" /f
> ```

you are my god,thanks!!!

**Comment by duduzai2019** [comment]
> 运行此命令（以管理员身份）：
> 
> ```shell
> reg add HKLM\SYSTEM\CurrentControlSet\Services\TermService\Parameters /v ServiceDll /t REG_EXPAND_SZ /d "%SystemRoot%\system32\termsrv.dll" /f
> ```

![image](https://user-images.githubusercontent.com/96464964/187962919-65e08831-3a52-4878-a75c-1017b9b852f5.png)
but my service state still stopped

**Comment by apolyakov2017** [comment]
> but my service state still stopped

Use this:
https://www.octaniumsw.site//2019/04/rdp-wrapper-confg-update-tool-en.html

**Comment by duduzai2019** [comment]
> > but my service state still stopped
> 
> Use this: https://www.octaniumsw.site//2019/04/rdp-wrapper-confg-update-tool-en.html

thanks！

**Comment by Nathanfonts** [comment]
thankss bro!

**Comment by fercosassistemas-sys** [comment]
> Ejecuta este comando (como administrador):
> 
> reg add HKLM\SYSTEM\CurrentControlSet\Services\TermService\Parameters /v ServiceDll /t REG_EXPAND_SZ /d "%SystemRoot%\system32\termsrv.dll" /f

buen dia Maestro Binario. despues de utilizar el comando me sale error en los clientes "error espacio insuficiente de almacenamiento para completar esta operacion escritorio remoto" y no he podido arreglarlo. gracias por su ayuda
