### ISSUE TITLE
Stopped working after some time.

### ISSUE THREAD

**Issue by thefernand** [stascorp/rdpwrap#385]
I was ising it normaly, then it stopped working. I tried to re-install but o couldn't.
![sem titulo](https://user-images.githubusercontent.com/35283216/34754350-65c0606e-f5a4-11e7-80e7-c94a909d1ea9.jpg)

What should I do to make it work again??
Currently I am using teamviewer to use the computer.

**Comment by YisroelAdler** [comment]
Maybe this is the solution:
https://github.com/stascorp/rdpwrap/issues/384#issuecomment-355833698

**Comment by thefernand** [comment]
Solution above worked.
