### ISSUE TITLE
Shadow Error: Unspecified Error after KB4056890

### ISSUE THREAD

**Issue by markreg** [stascorp/rdpwrap#386]
I'm getting a `Shadow Error: Unspecified Error` box after an automatic update of `KB4056890`.

After uninstalling `KB4056890` and blocking updates, the update still manages to reinstall itself after a reboot.

Since the update addresses the recent Spectre vulnerability, is it possible to workaround the shadow error problem and keep the update installed?

Using Windows 10 x64 LTSB to shadow other user sessions on same host.

**Comment by binarymaster** [comment]
Contact Microsoft support to fix their bugs...

**Comment by markreg** [comment]
That's a good point, but nevertheless I'm curious to know why KB4056890 would interfere with session shadowing.

**Comment by binarymaster** [comment]
KB4056890 cumulative update is huge, it may change many things, not only Spectre vulnerability.

See **file information** section here:
https://support.microsoft.com/en-us/help/4056890/windows-10-update-kb4056890

Many terminal services libraries were changed.

**Comment by markreg** [comment]
Figure out why updates kept getting re-enabled. Updates must be disabled only after KB4056890 or any other update is uninstalled.

Shadow sessions working again. Here's to hoping Microsoft fixes the issue.
