### ISSUE TITLE
listener not supported after last windows update

### ISSUE THREAD

**Issue by sogard83** [stascorp/rdpwrap#388]
Hello.

After last windows updates (09.01.2018 and 10.01.2018) the listener is not supported and when trying to run update.bat it says it "failed to download latest ini from github".

Any ideas how this problem can be solved?

Thank you.

**Comment by binarymaster** [comment]
You did not posted diagnostics screenshot.

**Comment by sogard83** [comment]
Sorry guys. I was stupid. My bitdefender was blocking the update and the ini file. Problem solved.

**Comment by binarymaster** [comment]
Ok, closing.
