### ISSUE TITLE
rdpwrap.dll x64 unknown crash / exception

### ISSUE THREAD

**Issue by binarymaster** [stascorp/rdpwrap#39]
We are experiencing technical issues with x64 version on some machines. There is unknown exception somewhere in the code, here are related comments and logs:
https://github.com/binarymaster/rdpwrap/issues/33#issuecomment-122507203
https://github.com/binarymaster/rdpwrap/issues/33#issuecomment-126168823
https://github.com/binarymaster/rdpwrap/issues/33#issuecomment-126202541
https://github.com/binarymaster/rdpwrap/issues/34#issuecomment-126060696
https://github.com/binarymaster/rdpwrap/issues/38#issue-98139824

For the advanced users who encountered the same problem, use Visual Studio 2013 or higher to debug the DLL file and to find actual reason of exception.

Test cases:
- VirtualBox - Windows 10 Home x64 - no issue

**Comment by binarymaster** [comment]
@Herjar @hooges8 @flauschi82 @XperianPro @alfred0
I joined your comments into one issue. If someone could help with realtime debugging of DLL file, you are welcome.

Thanks in advance!

**Comment by XperianPro** [comment]
Actually I am at the moment installing Visual Studio 2015. I will try to get some debug right now.

**Comment by binarymaster** [comment]
Thanks! Please note that `rdpwrap.dll` works in the context of `svchost.exe` process, so to get actual PID, use `tasklist /svc` and find which process hosts TermService.

**Comment by flauschi82** [comment]
I get an access violation writing the location ("Access violation writing location 0x00007FFC8474F34")

**Comment by binarymaster** [comment]
@flauschi82
If you are debugging, please provide more information... at least base address and number of line in the code.

**Comment by flauschi82** [comment]
The VS breaks inside of the termsrv.dll (Exception 0x00007FFC63F650FF). It seems like it tries to read a location at 0xFFFFFFFFFFFFFFFF - this causes an access violation.

**Comment by flauschi82** [comment]
Would it help, if i gave you access to that machine?

**Comment by XperianPro** [comment]
This is where it fails.

>rdpwrap+0x2953:
>00007ffe`039d2953 8906            mov     dword ptr [rsi],eax ds:00007ffd`fe4cf347=8b48000a

**Comment by asulwer** [comment]
any resolution with win10 pro?  I just replaced my ini and it restarting now, so we will see if it works

**Comment by alfred0** [comment]
asulwer please let us know if that works

**Comment by mrkengos** [comment]
just tried the latest ini with win10 pro and also experiencing the not listening status

**Comment by gompf01** [comment]
I think i have found the solution to this, common ini file issue, happend many times before in different projects ;) 

The last line in the ini is missing the CR LF thus the read is incomplete.

After adding the last CR LF, all is fine and the RDP is listening on RTM. at least here.

Chris

**Comment by gompf01** [comment]
![rdpwrapper](https://cloud.githubusercontent.com/assets/13584326/9002635/c1b47a12-3766-11e5-9517-b7f2f4f90d84.jpg)

**Comment by flauschi82** [comment]
It's working like a charm now. Thanks a lot :-) :+1:

**Comment by gompf01** [comment]
You are welcome :)

For all: Of course after editing the file , tou need to "Net Start TermService" fromt he command line to Start the RDP or reboot, both will do.

Chris

**Comment by hirolash** [comment]
gompf01, you sir are a saint, thank you. Something so trivial, yet so important to reminder, adding a blank line at the bottom of the ini file.

**Comment by binarymaster** [comment]
WisdomWolf helped with adding a workaround, I hope this will help :)

https://github.com/binarymaster/rdpwrap/commit/f534a1c8fcf7a5709b6d251888671981e2c6d2aa

**Comment by eXaminator** [comment]
I had a similar problem, but in my case 7and thanks to the screenshot above) I figured out that my ini fily hat unix format line endings, not windows. Changing those fixed the problem for me. :-)

**Comment by binarymaster** [comment]
RDP Wrapper updated to v1.6, problem with line-breaks solved by adding update feature to the installer.

If someone have this problem with the new version too, let me know.

**Comment by liuwenru** [comment]
can you write a.exe file to use in my computer how to use

**Comment by binarymaster** [comment]
> can you write a.exe file to use in my computer how to use

I didn't understood what you mean. If you're talking about something like help file, everything you need is README.md

**Comment by binarymaster** [comment]
Seems like this issue was solved after introducing batch update method in the installer.

**Comment by danielwalo** [comment]
Same issue on 1.6, sorry. Win10 Home (Norwegian)
