### ISSUE TITLE
Accidently stop working RDP service for multiply users

### ISSUE THREAD

**Issue by vserg2004** [stascorp/rdpwrap#390]
Accidently stop working RDP service for multiply users. Installed latest version of RDPWrap. After installation of RDPWrap stop working Windows RDP service, trying to start - unable to start error code 5. If uninstall RDPWrap, windows rdp service can be started but for only user access.

**Comment by binarymaster** [comment]
Did you read README?

![image](https://user-images.githubusercontent.com/578406/34905843-568c9826-f872-11e7-90f4-c14c4cbff95f.png)

**Comment by vserg2004** [comment]
I have read issue 215, win defender and smartscreen are disabled, but win defender service still working and I can't stop it, there are no options "start", "stop" or "reload"

**Comment by binarymaster** [comment]
You don't need to disable it, just add folder to exclusions.
