### ISSUE TITLE
Configure Server Authentication and Encryption Levels on RDwrap

### ISSUE THREAD

**Issue by djgreen-pl** [stascorp/rdpwrap#392]
Hello.
How to change server authentication and encryption levels to "RDwrap"
I am interested in: SSL (TLS 1.0).

**Comment by Porgi** [comment]
@djgreen-pl 

> Open the Local Group Policy Editor by typing “gpedit.msc” into either a Run prompt or the Start menu.
> When the Local Group Policy Editor opens, expand Computer Policy > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host, and then click on Security.
> Double-click on any settings in this menu to change their values.  The ones we recommend changing are:
> Set client connection encryption level – Set this to High Level so your Remote Desktop sessions are secured with 128-bit encryption.
> Require secure RPC communication – Set this to Enabled.
> Require use of specific security layer for remote (RDP) connections – Set this to SSL (TLS 1.0).


1:1 copy from [here](https://www.howtogeek.com/175087/how-to-enable-and-secure-remote-desktop-on-windows/)

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.
