### ISSUE TITLE
Support Build 10.0.17074.1002

### ISSUE THREAD

**Issue by marcwebdude** [stascorp/rdpwrap#396]
Request build support to resolve [not supported] status

Edit:
![rdpwrap](https://user-images.githubusercontent.com/3277752/35358632-e2042a06-011c-11e8-8a84-1c722de4bc21.PNG)

update.bin has been run several times just to make sure latest has been retrieved without clearing [not supported]

here is screenshot of teamsrv.dll
![teamsrv](https://user-images.githubusercontent.com/3277752/35358770-63014274-011d-11e8-99ca-3deaba466968.PNG)

**Comment by binarymaster** [comment]
Please provide config diagnostics screenshot.

**Comment by johndewood** [comment]
Here is the dll.
[termsrv-10.0.17074.1002.zip](https://github.com/stascorp/rdpwrap/files/1677572/termsrv-10.0.17074.1002.zip)

**Comment by rfgamaral** [comment]
Also using the same build, would love support for this one :)

How can we help further besides reporting the unsupported build?

**Comment by kurayamix** [comment]
For any one who looking for temporary fix.

use old termsrv.dll from this thread work fine for me.
[https://github.com/stascorp/rdpwrap/issues/357](url)

**Comment by binarymaster** [comment]
x86 (32-bit) DLL with build number 10.0.17074.1002 is also required to resolve this issue.

**Comment by sebaxakerhtc** [comment]
> x86 (32-bit) DLL with build number 10.0.17074.1002 is also required to resolve this issue
