### ISSUE TITLE
RDPwrapper 1.6.2 with Classic Shell Menu

### ISSUE THREAD

**Issue by Procstas** [stascorp/rdpwrap#397]
When connected to Win10_1709 via RDP Wrapper 1.6.1/1.6.2, the “Shutdown“  button at the bottom of the remote Classic Shell Menu is no longer visible.

**Comment by binarymaster** [comment]
Not a RDP Wrapper issue.

**Comment by redneck-f25** [comment]
As said above it's not a RDP wrapper issue.

- Open Classic Shell Settings.
- Enter "shutdown" in the search box
- Activate "Show Shutdown during remote sessions"

**Comment by Procstas** [comment]
Daniel, Thank you for your quick support.

Problem solved.

**Comment by Procstas** [comment]
A big thankyou to Daniel Hammerschmidt for his support and solution.
