### ISSUE TITLE
Shadow remote win 10 session?

### ISSUE THREAD

**Issue by markreg** [stascorp/rdpwrap#399]
Is it possible to shadow a session on a remote computer? Currently, mstsc says it cannot connect to the computer if I use this line:

`mstsc -v:[ip] /shadow:2 /control`

but it works correctly if I rdp to another account on the remote machine and then shadow locally on the rdp session using:

`mstsc /shadow:2 /control`

**Comment by binarymaster** [comment]
Shadowing requires you to be authorized on target computer, I doubt it can be used this way.

**Comment by markreg** [comment]
What does authorized mean in this context? I do have an account (separate from the one I want to shadow) on the target machine. Currently I have to rdp that account and then within the rdp session on the target machine I can shadow another account on the same machine.

It's a bit cumbersome that way, especially since the shadowed session within the rdp session on the target machine doesn't fullscreen for some reason (even with the `/f` flag).

**Comment by binarymaster** [comment]
> What does authorized mean in this context?

I don't know how MSTSC communicates with Terminal Services on local machine to achieve shadowing, probably by checking process' user SID and security context.

**Comment by markreg** [comment]
Does Windows 10 patched with rdpwrap have Terminal Services installed/running? I can't find it on the target machine.

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.
