### ISSUE TITLE
Win10 home service stopped

### ISSUE THREAD

**Issue by HugoLamm** [stascorp/rdpwrap#401]
Opened RDPConfig found service stopped & port not listening.
Double checked in service. Remote Desktop service is blocked to start.

Last, try to replace the termsrv.dll to system32 but access denied.
Any way to solve this?

**Comment by binarymaster** [comment]
See #384 and #391.

**Comment by HugoLamm** [comment]
Thanks for the prompt response binarymaster.

#384 works for enabling the RDP service. Thanks.

But I still hit the port not listening issue even replaced the rfxvmt.dll from
https://github.com/stascorp/rdpwrap/issues/194#issuecomment-325627235

**Comment by HugoLamm** [comment]
Add some screens
By default after RDPwrap installed.
![screen shot 2018-01-27 at 10 34 25 pm](https://user-images.githubusercontent.com/35869695/35472879-463e41fe-03b2-11e8-8bde-aa7b05c7437e.png)

If follows #384 works for enabling the RDP service
![screen shot 2018-01-27 at 10 31 01 pm](https://user-images.githubusercontent.com/35869695/35472865-199379a8-03b2-11e8-8d2b-7743b5e78182.png)

**Comment by binarymaster** [comment]
Totally uninstall, reboot, and install again.

**Comment by grzeg8102** [comment]
Had the same issue. It worked with 1.62 for the last two weeks, but suddenly today I noticed it stopped. But as suggested by @binarymaster - I uninstalled, rebooted and installed again and I have it working again. Without rebooting it doesn't work after you install again. Rebooting is crucial

**Comment by magolubev** [comment]
I had a similar problem - the Remote Desktop service did not start after installing the library, "Access denied".
My decision: to give full access rights to the network service on the directory "C:\Program Files\RDP Wrapper"
![2018-02-28_10-23-16](https://user-images.githubusercontent.com/36913710/36775123-c5b04914-1c71-11e8-81ef-be9e0078a55b.jpg)

**Comment by binarymaster** [comment]
See #391.
