### ISSUE TITLE
Problems with rdp connections on windows server 2008 r2

### ISSUE THREAD

**Issue by vbespuda** [stascorp/rdpwrap#403]
Hi, I installed the latest version of RDPwrapper on windows server 2008r2. Right now the server is in my company domain. Everything installed. The service running and listening but I can't connect more than 2 users via RDP. Is it a server trouble or I can't get more than 2 connections in the domain?

**Comment by Jonatanrm** [comment]
did you run update.bat?

**Comment by vbespuda** [comment]
Yes. But this server is not connected to the internet. Maybe I can update it manually?

**Comment by sebaxakerhtc** [comment]
> Maybe I can update it manually?

Yes. You can. If this issue is not actual anymore – please close it
