### ISSUE TITLE
Failed to connect to custom RDP port

### ISSUE THREAD

**Issue by joshsmithtogo** [stascorp/rdpwrap#405]
Install appears to function. Rdconf reports enabled, running and listening. Initiate rdp into local unit through port 10001 and unit fails to connect. I have set listening port in registry and it is listed in rdconf using default settings in RDconf too other than port. 
Any ideas? Can I not use this port number or something? It's available on my setup and not being used.  The version of RDPwrap is V1.6.2.  Any help is greatly appreciated.

**Comment by joshsmithtogo** [comment]
I have tested for a bit and port 3389 works just fine but 10001 will not work.  May be a bug. Unsure.

**Comment by tentaurus** [comment]
so RDPwrap works well with your Win 10? Also RDPcheck?
I still get the error Access denied with RDPcheck...but it works!
Using Win 10 Pro 1709 - 16299.192

**Comment by joshsmithtogo** [comment]
Rdpcheck just makes sure remote sessions are functional locally. RdpConf is the configuration editor.

**Comment by joshsmithtogo** [comment]
Also if you are using Win 10 Pro then you should be operational even easier.

**Comment by tentaurus** [comment]
@joshsmithtogo 
What do you mean?

**Comment by joshsmithtogo** [comment]
Win 10 Pro already has Remote Desktop server available to be used. You just have to turn it on in your Windows settings. You would want to use Rdpwrap if you wanted to make it where you could have multiple users logging into the pc at one time like a server. If you are the only user remoting into the unit then you shouldn’t need rdpwrap.

**Comment by tvcat** [comment]
16299.192 here and no problem with port 10001.
You need to restart your computer after changing the port.

**Comment by rtmbox** [comment]
@tvcat restart is not needded, they can uninstall/install using the bats and all will work fine :)

**Comment by binarymaster** [comment]
> Can I not use this port number or something?

There's some problem at your side, check out `netstat -an`.

**Comment by nickmcg02** [comment]
@joshsmithtogo you can use this software to access a server right even though I dont have windows 10 pro . I have tried many times to access the server but I always get the error that remote access to the server is not enabIed. I am new to this sorry

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.
