### ISSUE TITLE
Not listening

### ISSUE THREAD

**Issue by saurav-biswas** [stascorp/rdpwrap#406]
Hi,
I am using windows 10 pro,
built 16299.rs3_release.170928-1534. It is showing the following error as it showing not listening.
Please help me out.

![rdp wrapper configuration](https://user-images.githubusercontent.com/20636483/35723758-79c588e8-0821-11e8-9e9f-5956c3c5748d.PNG)
![windows 10 built version](https://user-images.githubusercontent.com/20636483/35723793-980eadb6-0821-11e8-8725-8ab1a99d5c4f.PNG)

**Comment by binarymaster** [comment]
Try full uninstall and install the latest version again.

**Comment by emorales1996** [comment]
i'm using windows 10 home and i have the same problem. Listener state is Not Listening. I uninstalled and install the latest version sometimes and it. Please, help me.

**Comment by binarymaster** [comment]
@emorales1996 you downloaded outdated release.

**Comment by omeverest** [comment]
Hi! I have the same problem as @emorales1996  and what needs to be done?

.....i'm using windows 10 home and i have the same problem. Listener state is Not Listening. I uninstalled and install the latest version sometimes and it doesn't work.
When I installed, in cmd line show -this version of Terminal Services is not supported-.....
![image](https://user-images.githubusercontent.com/36982614/36887514-d02d85d6-1e1b-11e8-9359-c494367496d4.png)
![image](https://user-images.githubusercontent.com/36982614/36887554-f9084374-1e1b-11e8-858a-41a8753ddb50.png)

**Comment by binarymaster** [comment]
@omeverest this is not latest version, according to your screenshot.

**Comment by omeverest** [comment]
sorry! and where to get the latest version?

**Comment by omeverest** [comment]
found, 1 .6.2, right? thank you, sorry again)
