### ISSUE TITLE
localuser rdp to another user on same machine fails

### ISSUE THREAD

**Issue by dhoer** [stascorp/rdpwrap#407]
I'm trying to get https://github.com/dhoer/choco-cloud-screen-resolution/tree/win10 to work with Windows 10.  This creates a local user account to Remote Desktop Protocol (RDP) at specified screen resolution (default is 1920x1080) into another user account on same Windows server.

I have _rdpwrapper_ installed and RDPConf diagnostics are green. I'm able to login with RDPCheck, but I still get 'cannot connect to another session because you have a console session progress' message.  

I use `New-ScheduledTaskAction -Execute 'cmdkey.exe' -Argument "/add:localhost /user:$($pp['UserName']) /pass:$($pp['Password'])"` along with `"mstsc.exe /v localhost /w:$($pp['Width']) /h:$($pp['Height'])"`.  Is the target localhost the problem somehow?

Thanks in advance!

**Comment by binarymaster** [comment]
This is limitation in `mstsc` that RDP Wrapper cannot overcome.

Contant the developer of `choco-cloud-screen-resolution` for further support.

**Comment by dhoer** [comment]
Lol, I am the developer of `choco-cloud-screen-resolution`.  Thanks for the information. I thought I was doing something wrong.  Do you have time to explain this limitation to me?  It is ok if you don't.  I would just like to have an understanding about this issue.

**Comment by binarymaster** [comment]
Ah... try connecting to `127.0.0.2` instead of `127.0.0.1` to achieve loopback RDP connection. But sometimes even this doesn't work.

**Comment by dhoer** [comment]
Ok, thanks.   It looks like this is how I would store the password: `cmdkey /generic:TERMSRV/127.0.0.2 /user:administrator /pass:redacted` to use with `mstsc /w:1920 /h:1200 /v:127.0.0.2`.  I will give that a try.  Thanks for the help.

**Comment by dhoer** [comment]
That works! Thanks.  It is prompting for userid and password, so the cmdkey info is not getting picked up. Any thoughts about how to work around this?

**Comment by binarymaster** [comment]
Try switching between different security modes in `RDPConf`, maybe it would help.

**Comment by dhoer** [comment]
I tried all 3 options. All prompted for password.  So close...

**Comment by dhoer** [comment]
Alright, I got this to work.  The cdmkey needed to be changed to `cmdkey /add:127.0.0.2 /user:administrator /pass:redacted`.  

Thanks so much for your help!
