### ISSUE TITLE
Max limit connections

### ISSUE THREAD

**Issue by steska77** [stascorp/rdpwrap#408]
Hi,

is it possible to set the software to run max 2 connections?

thanks

**Comment by binarymaster** [comment]
Use Google to find the solution, the issue section is for technical issues, not for support.

**Comment by steska77** [comment]
Sorry, this is a support question. I just need to know if .ini file can be modified to limit only 2 simultaneous connections.

**Comment by binarymaster** [comment]
Just try it, I didn't tested this though.

**Comment by steska77** [comment]
But I don't know what settings I have to edit to make it work.
