### ISSUE TITLE
no shadowing in win7pro?

### ISSUE THREAD

**Issue by sh-dvl** [stascorp/rdpwrap#410]
every try to shadow an existing session within win7pro 32bit, results in an error.

all tries are done in real Administrator-Mode, so there shouldn't be any access-problem.

taskmgr (context-menu at user-session): remotecontrol of session failed
shadow <id>: remotecontrol failed: error 120 (this function isn't supported by system)
mstsc /shadow:<id>: the windows-version on this server doesn't support shadowing

as I know, remote-app is only supported in win7ultimate, so maybe shadowing, too?

but: why even the taskmgr shows the option?

any trick to activate support for win7pro?

**Comment by binarymaster** [comment]
Windows 7 supports shadowing, there's something wrong with your system then.

**Comment by sh-dvl** [comment]
well, thanks, you're right. 
we've now tried some other systems, were it works well (but only as real administrator). Unfortunately it's not clear, why it fails on some systems, either with the above error, or another one: shadowing a console-session works well, but trying to shadow another rdp-session leads to a break of own connection (can be re-established a moment later)

is there any possibility to debug the mechanism or is the only solution the typical solution (re-installation of windows)?

**Comment by binarymaster** [comment]
> is there any possibility to debug the mechanism or is the only solution the typical solution (re-installation of windows)?

RDP Wrapper doesn't provide any Terminal Services debugging stuff, so try contacting Microsoft support / tech forums for non-typical solutions.

**Comment by Porgi** [comment]
> is there any possibility to debug the mechanism or is the only solution the typical solution (re-installation of windows)?

[Windows Debugger](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.
