### ISSUE TITLE
Reduce number of Screens for RDP?

### ISSUE THREAD

**Issue by JasterX** [stascorp/rdpwrap#411]
Hey,

First of all: Good job!
This is less an Issue, but more of a Request. I use a setup with 3+ screens and would like to RDP to a machine without using ALL my screens for that session, but still more than one. Is there a way to expand rdpwrap to enable such a configuration?

**Comment by binarymaster** [comment]
This should be configured at the client side.

**Comment by Porgi** [comment]
@JasterX 3rd party tools or try to tweak the RDP client (which is really hard to do that, example: setting resolution for RDP that will count 2 or more monitors but not all).
Issue/request should be closed as not related to the main feature of software.
If needed I can bring some sources for that.

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.
