### ISSUE TITLE
win 2003 reported Terminal service (RDP) not starting at RDPWrap install

### ISSUE THREAD

**Issue by grarturo** [stascorp/rdpwrap#413]
I had an error.... I tried to install RDPWrap v1.6.1 on win 2003 r2 server with SP2 (with all the updates from Microsoft(.  :-(

My regular Remote Desktop is not working any more, and it is needed.

RDP is not working, it just does not start the "service" and at the same time, I can not uninstall it... when starting the server I get an error about RDpcheck.exe can not be executed.

Is there a procedure to uninstall this and get back to my "normal" state ? the uninstall.bat does not work for my purpouse.

I will appreciate your help.

best regards.

**Comment by binarymaster** [comment]
You did not read the README.

**Comment by grarturo** [comment]
so, is there a solution?

**Comment by binarymaster** [comment]
Try this:
```sh
reg add HKLM\SYSTEM\CurrentControlSet\Services\TermService\Parameters /v ServiceDll /t REG_EXPAND_SZ /d "%SystemRoot%\system32\termsrv.dll" /f
```
