### ISSUE TITLE
Supposed Virus infection in repository

### ISSUE THREAD

**Issue by 3dWrecker** [stascorp/rdpwrap#414]
Bitdefender reports RDPWrap-v1.6.2.zip and link to msi download infected with Trojan.GenericKD.40145889
Please fix.
![infection](https://user-images.githubusercontent.com/34898242/36623780-b3192ba2-196c-11e8-9db2-09ad68c28129.png)

**Comment by 3dWrecker** [comment]
Sorry. I hadn't seen the previous threads on this issue. I will try to get Bitdefender to add rdpwrap components to their whitelist (or remove them from their malware list). I will update you if I have any success.

**Comment by binarymaster** [comment]
Duplicate of #277 < any further discussion here.
