### ISSUE TITLE
Fail to open 2nd session after 23/02/2018 windows update

### ISSUE THREAD

**Issue by fhoshino** [stascorp/rdpwrap#416]
Windows 8.1 x64 EN
Can't open 2nd session, only one session limit not removed.

**Comment by binarymaster** [comment]
No diagnostics screenshot and/or log provided.

**Comment by fhoshino** [comment]
![tvnviewer_2018-03-01_00-38-27](https://user-images.githubusercontent.com/771955/36799854-0c81d3a4-1ce9-11e8-81a4-6c7c1d828095.png)

**Comment by binarymaster** [comment]
According to the screenshot and error text, this limitation goes from elsewhere, but not Terminal Services.
