### ISSUE TITLE
Add support for termsrv 10.0.17115.1

### ISSUE THREAD

**Issue by redbluescreen** [stascorp/rdpwrap#424]
![image](https://user-images.githubusercontent.com/8455367/37172715-452cd712-231a-11e8-991b-11b976b9d7af.png)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1794579/termsrv.zip)

It is latest insider build

**Comment by DHaak93** [comment]
I am also having issues with this build of termserv

**Comment by tiboroni** [comment]
Hi same issue here, waiting for patch

**Comment by kurayamix** [comment]
replace with older version of DLL doesn't work too.

**Comment by yctn** [comment]
@rednekcowboy Thanks you. before this i use a modified termsrv.dll but this is a better sollution. its working good now.

**Comment by binarymaster** [comment]
x86 (32-bit) DLL **with build number 10.0.17115.1** is required to resolve this issue.

**Comment by tiboroni** [comment]
latest update solved my problem

Tnx
![image](https://user-images.githubusercontent.com/6125356/40106968-699a0e72-58f7-11e8-81e1-1db1f9c2b6a7.png)

**Comment by rednekcowboy** [comment]
you keep closing this but it's still an issue!!  yes there is a new build, but there hasn't been a new COMPILED BUILD for ages which renders a new build useless for 99% of users.

Quit being so quick to close an issue when it's not resolved for everyone or at least provide a link to a solution that everyone can use if you do!!
