### ISSUE TITLE
" The number of connections to this computer is limited..." despite rdpwrap running

### ISSUE THREAD

**Issue by abagarella** [stascorp/rdpwrap#427]
I'm running into an issue trying to log on to a Windows 10 Pro system (1709 / 16299.251) with termsrv.dll 10.0.16299.15.

rdpwrap 1.6.2 is installed and when I run RDPConf, everything checks out (running, listening, etc.).

![capture](https://user-images.githubusercontent.com/755284/37327401-853caeae-266c-11e8-839f-bb18b5d5197a.PNG)

If I try to log in with more than one user, I get the "The number of connections to this computer is limited..." error you would get if rdpwrap wasn't running.

I've tried uninstalling and reinstalling a number of times, and a number other random tweaks/fixes to Windows itself, but nothing seems to work. Is this possibly a bug or is something just wrong with my machine?

**Comment by binarymaster** [comment]
> something just wrong with my machine?

This.

I have no problems using concurrent sessions with this termsrv build.

**Comment by gagarinds** [comment]
I had the same problem.
I deleted the program. installed again. and it all worked

**Comment by abagarella** [comment]
When you say you deleted the program, did you just use the uninstall script? Or did you do any manual removal of anything? I ask because I've used the uninstall script and re-installed a number of times.

Is it possible that the install got corrupted somehow and the uninstall isn't working correctly? Is there a way/directions to manually remove what needs removing?

**Comment by gagarinds** [comment]
![2018-03-14_09-10-03](https://user-images.githubusercontent.com/37333640/37386030-acc629d6-2767-11e8-952a-d26f6b1f6e76.png)
i run uninstall.bat as admin
and next run install.bat as admin

**Comment by andydld** [comment]
Same problem here. 
Two Windows Server 2012 R2 Standard.
Problem since the most current Windows Updates (installed 13.03.2018/14.03.2018)

RDPwrapper 1.6.1 and 1.6.2

Wrapper state: Installed ver. 1.5.0.0
Service state: Running ver. 6.3.9600.18928
Listener state: Listening [not supported]

RDP.ini:  2017.12.27

Reinstall of RDPWrapper doesnt help.

**Comment by mariagil1975** [comment]
vaya, tengo el mismo problema. Que habrá ocurrido?

**Comment by lalogago** [comment]
Same here.
![sin titulo](https://user-images.githubusercontent.com/37376519/37413238-5a7f6192-2785-11e8-9397-037a99eb7c26.jpg)

Some one got a solution ?

**Comment by binarymaster** [comment]
@andydld @lalogago you are posting offtopic here, your issue is #418.

**Comment by abagarella** [comment]
Well, for some unknown reason this randomly started working again today. I was able to log in with multiple users and did not get the error. I didn't do anything, so I'm not exactly sure what happened. But I'll take it!

**Comment by Wajahat234** [comment]
![not supported](https://user-images.githubusercontent.com/30357439/38610393-23388b5c-3d9a-11e8-87e1-f3f456a9061f.PNG)

**Comment by Wajahat234** [comment]
Windows Server 2012 R2

**Comment by Wajahat234** [comment]
solution ?

**Comment by Rainer981** [comment]
I had the same problem as @abagarella My solution was to uninstall, then install with proxy settings set, update with proxy settings set, so the configuration file could have been downloaded. Then everything worked without the annoying text "The number of connections to this computer is limited".

**Comment by srjuanjo** [comment]
> I had the same problem as @abagarella My solution was to uninstall, then install with proxy settings set, update with proxy settings set, so the configuration file could have been downloaded. Then everything worked without the annoying text "The number of connections to this computer is limited".

Proxy settings? What are u talking about bro, don’t know what is that, having same issue here!

**Comment by frantisekhallo** [comment]
What helped to me was either a combination of running the update.bat, I also manually removed the directory 'C:\Program Files\RDP Wrapper' and run update.bat again. And followed by running by myself alone commands 'net stop termservice' and 'net start termservice' , though  who knows if running these commands alone did not solve it alone, but removing the Rdp Wrapper folder mentioned might had been needed to. Anyway now it works after some time of troubleshooting here.

Also I needed the newest INI file from the #999 issue.

**Comment by frantisekhallo** [comment]
I again struggled with it a little/considerably, but it is achievable. I had the same state as @Wajahat234  in his picture with the not supported message and the listener state listening. When you turn off the service 'net stop termservice' the listener state goes to "off" from "Listening" (I dont remember exactly but the state is changed from it to turned off or some like that state).

It seems like the provided configuration ini file, must be placed into the 'C:\Program Files\RDP Wrapper' , not to the directory with the application, as the installation actually updates that system directory. At this step I dont remember exactly but I think I had to turn off that service 'net stop termservice', but at some step it somehow complained about the service being disabled. But after having the attached configuration file in that Program Files Rdp directory, and subsequently running the uninstall.bat and install.bat/update.bat file afterwards, it started to work somehow. Just it looks like as if it could not install /update the library at some stage. But trying out various combinations of this steps should turn out well in the end.
