### ISSUE TITLE
RDP-Wrap disabled by Windows Update KB4088876

### ISSUE THREAD

**Issue by unbrainwasher** [stascorp/rdpwrap#428]
Since the forementioned Windows-Security-Update on Windows 8.1 RDPconfig tells "not supported". The current workaround ist to desinstall the update and disable it on the Update-List. Therefore, the code for the trmsvr.dll should be updated.

**Comment by binarymaster** [comment]
Which `termsrv.dll` version?

**Comment by pethrowilo** [comment]
Same here, win8.1, listener not supported
termsrv.dll version 6.3.9600.18928

**Comment by binarymaster** [comment]
Duplicate of #418.

**Comment by Jakamali** [comment]
We are uninstalling this patch from all twenty of our Server 2012 r2 RTDS servers. It is causing random servers to freeze and nobody can get in until the offending server is rebooted.
