### ISSUE TITLE
Fix for Windows 10 Insider Preview

### ISSUE THREAD

**Issue by rednekcowboy** [stascorp/rdpwrap#429]
Just replace the termsrv.dll with this one:

https://file.io/Ow2yWZ

Works fine

**Comment by binarymaster** [comment]
Please post in #424, closed as duplicate.

**Comment by yctn** [comment]
@rednekcowboy Can you maby reupload? ur link is dead

**Comment by rednekcowboy** [comment]
http://www.mediafire.com/file/7u594so6qas2a69/termsrv.rar

**Comment by yctn** [comment]
@rednekcowboy are you sure ur uploaded version is fixed/patched? i can still only have one RDP connection at the time?

**Comment by rednekcowboy** [comment]
all I did was take the file, replace my termsrv file with it and run rdp wrapper.  everything worked fine after that.

the file is untouched.  you need to use rdp wrapper in conjuction with it.

![image](https://user-images.githubusercontent.com/37426398/37518362-2eb5eeac-28eb-11e8-928b-269c41315e09.png)

those are my rdp wrapper settings
