### ISSUE TITLE
Cannot connect from remote

### ISSUE THREAD

**Issue by RDPAlvin** [stascorp/rdpwrap#433]
The configuration settings look correct; however, I cannot connect when I used remote desktop connection: 24.73.xxx.xxx:3395  I used RDPcheck.exe I could see the login screen. When I entered the correct password, it said Access is denied.
![screenshot](https://user-images.githubusercontent.com/37590464/37668708-7c536ca4-2c3b-11e8-8ac2-5df68c175136.png)

**Comment by FlynnLives** [comment]
make sure the user you are trying to connect as is an administrator

**Comment by nickmcg02** [comment]
my account is the administrator and I get the same issue- any update on this

**Comment by binarymaster** [comment]
See #391.
