### ISSUE TITLE
Listener not supported after Windows Update KB4088876 and KB4088879

### ISSUE THREAD

**Issue by yesidhm1** [stascorp/rdpwrap#434]
Hi, After applying the updates for the month of March, the rdpwapper 1.6.2 application stopped working. The patches that affect are KB4088876 and KB4088879. Could you please confirm if there is a fix that activates the rdpwapper 1.6.2 again? Thank you very much.

**Comment by 1valdis** [comment]
Same problem here. Waiting for update...

**Comment by gabor-farkas** [comment]
What's your version of termsrv.dll?
Doesn't this help: https://github.com/stascorp/rdpwrap/issues/418 ?

**Comment by KEVORK890** [comment]
same problem with windows 8.0

**Comment by binarymaster** [comment]
Duplicate of #418.
