### ISSUE TITLE
NOT SUPPORTED

### ISSUE THREAD

**Issue by gotti1977** [stascorp/rdpwrap#437]
hi
i,m running this on win8.1 enterprice. After upgrade windows i have this (pic)
![rdp](https://user-images.githubusercontent.com/37869964/38027353-a90131f0-328f-11e8-894a-94264570eaf6.jpg)
can anyone help??  

THANKS

**Comment by binarymaster** [comment]
Duplicate of #418.

**Comment by gotti1977** [comment]
THANKS !!!
