### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by eurovisionfanatic** [stascorp/rdpwrap#438]
Hi,

I have been using your software for a long time, after forcibly turning windows 10 automatic updates off your service worked great.  Microsoft automatically updated windows today and I was attempting to get your latest version in order to use it on Windows 10 home.  Unfortunately, when I went to download your file chrome blocked it and when I used virus total it came up with a number of viruses.  Is this simply because of the nature of the program or has the download been compromised.

Thanks so muc

**Comment by binarymaster** [comment]
Duplicate of #277.

**Comment by binarymaster** [comment]
> because of the nature of the program

This.
