### ISSUE TITLE
Listener is not listening on Win 10 Home (build 14997+)

### ISSUE THREAD

**Issue by Pmar13** [stascorp/rdpwrap#440]
Hi,

I get rfxvmt.dll from an old computer with Win10 home and place into windows system32 folder and then it works.
You will find the file in attachment

thank for your help.

[rfxvmt.zip](https://github.com/stascorp/rdpwrap/files/1871698/rfxvmt.zip)

**Comment by binarymaster** [comment]
Duplicate of #194.

**Comment by Pmar13** [comment]
i know but i fixed the problem and i can't answer in #194 because it closed.

**Comment by Pmar13** [comment]
Sorry i just see that the answer was at the end of the post
