### ISSUE TITLE
Not working on Windows 10.0.17133.1 (Spring Creators Update)

### ISSUE THREAD

**Issue by matthewryanparker** [stascorp/rdpwrap#442]
Hello, I upgraded to the new version of Windows and RDP Wrapper doesn't appear to work on this build. Just thought I'd let you guys know! Thanks for all your help.

**Comment by bobpaul** [comment]
Win 10 Home or Pro? 
32-bit or 64-bit?
On Windows 10 Home you might need to [get a copy of rfxvmt.dll](https://github.com/stascorp/rdpwrap/issues/194#issuecomment-325627235) and place it somewhere in your path (ex c:\windows\system32\)

**Comment by matthewryanparker** [comment]
This is Win10 Pro, 64bit.

**Comment by Dnominated** [comment]
Same issue. To try and fix it, I copied rfxvmt.dll from \System32 and \SysWOW64 from a working copy of Windows 10 (same build, 17133.1) Pro, and just for sure the termsrv.dll from \System32, to a copy of Windows 10 Home (same build, 17133.1), which had previously worked with RDPWrapper 1.6.2

I ran the following commands on all 3 DLL's, the two copies of RFXVMT and the one of TERMSRV, then restarted:
```
net stop TermService
takeown.exe /A /F rfxvmt.dll (or termsrv.dll)
icacls.exe rfxvmt.dll /grant "PCADDR\user:F"

icacls.exe rfxvmt.dll /inheritance:d
icacls.exe rfxvmt.dll /setowner "NT SERVICE\TrustedInstaller"
icacls.exe rfxvmt.dll /grant "NT SERVICE\TrustedInstaller:F"

icacls.exe rfxvmt.dll /remove "NT AUTHORITY\SYSTEM"
icacls.exe rfxvmt.dll /grant "NT AUTHORITY\SYSTEM:RX"

icacls.exe rfxvmt.dll /remove "BUILTIN\Administrators"
icacls.exe rfxvmt.dll /grant "BUILTIN\Administrators:RX"

icacls.exe rfxvmt.dll /remove "PCADDR\user"

```
I still have the "Not listening"/"Not Supported" error in Listener State on the RDP Wrapper Configuration

**Comment by matthewryanparker** [comment]
Is there a planned update to this? I would like to be able to deploy via chocolatey?

**Comment by ddt321** [comment]
please, upload termsrv.dll from Fall Creators Update

**Comment by gave92** [comment]
I got it from here https://www.mysysadmintips.com/-downloads-/Windows/Clients/termsrv_win_10.0.16299.15.zip

**Comment by ddt321** [comment]
sorry, I mean Spring Creators Update

**Comment by ddt321** [comment]
After dll from Fall Creators Update RDP successful not working

**Comment by Dnominated** [comment]
Rather than a kludgy fix, I paid less than $5 to get a Pro license key from eBay.

**Comment by ddt321** [comment]
I have license

**Comment by matthewryanparker** [comment]
What was the fix for this?

**Comment by FoGBaV** [comment]
Please - can someone with freaky skills patch the 0.0.17133.1 alias 1803 64 bit Version (Enterprise)? 

I know MS has killed the RTM Status ... but there are many people now out there sitting on a shitty 1803 Version without RDPWrap function ...8(

Please help ...

**Comment by alvarollt** [comment]
I've just found a solution on this link.
https://www.mysysadmintips.com/windows/clients/545-multiple-rdp-remote-desktop-sessions-in-windows-10
**Thanks to Adam**

_Windows 10 April 2018 Update 17134 RTM x64 build:

Find:

8B 99 3C 06 00 00 8B B9 38 06 00 00

Replace With:

B8 00 01 00 00 89 81 38 06 00 00 90

Cheers
Adam_

**Comment by yetangye** [comment]
Yesterday night，my Win10 home edition/x64 automatically updated to Win10 1803, and now I found the RDPwrap not works...

**Comment by yetangye** [comment]
Replace the C:\Windows\system32\termsrv.dll with the one from C:\Windows.old\system32\，after restart the computer, it works!

**Comment by homjak** [comment]
Replace the C:\Windows\system32\termsrv.dll with the one from C:\Windows.old\system32\，after restart the computer, it works! I confirm! Thank you!

**Comment by kostnermo** [comment]
That indeed works! In case you can't delete the file, you need to take ownership first.
Then you should be good to go.

**Comment by zydream** [comment]
how can i replace the DLL in win 10 Home？

**Comment by StarfighterJ** [comment]
I am in Same boat with Win10 1803 what do you mean take ownership first I can't seen to copy and paste from the windows.old on termsrv.dll please help

**Comment by kostnermo** [comment]
Check this link: 
https://www.laptopmag.com/articles/take-ownership-folder-windows-10-using-file-explorer

**Comment by XenobyteDK** [comment]
I can also confirm it works when you replace the termsrv.dll with the one from Windows.old. Reboot isn't necessary; a restart of the remote desktop service is enough. Actually you have to turn it off in order to replace the file so just start it again and it works.

**Comment by XenobyteDK** [comment]
Update: On my system updated with the Spring Creator update with the termsrv.dll copied from Windows.old I get two logon-screens when connecting using RDP. After logging in on the first one I get a blank bluish screen for less than a second and then the logon screen again. After logging in the second time I get the normal desktop and everything works as before.

**Comment by framosl** [comment]
There is a thread for Windows 10.0.17134.48??

**Comment by GambaGirl** [comment]
I also just updated to Windows 10 build 1803 17134.48.

I am getting Not Listening Not Supported when I run RDPConf. I downloaded the latest version 1.6.2 and ran update as well.

I tried to implement the suggested change - moving termsrv.dll from Windows.old, but there is no system32 directory under Windows.old. Searching for termsrv.dll in that tree turned up nothing.

**Comment by XenobyteDK** [comment]
Get the termsrv.dll from the link earlier in this thread - the post by gave92.

**Comment by FormadorLar** [comment]
@gave92 @XenobyteDK the link you posted for termsrv.dll isn't working... anyone who could upload the x64 version of it? 

Thank you.

**Comment by Crush33** [comment]
same issue here...
win10 pro updated from 1709 to 1803 and even when replacing with termserv under windows.old it wont work, only one session allowed :(

any idea ? thx !

**Comment by ITSUPPORTGIC** [comment]
Hi All,

I am facing an issue ie. a new windows update is installed after the installation,my RDP Wrapper is not working. Kindly give solution to resolve this issue.

**Comment by fullerSystems** [comment]
Replacing termsrv.dll with the link provided above resolved the issue for me.

1. In Command Prompt run: net stop TermService
2. Download termsrv.dll from:
https://www.mysysadmintips.com/-downloads-/Windows/Clients/termsrv_win_10.0.16299.15.zip 
**or** 
https://transfer.sh/LaY0f/termsrv.zip 
and extract
3. Goto C:\Windows\System32 in explorer
4. Right-click > Properties > Security > Advanced
5. Make yourself the owner of the file and close all windows
6. Back in C:\Windows\System32, goto the Properties > Security tab again and hit Edit
7. Give yourself (or Administrator assuming you are admin of your box) modify rights
8. Copy and paste the newly extracted termsrv.dll into the folder
9. Hit replace when prompted
10. You should then run in Command Prompt: net start TermService

Then run RDPConf to confirm the Listener is in a "Listening" state, and then RDPCheck to confirm RDP access locally. 

It worked for me, hope it works for others.
