### ISSUE TITLE
Silent installer

### ISSUE THREAD

**Issue by moaeddy** [stascorp/rdpwrap#443]
Anyway to have this installer/uninstaller not poping up this?

![wrapper](https://user-images.githubusercontent.com/7292467/38496114-2316d5c4-3bb1-11e8-806c-85417c614ee1.png)

**Comment by binarymaster** [comment]
Write your own application that will run installer with window hidden.

**Comment by realyukii** [comment]
Did you manage to get it working, @binarymaster?
