### ISSUE TITLE
Installation procedure not clear

### ISSUE THREAD

**Issue by CeresBarros** [stascorp/rdpwrap#447]
Hi there,

Perhaps I'm too much of a newbie, but I found that the installation of RDPWrap is not clear. After 30min of trying to understand how it works I finally found this page, that made it all clear:
https://appuals.com/how-to-setup-rdp-on-windows-10-all-versions/

Could you include these steps (or other installation steps) on the README? 

Thanks!
Ceres

**Comment by binarymaster** [comment]
> Could you include these steps (or other installation steps) on the README?

They are already included in README.

**Comment by CeresBarros** [comment]
I'm sorry! I found them now I guess I was expecting them to be before FAQ and all the releases and all and never bothered to scroll all the way down!
Thanks :)
