### ISSUE TITLE
Windows server 2012 R2 wrapper 1.5.0.0 servce 6.3.9600.18928 not supported

### ISSUE THREAD

**Issue by danielabelski** [stascorp/rdpwrap#452]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1918447/termsrv.zip)

Hi!
Windows server 2012 R2 wrapper 1.5.0.0 service 6.3.9600.18928 not supported
any way to fix this or bypass it?

**Comment by mitcbw** [comment]
Second this. Please can you release a fix - or if there is something to do.

**Comment by binarymaster** [comment]
Duplicate of #418.
