### ISSUE TITLE
termsrv.dll 10.0.15063.994 not supported

### ISSUE THREAD

**Issue by giovannigarifo** [stascorp/rdpwrap#455]
Correctly listening, but RDPConf says that the attached dll is not supported. 

Thanks for your job, waiting for an update to support the new dll.

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1942394/termsrv.zip)

**Comment by jfajardomercado** [comment]
I have the same problem with the same DLL. We will wait for an update

**Comment by giovannigarifo** [comment]
Sorry but i don't have the 32 bit version of the dll, I checked on SysWoW64 without success.

**Comment by binarymaster** [comment]
x86 architecture DLL is required to resolve this issue.

**Comment by WBowley** [comment]
[termsrv-x86.zip](https://github.com/stascorp/rdpwrap/files/2016862/termsrv-x86.zip)
Attached termserv.dll from Windows 10 Pro (x86) version.

**Comment by binarymaster** [comment]
@WBowley this is wrong DLL, build number should be **10.0.15063.994**.

**Comment by fre4kyC0de** [comment]
There is just an x64-version of termsrv.dll 10.0.15063.994.
The offsets are:
```
[10.0.15063.994]
; no x86 version
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8CB01
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=15EA4
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=FAE5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=234DC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.15063.994-SLInit]
; no x86 version
bInitialized.x64      =E9468
bRemoteConnAllowed.x64=E946C
bMultimonAllowed.x64  =E9470
ulMaxDebugSessions.x64=E9474
bFUSEnabled.x64       =E9478
bServerSku.x64        =E9484
lMaxUserSessions.x64  =E9488
bAppServerAllowed.x64 =E948C
```
