### ISSUE TITLE
VPN Disconnect on Second User Login

### ISSUE THREAD

**Issue by darkmoon2** [stascorp/rdpwrap#457]
Windows 10 Version 1709 (OS Build 16299.371)
When the first user who is logged in and already is working, and has a VPN Connection established, if the second user on the machine logs in, the first users VPN Connection is automatically terminated.  Once that users login has completed, the first user can reconnect the VPN and both can work until the next login event.

**Comment by binarymaster** [comment]
This is normal Windows behaviour. To workaround this, the credentials for the VPN connection should be saved for all users.

**Comment by darkmoon2** [comment]
okay thanks for the clarification.
