### ISSUE TITLE
Not supported on windows insider 17133.1

### ISSUE THREAD

**Issue by StoneNimRod** [stascorp/rdpwrap#460]
Hello. This program doesn't work on my windows 10 home insider 17133.1. It's written that: Not listening, [not supported]. 
I don't know what to do (I'm new here).
Thanks

**Comment by binarymaster** [comment]
Duplicate of #442.

**Comment by StoneNimRod** [comment]
Ok thanks. I had problems with permissions, but now I've solved them.
