### ISSUE TITLE
RDWRAP 1.6.2 no longer working with Windows 10 Release 1803

### ISSUE THREAD

**Issue by Crossswiss** [stascorp/rdpwrap#461]
RDWRAP 1.6.2 no longer working with Windows 10 Release 1803

**Comment by mtorrisi** [comment]
Hello.

I'm not sure about the Windows 10 version we've, but as soon I install RDPWrap, Remote desktop service stops and it cannot be restarted again, it says something like: "Error code 5 Access denied".

Uninstalling the wrapper it can be started again.

**Comment by binarymaster** [comment]
Incorrectly filed issue, no termsrv.dll build specified.
