### ISSUE TITLE
access denied when trying RPD check 

### ISSUE THREAD

**Issue by nickmcg02** [stascorp/rdpwrap#462]
![screenshot 4](https://user-images.githubusercontent.com/38920635/39538013-3b34db1c-4e33-11e8-8d3b-d00b20bf240a.png)
There might be something wrong with my zip not sure? 
![screenshot 5](https://user-images.githubusercontent.com/38920635/39538057-61ed87cc-4e33-11e8-9b1a-950236ffb410.png)
This is also the administrator account.

**Comment by binarymaster** [comment]
Consult the `README.md` for "Access Denied" problem.
