### ISSUE TITLE
Socket connection failed but RPD conf looks ok

### ISSUE THREAD

**Issue by nickmcg02** [stascorp/rdpwrap#465]
![screenshot 9](https://user-images.githubusercontent.com/38920635/39578975-87fb92e2-4edd-11e8-903f-dab8ea993ba3.png)

**Comment by tvcat** [comment]
Did you try to connect from another Windows?
What version of installer you are using?
You need the latest version.
Windows Home? Pro?
You need to provide details, no one can help you with just a screenshot.

**Comment by Hurrican666** [comment]
Maybe this is the Error 

Please Help Windows 10 pro NEW UPDATE 1803 today (04.05.2018) doesen´t work with RDP-Wrap...
any Ideas?

**Comment by binarymaster** [comment]
@Hurrican666 stop spamming, or I'll ban you. Track this issue: #456.

**Comment by nickmcg02** [comment]
It turns out I have to interchange which port I use (either 10001 or 3389) Don't know why tbh
