### ISSUE TITLE
Windows 10 Version 1803

### ISSUE THREAD

**Issue by izotecarlitos** [stascorp/rdpwrap#466]
I just tried this on Windows 10 Version 1803 and get this: 

![image](https://user-images.githubusercontent.com/35771489/39611818-f373c5aa-4f17-11e8-941c-4b0ab5304b1e.png)

![image](https://user-images.githubusercontent.com/35771489/39611822-fba23f36-4f17-11e8-8180-356d3229973b.png)

**Comment by F21** [comment]
See #456

**Comment by binarymaster** [comment]
Duplicate of #456.
