### ISSUE TITLE
RDP WRAPPER STOPPED AFTER LAST WINDOWS UPDATE

### ISSUE THREAD

**Issue by Fedomorro** [stascorp/rdpwrap#467]
After updating windows April rdp wrapper stopped working, how to solve?

![rdp](https://user-images.githubusercontent.com/29048745/39646635-75572702-4fb2-11e8-90dd-3d3504b40981.PNG)
![winver](https://user-images.githubusercontent.com/29048745/39646646-7ab2c35a-4fb2-11e8-827d-713de2b70aae.PNG)

**Comment by binarymaster** [comment]
> how to solve?

Look for existing issues. #456

**Comment by tetelom** [comment]
same problem, i cant use after april 2018 update..
