### ISSUE TITLE
Disable multiple users feature.

### ISSUE THREAD

**Issue by FURI0UZ** [stascorp/rdpwrap#468]
Is there a way to disable the multiple users feature?
Thanks for your help.

**Comment by strarsis** [comment]
I guess he has the same issue as I encountered: Apparently users that disconnect don't reconnect to same user session, instead a new user session (of same user) is opened. In the end there are lots and lots of disconnected but still running user sessions in task manager that have to be terminated manually. CPU ramps up with all these left over sessions.

**Comment by xfjx** [comment]
If that is the course for the question you can try this setting in RDPConf

![image](https://user-images.githubusercontent.com/10652613/39667743-17a31e34-50bd-11e8-9e0f-90d4a399e635.png)

**Comment by strarsis** [comment]
@xfjx: So when the user already exists and a login with same user is tried, access is denied.
But this doesn't reconnect the client to an existing session.
This issue seems to be new (April update?) that 
disconnected sessions pile up in task manager (and consume CPU).

**Comment by xfjx** [comment]
It should log you into your old session. Works for me with latest update.

**Comment by FURI0UZ** [comment]
Sorry, I wasn't clear in my question before...
But it's what strarsis said. In a Windows 10 Single Language, disconnected sessions were piling in task manager. 
I'd like to disable the concurrent sessions too, because in a pc with two users. If User-A is physically logged in, User-B can log through a new rdp session. 
Sometimes we need to update many files of a program through a User-B session, but if User-A starts using it, this will crash the update.
We normally do this with Win10 Pro PCs, but only this one is a Home/Office "Boss" Pc

**Comment by xfjx** [comment]
Try the setting I posted earlier. Here is how it looks when you reconnect. I still have multiple sessions cause I enabled the setting after I already logged in several time.

![image](https://user-images.githubusercontent.com/10652613/39671130-9f63a2b2-5112-11e8-9878-fd1c3bbfb448.png)

**Comment by mOrfiUs** [comment]
hi all. This question is for @xfjx . You have the same update, but yours is [fully supported]. I work with rdpwrap before two years and after windows update, just run update.bat and works fine, but after Windows 10 April 2018 Update, dont work. Have you the last windows update?, please see my last issue.

**Comment by xfjx** [comment]
maybe close the issue if it is solved? there are so many open issues because of the latest windows upgrade already...

**Comment by FURI0UZ** [comment]
Yes this issue can be closed. I did what you said and it fixed the issue. Thanks.
