### ISSUE TITLE
What do I do with the updated file.ini

### ISSUE THREAD

**Issue by Kryxxxuz** [stascorp/rdpwrap#470]
Hello everyone, first of all thank you very much for this RDP that has solved so many "problems" for some Windows users, what happens is that I have windows 8.1 with 6.3 9600 and the RDP does not work, it shows me as "Not Supported", then I read a bit, and it says to update the rdpwrap.ini with some new parameters, then download the files and I did, now, what should I do with these files? You have to pack them? How to do it? with what software does that, I'm sorry I'm not very expert in this, I would greatly appreciate your help.
![screenshot_1](https://user-images.githubusercontent.com/35381725/39667549-b3720530-507e-11e8-9a48-3856d13cfe6f.png)

**Comment by binarymaster** [comment]
This is bug tracker, not forum for discussions.

**Comment by Kryxxxuz** [comment]
where i can find the forum for this question?
