### ISSUE TITLE
RDPWrap on Win10Home build 1803 listening but not connecting

### ISSUE THREAD

**Issue by gldmeier** [stascorp/rdpwrap#471]
I have replaced the termsrv.dll and rfxvmt.dll files and I have the rdpwrap program in listening state (and fully supported). I have checked with netstat that the port I configured (4222, though I tried with others as well) is listening. I have turned off my firewall and antivirus, just to try.I test it with rdpcheck and the rdp connection opens up and I can connect internally.

however, when I try to connect using rdp from an external computer it gets stuck on initiating remote connection and never opens a connections.

any suggestions?

**Comment by binarymaster** [comment]
> Win10Home build 1803

Duplucate of #456.
