### ISSUE TITLE
Windows 10 v.1803

### ISSUE THREAD

**Issue by altinojoao** [stascorp/rdpwrap#474]
RDP Wrapper not working after recent updates.
Can someone share the solution?

**Comment by miglaranjeira** [comment]
Hi,
After recent windows 10 updates:
![capturar](https://user-images.githubusercontent.com/4007134/39865905-6aadb7ec-5446-11e8-8361-d920a72d7e86.PNG)

Thanks

**Comment by maxsaimon** [comment]
Hi!
DLL files can be modified using any HEX Editor (for example Tiny Hexer).
Find:

8B 99 3C 06 00 00 8B B9 38 06 00 00

Replace With:

B8 00 01 00 00 89 81 38 06 00 00 90

**Comment by binarymaster** [comment]
Duplicate of #456.
