### ISSUE TITLE
Not working after Windows Update

### ISSUE THREAD

**Issue by daniel2029** [stascorp/rdpwrap#478]
Can someone please help me as my computer just installed the new windows update 1803 (17134.48) and now it doesnt work. It says:

Listener state: Not listening [not supported]

Someone please help me

Thanks

**Comment by syaifulnizamyahya** [comment]
Doesnt work for me too. Exactly after windows update.

**Comment by mOrfiUs** [comment]
#456 
please consider close this issue for supress duplicates.

**Comment by binarymaster** [comment]
> I saw that post and tried to see if my issue resolves from that and i found that it does not.

Anyway it's a duplicate issue.
