### ISSUE TITLE
RDP Wrap Win10 Home - Access denied

### ISSUE THREAD

**Issue by Agebrand** [stascorp/rdpwrap#479]
I need to remote access a computer for a course I'm attending, but Microsoft wants me to upgrade to Pro och Enterprise (not happening!) 
I have installed RDP Wrap. Get all green on the RDPConf and when I run RDPCheck I get "Access denied".
I have:
- disabled Win Defender
- added the RDP Wrap file paths to my anti-virus exceptions
- given full access to C:\Program Files\RDP Wrapper (including rdpwrap.dll).
Still nothing.

![image](https://user-images.githubusercontent.com/34568826/39966198-e9a3f77e-56a7-11e8-890f-0a6b2b39250c.png)

![image](https://user-images.githubusercontent.com/34568826/39966219-0f181512-56a8-11e8-8fb1-d446f6140c6f.png)

Could someone pls help?

**Comment by binarymaster** [comment]
See #391.

**Comment by godtang** [comment]
same wrong, doesn't help to me @binarymaster
