### ISSUE TITLE
RDP Wrap Win10 Pro - Cannot acces more than one USER

### ISSUE THREAD

**Issue by melvin770** [stascorp/rdpwrap#482]
Hello, 

Since i did last windows update, i cannot log in with more than one user

1) are you planing to launch a new version of RDP Wrap
2) i any body can help me solve this problem (i am ready to pay i cannot wait)

Thanks for help

**Comment by alcaraz73** [comment]
Melvin, 

replace termsvr32.dll with an older one.

Take a look on this: https://github.com/stascorp/rdpwrap/issues/456

Regards.

**Comment by Bigben83** [comment]
Attached is the latest termsrv.dll 10.0.17134.1
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/2003185/termsrv.zip)

**Comment by alcaraz73** [comment]
Thanks, this version is patched?

**Comment by binarymaster** [comment]
Duplicate of #456.
