### ISSUE TITLE
RDP Stopped working 

### ISSUE THREAD

**Issue by rdpbk** [stascorp/rdpwrap#484]
I had RDP running for almost 8 months now after i used RDPWrap when setting this PC. 

Suddenly, this morning i was not able to connect remotely to this PC. Searching on net i see people reported CredSSP issue causing similar observation. Anyway, i added the registry entries per the remediation steps mentioned elsewhere. That did'nt solve my issue. 

Tried RDPConf and I see the state as attached. The listener state shows as Not Listening. 

Uninstalled and Installed again but no help. Any ideas?

![image](https://user-images.githubusercontent.com/39319381/40089671-f1999eb4-587a-11e8-86f0-71159a5dc9e4.png)

**Comment by binarymaster** [comment]
Duplicate of #456.
