### ISSUE TITLE
Fresh install doesn't work on win 10.0.17134.1 Pro

### ISSUE THREAD

**Issue by FMiot** [stascorp/rdpwrap#486]
Hello,

Thanks for your programm.
I fresh installed Windows 10 and install.bat.
I run update and it's OK
When i launch user domain RDP service state shutdown just after the connexion.
Can you help me ?

Thanks

**Comment by binarymaster** [comment]
I need your:
1. Diagnostics screenshot
2. Termsrv.dll file

**Comment by FMiot** [comment]
Re,

My dll file is in the post.
where i can find the diagnostics ?
Thanks
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/2009106/termsrv.zip)

**Comment by FMiot** [comment]
in complement
![2018-05-16_14h51_52](https://user-images.githubusercontent.com/18003813/40117942-bd91cb7a-5918-11e8-8304-912b75a6ba3b.png)

**Comment by FMiot** [comment]
Other precision.
The service shutdown with domain user not with local user.
Thanks

**Comment by Loonacy** [comment]
After a fresh install and rebooting, logging in locally displays "The remote procedure call failed. [OK]"
Clicking OK returns to the login screen.  Sometimes logging in again shows the same error, sometimes it logs in then shows the desktop.
Connecting remotely sometimes works, but sometimes causes the service to crash.
On a fresh install, RDPConf looks like:

![rdpconf1](https://user-images.githubusercontent.com/154040/40121751-89efe0ce-58df-11e8-9f77-1ce338a76405.png)

After the service crashes:

![rdpconf2](https://user-images.githubusercontent.com/154040/40121792-9f9003c8-58df-11e8-8f61-f2818fe8d86b.png)

**Comment by Loonacy** [comment]
Windows event log shows:

Faulting application name: svchost.exe_TermService, version: 10.0.17134.1, time stamp: 0xa38b9ab2
Faulting module name: termsrv.dll, version: 10.0.17134.1, time stamp: 0xde65cece
Exception code: 0xc0000005
Fault offset: 0x0000000000010e8c
Faulting process id: 0x1ca0
Faulting application start time: 0x01d3ed1d839da636
Faulting application path: C:\WINDOWS\System32\svchost.exe
Faulting module path: C:\WINDOWS\System32\termsrv.dll
Report Id: 8e492f2e-cef7-4e8e-b2b1-ab431482132e
Faulting package full name: 
Faulting package-relative application ID:

**Comment by fxwireless** [comment]
Having the same problem since this morning. Was working fine until the update to 1803_17134.48.

**Comment by binarymaster** [comment]
Ok, I found the problem, fixing...

**Comment by Xhuevox** [comment]
thank you!!!!

**Comment by fxwireless** [comment]
Works fine now! Thank you.

**Comment by FMiot** [comment]
Perfect Thanks you are the best ;-)
Fix

**Comment by stak99** [comment]
Hi all,

Can someone suggest how can I build these fixed code as my RDP wrapper is no longer working after updating windows 10.

Also last release 1.6.2 was on Dec 2017, may I know when you guys are planning the next release? 

Many thanks
Surya

**Comment by svv111** [comment]
Hello.
I have the same error after updates. Windows 10 Pro (1803_17134.137)
I've already tried to reinstall RDP Wrapper v1.62 with updates from 16 May, But still it does not work.
"An internal error has occurred".
I don't understand how can I build these fixed code as my RDP wrapper.
Thank you in advance

**Comment by alvarollt** [comment]
![2019-03-06 2](https://user-images.githubusercontent.com/48291589/53897720-030be180-4037-11e9-930a-985867d535da.png)
Hi,
In a fresh install, I have "Fully Supported" but can't connect differents users at the same time.
Any help?
Thanks in advance.
