### ISSUE TITLE
Add Support remote audio microfon?

### ISSUE THREAD

**Issue by burluckoff** [stascorp/rdpwrap#488]
![default](https://user-images.githubusercontent.com/36870158/40285839-791872e8-5ca9-11e8-9f52-425851c54bbf.png)

**Comment by binarymaster** [comment]
This is built-in feature which is available in Pro editions or higher.

Duplicate of #74.

**Comment by PGilm** [comment]
Yes, but any way to wrap this feature for a Win 7 Home premium edition?
