### ISSUE TITLE
Need INI Update for 10.0.17134.48

### ISSUE THREAD

**Issue by cuzzins** [stascorp/rdpwrap#489]
The latest build has been updated to .48 (there was also a .5) but the INI file does not reference it and the installer just quits on launch.

Out of curiosity, would it make sense to have the last entry be a 'default' of some sort, or is there too much risk involved?

**Comment by binarymaster** [comment]
Please provide a diagnostics screenshot (use `RDPConf`).

**Comment by binarymaster** [comment]
> The latest build has been updated to .48

No, it was not updated - see version on your screenshot.

> MSI installer version and it flashed up briefly and just went away.

Don't use it, it doesn't work in Windows 10 (#377).

Closed as a duplicate of #456.
