### ISSUE TITLE
Add support remote microfone on server 2012, without activate terminal server license.

### ISSUE THREAD

**Issue by burluckoff** [stascorp/rdpwrap#490]
Server 2012. For use remote microfone need add role RD Session Host, but this activate 120 days trial period terminal server.

**Comment by burluckoff** [comment]
After end trial period i cant use remote desktop and in first session.
![screenshot_1](https://user-images.githubusercontent.com/36870158/40428339-b7baffb0-5ea8-11e8-96f7-08a087a909ba.jpg)

**Comment by sebaxakerhtc** [comment]
> For use remote microfone need add role RD Session Host, but this activate 120 days trial period terminal server

Looks like enhancement but this project is abandoned
