### ISSUE TITLE
Add support for 10.0.17134.1

### ISSUE THREAD

**Issue by ingenium13** [stascorp/rdpwrap#492]
![screenshot from 2018-05-23 16-36-00](https://user-images.githubusercontent.com/3280458/40449813-b1cf1a1a-5ea7-11e8-9c90-b65ab5aff3d4.png)

[termsrv_x64.zip](https://github.com/stascorp/rdpwrap/files/2032776/termsrv_x64.zip)

**Comment by binarymaster** [comment]
Duplicate of #456.
