### ISSUE TITLE
Questions about RDPWRAP 1.62 install

### ISSUE THREAD

**Issue by NA6T** [stascorp/rdpwrap#494]
I have to drive 80 miles 1 way the install RDP Wrap on a Windows 10 X64 computer.  I was having problems with the original install because the listerner state of LISTENING, but it also said "NOT SUPPORTED".
I reading through the latest info it looks like RDPWRAP v1.62 has cured this problem?   IS this true..??
I had version 1.61 installed and it 'went to hell' and I couldn't use it.  I started using RDP from Windows and it worked, but only for 1 person,  not a couple.
RDP WRAP was working great until the latest windows updates.   So tell me what I have to do to install it
correctly and use it again...
Thanks,,
Bob Smith

**Comment by NA6T** [comment]
I haven't used github that much, but when I logged in to read any comments it's telling me to 'attach files
by dragging and dropping, selecting them or pasting them......   ALL I NEED TO KNOW IS IF RDPWRAP IS WORKING WITH INSTALL 1.,62 ??????? PLEASE LET ME KNOW,... THANKS BOB SMITH

**Comment by binarymaster** [comment]
Too many words here, but no termsrv version specified at all. Closing as invalid.
