### ISSUE TITLE
Remote desktop can't  connect to the remote computer

### ISSUE THREAD

**Issue by banguyen22** [stascorp/rdpwrap#495]
### System:
Window 10 64bit pro
RDPWrap-v1.6.2
I just installed windows 10 (full driver, no software 3rd party)

### Issue:
RDPWrap work perfect in first time but when I restart my computer and run remote desktop, I get a bug https://i.stack.imgur.com/YXKAg.png . after it alway show this bug 

### I tried:
1) turnoff firewall or rules setup for remote desktop
2) kill session remote desktop (https://itstillworks.com/kill-remote-desktop-sessions-6873735.html)
3) uninstall RDPWrap and reinstall RDPWrap
4) change port
5) **reset, reinstall window and It work but when I restart my computer and run remote desktop, I continues get that bug**
6) Allow remote connections to this computer
7) reset modem IP 
8) Select Private as your network profile
9) Add the IP address and sever name to the hosts file

no working, it always show bug "remote desktop can't connect to the remote computer for one of these reasons: ...."
PLS HELP ME!

p/s:
"RDPCheck.exe" it's working fine

**Comment by guayagua** [comment]
Got the same problem. Anyone can help?

**Comment by binarymaster** [comment]
> "RDPCheck.exe" it's working fine

Then it is not RDP Wrapper problem, use Google and external forums for help and support.
