### ISSUE TITLE
Not listening on Windows 10 Home 1803

### ISSUE THREAD

**Issue by XythQ** [stascorp/rdpwrap#496]
Wrapper state 1.5.0.0 Installed
Service state 10.0.17134.1 Running
Listener State: Not Listening  [Fully Supported]

Was working before 1803 update

**Comment by XythQ** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/2042858/termsrv.zip)

**Comment by jaxjexjox** [comment]
This is broken on Windows 10, 1803 and has been for near a month.

When will the app be updated?

**Comment by Vasik76** [comment]
Faced with issue on 1803 right after update (two hours ago)
system service won't start after applying rdpwrapper 1.6.2 with the newest ini file.
But I resolve it: just add **Full Access** to the both **RDP Wrapper** folder and **rdpwrap.dll** for user
Network Service
So now service is starting and working like a charm!

**Comment by NMCowboy** [comment]
I added Network Service to the RDPWrapper  folder and the .dll inherited the security setting. However I still can't logon with the password defined in the RDP client. I have to leave the passwork blank and then supply it once the connection is made.

**Comment by lars18th** [comment]
> Was working before 1803 update

Then, do this:

- After upgraded to 1803, open CMD with Admin rights and execute:
  "copy C:\Windows.old\Windows\System32\rfx*.dll C:\Windows\System32\"
- Execute then (with Admin rights) the "uninstall.bat" of the RDP-Wrapper.
- After that, re-install it ("install.bat").

With this I do the clean upgrade to 1803 HOME EDITION, and RDP returns to work!
Regards.

**Comment by tnynyn** [comment]
[rfxvmt.zip](https://github.com/stascorp/rdpwrap/files/2054930/rfxvmt.zip)

Windows 10 Home 1803 x64 working here:

1 Stop service:  remote desktop services
2 replace rfxvmt.dll in system32 with the attached dll
3 uninstall.bat
4 install.bat

Note: I am on 64 bit, but only replaced the rfxvmt.dll in system32 folder and did not touch anything in syswow64 folder

**Comment by Furbach** [comment]
i got error access denied

**Comment by jaxjexjox** [comment]
When will the program be updated that just does it all for us? Can't it be done anymore?

**Comment by prototype2118** [comment]
Did everything people have suggested on here and still can't get RDPWrap to work on update 1803.

**Comment by jaxjexjox** [comment]
Same here, what is going on?

**Comment by prototype2118** [comment]
@jaxjexjox obviously update 1803 broke RDPWrap and I'm not sure who knows what exactly is causing it to break.  I do hope someone in the community finds out and issues a patch or new release.

**Comment by jaxjexjox** [comment]
According to this thread and the other one about this though, people have fixed it and got it working, I just can't get the right DLL going or whatever.     Surely if they can do it, the original package can be updated.

**Comment by prototype2118** [comment]
I've tried every single method the ones who have listed what they did to get RDPWrap working again.  None of them worked for me.  I stopped the remote desktop services, I gave network service full control to the RDPWrap folder and dll file, I've uninstalled and reinstalled, & none of it worked.

**Comment by NMCowboy** [comment]
Are all you guys using Windows 10 HOME?

**Comment by greensweater** [comment]
I just installed 1803 update and RDPWrap broke. I ran an admin CMD prompt and ran:

`copy C:\Windows.old\Windows\System32\rfxvmt.dll C:\Windows\System32`

Then did admin uninstall.bat and admin install.bat. RDP came back up immediately.

**Comment by XythQ** [comment]
greensweater's fix worked for me, but I needed to run both installs before it worked properly.

**Comment by prototype2118** [comment]
@XythQ what do you mean both installs?

**Comment by RDPWrapperUser** [comment]
Get a look by : https://github.com/stascorp/rdpwrap/issues/501 (the end of the side/ the last bit-change is important) and before you have you unistall rdpwrapper
And then it works without rdpwrapper by multi rdp user

Sincerley

**Comment by Wootburger** [comment]
Not working for Windows 10 Home 64bit for me.

Neither greensweaters fix, nor patching termserv.dll according to [#501](https://github.com/stascorp/rdpwrap/issues/501) nor the combination of both.

I copied rfxvmt.dll, restarted, executed uninstall.bat, then install.bat. restarted. Still Service not running/not listening.

I patched termsrv.dll version 10.0.17134.1 as stated above, even tried a download of a patched version in case I messed patching up.

Still nothing :-/

Any hints for me?

**Comment by greensweater** [comment]
64-bit Windows 10: https://github.com/stascorp/rdpwrap/files/1236856/rfxvmt.zip
32-bit Windows 10: https://github.com/stascorp/rdpwrap/files/1238499/rfxvmt.zip

These are from https://github.com/stascorp/rdpwrap/issues/194 ... I guess you could review that thread for additional help. There are many other links to rfxvmt.zip you could try (there is one in this thread). You may also need to run update.bat from the installer.

**Comment by Wootburger** [comment]
Will try that asap, thx dude!

**Comment by westsmoker** [comment]
I've got also the error with "Access denied", so i watched in the rdpconf.exe and disabled "single session per user" and now it works

**Comment by jaxjexjox** [comment]
So this still hasn't been updated?  I see it showing 2017 as latest version on the site?

**Comment by prototype2118** [comment]
Ran update.bat after replacing the dll as explained by @tnynyn and now my rdp wrap is working again on Win10 x64 Home.

**Comment by Sp0oner** [comment]
Thanks @greensweater 

I downloaded the 64 bit file. Stopped remote desktop service, copied the file to system32 restarted remote desktop service then ran update.bat then checked using rdpcheck.exe and now all working fine.

I had tried previously from other posts and could never get it working.

**Comment by binarymaster** [comment]
Closing as inactive (probably fixed in master branch).
