### ISSUE TITLE
Question about rdpwrap.dll

### ISSUE THREAD

**Issue by zeb0z** [stascorp/rdpwrap#497]
I took a PC offline (no Internet connection) and found that when I installed rdpwrap 1.6.2, rdpwrap.dll still gets installed.  So my question is, where is it getting installed from?  Is it embedded in one of the installer files like RDPWInst.exe?  Or is it perhaps getting compiled on-the-fly?  Thank you

**Comment by binarymaster** [comment]
> Is it embedded in one of the installer files like RDPWInst.exe?

This.
