### ISSUE TITLE
Not Working In Windows 10 Pro v1804 May 2018 

### ISSUE THREAD

**Issue by rezaf28** [stascorp/rdpwrap#501]
Hi!
i Installed Windows 10 Pro v1804 May 2018  (original Microsoft Site iso release - Microsoft Image Disk).
In my first test, Remote Desktop Service Worked.
but while I install rdpwrap as administrator, Remote Desktop Service not worked
so i uninstalled it, now Remote Desktop Service working.
The problem is not firewall and antivirus, I also checked them
I even changed the file with the following:
```
https://github.com/stascorp/rdpwrap/files/2054930/rfxvmt.zip
```
if rdpwrap installed ==> Remote Desktop Service not working , if you want to start manually , show this Error:
<img src="https://pictr.com/images/2018/06/02/b374c0f9dfddfddd4fb53ada180bc9b7.png" alt="b374c0f9dfddfddd4fb53ada180bc9b7.png" border="0" />

and rdpwrap install result:

<img src="https://pictr.com/images/2018/06/02/c8f5a508db8f1612d4a20842f2b92d8b.png" alt="c8f5a508db8f1612d4a20842f2b92d8b.png" border="0" />

and RDPConf:
<img src="https://pictr.com/images/2018/06/02/8505ea4494f685b5c2abc6872a8adcee.png" alt="8505ea4494f685b5c2abc6872a8adcee.png" border="0" />

dll files (Files that may be used):
```
https://www.dropbox.com/s/vlaqecnwez7h67m/dll.zip?dl=0
```
Another link but the same file(dll.zip):
```
https://ufile.io/s41ro 
```

i tested many ways, and in google searched , but ==>  this problem not fixed!
i download rdp wrap from :

```
https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip
```
//////// System Info

```

///////  OS
Installded From Microsoft Image Disk
Windows 10 Pro v1804 May 2018
OS Name	Microsoft Windows 10 Pro
Version ==>	10.0.17134 Build 17134
Other OS Description  ==>	Not Available
OS Manufacturer ==>	Microsoft Corporation
System Name ==>	DESKTOP-PC
System Manufacturer ==>	ASUS
System Model ==>	All Series
System Type ==>	x64-based PC
System SKU ==>	All
BIOS Version/Date ==>	American Megatrends Inc. 2801, 11/11/2015
SMBIOS Version ==>	2.8
Embedded Controller Version	255.255
BIOS Mode ==>	Legacy
BaseBoard Manufacturer ==>	ASUSTeK COMPUTER INC.
BaseBoard Model ==>	Not Available
BaseBoard Name ==> Base Board
Platform Role ==>	Desktop
Secure Boot State ==>	Unsupported
PCR7 Configuration ==>	Binding Not Possible
Windows Directory ==>	C:\Windows
System Directory ==>	C:\Windows\system32
Boot Device ==>	\Device\HarddiskVolume1
Locale ==>	United States
Hardware Abstraction Layer ==>	Version = "10.0.17134.1"
User Name ==>	DESKTOP-PC\PC
Time Zone ==>	Iran Daylight Time
Installed Physical Memory (RAM)  ==>	8.00 GB
Page File Space  ==>	3.25 GB
Page File	 ==> C:\pagefile.sys
Kernel DMA Protection	==> Off

/////// Local Network Adaptor
Name  ==>	[00000001] Intel(R) Ethernet Connection (2) I218-V
Adapter Type  ==>	Ethernet 802.3
Product Type  ==>	Intel(R) Ethernet Connection (2) I218-V
Installed	  ==> Yes
//////////////////////////////////////////////////////////////////////////

```
**# Fast Answer For This Problem:**
```
https://www.mysysadmintips.com/windows/clients/545-multiple-rdp-remote-desktop-sessions-in-windows-10
```
Solved:
```
Windows 10 Spring 2018 Update (1803) updates termsrv.dll to version 10.0.17134.1. To get back concurrent remote desktop connections, make following changes:

Find:

8B 99 3C 06 00 00 8B B9 38 06 00 00

replace with:

B8 00 01 00 00 89 81 38 06 00 00 90
```

**Comment by Tarocco** [comment]
@rezaf28 this worked for me 👍

**Comment by binarymaster** [comment]
Build `10.0.17134.1` is already added to support, something wrong at your side.

**Comment by devalian** [comment]
somehow my 10.0.17134 will stopped working after 10-15 days. just stopped for no reason. uninstall rdpwrapper and re-install will make it work again, but when installing, it will show 17134 is not supported on install.bat.
