### ISSUE TITLE
Second user can't login due to none working keyboard (10.0.17134.1)

### ISSUE THREAD

**Issue by I-Xenophon-I** [stascorp/rdpwrap#502]
Since the Windows update (10.0.17134.1) a second user can't login anymore since the keyboard is not working. The mouse is working fine but I can't enter the password via keyboard. I had a similar issue in the past but this time the update of rdpwrap.ini does not solve this issue. RDPConf shows that everything is running and fully support also the remote connections are working and everything works as expected with a single user that logs in. Only additional users are not able to login since they can't enter the password.

**Comment by RDPWrapperUser** [comment]
Get a look by : https://github.com/stascorp/rdpwrap/issues/501 (the end of the side/ the last bit-change is important) and before you have you unistall rdpwrapper

Sincerley

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/501
