### ISSUE TITLE
Start Button not working after 10-12 concurrent RDP connections

### ISSUE THREAD

**Issue by astralmaster** [stascorp/rdpwrap#505]
I have RDP Wrapper v1.6.2 installed on Windows Server 2016 Datacenter version 1607,  OS Build 14393.0
with termsrv.dll version 10.0.14393.1737. Whenever more than 10-12 users open a concurrent RDP sessions Start button becomes unresponsive - clicking it does not invoke the start menu. I have had the exact same problem on one of the previous builds of Server 2016 but back then I thought it was due to this specific OS version but now that I've installed this on this newer build it seems unlikely. I know it cant be due to server resource exhaustion since I have 64 GB of ram running on Intel Core i7 8700 and there is no third party software running except the RDP Wrapper itself. Basically it's a fresh install.

**Comment by binarymaster** [comment]
This is not RDP Wrapper issue, but a Windows bug. Contact Microsoft tech support.

**Comment by astralmaster** [comment]
Then why doesn't the same happen with Windows Server 2016 Remote Desktop Services with purchased CAL-s ?

**Comment by binarymaster** [comment]
Even if this is programmatically triggered behaviour, this is out of RDP Wrapper scope and possibilities.
