### ISSUE TITLE
Add support for 10.0.15063.1155

### ISSUE THREAD

**Issue by Yurii84** [stascorp/rdpwrap#506]
Hello!
When windows update to 10.0.15063.1155. rdpwrap stopped working.
I found termsrv.dll only in C:\Windows\System32

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/2101847/termsrv.zip)

**Comment by matheuscanela** [comment]
Hi, 
I am having the same issue with the new version.
Any news?

**Comment by vvburkovsky** [comment]
For me, a temporary solution it's delete kb4284874 to downgrade windows 10 pro

**Comment by zimmerma379** [comment]
Same issue here.  Hoping for a "rdpwrap.ini" update soon.

**Comment by binarymaster** [comment]
Try duplicating an entry in the INI file from 10.0.15063.296 to 10.0.15063.1155 (run `RDPWInst -r` right after that), and check out whether it works for you.

**Comment by zimmerma379** [comment]
![image](https://user-images.githubusercontent.com/30243621/41874149-e0c3d0c0-787b-11e8-96dd-cb4ba247457d.png)

**Comment by Yurii84** [comment]
> Try duplicating an entry in the INI file from 10.0.15063.296 to 10.0.15063.1155 (run RDPWInst -r right after that), and check out whether it works for you.

I try this to, it no working for me

**Comment by Glandos** [comment]
> Try duplicating an entry in the INI file from 10.0.15063.296 to 10.0.15063.1155 (run RDPWInst -r right after that), and check out whether it works for you.

Same here. I've duplicated the two sections (with and without `-SLInit`), the restart is fine, the RDPConf shows only green text, but only one connected user at a time is supported.

**Comment by guebert** [comment]
I'm not sure, if RDP Wrapper will work with Win10 1803 (64 Bit, Pro).

Could somebody clarify this, please?

Has to be anything changed on an running RDP Wrapper configuration under 1703?

**Comment by BashedCode** [comment]
It worked smooth(ish) on 1803.  Once downloaded, install.bat worked as administrator. Then the next step was RDPCheck which didn't work as expected. Then RDPConf ran and showed installed/running/listening. 
It was a fresh install.
Tested to confirm concurrent users.
Thanks for your work!

**Comment by WoolenWang** [comment]
My way to solve this problem is uninstall the windows update (KB4338826),
after success uninstall KB4338826 the Service ver turn to be like this 
![image](https://user-images.githubusercontent.com/3388253/43364160-7df3e412-9347-11e8-9e61-dc83b7be4d37.png)

and it successful support and listen ok

**Comment by MrRobot5000** [comment]
I'm still seeing this issue. Windows 10 1607 and 1709 appear to be fine. 1703 however is still showing as not a supported version of terminal services.

**Comment by CookiePLMonster** [comment]
Any news? Seems like plenty of people are affected, and uninstalling updates is a sub-optimal solution.

**Comment by binarymaster** [comment]
@CookiePLMonster the project is open source and anybody is welcome to contribute. I'm busy with other projects right now.

**Comment by CookiePLMonster** [comment]
Looking at the INI file, are x64-only submissions even accepted? If not, how one would get into obtaining this specific DLL file in x86 version from that specific build?

**Comment by binarymaster** [comment]
> are x64-only submissions even accepted

Yes, but it would be more preferable to add both.

> how one would get into obtaining this specific DLL file in x86 version from that specific build?

Either you have some x86 machines with Windows 10 installed, or search in the Internet (sometimes I use WZor's UUP archives).

**Comment by fre4kyC0de** [comment]
x64 offsets (no x86 version):

[10.0.15063.1155]
; no x86 version
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8CB01
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=15EA3
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=FAE5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=234DC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.15063.1155-SLInit]
; no x86 version
bInitialized.x64      =E9468
bRemoteConnAllowed.x64=E946C
bMultimonAllowed.x64  =E9470
ulMaxDebugSessions.x64=E9474
bFUSEnabled.x64       =E9478
bServerSku.x64        =E9484
lMaxUserSessions.x64  =E9488
bAppServerAllowed.x64 =E948C

**Comment by phrsn** [comment]
Thanks! Works like a charm!

**Comment by MrRobot5000** [comment]
Thanks! It appears to be working!

**Comment by fre4kyC0de** [comment]
corrected one typo
