### ISSUE TITLE
RDP seccond session takes more than one hour to get established after first session

### ISSUE THREAD

**Issue by Rashmi091427** [stascorp/rdpwrap#508]
Hi,
I have issue connecting to 2/more sessions from the same user account with rdpwrap configured on windows 10 machine. Need your help for the same. This is a very urgent requirement and hence please resolve/reply at the earliest.
PFB complete details of the issue described:
1.Windows 10 (64-bit) is configured with RDPWrapper latest version RDPWrap-v1.6.2
2.RDP Wrapper is installed successfully along with Local RDP check being successful.
3.Establish RDP to window-10 with session-1
4.Try to establish RDP to windows-10 with session-2.Now, the second session gets enabled but witht the first session getting disconnected.
5.Wait for some time after the first session is established, say 10min/30min/etc which is variant parameter which I couldn't figure out yet.
6.Now with first session enabled , try to Establish RDP connection for the second time.
7.It's successful and the successive connections are positive.

This is a major issue blocking our application from using multiple sessions which needs to run for weeks.
Kindly resolve the issue at the earliest.

Thanks,
Rashmi C

**Comment by sebaxakerhtc** [comment]
> I have issue connecting

The project was abandoned.
But looks like the problem is on your side, because of no other issues like this.
