### ISSUE TITLE
Allow to start custom programs

### ISSUE THREAD

**Issue by cecov74** [stascorp/rdpwrap#511]
Hi, when I try to connect to RDP launching a program I receive a error "access Denied" "Can't Start the program…."

I have enabled "allow to start custom programs"

![image](https://user-images.githubusercontent.com/19213713/41777944-5711a014-762d-11e8-95f5-6c9dca7045d6.png)
![image](https://user-images.githubusercontent.com/19213713/41778015-99ffadbc-762d-11e8-8a3b-0c7e331f333d.png)

**Comment by binarymaster** [comment]
This is not RDP Wrapper issue, use Google to find out the solution (seems to be related to ACLs).
