### ISSUE TITLE
Wrapper State: Not Installed

### ISSUE THREAD

**Issue by cc86394** [stascorp/rdpwrap#514]
Wrapper State: Not Installed
Service State: Running
Listener State: Listening

When trying to run install.bat and/or uninstall.bat as an admin and through cmd as admin I get the following error: Installer executable not found. Please extract all files from the downloaded package or check your anti-virus. Press any key to continue...

I opened Port 3389
Turned off Bit Defender
Turned off all Windows Firewalls
Turned off Windows Virus & threat protection
Downloaded and extracted 64 Bit rfxvmt.dll, changed file name to rfxvmt.dllOld, then copy and pasted into System32 & SysWOW64
Rebooted...

Issue still persists... Please help!

**Comment by binarymaster** [comment]
Take a screenshot of a folder from which you're trying to install.

**Comment by cc86394** [comment]
![rdp-ss](https://user-images.githubusercontent.com/40697472/42102347-a684e618-7b93-11e8-8717-5ddacf6166f7.JPG)

**Comment by binarymaster** [comment]
@cc86394 do you see `RDPWInst.exe` here? I don't.

**Comment by cc86394** [comment]
I do not

**Comment by binarymaster** [comment]
So, fix this problem.
