### ISSUE TITLE
At first it works, but then...

### ISSUE THREAD

**Issue by Olegtopchiy** [stascorp/rdpwrap#515]
Help me pls, at first launch that all works good, but then i disabled option for rdp in "My computer" and now i cant connect to terminal...why? 

That's some screen's, all settings is good, but i can't connect to terminal across static IP.

![image](https://user-images.githubusercontent.com/34839972/42114946-b21f9a34-7bf9-11e8-9f3d-493427718ae7.png)

One more thing...across  RDPCheck.exe - connecting successfully, but not from client terminal
![image](https://user-images.githubusercontent.com/34839972/42115003-f323b0c4-7bf9-11e8-9a42-2205fc74c3a0.png)

**Comment by binarymaster** [comment]
> i disabled option for rdp in "My computer" and now i cant connect to terminal...why?

Because.

**Comment by Olegtopchiy** [comment]
> Because.

No-no, then i turned it ON again


Я потом включил обратно, забыл это указать

**Comment by binarymaster** [comment]
Try to reinstall it.

**Comment by Olegtopchiy** [comment]
> Try to reinstall it.

У тебя есть вк\телега? Можешь дать контакт? 
Я пробовал переустанавливать, не помогло.

**Comment by binarymaster** [comment]
Make sure you reinstalled it correctly (run `uninstall.bat` and then `install.bat`).

**Comment by Olegtopchiy** [comment]
> Make sure you reinstalled it correctly (run uninstall.bat and then install.bat).

Yes, it was correctly, 100%

**Comment by binarymaster** [comment]
> One more thing...across RDPCheck.exe - connecting successfully, but not from client terminal

Then you have a problem in port mapping / firewall - software one or hardware - router/switch.

**Comment by Olegtopchiy** [comment]
> Then you have a problem in port mapping / firewall - software one or hardware - router/switch.

Port working correctly, i checked it

![image](https://user-images.githubusercontent.com/34839972/42116490-148a75f8-7c00-11e8-93f5-4df362338241.png)

**Comment by binarymaster** [comment]
If RDPCheck works without issues, there is some networking problem at your side. Either you're entering wrong IP into the client, or something else.

I cannot help you in this question.

**Comment by Olegtopchiy** [comment]
>  Either you're entering wrong IP into the client, or something else.
I'm entering same IP like at first time, when all worked fine.

**Comment by binarymaster** [comment]
Since RDPCheck works, this is actually not RDP Wrapper issue, and should not be discussed here.
