### ISSUE TITLE
Will not install in windows 10

### ISSUE THREAD

**Issue by fletchg** [stascorp/rdpwrap#517]
Does this software still work with windows 10?.
Windows blocked it on the first attempt, but I did not get the error message.
Now it starts to install and then just quits.

Thanks.

**Comment by aubreybailey** [comment]
possible duplicate? Please check your build number and see if it matches.
https://github.com/stascorp/rdpwrap/issues/506

**Comment by MrRobot5000** [comment]
I believe the issue you could be seeing is from Windows 10's June updates. I believe I've read that terminal services was updated and from what i can see once a machine has received June's cumulative update RDP wrapper will no longer function.

**Comment by binarymaster** [comment]
Issue description does not contain any information, closed as invalid.
