### ISSUE TITLE
RDP will not log in (password incorrect)

### ISSUE THREAD

**Issue by gunz2000** [stascorp/rdpwrap#519]
Hello, I just installed RDPWrap on Windows 10 Home, after messing around with the Not Listening issue it seems to be working, now I try to connect to the computer I get the log on screen on the remote desktop and it keeps telling me the password is in correct, I have changed the password and tried all sorts of things like shutting off the firewall and still can not connect 
has any one ran across this issue 
thanks

**Comment by aubreybailey** [comment]
This happens when you have multiple users logged in and network level authentication enabled on the new build.
Turn multiple user settings off and you should be able to log in with a single user again.

Related to new build not yet being supported: https://github.com/stascorp/rdpwrap/issues/506

**Comment by binarymaster** [comment]
Closed as inactive.
