### ISSUE TITLE
no audio on the Desktop after connecting to RDP

### ISSUE THREAD

**Issue by MosheL** [stascorp/rdpwrap#520]
I am connecting to RDP on Windows 10 lastest.
after I am connecting with the "stay with remote" (audio), the audio on the local machine is stopped.

the Audio Service is works and WMP (or Chrome) is playing, but no audio or volume.

the workaround for now:
disconnect the remote user

> net stop "Windows Audio"
-- go to sleep, wake up
> net start "Windows Audio"

**Comment by MosheL** [comment]
Tried also:

switch user (via Start Menu) 
logoff / logon

audio did not restored after taken via RDP.

**Comment by YisroelAdler** [comment]
That's a Microsoft issue that's sometimes happening (see here https://answers.microsoft.com/en-us/windows/forum/apps_windows_10-winapps-appscat_music/windows-10-remote-desktop-session-sound-stops-when/40594f6f-933a-4a2e-90cc-388fd4410851 and here https://social.technet.microsoft.com/Forums/en-US/ce4eaa3e-cd48-4280-a3b6-5de1200df2b5/sound-stops-working-after-disconnecting?forum=winserver8gen) nothing to do with RDP Wrapper.

**Comment by binarymaster** [comment]
Not RDP Wrapper issue.
