### ISSUE TITLE
MSTS 6.3.9600.18928 Not supported

### ISSUE THREAD

**Issue by GGGunrunner** [stascorp/rdpwrap#522]
I stupidly ran Windows Update yesterday (which I normally dont), and it updated the TS dlls apparently.

Now I'm getting this in RDPConf:

Wrapper 1.5.0.0 - Installed
Service 6.3.9600.18928 - Running
Listener - Not supported

I'd rather rollback the individual update. Can you guys help me with its number?

**Comment by binarymaster** [comment]
6.3.9600.18928 is already added to support, update your RDP Wrapper installation.
