### ISSUE TITLE
Termservices stops everytime a new user logs into remote desktop

### ISSUE THREAD

**Issue by BaseofGrace** [stascorp/rdpwrap#523]
Had the 1.62 version of RDP wrapper, the check says everything is fine., but suddenly today can't access with more than one user the termservices stops and has to be restarted.
Any ideas?

**Comment by binarymaster** [comment]
Retry with latest version (please uninstall first, and then install).

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
