### ISSUE TITLE
Project Does Not Load Correctly in Delphi 10.2 Community Edition

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#527]
Hello,

If I load the project in Delphi 10.2 CE a dialog indicates that it can't find the MsRdpClient2 class. This seems to be generated by the form loader. Hitting "Ignore" will mangle the project so that it loads but does not work (the form no longer contains the aforementioned component). If the user instead hits "Cancel" the definition in the .dfm file will be kept. The form can't be viewed either as a form or as text, but attempting to run the project will work assuming the type library export has been made.

I'm not really sure what to do from here, can anyone else try to get the project working? After importing the ActiveX component I am unable to find it in the component palette. The CE edition webpage doesn't say a great deal about missing functionality; all that is missing should be Linux support and remote database support.

**Comment by binarymaster** [comment]
You should add/register mstscax.dll ActiveX component to your IDE.

**Comment by sebaxakerhtc** [comment]
Closed as solved
