### ISSUE TITLE
10.0.17134.191 supported or not?

### ISSUE THREAD

**Issue by Spongman** [stascorp/rdpwrap#529]
i'm running win10 x64 10.0.17134.191

when i run `install.bat` most everything worked, but it did say:
```
[-] This version of Terminal ervices is not supported.
```

however, RDPConf says it's `[fully supported]':
![image](https://user-images.githubusercontent.com/1088194/43292179-18756580-90e9-11e8-9e33-961ec17eb43b.png)

`update.bat` says everything is up-to-date.

needless to say, it's not working now.

**Comment by vandenk** [comment]
it works at home :
![191](https://user-images.githubusercontent.com/11425010/43348947-02ab51fa-91fd-11e8-9408-38c66e2e545d.jpg)

**Comment by Spongman** [comment]
did you do something special (more than just run `install.bat`) ?

**Comment by binarymaster** [comment]
Build `10.0.17134.1` is already added to support, something wrong at your side.
