### ISSUE TITLE
Remote Session - randomized keyboard output

### ISSUE THREAD

**Issue by Huppys** [stascorp/rdpwrap#532]
Hi,

I experienced a bug in RDPWrap. 

#### In Short
* After pressing the `Windows key`/`Home key` and typing letters to find something, the keyboard input seems to be randomized. I type `aaa` on the remote client's keyboard and `q3h` shows up on the remote host's search bar.
* I like the option to have concurrent session on one RDP host, like:
    * Another user uses the RDP host PC to work as user `localuser`.
    * I login as user `rdpuser` from another machine.
    * We can both work happily next to each other.  
    * But: The issue described above affects `localuser`, too. He presses `Windows key` to use Windows' search just to see its keyboard randomized, too. 

#### Example with screenshot:  
I just typed `aaa`:  

![image](https://user-images.githubusercontent.com/7705640/43420422-e7e33dd0-9443-11e8-912f-3ebdcf4a92d5.png)

This is my setup:

* I installed RDPWrap on one Windows 10 PC, listening on Port 3389.
    * Installation and configuration were without any problems or red flags.
    * I created a dedicated RDP user called `rdp` on RDP host PC.1
* I'm using the pre-installed (old) Remote Desktop application on another Windows 10 PC.
   * Connection is established with [IP_ADDRESS]:3389
   * Login with user `rdp`.

No issues so far.

I were not able to reproduce the behavior described above by 100%. 

Could this be an issue regarding the separation of keyboard inputs?

**Comment by binarymaster** [comment]
This sometimes happens for me in Windows 7 RDP as well.

It may be RDP Client issue, but usually disconnecting & connecting again helps. Also it may be related to some "sticky" keyboard keys.

Anyway, that's not RDP Wrapper issue.
