### ISSUE TITLE
KB4284874 Disables rdpwrap

### ISSUE THREAD

**Issue by jparduhn70** [stascorp/rdpwrap#534]
Applied KB4284874 to Windows 10 Enterprise computer over the weekend. It immediately disabled the application with the 'not supported' error, and permissions on termserv.ini were locked. Uninstalled the update and the application works again. I wanted to post an FYI for anyone that may be experiencing the same issue.

**Comment by binarymaster** [comment]
Please provide RDPConf screenshot, KB number is not informational.

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
