### ISSUE TITLE
RDPWrap not working 1803 even after I installed the old termserv.dll

### ISSUE THREAD

**Issue by joelduffield** [stascorp/rdpwrap#535]
Windows 10 Pro 1803 was working, even after 1803 until early last week. I use RDPwrap to allow a user to remote in while one is on the console. Everything in RDP Conf shows that it is running fine, but when the user connects it bumps out the console user.

Here was the log file
`>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFE6DA20000
SvcMain:    termsrv.dll+0x000000000000D560
SvcGlobals: termsrv.dll+0x0000000000033260
Version:    10.0.17134.1
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFE6DB11378] bServerSku = 1
SLInit [0x00007FFE6DB12434] bRemoteConnAllowed = 1
SLInit [0x00007FFE6DB12440] bFUSEnabled = 1
SLInit [0x00007FFE6DB11380] bAppServerAllowed = 1
SLInit [0x00007FFE6DB12438] bMultimonAllowed = 1
SLInit [0x00007FFE6DB1137C] lMaxUserSessions = 0
SLInit [0x00007FFE6DB1243C] ulMaxDebugSessions = 0
SLInit [0x00007FFE6DB12430] bInitialized = 1
<<< CSLQuery::Initialize`

And the output of install.bat
`RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.17134.1
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[+] TermService found (pid 11368).
[*] No shared services found.
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[*] Downloading latest INI file...
[+] Latest INI file -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting TermService...
[*] Configuring registry...
[*] Configuring firewall...
Ok.

[+] Successfully installed.
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

Press any key to continue . . .`

Here is the really weird thing I downloaded the old termsrv.dll from https://github.com/stascorp/rdpwrap/files/1963066/termsrv.zip the 1709 version, the installer then says its fully supported, however it still does the exact same behavior. 

I have seen the report of KB4284874 but I cannot see that listed as something I can uninstall from updates.

**Comment by block123456** [comment]
have the same problem win 1803, just everything was ok, now when i connect via rdp, console boot the same user, which connect via rdp, rdpwrap installed, and dll is patched.

**Comment by binarymaster** [comment]
Build `10.0.17134.1` is already added to support, something wrong at your side.

Also note that downgrading termsrv.dll manually is not a good idea, better to rollback the update.
