### ISSUE TITLE
concurrent rdp not working on w10 10.0.17713.1002

### ISSUE THREAD

**Issue by princepsycho** [stascorp/rdpwrap#536]
Hello everyone,

When i install the rdp wrap on windows 10.0.17713.1002 i still have the message saying an user is already logged in....

Do you know how to fix this ?

Regards.

**Comment by binarymaster** [comment]
Please provide RDPConf screenshot, Windows build is not informational.

**Comment by sebaxakerhtc** [comment]
Closed because of missing answer
