### ISSUE TITLE
Add support for build 10.0.17723.1000

### ISSUE THREAD

**Issue by SaJJaDAgEnT47** [stascorp/rdpwrap#537]
the rdp wrapper says not supported and not working **windows 10 build 17723.1000**

**Comment by binarymaster** [comment]
Please provide RDPConf screenshot, Windows build is not informational.

**Comment by SaJJaDAgEnT47** [comment]
![image](https://user-images.githubusercontent.com/16731802/44588021-dd6d6800-a7c9-11e8-9eaa-e9a918683624.png)

**Comment by binarymaster** [comment]
@SaJJaDAgEnT47 now share the termsrv.dll

**Comment by SaJJaDAgEnT47** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/2318724/termsrv.zip)

**Comment by zydream** [comment]
how can I replace the files such as termsrv.dll in windows home version?

**Comment by binarymaster** [comment]
@zydream you **should not** do that, it will break Terminal Services in most cases.

**Comment by zydream** [comment]
@binarymaster but I have the same problem in my win 10 Home version (1803) and some answers say replace the file.
is there a way to use this software in version 1803? (win 10 home)

**Comment by binarymaster** [comment]
@zydream there are only two possible solutions:
- Add support for new termsrv build into RDP Wrapper ini file
- Rollback the update which introduced behaviour change

**Comment by zydream** [comment]
@binarymaster Thank you very much! Btw, Can the latest INI file work with 1803?
