### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by glennpd** [stascorp/rdpwrap#538]
Virustotal.com reports that 31 different AV engines found (v1.6.2) RDPconf.exe and RDPWinst.exe to be infected with a virus.  When I try to download the ZIP file my browser (Vivaldi) warns that it is infected.  When attempting to install RDPWrap my AV quarantines both of these files.  I am using Panda Dome v18.06.00..

**Comment by binarymaster** [comment]
RDP Wrapper files are not infected with viruses, these are false positives.

Duplicate of #277.
