### ISSUE TITLE
Please add support for 10.0.14393.2457

### ISSUE THREAD

**Issue by haba-haba** [stascorp/rdpwrap#542]
![10 0 14393 2457](https://user-images.githubusercontent.com/42865162/44908389-edce9700-ad23-11e8-9152-ea41601528c4.jpg)

Windows 10  1607	LTSB
August 30 cumulative update KB4346783
10.0.14393.2457
Became unsupported

[termsrv-10.0.14393.2457.zip](https://github.com/stascorp/rdpwrap/files/2339754/termsrv-10.0.14393.2457.zip)

**Comment by khmelevskiy** [comment]
Please, update as soon as possible ☹️

**Comment by xaduha** [comment]
@khmelevskiy I had to rollback that update in the meantime, you can do the same.

**Comment by khmelevskiy** [comment]
@xaduha ver 1607 (14393.2457)
After the update was uninstalled, the computer began to reboot cyclically....

**Comment by xaduha** [comment]
Well, that sucks. Worked fine for me.

**Comment by alkila** [comment]
I save that update but restore old termsrv.dll.
It's work.

**Comment by Ivanovic000** [comment]
I have the same problem. Can i update the termsrv.dll library to fix it?

**Comment by alkila** [comment]
Uninstall RDPWrap-v1.6.2
rename new termsrv.dll 10.0.14393.2457 to termsrv0.dll or delete in windows/system32
mov old termsrv.dll 10_0_14393_1737 in windows/system32
Install RDPWrap-v1.6.2

[termsrv_10_0_14393_1737.zip](https://github.com/stascorp/rdpwrap/files/2353519/termsrv_10_0_14393_1737.zip)

**Comment by Bastien59960** [comment]
Hi,, did anyone know why sharing printer is not working with wrapper or termsrv modified ?

**Comment by Ivanovic000** [comment]
@alkila thanks for your help, but i can't do that because i've not the permissions. Anyway i fix the problem uninstalling the last windows 10 enterprise update (i don't remember the build).

**Comment by zzelalex** [comment]
While waiting for the complete solution from the developer you may like to add these lines to your rdpwrap.ini (for x64 systems only):


```
[10.0.14393.2457]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8D781
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=2A3D4
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1B545
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=C920
SLInitFunc.x64=New_CSLQuery_Initialize


[10.0.14393.2457-SLInit]
bServerSku.x64        =E73D0
lMaxUserSessions.x64  =E73D4
bAppServerAllowed.x64 =E73D8
bInitialized.x64      =E8470
bRemoteConnAllowed.x64=E8474
bMultimonAllowed.x64  =E8478
ulMaxDebugSessions.x64=E847C
bFUSEnabled.x64       =E8480

```

**Comment by artsonit** [comment]
> 
> 
> While waiting for the complete solution from the developer you may like to add these lines to your rdpwrap.ini (for x64 systems only):
> 
> ```
> [10.0.14393.2457]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=8D781
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=2A3D4
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=1B545
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=C920
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> 
> [10.0.14393.2457-SLInit]
> bServerSku.x64        =E73D0
> lMaxUserSessions.x64  =E73D4
> bAppServerAllowed.x64 =E73D8
> bInitialized.x64      =E8470
> bRemoteConnAllowed.x64=E8474
> bMultimonAllowed.x64  =E8478
> ulMaxDebugSessions.x64=E847C
> bFUSEnabled.x64       =E8480
> ```
> 
> ![2457](https://user-images.githubusercontent.com/43055218/45337955-64289000-b593-11e8-8be8-b7ba35b3ea0e.PNG)

We try these settings - but RDP service does not start after. Any idea?

**Comment by gamma-577** [comment]
I too got installation message as : 

....
[*] Terminal Services version: 10.0.17134.1
[-] This version of Terminal Services is not supported.
....

But actually, above version of TS is indeed supported. I tested and found working for other (non 3389) ports as well. Just wanted to confirm that.

Thanks!
-Gamma

**Comment by zzelalex** [comment]
> I too got installation message as :
> 
> ....
> [*] Terminal Services version: 10.0.17134.1

Don't you see any difference between 17134 and 14393 numbers?

**Comment by gamma-577** [comment]
> 
> 
> > I too got installation message as :
> > ....
> > [*] Terminal Services version: 10.0.17134.1
> 
> Don't you see any difference between 17134 and 14393 numbers?

I don't know anything about ver 14393.

Thanks!

**Comment by Hubert-Jan** [comment]
I too got the installation message:
[*] Terminal Services version: 10.0.14393.2457
[-] This version of Terminal Services is not supported.

After replacing the ini-file by the one provided by zzelalex RDPConfig says it is fully supported:
![afbeelding](https://user-images.githubusercontent.com/43402893/45740213-0b8d6e80-bbf5-11e8-9fbc-41911d268884.png)

After installing the RDP Wrapper I restarted the system.
Now it is possible to open multiple RDP sessions. But I could not open multiple concurrent sessions. When I do TermService crashes and only the console session stays open.
On another system I can open multiple concurrent sessions, but when I log off from a rdp session TermService crashes. Agian the console session is not affected.

EventViewer tells me not only TermService did crash, but also Cryptographic Services, DNS Client, Workstation, Network Location Awareness and Windows Remote Management terminated unexpectedly.
There is also an Application Error 1000:
_Faulting application name: svchost.exe_TermService, version: 10.0.14393.0, time stamp: 0x57899b1c
Faulting module name: termsrv.dll, version: 10.0.14393.2457, time stamp: 0x5b7e2c17
Exception code: 0xc0000005
Fault offset: 0x000000000002a3af
Faulting process id: 0x3dc
Faulting application start time: 0x01d44fed705ac4f5
Faulting application path: C:\Windows\System32\svchost.exe
Faulting module path: C:\Windows\System32\termsrv.dll
Report Id: e45daa6b-df45-417d-9834-a92c957d32d9
Faulting package full name: 
Faulting package-relative application ID:

Am I doing something wrong or is there still an issue whith RDPWrapper 1.6.2 with rdpwrap.ini provided by zzelalex?

**Comment by fre4kyC0de** [comment]
Will create offsets for all 09/2018 patches soon. Work is in progress

**Comment by noubit** [comment]
Hello,

I'm in version 10.0.14393.2457 and the patch provided by zzlelalex work for me, all the checks by the application are in green.

But from then, termservice service crashes aleatory and I have to wait the service to restart (60000 seconds)

Anyone faced the same problem?

Thanks

**Comment by miltonreg** [comment]
Hi,

I'm having the same behavior as noubit using version 10.0.14393.2457 with the new offsets. The service works fine for some hours, but then it becomes unstable. The RDP service stops without any apparent reason.

Has anyone found a solution to this issue?

Thanks

**Comment by fre4kyC0de** [comment]
Final offsets for 10.0.14393.2457 (all 2018-09 updates now supported).
For more offsets, take a look at https://github.com/fre4kyC0de/rdpwrap

```
[10.0.14393.2457]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=A6248
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8D781
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=36CE5
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=2A3D4
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=31209
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1B545
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=45824
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=C920
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.14393.2457-SLInit]
bInitialized.x86      =C1F94
bServerSku.x86        =C1F98
lMaxUserSessions.x86  =C1F9C
bAppServerAllowed.x86 =C1FA0
bRemoteConnAllowed.x86=C1FA4
bMultimonAllowed.x86  =C1FA8
ulMaxDebugSessions.x86=C1FAC
bFUSEnabled.x86       =C1FB0

bServerSku.x64        =E73D0
lMaxUserSessions.x64  =E73D4
bAppServerAllowed.x64 =E73D8
bInitialized.x64      =E8470
bRemoteConnAllowed.x64=E8474
bMultimonAllowed.x64  =E8478
ulMaxDebugSessions.x64=E847C
bFUSEnabled.x64       =E8480
```

**Comment by miltonreg** [comment]
Hi,

I'm using the latest offsets for 10.0.14393.2457 published by fre4kyC0de, but RDP Services are still crashing unexpectedly when a session is disconnected or terminated. Any idea?

Thanks.

**Comment by scerazy** [comment]
Same here, Cryptographic Services, DNS Client, Workstation, Network Location Awareness and Windows Remote Management terminated unexpectedly randomly on some machines

Sadly not a reliable solution!

**Comment by g0105** [comment]
Сделал все как описано. Но безрезультатно. termsrv.dll на старую не менял.
Очень жду решения!
Did everything as described. But to no avail. termsrv.dll on the old did not change.
Very much I wait for the decision!
![2018-09-25_170529](https://user-images.githubusercontent.com/43577647/46019696-5cb1cc80-c0e5-11e8-812c-dd71b9be4f91.jpg)

**Comment by scerazy** [comment]
Anybody having any more ideas?

**Comment by miltonreg** [comment]
I just have a temporary workaround, until find a real solution. I used WSUS to reject this September's update for my TS running on Windows 2016... Otherwise, the server will continue downloading and installing it automatically.

**Comment by zzelalex** [comment]
I have the same issues.
Replaced the new termsrv.dll with  the old one v. 14393_1737.
Everything is fine as for now.
Waiting for RS5....

**Comment by g0105** [comment]
How to replace the old one in the working Windows without rebooting into safe mode?

**Comment by zzelalex** [comment]
> 
> 
> How to replace the old one in the working Windows without rebooting into safe mode?

1. Uninstall rdpwrap (uninstall.bat).
2. Stop the service (net stop termservice).
3. Take ownership over c:\windows\system32\termsrv.dll ([TakeOwnershipEx](https://www.majorgeeks.com/files/details/takeownershipex.html) or manually).
4. Renave c:\windows\system32\termsrv.dll to something else, like termsrv_2457.dll
5. Copy the old termsrv.dll to the c:\windows\system32\ folder.
6. Restore the ownership of c:\windows\system32\termsrv.dll (it is the new file already).
7. Start the service (net start termservice).
8. Install rdpwrap (install.bat)

Not a complicated task but the physical presence is necessary, you cannot do it via RDP.

**Comment by g0105** [comment]
> Not a complicated task but the physical presence is necessary, you cannot do it via RDP.

Thank you! It is possible and not physically. I can do it on TeamViewer or VNC ....

**Comment by zzelalex** [comment]
> 
> >  TeamViewer or VNC ....
... or Radmin, etc.
If you know this my advice is not necessary, I assume.

**Comment by fixxitarc** [comment]
Where we can found old versions of termsrv.dll for example this version Windows 7 - 6.1.7601.22104? Thank you

**Comment by g0105** [comment]
> 
> 
> > > TeamViewer or VNC ....
> > > ... or Radmin, etc.
> > > If you know this my advice is not necessary, I assume.

No, no, I did not mean to offend. Wonderful description, and I have it all happened. I also wrote about this program TakeOvnersnipEx. Thank you!

**Comment by scerazy** [comment]
That (replacement) works easily for one machine, but not 100's on the network...

**Comment by the0day** [comment]
Can anyone share with termsrv.dll v14393,1737 for 32-bit?

**Comment by scerazy** [comment]
Download .msu & extract it from there?

**Comment by Zaebumba** [comment]
Hi,
I confirm the malfunction.
When I log out these services are stopped: Cryptographic Services, DNS Client, Remote Desktop Services.
It does not happen every time but periodically.

**Comment by scerazy** [comment]
How can we close something that CLEARLY  does NOT work?

**Comment by binarymaster** [comment]
> How can we close something that CLEARLY does NOT work?

I know what I'm doing. So you CLEARLY doing something WRONG.

**Comment by Hubert-Jan** [comment]
Do you mean the RDPWrapper should work correctly with the latest ini file?
I am only one out of several people who did not get RDPWrapper with the latest ini file working correctly on Windows 10.0.14393.2457. (Replacing termsvr.dll by a old one is not a real solution.)
If we all are doing something wrong, I (we) would like to know what.

**Comment by binarymaster** [comment]
> Do you mean the RDPWrapper should work correctly with the latest ini file?

Yes. Update procedure is described in README.

**Comment by Hubert-Jan** [comment]
I have used the latest INI file you have posted today\yestserday. That is working properly on m Windows 10.0.14393.2457 even with Windows security update KB4457127.
If I am correct you have removed the offsets for x86? Then this INI file would not work for everybody.
But for me it works. Thank you very much!

**Comment by binarymaster** [comment]
> @fre4kyC0de could you please also provide link to 10.0.14393.2457 x86 build?

Nvm, I've got it from `Cab_5_for_KB4343884.cab`.
