### ISSUE TITLE
line ending problem

### ISSUE THREAD

**Issue by fre4kyC0de** [stascorp/rdpwrap#543]
When manually downloading an new ini file from this repo (.\res\rdpwrap.ini) using Firefox, the file downloads with UNIX line-ending (<LF>). When copying this file into the installation directory (e.g. "C:\Program Files\RDP Wrapper"), the library fails to work (Listener not listening).
Converting the line-ending to Windows-style (<CRLF>) fixes the problem.

Could you automate this by adding a check, if the ini contains <CRLF> and (if needed) convert all <LF> to <CRLF>?

**Comment by DarthJahus** [comment]
Since this is a Windows software project, I would recommend **committing with CRLF** instead of checking out Windows style / committing Linux style. That would fix the problem.

**Comment by sebaxakerhtc** [comment]
Closed as not actual
