### ISSUE TITLE
Sharing printer on RDP

### ISSUE THREAD

**Issue by Bastien59960** [stascorp/rdpwrap#548]
Hi, did anyone know why sharing printer is not working with wrapper or termsrv modified ?

Thanks
Sébastien

**Comment by SEEDWISHER2** [comment]
I use GOOGLE CLOUD PRINT cause is not working for the moment

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/504
