### ISSUE TITLE
Add support for build 6.3.9600.19093

### ISSUE THREAD

**Issue by antonabits** [stascorp/rdpwrap#549]
August 30, 2018—KB4343891
Applies to: Windows 8.1, Windows Server 2012 R2
[termsrv_6.3.9600.19093.zip](https://github.com/stascorp/rdpwrap/files/2361689/termsrv_6.3.9600.19093.zip)

**Comment by ivanmara555** [comment]
I confirm it's working on win8.1x64_Pro ! Thanks!

**Comment by Lemon-kent** [comment]
![default](https://user-images.githubusercontent.com/43260344/45530406-fae68e00-b7d9-11e8-9895-b88a9652a16f.PNG)
![1](https://user-images.githubusercontent.com/43260344/45530407-fb7f2480-b7d9-11e8-955a-111580448dd5.PNG)
 I still do not get it, I replaced termsrv.dll with yours but everything is not exactly supported

**Comment by ivanmara555** [comment]
DON't replace termsrv.dll!  just add sections from second post to the end of c:\program files\rpd wraper\rdpwrap.ini ... restart or reboot terminal service and start rdpconf.exe again to chek is all correct

**Comment by flaschenpost87** [comment]
![screen](https://user-images.githubusercontent.com/37618337/45620098-4e7c0480-ba84-11e8-96c3-d501a18de81a.png)
I added a section to the end of the file, but the program still writes to me Not Listen

**Comment by DakotaBcn** [comment]
Windows 2012 R2 with same problem, if update the INI the listener state is Not Listening after reboot the service

**Comment by fre4kyC0de** [comment]
x64 and x86 offsets:

[6.3.9600.19093]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B3958
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8AE4E
LocalOnlyCode.x64=nopjmp
SingleUserPatch.x86=1
SingleUserOffset.x86=3F045
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=36BC9
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3D899
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=45305
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=18288
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=5D660
SLInitFunc.x64=New_CSLQuery_Initialize

[6.3.9600.19093-SLInit]
bFUSEnabled.x86       =D3068
lMaxUserSessions.x86  =D306C
bAppServerAllowed.x86 =D3070
bInitialized.x86      =D3074
bMultimonAllowed.x86  =D3078
bServerSku.x86        =D307C
ulMaxDebugSessions.x86=D3080
bRemoteConnAllowed.x86=D3084

bFUSEnabled.x64       =FA054
lMaxUserSessions.x64  =FA058
bAppServerAllowed.x64 =FA05C
bInitialized.x64      =FA060
bMultimonAllowed.x64  =FA064
bServerSku.x64        =FA068
ulMaxDebugSessions.x64=FA06C
bRemoteConnAllowed.x64=FA070

**Comment by rav76** [comment]
Thank you DakotaBcn. It's working now!

**Comment by flaschenpost87** [comment]
Windows 8.1 The program still writes to me "Not Listening". What should I do?

**Comment by flaschenpost87** [comment]
> 
> 
> Hi
> You Have to put code from fre4kyC0de (from line [6.3.9600.19093] to end) to "c:\program files\RDP Wrapper\rdpwrap.ini (at the end of file). Save, and restart termservice
> net stop termservice,
> net start termservice (with local login), or restart computer.
> run RDPConf.exe to check.

I did it all and still get "Not Listening"

**Comment by royshum** [comment]
> 
> 
> > Hi
> > You Have to put code from fre4kyC0de (from line [6.3.9600.19093] to end) to "c:\program files\RDP Wrapper\rdpwrap.ini (at the end of file). Save, and restart termservice
> > net stop termservice,
> > net start termservice (with local login), or restart computer.
> > run RDPConf.exe to check.
> 
> I did it all and still get "Not Listening"

Try rebooting after modified the rdpwrap.ini? In my case I also need to reboot the computer to get it working, simply restart the termservice did not work for me.

**Comment by rav76** [comment]
I try with Srv 2012 R2 (all updates) and it works ok.
Maybe You have to reboot...

**Comment by ericernie** [comment]
When I add  fre4kyC0de  [6.3.9600.19093] to end of INI, then reboot Termsservice stops working, = Not listening. Remote Desktop Service in Services not running.

tried - Uninstall wrapper, re Install, add 19093 line to INI again.   Same problem.
Termservice will not run, Trying to Start/restart TS gives error.

**Comment by ivanmara555** [comment]
try to add fre4kyC0de post  to my ini file  ... reboot ... and all working on my 8.1x64 pro ... !

**Comment by rav76** [comment]
Hi, What ver. RDP Wrapper do you use?
I use 1.6.2, maybe you have old ver. 1.6.0?

**Comment by flaschenpost87** [comment]
> 
> 
> Hi, What ver. RDP Wrapper do you use?
> I use 1.6.2, maybe you have old ver. 1.6.0?

I use 1.6.2, and i try to reboot. Not Listening((((

**Comment by rav76** [comment]
Standard port 3389? 
I use 8585, not default.
Do you have  win 8 pro?
Without Wrapper one remote connection work?

**Comment by flaschenpost87** [comment]
Port 3389. I have windows 8.1 for one language. I do not have a Remote Desktop function.

**Comment by DakotaBcn** [comment]
aplied and reboot server 2012 R2
Service terminal server not work
Insert code in INI, save, rdpconf show listening, but open rdpcheck and no work, service stopped
reboot server, no start service

event viewer show this message (sorry for spanish)

Nombre de la aplicación con errores: svchost.exe_TermService, versión: 6.3.9600.17415, marca de tiempo: 0x54504177
Nombre del módulo con errores: rdpwrap.dll, versión: 1.5.0.0, marca de tiempo: 0x5488aa5a
Código de excepción: 0xc0000005
Desplazamiento de errores: 0x0000000000002953
Identificador del proceso con errores: 0x19d0
Hora de inicio de la aplicación con errores: 0x01d4504d42b99629
Ruta de acceso de la aplicación con errores: C:\Windows\System32\svchost.exe
Ruta de acceso del módulo con errores: c:\program files\rdp wrapper\rdpwrap.dll

**Comment by rav76** [comment]
ok, I attach my INI, win 2012 R2 Fundation, ver. 6.3.9600 Compilation 9600.
You can compare with your.
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/2398621/rdpwrap.zip)
![rdp](https://user-images.githubusercontent.com/43398616/45778717-acae1080-bc59-11e8-89cb-456786a844d7.jpg)

**Comment by fre4kyC0de** [comment]
Could you try this file?
Working fine here (Windows 8.1 Core x64 with all updates)

[rdpwrap_master_justFinal.txt](https://github.com/stascorp/rdpwrap/files/2398869/rdpwrap_master_justFinal.txt)

Please also check, if the file has been saved with <CRLF> line ending (e.g. using Notepad++; Line ending should be "Windows (CR + LF)"). If not, convert it to Windows format.

**Comment by DakotaBcn** [comment]
@rav76  thanks!!! your ini works with mi Win2012 👍

**Comment by ericernie** [comment]
Thanks fre4ky/ rav.
Pasting just 19093 section into existing INI just stopped T/Serv listening didnt work, 
but
rdpwrap_master_justFinal.txt worked for me, Stop T/Service. Cut and Paste to overwrite INI, 
It then needed a Reboot.

**Comment by EliezerBee** [comment]
@flaschenpost87, I tried replacing the contents of the INI file with your file (THANKS!!!) which seems to work:
![config](https://user-images.githubusercontent.com/5578694/46083522-42203780-c167-11e8-8798-e049091f9d2d.jpg)
I rebooted but when I run RDPCheck, it still shows access denied. Please advise. Thanks!

**Comment by rav76** [comment]
> I rebooted but when I run RDPCheck, it still shows access denied. Please advise. Thanks!
Hi
Change: 
Authentication Mode: Network Level Autentication
Session Shadowing: Full access with user's permition.
After reboot you have diagnostics green?

**Comment by EliezerBee** [comment]
@rav76, I tried making those changes but Authentication Mode seems to keep reverting back to GUI Authentication Only. Yes, everything is all green, as shown in my screenshot in my last post (less than an hour ago). When I try RDPCheck, it says my password is wrong (even though it's definitely not) instead of Access Denied like it was saying before...

**Comment by rav76** [comment]
> @rav76, I tried making those changes but Authentication Mode seems to keep reverting back to GUI Authentication Only. Yes, everything is all green, as shown in my screenshot in my last post (less than an hour ago). When I try RDPCheck, it says my password is wrong (even though it's definitely not) instead of Access Denied like it was saying before...

**Comment by rav76** [comment]
@EliezerBee, Do you have admin rights, when you're changing settings?

**Comment by EliezerBee** [comment]
Yes

**Comment by rav76** [comment]
What system?

**Comment by EliezerBee** [comment]
8.1 Pro x64

**Comment by rav76** [comment]
Did you test without wrapper? 
Try uninstall wrapper, check rdp connection.
Rename or delete rdp wrapper folder in program files. Install wrapper 1.62. 
After that, update.cmd, after change file rdpwrap.ini from @fre4kyC0de or me.
Restart windows.
It should be work.

**Comment by rav76** [comment]
Yes, without rdp wrapper.

**Comment by EliezerBee** [comment]
Perfect - thank you! Apparently, remote connections were disabled somehow for the PC in Windows' "Remote Settings".
