### ISSUE TITLE
Add support for version 10.0.17744.1001

### ISSUE THREAD

**Issue by IncognitoJam** [stascorp/rdpwrap#550]
Microsoft Windows 10 Pro
[Version 10.0.17744](https://changewindows.org/build/17744)
(Insider Preview RS5)

termsrv.dll
[10.0.17744.zip](https://github.com/stascorp/rdpwrap/files/2363380/10.0.17744.zip)

**Comment by royshum** [comment]
Not sure if work or not, but maybe someone would try the following?

[10.0.17744.1001]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=772E1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=123EC
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=179CF
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1D8AC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.17744.1001-SLInit]
bServerSku.x64        =EBAB4
lMaxUserSessions.x64  =EBAB8
bAppServerAllowed.x64 =EBAC0
bInitialized.x64      =EBAB0
bRemoteConnAllowed.x64=EBAC4
bMultimonAllowed.x64  =EBAC8
ulMaxDebugSessions.x64=EBACC
bFUSEnabled.x64 =EBAD0

**Comment by alexlovar** [comment]
> Not sure if work or not, but maybe someone would try the following?
> 
> [10.0.17744.1001]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=772E1
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=123EC
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=179CF
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1D8AC
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.17744.1001-SLInit]
> bServerSku.x64 =EBAB4
> lMaxUserSessions.x64 =EBAB8
> bAppServerAllowed.x64 =EBAC0
> bInitialized.x64 =EBAB0
> bRemoteConnAllowed.x64=EBAC4
> bMultimonAllowed.x64 =EBAC8
> ulMaxDebugSessions.x64=EBACC
> bFUSEnabled.x64 =EBAD0

yes, Works

**Comment by CaseyRedisAtWork** [comment]
This is working for me as well, thanks!

**Comment by CaseyRedisAtWork** [comment]
As it turns out, it's not surviving a restart of the RDP service.  It starts, then stops with an error in the event log.  Had to uninstall again to get RDP working.
