### ISSUE TITLE
TrendMicro is reporting HKTL_RADMIN threat for MSI

### ISSUE THREAD

**Issue by kclubb** [stascorp/rdpwrap#553]
I am unsure if this is real, but our company trendmicro will not allow this to install. 

HKTL_RADMIN
October 11, 2015
  Analysis by: Jaime Benigno Reyes
--------------------------------------------------------------------------------
ALIASES:
RemoteAdmin.Win32.RAdmin.tw (Kaspersky), RemAdm-RemoteAdmin. (McAfee)

  PLATFORM:
Windows 2000, Windows Server 2003, Windows XP (32-bit, 64-bit), Windows Vista (32-bit, 64-bit), Windows 7 (32-bit, 64-bit)
  OVERALL RISK RATING:Low
  DAMAGE POTENTIAL:Low
  DISTRIBUTION POTENTIAL:Low
  REPORTED INFECTION:Low
  INFORMATION EXPOSURE:Low
Threat Type: Hacking Tool 
Destructiveness: No
Encrypted: No 
In the wild: Yes 

Minimum Scan Engine:  9.700

FIRST VSAPI PATTERN FILE:  1.291.00

FIRST VSAPI PATTERN DATE:  24 May 2012

**Comment by binarymaster** [comment]
There is a single thread related to all antivirus problems: #277
