### ISSUE TITLE
Win8.1Pro

### ISSUE THREAD

**Issue by DATUC** [stascorp/rdpwrap#554]
rdpwrap Not working this morgning
Windows 8.1 Pro
Wrapper state V: 1.5.0.0
Services state : 6.3.9600.19093
Listner : Not supported
![rdp](https://user-images.githubusercontent.com/26550824/45416340-a75c2f00-b677-11e8-98ff-7e42132aeacc.JPG)

**Comment by binarymaster** [comment]
Duplicate of #549.
