### ISSUE TITLE
Install log shows Service not supported

### ISSUE THREAD

**Issue by bemoons** [stascorp/rdpwrap#557]
Windows 10 LTSB updated recently. I can't log in via RDP with another user.
I tried to reinstall RDPWrapper, install log showed：

RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.17134.1
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[+] TermService found (pid 8236).
[*] No shared services found.
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[*] Downloading latest INI file...
[+] Latest INI file -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting TermService...
[*] Configuring registry...
[*] Configuring firewall...

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/2382379/termsrv.zip)

and I attach the 'termsrv.dll' .
Plz check it ,Thanks a lot for your great work. It's really very useful!

**Comment by binarymaster** [comment]
This is not an issue, since this build was already added to support.

**Comment by bemoons** [comment]
I run update.bat
It showed 
 RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Checking for updates...
[*] Current update date: 2018.05.16
[*] Latest update date:  2018.05.16
[*] Everything is up to date.

But RDPConf still have red [Not supported].

**Comment by binarymaster** [comment]
Please take a screenshot of RDPConf.

**Comment by binarymaster** [comment]
Do you see the difference between 10.0.17134.1 and 10.0.14393.2457? :confused:

**Comment by bemoons** [comment]
Sorry！
Maybe I pasted another computer's install log...
But the attachment is from the same mechine of screenshot.

The right install log is :  

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.14393.2457
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[+] TermService found (pid 6468).
[*] Shared services found: CryptSvc, Dnscache, LanmanWorkstation, NlaSvc
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[*] Downloading latest INI file...

**Comment by binarymaster** [comment]
So, this issue is a duplicate of #542.
