### ISSUE TITLE
Add support for version 10.0.17758.1

### ISSUE THREAD

**Issue by AKuHAK** [stascorp/rdpwrap#560]

**Comment by nraggett** [comment]
Adding termsrv.dll for this build for support.
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/2436238/termsrv.zip)

**Comment by binarymaster** [comment]
Why closed? This issue is not resolved yet.

**Comment by sebaxakerhtc** [comment]
> 
> 
> Why closed? This issue is not resolved yet.

Looked inside. The version of termsrv.dll is 10.0.17763.1 and it is supported by your *.ini
