### ISSUE TITLE
Keep getting Unknown Error 0x4

### ISSUE THREAD

**Issue by Kryptonit3** [stascorp/rdpwrap#571]
I keep getting Unknown Error 0x4 when trying to connect to a offsite PC with RDPWrap running. Restarting computer fixes the issue but it pops up again a week or so later. Any idea how to see what is causing it or how to fix it?

Everything is green across the board.

<img width="454" alt="screen shot 2018-09-30 at 6 10 28 pm" src="https://user-images.githubusercontent.com/5751754/46263366-3b355400-c4dc-11e8-9a87-7030d449b580.png">

Thanks!

**Comment by binarymaster** [comment]
Contact Microsoft support, this is not RDP Wrapper issue.

**Comment by Kryptonit3** [comment]
Can you point me in the right direction? Google offers no real insight on a solution. I enable TLS / SSL on all connections, maybe that will help. We will see.

**Comment by Kryptonit3** [comment]
@binarymaster I would pay you for a fix for this issue. It seems to be happening once a week now and fixes when I restart the computer. Please help.

**Comment by binarymaster** [comment]
I have no idea how to fix that, because this is not RDP Wrapper issue.
