### ISSUE TITLE
Windows 7 - 6.1.7601.24234

### ISSUE THREAD

**Issue by CZcharlie** [stascorp/rdpwrap#572]
Supported partially

**Comment by binarymaster** [comment]
Which KB update introduces this build?

**Comment by CZcharlie** [comment]
The problem started one week ago.
I had an installed version 1.6.1 , so I tried ver 1.6.2 and no change.








Charlie

**Comment by binarymaster** [comment]
You did not answered my question.

**Comment by CZcharlie** [comment]
Iam sorry, :-)
I was looking for witch update was the last one, but I can not find it
I dont know

**Comment by binarymaster** [comment]
Attach your `termsrv.dll` then.

**Comment by CZcharlie** [comment]
There is last installed KB

**Comment by binarymaster** [comment]
> There is last installed KB

Where?? :confused:

**Comment by binarymaster** [comment]
No I don't.

![image](https://user-images.githubusercontent.com/578406/46285991-1f868800-c586-11e8-8c75-48a8b32c5f3d.png)

**Comment by CZcharlie** [comment]
Oops I answered from mail 🤦‍♂️

**Comment by CZcharlie** [comment]
<img width="176" alt="kb" src="https://user-images.githubusercontent.com/34250213/46286150-55c00980-c57e-11e8-8e69-8abd487664c0.png">

**Comment by binarymaster** [comment]
I couldn't find update package which contains `termsrv.dll` with build number 6.1.7601.24234.

Please upload the file.

**Comment by CZcharlie** [comment]
[termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/2433844/termsrv.dll.zip)

**Comment by CZcharlie** [comment]
how I can download new build ? or when will be it ?

**Comment by kevindaley** [comment]
What are you talking about binarymaster? This has nothing to do with the issue I raised?

**Comment by CZcharlie** [comment]
> What are you talking about binarymaster? This has nothing to do with the issue I raised?

👍

**Comment by yangshuaiqun3211** [comment]
You did not answered my question.
