### ISSUE TITLE
Startup programs for specific session

### ISSUE THREAD

**Issue by Peterthegreat** [stascorp/rdpwrap#573]
Hello,

Is there a way to start some programs only for a specific session? Contrary to issue #546, there are some programs that can run multiple instances over different sessions. I want to start a certain program at startup for a specific user _(already added in USER\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup)_ but it's starting another instance once I open another RDPWrap session (on the same user).

Maybe somebody else had this problem.
Many thanks!

**Comment by binarymaster** [comment]
This is general Windows problem, not related to RDP Wrapper at all. Ask on Windows forums.
