### ISSUE TITLE
Лицензионные соглашения

### ISSUE THREAD

**Issue by Abdula-2015** [stascorp/rdpwrap#576]
Данный **rdpwrap** НЕ нарушает исходный код Windows.

Но на форуме  зашел  спор - нарушает ли ваша программа лицензионные соглашения по Windows?

https://forum.windowsfaq.ru/showthread.php?p=928050&post928050#post928050

**Comment by binarymaster** [comment]
Duplicate of #26.

**Comment by Abdula-2015** [comment]
Duplicate of #26 - и как же окончательный вывод из этого длинного спора?

**Comment by binarymaster** [comment]
Нет вывода.

**Comment by Abdula-2015** [comment]
Спасибо, что отвечаете по русски :)
И как-то удивительно. Ведь в спор вовлечены такие грамотные люди, и они не могут придти к окончательному выводу?
Может, стоит к юристам MS обратится? Уж они-то хай подымут, но вам ведь все равно ничего не грозит, зато может всем пользователям вашего замечательного враппера может будет огромная польза.

**Comment by binarymaster** [comment]
Дело ваше.

**Comment by Abdula-2015** [comment]
Без вашего согласия я их спрашивать  не буду, дабы не накликать на ваш проект гонения.
Наверное, вообще не стоит этого делать, пусть каждый использует его на свой страх и риск.

**Comment by binarymaster** [comment]
> Наверное, вообще не стоит этого делать, пусть каждый использует его на свой страх и риск.

А вот это хорошая мысль, поддерживаю.

**Comment by Abdula-2015** [comment]
Хорошо, да будет так  ;)

**Comment by R030t1** [comment]
At minimum sharing the code is legal in the US. 

Sorry, my Russian is no good yet.
