### ISSUE TITLE
Service state Stopped \\ Listerner state : Not Listening

### ISSUE THREAD

**Issue by Zheruinz** [stascorp/rdpwrap#577]
![image](https://user-images.githubusercontent.com/43809324/46401226-f9e8b280-c72e-11e8-82cf-1f4ae1e2040c.png)

Hi i have been using rdpwrap for several month without any issues but today we found out we're unable to connect to the system. 

the anti virus & the firewall is disabled.

can anyone help how to resolve this please?

**Comment by sblaydes** [comment]
Ran into the same problem after updating to Windows 10 Version 10.0.17763.1. I had to uninstall via the uninstall.bat and reinstall via the install.bat. After doing that RDPConf.exe showed:
Wrapper state: Installed
Service state: Running
Listener state: Listening

I could then connect via RDP from another computer.

Hope that helps.

**Comment by penasanc** [comment]
Hi, I have run uninstall.bat and reinstall via the install.bat. On 8 similar computers it has worked. 1 computer however is not working. 

I have tried to replace the termsvr.dll from the old windows and still is not working.  Any help would be appreciated. Thanks.

**Comment by FOSSFOREVER** [comment]
I hope there's a new release soon to address the Microsoft 10 1809 update. I rely on this wrapper and am very happy with it.

**Comment by binarymaster** [comment]
Closing as inactive (and seems like solved).

**Comment by Magissia** [comment]
Could reproduce with same version.

Service does not start when wrapper is applied, uninstalling the wrapper allows the service to start.

Please provide instruction to send logs that would be useful to you.

When in this state, your scripts all get "access denied" errors (0x5) interacting with service stop/start.

Disabling Kaspersky isn't much of help.

There is actually an error happening : 

18:51:03,3934538	svchost.exe	10912	CreateFile	C:\Program Files\RDP Wrapper\rdpwrap.dll	ACCESS DENIED	Desired Access: Read Data/List Directory, Execute/Traverse, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: n/a, ShareMode: Read, Delete, AllocationSize: n/a

Upon inspection, the rdpwrap.dll sole ACL is administators group full control, network service has no read permission on it, adding it manually suffice.

Maybe the installer could enforce read permission on this file to be on the safe side ?
