### ISSUE TITLE
Please add support for Windows 10 1809 - 10.0.17763.1

### ISSUE THREAD

**Issue by redskilldough** [stascorp/rdpwrap#578]
Please add support for Windows 10 1809 - 10.0.17763.1. I have attached the termsrv.dll file. Thanks
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/2441419/termsrv.zip)

**Comment by ZhenlyChen** [comment]
I find the offset for x64, but I don't know how to use it.

```
[10.0.17763.1-SLInit]
bInitialized.x64      =ECAB0
bServerSku.x64        =ECAB4
lMaxUserSessions.x64  =ECAB8
bAppServerAllowed.x64 =ECAC0
bRemoteConnAllowed.x64=ECAC4
bMultimonAllowed.x64  =ECAC8
ulMaxDebugSessions.x64=ECACC
bFUSEnabled.x64       =ECAD0
```

**Comment by Serhiy2018** [comment]
> I find the offset for x64, but I don't know how to use it.
> 
> ```
> [10.0.17763.1-SLInit]
> bInitialized.x64      =ECAB0
> bServerSku.x64        =ECAB4
> lMaxUserSessions.x64  =ECAB8
> bAppServerAllowed.x64 =ECAC0
> bRemoteConnAllowed.x64=ECAC4
> bMultimonAllowed.x64  =ECAC8
> ulMaxDebugSessions.x64=ECACC
> bFUSEnabled.x64       =ECAD0
> ```
> It always is not listening

Doesn't work for my 10 1809 - 10.0.17763.1

**Comment by ZhenlyChen** [comment]
@Serhiy2018 Doesn't work for my 17763 too, but this offset should be right

**Comment by Zaebumba** [comment]
It may not be right.
I think there should be two sections:

[10.0.17763.1]
and
[10.0.17763.1-SLInit]

**Comment by ZhenlyChen** [comment]
@Zaebumba  you are right, but I don't know how to modify `DefPolicyPatch`, other should be right.
```
[10.0.17763.1-SLInit]
bInitialized.x64      =ECAB0
bServerSku.x64        =ECAB4
lMaxUserSessions.x64  =ECAB8
bAppServerAllowed.x64 =ECAC0
bRemoteConnAllowed.x64=ECAC4
bMultimonAllowed.x64  =ECAC8
ulMaxDebugSessions.x64=ECACC
bFUSEnabled.x64       =ECAD0

[10.0.17763.1]
;.text:000000018007793A                 js      short loc_18007795B
;.text:000000018007793C                 cmp     [rsp+48h+arg_18], 0
;.text:0000000180077941                 jz     short loc_18007795B <- jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=77941
LocalOnlyCode.x64=jmpshort
;.text:0000000180013221                 push    r15
;.text:0000000180013223                 sub     rsp, 20h
;.text:0000000180013227                 xor     ebx, ebx
;.text:0000000180013229                 mov     dword ptr [rax+8], 1 <- Zero
;.text:0000000180013230                 lea     rsi, [rcx+6F0h]
;.text:0000000180013237                 mov     [rax+18h], rbx
SingleUserPatch.x64=1
SingleUserOffset.x64=1322C
SingleUserCode.x64=Zero
;before
;.text:0000000180017F3D                 mov     [rdx], eax
;.text:0000000180017F3F                 mov     eax, [rcx+638h]
;.text:0000000180017F45                 cmp     [rcx+63Ch], eax 
;.text:0000000180017F4B                 jz      loc_18002ABD0
;after
;.text:0000000180017F3D                 mov     [rdx], eax
;.text:0000000180017F3F                 mov     eax, [rcx+638h]
;.text:0000000180017F45                 mov     eax, 100h
;.text:0000000180017F4A                 mov     [rcx+638h], eax
;.text:0000000180017F50                 nop
; I don't know how to modify it
DefPolicyPatch.x64=1
DefPolicyOffset.x64=17F45
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1ABFC
SLInitFunc.x64=New_CSLQuery_Initialize
```

**Comment by saurav-biswas** [comment]
Doesn't work for my 10 1809 - 10.0.17763.1

**Comment by G-UK** [comment]
This works for me

```
[10.0.17763.1]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=77941
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=132F9
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=17F45
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1ABFC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.17763.1-SLInit]
bInitialized.x64      =ECAB0
bServerSku.x64        =ECAB4
lMaxUserSessions.x64  =ECAB8
bAppServerAllowed.x64 =ECAC0
bRemoteConnAllowed.x64=ECAC4
bMultimonAllowed.x64  =ECAC8
ulMaxDebugSessions.x64=ECACC
bFUSEnabled.x64       =ECAD0
```

**Comment by docikstorm** [comment]
> [10.0.17763.1] LocalOnlyPatch.x64=1 LocalOnlyOffset.x64=77941 LocalOnlyCode.x64=jmpshort SingleUserPatch.x64=1 SingleUserOffset.x64=132F9 SingleUserCode.x64=Zero DefPolicyPatch.x64=1 DefPolicyOffset.x64=17F45 DefPolicyCode.x64=CDefPolicy_Query_eax_rcx SLInitHook.x64=1 SLInitOffset.x64=1ABFC SLInitFunc.x64=New_CSLQuery_Initialize [10.0.17763.1-SLInit] bInitialized.x64 =ECAB0 bServerSku.x64 =ECAB4 lMaxUserSessions.x64 =ECAB8 bAppServerAllowed.x64 =ECAC0 bRemoteConnAllowed.x64=ECAC4 bMultimonAllowed.x64 =ECAC8 ulMaxDebugSessions.x64=ECACC bFUSEnabled.x64 =ECAD0

For me not work :(

**Comment by lotniak** [comment]
> 
> 
> This works for me
> 
> ```
> [10.0.17763.1]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=77941
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=132F9
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=17F45
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1ABFC
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.17763.1-SLInit]
> bInitialized.x64      =ECAB0
> bServerSku.x64        =ECAB4
> lMaxUserSessions.x64  =ECAB8
> bAppServerAllowed.x64 =ECAC0
> bRemoteConnAllowed.x64=ECAC4
> bMultimonAllowed.x64  =ECAC8
> ulMaxDebugSessions.x64=ECACC
> bFUSEnabled.x64       =ECAD0
> ```

It DOES NOT work. Maybe program says "fully supported" but concurrent connections does NOT work.

**Comment by docikstorm** [comment]
sorry i mistake, it's realy working, i forgot restart!
Thanks!!!

**Comment by Julien-nl** [comment]
Thank you all for the support
i am using only the cracked termsrv.dll
does anyone have a working one?

**Comment by binarymaster** [comment]
> i am using only the cracked termsrv.dll

Read README. RDP Wrapper won't work with modified termsrv.dll

**Comment by stefan7n** [comment]
I can't seem to get RDP wrapper working as others here have.

I have win 10 home 1809 update. The conf is all green and suggests it should be working, but still won't connect using remote desktop app from iPhone or mac app.

Tried updating the ini as above, but to no avail.

**Comment by waltw1207** [comment]
Windows 10 1809 has been installed on my computer and now rdpwrapper does not work.  I did change my termsrv.dll to get it to work under the 1803 build.   Can someone send me the non modified termsrv.dll for Windows 10 64 bit please?   And, I also modified the rfxvmt.dll file.   Do I need to ensure I have the unmodified version of this library as well?

**Comment by HanyBarbis** [comment]
How can i replace "termsrv.dll" file its need privilege although an administrator

**Comment by romanad** [comment]
Plz guys help me with workaround, I don't understand where to use offset? what to do?

**Comment by romanad** [comment]
> This works for me
> 
> ```
> [10.0.17763.1]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=77941
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=132F9
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=17F45
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1ABFC
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.17763.1-SLInit]
> bInitialized.x64      =ECAB0
> bServerSku.x64        =ECAB4
> lMaxUserSessions.x64  =ECAB8
> bAppServerAllowed.x64 =ECAC0
> bRemoteConnAllowed.x64=ECAC4
> bMultimonAllowed.x64  =ECAC8
> ulMaxDebugSessions.x64=ECACC
> bFUSEnabled.x64       =ECAD0
> ```

How to use it? Plz?

**Comment by jhugor123** [comment]
could anyone make available the files already set for installation?

thanks

**Comment by taegul** [comment]
rdpwrap.ini file is located at (you can copy and paste the following address to windows explorer)
- 64bit
%ProgramFiles%\RDP Wrapper
- 32 bit (probably/not tested)
%ProgramFiles(x86)%\RDP Wrapper

You need to modify rdpwrap.ini to match your windows version ( I only tested with my version 10.0.17763.168)
Your windows version can be found using RDPConf.exe -> ver

In your rdpwrap.ini file, if you recently installed rdpwrap, then you may have already the INI info which you mentioned. If you don't, add the INI info to the at the end of rdpwrap.ini file.
[10.0.17763.1]
xxxx
[10.0.17763.1-SLInit]
xxxx

Now, I assume your windows version is 10.0.17763.abc, then you need to change
[10.0.17763.1]  -> [10.0.17763.abc] 
[10.0.17763.1-SLInit] -> [10.0.17763.abc-SLInit]

After saving, restart the RDP service by executing the following command
RDPWInst.exe -r

I suspect this method is only working for the same big(?) build (10.0.17763.xxx)

**Comment by jhugor123** [comment]
**romanad**

download source code zip
extract files
edit rdpwrap.ini ( with notepade++ for example )

add the code in res\rdpwrap.ini

[10.0.17763.1]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=77941
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=132F9
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=17F45
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1ABFC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.17763.1-SLInit]
bInitialized.x64 =ECAB0
bServerSku.x64 =ECAB4
lMaxUserSessions.x64 =ECAB8
bAppServerAllowed.x64 =ECAC0
bRemoteConnAllowed.x64=ECAC4
bMultimonAllowed.x64 =ECAC8
ulMaxDebugSessions.x64=ECACC
bFUSEnabled.x64 =ECAD0

>> respect the file structure ( res\rdpwrap.ini )


**now I need to figure out how to generate the files from the source code.

Can someone teach us?**

**Comment by jhugor123** [comment]
taegul, very very thanks for feedback friend, sorry my english.

rdpwrap.ini is a file that is in the folder (res)
that was zipped uncompressed, right?

I was able to enter the data there.

but how do I make the installer?

thanks

**Comment by jhugor123** [comment]
ok ok taegul

C:\Program Files\RDP Wrapper\rdpwrap.ini

i go test

thanks

**Comment by jhugor123** [comment]
help me please

http://prntscr.com/lxuaha
http://prntscr.com/lxuank
http://prntscr.com/lxuate
http://prntscr.com/lxub3i
http://prntscr.com/lxub8o
http://prntscr.com/lxubff
http://prntscr.com/lxubk9

thanks

**Comment by jhugor123** [comment]
I still can not

see https://github.com/stascorp/rdpwrap/issues/623

thanks

**Comment by romanad** [comment]
Thanx Guys it works !!! Windows is useless without RDPwrap !!!

**Comment by rdwray** [comment]
Did all this, RDP connects without showing remote desktop and then just terminates.

**Comment by dmcdivitt** [comment]
When attempting to use RDPWrap, make sure you have all original Windows DLL files with no tweaks or changes. If you have original Windows DLL files with known versions, there is no reason RDPWrap will not work for you, if you have followed the proper installation procedures and have replaced the ini file properly.
