### ISSUE TITLE
Cancel "Same user several sessions"

### ISSUE THREAD

**Issue by mariagil1975** [stascorp/rdpwrap#584]
How do I get it to let me connect several users at the same time, but do not let the same users log in several times.
I have the problem that the same user (for example David) logs in remotely. When you disconnect and reconnect, instead of continuing where you left off, another session opens.
2 sessions of DAVID appear in the task manager. I do not want this but I want to patch the RDP to be able to connect 5 or 6 users at the same time. Thank you.

**Comment by nEON7** [comment]
It's simple, in RDPwrap folder, there is "RDPConf.exe" so run it and set:
tick - single session per user

**Comment by mariagil1975** [comment]
Thanks
