### ISSUE TITLE
How do I update the rdpwrap.ini file?

### ISSUE THREAD

**Issue by mariagil1975** [stascorp/rdpwrap#585]
I have a question, installing RDP Wrapper Library v1.6.2, the ini file is automatically updated?
If I do not have an internet connection at that moment, how do I update the rdpwrap.ini file?

**Comment by binarymaster** [comment]
1. Uninstall RDP Wrapper if it was installed
2. Place rdpwrap.ini along with RDPWInst.exe file in the same directory
3. Perform installation (the installer will use this file)

**Comment by myfingerhurt** [comment]
@binarymaster  Unfortunately, the solution didn't work. 

Here's what you need to do instead:

1.    Open a new `rdpwrap.ini` file and make sure that your version (e.g. `10.0.19041.1566`) is included in the file.
2.    Manually copy the newer version of `rdpwrap.ini` into the `C:\Program Files\RDP Wrapper` folder.
3.    Grant admin permission when prompted.
4.    Overwrite the old `rdpwrap.ini` file with the new one.
5.    Open an administration terminal and run `RDPWInst.exe -r`.
6.    Run `RDPConf.exe` to verify that it's working.

If you're unable to overwrite the old `rdpwrap.ini` file, go to Computer Management, then to Services, Remote Desktop Services, right-click and select Stop. After overwriting the file, restart the Remote Desktop Services.

**Comment by zavaidok** [comment]
I need to update the .ini file on a remote VM. Stopping the RDP service kicks me out, obviously. Can I do a fresh install of RDP Wrapper and make it point to the updated .ini somehow? I'm using this for the updated .ini https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini  
binarymaster's solution didn't work.
Cheers!

**Comment by myfingerhurt** [comment]
@zavaidok 
Try this, but I haven't tested it yet, so you have to test it before using.

```
@echo off
REM elevate permissions
goto check_Permissions

:check_Permissions
net session >nul 2>&1
if %errorLevel% == 0 (
    goto start_Copy
) else (
    goto get_Admin_Permissions
)

:get_Admin_Permissions
powershell Start-Process cmd.exe -ArgumentList '/c', '"net session >nul 2>&1 && echo Administrative Privileges acquired || echo Requesting Administrative Privileges" & pause' -Verb runAs
goto check_Permissions

:start_Copy
REM stop RDP service
net stop termservice
timeout /t 5 /nobreak > nul

REM copy rdpwrap.ini file
copy /y "<source_path>\rdpwrap.ini" "C:\Program Files\RDP Wrapper\rdpwrap.ini"

REM start RDP service
net start termservice
timeout /t 5 /nobreak > nul

```

Note: Replace `<source_path>` with the full path of the folder containing the new `rdpwrap.ini` file.

1.    Save the file with a `.cmd` extension, for example, `copy_rdpwrap.cmd`.
2.    Open Task Scheduler by pressing Win + R and type in `taskschd.msc`, then click OK.
3.    Click on `Create Task` on the right-hand side.
4.    Enter a name for the task, for example, `Copy rdpwrap.ini`.
5.    Go to the `Triggers` tab and click `New`.
6.    Choose `On an event` as the trigger, then click `Custom` and click `New Event Filter`.
7.    Set the following filter parameters:
    -     Log: System  
    -     Source: Service Control Manager  
    -     Event ID: 7045  
8.    Click `OK` to save the filter settings.
9.    Go back to the `New Trigger` window and click `OK` to create the trigger.
10.    Go to the `Actions` tab and click `New`.
11.    Choose `Start a program` as the action and browse to the location where you saved the .cmd file.
12.    Click `OK` to create the action.
13.    Go to the `Conditions` tab and uncheck `Start the task only if the computer is on AC power`.
14.    Click `OK` to save the task.

Now, the task will run every time the Remote Desktop Services are stopped, and it will copy the new rdpwrap.ini file and restart the Remote Desktop Services.

**Comment by lapeshkin** [comment]
> I need to update the .ini file on a remote VM. Stopping the RDP service kicks me out, obviously. Can I do a fresh install of RDP Wrapper and make it point to the updated .ini somehow? I'm using this for the updated .ini https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini binarymaster's solution didn't work. Cheers!

You can't update an existing rdpwrap.ini file, but you can overwrite it by replacing it with a previously prepared file (for example using Far Manager)
