### ISSUE TITLE
Please add support for Windows 7 32-Bit v 6.1.7601.24260 after KB4462923

### ISSUE THREAD

**Issue by DevGitJ** [stascorp/rdpwrap#586]
Hi,

after the last monthly Rollup (KB4462923) multiple user login doesn't work anymore
on my Windows 7 Ultimate 32-Bit with latest RDPWRAP Updates.
RDPConf doesn't show any problems, everything is supported/green

MS Info on updated termsrv.dll
Termsrv.dll,6.1.7601.24234,"1,283,072",13-Aug-18,15:27,IA-64,None,Not applicable

thank you in advance, best regards J

**Comment by binarymaster** [comment]
> RDPConf doesn't show any problems, everything is supported/green

There is nothing to fix then.

**Comment by binarymaster** [comment]
Well, looks like 32-bit version is not added yet, I'll look into that.

**Comment by waltw1207** [comment]
I had the same problem on my windows 10 computer after the 1803 update.   In rdpconf, set the Authentication Mode to GUI Authentication Only.   This resolved the problem for me.
![rdpwrapper](https://user-images.githubusercontent.com/43960007/46738057-5f223380-cc5a-11e8-80e0-4cf9b49b4544.jpg)

Hope this helps!

**Comment by jjwhite77** [comment]
Please add support for 10.0.14393.2906  
Thank You

**Comment by amjara** [comment]
I have the installation of Windows 10 1903, compilation 18362.32, I disabled the firewall, the smart screen and the antivirus and I still can not run multiple users.

**Comment by graig77** [comment]
hi how are you how can i get rdp wrapper for instal
