### ISSUE TITLE
More than 2 users not working on Win7 ver . 6.1.7601.24234

### ISSUE THREAD

**Issue by ZeljkoManjkas** [stascorp/rdpwrap#588]
Hi

After install KB4462923 (SSO KB 3177467) or KB4457139 on Windows 7 Profesional (32bit) RDP works but only for 2 users. Loging 3th user get message that another user must disconnect.

New termserv.dll have version 6.1.7601.24234.
Wrapper is version 1.6.2.

I try uninstall wrapper (RDPWInst -u) and install (RDPWInst -i -o) but problem is still here.
On configuration window in diagnostic section stay [fully supported].

Reverting termsrv.dll to 6.1.7601.18637 RDP works for more than 2 users.

Zeljko Manjkas

**Comment by ZeljkoManjkas** [comment]
I found solution in [#587](https://github.com/stascorp/rdpwrap/issues/587)

**Comment by zoth1985** [comment]
Hello! Please add 6.1.7601.24236

**Comment by yangshuaiqun3211** [comment]
Hello! Please add 6.1.7601.24236
