### ISSUE TITLE
Add support for 17763.55 (released 10/19 by MS)

### ISSUE THREAD

**Issue by millsysbl** [stascorp/rdpwrap#590]
RDP Wrap stopped working after installing latest windows updates KB4464330

**Comment by JEmlay** [comment]
Agreed, needs to be updated for 1809+.  Hopefully it's at least being worked on.

**Comment by belko-letyago** [comment]
I have Windows version 17763.**55**, but termsrv.dll version is 17763.**1**, is it okay?
And rdpwrap is working fine:
![image](https://user-images.githubusercontent.com/3055972/47309630-9a026f00-d63d-11e8-87cc-232f476e01ab.png)

**Comment by JEmlay** [comment]
I have 17763.1 as well via Win10 ENT LTSC.  I'm having mixed results.  Every machine in my building has an INI that says it was updated 10.10.18 but some machines I can connect to and some I can't.  They tell me the other user will be booted.  This has never been a problem before.  Even new installs of 1809 it's hit and miss.  Prior versions of windows all work fine here.

**Comment by belko-letyago** [comment]
Just forgot to say: it's Win10 Home on my screenshot.

**Comment by S1AnGeR** [comment]
Yep. Confirmed issue , on Win 10 (1809)

**Comment by sebaxakerhtc** [comment]
Same as https://github.com/stascorp/rdpwrap/issues/560
