### ISSUE TITLE
Installing MSI

### ISSUE THREAD

**Issue by moaeddy** [stascorp/rdpwrap#591]
been trying to install the msi but not seeing it work. is there any other syntax to make this install than normal MSI installation?

**Comment by binarymaster** [comment]
There was a native installer over the years.

**Comment by moaeddy** [comment]
despite i modify the binary to bypass webroot AV yet it won't allow me to put it on system. it keeps killing it just thought i try the .MSI

By the way, if i want to go with the .MSI i believe it might have someway of installation
