### ISSUE TITLE
Aero design Win 7 Ultimate missing after installation

### ISSUE THREAD

**Issue by michael0815000** [stascorp/rdpwrap#595]
I have installed RDP Wrapper Library 1.6.2 on Windows 7 Ultimate including security update KB4462923.
When any user logs on now at console or with RDP the desktop background is single coloured and the formerly used Windows 7 aero design is not set any longer and cannot be activated any longer.
Unstinstall does not help, only a Windows System restore.
Is this a bug or is it well-known?

Thanks and regards

Michael

**Comment by binarymaster** [comment]
RDP Wrapper have nothing to do with Aero / DWM API, so this is Windows bug.

You may ask for support on Windows related forums.
