### ISSUE TITLE
Single user session not working windows 10 Pro v1803

### ISSUE THREAD

**Issue by increditus** [stascorp/rdpwrap#596]
Hi, I am unable to activate and use this feature: single user session. I have updated the rdpwarapper to the lastest version, runed it as administrator, reinstalled multiple times and even changed the regedit as suggested on another thread from 0 to 1 and still, I can't disable this and stop from having a new session each time. This is really frustrating, each time I connect, I am in a new session. I currently use the workaround of going on the taskbar and select users, but doing this every time is really frustrating and makes it impossible to use. 
Please let me know if there a way to fix, I would appreciate so much and as retribution donate some Bitcoin. 
Really appreciate your work developers! 

Windows 10 Pro v1803
OS 17134.376
Release: 8/09/2018

**Comment by tomas123** [comment]
this is an old bug

some users describe the problem:
https://github.com/stascorp/rdpwrap/issues/422#issuecomment-397284365
https://github.com/stascorp/rdpwrap/issues/513#issuecomment-407696493

see my post for a workaround:
https://github.com/stascorp/rdpwrap/issues/422#issuecomment-398808660

**Comment by estivalinp** [comment]
Same problem in win10 home 1809 17763.615. If you know any way to slove the probleam, please help me, THX!

**Comment by estivalinp** [comment]
> Same problem in win10 home 1809 17763.615. If you know any way to slove the probleam, please help me, THX!

Problem solved in #836

**Comment by sebaxakerhtc** [comment]
Same as https://github.com/stascorp/rdpwrap/issues/422
