### ISSUE TITLE
Support for 1734.285?

### ISSUE THREAD

**Issue by andrePKI** [stascorp/rdpwrap#599]
Installed on 10.0.1734.285. It does wor, but is says
[*] Terminal Services version: 10.0.17134.1
[-] This version of Terminal Services is not supported.

update.bat/RDPWinst -w both tell me

[*] Checking for updates...
[*] Current update date: 2018.10.10
[*] Latest update date:  2018.10.10
[*] Everything is up to date.

Attached is my termsrv.dll
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/2577615/termsrv.zip)

**Comment by binarymaster** [comment]
`10.0.17134.1` is already added to support.
