### ISSUE TITLE
Rdpwrap didn't work on Win10 64bit.

### ISSUE THREAD

**Issue by djgreen-pl** [stascorp/rdpwrap#603]
Hello.
I have windows 10 home "64 bit"
After installing rdwrap, i checking the diagnostics "RDP Wrapper Configuration". Everything is ok.

Wrapper state: Installed - ver. 1.5.0.0
Service state: Running - ver. 10.0.17134.1
Listener state: Listening - [Fully Supported]

Unfortunately, the RDP connection does not work.
I have tried in different ways but nothing works.
Different versions of termsrv.dll.

Is anyone able to help me solve the problem?

**Comment by chineserain** [comment]
You need run the "update.bat" as Administrators, @djgreen-pl ,then run "RDPConf.exe " you will see "full supported".

**Comment by djgreen-pl** [comment]
Welcome back. You're right, my problem was on the firewall side. I checked it at the beginning and there was a rule about passing traffic for RDP. That's why I ignored it. I have removed the rule and re-introduced the rule and it is already good. Sorry for the confusion.
Greetings.
