### ISSUE TITLE
Kaspersky and Remote Desktop Protocol RDP solution

### ISSUE THREAD

**Issue by jul974** [stascorp/rdpwrap#605]
Kaspersky as well-done help.

If you have problems using RDP please check this link :
[https://support.kaspersky.com/13225](https://support.kaspersky.com/13225)
![image](https://user-images.githubusercontent.com/45034867/49567920-2a172200-f927-11e8-8af4-0a032689f977.png)

I also suggest to change the listening port for example : 8888 using RDPCONF instead of 3389.
![image](https://user-images.githubusercontent.com/45034867/49567834-d1478980-f926-11e8-8bca-694644e415d1.png)

When connecting you will have to use colon ":" after IP adress, folowed by the port (here 8888)

Example : on Windows RDP : 
Instead of 
   145.235.128.35  use 145.235.128.35:8888

Instead of 
   Remote-PCName use Remote-PCName:8888 

![image](https://user-images.githubusercontent.com/45034867/49567582-128b6980-f926-11e8-8229-185662d6740a.png)

Hope this will help.

**Comment by binarymaster** [comment]
This is hacky workaround and should be not used. Kaspersky allows to enable remote desktop connections in its network firewall configuration.
