### ISSUE TITLE
Sessions Freez

### ISSUE THREAD

**Issue by Julien-nl** [stascorp/rdpwrap#607]
Dear All,
At Win 10 Build 1809, after i log in sometimes it does works and sometimes not, the sessions freez and i cannot click in anything. i have to close the RDP multiple time and try to log in in order to get it working.
i can ping the remote rdp computer and the ping is continue and no drop time.

**Comment by Julien-nl** [comment]
I've got this working, its appear windows 10 1809 mstsc.exe (10.0.17763.1) and mstscax.dll of windows 1809 (10.0.17763.1) of the client where i am connecting from is the issue.

after replacing those two files from a working 1807 windows stuff start working.
the working build mstsc.exe is 10.0.17134.112
the working build of mstsccax.dll is 10.0.17134.191

i've attached them in case someone else having the same problem.

**Comment by binarymaster** [comment]
So, this is not RDP Wrapper issue.
