### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by Xadzkon** [stascorp/rdpwrap#608]
Hello!
I am trying to install this software on my machine with Windows 7 Professional x64. I have downloaded the .zip file from the releases, then I have followed the installation instructions found on the bottom of the readme.md file, meaning that I have clicked install.bat then when it finished, I have clicked update.bat. The remote desktop connection however still says that there is already a console running on my computer, so I can't connect to it. I have run the RDPCheck.exe file, and it said that it can't connect to the socket. Is this a firewall issue, I don't think it should be, as I am trying to connect to localhost. I have then uninstalled it with the batch file, and downloaded the .msi installer. Upon executing it, after a short time, I got the message "There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor.". The installer doesn't seem to have created any folders in Program Files, but I can't uninstall it in from the Control Panel either, because the same message appears.
Thanks for any help.

**Comment by binarymaster** [comment]
Your issue consist of multiple known issues, so closing as duplicate.

**Comment by Xadzkon** [comment]
I see, but could I ask you to link those issues so I can take a look at them? I don't know which of them to look for.

**Comment by binarymaster** [comment]
> The remote desktop connection however still says that there is already a console running on my computer, so I can't connect to it.

#370

> downloaded the .msi installer. Upon executing it, after a short time, I got the message "There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor.". The installer doesn't seem to have created any folders in Program Files, but I can't uninstall it in from the Control Panel either, because the same message appears.

#377

> I have run the RDPCheck.exe file, and it said that it can't connect to the socket.

Btw. you did not attached a diagnostics screenshot.
