### ISSUE TITLE
Add option to -w to use local server

### ISSUE THREAD

**Issue by scerazy** [stascorp/rdpwrap#609]
As the ini is not kept updated fast enough, I really would like to have option added to -w where one can specify local server for update

**Comment by binarymaster** [comment]
The offline update feature (using predownloaded INI file) was already implemented.

**Comment by scerazy** [comment]
How? Any switch for it?

**Comment by scerazy** [comment]
If you mean this: https://github.com/stascorp/rdpwrap/issues/300
then it seems to only apply to -i

**Comment by binarymaster** [comment]
Yes, just uninstall and install again with new INI file placed along with installer.
