### ISSUE TITLE
Cannot connect to RDP/Putty after RDPwrapper uninstall.bat

### ISSUE THREAD

**Issue by MrARCO** [stascorp/rdpwrap#610]
After i installed RDP wrapper, it worked perfectly fine, no issues whatsoever. But when i deciced i was fine without RDPwrapper, i went and ran uninstall.bat, wich imediately kicked me out of RDP, Putty, etc. My server is not in my home, but in a datacentre. All my data is stored on my VPS, so i have no way to connect to it now. Any tips on how i can reverse this issue? Thank you!

Also, rebooting the server wont work

**Comment by binarymaster** [comment]
So this is a problem with your server, RDP Wrapper uninstallation process couldn't affect other services besides RDP (i.e. Putty / SSH).

Uninstall script disables RDP by default. To overcome that and keep settings, you should have used `RDPWInst -u -k` command.

**Comment by MrARCO** [comment]
Managed to get my data via the Linux FTP Kernel. Had to mount the disks, after i fixed the NTFS state wich was broken. You really should remove the install.bat, lmao
