### ISSUE TITLE
Does not work, the redirected printer w/pro 10, 1809 17763.194

### ISSUE THREAD

**Issue by sagtlt** [stascorp/rdpwrap#614]
Good day! All done as https://github.com/stascorp/rdpwrap/issues/611#issuecomment-447068372 ahhh! The remote connection works, but the redirected printer does not work . I can't print the documents. Ask for help. I'm a loser (beginner) and do not know English

Добрый день! Все сделал как https://github.com/stascorp/rdpwrap/issues/611#issuecomment-447068372. Удаленное подключение работает, но не работает перенаправленный принтер . Не могу печатать документы. Прошу помощи. Я лузер (новичок) и плохо знаю английский язык

**Comment by hajubu** [comment]
# Printer redirection Problem
@sagtit wrote and asked for assistance
Without knowing little abou your physical and logical environment
I suppose it will be hard to get help here.

> Here some infos
---
> Depending on Printer Redirection wanted you should observe certain rules,

> Besides the Main Scenarios Sets you needs the Printer Driver for the OSxx installed before.

> Not all Printer do allow a set up a Network Printer without having an 'local' Driver installed via IP Network.

> In addtion to the 'normal' rules there are some more, when a virtual Printer in VM /Vboxes environment is involved.

> It will be hard for "Beginners" to handle all possible scenarios and conditions

> The physical type of connection (Printer to Machine) may be also a key point

> Also when open the Windows Remotedesktop Connections the Options on the third tab "Local Resources"  and there an the bottom the checkbox for Printer have to be checked.

> in some cases GPO (Group Policy Object) may  be conntrolled by the Administrator of your "Company Environment" , having an influence to "shared" Printer usage.

> Trying to get support in your natural language (russian), will be help to shorten the long way.

> Hope this will at least shed some light on your question.


---

## Scenario Local-Host -> Remote-Client

        +---------+       +---------+
       -+  HOST   +-     -+  CLIENT +-
        +---------+       +---------+

  L1sh  o-+-  Host -+- //  -+- Client -+-o RP2,P2

### Printer on HOST-OS

* Host: wanted is a shared Printer on Host ?
  * Install Printer Driver on/in Host-OS
  * and give permission for "Client-User"

* Host: wanted is a shared Printer on Client ?
  * Have an 'local' Printer Driver on Client
  * with given permission for "Host-User"

---

## Scenario Remote-Client -> Local-Host

        +---------+       +---------+
       -+ CLIENT  +-     -+  HOST   +-
        +---------+       +---------+

 P2,RP2 o-+-Client -+- // -+-- Host  -+-o

### Printer on CLIENT-OS

* Client: wanted is a shared Printer on Client ?
  * Install Printer Driver on/in Client-OS
  * and give permission for "Host-User"

* Client: wanted is a shared Printer on Host ?
  * Have an 'local' Printer Driver on Host
  * with given permission for "Client-User"

---

**Comment by sagtlt** [comment]
All drivers are installed, before Windows update everything worked. Me not understandable far insert P2,P2 o - + - Client - + - / / - + -- Host - + - o

Все драйвера установлены, до обновления Windows все работало. Мне не понятно куда вставить P2,RP2 o-+-Client -+- // -+-- Host -+-o

**Comment by hajubu** [comment]
sagtIt wrote:  All drivers are installed, before Windows update everything worked. 
>Up till now    you did not specify   what the Environment  looks like.

Is the redirection without  „RDP“  Working ?
Or Does the redirection from a host to a RDP Client have no comnection ?
Or is it the otherway around ?
Please explain where your Printer is physically connected ( Host or Client) .
How  the Printer Properties , especially  the ports used  there ( Host and Client)

Do You use an RDP to an VM / VBox ; If „Yes“ which  RemoteTerminal  Manager do you use ?

sagtIt wrote:  Me not understandable for insert
 P2,RP2 o - + - Client - + - /…… / - + -- Host - + - o P1, RP1
Just a Sketch to explain to you  that we can have  2 ‚redirection‘ paths
a) HOST to Client
b) CLIENT to Host

Each Setting Needs a different Approach !
WHAT IS YOURS before the it stopped to work ?

 P1 =   local Printer on HOST
 RP1 = shared Printer on Host //  may be reached from a Client

 P2 = local Printer ON  CLIENT 
 RP2 = shared Printer on CLIENT //  ( may be reached from a Host)

**Comment by sagtlt** [comment]
![2018-12-16_095632](https://user-images.githubusercontent.com/45890717/50050587-015a0e00-0119-11e9-98c5-4f1ab9c040d1.png)

**Comment by sagtlt** [comment]
Microsoft Windows [Version 10.0.17763.194]
I go to a remote server, click print via Adobe Acrobat DC printer, I have a file Explorer window to save the file, but not my computer and the server, the redirection does not work. I press print and nothing happens, everything disappears.
Tried from the server, on the server to be connected remotely ( to check drivers) nothing happens. Not remotely all prints.
I think the problem is that it doesn't redirect.


Microsoft Windows [Version 10.0.17763.194]
Захожу на удаленный сервер, нажимаю печать через Adobe Acrobat DC принтер, у меня появляется окно проводника для сохранения файла, НО не моего копьютера а сервера, перенаправления не работает. Нажимаю печать и ничего не происходит, все пропадает.
Пробовал с сервера, на сервер удаленно подключиться ( проверить драйвера) ничего не происходит. Не удаленно все печатает.
Думаю проблема в том что не перенаправляет.

**Comment by sagtlt** [comment]
> Is the redirection without „RDP“ Working ?

how to check??
как проверить??

**Comment by sagtlt** [comment]
> Or Does the redirection from a host to a RDP Client have no comnection ?

Yes, not redirecting! There is a redirected printer in the lists. Sees, but does nothing

да, не перенаправляет! В списках есть принтер перенаправленный. Видит, но ничего не делает

**Comment by binarymaster** [comment]
This is Windows bug, contact Microsoft support.
