### ISSUE TITLE
.ini parser truncates last value when file has no ending newline

### ISSUE THREAD

**Issue by ksmyth** [stascorp/rdpwrap#619]
Test program:

```
#include "IniFile.h"
#include <stdio.h>

int main(int argc, char** argv) {
	INI_FILE testIni(L"test.ini");
	INI_VAR_STRING test;
	testIni.GetVariableInSection("test", "test1", &test);
	printf(test.Value);
}
```

test.ini

```
[test]
test1 =abc
```

If `test.ini` does not end with a newline, the test program outputs `ab` not `abc`

(I found this bug by trying the .ini in #617)

**Comment by binarymaster** [comment]
This is known bug, but currently we have a workaround in the installer for it (assuming the user wouldn't modify the file directly, but install or update it with installer).

If you have any idea how to fix it, please create a Pull Request. :wink:
