### ISSUE TITLE
Looking for 10.0.17763.195 support

### ISSUE THREAD

**Issue by StarfighterJ** [stascorp/rdpwrap#622]
I can't seem to get 168 to work anymore with is new 195 ver.

**Comment by binarymaster** [comment]
Please post RDPConf screenshot then...

**Comment by StarfighterJ** [comment]
It is all Listening I toggled Authentication Mode around and Now it is working thanks
I was using the 168 RDPWrap.in Zip File to do this this

**Comment by explorerhk** [comment]
> It is all Listening I toggled Authentication Mode around and Now it is working thanks
> I was using the 168 RDPWrap.in Zip File to do this this

Please refer this link, it is working in 194/195 version

https://github.com/stascorp/rdpwrap/issues/606#issuecomment-448832138
