### ISSUE TITLE
RDP config

### ISSUE THREAD

**Issue by moaeddy** [stascorp/rdpwrap#625]
is there anyway to uncheck **SINGLE USER PER SESSION** without running the RDPConfig GUI?

**Comment by binarymaster** [comment]
Via registry:

`reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fSingleSessionPerUser /t REG_DWORD /d 0 /f`

**Comment by moaeddy** [comment]
thanks mate, Merry Xmas and happy new year in advance
