### ISSUE TITLE
Bitdefender killed it?

### ISSUE THREAD

**Issue by Ptyalin** [stascorp/rdpwrap#628]
Hey guys,

I'm trying to set up a workstation with multiple remote desktop applications. 
I had it all running and working with the newest updates aswell.
After I installed Bitdefender it deleted the programm (not all of it tho). So I uninstalled Bitdefender, told him to remove things from quarantine during the process (only rdpwrap install file). Uninstalled rdpwrap and installed it again. However if I try to connect from more than one device it needs to disconnect the other connection. 
Do you have any idea how to get it working again without resetting the whole thing? 
The configuration shows this: [https://user-images.githubusercontent.com/24698494/49691042-3bd90f00-fb4b-11e8-8771-3cdf1086f328.JPG](url) but with network level autification activated

Edit:
since the link to the picture doesnt work, I got it from this thread, was the first one shown and not just linked.
https://github.com/stascorp/rdpwrap/issues/606

**Comment by binarymaster** [comment]
We already have a thread related to antiviruses behaviour against RDP Wrapper.

See #277. Closed as duplicate.
