### ISSUE TITLE
Win10 Pro 1809 update doesn't allow concurrent users anymore.

### ISSUE THREAD

**Issue by okaris** [stascorp/rdpwrap#630]
After updating to 1809, multiple users can't concurrently RDP in. Rolling back to 1803 temporarily solves the issue. Reinstalling after update didn't help.

**Comment by sagtlt** [comment]
Обнови файл rdpwrap.ini
C:\Program Files\RDP Wrapper или [update.zip](https://github.com/stascorp/rdpwrap/files/2729423/update.zip)

https://github.com/stascorp/rdpwrap/issues/606
