### ISSUE TITLE
Win 10 Pro not listening and access denied despite being fully supported

### ISSUE THREAD

**Issue by joecamel** [stascorp/rdpwrap#631]
![capture rdpwrap](https://user-images.githubusercontent.com/190519/50614057-9a28b180-0ead-11e9-802f-c3d58ef61a5e.PNG)

When I run RDP Check I get access denied.  If I try to connect without leaving a session open, I get access denied.  I assume since it is fully supported, the problem is on my end.  I tried replacing rfxvmt.dll, and have correct security access for program folder.  How can I troubleshoot in order to isolate problem?  Any advice will be appreciated.

**Comment by binarymaster** [comment]
Search for "access denied" keywords in readme.

Closing as duplicate.
