### ISSUE TITLE
Looking for 10.0.18305.1000 support

### ISSUE THREAD

**Issue by mmhafez** [stascorp/rdpwrap#632]
Any help would be greatly appreciated please.

**Comment by sagtlt** [comment]
Да очень интересно! Кто пробовал 18305??

Yes, very interesting! Who tried 18305??

**Comment by sagtlt** [comment]
нет героев :)  ???

**Comment by Kommunist7304** [comment]
Тут для релизной ветки уже 2 месяца никак официально не выкатят, а вы для тестовой чего-то захотели.

**Comment by mmhafez** [comment]
Not required any more. Thanks!
