### ISSUE TITLE
Would you plz make local user not locked when remote rdp user login and share same screen?

### ISSUE THREAD

**Issue by BuddhaLotus** [stascorp/rdpwrap#633]
Thus, local user can watch the operations from the remote user for study and education etc.
Thanks for your perfect work on rdpwrap.

**Comment by fragtion** [comment]
This need is better met using screen mirroring software such as TeamViewer, VNC, Radmin etc. I don't think it's possible to share displays with terminal services because each connection is tied to a distinct logon session

**Comment by binarymaster** [comment]
In the Terminal Services there is shadowing feature for that.
