### ISSUE TITLE
RDP Wrapper uninstaller not working?

### ISSUE THREAD

**Issue by gilboz** [stascorp/rdpwrap#634]
Hi I am running windows 10 home version 1809 (which seems to be unsupported) so I decided to uninstall the program and when I used uninstall.bat it seems that it failed to remove the service it created, since after uninstalling I have ran RDPConf.exe and it claims the service state is "Running"

When I run the msi uninstall it fails with an error equal to #377 
Should I remove the service manually from the control panel?
If so, what services have been created during the installation process?

**Comment by binarymaster** [comment]
Just run `uninstall.bat` and remove entries from control panel manually.

**Comment by LegacyTechnologies** [comment]
where do we run uninstall.bat?
