### ISSUE TITLE
RDPWrap 1.6.1

### ISSUE THREAD

**Issue by lafsbg** [stascorp/rdpwrap#642]
Hi after the last Microsoft update to 1809 build.  RDPWrap 1.6.1 stopped working. It was very useful for us. When we start the config it say unsupported. When we start check it says Access Denied. And when we try to use it with RDC from another machine the behavior is like there is no running RDPWrap 1.6.1 It want to disconnect the user
![rdp_wrapper](https://user-images.githubusercontent.com/46814922/51385654-8d9c8e00-1b28-11e9-9f82-981cb4e68bb1.JPG)

**Comment by binarymaster** [comment]
Duplicate of #606.
