### ISSUE TITLE
Загрузка процессора...

### ISSUE THREAD

**Issue by vovka3003** [stascorp/rdpwrap#643]
Вот такое систематически происходит при некотором времени работы в подключенном сеансе:
![default](https://user-images.githubusercontent.com/25551965/51402723-54334500-1b5f-11e9-8caa-15197a6f3c51.png)
Сбрасывается перезагрузкой компьютера :)

**Comment by binarymaster** [comment]
Not RDP Wrapper bug.

**Comment by vovka3003** [comment]
Такое происходит именно при использовании RDP Wrapper. Ни в каких других случаях подобной перегрузки не наблюдается.
