### ISSUE TITLE
Tried all the Fixes I can find for Listener State Not Listening

### ISSUE THREAD

**Issue by Maverick494** [stascorp/rdpwrap#649]
I have replaced the term dll and the rfxvmt as suggested in all the other posts I can find and I still get:

<a href="https://imgbb.com/"><img src="https://i.ibb.co/ZzDwy1b/Broken-RDPWrapper.jpg" alt="Broken-RDPWrapper" border="0"></a><br />

I have uninstalled and reinstalled.  I have stopped and restarted termservice.

What else is there to try?

**Comment by binarymaster** [comment]
Duplicate of #645.
