### ISSUE TITLE
RDP Not listening

### ISSUE THREAD

**Issue by HellMonger** [stascorp/rdpwrap#656]
What I can't understand is the fact that after I tried the recommended solution, which was copying a new rfxvmt.dll to the System32 files and then update RDPWrap, and I tired that but I still can't connect to my desktop via RDPCheck, Any solutions?

**Comment by Aetton** [comment]
#645 
Try this. 
You can find .ini in  %ProgramFiles%\RDPWrap\rdpwrap.ini

**Comment by binarymaster** [comment]
No system information provided in issue description, closing as invalid.

Use Telegram chat for support questions (see readme).
