### ISSUE TITLE
Not working since latest Windows 10 update (KB4487044) (Feb 2019)

### ISSUE THREAD

**Issue by davidboily** [stascorp/rdpwrap#664]
The software is not working anymore since Windows Update of February 2019 (KB4487044) on Windows 10. Here are some pertinent info (using RDPWrap 1.6.2):
![termsrv](https://user-images.githubusercontent.com/18334482/52724389-41a10580-2f7d-11e9-9ce6-851a5f8a37bb.PNG)
![rdpconf](https://user-images.githubusercontent.com/18334482/52724396-42d23280-2f7d-11e9-902e-f1e49d048603.PNG)

**Comment by binarymaster** [comment]
Duplicate of #645.
