### ISSUE TITLE
Update Win10 on 2019Feb12 make RDP Wrapper v1.6.2 cannot use multi user at same time

### ISSUE THREAD

**Issue by SIAMHW** [stascorp/rdpwrap#666]
Update Win10 on 2019Feb12 make RDP Wrapper v1.6.2 cannot use multi user at same time

**Comment by grodish** [comment]
Same problem, i'm trying to uninstall all updates, i hope it will work

**Comment by jereven** [comment]
Same here, I suppose the .ini file needs an update. ;-)

**Comment by grodish** [comment]
I can solve it, uninstalling KB4483458 , KB4486563 and KB4483187 worked for me!
I'm running windows 7

**Comment by binarymaster** [comment]
No exact termsrv.dll build specified in the issue, closing as invalid.

**Comment by SIAMHW** [comment]
How

**Comment by SIAMHW** [comment]
need .ini file  or other help

**Comment by binarymaster** [comment]
@SIAMHW for user support there is Telegram chat link in readme.
