### ISSUE TITLE
add support for Windows 7 build 6.1.7601.24326 (2019-02)

### ISSUE THREAD

**Issue by fre4kyC0de** [stascorp/rdpwrap#668]
As I can't answer to the existing issue (https://github.com/stascorp/rdpwrap/issues/646):

https://github.com/fre4kyC0de/rdpwrap/blob/master/6.1.7601.24326.txt

**Comment by fre4kyC0de** [comment]
https://github.com/stascorp/rdpwrap/issues/646

**Comment by gitgotgone** [comment]
Here's an interim fix:
https://github.com/stascorp/rdpwrap/issues/669

**Comment by joebrug** [comment]
That's a workaround. The fix is getting rdpwrap to work with latest termsrv.dll. thanks @fre4kyC0de will try this tomorrow. Would love to know how you figured it out. I tried following the YouTube without luck.

**Comment by gitgotgone** [comment]
Yeah, fix to the lack of access, not to the software. I don't have nearly the knowledge to fix that!

**Comment by binarymaster** [comment]
Duplicate of #646.
