### ISSUE TITLE
Rollback RDPWrap after Windows update

### ISSUE THREAD

**Issue by gitgotgone** [stascorp/rdpwrap#669]
[Below is for Windows 10 1809 (17763) 64-bit--perhaps others can provide for other OS versions]

Lately it seems like there have been a lot of edits to the termsrv.dll by windows updates, and each time it breaks RDP Wrap. Kudos to the community for providing RDP Wrap updates, but the windows updates are coming too fast for the RDP Wrap updates to keep up.

For those who are desperate for it to work, here are instructions and files (termsrv.dll and rdpwrap.ini) to roll back to a working version. I have no idea if the provided older version of termsrv.dll has any security flaws that have since been patched (I don't know why it was updated, except perhaps to frustrate the concurrent user community), so use at your own risk. The attached files date back to 12/22/2018, so not that old.

Here are the instructions. Enjoy.

Run cmd as admin and type "net stop TermService"
Find updated termsrv.dll in file C:\Windows\System32\
Rename or move new copy using by changing owner from TrustedInstaller:
	Properties-->Security-->Advanced-->Change Owner to admin user
	and then Add same admin user as permission
Move attached old copy (v168) to C:\Windows\System32\ and rename termsrv.dll
Open the RDPWrap folder (from github download).
Run as administrator uninstall.bat
Run as administrator install.bat
Copy attached old rdpwrap.ini file to C:\Program Files\RDP Wrapper

The combination of old termserv.dll and old rdpwrap.ini file should work.

However, if you reinstall RDPWrap and/or run the update.bat file, you'll
need to copy back the old ini file.

[Files for RDPWrap rollback.zip](https://github.com/stascorp/rdpwrap/files/2868016/Files.for.RDPWrap.rollback.zip)

**Comment by fre4kyC0de** [comment]
WARNING: Only use the attached files, if you are running Windows 10 1809 (17763) 64-bit.

**Comment by hookymd** [comment]
Does not work.
When the user starts the PDR, he disables the Administrator and they both see the same screen.

**Comment by pravyroxor** [comment]
It works with this dll:
- uninstall wrapper
- replace dll
- install wrapper 
[W7x64_6.1.7601.24234_termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/2868678/W7x64_6.1.7601.24234_termsrv.dll.zip)

**Comment by hookymd** [comment]
> It works with this dll:
> 
> * uninstall wrapper
> * replace dll
> * install wrapper
>   [W7x64_6.1.7601.24234_termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/2868678/W7x64_6.1.7601.24234_termsrv.dll.zip)

This is for WInfows 7! Not for 10

**Comment by gitgotgone** [comment]
Doh! I've updated my post to clarify Windows 10 1809 (17763) 64-bit. Thanks!

**Comment by binarymaster** [comment]
I don't appreciate such kind of issues, because issue section is for bugs, not for user support. We have Telegram chat for that.

**Comment by gitgotgone** [comment]
Sorry, I was just trying to be helpful. Let me know if there is a more appropriate way to help. Thanks for your efforts!!

**Comment by hookymd** [comment]
On Windows 10 1809 17763.316 don't working. 
RDP Users mirroring account of Administrator

**Comment by tepidmoney** [comment]
Thhhhaaaaaaaankssssss  wooorks!!!!

**Comment by MichiMess** [comment]
Thanks! Works!
