### ISSUE TITLE
Listener not Listening in Win10 x64 1809 SL

### ISSUE THREAD

**Issue by texNICKru** [stascorp/rdpwrap#677]
![screenshot_1](https://user-images.githubusercontent.com/11171453/53071239-aebf1880-34f2-11e9-8792-627dbdd487ee.png)
I tried. Used all the ways I found
This ini [https://github.com/stascorp/rdpwrap/issues/606#issuecomment-455488763]
permitions on rfxvmt.dll
```
set PC_NAME=
set USER_NAME=
net stop TermService
copy c:\rfxvmt.dll c:\windows\system32
cd c:\windows\system32
takeown.exe /A /F rfxvmt.dll
icacls.exe rfxvmt.dll /grant "%PC_NAME%\%USER_NAME%:F"
icacls.exe rfxvmt.dll /inheritance:d
icacls.exe rfxvmt.dll /setowner "NT SERVICE\TrustedInstaller"
icacls.exe rfxvmt.dll /grant "NT SERVICE\TrustedInstaller:F"
icacls.exe rfxvmt.dll /remove "NT AUTHORITY\SYSTEM"
icacls.exe rfxvmt.dll /grant "NT AUTHORITY\SYSTEM:RX"
icacls.exe rfxvmt.dll /remove "BUILTIN\Administrators"
icacls.exe rfxvmt.dll /grant "BUILTIN\Administrators:RX"
icacls.exe rfxvmt.dll /remove "%PC_NAME%\%USER_NAME%"
net start TermService
```

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/2883308/termsrv.zip)
[rfxvmt.zip](https://github.com/stascorp/rdpwrap/files/2883309/rfxvmt.zip)

**Comment by binarymaster** [comment]
Duplicate #606.

Don't create duplicate issues, use Telegram chat for user support.
