### ISSUE TITLE
Multiple RDP

### ISSUE THREAD

**Issue by hrpuae** [stascorp/rdpwrap#682]
Hi
I have downloaded RDP Wrap 1.6.2 & installed as administrator in windows 10pro 
In RDP config listener state showing not supported.So I am not able to connect multiple RDP.
Please help.
![snap-rdp](https://user-images.githubusercontent.com/47962525/53315213-8745c280-38db-11e9-8c8c-8809a1f2e15a.PNG)

**Comment by hrpuae** [comment]
OS build-17763.316

**Comment by binarymaster** [comment]
Duplicate of #645.
