### ISSUE TITLE
Please care for current open 'pull request'

### ISSUE THREAD

**Issue by Hopfengetraenk** [stascorp/rdpwrap#685]
... they currently 2 nice & working pull requests for **rdpwrap.ini** in the moderators queue since almost **3 month**.

Anyway here you can find among all the forks the most recent one:
[Active GitHub Forks for rdpwrap](https://techgaun.github.io/active-forks/index.html#stascorp/rdpwrap)
^- with commits that are more head the master branch

I'm also tempted to create my own fork from this. 
So I can apply the pull requests + do a release with modded update url to the fork's rdpwrap.ini.

May some of the other forks already did this, in responds to the feeling that comes up. 
Dev is in holiday or even more worst project's abandoned.

**Comment by binarymaster** [comment]
https://github.com/stascorp/rdpwrap/issues/661#issuecomment-463168294
