### ISSUE TITLE
Access Denied. 

### ISSUE THREAD

**Issue by McTechSolutions** [stascorp/rdpwrap#687]
Hi Guys. 

I am trying to use RDPWrap. I have install the latest version of the RDPWrap and i have updated my ini file to support Windows version 10.0.17763.292.

Everything is green when i run the RDPConf.exe. However when i run RDPCheck.exe and put in the credentials for my account i am faced with an access denied message. 

Any ideas? 

Thanks in advance.

**Comment by binarymaster** [comment]
Search for "Access Denied" in the README.
