### ISSUE TITLE
Lissener not working after Update KB4482887

### ISSUE THREAD

**Issue by Tastenkasper** [stascorp/rdpwrap#693]
After the latest Update KB4482887 is the Lissener State no more Lissening.

**Comment by graphixillusion** [comment]
I don't have any problems. Check if you have the correct ini file.

**Comment by mifrith** [comment]
The name of the failed application: svchost.exe_TermService, version: 10.0.17763.1, time stamp: 0xb900eeff
The name of the failed module: rdpwrap.dll, version: 1.5.0.0, time stamp: 0x5488aa5a
Exception code: 0xc0000005
Error offset: 0x00000000000029fc
Failure Process ID: 0xbe0
Runtime of failed application: 0x01d4d76c64685c9f
The path of the failed application: C: \ WINDOWS \ System32 \ svchost.exe
Path of the failed module: c: \ program files \ rdp wrapper \ rdpwrap.dll
Report ID: 81abe010-d0fb-4f57-a579-bd768273c250

I have this error

**Comment by graphixillusion** [comment]
I suggest to you to unistall everything, then reinstall from scratch. Here's the ini file i'm using.


[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/2949950/rdpwrap.zip)

**Comment by turboflash** [comment]
@graphixillusion Thanks, it works!

**Comment by jmeile** [comment]
> I suggest to you to unistall everything, then reinstall from scratch. Here's the ini file i'm using.
> rdpwrap.zip

I'm just wondering: where do you have to put the ini file?

**Comment by jmeile** [comment]
Ok, I found it. You need to put it here:
C:\Program Files\RDP Wrapper

**Comment by mrwtong** [comment]
> Ok, I found it. You need to put it here:
> C:\Program Files\RDP Wrapper

When I replace the ini file ，system denied and alerted this file is being used by RDP Service，

**Comment by jmeile** [comment]
On my case, I need to copy the file and not move it. It told me then to confirm overwriting the file.

Please also note that you need to extract it first somewhere. Do not move or copy it from the zip file directly.

If it does not work, then I guess you need either to stop the "RDP Service" -> I'm don't what's the name on the services manager.

Or you can also try to start the pc in safe mode and overwrite the file, then restart in normal mode.

Other thing you can try is to rename the file first, then copy the new ini file.

**Comment by mrwtong** [comment]
@jmeile Thanks，This ini file is occupied because I overwrite the file through RDP connection. I  log out all remote log-in account and log in locally to overwrite this file successfully

**Comment by kingketo** [comment]
lol

> @jmeile Thanks，This ini file is occupied because I overwrite the file through RDP connection. I log out all remote log-in account and log in locally to overwrite this file successfully

lol it cant be done ? :D i had admin account no chance.

**Comment by sebaxakerhtc** [comment]
Closed as not actual
