### ISSUE TITLE
RDPconf state all right, but can't log in with remote control while mentaining multi-user work.

### ISSUE THREAD

**Issue by HaujetZhao** [stascorp/rdpwrap#694]
windows version: 1809  17763.348
first the listener state is not fully supported, then I just changed the ini file, it became fully supported.
but, when I use my another computer on the same wifi to connect to this PC, it still says that other users would log out if I log in. 
the gpedit.msc is modified too, but it didn't work.

**Comment by Julien-nl** [comment]
to do so you need to restart the termservice and after reboot the box.

**Comment by HaujetZhao** [comment]
> to do so you need to restart the termservice and after reboot the box.

ok, that worked, but another problem popped up, no matter whether I set the "one session per user" and then reboot, restart the service, everytime I log in my main account, it will open a new session.

**Comment by HaujetZhao** [comment]
> > to do so you need to restart the termservice and after reboot the box.
> 
> ok, that worked, but another problem popped up, no matter whether I set the "one session per user" and then reboot, restart the service, everytime I log in my main account, it will open a new session.

ok, found the solution here. Thank you, dude! [solution](https://github.com/stascorp/rdpwrap/issues/422#issuecomment-398808660)

**Comment by sebaxakerhtc** [comment]
Same as https://github.com/stascorp/rdpwrap/issues/422
