### ISSUE TITLE
chrome and opera is not working

### ISSUE THREAD

**Issue by omergull88** [stascorp/rdpwrap#700]
i am using window 7 where i face issue with RDP wrap is that chrome browser is not working in any RDP wrap version

**Comment by themasquedpear** [comment]
Maybe the process is opened elsewhere...
Try to close all browser process then retry.

**Comment by andrekir** [comment]
Chrome use of GPU acceleration by default can be problematic in an RD session. Check if it works adding "--disable-gpu" after the chrome.exe in your shortcut. If that is indeed the issue you can also enforce to all RD session users adding Google Chrome GPO and setting "HardwareAccelerationModeEnabled" = false.

**Comment by sebaxakerhtc** [comment]
Closed as not actual and missing answer
