### ISSUE TITLE
[Question] Where are stored the RDPConf.exe settings?

### ISSUE THREAD

**Issue by themasquedpear** [stascorp/rdpwrap#702]
Hello !

The title say all.
I would like to know where are stored the RDPConf.exe settings OR maybe the registery entries that modify this program.
As you understood, i whant to modify these settings without the help of RDPConf.exe.

Thank you.
Best regards.

**Comment by themasquedpear** [comment]
bump

**Comment by iam-sysop** [comment]
RDPConf manages Registry settings for MS-RDP and Imports INI file settings for RDPWrap.  Source Code reveals what settings it manages in registry.

**Comment by themasquedpear** [comment]
> 
> 
> RDPConf manages Registry settings for MS-RDP and Imports INI file settings for RDPWrap. Source Code reveals what settings it manages in registry.

The Rdpwrap.ini file is not imported by RDPWInst.exe? with -i -o arguments.
RDPConf.exe seems to check if everyhting is fine and working and the only modification come from the registry.
I will run it in sandboxie for see the modification then create a reg file, since no one whant or can't help me...

**Comment by iam-sysop** [comment]
I've looked in source of rdpconf - it alters 4 registry keys...  They're defined in the source.

You're right.  Conf does not import INI settings - it only reveals if INI supports current termserv.dll in Windows system.  It reads additional keys to determine local termserv.dll version and windows version and architecture.

I have been working on a fork and my mgr/conf will be able to update ini from GUI.  That is why I confused momentarily origin rdpconf features.  Apologies.

**Comment by sebaxakerhtc** [comment]
Closed as not actual
