### ISSUE TITLE
RDP Wrap enabled but cannot connect

### ISSUE THREAD

**Issue by hozermd** [stascorp/rdpwrap#704]
Everything appears to be normal but I cannot connect with Remote Desktop to my windows 10 PC. I think I've set firewall permissions. Username and password correct. What should I do?

![ezgif-5-0ed771ae7695](https://user-images.githubusercontent.com/4442275/54784969-21c4c780-4c36-11e9-92c2-7dd62fce1d5e.gif)

<img width="404" alt="Ekran Resmi 2019-03-21 23 46 54" src="https://user-images.githubusercontent.com/4442275/54783950-b2e66f00-4c33-11e9-9fa7-80f2d0d203ee.png">

**Comment by ziggi24** [comment]
Which version of windows are you running? 

If windows update ran and you're on 10.0.17763.379 then you'll probably have to make some modifications to the ini and dll files. More info here - https://github.com/stascorp/rdpwrap/issues/699#issuecomment-474374585

**Comment by hozermd** [comment]
Thanks
My windows version 10.0.17763.379. I make some modifications and finally it works.

**Comment by sebaxakerhtc** [comment]
Closed as not actual
