### ISSUE TITLE
Windows 10 Latest Not Supported

### ISSUE THREAD

**Issue by frinkfromthedrink** [stascorp/rdpwrap#705]
![image](https://user-images.githubusercontent.com/45270931/54860829-2b156900-4cf6-11e9-8b88-6726d3624a64.png)

Is this version of Windows 10 not supported? It doesn't work....

**Comment by yuumusic** [comment]
![スクリーンショット (2)](https://user-images.githubusercontent.com/48858039/54866005-244c2c00-4db2-11e9-94ec-afe2aa824b4b.png)

W10HOME 17763.379
I also tried to uninstall and reboot. rewriting INI 292 → 379, but it does not work.

I tried initializing the OS and installing it.1.6.2 installation, termservice stop, replace termsrv.dll, INI rewrite, restart.

Is the procedure wrong? I want you to help.

**Comment by ailearncoder** [comment]
I have the same problem.

**Comment by qpcyet** [comment]
Same problem. 
My Windows 10 version is profession 1809 17763.379

**Comment by savitsky** [comment]
![111](https://user-images.githubusercontent.com/9442965/54911614-8793a680-4ef7-11e9-9f6e-1f350496c399.PNG)
Same problem. please fix it!

**Comment by savitsky** [comment]
![111](https://user-images.githubusercontent.com/9442965/54911993-48b22080-4ef8-11e9-9a8f-594f0cf8f215.PNG)
Same problem.
Please fix it!

**Comment by mpibpc-mroose** [comment]
sorry, same for me with a regular Win 10 LTSC 1809

![image](https://user-images.githubusercontent.com/8191021/54913835-ee16c580-4ef3-11e9-9025-37141d506993.png)

**Comment by thaguitarist** [comment]
Use the following file : 

Open a command prompt windows in admin mode  then : 
net stop termservice

Copy the file from the zip provided  into C:\Program files\RDP Wrapper 

Return to your command prompt windows (still in admin mode) then : 
net start termservice. 

If it is not working, simply reboot the computer.
[rdpwrap 10.0.17763.292.zip](https://github.com/stascorp/rdpwrap/files/3003741/rdpwrap.10.0.17763.292.zip)

**Comment by DCS59** [comment]
I have had this problem but it was solved by the following. Use "administrator rights" as necessary.
1. uninstall rdpwrap including deleting the rdpwrap.ini and rdpwrap.dll files in <Program Files/RDP Wrapper>
2. reboot the computer
3. install rdpwrap.
4. Check RDPConf and note the version number. The screenshot above shows .292
5. Check the version of termserv.dll and compare to that of RDPConf.
6. Use CMD to "net stop termservice"
7. edit the rdpwrap.ini file in <program Files/RDP Wrapper> to include the snippets relative to the versions above. save it in documents if you can't save it the same spot. Or you can use one of the files mentioned above.
7. Rename rdpwrap.ini and move the edited one into <Program File/RDP Wrapper>.
8., Use CMD to "net start termservice".
9. Reboot computer.
10. run RDPConf to confirm it is listening and supported.

A comment on the above screenshots. RDP is used by hackers to install ransomware as it is easily hacked. Maintaining maximum security is very important and 2 of the settings above do not do that.  "Hide users on logon screen" and "Network level Authentication"  should be checked. In addition Windows security should limit the number of failed password attempts and your users and passwords should not be short nor simple or common. I made these mistakes and have lost all my work and memories from the last 20 years.
If I've made a mistake in my directions above please post the correction.

**Comment by xhotzkin** [comment]
> Use the following file :
> 
> Open a command prompt windows in admin mode then :
> net stop termservice
> 
> Copy the file from the zip provided into C:\Program files\RDP Wrapper
> 
> Return to your command prompt windows (still in admin mode) then :
> net start termservice.
> 
> If it is not working, simply reboot the computer.
> [rdpwrap 10.0.17763.292.zip](https://github.com/stascorp/rdpwrap/files/3003741/rdpwrap.10.0.17763.292.zip)

Thank you very much @thaguitarist, this fixed the problem for me.

**Comment by mpibpc-mroose** [comment]
Maybe somebody could do a merge request for https://github.com/stascorp/rdpwrap/blob/master/res/rdpwrap.ini ? Then the installer would just download the right version on install, I guess.

**Comment by yesidtaz** [comment]
Hello good morning friends, and try the version 10.0.17763.292 and works perfectly in the version 10.0.17763.379 ... They must install the RDP 1.6.2 version, if they already have it installed it is just running the patch and it is ready and it is working.

I hope you help them who have not yet been able to solve the error.

![image](https://user-images.githubusercontent.com/48970086/55041208-0ec94300-4ffa-11e9-8a40-af515ad23781.png)


[Download Patch](http://www.mediafire.com/file/191rg42erapcjni/10.0.17763.379.rar/file)

**Comment by auliarahmed** [comment]
> Hello good morning friends, and try the version 10.0.17763.292 and works perfectly in the version 10.0.17763.379 ... They must install the RDP 1.6.2 version, if they already have it installed it is just running the patch and it is ready and it is working.
> I hope you help them who have not yet been able to solve the error.
> 
> Download Patch

THE REAL MVP
*insertgif* THANKYOU!

**Comment by zixun123** [comment]
> 你好早上好朋友，并尝试10.0.17763.292版本，并在10.0.17763.379版本中完美运行...他们必须安装RDP 1.6.2版本，如果他们已经安装它只是运行补丁它已经准备好了它正在发挥作用。
> 
> 我希望你帮助那些尚未解决错误的人。
> 
> ![图片](https://user-images.githubusercontent.com/48970086/55041208-0ec94300-4ffa-11e9-8a40-af515ad23781.png)
> 
> [下载补丁](http://www.mediafire.com/file/191rg42erapcjni/10.0.17763.379.rar/file)

这个是有效的，谢谢

**Comment by Jed-Z** [comment]
> Use the following file :
> 
> Open a command prompt windows in admin mode then :
> net stop termservice
> 
> Copy the file from the zip provided into C:\Program files\RDP Wrapper
> 
> Return to your command prompt windows (still in admin mode) then :
> net start termservice.
> 
> If it is not working, simply reboot the computer.
> [rdpwrap 10.0.17763.292.zip](https://github.com/stascorp/rdpwrap/files/3003741/rdpwrap.10.0.17763.292.zip)

This works on me. ver. 10.0.17763.292

**Comment by guojindai** [comment]
> Use the following file :
> 
> Open a command prompt windows in admin mode then :
> net stop termservice
> 
> Copy the file from the zip provided into C:\Program files\RDP Wrapper
> 
> Return to your command prompt windows (still in admin mode) then :
> net start termservice.
> 
> If it is not working, simply reboot the computer.
> [rdpwrap 10.0.17763.292.zip](https://github.com/stascorp/rdpwrap/files/3003741/rdpwrap.10.0.17763.292.zip)

it does work on 292

**Comment by savitsky** [comment]
![Снимок](https://user-images.githubusercontent.com/9442965/56146955-f2447900-5faf-11e9-947b-bc08c457c060.PNG)
new build and same problem.
can you write the "how-to" steps to solve the problem?

**Comment by affinityv** [comment]
::::::::::::::
[10.0.17763.437]
::::::::::::::
[10.0.17763.437]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=77A41
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=3E520
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18025
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1ACDC
SLInitFunc.x64=New_CSLQuery_Initialize

bInitialized.x64 =ECAB0
bServerSku.x64 =ECAB4
lMaxUserSessions.x64 =ECAB8
bAppServerAllowed.x64 =ECAC0
bRemoteConnAllowed.x64=ECAC4
bMultimonAllowed.x64 =ECAC8
ulMaxDebugSessions.x64=ECACC
bFUSEnabled.x64 =ECAD0

::::::::::::::
[10.0.17763.437-SLInit]
::::::::::::::
[10.0.17763.437-SLInit]
bInitialized.x86 =CD798
bServerSku.x86 =CD79C
lMaxUserSessions.x86 =CD7A0
bAppServerAllowed.x86 =CD7A8
bRemoteConnAllowed.x86=CD7AC
bMultimonAllowed.x86 =CD7B0
ulMaxDebugSessions.x86=CD7B4
bFUSEnabled.x86 =CD7B8
bInitialized.x64 =ECAB0
bServerSku.x64 =ECAB4
lMaxUserSessions.x64 =ECAB8
bAppServerAllowed.x64 =ECAC0
bRemoteConnAllowed.x64=ECAC4
bMultimonAllowed.x64 =ECAC8
ulMaxDebugSessions.x64=ECACC
bFUSEnabled.x64 =ECAD0

**Comment by sebaxakerhtc** [comment]
Closed as not actual
