### ISSUE TITLE
Nothing Returned Download

### ISSUE THREAD

**Issue by Austin-Src** [stascorp/rdpwrap#707]
Downloading the .zip and .msi files from the most recent releases produce a 0 Byte .msi and an empty .zip. Microsoft may have added a stripper script to mitigate this technique.

**Comment by thaguitarist** [comment]
Your antivirus probably detects it as a potential threat (but it's a false positive)  
I suggest you put an exception for the folder where you download Rdp Wrap and once installed, put the \Program files\rdp wrapper\ folder in your exceptions as well.

**Comment by Austin-Src** [comment]
Yes, that likely is the problem. Will close this issue.
