### ISSUE TITLE
Graphic pixelated distortions when connected to client

### ISSUE THREAD

**Issue by Remonell** [stascorp/rdpwrap#708]
I could not install updates for like 12 months for Win 10 x64. I fixed it and finally could update my windows a few days ago. And of course rdp wrap stopped working. After replacing the .dll and .ini file etc. it worked again. 
**BUT** now I have weird **graphical distortions** that appear when I connect to my remote clients (other windows user). [Here is an image.](https://imgur.com/TLOQMmu)
Every few seconds those pixelated black or grey boxes appear and they stay for a few seconds. Sometimes even covering the whole window.

What I tried so far to get rid of it:
- clean and reinstall newest GPU drivers
- update direct x
- tried multiple remote desktop managers
- played around with color and resolution settings in the managers
- changed rdp version that is being used (possible in Remote Desktop Manager Free from Devolutions)
- tried diffrent combinations of .ini files, .dll files and settings of rdp-wrap

If you have any idea what I could try, please let me know. I am more than happy to double or tripple check possible solutions.

**Comment by sebaxakerhtc** [comment]
Test your RAM, run `sfc /scannow`, or `dism /online /cleanup-image /restorehealth` on both (server and client), 
Not an rdpwrapper issue
