### ISSUE TITLE
Add rd-wrapper support for 10.0.17134.648

### ISSUE THREAD

**Issue by javedfar** [stascorp/rdpwrap#711]
Listener state showing not listening fully supported

**Comment by thaguitarist** [comment]
Can you provide a screenshot of the rdpconf window and a zipped copy of your termsvr.dll file please ?

**Comment by javedfar** [comment]
thanks for replying on my issue..
kindly find below screenshot and zip file attached as per your request.

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/3025635/termsrv.zip)

![image](https://user-images.githubusercontent.com/49052872/55278055-5e2aae80-532d-11e9-84f8-dd63ee0e93ed.png)

**Comment by javedfar** [comment]
Hi,
Kindly help me on the above issue.
I need to sort out immediately.
Thanks.

**Comment by thaguitarist** [comment]
This version (10.0.17134.1) is supported. 

In your case, the listener is not listening.  Are you using a Home version of Windows 10 ? If yes, make sure you have rfxvmt.dll in your C:\Windows\System32 folder. If not, download it [here](https://github.com/stascorp/rdpwrap/issues/194#issuecomment-325627235) !

Please follow the instruction [here](https://github.com/stascorp/rdpwrap/issues/194#issuecomment-353029623) after downloading and copying file to System32! 

Let us know if it works.

**Comment by javedfar** [comment]
Hi,
Your instructions and replacement of rfxvmt.dll file really worked for me.
My issue is resolved successfully.
Thanks a lot for your support.
