### ISSUE TITLE
RDP-Wrapper Not Supported For Version 1809 [Updated]

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#713]
Hi,
After upgraded to 1809 (include march updates) | 10.0.17762.292 not supported :( There also similar issues https://github.com/stascorp/rdpwrap/issues/709 and https://github.com/stascorp/rdpwrap/issues/711 and im opening this issue atleast expecting manual configuration

also https://www.reddit.com/r/sysadmin/comments/9kze8h/windows_10_1809_update_rdp_connections_failing/ etc. any of those solution not work for non-domain computers

Just since unable use RDP-Wrapper then i tried enable that through group policy | Administrative Templates -> windows Component -> Remote Desktop Services -> remote desktop session host -> connections
\# Limit number of connections - 2
\# Restrict Remote desktop service users to a single - disable 

Unfortunately when try connect, i get error "An internal error has occurred"

Any helps?

**Comment by ghost** [comment]
That one doesnt even work.
https://www.raymond.cc/blog/enable-remote-desktop-connection-in-windows-7-home-premium/
https://www.raymond.cc/blog/download/did/3946/ 
Download Concurrent RDP Patcher 2018 with KB4462923 Fix
https://www.raymond.cc/blog/download/did/3947/
 Download Concurrent RDP Patcher 2019 with KB4486563

Unsupported: termsrv.dll has an unknown checksum

**Comment by graphixillusion** [comment]
Works greate under 1809 with this ini file:

https://github.com/stascorp/rdpwrap/issues/693#issuecomment-471335801

**Comment by chrisxvin** [comment]
Report: 10.0.17763.379 not supported.

**Comment by sebaxakerhtc** [comment]
Closed as not actual
