### ISSUE TITLE
Rdpwrap not working Windows 10 1903

### ISSUE THREAD

**Issue by DaDD65** [stascorp/rdpwrap#715]
Updating to April 1903 update breaks rdpwrap

**Comment by DaDD65** [comment]
Replacing ini and rebooting got it working.
https://github.com/stascorp/rdpwrap/files/2949950/rdpwrap.zip

**Comment by PCMacDr** [comment]
@DaDD65 

Thank you, worked great on my latest april 2019 build

**Comment by ivobg1980** [comment]
I agree

**Comment by chrisskoni** [comment]
I have replaced the file and did restart the machine serveral times... Also the updater file confirms me that i have the february 2019 version and ask if im a developer :)
I have running a Win 10 Pro as a Hyper-V Virtual Machine and maybe that is the culprit.
I want to run a software and use this VM as a terminal server to connect 3 users at the same time to it.

RDP Config says not supported....
![Version](https://user-images.githubusercontent.com/49407572/55738644-cbbe9500-5a27-11e9-931a-473bb6aa1a14.jpg)

**Comment by futouyiba** [comment]
@DaDD65 's solution worked for me. Why can't update bat use this file?

**Comment by sbzagorodin** [comment]
> Replacing ini and rebooting got it working.
> https://github.com/stascorp/rdpwrap/files/2949950/rdpwrap.zip

It does not work for me. The file does not contain definition for **18362.1** build.

**Comment by hdatma** [comment]
Any hope to fix it from the command line?

```
>Get-Item "C:\Windows\system32\termsrv.dll" | select Name,Length,Mode,LastWriteTime,Name | fl

Name          : termsrv.dll
Length        : 1018880
Mode          : -a----                                                                                                          
LastWriteTime : 3/29/2019 9:12:21 PM
```

**Comment by pierospi** [comment]
It does not work for me too.
My win ver: 1903 (build SO 18362.592)

sorry  :)

**Comment by s0nic9** [comment]
use new offset https://github.com/stascorp/rdpwrap/issues/945#issuecomment-573673428

**Comment by gerardoparedes** [comment]
it does not work for me  My win ver: 1903 (build SO 18362.592)

**Comment by sebaxakerhtc** [comment]
Closed as not actual
