### ISSUE TITLE
Resolution/Scale problem W10 

### ISSUE THREAD

**Issue by thomas0686** [stascorp/rdpwrap#716]
Hello,

First thanks for the solution, i love it. 
I don't know if my issue is due to RDPWrapper but i 'm out of options so i ask
I have some sessions wich are not well displayed. Applications and icons are much too big . And sometimes thats good. It is like scale is forced the most of the time and in some configuration that i don't find it's good. 
Some words about configuration:
A server with some application on a site (W10 10.0.17763.292), with some square old screen (base resolution 1024x768)
Resolution on each session configured to be 1920x1080 with teamviewer),
correction of blurring application option is off ans scaling is forced at 100%
5 computers on an other site with RDP wrapper and different screens. They connect in full screen, correction of blurring application option is off, scaling not forced
For the moment there are also some teamviewer connections on the server but i tried with or without at the same time, nothing  change.
Have you some idea?
Thanks and sorry for my english (french guy...)
Regards

**Comment by iam-sysop** [comment]
When connect host via MSTSC, verify options for display on client level.  Additionally, some outside application may have set "server inherit" settings on RDP registry keys.  RDP Hosts can "push" their settings on the client if the client does not have it's own "preferences set"...  

RDPWrap doesn't alter resolution - it only hooks licensing and client connection counts.  Core code is still MS and MS handles screens from what I tell in code so far.

**Comment by thomas0686** [comment]
Ok thanks for your answer. So I tried on the client to change the scale and it resolve the problem on the server by RDP but it 's a problem on a high resolution device because on the client become tiny (for exemple on a dell with 3840 x 2160 resolution, the scale is set on 300%, i have to make it on 100% to have a good RDP display but on the dell it's tiny). Where can i see the inheritence options to avoid the client to pass the scale options?

**Comment by iam-sysop** [comment]
Inheritance is controlled in registry, but it is rare.  You describe DPI issue (scaling) issue - which can be factor if not all hosts/clients support it.  Will want to investigate MS-RDP behaviors and such.  Win Vista = 2008 Server, Win7 = 2008R2 Server, Win8 = 2012 Server,  Win10 - 2016 Server -- RDP is MS Server tech.  You may need to research server side configurations for terminal services clients where DPI scaling is involved.  The same registry settings that control RDP on servers exist on workstations - just that workstations are not configured to serve by MS.  

I feel there should not need to be much bothering the Registry.  Somewhere a setting is not cooperating for DPI scaling.  That is where I would investigate --

**Comment by thomas0686** [comment]
Ok i will insvestigate in that way. Thanks a lot for your help. I close the issue wich is not due to RDPWrapper
