### ISSUE TITLE
Fail to connect RDP after uninstall rdp wrapper to renew the ini file

### ISSUE THREAD

**Issue by tao96** [stascorp/rdpwrap#718]
I run a virtual machine with win 10 on ESXI, I reinstall the rdp wrapper to fit the latest update of win10, however, the RDP service stopped work after uninstall the rdp wrapper.
The virtual machine can only be connected with RDP, when I try to use vSphere and teamviewer to connect it, I only got black screen, I think the reason may be no monitor connected with the virtual machine, how can I deal with this issue? It's really urgent for me!

**Comment by tao96** [comment]
I run a virtual machine with win 10 on ESXI, I reinstall the rdp wrapper to fit the latest update of win10, however, the RDP service stopped work after uninstall the rdp wrapper.
The virtual machine can only be connected with RDP, when I try to use vSphere and teamviewer to connect it, I only got black screen, I think the reason may be no monitor connected with the virtual machine, how can I deal with this issue? It's really urgent for me!

**Comment by tao96** [comment]
I can boot my computer in safe mode, and I can't uninstall rdp wrapper since the term service is not running

**Comment by kelly-crompton** [comment]
m

**Comment by sebaxakerhtc** [comment]
Closed as not actual
