### ISSUE TITLE
Last Windows Security Update breaks RDPWrap

### ISSUE THREAD

**Issue by Fabliv** [stascorp/rdpwrap#722]
Hi all,

The last Security Update KB4489899 on Windows 10 breaks RDPWrap, have to uninstall it to recover the fonctionnality.

**Comment by mihalich1988** [comment]
Команда для удаления через командную строку (в режиме Администратора):
wusa /uninstall /kb:4489899

**Comment by Fabliv** [comment]
@mihalich1988, That's what I did. ;)

**Comment by CONTIGIANLUCA** [comment]
Not work anyway ..

**Comment by mihalich1988** [comment]
> Not work anyway ..

Check this https://github.com/stascorp/rdpwrap/issues/721

**Comment by Pigman91** [comment]
I updated .ini file via update.bat and uninstall KB4493464. After reastart it works again.

**Comment by CONTIGIANLUCA** [comment]
Nothing to do :-(

**Comment by CONTIGIANLUCA** [comment]
![immagine](https://user-images.githubusercontent.com/22478881/55863630-36ccb080-5b7b-11e9-910a-d0ad4af13f93.png)

**Comment by mihalich1988** [comment]
> Nothing to do :-(

Do you remove KB4493464?

**Comment by CONTIGIANLUCA** [comment]
Yes, but i don't restart

**Comment by mihalich1988** [comment]
> Yes, but i don't restart

I restart and reinstall RDPWrap. All work fine

**Comment by bramburn** [comment]
@mihalich1988 this is a good temporary fix. I had a different KB reference for the security update.

1. Check the latest Windows update history and identify the latest security update KB reference
2. uninstall the KB using @mihalich1988 command `wusa /uninstall /kb:xxxxxx` << replace xxxxxx with the reference
3. Restart the machine
4. click update.bat in the rdpwrapper/
5. click install.bat in the rdpwrapper/
6. Check if everything is fine in rdpconf.exe

**Comment by Fabliv** [comment]
**Warning**: following this security update, Windows Defender seems to recognize **RDPConf.exe** and **rdpwinst.exe** as **HackTool: Win32 / RemoteAdmin** on some computers.

Any feedback will be apreciated.

**Comment by eduardogcorrea** [comment]
OK... problem temporaly solved. But how can I make windows stop to do updates? The option is for 35 days..

**Comment by lucassssmi** [comment]
> @mihalich1988 this is a good temporary fix. I had a different KB reference for the security update.
> 
> 1. Check the latest Windows update history and identify the latest security update KB reference
> 2. uninstall the KB using @mihalich1988 command `wusa /uninstall /kb:xxxxxx` << replace xxxxxx with the reference
> 3. Restart the machine
> 4. click update.bat in the rdpwrapper/
> 5. click install.bat in the rdpwrapper/
> 6. Check if everything is fine in rdpconf.exe

Bram, i am sorry, how can find "Check the latest Windows update history"

**Comment by lucassssmi** [comment]
> **Warning**: following this security update, Windows Defender seems to recognize **RDPConf.exe** and **rdpwinst.exe** as **HackTool: Win32 / RemoteAdmin** on some computers.
> 
> Any feedback will be apreciated.

Fabliv, please esplane to my ignorance .. 
HackTool: what is, what i need to do... ?

**Comment by lucassssmi** [comment]
![image](https://user-images.githubusercontent.com/17559452/55878468-c9ca1280-5b9c-11e9-97a1-8ae44d65d60c.png)

**Comment by lucassssmi** [comment]
> Команда для удаления через командную строку (в режиме Администратора):
> wusa /uninstall /kb:4489899

ok, with prompt dos, put this command; i removed wusa /uninstall /kb:4493509
Source from https://pureinfotech.com/windows-10-version-release-history/#windows10_version_1903

But when i restart  pc it make the upgrade but work fine!! 
Thanks everybody.. nice for your work and your help! -)

**Comment by donalld** [comment]
> @mihalich1988 this is a good temporary fix. I had a different KB reference for the security update.
> 
> 1. Check the latest Windows update history and identify the latest security update KB reference
> 2. uninstall the KB using @mihalich1988 command `wusa /uninstall /kb:xxxxxx` << replace xxxxxx with the reference
> 3. Restart the machine
> 4. click update.bat in the rdpwrapper/
> 5. click install.bat in the rdpwrapper/
> 6. Check if everything is fine in rdpconf.exe

THX A LOT BRO! you saved my day

**Comment by ITCMD** [comment]
Full steps fix this:
**A. Stop the service**
1. Open admin command prompt window (search CMD, right click, run as admin)
2. type `net stop termservice` and press enter
3. Leave window open to start service later (optional)

**B. Move new DLL file**
1. Open Explorer, type `system32` to go to the system32 folder.
2. Search and find `termsrv.dll`
3. Open the file's properties.
4. Go to `Security`.
5. Click `Advanced`.
6. Click `Change` next to owner.
7. Type your username and press enter.
8. Press `Ok`.
9. Back in the security tab (step 4) Click `Edit`.
10. Under `Group or user names` Click on your username
11. Check the `Allow` Checkbox next to `Full Control`.
12. Press OK.
13. Drag and drop the new `termsrv.dll` File into the system32 folder. (found [here](https://github.com/stascorp/rdpwrap/files/3062444/termsrv.zip), same link as found in issue #721)
14. When prompted to replace, hit yes.
15. Now we want to change the settings back. **Note that this is optional, but better for security.**
16 Follow the same steps to get to the window in step 11.
17. Under your username, uncheck `modify` and `write`.
18. Press Ok.
19. Follow the same steps to get to the window in step 7.
20. Now type in `NT SERVICE\TrustedInstaller` to make TrustedInstaller the owner again.
21. Press Ok.
22. Done!

**D. Start the service**
1. If you didn't leave the admin window open, open a new one.
2. type `net start termservice` and press enter
3. Enjoy RDP

**Comment by Prakhov** [comment]
Didn't work for me. With provided file termsrv.dll terminal service crushes. With native file system works, but only for one connection.

**Comment by Fabliv** [comment]
@Prakhov, uninstall last windows security updates, reboot your computer and reinstall RDPWrap, as mentioned above. ;)

**Comment by yuyujulin** [comment]
@ITCMD you made my day, thanks bro.

**Comment by sebaxakerhtc** [comment]
Closed as not actual
