### ISSUE TITLE
After Restart suddenly RDP Wrapper not supported?

### ISSUE THREAD

**Issue by ITCMD** [stascorp/rdpwrap#724]
I had to restart my PC to apply some settings, and afterwards I cannot Remote in to my computer. It worked before but all of a sudden it says `Listener state:  Not listening        [not supported]`.
Here is a screenshot:
![](http://i.imgur.com/KKMPLkW.png)

I tried restarting the TermService with no avail.

Any ideas what changed? It was working perfectly before!

**Comment by YharB** [comment]
Такая же проблема. Помогло удаление обновления.

**Comment by donalld** [comment]
I solved it on this post

https://github.com/stascorp/rdpwrap/issues/722

**Comment by Fabliv** [comment]
Duplicate.

Please, have a look to the issue #722

**Comment by ITCMD** [comment]
thanks. Added to it. Admin please delete or close this post.

**Comment by fre4kyC0de** [comment]
All files patched, tests are running ATM.
Second half of 2019-04 updates will follow as soon as tests are finished.
https://github.com/fre4kyC0de/rdpwrap

**Comment by sebaxakerhtc** [comment]
Closed as not actual
