### ISSUE TITLE
April MS-Update breaks Win81/2012R2 - support 6.3.9600.19318 missing

### ISSUE THREAD

**Issue by johndoe7000** [stascorp/rdpwrap#727]
After the Update RDPWrapper ist not supported. Only single login.

**Comment by romeroayub** [comment]
same here, terminal server is not supported.

Terminal Services Version: 6.3.9600.19318

**Comment by ericernie** [comment]
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/3067807/termsrv.zip)
6.3.9600.19318   file for parsing for offset

**Comment by johndoe7000** [comment]
OK - done. what next?

**Comment by ericernie** [comment]
Looking for someone to Parse that dll to find offsets needed, then post Lines of txt to add to rdpwrap.ini.

**Comment by landroam** [comment]
same problem win 8.1 x64 termsrv 6.3.9600.19318

**Comment by Jonathan-rodriguez-r** [comment]
add this lines to rdwrap.ini 
[6.3.9600.19318]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B3958
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8AE4E
LocalOnlyCode.x64=nopjmp
SingleUserPatch.x86=1
SingleUserOffset.x86=3F045
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=36BC9
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3D899
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=45305
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=18288
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=5D660
SLInitFunc.x64=New_CSLQuery_Initialize

[6.3.9600.19318-SLInit]
bFUSEnabled.x64       =FA054
lMaxUserSessions.x64  =FA058
bAppServerAllowed.x64 =FA05C
bInitialized.x64      =FA060
bMultimonAllowed.x64  =FA064
bServerSku.x64        =FA068
ulMaxDebugSessions.x64=FA06C
bRemoteConnAllowed.x64=FA070

**Comment by johndoe7000** [comment]
Sadly this does not work for me.
After adding this to my ini file and making a reboot service state goes to "stopped" and listener state to "not listening".
Reverting this makes me at least start a single session.
Could you please recheck on your side.
And before you ask... yes I did hit Return after the end of your codes.

**Comment by Jonathan-rodriguez-r** [comment]
first you must to stop termservice; next add this lines after the end of the code
[6.3.9600.19318]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=92521
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=1511C
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=10E78
DefPolicyCode.x64=CDefPolicy_Query_edi_rcx
SLInitHook.x64=1
SLInitOffset.x64=22F5C
SLInitFunc.x64=New_CSLQuery_Initialize

[6.3.9600.19318-SLInit]
bFUSEnabled.x64       =FA054
lMaxUserSessions.x64  =FA058
bAppServerAllowed.x64 =FA05C
bInitialized.x64      =FA060
bMultimonAllowed.x64  =FA064
bServerSku.x64        =FA068
ulMaxDebugSessions.x64=FA06C

**Comment by jirijanata** [comment]
Dear Jonathan Rodriguez. You are posting wrong offsets. Please, stop it! Right Offsets for Windows 8.1 19318 are here (the spaces are for the x86 version):

@johndoe7000 Can you test it?

[6.3.9600.19318]

LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=89EAC
LocalOnlyCode.x64=nopjmp

SingleUserPatch.x64=1
SingleUserOffset.x64=35779
SingleUserCode.x64=Zero

DefPolicyPatch.x64=1
DefPolicyOffset.x64=43CE5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx

SLInitHook.x64=1
SLInitOffset.x64=5C0D0
SLInitFunc.x64=New_CSLQuery_Initialize

[6.3.9600.19318-SLInit]
bFUSEnabled.x64       =FA054
lMaxUserSessions.x64  =FA058
bAppServerAllowed.x64 =FA05C
bInitialized.x64      =FA060
bMultimonAllowed.x64  =FA064
bServerSku.x64        =FA068
ulMaxDebugSessions.x64=FA06C
bRemoteConnAllowed.x64=FA070

**Comment by johndoe7000** [comment]
It works.
Thank you jirijanata.
For clarification... which spaces to you mean the ones in the [6.3.9600.19318] tag oder the spaces in [6.3.9600.19318-SLInit] after some "="?

**Comment by jirijanata** [comment]
This spaces :)

![image](https://user-images.githubusercontent.com/14040091/55984060-e0f02980-5c9c-11e9-9e2c-d1e1573e1609.png)

**Comment by johndoe7000** [comment]
How you guys do that? is there some tool?

**Comment by jirijanata** [comment]
Yes, there is IDA - it's decompilator. On the main page is tutorial Video:

[How to find offsets for new termsrv.dll versions](http://www.youtube.com/watch?v=FiD86tmRBtk)

[See here my other post](https://github.com/stascorp/rdpwrap/issues/734#issuecomment-482251207)

**Comment by Jonathan-rodriguez-r** [comment]
> Dear Jonathan Rodriguez. You are posting wrong offsets. Please, stop it! Right Offsets for Windows 8.1 19318 are here (the spaces are for the x86 version):
> 
> @johndoe7000 Can you test it?
> 
> [6.3.9600.19318]
> 
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=89EAC
> LocalOnlyCode.x64=nopjmp
> 
> SingleUserPatch.x64=1
> SingleUserOffset.x64=35779
> SingleUserCode.x64=Zero
> 
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=43CE5
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> 
> SLInitHook.x64=1
> SLInitOffset.x64=5C0D0
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [6.3.9600.19318-SLInit]
> bFUSEnabled.x64 =FA054
> lMaxUserSessions.x64 =FA058
> bAppServerAllowed.x64 =FA05C
> bInitialized.x64 =FA060
> bMultimonAllowed.x64 =FA064
> bServerSku.x64 =FA068
> ulMaxDebugSessions.x64=FA06C
> bRemoteConnAllowed.x64=FA070

Thanks, can you explain me how do you get that offsets?

**Comment by johndoe7000** [comment]
Great jirijanata. I will look into this.
Many thanks again.

**Comment by jirijanata** [comment]
Please see post above - there is videotutorial.

**Comment by Jonathan-rodriguez-r** [comment]
> Please see post above - there is videotutorial.

thanks

**Comment by fre4kyC0de** [comment]
https://github.com/fre4kyC0de/rdpwrap/blob/master/6.3.9600.19318.txt

**Comment by moaeddy** [comment]
> Dear Jonathan Rodriguez. You are posting wrong offsets. Please, stop it! Right Offsets for Windows 8.1 19318 are here (the spaces are for the x86 version):
> 
> @johndoe7000 Can you test it?
> 
> [6.3.9600.19318]
> 
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=89EAC
> LocalOnlyCode.x64=nopjmp
> 
> SingleUserPatch.x64=1
> SingleUserOffset.x64=35779
> SingleUserCode.x64=Zero
> 
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=43CE5
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> 
> SLInitHook.x64=1
> SLInitOffset.x64=5C0D0
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [6.3.9600.19318-SLInit]
> bFUSEnabled.x64 =FA054
> lMaxUserSessions.x64 =FA058
> bAppServerAllowed.x64 =FA05C
> bInitialized.x64 =FA060
> bMultimonAllowed.x64 =FA064
> bServerSku.x64 =FA068
> ulMaxDebugSessions.x64=FA06C
> bRemoteConnAllowed.x64=FA070

Thanks alot man, i have searched through until i come across yours wish help me solved it

**Comment by acmodeu** [comment]
Are these offsets correct? I've added them to rdpwrap.ini and all of the diagnostics are green yet still i get "another user is signed in..."

Can someone provide with patched termsrv.dll maybe?

**Comment by moaeddy** [comment]
did you use RDPConf to UNCHECK single session per user?

also make sure to use RDPWINST -r to restart Termservice for connection to work properly

**Comment by acmodeu** [comment]
No. But after adding strings from [your post](https://github.com/stascorp/rdpwrap/issues/727#issuecomment-484282362), unchecking single session... and restarting RDPWInst.exe I got that the listener is not listening though it is fully supported.

**Comment by TonightShaka** [comment]
I turn to a version call of RDPWrapper V1.7, since they do not make a sense and give stinging tips, I had a lot of difficulties, I get a layman if I do not read here to break a head. The program has a BUG, ​​the purpose is here and help, will do and post here ...
I will give the credits to: jirijanata and fre4kyC0de .. I will add all the code files to rdpwrap.ini. and the fix already applied did not install by Jirijanata:

Backup rdpwrap.ini file
Download RDPWrapper from github and unpack it.
Uninstall RDPWrapper
Change in install.bat "%~dp0RDPWInst" -i -o to "%~dp0RDPWInst" -i
= simply remove -o and save the file.
Copy rdpwrap.ini into the same folder as install.bat
Add to rdpwrap.ini new offsets and save it.
Install RDPWrapper with install.bat

I'll go ahead, just editing the .rdpwrap.ini file just does not work.
More option in installer, sorry my English, using google translator.
YOU CAN CHARGE ME IN 5 DAYS HERE.

**Comment by sebaxakerhtc** [comment]
Closed as solved and not actual anymore
