### ISSUE TITLE
Instructions when the listener state goes to not listening

### ISSUE THREAD

**Issue by tech-is-fun** [stascorp/rdpwrap#728]
I have been using RDP wrapper for a while and it has helped me tremendously.  But I have noticed that is has stopped working a few times over the last 6 months and I have to search the internet to get it working again.  I decided to make instructions to make this easier and faster for me to fix when it goes to not listening state.  I thought I would share these instructions on github in case it helps someone else
[rdpwrapper_troubleshooting.pdf](https://github.com/stascorp/rdpwrap/files/3065661/rdpwrapper_troubleshooting.pdf)

**Comment by sebaxakerhtc** [comment]
Closed as not actual. 
If listener state goes to not listening there are two ways:
1) Wrong offsets
2) Termservice not started
