### ISSUE TITLE
update.bat does not get new INI file

### ISSUE THREAD

**Issue by swaibel** [stascorp/rdpwrap#730]
Update.bat no longer downloads a new INI file and reports that the current update is 2018.10.10 and the rdpwrap.ini in rdpwrap/res/ hasn't been updated in a long time.  RDPWrap 1.6 is breaking nearly every month on our Windows 7 PCs due to Windows updates. Today it was broken by KB4493472 which updated termsrv.dll to 6.1.7601.24402. 

Is the update to the INI file being supported by some other method, other than hoping someone posts a file in response to a posted issue?

**Comment by Zplusless** [comment]
1803(17134.706) also failed to update ini file

**Comment by fre4kyC0de** [comment]
Windows 7 2019-04 offsets are available
https://github.com/fre4kyC0de/rdpwrap/blob/master/6.1.7601.24402.txt

**Comment by thecodygriffin** [comment]
Would it be possible to get a documentation update that states that update.bat is effectively useless along with clear, concise, written instructions on how to reliably update rdpwrap.ini consistently? It took me about 3 hours yesterday to figure out something that should have taken, at most, 5 minutes.

**Comment by sebaxakerhtc** [comment]
> Update.bat no longer downloads a new INI file and reports that the current update is 2018.10.10

Update.bat works. There's no updated ini.
