### ISSUE TITLE
Add support for version 10.0.10240.18186

### ISSUE THREAD

**Issue by vdobrev** [stascorp/rdpwrap#732]
Here's the new file [termsrv.zip](https://github.com/stascorp/rdpwrap/files/3066838/termsrv.zip)

The change was introduced by:
* 2019-04 Cumulative Update for Windows 10 Version 1507 for x64-based Systems (KB4493475)

**Comment by vdobrev** [comment]
Update: if KB4493475 is uninstalled then termsrv.dll reverts back to [supported v10.0.10240.18036](https://github.com/stascorp/rdpwrap/issues/600#issuecomment-439505675) 
Just a temporary fix until someone smarter extracts the new offset values..

**Comment by martinadi** [comment]
hi, i can't replace termsrv.dll can you help me?

**Comment by smellahi** [comment]
how can i replace termsrv.dll??? its asking some kind of permissions and not letting me override Thanks

**Comment by vdobrev** [comment]
@martinadi @smellahi There is NO fix yet, the attached file above must be [parsed for the actual offsets](http://www.youtube.com/watch?v=FiD86tmRBtk) on this update

Until then, for a temporary workaround, just follow [these instructions](https://github.com/stascorp/rdpwrap/issues/722#issuecomment-481636753) to rollback the update to restore old state

**Comment by Poohbear69** [comment]
I don't have KB4493475 install on my system but then again I'm Windows 10 version 1803.
I noted that 4 KB were installed last night and my system rebooted and RDP has now stopped working (or should I say is not listening on port 3389).
Out of the 4 updates I would have said it was KB4493464.
I have removed that KB and I'm now back up and running RDP as expected, thanks for the pointers.
wusa /uninstall /kb:4493464
Regards

**Comment by vdobrev** [comment]
@Poohbear69 it's good to get it back running, but it's just a temp hack.
Hope you kept a copy of the updated dll (the one not working)
Post it in a new topic with the proper version title and someone someday hopefully will figure out the offsets so everyone with that version can get a permanent fix.
The file version is clearly visible from file properties, details tab, under file/product version.

**Comment by SamihIsHis** [comment]
I can confirm that uninstalling KB4493464 allows RDPWrap to work again.

After installing a bunch of updates yesterday I discovered RDP stopped working this morning. Troubleshooting process led me here, running the cmd:

wusa /uninstall /kb:4493464

from powershell and restarting my machine and RDP connected without issue.

**Comment by fre4kyC0de** [comment]
Use these offsets:
https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.10240.18186.txt

**Comment by vdobrev** [comment]
@fre4kyC0de sadly, it does not work over here.. allows just one connection at a time...

![image](https://user-images.githubusercontent.com/3455823/56003647-25e18380-5cd0-11e9-8711-9ba04b5f31de.png)
![image](https://user-images.githubusercontent.com/3455823/56003676-4f021400-5cd0-11e9-91ea-f08ba9a64764.png)
[termsrv 10.0.10240.18186.zip](https://github.com/stascorp/rdpwrap/files/3071098/termsrv.10.0.10240.18186.zip)

**Comment by vdobrev** [comment]
..and a remote connection fails every time

![image](https://user-images.githubusercontent.com/3455823/56004145-66420100-5cd2-11e9-8eb8-4a4e034e83f5.png)

while on the host it said "the remote procedure call failed"

**Comment by fre4kyC0de** [comment]
Strange.
I‘ll verify the offsets and report back.

Maybe it‘s cuased by a bug introduced by MS a few months ago preventing multiple logins using RDP? (Known issue in 2019-03 and previous updates).

**Comment by fre4kyC0de** [comment]
Correct.
I copied the wrong line.

Replace
`DefPolicyOffset.x64=EDCB`
with
`DefPolicyOffset.x64=EDC5`

My repo will be updated as soon as I rechecked the offsets for all versions.

**Comment by vdobrev** [comment]
Thanks a million, applied the update and confirmed as working

**Comment by sevakgrig** [comment]
Hello fre4kyC0den.
The configuration for your link (https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.10240.18186.txt) did not work for me.

![wrapper](https://user-images.githubusercontent.com/46564800/56090810-de195280-5eaf-11e9-8364-015a8da131b7.png)

**Comment by sevakgrig** [comment]
A complete reinstall of the wrapper, restarting the computer did not help either. Can you help me solve this problem?

**Comment by affinityv** [comment]
::::::::::::::
[10.0.10240.18186]
::::::::::::::
[10.0.10240.18186]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=A8048
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=96A41
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=32B15
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=17264
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=2F699
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=EDC5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=3FA58
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=249D0
SLInitFunc.x64=New_CSLQuery_Initialize

::::::::::::::
[10.0.10240.18186-SLInit]
::::::::::::::
[10.0.10240.18186-SLInit]
bFUSEnabled.x86       =C4F88
lMaxUserSessions.x86  =C4F8C
bAppServerAllowed.x86 =C4F90
bInitialized.x86      =C4F94
bMultimonAllowed.x86  =C4F98
bServerSku.x86        =C4F9C
ulMaxDebugSessions.x86=C4FA0
bRemoteConnAllowed.x86=C4FA4

lMaxUserSessions.x64  =F23B0
bAppServerAllowed.x64 =F23B4
bServerSku.x64        =F23B8
bFUSEnabled.x64       =F3460
bInitialized.x64      =F3464
bMultimonAllowed.x64  =F3468
ulMaxDebugSessions.x64=F346C
bRemoteConnAllowed.x64=F3470

**Comment by sevakgrig** [comment]
here are config that i use  :

[10.0.10240.18186]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=A8048
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=96A41
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=32B15
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=17264
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=2F699
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=EDC5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=3FA58
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=249D0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.10240.18186-SLInit]
bFUSEnabled.x86 =C4F88
lMaxUserSessions.x86 =C4F8C
bAppServerAllowed.x86 =C4F90
bInitialized.x86 =C4F94
bMultimonAllowed.x86 =C4F98
bServerSku.x86 =C4F9C
ulMaxDebugSessions.x86=C4FA0
bRemoteConnAllowed.x86=C4FA4

lMaxUserSessions.x64 =F23B0
bAppServerAllowed.x64 =F23B4
bServerSku.x64 =F23B8
bFUSEnabled.x64 =F3460
bInitialized.x64 =F3464
bMultimonAllowed.x64 =F3468
ulMaxDebugSessions.x64=F346C
bRemoteConnAllowed.x64=F3470

and get an listener stat error.

**Comment by wilsonfoz** [comment]
Still not listening... any tip?

**Comment by wilsonfoz** [comment]
Still not working
![image](https://user-images.githubusercontent.com/427992/58483325-7739bb00-8136-11e9-9f87-b305002e9b66.png)

Here the change was introduced by update KB4499154. Reverting to workaround.
