### ISSUE TITLE
Permanently Stop Windows Updates Tips

### ISSUE THREAD

**Issue by herbiecomputerservice** [stascorp/rdpwrap#733]
Hi,

If you want to have more control on when to install windows updates this tool actually helped me alot. Check https://www.greatis.com/stopupdates10/ 
I hope someone is helped by this. Because the wrapper not working is always happening when you don't have time... at least in my cases. 
But please lets share how you can really disable windows 10 updates... 

Ofcourse i know its a security issue this way, but i want to upgrade when i know there is a working solution in the comments and then i want to enable updates again and fix it.

Kind regard
Herbie

**Comment by sebaxakerhtc** [comment]
Not an RDPWrapper issue
