### ISSUE TITLE
fix Add support for termsrv 6.3.9600.19318 Win 8.1 x64

### ISSUE THREAD

**Issue by landroam** [stascorp/rdpwrap#736]
Please help me to fix  rdp wrapper not supported on windows 8.1 with termsrv  6.3.9600.19318

**Comment by jirijanata** [comment]
You can not read? There are two other threads with the same problem. In the newest ist solution. Please, close your issue.

**Comment by fre4kyC0de** [comment]
Add these offsets to your rdpwrap.ini:
https://github.com/fre4kyC0de/rdpwrap/blob/master/6.3.9600.19318.txt

**Comment by landroam** [comment]
thanks  fre4kyc0de!! its works fine!!

**Comment by hein-netzwerktechnik** [comment]
Server 2012r2 essential - ist works!!!
