### ISSUE TITLE
Rds

### ISSUE THREAD

**Issue by test2a** [stascorp/rdpwrap#737]
Does this also bypass remote desktop services license?

Any keygen or patcher for that?

**Comment by jirijanata** [comment]
Please, do not ask on Github for Keygens or cracks.

Use reddit, google, etc..

http://lmgtfy.com/?q=rds+license+pastebin

Please, close this issue. Thx.

**Comment by test2a** [comment]
i was not asking for links. i was asking if rdpwrap ALSO patches RDS license server?

**Comment by jirijanata** [comment]
no, and again, there is no need to patch RDS

**Comment by sebaxakerhtc** [comment]
Not an RDPWrapper issue
