### ISSUE TITLE
Windows 10 version 10.0.18362.53 not supported

### ISSUE THREAD

**Issue by jiayaoO3O** [stascorp/rdpwrap#738]
My desktop is windows 10 1903 version 10.0.18362.53,I tried to replace the `rdpwrap.ini` file with [#709](https://github.com/stascorp/rdpwrap/issues/709).and the RDPConf.exe show me [fully supported],but my RDPCheck.exe still could not work.

**Comment by jirijanata** [comment]
You need to post termsrv.dll.

Actually, I don't see any reason for supporting preview versions...

**Comment by sbzagorodin** [comment]
"10.0.18362.53" is release version of Windows 10 version 1903, not preview.

**Comment by sbzagorodin** [comment]
Actually, I don't see any reason for supporting previous versions before 18362.53.

**Comment by chrisskoni** [comment]
I am in the same situation. Please provide a Fix or working ini file. Thank you very much :-)

**Comment by chrisskoni** [comment]
MY Termsrv.dll attached. Thanks alot
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/3080361/termsrv.zip)

**Comment by jirijanata** [comment]
Windows 10 1903 was not officialy released yet. Or can you provide some official informations from Microsoft?

I see many reasons for supporting versions before 18362.53:
1809 - LTSC, 1607 - LTSB, etc. 

https://en.m.wikipedia.org/wiki/Windows_10_version_history

**Comment by chrisskoni** [comment]
I dont know why my Win10 has that version already? I have it fresh installed from an ISO with latest update and it make auto updates like every few days... 
Can you show me a way to work with the .dll myself so i can provide the ini-changes for others and me?

**Comment by swan201** [comment]
@chrisskoni 

https://github.com/stascorp/rdpwrap/issues/709

**Comment by swan201** [comment]
single session code is wrong, see my last comment

**Comment by mz8080** [comment]
> [10.0.18362.53]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=759E8
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=4CB40
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=1FE15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=22DDC
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.18362.53-SLInit]
> bInitialized.x64 =F6A8C
> bServerSku.x64 =F6A90
> lMaxUserSessions.x64 =F6A94
> bAppServerAllowed.x64 =F6A9C
> bRemoteConnAllowed.x64=F6AA0
> bMultimonAllowed.x64 =F6AA4
> ulMaxDebugSessions.x64=F6AA8
> bFUSEnabled.x64 =F6AAC

Unfortunatly,  This Does not work.
And That one Does not work either.

[10.0.18362.1]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82F35
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DDC9
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE05
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22DCC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.1-SLInit]
bInitialized.x64 =F6A8C
bServerSku.x64 =F6A90
lMaxUserSessions.x64 =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64 =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64 =F6AAC

**Comment by swan201** [comment]
@mz8080 are u restart service?

![image](https://user-images.githubusercontent.com/12713262/56459852-ad1baf00-63d4-11e9-971b-cbf29d959eb8.png)

windowws 18362.53 fully working in that code

**Comment by sbzagorodin** [comment]
swan201, 
Do not work too.
RDPCheck shows what it works but I cannot connect from another machine correctly.

**Comment by mz8080** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/49567995/56460976-69607f80-63ab-11e9-8907-15d7b696da1e.png)
Here it is. It dows not work. RDP service fails to start.

**Comment by swan201** [comment]
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/3100701/rdpwrap.zip)

try to using my rdpwarp.ini 
this file is currently fully working in my machine

**Comment by mz8080** [comment]
Thank you swan201. I used your ini file and it finally worked!

**Comment by ner00** [comment]
Why are these issues being closed without reason? Makes no sense at all...

**Comment by Kyrluckechuck** [comment]
~~Woah, super confused, but turns out the one posted by @swan201 fixed it for me.. I'm not sure how this differs from the so-far-accepted one in #766, but at this point I'm just going to give up on understanding~~

I lied. RDP Wrapper Configuration marks it all as up but `RDPWInst.exe -r` returns a lovely 1056 error on StartService, and no RDP sessions are able to get to authentication (including RDPCheck). Will continue on other thread.

**Comment by swan201** [comment]
dont use my code 

use https://github.com/stascorp/rdpwrap/issues/766 sbzagorodin  code

**Comment by v1p3r1s** [comment]
https://github.com/stascorp/rdpwrap/files/3342710/rdpwrap.zip here is ini for 18362.53. worked for me

**Comment by idleGH** [comment]
> https://github.com/stascorp/rdpwrap/files/3342710/rdpwrap.zip here is ini for 18362.53. worked for me

Да! Этот файл работает! Подтверждаю для версии termsrv =18362.53, winver 1903 (18362.239)

![2019-08-07_09-44-36](https://user-images.githubusercontent.com/45394623/62600842-8ab48f80-b8f8-11e9-9ab9-3a2e7e51beaa.png)

**Comment by prasadry** [comment]
idleGH thank you very much.you save my time.
