### ISSUE TITLE
10.0.17763.437 not supported please help sir

### ISSUE THREAD

**Issue by sailendra00** [stascorp/rdpwrap#739]
After a recent update i cant use rdp its showing not supported  10.0.17763.437 not supported please help sir provide me ini file sir

**Comment by sailendra00** [comment]
listener not supported after adding text to .ini file what to do should we change termsv.dll file??

**Comment by dimonpanik** [comment]
та же проблема

**Comment by error2221** [comment]
after update doesnt work, before it worked on windows server 2016

**Comment by IngArt** [comment]
Решение в соседней ветке https://github.com/stascorp/rdpwrap/issues/729 <= Solution for x64
Для х64 мне помогло

**Comment by msap12** [comment]
I'm looking for INI patch code for version 10.0.17763.437-SLInit    **x86**

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/720
