### ISSUE TITLE
win10 1809 + 10.0.17763.437 + not supported with KB4493509 

### ISSUE THREAD

**Issue by joxrono** [stascorp/rdpwrap#740]
when i uninstall the security update everything fine but everyday this update installed and corrupt rdpwrap

**Comment by akadi81** [comment]
Try disable windows update service. Run "cmd" as administrator and then type "services.msc" + Enter. After that you are able to disable updates. Remove last security KB with "wusa /uninstall /kb:NUMBER". Reconfigure and update rdpwrap. It's working for me, no updates, no problems. Til now. Waiting for new INI file.

**Comment by joxrono** [comment]
thanks
i have allready done it and i am wating also for new ini

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/720
