### ISSUE TITLE
Win 81 listener state not listening [not supported]

### ISSUE THREAD

**Issue by cakexxx** [stascorp/rdpwrap#745]
my system is windows 8.1  and my listen state is not listening [not supported] and the RDP check is socket connection failed . would someone help me?

**Comment by fre4kyC0de** [comment]
Add the offsets from 6.3.9600.19318.txt from https://github.com/fre4kyc0de/rdpwrap to your RDPWrap.ini

**Comment by cakexxx** [comment]
the listener state is [fully supported] while not listening

**Comment by cakexxx** [comment]
the listener state is not listening [fully supported] now

> Add the offsets from 6.3.9600.19318.txt from https://github.com/fre4kyc0de/rdpwrap to your RDPWrap.ini

**Comment by fre4kyC0de** [comment]
Win 8.1 x86 or x64?

Working fine here on x64

**Comment by cakexxx** [comment]
> Win 8.1 x86 or x64?
> 
> Working fine here on x64

well, x64. by the way, add the offsets mean "add the texts in the file "?

**Comment by fre4kyC0de** [comment]
Correct

**Comment by cakexxx** [comment]
works after reinstallment. thanks

**Comment by chair008** [comment]
> the listener state is not listening [fully supported] now
> 
> > Add the offsets from 6.3.9600.19318.txt from https://github.com/fre4kyc0de/rdpwrap to your RDPWrap.ini

Please.... the link is not available.

**Comment by themikesam** [comment]
@cakexxx  could you share the config? the link is not available

**Comment by sebaxakerhtc** [comment]
It's not clear of version. No screenshot, no file provided
