### ISSUE TITLE
Maximum 16 users, after that black screen.

### ISSUE THREAD

**Issue by zaiclopz** [stascorp/rdpwrap#746]
Hello, since 2 or 3 updates i have this strange issue.
I use my PC for 25 users with RDPWrap, but it seems to be a limit.
Once 16 users logged in, no one else can log on. It shows a black screen and a message that the remote sesion has ended.

If i disconect one user from task manager, then it can log on, but again only till 16.
Also, if i manualy log on the user on the PC, for example 3 users that are not connected, after that those 3 users can connect, and now i have 19 connected, and so on..

**Comment by j1nseng** [comment]
Why don't u use Windows Server? It's strange to try home system for your purpose.

**Comment by chocolait** [comment]
> Why don't u use Windows Server? It's strange to try home system for your purpose.

thin clients

Any progress on this? Since 10.0.18362.267, this happens to me too. Only 16 RDP users.

**Comment by sebaxakerhtc** [comment]
Дуплицате оф https://github.com/stascorp/rdpwrap/issues/512
