### ISSUE TITLE
Question about the Windows Home version and the use of rdpwrap

### ISSUE THREAD

**Issue by BarryBA** [stascorp/rdpwrap#747]
My windows is Windows Home Version, which has no remote desktop function, just like the screenshot:
![image](https://user-images.githubusercontent.com/35425412/56121320-73950f00-5fa2-11e9-9e2a-85bdef1a8e03.png)
But before I installed the rapwarp, when I search the "Remote Desktop" in the windows search box (or Cortana), I can also find the software:
![image](https://user-images.githubusercontent.com/35425412/56121479-ccfd3e00-5fa2-11e9-9b26-ec2549a04cff.png)
I wonder to know why my home version windows still has the "Remote Desktop" software?
After I installed the rdpwarp, how do I use it?  
Should I still use this software shown above? If so, I don't have to install the rdpwarp, isn't it?
Thanks a lot for your answers.

**Comment by j1nseng** [comment]
You must install the Rdpwrap in order to have ability to use multiple connections to your PC.  Please scroll down here https://github.com/stascorp/rdpwrap and read what it is, and how it works.
