### ISSUE TITLE
after the KB4493464 no multiple login possible on WIn10 pro

### ISSUE THREAD

**Issue by larieu** [stascorp/rdpwrap#748]
After this install not able to multiple login any more

tried uninstall the wrapper / reinstall / manual remove ....
nothing worked 

uninstall the patch
everything resumed without problems

**Comment by j1nseng** [comment]
Try this https://github.com/stascorp/rdpwrap/issues/744

**Comment by susl16c** [comment]
No it doesn't help

**Comment by larieu** [comment]
No 
is not a solution

**Comment by joebrug** [comment]
Go here https://github.com/fre4kyC0de/rdpwrap , find your version and add the contents to your rdpwrap.ini, reboot.

**Comment by SealedCrib** [comment]
After going to https://github.com/fre4kyC0de/rdpwrap as Joebrug pointed out, make sure you leave a space at the end of your ini file. As in, you cannot have text at the bottom of the ini file, make sure after copying, you hit return, then save.

**Comment by sebaxakerhtc** [comment]
Closed as not actual
