### ISSUE TITLE
Add support for termsrv.dll version 6.2.9200.22715

### ISSUE THREAD

**Issue by hartimcwildfly** [stascorp/rdpwrap#749]
There is no entry in rdpwrap.ini for version 6.2.9200.22715.
So rdp-conf shows "not supported" for this version.

If you give a short how to, I can try to find the bytecode addresses by myself and then create a pull request. Do you decompile the termsrv.dll?

**Comment by FZappatta** [comment]
See here ....
https://www.mysysadmintips.com/windows/clients/545-multiple-rdp-remote-desktop-sessions-in-windows-10

**Comment by jirijanata** [comment]
1. Post your termsrv.dll (and also write us, if it's 64 or 32 bit). (it will be 64 bit :) )
https://github.com/fre4kyC0de/rdpwrap/blob/master/6.2.9200.22715.txt
2. Do not use Windows 8, if you want to stay at Windows 8, please upgrade to 8.1. Windows 8 are not supported anymore! If you are using Windows Server 2012 (what's more likely), do not use RDP Wrapper but use RDS instead. Then you don't need to worry about new Windows Updates..

**Comment by affinityv** [comment]
[6.2.9200.22715]
; x86-Offsets are not safe (determined without symbols)
SingleUserPatch.x86=1
SingleUserOffset.x86=155B2
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=2BAE4
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=13F68
DefPolicyCode.x86=CDefPolicy_Query_eax_esi
DefPolicyPatch.x64=1
DefPolicyOffset.x64=2A396
DefPolicyCode.x64=CDefPolicy_Query_eax_rdi
SLPolicyInternal.x86=1
SLPolicyOffset.x86=195B9
SLPolicyFunc.x86=New_Win8SL
SLPolicyInternal.x64=1
SLPolicyOffset.x64=21F90
SLPolicyFunc.x64=New_Win8SL

PS: I never made it, but I've got an rdpwrap.ini file that has lots from all over the place.

**Comment by SergiuEnachi** [comment]
I can confirm this worked on a Server 2012 (non-R2). thanks @affinityv

**Comment by hartimcwildfly** [comment]
I can confirm, too. Thank you!

**Comment by fre4kyC0de** [comment]
Due to the comment, I would say the offsets are the ones I created
