### ISSUE TITLE
Thin clients having trouble connecting after fixing Win 8.1 machine for Issue #745

### ISSUE THREAD

**Issue by EliezerBee** [stascorp/rdpwrap#751]
I have two thin clients used to connect to a Win 8.1 x64 machine. When powered on, they immediately show the account pictures of all Windows accounts on the server. Ever since I had and fixed the problem described in https://github.com/stascorp/rdpwrap/issues/745 they haven't connected correctly anymore.

- One of them is "confused" and just shows a black screen.
- The other one pops up a generic Windows login dialog asking for username/password  with the option of adding in a domain. When correct credentials are entered, the RDP session _does_ connect to that user.

The timing of RDP Wrapper breaking (due to issue #745) and my fixing it coincided exactly with the thin clients' wackiness beginning. These two issues _have_ to be somehow related.
_Details follow..._

I followed the advice offered in the issue: https://github.com/stascorp/rdpwrap/issues/745#issuecomment-482889047
and appended the text from here https://github.com/fre4kyC0de/rdpwrap/blob/master/6.3.9600.19318.txt
into my INI file
[rdpwrap.ini (changed extention to upload here).txt](https://github.com/stascorp/rdpwrap/files/3085434/rdpwrap.ini.changed.extention.to.upload.here.txt)

My settings look like this:
![RDP Wrapper settings](https://user-images.githubusercontent.com/5578694/56218884-56f0e980-602b-11e9-864b-20e208d263ff.jpg)

And these were my recent Windows updates:
![my recent Windows updates](https://user-images.githubusercontent.com/5578694/56219299-1e9ddb00-602c-11e9-919a-7e2adbc2aa82.png)

What might be the problem with my server's RDP/RDP Wrapper configuration?

Thanks much,
Eli

**Comment by EliezerBee** [comment]
I found the problem:  my thin clients only connect normally when RDP Wrap's _"Authentication Mode"_ is set to _"GUI Authentication Only"_. So when I switched it to that, it now works.

But is that secure to use?

**Comment by fre4kyC0de** [comment]
Might be a combo with some RDP problems MS introduced in one of the last rollups (I think it was 01-2019 or 02-2019 but I‘m unsure)...

**Comment by EliezerBee** [comment]
Is _"GUI Authentication Only"_ secure to use?

**Comment by princepsycho** [comment]
Hi is there a way to set it up on "GUI Authentication Only" from the command prompt ?

**Comment by EliezerBee** [comment]
An [article](https://amp.tomshardware.com/news/million-windows-systems-rdp-vulnerability,39520.html) on Toms Hardware says:

> Microsoft noted that Windows 8 and Windows 10 machines are partially protected against any potential worms that could be created with the help of this vulnerability due to these operating systems benefiting from a new mitigation called [Network Level Authentication (NLA)](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc732713(v=ws.11)).
> 
> This feature simply requires a user to authenticate before establishing an RDP sessions. However, Microsoft warned that attackers with valid credentials could still abuse the vulnerability to cause some damage inside computer networks. Therefore, the company is recommending all Windows users to update their systems as soon as possible.

So back to my [question above](https://github.com/stascorp/rdpwrap/issues/751#issuecomment-486767282): is it safe to set RDP Wrap's "Authentication Mode" to _"GUI Authentication Only"?_

**Comment by sebaxakerhtc** [comment]
Closed as not actual
