### ISSUE TITLE
Win10 Home not listening

### ISSUE THREAD

**Issue by dampl** [stascorp/rdpwrap#753]
could you tell me how can I fix it? 

Yes, I need 3390, because my internet provider redirect 3390 to my local address. 

[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/3088844/rdpwrap.txt)
![rdpwrapper](https://user-images.githubusercontent.com/49714533/56277186-2cbf2a80-6104-11e9-8526-dfa010e868c9.png)

![updates](https://user-images.githubusercontent.com/49714533/56277564-e28a7900-6104-11e9-8f19-aec0685849fc.png)

![access denied](https://user-images.githubusercontent.com/49714533/56277858-693f5600-6105-11e9-8b9e-c93586a36f42.png)
it means access denied

**Comment by SealedCrib** [comment]
Go here https://github.com/fre4kyC0de/rdpwrap , find your version and add the contents to your rdpwrap.ini, reboot. Make sure you leave a space at the end of your ini file. RDPwrap will not function properly if there is any text at the bottom of the ini file, it needs to end with a blank space.

**Comment by sebaxakerhtc** [comment]
Closed as not actual
