### ISSUE TITLE
What is "Listener state: Not listening" in general

### ISSUE THREAD

**Issue by 1Pekol** [stascorp/rdpwrap#754]
Hi,
I copy my own rdpwrap.ini by similar code:
  net stop UmRdpService
  net stop termservice
  copy /b rdpwrap.ini "c:\Program Files\RDP Wrapper"
  net start termservice
  net start UmRdpService
It is ok, but sometimes result is "Listener state: Not listening". After restart PC everything is OK. Can I restrat some service or something similar to managed it without restart whole PC?
Thanks for help.

**Comment by SealedCrib** [comment]
Try restarting remote desktop services

**Comment by bezik46** [comment]
@SealedCrib

net stop termservice
net start termservice

does EXACTLY that, so if you cannot help then move on politely

**Comment by sebaxakerhtc** [comment]
It can be error of owner of file or file can be used by another process. Look at log

**Comment by sebaxakerhtc** [comment]
Closed as not actual
