### ISSUE TITLE
WINDOWS SERVER FOUNDATION

### ISSUE THREAD

**Issue by PCJOVE** [stascorp/rdpwrap#756]
ERROR LISTENING NOT SUPPORTED 
SERVICE STATE V.6.2.9200.22715

**Comment by SealedCrib** [comment]
Go here https://github.com/fre4kyC0de/rdpwrap , find your version and add the contents to your rdpwrap.ini, reboot. make sure you leave a space at the end of your ini file. As in, you cannot have text at the bottom of the ini file, make sure after copying, you hit return, then save.

**Comment by PCJOVE** [comment]
oK now several computers are connected, but in the remote desktop configuration, apart from the ip, sometimes I have to put: 3389 to connect and other times remove it to connect

**Comment by sebaxakerhtc** [comment]
Closed as not actual
