### ISSUE TITLE
CANNOT ADD .INI FILE

### ISSUE THREAD

**Issue by Jchapel15** [stascorp/rdpwrap#757]
Hi all,

I installed the latest version and when launched, I am getting a message stating that it is not supported.  The version that is installed is 10.0.17763.437.  I saw some posts about adding extensions onto the .ini file but am having a hard time finding that. 

Can someone please show me a step by step guide to making this happen?  Thanks so much.

**Comment by sumohax0r** [comment]
You can update the INI file by running "net stop termservice" in CMD prompt as admin. You'll then have to reboot to get it running again.

I did this today but was unable to get the wrapper working with latest version of windows :/

**Comment by tekwerx** [comment]
This .ini file did the trick for version 10.0.17763.437.

https://github.com/stascorp/rdpwrap/issues/744#issuecomment-483099457

**Comment by MicrosoftwareHack** [comment]
Do not waste your time editing files.ini or another file, the multiuser file is the termserv.dll in system32. with the update it stops being multiuser and is protected in such a way that the usual installation no longer replaces it or can modify it

I tell you if I have a saved master key, it will allow me to copy other users freely after I have the management?

wake up! github.com is from Microsoft, with that I tell them everything

**Comment by QwertyTester** [comment]
> Не тратьте свое время на редактирование files.ini или другого файла, многопользовательский файл - termserv.dll в system32. с обновлением оно перестает быть многопользовательским и защищено таким образом, что обычная установка больше не заменяет его и не может его изменить

I have several computers under Windows 7 about x64 and Windows 10 about x64. Everything works for them. With the latest updates at the moment. It does not work on one, and I suffer with it. All conditions are identical - but ...... on one does not work. It's not the file termserv.dll в system32.

**Comment by Wolf1975** [comment]
Sori for Google translation I can not in English
Download the necessary ini file. Run the CMD as an administrator, run explorer there, and use it to copy and paste the ini file along the path c: \\ Program Files \\ RDP Wrapper \\

**Comment by bezik46** [comment]
> Do not waste your time editing files.ini or another file, the multiuser file is the termserv.dll in system32. with the update it stops being multiuser and is protected in such a way that the usual installation no longer replaces it or can modify it
> 
> I tell you if I have a saved master key, it will allow me to copy other users freely after I have the management?

What did you want to say here? Because in English none of it makes any sense!

**Comment by sebaxakerhtc** [comment]
Closed as not actual
