### ISSUE TITLE
Please support for Windows 10 1809 - 10.0.17763.437

### ISSUE THREAD

**Issue by miguelcarr** [stascorp/rdpwrap#759]
The computer updated from Windows 10 1809 - 10.0.17763.379 to Windows 10 1809 - 10.0.17763.437 and now rdp wrapper is not working anymore.

**Comment by CypherAus** [comment]
Try this...  https://github.com/stascorp/rdpwrap/issues/741

**Comment by gavazquez** [comment]
Or just check the ini file at this fork:
https://github.com/DrDrrae/rdpwrap/blob/66b3358c52fd3bed211d0ead73f656ac59fd18f5/res/rdpwrap.ini

**Comment by andrew521** [comment]
> Or just check the ini file at this fork:
> https://github.com/DrDrrae/rdpwrap/blob/66b3358c52fd3bed211d0ead73f656ac59fd18f5/res/rdpwrap.ini

Doesn't work for me. It would disconnect any other existing sessions when launched.

**Comment by VirheCZ** [comment]
> Or just check the ini file at this fork:
> https://github.com/DrDrrae/rdpwrap/blob/66b3358c52fd3bed211d0ead73f656ac59fd18f5/res/rdpwrap.ini

I did work for me like a charm :)

**Comment by VirheCZ** [comment]
> > Or just check the ini file at this fork:
> > https://github.com/DrDrrae/rdpwrap/blob/66b3358c52fd3bed211d0ead73f656ac59fd18f5/res/rdpwrap.ini
> 
> Doesn't work for me. It would disconnect any other existing sessions when launched.

Have you tried "RDPWinst.exe -r" (should restart the service) afterwards?

**Comment by andrew521** [comment]
> Have you tried "RDPWinst.exe -r" (should restart the service) afterwards?

c:\Program Files\RDP Wrapper>RDPWInst -r
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Restarting...
[+] TermService found (pid 15772).
[*] No shared services found.
[*] Terminating service...
[*] Starting TermService...
[-] StartService error (code 1056).
[+] Done.

c:\Program Files\RDP Wrapper>

**Comment by orzass** [comment]
> Or just check the ini file at this fork:
> https://github.com/DrDrrae/rdpwrap/blob/66b3358c52fd3bed211d0ead73f656ac59fd18f5/res/rdpwrap.ini

it's work for me! tks!

**Comment by orzass** [comment]
> > Have you tried "RDPWinst.exe -r" (should restart the service) afterwards?
> 
> c:\Program Files\RDP Wrapper>RDPWInst -r
> RDP Wrapper Library v1.6.2
> Installer v2.5
> Copyright (C) Stas'M Corp. 2017
> 
> [_] Restarting... [+] TermService found (pid 15772). [_] No shared services found.
> [_] Terminating service... [_] Starting TermService...
> [-] StartService error (code 1056).
> [+] Done.
> 
> c:\Program Files\RDP Wrapper>

when i run RDPWInst -r, output code same like you, but rdp successful run on my computer.

**Comment by zcq0730** [comment]
> > Have you tried "RDPWinst.exe -r" (should restart the service) afterwards?
> 
> c:\Program Files\RDP Wrapper>RDPWInst -r
> RDP Wrapper Library v1.6.2
> Installer v2.5
> Copyright (C) Stas'M Corp. 2017
> 
> [_] Restarting... [+] TermService found (pid 15772). [_] No shared services found.
> [_] Terminating service... [_] Starting TermService...
> [-] StartService error (code 1056).
> [+] Done.
> 
> c:\Program Files\RDP Wrapper>

Thanks a lot! This works for me.

**Comment by JaWaRo** [comment]
#795 Works

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/720
