### ISSUE TITLE
Win10 home access denied on external network

### ISSUE THREAD

**Issue by dampl** [stascorp/rdpwrap#761]
when I try to connect on external network I have access denied
On local network works properly

RDP Wrapper Conf
![rdpwrapperconf](https://user-images.githubusercontent.com/49714533/56648275-512a8200-6683-11e9-8b71-62ca613e7e40.png)

Any ideas?

**Comment by acdcjavier** [comment]
Hello
The Default RDP port is 3389.

If you want to change the port to 3390 (as you are using now) you need to change the default windows RDP port:

https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/change-listening-port

You need to check the listener state must be green.
Also you must to ensure that tour router is the 3390 port opened

**Comment by sebaxakerhtc** [comment]
Closed as not actual
