### ISSUE TITLE
Use existing .ini during install?

### ISSUE THREAD

**Issue by bezik46** [stascorp/rdpwrap#762]
`psexec \\some-pc -accepteula -c \\server\share\wrapper\install\RDPWInst.exe "-i"`

That does not use existing .ini file \\server\share\wrapper\install\rdpwrap.ini but insists on extracting

[+] Extracted config -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll

HOW do I make it use existing .ini ?

**Comment by bezik46** [comment]
Nobody?

**Comment by ZeljkoManjkas** [comment]
Try use -w to set directory on remote machine.

**Comment by bezik46** [comment]
Sadly the -w option seems to insist on getting the ini from elsewhere!

`RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[] Checking for updates...
[] Current update date: 2019.04.19
[] Latest update date: 2018.10.10
[] Your INI file is newer than public file. Are you a developer? :)
RDPWInst.exe exited on computer4 with error code 0.`

**Comment by bezik46** [comment]
Easier to just copy .ini by hand (or GPO) and then do -r

**Comment by sebaxakerhtc** [comment]
Closed as not actual
