### ISSUE TITLE
Troubleshooting steps for 10.0.17134.706, "Access denied", "Not Listening", "[not supported]"

### ISSUE THREAD

**Issue by Cobertos** [stascorp/rdpwrap#765]
I seemingly ran into every common issue while installing RDPWrap, so I just wanted to put together a troubleshooting guide to pull together all the information in the many other issues. 
I'm running 10.0.17134.706 for reference.

Here's the status I ran into and how each one was fixed.
Wrapper Status: Installed
Service State: Running
Listener State: **Not Listening** 

To fix this, you need the most up to date `.ini` file (located in `C:\Program Files\RDPWrapper\rdpwrap.ini`). The most comprehensive one I found was [this one from Zeljko Manjkas](https://github.com/stascorp/rdpwrap/issues/763#issuecomment-487463650). After downloading this and replacing the original `.ini`, you need to [restart the service using `RDPWInst.exe -r`](https://youtu.be/W9BpbEt1yJw?t=198). After you have the right `.ini` with the right offsets for `termsvr.dll` and restart the service, this should go green. If not, open the `.ini` file and do a `Ctrl+F` for your windows version number. If it's not in there, you either [need to make it yourself by disassembling the original .dll](https://www.youtube.com/watch?v=FiD86tmRBtk&t=687s) or wait for another developer to help you out.

**[not supported]** / "Access denied" when logging in with `RDPCheck.exe`

I found when using RDPCheck.exe, I would get an "Access denied" error after logging in. Some people suggest [modifying the permissions on the `rdpwrap.dll` in `C:\Program Files\RDPWrapper\rdpwrap.dll`](https://github.com/stascorp/rdpwrap/issues/391#issuecomment-452162676) to allow for full control but this did not work for me. I found that my issue was related to the default `Single session per user` checkbox being checked, which is it's default. Unchecking it and restarting the service got me `[fully supported]`. Thanks to [this comment](https://github.com/stascorp/rdpwrap/issues/37#issuecomment-160430624) for helping me figure this out. I was reading that this has something to do with newer versions of Windows not supporting the feature or something?

Hope this helps, they're all simple fixes, you just have to know where to look.

**Comment by theresnotime** [comment]
Thanks for this 👍 

For anyone else, I'm running;
<pre>
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17134  0
</pre>
and the above mentioned `.ini` [from Zeljko](https://github.com/stascorp/rdpwrap/issues/763#issuecomment-487463650) fixed the issue

**Comment by silencexuzhaoxing** [comment]
Thank you very much,it solved my problem

**Comment by Pengyang233** [comment]
Thank you very much, it helped me a lot and solved the problem!!!

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/721
