### ISSUE TITLE
RDPWrap issue 10.0.17763.437 even after update

### ISSUE THREAD

**Issue by CipherNameRaven** [stascorp/rdpwrap#769]
Hello, 
I have Windows 10 64bit pc. I have applied fix #720. According to the RDP Wrapper Configuration everything is good.   However, when I run RDPCheck.exe, it spits out en error:
"The number of connections to this computer is limited and all connections are in use right now. Try connecting later or contact your system administrator."
If I try to connect to it from another PC, it acts like the Wrapper is not even there, and attempts to sign off the second use. 
![image](https://user-images.githubusercontent.com/50176776/57026135-01116980-6c07-11e9-9a69-35fe800527bb.png)

I have restarted the computer. I have reinstalled the RDPwrapper. Same issue. Does anyone have any ideas?

**Comment by andrew521** [comment]
There are six other tickets already open for 10.0.17763.437. There is no fully working solution at this time.

**Comment by j1nseng** [comment]
https://github.com/stascorp/rdpwrap/issues/744
Tested and working on many machines with 10.0.17763.437

**Comment by CipherNameRaven** [comment]
Thanks, j1nseng! 
That worked beautifully after I restarted Remote Desktop Services.
