### ISSUE TITLE
W10 Update 17763.475

### ISSUE THREAD

**Issue by CONTIGIANLUCA** [stascorp/rdpwrap#772]
More problem ...
with last update not wok RDP.
Anybody have the new rdpwrap.ini ?

**Comment by serge-io** [comment]
This ini file worked for me on 17763.475

https://github.com/stascorp/rdpwrap/issues/744

**Comment by CONTIGIANLUCA** [comment]
Work with 17763.437 but with 17763.475 NOT WORK !

**Comment by serge-io** [comment]
Same for me at the start. Then I uninstalled rdwrapper, install again, replace ini file, restart terminal service, than everything works.

**Comment by pdean** [comment]
system about says 475 but rdpconf says 437!?  The ini in #744 still works for me

**Comment by n8claw** [comment]
same ini file like here..
https://github.com/stascorp/rdpwrap/files/3138022/rdpwrap_corrected_single_10.0.17763.437.zip
stop term service, install ini file and start again.

The .475 is the actually os build but working dll is 437, show picture.
I use windows 10 pro 64-bit version.
https://cl.ly/0514fcfd0c05

**Comment by Nikolike** [comment]
I had the same problem and i can't find the way to fix it!! @n8claw I tried your method but it still no work..

**Comment by Tuumke** [comment]
We are noticing that the system is slower then with previous version :(. Anyone else has this problem?
ini file: https://pastebin.com/2Xc9H2Ve

**Comment by gustavovelascoh** [comment]
Thanks @n8claw, it did work for me.

**Comment by Tuumke** [comment]
Nobody who has problems with performance?

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/720
