### ISSUE TITLE
Windows 10.0.17763.165 - update done but only single session possible

### ISSUE THREAD

**Issue by MerisaCWC** [stascorp/rdpwrap#775]
Hello,
I did everything as described in [https://github.com/stascorp/rdpwrap/issues/697](url)
Listener state is Listening (fully supported) but i can only start one session at a time.
what am I doing wrong?

![grafik](https://user-images.githubusercontent.com/46190635/57374653-a2fefc00-719b-11e9-9ce9-4cc741d66d98.png)

![grafik](https://user-images.githubusercontent.com/46190635/57374663-a8f4dd00-719b-11e9-924e-e5bf2df231f1.png)

**Comment by PCMacDr** [comment]
uncheck single session to see if that helps

**Comment by MerisaCWC** [comment]
change "Default RDP Authentication" has no effect.
"Single session per user" is necessary and must remain so but a change has no effect.
Does anyone have an idea what I can do?

**Comment by christian-elias** [comment]
I had the same issue
this worked for me
https://github.com/stascorp/rdpwrap/issues/763#issuecomment-487466729

**Comment by MerisaCWC** [comment]
Thanks a lot. This ini worked fine for me.
