### ISSUE TITLE
Win 10 Pro Listening but not supported

### ISSUE THREAD

**Issue by Phishy042** [stascorp/rdpwrap#776]
Installed flawlessly on 2 machine over the past 3 months, this third however i cannot get working.  I dont have any of the security updates to remove like in other posts, and i have appended the .ini file but still no avail.  Any help would be appreciated.

![rdpwrapper](https://user-images.githubusercontent.com/50459755/57478877-0e170400-726a-11e9-951b-279a0ab892e3.PNG)

**Comment by joebrug** [comment]
They're all the same windows version? what about the termsrv.dll file? Have you tried copying/pasting a "working" rdpwrap.ini file to the non-working computer?

**Comment by Phishy042** [comment]
I just tried copy/pasting a working ini file to the nonworking machine and was still having same issues.

**Comment by Wikibear** [comment]
Same issue here.

**Comment by sebaxakerhtc** [comment]
Is this issue still actual?

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/720
