### ISSUE TITLE
support for 10.16299.1087?

### ISSUE THREAD

**Issue by rezeptpflichtig** [stascorp/rdpwrap#778]
Hello my windows updated despite no update policy so it stopped working now.
any input how i can find out the new values?

**Comment by rezeptpflichtig** [comment]
I tried debugging it and

> [10.0.16299.1087]
> ; Patch CEnforcementCore::GetInstanceOfTSLicense
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=8FC11
> LocalOnlyCode.x64=jmpshort
> ; Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
> SingleUserPatch.x64=1
> SingleUserOffset.x64=1C785  // not sure about this one..
> SingleUserCode.x64=Zero
> ; Patch CDefPolicy::Query
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=12D85
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> ; Hook CSLQuery::Initialize
> SLInitHook.x64=1
> SLInitOffset.x64=22D5C
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.16299.1087-SLInit]
> bServerSku.x64        =ED3E8
> lMaxUserSessions.x64  =ED3EC
> bAppServerAllowed.x64 =ED3F0
> bInitialized.x64      =EE4A0
> bRemoteConnAllowed.x64=EE4A4
> bMultimonAllowed.x64  =EE4A8
> ulMaxDebugSessions.x64=EE4AC
> bFUSEnabled.x64       =EE4B0

but it does not work.
this is my termsrv.dll (64bit)
https://www.filehosting.org/file/details/799721/termsrv-10.0.16299.1087.dll
if anyone can take a look who did this already sucessfully?

**Comment by Benjamin-Loison** [comment]
Same problem.

**Comment by fre4kyC0de** [comment]
Try this

https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.16299.1087.txt

**Comment by Benjamin-LOISON** [comment]
I replaced with previous in C:\Program Files\RDP Wrapper\rdpwrap.ini but when I restart and check with RDPConf, service state goes directly to stopped. Ideas ? (thank you)

**Comment by Benjamin-Loison** [comment]
> Try this
> 
> https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.16299.1087.txt

I replaced with previous in C:\Program Files\RDP Wrapper\rdpwrap.ini but when I restart and check with RDPConf, service state goes directly to stopped. Ideas ? (thank you)

EDIT: okay I was looking how was this configuration file by default and I simply realized that the whole file you gave me isn't to be replaced by the old one, I just added after [PatchCodes] section and everything fine, thank you so much ! :)

**Comment by rezeptpflichtig** [comment]
@fre4kyC0de thank you very much
after a `RDPWInst -r`
it works now perfectly.
I will take a look where you changed the bits and try again myself next time.
very much appreciated

**Comment by Benjamin-Loison** [comment]
@fre4kyC0de same problem with 10.0.17134.885, could you send again please or post a kind of video to explain how to do the right stuff to write by ourselves the stuff to add in the config file please ?
