### ISSUE TITLE
Another device has connected to this session, disconnecting you (code DisconnectedByOtherConnection(5))

### ISSUE THREAD

**Issue by lgbeno** [stascorp/rdpwrap#78]
I just installed rdpwrap on Windows 10.  It works quite well except that every 3-5 min, I get disconnected with the error message above.

I am connecting to the machine via the Remote Desktop Client for Mac.  Also, I can assure you that there is not another person on my network trying to connect to this machine.

**Comment by binarymaster** [comment]
Network protocol errors are not related to RDP Wrapper, because its code doesn't have control over network.
