### ISSUE TITLE
Stopped connecting

### ISSUE THREAD

**Issue by blueberry-bytes** [stascorp/rdpwrap#781]
I've been using RDP Wrapper for years now. Every time after Windows 10 update new ini file worked for me. This time it's different. Although it says that everything is OK, I can't connect. Last week I had this problem, I changed port number and it was working few days without restarting. But during weekend I had to restart and again it's not connecting and changing port this time doesn't help. What can I do?

![image](https://user-images.githubusercontent.com/5322956/57598696-81639300-7554-11e9-9302-2bd25f62eea1.png)

![image](https://user-images.githubusercontent.com/5322956/57598725-9e986180-7554-11e9-8ddb-542643cbb9bb.png)

**Comment by aloksharma1** [comment]
i tried this one and its working for me https://github.com/stascorp/rdpwrap/issues/763
can you try and let us know

**Comment by blueberry-bytes** [comment]
Yes, it's working now, thank you. Earlier I was trying this INI https://github.com/stascorp/rdpwrap/issues/744 and it wasn't working.
