### ISSUE TITLE
Se actualizo Windows 10 pro 64 bits 10.0.17763.437 con un parche de seguridad el 15 05 2019

### ISSUE THREAD

**Issue by jonathan19091** [stascorp/rdpwrap#784]
He estado probado que cuando se actualiza el windows 10 pro se pueda seguir usando pero en esta ocasión después de actualizar windows con unos parches de seguridad estos ya no deja trabajar bien, y aun tengo la misma version Windows 10 pro 64 bits 10.0.17763.437.
Las actualizaciones fueron la KB4494441.

![DEL CONFIGURADOR RDP](https://user-images.githubusercontent.com/46203359/57801470-63935b00-7719-11e9-93c9-52507fc776aa.PNG)

**Comment by jonathan19091** [comment]
yo tengo el mismo error y por más que veo el código, pero intente algo después de reiniciar el servicio de escritorio remoto ejecute un bat que tengo el cual es:

CD C: \ Discos \ RDP 
RDPWInst -r

Y esta función se cumple y se ejecuta sin error de error.

No se puede tener la solución final, y poder dar un beneficio entre todos los aspectos económicos.

**Comment by jonathan19091** [comment]
[rdpwrap_JONH.zip](https://github.com/stascorp/rdpwrap/files/3192476/rdpwrap_JONH.zip)

use ese archivo .ini para poder hacer trabajar de nuevo pero como comento cree la tarea para que cada que reinicio este no me de problemas.

**Comment by reddit-reaper** [comment]
thanks @jonathan19091 that ini worked perfectly! please keep it updated somewhere great help :)

**Comment by sezercoban** [comment]
I couldn't understand any word but @jonathan19091 's ini file is works with 17763.503 !! Muchas gracias!

**Comment by KevinH404** [comment]
@jonathan19091 @reddit-reaper @sezercoban 

[Here](https://github.com/stascorp/rdpwrap/files/3062713/rdpwrap.zip) ini file with solution for 64bits 10.0.17763.437

![image](https://user-images.githubusercontent.com/12038888/58157949-84d1e980-7ccd-11e9-9593-b7b685287b7a.png)

**Comment by Maed-Portales** [comment]
Hasta la semana pasada me funcinaba bien.
Alguie sabe como puedo arrancar de nuevo el RDP, No ejecuta al 100%,
Me puede ayudar a ejecutarlo?
 
 
![RDP](https://user-images.githubusercontent.com/15661110/70942100-88cfab00-2013-11ea-885b-d7049358b1a9.JPG)

**Comment by sebaxakerhtc** [comment]
Duplicate of Duplicate of https://github.com/stascorp/rdpwrap/issues/720
