### ISSUE TITLE
MS KB4499164 causes RDP Wrapper to fail

### ISSUE THREAD

**Issue by RoppXs2** [stascorp/rdpwrap#785]
Having just installed the latest Microsoft updates I was no longer able to use RDP Wrapper.  I removed all the updates I installed and then tested each one separately...after installing May 14, 2019—KB4499164.  RDP Wrapper would no longer allow multiple user connections on Windows 7 Pro.  Once removed, RDP Wrapper worked again.

**Comment by ericvb** [comment]
Yesterday, my PC, running Windows 10, did install his updates and now I have the same problem.
Searched the given KB number but didn't find it. Probably the number is different on Windows 10 versions.
But same problem, no possibility anymore to connect a second session to the same machine.

**Comment by Mayar** [comment]
Confirm the problem.

**Comment by tiagowippel** [comment]
Same here.

**Comment by rbasche** [comment]
I newly installed RDPWrap to Win 10 x64 17763.503. I did not work, it did not allow me more than 1 rdp session.
After updating the rdpwrapper.ini file with the 437 and later additions from (i.e 437, 475 and 503) here it worked:
https://github.com/stascorp/rdpwrap/issues/744#issuecomment-485531249

**Comment by EngelbertAnon** [comment]
On Windows 7 Pro Sp1 x64 with the new KB4499164 update, version "6.1.7601.24402" is reported and this update for the rdpwrapper.ini file works for me with multiple users: 
```
[6.1.7601.24402]
SingleUserPatch.x86=1
SingleUserOffset.x86=1A675
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=17F26
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=19E41
DefPolicyCode.x86=CDefPolicy_Query_eax_esi
DefPolicyPatch.x64=1
DefPolicyOffset.x64=17CFE
DefPolicyCode.x64=CDefPolicy_Query_eax_rdi
```

I didn't test the x86 Version.

**Comment by proxyolism** [comment]
I'm using windows 10 home edition, updated about 3 or 4 days ago, and after update, RDP wrapper doesn't work. maybe KB4497398 and/or KB4499167 affects with this issue.

**Comment by ericvb** [comment]
I tested the proposed solution by modifying the ini file with the one from https://github.com/stascorp/rdpwrap/issues/744 (first topic comment) and I can confirm that it works in my case.

**Comment by RoppXs2** [comment]
Thank you.

Sent from my iPad

On May 18, 2019, at 12:48 AM, EngelbertAnon <notifications@github.com> wrote:

On Windows 7 Pro Sp1 x64 with the KB4499164 the Version "6.1.7601.24402" is reported and this update for the rdpwrapper.ini file works for me with multiple users:

[6.1.7601.24402] SingleUserPatch.x86=1 SingleUserOffset.x86=1A675 SingleUserCode.x86=nop SingleUserPatch.x64=1 SingleUserOffset.x64=17F26 SingleUserCode.x64=Zero DefPolicyPatch.x86=1 DefPolicyOffset.x86=19E41 DefPolicyCode.x86=CDefPolicy_Query_eax_esi DefPolicyPatch.x64=1 DefPolicyOffset.x64=17CFE DefPolicyCode.x64=CDefPolicy_Query_eax_rdi

I didn't test the x86 Version.

**Comment by mauro-miatello** [comment]
fixed, thanks!
I've had to copy new ini with:
copy /y rdpwrap.ini "c:\program files\rdp wrapper\rdpwrap.ini"
in an elevated terminal

**Comment by sebaxakerhtc** [comment]
No file or rdpconf screenshot. It's not clear which version
