### ISSUE TITLE
Add support for new versions

### ISSUE THREAD

**Issue by ChD1** [stascorp/rdpwrap#79]
Don't work.
http://c2n.me/3sSyH5v

**Comment by Grezzo** [comment]
Same for me after a windows update. I notice that if I uninstall/reinstall, there is a message logged saying:
    [*] Terminal Services version: 10.0.10586.0
    [-] This version of Terminal Services is not supported.
    Send your termserv.dll to project developer for support.
So that is what I have done here: [termsrv.zip](https://github.com/binarymaster/rdpwrap/files/90144/termsrv.zip)

I hope that gives enough information to add support for this version.

**Comment by fig2k4** [comment]
Same problem here with 10.0.11082.1000

How long does it usually take for someone to get round to updating the offsets in the ini file?  I might try later myself using the video..  https://www.youtube.com/watch?v=FiD86tmRBtk

This a zip file containing the dll.  For some reason I couldn't attach it with the zip extension.
[termsrv.txt](https://github.com/binarymaster/rdpwrap/files/91776/termsrv.txt)

**Comment by binarymaster** [comment]
@fig2k4 thanks for the 10.0.11082.1000 version

Can you upload the same DLL for x86 architecture?

**Comment by fig2k4** [comment]
Here you go. 
[termsrv.txt](https://github.com/binarymaster/rdpwrap/files/92341/termsrv.txt)

**Comment by binarymaster** [comment]
Version 10.0.11082.1000 has been added to support.

Run as administrator `RDPWInst -w` or `update.bat` to download latest INI file.

**Comment by fig2k4** [comment]
Nice, that works fine.  10.0.11082.1000 shows as fully supported and multiple connections are working at the same time.  Cheers for doing that so quickly.

**Comment by ChD1** [comment]
My don't work
[termsrv.txt](https://github.com/binarymaster/rdpwrap/files/92518/termsrv.txt)

**Comment by binarymaster** [comment]
@ChD1 your version 10.0.10240.16384 already added to support.

However, I don't know why it isn't working for you. Maybe something is missing in the system registry.

**Comment by sysilion** [comment]
need to support `ver 10.0.11102.1000`

here is termsrv.dll file [termsrv.zip](https://github.com/binarymaster/rdpwrap/files/101122/termsrv.zip)

**Comment by binarymaster** [comment]
@sysilion both x86 and x64 versions are required to add support.

**Comment by sysilion** [comment]
@binarymaster my termsrv.dll file is x64 binary :)

**Comment by binarymaster** [comment]
@sysilion I know, see my previous message.

**Comment by sysilion** [comment]
@binarymaster here is 32bit termsrv.dll
[termsrv.zip](https://github.com/binarymaster/rdpwrap/files/105025/termsrv.zip)

**Comment by binarymaster** [comment]
@sysilion Added support for `10.0.11102.1000` in https://github.com/binarymaster/rdpwrap/commit/103a687689866caa2cfca88c8560cf5ab839996e
Update your INI file.

**Comment by sysilion** [comment]
@binarymaster THX XD

**Comment by sysilion** [comment]
Windows 10 Home Insider preview build 14251
x86 [termsrv.zip](https://github.com/binarymaster/rdpwrap/files/108519/termsrv.zip)
x64 [termsrv.zip](https://github.com/binarymaster/rdpwrap/files/108521/termsrv.zip)
service state `ver 10.0.14251.1000`
update plz :)

**Comment by binarymaster** [comment]
@sysilion Added support for `10.0.14251.1000` in https://github.com/binarymaster/rdpwrap/commit/ff3df89647fa34e815ebc0150fd7181c5da1d33e
Probably the same version as `10.0.11102.1000`, offsets are identical.

**Comment by datmar78** [comment]
Windows 10 Build 14279 - not working... 

[termsrv.zip](https://github.com/binarymaster/rdpwrap/files/159759/termsrv.zip)

**Comment by zackp30** [comment]
Same as @datmar78, latest update killed rdpwrap. :(

**Comment by binarymaster** [comment]
@datmar78 @zackp30 
Build `10.0.14279.1000` has been added to support, run `update.bat`.

**Comment by CollinChaffin** [comment]
Build 14295 not supported and totally broke RDPwrap again.  How fast will it be updated?  Is there a guide could be put together to teach the community how to help update the ini params when this happens for faster fixes?

**Comment by CollinChaffin** [comment]
FYI looks like this is the byte string for build 14295 (note the 2 bytes changed from last build):

39 81 3C 06 00 00 0F 84 af ca 02 00

I have not yet tested to see if the prior string patch value is working but I am guessing it will not and will also need to be modified.

**Comment by binarymaster** [comment]
@CollinChaffin 
Added support for 10.0.14295.1000 in https://github.com/stascorp/rdpwrap/commit/6c58b69306def64c96a1fb2a7cb27b5e104d43ea

**Comment by ili101** [comment]
10.0.14316.1000
That didn't last long /:
Need fixing again
Thank you!

**Comment by binarymaster** [comment]
@ili101 
Added support for 10.0.14316.1000 in https://github.com/stascorp/rdpwrap/commit/37bcdd641410505476d9ebb3d9719f54ef91dd5c

**Comment by stephenbice** [comment]
>Same for me after a windows update. I notice that if I uninstall/reinstall, there is a message logged >saying:
>
>[*] Terminal Services version: 10.0.10586.0
>[-] This version of Terminal Services is not supported.
>Send your termserv.dll to project developer for support.
>o that is what I have done here: termsrv.zip

>I hope that gives enough information to add support for this version.v

Was support for this version ever added?

**Comment by avoidik** [comment]
I have termsrv.dll with version 10.0.10586.0. And it says not supported.
http://rghost.ru/private/7gnWTdGCB/9e08b0665df15fbb54fdb7f1f3488b8b

**Comment by binarymaster** [comment]
@avoidik read closed issues.

**Comment by binarymaster** [comment]
TODO: investigate build 14328.

**Comment by binarymaster** [comment]
@RobertSpir @dps85
Added support for builds `10.0.14300.1000` and `10.0.14328.1000` in https://github.com/stascorp/rdpwrap/commit/53897b40c7c6dda734f981039a25f347a3386e86

**Comment by hsbadr** [comment]
@binarymaster 
I have attached both x86 and x64 versions of termsrv.dll for build `10.0.14342.1000`.

[termsrv_10.0.14342.1000.zip](https://github.com/stascorp/rdpwrap/files/264558/termsrv_10.0.14342.1000.zip)

**Comment by binarymaster** [comment]
@hsbadr two versions in the archive are x64 and have identical content, reupload it.

**Comment by binarymaster** [comment]
@hsbadr 
Added support for build `10.0.14342.1000` in https://github.com/stascorp/rdpwrap/commit/bb6d905b8d7f216b9d77f7b924196a1f06db7ecc

**Comment by hsbadr** [comment]
@binarymaster 
Thank you!

**Comment by schmurtzm** [comment]
Hi, I've got a french version of Win 10 Family version 10.0.10586

Please find [my termsrv.dll here](https://DL.dropbox.com/s/f0vtv59bc0eu06y/termsrv.dll?dl=0)
Is it possible to make it compatible with this one ?

Thank you for this great software !

**Comment by binarymaster** [comment]
Closing the issue since its not updated anymore. Let users create new issues for each new version.
