### ISSUE TITLE
Ya listo para actualización de Mayo 1903 de windows que miedo. 

### ISSUE THREAD

**Issue by jonathan19091** [stascorp/rdpwrap#790]
Ya pronto todos tendrán la actualización de mayo para windows , 1903. 
voy actualizar para hacer pruebas quien mas se apunta?

**Comment by TheDanthes** [comment]
yo tengo la 1903 hasta el dia de hoy y lo tengo funcionando. pero me paso que en un equipo que tenia las actualizaciones detenidas ahora no me funciona la multisession solo un usuario a la vez.

**Comment by KevinH404** [comment]
Sorry to bother you @jonathan19091 but lets keep this channel for real issues. And I would advice you to write in english to have a more broad reach. Please dont take it the wrong way, Im a native spanish speaker too.

**Comment by sebaxakerhtc** [comment]
It's not clear. Not understandable
