### ISSUE TITLE
Can RDP wrapper break current remote desktop client setup?

### ISSUE THREAD

**Issue by SamHamels** [stascorp/rdpwrap#791]
My company has set up remote desktop for me, so I can access my powerful desktop PC from my laptop. This required some configuration by our IT department, which I didn't witness firsthand. I now regularly use the standard Windows Remote Desktop client to start a remote desktop session on my desktop.

I would like to test out RDP wrapper, because being able to open several sessions on my desktop at the same time would come in handy for my work.

Let's say I install RDP wrapper to test it out, and it turns out not to work for me (or I dislike it for another reason). Will simply uninstalling it restore my current situation (still being able to use the standard Windows Remote Desktop Client, as it is currently configured), or is is possible that testing out RDP wrapper messes up my current setup. It would suck to have to ask my IT department to redo their work setting up the Remote Desktop Client for my desktop PC, because I screwed it up by messing around with RDP wrapper.

**Comment by sebaxakerhtc** [comment]
No
