### ISSUE TITLE
W10 Version 10.0.18362.116 UPDATE (1903 May 2019)

### ISSUE THREAD

**Issue by CypherAus** [stascorp/rdpwrap#792]
Hi
Has anyone got a .ini file for the latest production release?

EDIT: See this https://github.com/stascorp/rdpwrap/issues/766

Thanks!

**Comment by asmtron** [comment]
support for 10.0.18362.116: #795

**Comment by CypherAus** [comment]
Not needed

**Comment by covid-19** [comment]
You can try this file .ini !

[rdpwrap2020.zip](https://github.com/stascorp/rdpwrap/files/4196281/rdpwrap2020.zip)

**Comment by covid-19** [comment]
or this file 🍡 
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/4196774/rdpwrap.zip)
