### ISSUE TITLE
Support for release 17763.529

### ISSUE THREAD

**Issue by erlake** [stascorp/rdpwrap#796]
support for release 17763.529
![winver2](https://user-images.githubusercontent.com/46791360/58363796-ae586400-7ecb-11e9-9ae7-299cee9b7613.PNG)

**Comment by huangsen365** [comment]
Same request here.

**Comment by MadDog927ca** [comment]
I assume you're new. You don't patch to match your Windows version - you patch to match the version of termsrv.dll. I am running the same version of Windows as you (17763.529), but my termsrv.dll version is 10.0.17763.437. You will find there is already a downloadable batch file that can automatically patch this particular termsrv.dll version in issue #795

**Comment by erlake** [comment]
thanks
