### ISSUE TITLE
Running install.bat removes installer messages too quickly for them to be read

### ISSUE THREAD

**Issue by ackalker** [stascorp/rdpwrap#80]
(Just as a convenience for users who use the batch file.)

When I click on `install.bat`, the messages from the installer flash by too quickly for me to read (among them there was an error about an unsupported version of terminal services), then get replaced by the "You can check RDP functionality with RDPCheck program." message.
I ether have to shoot a video using my phone or run the installer from a cmd prompt.

Perhaps use `start /wait` or `start /b` to run the installer from the batch file? (sorry, I haven't used Windows much recently.)

**Comment by binarymaster** [comment]
Try running `install.bat` by right clicking on it, and selecting "Run as Administrator".

This happens because elevated executable runs in different console window. Also you may try to disable UAC, but this isn't recommended.
