### ISSUE TITLE
need help!　All items under Diagnostics are green ,but it's not working.....

### ISSUE THREAD

**Issue by syou21** [stascorp/rdpwrap#800]
Where is the problem？
![2](https://user-images.githubusercontent.com/51103784/58461101-db29a700-8169-11e9-934c-0157aebe84a9.PNG)

**Comment by asmtron** [comment]
please try the new [rdpwrap_ini_updater_(07_June_2019).zip](https://github.com/stascorp/rdpwrap/issues/795#issue-448382061) with fixed **10.0.17763.437 x64**

**Comment by tayxmch** [comment]
> 
> 
> please try the new [rdpwrap_ini_updater_(07_June_2019).zip](https://github.com/stascorp/rdpwrap/issues/795#issue-448382061) with fixed **10.0.17763.437 x64**

same problem and tried the new ini_updater, but still doesn't work. my windows version is 10.0.17134.706

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/353
