### ISSUE TITLE
#724

### ISSUE THREAD

**Issue by dixitU** [stascorp/rdpwrap#808]
OS: Windows 10 Home (Version 1803, OS Build 17134.766)

RDP Wrapper 1.6.2

I got Listener state: Not listening in RDPConf.exe; and RDPCheck.exe told me Socket connection failed.i didn't found security update KB4493646 in update history.so how am i resolve it?

**Comment by s0nic9** [comment]
no problems here with updates of @fre4kyC0de

**Comment by sebaxakerhtc** [comment]
Closed as not actual
