### ISSUE TITLE
Не работает поддержка 10.0.17763.592

### ISSUE THREAD

**Issue by ZeLLinsKi** [stascorp/rdpwrap#817]
Здравствуйте!!! Не работает поддержка 10.0.17763.592(Постоянно было not supported, скопировал в system32 dll от версии 10.0.17763.1 стало fully supported, но listener state Not listening). Скажите пожалуйста как настроить чтобы работало, запутался уже весь.
![рдп врап](https://user-images.githubusercontent.com/52062669/59902086-b3e79200-9416-11e9-927f-bdc7d3ca834f.png)
![рдпврап2](https://user-images.githubusercontent.com/52062669/59902089-b5b15580-9416-11e9-829c-831f98ab88a8.png)

**Comment by PCMacDr** [comment]
Next time use google translate and paste it here in english

**Comment by ghost** [comment]
I meet the same issue. Who could give us the new rdpwrap.ini

**Comment by ghost** [comment]
http://www.lotpc.com/dngz/8180.html   .Here has what U want.
