### ISSUE TITLE
windows 8.1 services 10.0.17763.292

### ISSUE THREAD

**Issue by netriderone** [stascorp/rdpwrap#819]
hi guys,
is there a solution to run rdpwrap on windows 8.1 pro, everything is green but not working
thanks

![Captură](https://user-images.githubusercontent.com/52084158/59944380-4d419300-946d-11e9-8dae-6d8a45660349.PNG)

**Comment by netriderone** [comment]
nothing :(

**Comment by s0nic9** [comment]
windows 8.1 version is 6.3.9600.19395 july 2019 updates, dll keep at 19318 version and it's supported by updates of @fre4kyC0de
10.0.17763 is version of windows 10 v1809 and it's supported by updates of @asmtron
