### ISSUE TITLE
Constantly failing sign in

### ISSUE THREAD

**Issue by ITCMD** [stascorp/rdpwrap#821]
I'm constantly getting the error: "The Local Session Manager Failed to Sign In: The Connections to this computer are limited and all connections are in use." When I try and sign in. Usually I can SSH into the computer and restart the RDP service, and it will let me sign in, but sometimes the only solution is to unplug the ethernet cord and restart four or five times until it finally lets me sign in. This solution usually works for about half a day before I have to restart the RDP service every time, and then every week or so I have to go through that whole process. I'm running Windows 10 Home on an Optiplex 780.

Note: I've checked again and again and no other devices are connected to the computer. Even if it's a direct wired connection from one computer to another it still happens.

**Comment by sebaxakerhtc** [comment]
No version, no rdpconf screenshot. It's not clear which version
