### ISSUE TITLE
Win 10 Enterprise 2015 (LTSB) 10.0.10240.18186 not supported

### ISSUE THREAD

**Issue by wilsonfoz** [stascorp/rdpwrap#826]
The #732 solution is not working for this version. 
![image](https://user-images.githubusercontent.com/427992/60434273-286fbd00-9bdd-11e9-8e7d-3b7f8bf01b86.png)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/3345389/termsrv.zip)

**Comment by amirhosseinzare** [comment]
any idea how to make it work again??

**Comment by s0nic9** [comment]
don't forget to add a blank line at the end of the ini file. Tested here with july 2019 update, it works.

**Comment by wilsonfoz** [comment]
Yes, it's working! A blank line changes everything! Sorry about my mistake. Thank you very much @s0nic9 .
