### ISSUE TITLE
Sessions Limite 15 - Window 10 x64 1903

### ISSUE THREAD

**Issue by DarKWinGTM** [stascorp/rdpwrap#833]
Sessions Limite 15 - Window 10 x64 1903

My remote desktop patched with full support, But i found some issue remote desktop have connection limite 15 connection.

- Already config in "gpedit.msc"
- Already config in registery "MaxInstanceCount"

**Comment by songlim327** [comment]
Hi,  i faced the same issue with Windows 10 x64 1903, do you found a solution for it?

**Comment by DarKWinGTM** [comment]
No.

**Comment by DarKWinGTM** [comment]
I found Solution for this issue, So am not sure it's bug in 1903 or not but you can startup all remote desktop as select all *.rdp file then press enter to open and connect all remote desktop in one enter action, This trick will bypass limite connection in 1903.

**Comment by DarKWinGTM** [comment]
I found Solution for this issue, So am not sure it's bug in 1903 or not, You can startup all remote desktop by select all *.rdp file then press enter to open all connect remote desktop in one action with enter, This trick will bypass limite connection in 1903.

**Comment by chocolait** [comment]
could you clarify?

**Comment by mrselek** [comment]
My Sessions Limite is 5. How can I more? without *,rdp file!

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/512
