### ISSUE TITLE
Windows 10 1903

### ISSUE THREAD

**Issue by Hagrid78** [stascorp/rdpwrap#844]
This is kind of a dumb question but does rdpwrap work on systems thats on a domain controller?

**Comment by nirari** [comment]
try https://github.com/stascorp/rdpwrap/issues/837

**Comment by PCMacDr** [comment]
> This is kind of a dumb question but does rdpwrap work on systems thats on a domain controller?

If you mean, behind a domain, then Yes
Within DC in Virtual, via, lets say Hyper-V, then Yes
