### ISSUE TITLE
[Solved] Offsets For 18362.267

### ISSUE THREAD

**Issue by Kyrluckechuck** [stascorp/rdpwrap#845]
Hello!

Has anyone had any luck decompiling the latest update / finding the offsets for rdpwrap? 

It would appear that the `18362.53` offsets (https://github.com/stascorp/rdpwrap/issues/837) worked up until `18362.254`, but with the latest update it results in a 1067 error code when starting up the term service. 😟

P.S. Has anyone thought up a way for these updates to somehow come from a dynamic server so that you aren't completely locked out of the computer until you're able to get physical access again / terminal access in order to update the offsets by hand?

**Comment by mytharch** [comment]
Hello,

after updating windows 10 getting this error 
![rdp](https://user-images.githubusercontent.com/53371545/61994580-dc0f8400-b099-11e9-8aa5-99dcbe598280.png)

please help into this

**Comment by jonathan19091** [comment]
Buen día con gusto les ayudo, solo por favor implementen o ayuden a la comunidad aportando cambio cuando se requiera modificar código vale. 

abran su archivo rdpwrap.ini de la ruta C:\Program Files\RDP Wrapper
ir hasta el final 
dar tabulador o agregar un renglón y pegar los sig:
ya lo probé en muchos equipos y si funciona sin problemas , apagar y reiniciar y aun así estable 
claro solo 64 bits

[10.0.18362.267]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FB5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.267-SLInit]
bInitialized.x64      =F6A8C
bServerSku.x64        =F6A90
lMaxUserSessions.x64  =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64  =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64       =F6AAC

**Comment by Kyrluckechuck** [comment]
Hmm, unfortunately the options you posted do not work for me, so I must be using a setting that you are not here (where the offset is incorrect, but it does not affect you because you are not using the setting), or some other weird scenario...

**Comment by thanh2uan** [comment]
> Hmm, unfortunately the options you posted do not work for me, so I must be using a setting that you are not here (where the offset is incorrect, but it does not affect you because you are not using the setting), or some other weird scenario...

You have fixed the problem yet? Please attach your rdpwrap.ini file

**Comment by SlavaSumyUA** [comment]
stop the service running CMD as administrator
net stop termservice
	Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
net start termservice
	Reboot your PC
[rdpwrap_10.0.18362.267_x64.zip](https://github.com/stascorp/rdpwrap/files/3439498/rdpwrap_10.0.18362.267_x64.zip)

**Comment by Kyrluckechuck** [comment]
Odd, I believe the offsets you included in your file @SlavaSumyUA were the same as above, however, they seemed to work this time. Exact same procedure, so now I'm quite confused. 

In that case though I'll agree that these are the current offsets for `18362.267`!

**Comment by s0nic9** [comment]
@Kyrluckechuck You had probably forgotten the mandatory last blank line in the .ini

**Comment by Kyrluckechuck** [comment]
@s0nic9 
Heh.. You're 100% correct. This will get me every time 🤦‍♂️

**Comment by Sp0oner** [comment]
I have tried this and replaced the ini file and rebooted etc but it's still not working listener state still not listening. Everything else is green.

**Comment by trilomix** [comment]
Check for the last return in the .ini file to be added. this fix work for me with the same status as you.
Snapshot with Win HOME 1903 (18362.535)
![image](https://user-images.githubusercontent.com/895120/72811522-1f6d3880-3c60-11ea-95ec-fd77be96a55e.png)
