### ISSUE TITLE
Windows 10 version 10.0.18362.267 not supported

### ISSUE THREAD

**Issue by romanad** [stascorp/rdpwrap#848]

**Comment by SlavaSumyUA** [comment]
stop the service running CMD as administrator
net stop termservice
	Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
net start termservice
	Reboot your PC
[rdpwrap_10.0.18362.267_x64.zip](https://github.com/stascorp/rdpwrap/files/3439496/rdpwrap_10.0.18362.267_x64.zip)

**Comment by graphixillusion** [comment]
@SlavaSumyUA thank you, it works good. Do you know if it's possible to resume an already open rdp session?

**Comment by yotoprules** [comment]
the 239 version wasn't working, I updated to 18362.267 and copied your rdpwrap.ini, everything is green but it still locks me when I try to connect using RDP. RDP Check always says "Access Denied"

![trtrrrrrrrr](https://user-images.githubusercontent.com/39581623/62013062-bc558a00-b185-11e9-8024-5bc0760a3f0d.PNG)

**Comment by alexlovar** [comment]
> the 239 version wasn't working, I updated to 18362.267 and copied your rdpwrap.ini, everything is green but it still locks me when I try to connect using RDP. RDP Check always says "Access Denied"
> 
> ![trtrrrrrrrr](https://user-images.githubusercontent.com/39581623/62013062-bc558a00-b185-11e9-8024-5bc0760a3f0d.PNG)

the account that you are using to rdp access must have administrator rights

**Comment by yotoprules** [comment]
it does have admin rights. it gives me this error every time. and when I rdp into the machine it locks the screen. If I uncheck single session per user, that works. it just doesn't work with it in single session per user.

**Comment by graphixillusion** [comment]
@yotoprules try with gui or default auth only. network level auth doesn't work

**Comment by yotoprules** [comment]
I already tried that and it still locks me out as the other user connects through RDP.

**Comment by graphixillusion** [comment]
> I already tried that and it still locks me out as the other user connects through RDP.

So unistall everything and retry from scratch. On my system it works good.

**Comment by yotoprules** [comment]
I've tried that when updating the ink file. Maybe I'll upload a video and show what happens when I get to my pc.

**Comment by yotoprules** [comment]
> > I already tried that and it still locks me out as the other user connects through RDP.
> 
> So unistall everything and retry from scratch. On my system it works good.

https://youtu.be/ZsxAfKqYStQ

**Comment by graphixillusion** [comment]
@yotoprules try this:

1) net stop termservice
2) unistall rdpwrap
3) reboot pc
4) install rdpwrap
6) add this in the ini with notepad++

```
[10.0.18362.267]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FB5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.267-SLInit]
bInitialized.x64 =F6A8C
bServerSku.x64 =F6A90
lMaxUserSessions.x64 =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64 =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64 =F6AAC
```

7) Save and exit (as administrator)
8) net stop termservice
9) net start termservice
10) in the option set default rdp or gui auth only

and try again.

**Comment by jagbarcelo** [comment]
What about 32 bit (x86) offsets for termsrv.dll version 10.0.18362.267 ? Any progress yet?

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/3445933/termsrv.zip)

**Comment by toddmaddison** [comment]
Not working for me either...  This is about the 20th time I've had to refresh the concurrent RDP wrapper or termsrv.dll so I'm not new to it, but I can't get it to work this time around...

I'm on Win 10 V 1903 build 18262.267, which means termsrv.dll 10.0.18362.267. 

I've tried the "replace the RDP Wrapper file" with the one linked above by SlavaSumyUA, no luck.

Tried modifying my existing rdpwrapper.ini with the code in graphixillusion  comment, no luck.

Have, of course, done a complete reboot after each attempt...

Holding on additional solutions, hopefully they're out there!

**Comment by MarcinWerra** [comment]
> What about 32 bit (x86) offsets for termsrv.dll version 10.0.18362.267 ? Any progress yet?
```
[10.0.18362.267]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FB5
LocalOnlyCode.x64=jmpshort
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B7D06
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
SingleUserPatch.x86=1
SingleUserOffset.x86=50535
SingleUserCode.x86=nop
DefPolicyPatch.x64 =1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
DefPolicyPatch.x86 =1
DefPolicyOffset.x86=50269
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize
SLInitHook.x86=1
SLInitOffset.x86=5A77A
SLInitFunc.x86=New_CSLQuery_Initialize

[10.0.18362.267-SLInit]
bInitialized.x64      =F6A8C
bServerSku.x64        =F6A90
lMaxUserSessions.x64  =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64  =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64       =F6AAC
bInitialized.x86      =D577C
bServerSku.x86        =D5780
lMaxUserSessions.x86  =D5784
bAppServerAllowed.x86 =D578C
bRemoteConnAllowed.x86=D5790
bMultimonAllowed.x86  =D5794
ulMaxDebugSessions.x86=D5798
bFUSEnabled.x86       =D579C
```

**Comment by graphixillusion** [comment]
@toddmaddison are you using Win 10 Pro? This is very strange, i tried it on two different machines and it works perfect on both sides.

**Comment by toddmaddison** [comment]
Yes, sorry I didn't mention that.  I've been on Pro for probably at least 3-4 years, have updated termsrv multiple times in that period, it has always worked before...

Any suggestions on logs or anything I can look at to see what's failing?

**Comment by graphixillusion** [comment]
this is the ini i'm using. try with this file.
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/3448151/rdpwrap.zip)

**Comment by StarfighterJ** [comment]
Thanks SlavaSumyUA that worked great

**Comment by romanad** [comment]
Hi everyone, please confirm that network level auth does work. Without it this solution is insecure.

**Comment by toddmaddison** [comment]
> this is the ini i'm using. try with this file.
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/3448151/rdpwrap.zip)

Gosh darn it, tried your new file, rebooted, etc, etc - no luck...   Still limited to a single login on the machine...  Thanks for the help, though!

**Comment by graphixillusion** [comment]
> Hi everyone, please confirm that network level auth does work. Without it this solution is insecure.

NLA doesn't work. If you need this to remotely connect to your machine using RDP protocol, never expose the port to the internet. Use a private VPN or a secure ssh tunnel with it with a super strong public/private key auth.

**Comment by romanad** [comment]
> > Hi everyone, please confirm that network level auth does work. Without it this solution is insecure.
> 
> NLA doesn't work. If you need this to remotely connect to your machine using RDP protocol, never expose the port to the internet. Use a private VPN or a secure ssh tunnel with it with a super strong public/private key auth.

It's very bad that NLA doesn't work, it worked flawlessly on version 10.0.18362.53.
It's useless without NLA because there are a lot of cases when you can't use clumsy VPN, for example if you work with terminal internet (web browser shared by terminal server), sometimes all you have is web browser and all you can use is HTML5 RDP.
NLA + Strong pass + IDS/IPS = secure enough

**Comment by graphixillusion** [comment]
@romanad 
Actually if you choose NLA in the config and then check it, you can connect but after you close and reopen the config, that option is auto reverted to GUI auth only. By the way which programs do you use for IDS/IPS? Any good FOSS alternative?

**Comment by Dyna-007** [comment]
hey i go it work with nla i just use a (termsrv.dll) from 18362.239
and use the same rdpwrap.ini working before with i place the archive if anyone want to try or use your
place termsrv.dll in C:\Windows\System32  (know how to edit perm and stop rdp service)
place rdpwrap.ini in C:\Program Files\RDP Wrapper (stop termservice)
after reboot will work like before
remenber to backup our termsrv.dll
[rdpwrap+termsrv.zip](https://github.com/stascorp/rdpwrap/files/3454333/rdpwrap%2Btermsrv.zip)

**Comment by jaydacanay** [comment]
Thanks, 

> ```
> stop the service running CMD as administrator
> ```
> 
> net stop termservice
> Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
> net start termservice
> Reboot your PC
> [rdpwrap_10.0.18362.267_x64.zip](https://github.com/stascorp/rdpwrap/files/3439496/rdpwrap_10.0.18362.267_x64.zip)

Thanks!!

**Comment by romanad** [comment]
> @romanad
> Actually if you choose NLA in the config and then check it, you can connect but after you close and reopen the config, that option is auto reverted to GUI auth only. By the way which programs do you use for IDS/IPS? Any good FOSS alternative?

Symantec Endpoint Protection has nice IPS service for Windows that prevents common attacks including RDP brute-force.

**Comment by romanad** [comment]
Has anyone tested solution from Dyna-007 - does it work for everyone?

**Comment by asmtron** [comment]
add support for 267 to https://github.com/stascorp/rdpwrap/pull/816 (pull request) and https://github.com/stascorp/rdpwrap/issues/795 (rdpwrap_ini_updater)

the new termsrv.dll 10.0.18362.267 disassembled and tested successfully on Win10 Pro x64

**Comment by graphixillusion** [comment]
@asmtron Thank you very much for your effort. NLA auth still doesn't work though.  And what about to resume an already opened session? Right now it will always open a new one.

**Comment by S474N** [comment]
> ```
> stop the service running CMD as administrator
> ```
> 
> net stop termservice
> Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
> net start termservice
> Reboot your PC
> [rdpwrap_10.0.18362.267_x64.zip](https://github.com/stascorp/rdpwrap/files/3439496/rdpwrap_10.0.18362.267_x64.zip)

Excellent, works perfectly!

**Comment by romanad** [comment]
Hello guys!
Please inform us if there fully workable fix available with NLA and open session resuming?

**Comment by romanad** [comment]
I confirm it works well, thank you very much guys.

**Comment by graphixillusion** [comment]
@romanad you got nla and open session resume working too?

**Comment by romanad** [comment]
Yes all works fine, no issues at all.
But of course till new windows update.

**Comment by graphixillusion** [comment]
@romanad what did you do for make them work? On my system if i choose NLA, it always revert back to GUI auth only after the first connect. And i can't have open session resuming becouse it always starts a new session.

**Comment by romanad** [comment]
I just replaced ini file in program files and restarted RDP service according to the instruction. 
I suppose that in RDP wrapped config you should check single session per user.

**Comment by graphixillusion** [comment]
@romanad No, if you check single session per user in the config, the concurrent logins will stop working. I mean, i would like to restore the old behaviour like the system should prompt a window which offers you the option to resume the already opened session or start a new one.

**Comment by romanad** [comment]
https://i.imgur.com/fjdvjwc.png
It's my config

**Comment by graphixillusion** [comment]
Using the RDPCheck.exe or the default mstsc.exe, the NLA auth doesn't work: as i said it reverts back to GUI Auth only after the first connect. I just tried with another rdp client, freerdp for windows and with it NLA works as it should. Just want to report. Now i just need to find a way to resume an already opened concurrent session.

**Comment by romanad** [comment]
> Using the RDPCheck.exe or the default mstsc.exe, the NLA auth doesn't work: as i said it reverts back to GUI Auth only after the first connect. I just tried with another rdp client, freerdp for windows and with it NLA works as it should. Just want to report. Now i just need to find a way to resume an already opened concurrent session.

Sorry to hear that friend. I have no issues at all. I suggest to install your clean version of windows to new VM a test if the issue appears. I tested on Windows x64 Enterprise En.

**Comment by graphixillusion** [comment]
@romanad i already tried several times but i always get the same behaviour. Talking about the sessionID, i have tried to connect to the console with this command:

mstsc /admin /v:ipaddress 

but nothing: it doesn't connect to the default console but it opens a new session. During my tests, i observed one thing: when you conect using rdp, the query session shows rdp-tcp#xx in the list. When you disconnect, that value will becomes CONSOLE with a sessionID number which is progressively increase by one each new try. I don't know if it's related. In the meantime we can use tscon switch as a workaround.

**Comment by romanad** [comment]
> @romanad i already tried several times but i always get the same behaviour. Talking about the sessionID, i have tried to connect to the console with this command:
> 
> mstsc /admin /v:ipaddress
> 
> but nothing: it doesn't connect to the default console but it opens a new session. During my tests, i observed one thing: when you conect using rdp, the query session shows rdp-tcp#xx in the list. When you disconnect, that value will becomes CONSOLE with a sessionID number which is progressively increase by one each new try. I don't know if it's related. In the meantime we can use tscon switch as a workaround.

I don't know what's wrong with your configuration, but that same command works fine for me.

**Comment by graphixillusion** [comment]
Well, who knows. This is the dafult behaviour on two different machines, clean install, Win10 Pro

**Comment by fglez-tsl** [comment]
Hi,

Latest rdpwrap.ini in this thread is not working for me on 

Windows 10 Home 
1903
18362.267
64-bit

![rdpwrap](https://user-images.githubusercontent.com/1586803/62841000-f4d78680-bca2-11e9-8f83-ef5986ebb20b.png)

Does anyone have it working with this same configuration? 

Thank you.

**Comment by fglez-tsl** [comment]
Got it working after removing everything and starting from scratch.

**Comment by ryangriggs** [comment]
I am trying to get RDPWrap to run on Windows 10 Pro 10.0.18362.267.
I have copied the new INI sections to the file, but afterward when attempting to restart termservice, I get the following error:
"A system error has occurred." "System error 1067 has occurred."  "The process terminated unexpectedly."

RDPConf shows [fully supported]:
![image](https://user-images.githubusercontent.com/5854489/63206319-45265e00-c080-11e9-801d-07b0e399b7a1.png)

Thanks for any additional guidance.

**Comment by jvalencia167** [comment]
> ```
> stop the service running CMD as administrator
> ```
> 
> net stop termservice
> Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
> net start termservice
> Reboot your PC
> [rdpwrap_10.0.18362.267_x64.zip](https://github.com/stascorp/rdpwrap/files/3439496/rdpwrap_10.0.18362.267_x64.zip)

Muchas gracias hermano uff me sirvio  mucho

**Comment by TGeRi** [comment]
THANKS YOU so much for everyone who is involved in the ini-updates above!!!

**Comment by alexvulpe** [comment]
> Latest rdpwrap.ini in this thread is not working for me on
> 
> Windows 10 Home
> 1903
> 18362.267
> 64-bit
> 
> ![rdpwrap](https://user-images.githubusercontent.com/1586803/62841000-f4d78680-bca2-11e9-8f83-ef5986ebb20b.png)
> 
> Does anyone have it working with this same configuration?

I had this situation.
All changes to rdpwrap.ini shall be done in c:\Program Files\RDP Wrapper\rdpwrap.ini.
The one from install folder (where install.bat is located) is for reference only, it does not have effect (at least for me).
As soon as I updated the c:\Program Files\RDP Wrapper\rdpwrap.ini. file - it worked perfectly.
Thanks a lot!

**Comment by s0nic9** [comment]
try updates from others like https://github.com/stascorp/rdpwrap/issues/860

**Comment by raphaelmachado** [comment]
> ```
> stop the service running CMD as administrator
> ```
> 
> net stop termservice
> Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
> net start termservice
> Reboot your PC
> [rdpwrap_10.0.18362.267_x64.zip](https://github.com/stascorp/rdpwrap/files/3439496/rdpwrap_10.0.18362.267_x64.zip)

Yes! It Worked!!! Thanks (-_-*)

**Comment by riosan** [comment]
In order for everything to work, it is necessary to replace termsrv.dll x64
[termsrv_64.zip](https://github.com/stascorp/rdpwrap/files/3869191/termsrv_64.zip)

**Comment by healinsmile** [comment]
Thanks it worked
