### ISSUE TITLE
New Release v1.7 with updates and fixes?

### ISSUE THREAD

**Issue by appetiteoven** [stascorp/rdpwrap#85]
Hi-

Will you be releasing a compiled version that includes recent fixes and updates?

The latest on this page is for v1.6 which doesn't work on the latest Windows. 
https://github.com/binarymaster/rdpwrap/releases

I tried compiling but I have VS2015 and was running into compatibility issues.

Thanks for your great work !

**Comment by LittleVulpix** [comment]
@appetiteoven For the time being, you can install v1.6 and then run the update.bat.

It'll say something like:

RDP Wrapper Library v1.6
Installer v2.3
Copyright (C) Stas'M Corp. 2015

[*] Checking for updates...
[*] Current update date: 2015.07.30
[*] Latest update date:  2016.01.15
[+] New update is available, updating...
[+] TermService found (pid 4732).
[*] Shared services found: CryptSvc, Dnscache, LanmanWorkstation, NlaSvc
[*] Terminating service...
[*] Starting CryptSvc...
[*] Starting Dnscache...
[*] Starting LanmanWorkstation...
[*] Starting NlaSvc...
[*] Starting TermService...
[+] Update completed.

Press any key to continue . . .


And then it'll work again! Yay!

**Comment by lionel126** [comment]
[] Latest update date: 2016.01.15

**Comment by wjhendr** [comment]
i'm trying to do this update to an offline windows 10 home machine and it cannot download the latest INI file from github, obviously.  Before I attach a sniffer to the LAN, can you give me an easier solution?

**Comment by binarymaster** [comment]
@wjhendr Just download INI file manually and copy it to the destination machine into RDP Wrapper's folder.

**Comment by wjhendr** [comment]
ty...what is the latest INI file URL?

**Comment by wjhendr** [comment]
is it: https://raw.githubusercontent.com/stascorp/rdpwrap/master/res/rdpwrap.ini

**Comment by binarymaster** [comment]
Yes.

**Comment by wjhendr** [comment]
thanks.

just tried, still says same error.

here's what's in my local win 10 home rdpwrap folder:

dir c:\Users\user\Downloads\RDPWrap-v1.6\
install.bat
RDPCheck.exe
RDPConf.exe
RDPWInst.exe
rdpwrap.ini
uninstall.bat
update.bat

The command output (run as administrator) is:
[*] Checking for udpates...
[*] Current update date: 2015.07.30
[-] Failed to download latest INI from GitHub.

**Comment by binarymaster** [comment]
You need to place INI file in the RDP Wrapper's folder, by default it's located at:
`C:\Program Files\RDP Wrapper\`

**Comment by wjhendr** [comment]
okay, did that (had to stop a bunch of services b/c the file was "in use". 

tried the update.bat again and still exact same error.

**Comment by binarymaster** [comment]
Since you updated INI file, you don't need to run `update.bat`, just restart terminal services (or reboot).

**Comment by wjhendr** [comment]
how do i restart terminal services?  I see no service by that name in services.msc (or in a "sc query type= all")

**Comment by binarymaster** [comment]
`net stop TermService`
`net start TermService`

**Comment by wjhendr** [comment]
okay, did that.  it stopped and started successfully.  but i still cannot connect from a remote pc (win 10 pc).

i notice that the RDP Wrapper Configuration tool reports Listener state as **Not listening**.

**Comment by wjhendr** [comment]
FYI, in desperation, I tried to edit **termsrv.dll** according to these instructions:

[http://www.mysysadmintips.com/windows/clients/545-multiple-rdp-remote-desktop-sessions-in-windows-10](url)

e.g.:

> in termsrv.dll search for:
> 39 81 3C 06 00 00 0F 84 73 42 02 00
> replace by:
> B8 00 01 00 00 89 81 38 06 00 00 90
> 

I restarted `termservice`, and still no luck.  The `netstat -na|findstr 3389` command shows that the port is not listening.

The RDP Wrapper Config tool still says:

    Wrapper state:  Installed         ver. 1.5.0.0
    Service state:  Running           ver. 10.0.10586.0
    Listener state: Not listening     [fully supported]

**Comment by ranger01** [comment]
Any chance that a version will be coming that will work with Windows 10 Enterprise version 1511 (build no. 10586.420),
won't work since I upgraded.

**Comment by binarymaster** [comment]
@ranger01 run `update.bat`

**Comment by ranger01** [comment]
Genius! Thanks!

**Comment by binarymaster** [comment]
[v1.6.1](https://github.com/stascorp/rdpwrap/releases/tag/v1.6.1) released.

**Comment by mastersatboy** [comment]
From today mybe after some windows update doesnt work any more.It says not supported in windows 10.Any solution??,thnx!

**Comment by johnsoaf** [comment]
I have encountered a similar issue.  Windows 10 Home.  Worked flawlessly for months.
![rdpwrap](https://cloud.githubusercontent.com/assets/22202128/18524795/f8835332-7a87-11e6-829e-b1eaaa5b838f.jpg)

**Comment by kadzsol** [comment]
Same problem here with w10 home. Noticed today, yesterday installed the latest patches...

**Comment by binarymaster** [comment]
@johnsoaf @kadzsol added support for this version just a minutes ago.

Run `update.bat` from release package.

**Comment by kadzsol** [comment]
did so, listener is now up and state is supported/green. Unfortunately, still cannot connect. I am using a non standard (3390) port. Could that be the reason?

**Comment by kadzsol** [comment]
some logs

>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFCE9F90000
SvcMain:    termsrv.dll+0x000000000000D010
SvcGlobals: termsrv.dll+0x00000000000346C0
Version:    10.0.10586.589
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFCEA0823B8] bServerSku = 1
SLInit [0x00007FFCEA083470] bRemoteConnAllowed = 1
SLInit [0x00007FFCEA083460] bFUSEnabled = 1
SLInit [0x00007FFCEA0823B4] bAppServerAllowed = 1
SLInit [0x00007FFCEA083468] bMultimonAllowed = 1
SLInit [0x00007FFCEA0823B0] lMaxUserSessions = 0
SLInit [0x00007FFCEA08346C] ulMaxDebugSessions = 0
SLInit [0x00007FFCEA083464] bInitialized = 1
<<< CSLQuery::Initialize
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFEF22E0000
SvcMain:    termsrv.dll+0x000000000000D010
SvcGlobals: termsrv.dll+0x00000000000346C0
Version:    10.0.10586.589
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFEF23D23B8] bServerSku = 1
SLInit [0x00007FFEF23D3470] bRemoteConnAllowed = 1
SLInit [0x00007FFEF23D3460] bFUSEnabled = 1
SLInit [0x00007FFEF23D23B4] bAppServerAllowed = 1
SLInit [0x00007FFEF23D3468] bMultimonAllowed = 1
SLInit [0x00007FFEF23D23B0] lMaxUserSessions = 0
SLInit [0x00007FFEF23D346C] ulMaxDebugSessions = 0
SLInit [0x00007FFEF23D3464] bInitialized = 1
<<< CSLQuery::Initialize

**Comment by binarymaster** [comment]
@kadzsol use command `netstat -a -n -b` to see which port is actually being listened by TermService.

**Comment by kadzsol** [comment]
[System]
  TCP    0.0.0.0:3390           0.0.0.0:0              LISTENING
  TermService

**Comment by johnsoaf** [comment]
Running update.bat from release package fixed the issue.  Not sure if changes were made because it wasn't working this afternoon but is working now.  Thank you @binarymaster!

**Comment by binarymaster** [comment]
@kadzsol which way you're trying to connect? Loopback (127.0.0.x), local network, or over the Internet?

**Comment by kadzsol** [comment]
rdpcheck.exe does connect (from the same machine/local). From a remote machine (LAN & internet) it still does not work. I switched off the firewall and now I can connect. So something wrong there, which is strange as I did not changed anything except updating the wrapper.

**Comment by vxbush** [comment]
Is this Windows 10? Chiming in here—for a lot of really weird reasons, Windows 10 will turn on the firewall automatically and not notify you. Things like changing the fonts on the computer. Yes, really.

Relevant link:
http://superuser.com/questions/957907/unable-to-install-fonts-on-windows-10

This particular issue hit me a few weeks ago. Just FYI in case it helps.



--


On Sep 15, 2016, at 11:47 AM, kadzsol <notifications@github.com<mailto:notifications@github.com>> wrote:


rdpcheck.exe does connect (from the same machine/local). From a remote machine (LAN & internet) it still does not work. I switched off the firewall and now I can connect. So something wrong there, which is strange as I did not changed anything except updating the wrapper.

**Comment by kadzsol** [comment]
Yes, W10 Home. I will investigate further and let you know.

**Comment by kadzsol** [comment]
Issue solved. port 3390 was not open any more. I had to add it again and now everything works just before installing the latest patches. Thanks for the fast fix!

http://www.tomshardware.co.uk/faq/id-3114787/open-firewall-ports-windows.html

**Comment by bigdnf** [comment]
I have Windows 10 build 14971 and app app is saying that this version is not supported. I have tried to update but this update only do some prev build so I have modified ini manually to fit my build and restart windows but I have still info [not supported]. Is there anything I can do?

**Comment by binarymaster** [comment]
@bigdnf sorry I don't have enough time to add support for new builds.

There is also one pending issue #181 about build 14959.

**Comment by bigdnf** [comment]
I understand - if you can say what to change in source to align with current build I can help with this. I'm c# dev so I should figure it out ;)

**Comment by binarymaster** [comment]
Ok, see these two commits for reference, what needed to change:
- https://github.com/stascorp/rdpwrap/commit/0175a08fd1ed7a42ce46ae32bd783b6e3303f356
- https://github.com/stascorp/rdpwrap/commit/47830889eb13e4e3ba5130906353685a34ed8326

And see section **Tutorial videos** in `README.md` to know how to obtain new offset values.

**Comment by bigdnf** [comment]
Unfortunately I failed :) As far as I can see in commits the only file I have to change is (C:\Program Files\RDP Wrapper\rdpwrap.ini – I have simply changed 10.0.14955.1000 to 10.0.14971.1000) – the rest of files are txt and md so I think they are irrelevant? After that I have restarted windows but it still says that is not supported. The other thing hat bothers me that I have release 1.6.1 but when running wrapper configuration it shows ver. 1.5.0.0?

**Comment by binarymaster** [comment]
> As far as I can see in commits the only file I have to change is (C:\Program Files\RDP Wrapper\rdpwrap.ini – I have simply changed 10.0.14955.1000 to 10.0.14971.1000)

I think this will not work. You need to create a new section and obtain new values (btw there is more than one section, see *-SLInit), values are different between builds.

> The other thing hat bothers me that I have release 1.6.1 but when running wrapper configuration it shows ver. 1.5.0.0?

See `README.md`:

> Config Tool reports version 1.5, but I installed higher version.

**Comment by bigdnf** [comment]
Sorry I missed that you pointed me video tutorial :) I have a question about it – in video you are using IDA but I have insider build of Windows and IDA cant find PDB for termsrv.dll? Dou you have a workaround for this?

**Comment by binarymaster** [comment]
I also experiencing issue with PDB, but it isn't big problem for me. I just searching for similar ASM sequences.

BTW I already added signatures to INI file for last builds yesterday. https://github.com/stascorp/rdpwrap/commit/3cb1ed5944d0d223db58468f797f62ceeac39c56 :wink:

**Comment by bigdnf** [comment]
tnx :) You're the man!

**Comment by luisvaldez** [comment]
I'm having the same issue on 1.6.1.
![image](https://user-images.githubusercontent.com/567319/27042332-8109eb5e-4f8e-11e7-83e3-3b67faf3870b.png)
Any ideas?

**Comment by binarymaster** [comment]
@luisvaldez there are still no ideas, but your issue is #194.

**Comment by Wajahat234** [comment]
![not supported](https://user-images.githubusercontent.com/30357439/28483966-4bddf820-6e89-11e7-87ed-c3dbc515d95a.GIF)

i m using windows server 2012 r2  getting this message from last 2 days when i updated my windows server tel me how i can slove this issue !.

**Comment by binarymaster** [comment]
@Wajahat234 your issue is probably #285 about KB4025335 update.

**Comment by Wajahat234** [comment]
Thx
