### ISSUE TITLE
Only one session allowed

### ISSUE THREAD

**Issue by rendgeor** [stascorp/rdpwrap#852]
Hello,
installing and running on with status green and fully supported.

Unfortunately still second session blocked by RDP limitations.

What could be the problem?
Do I need manually start more than one RDP service?

**Comment by magarjoba** [comment]
I have a problem of the same nature.
What I just did not do, but the problem with the simultaneous login of the same user has not been solved.
Those. c RDP does not throw out when connecting different users., but when trying, for example:
from different machines, log in at the same time from the same name ...
!!!

In group policies, users are ideally tuned, here it’s more to the practical part, maybe we are doing something in the wrong order ...
Tell me.
**ver. 10.0.17763.437**

**Comment by s0nic9** [comment]
don't forget the mandatory blank line at the end of the ini

**Comment by sebaxakerhtc** [comment]
User must be a member of rdp group
If it is the same user - uncheck Single Session per User
