### ISSUE TITLE
dwm.exe cost 10% CPU when disconnect

### ISSUE THREAD

**Issue by LeadroyaL** [stascorp/rdpwrap#853]
Platform:  Win10-1903
Version: 1.6.2 (newest)
Wrapper state: Installed     ver 1.5.0.0
Service state: Running ver 10.0.18362.53
Listener state:Listening [fully supported]

I have two users A and B, both of them is myself.

Step1: A RDP login, B RDP login.
Step2: B disconnect. (And I'm sure I have no background tasks.)
Step3: A open task manager and see the following picture:

![image](https://user-images.githubusercontent.com/9478918/62275554-cffa3c80-b474-11e9-93ac-10fa0b46a8c3.png)

When I want to figure it out, I find this execute file: 
C:\Windows\System32\dwm.exe cost 10% CPU.
![image](https://user-images.githubusercontent.com/9478918/62275692-10f25100-b475-11e9-87fd-9b74d1e01bc5.png)

Step4: B RDP connect again.
The usage of CPU from 10% to 0%.

So why this file cost 10% CPU when user is offline? Thanks!

**Comment by ghost** [comment]
I am having same issues. Now i cannot connect via remote desktop. It freezes, i get black screen, then disconnects

**Comment by LeadroyaL** [comment]
https://www.reddit.com/r/Windows10/comments/c0agnb/1903_dwmexe_goes_to_100_cpu_on_remote_host_after/

**Comment by ghost** [comment]
what if this is happening for AZURE VM? (it's not running intel video card)?

**Comment by hsv000** [comment]
Me too. I have 5 users, and when they disconnect, user's dwm process use 25%cpu (4core cpu -> 100% load 1 core)
Need help

**Comment by s0nic9** [comment]
https://github.com/stascorp/rdpwrap/issues/858#issuecomment-523192537
