### ISSUE TITLE
Error when installing RDP: error code 0

### ISSUE THREAD

**Issue by dajpes** [stascorp/rdpwrap#857]
Hi, after many hours trying to fix this by my self, I came upon this error:

" OpenKeyReadOnly error code 0"

Whether I try to run install.bat or uninstall.bat I got the same error:

https://i.imgur.com/2FYWkpu.jpg

If I go to the source code, i Find this:

`

procedure CheckInstall;
var
  Code: DWORD;
  TermServiceHost: String;
  Reg: TRegistry;
begin
  if Arch = 64 then
    Reg := TRegistry.Create(KEY_WOW64_64KEY)
  else
    Reg := TRegistry.Create;
  Reg.RootKey := HKEY_LOCAL_MACHINE;
  if not Reg.OpenKeyReadOnly('\SYSTEM\CurrentControlSet\Services\TermService') then
  begin
    Reg.Free;
    Code := GetLastError;
    Writeln('[-] OpenKeyReadOnly error (code ', Code, ').');
    Halt(Code);
  end;
  TermServiceHost := Reg.ReadString('ImagePath');
  Reg.CloseKey;
  if (Pos('svchost.exe', LowerCase(TermServiceHost)) = 0)
  and (Pos('svchost -k', LowerCase(TermServiceHost)) = 0) then
  begin
    Reg.Free;
    Writeln('[-] TermService is hosted in a custom application (BeTwin, etc.) - unsupported.');
    Writeln('[*] ImagePath: "', TermServiceHost, '".');
    Halt(ERROR_NOT_SUPPORTED);
  end;
  if not Reg.OpenKeyReadOnly('\SYSTEM\CurrentControlSet\Services\TermService\Parameters') then
  begin
    Reg.Free;
    Code := GetLastError;
    Writeln('[-] OpenKeyReadOnly error (code ', Code, ').');
    Halt(Code);`

Do you have any idea what could that error be? I tried disabling nod 32+ firewall to no avail. I don't know what else to do

**Comment by fwelto** [comment]
did you try running the .bat file as admin (elevated privilege level)?

**Comment by Pegaska** [comment]
ESET recently started to remove RDPWInst.exe, you are missing the TermService registry service after restarting your computer

**Comment by moreleb** [comment]
exactly as you describe. eset removes rdp service. is there any solution to restore rdp?

**Comment by dajpes** [comment]
> ESET recently started to remove RDPWInst.exe, you are missing the TermService registry service after restarting your computer

I got exactly the same error (thanks nod). I even tried seting the entire rdp wrap as an exclusion but that didn't work either.

**Comment by moreleb** [comment]
Before unpacking and install RDPWrap, I turned off the options in ESET:
Enable detection of potentially unwanted applications
Enable detection of potentially unsafe applications
Enable detection of suspicious applications

As for the absence of Remote Desktop Services, ESET deletes the registry entry: HKEY_LOCAL_MACHINE \ SYSTEM \ CurrentControlSet \ services \ TermService

You must add an entry. I found a script on the internet that added the RDP service. Also, I couldn't add exceptions in ESET

**Comment by moreleb** [comment]
Exclusions ESET:

Threat: @NAME=Win32/RDPWrap.A@TYPE=ApplicUnsaf
Path: C:\RDPWrap-v1.6.2\RDPWInst.exe

Threat: @NAME=Win32/RDPWrap.A@TYPE=ApplicUnsaf
Path: *

Threat: @NAME=Win64/RDPWrap.A@TYPE=ApplicUnsaf
Path: C:\Program Files\RDP Wrapper\rdpwrap.dll

Threat: @NAME=Win64/RDPWrap.A@TYPE=ApplicUnsaf
Path: *

**Comment by dajpes** [comment]
> Before unpacking and install RDPWrap, I turned off the options in ESET:
> Enable detection of potentially unwanted applications
> Enable detection of potentially unsafe applications
> Enable detection of suspicious applications
> 
> As for the absence of Remote Desktop Services, ESET deletes the registry entry: HKEY_LOCAL_MACHINE \ SYSTEM \ CurrentControlSet \ services \ TermService
> 
> You must add an entry. I found a script on the internet that added the RDP service. Also, I couldn't add exceptions in ESET

Hi,

Do you have the link for the script, or maybe the script it self

**Comment by moreleb** [comment]
You use at your own risk. Make a copy of the registry before running the script. Script for Win 7 i found on the internet. Script for Win 10 is export from my registry. They look similar, but I preferred to separate scripts

[Remote_Desktop_Services_Script](https://drive.google.com/drive/folders/1UpdH-lWQKxLHWfKuILxAEc29P7vZjZn1?usp=sharing)

**Comment by grix25** [comment]
> 
> 
> You use at your own risk. Make a copy of the registry before running the script. Script for Win 7 i found on the internet. Script for Win 10 is export from my registry. They look similar, but I preferred to separate scripts
> 
> [Remote_Desktop_Services_Script](https://drive.google.com/drive/folders/1UpdH-lWQKxLHWfKuILxAEc29P7vZjZn1?usp=sharing)

@morelab
Thanks for script, I worked out my problem by installing that reg entry.
Reinstall RDP Wrapper and installed new terms.dll for my version of OS

**Comment by thomasvjohansen** [comment]
@moreleb 
thx for the work

**Comment by acrolink** [comment]
@moreleb 

Thanks for sharing, Do I have to disable the above mentioned options in ESET and exclude `RDPWrapper` folders? What about excluding the folders only?

**Comment by moreleb** [comment]
I will not answer this question for you. I know ESET is very effective and it's better to add a few more exceptions and have a problem solved.

**Comment by JohnnyLove007** [comment]
> > You use at your own risk. Make a copy of the registry before running the script. Script for Win 7 i found on the internet. Script for Win 10 is export from my registry. They look similar, but I preferred to separate scripts
> > [Remote_Desktop_Services_Script](https://drive.google.com/drive/folders/1UpdH-lWQKxLHWfKuILxAEc29P7vZjZn1?usp=sharing)
> 
> @morelab Thanks for script, I worked out my problem by installing that reg entry. Reinstall RDP Wrapper and installed new terms.dll for my version of OS



> You use at your own risk. Make a copy of the registry before running the script. Script for Win 7 i found on the internet. Script for Win 10 is export from my registry. They look similar, but I preferred to separate scripts
> 
> [Remote_Desktop_Services_Script](https://drive.google.com/drive/folders/1UpdH-lWQKxLHWfKuILxAEc29P7vZjZn1?usp=sharing)

Thank, This Work...

**Comment by sebaxakerhtc** [comment]
Not an RDPWrapper issue
Acceptable https://github.com/stascorp/rdpwrap/issues/277

**Comment by nasrrafiq** [comment]
> You use at your own risk. Make a copy of the registry before running the script. Script for Win 7 i found on the internet. Script for Win 10 is export from my registry. They look similar, but I preferred to separate scripts
> 
> [Remote_Desktop_Services_Script](https://drive.google.com/drive/folders/1UpdH-lWQKxLHWfKuILxAEc29P7vZjZn1?usp=sharing)

Can anyone help me get this for windows server 2012 r2 9.63.9600.16384 trend micro alao wrecked my rdpwrap .

**Comment by moreleb** [comment]
> > You use at your own risk. Make a copy of the registry before running the script. Script for Win 7 i found on the internet. Script for Win 10 is export from my registry. They look similar, but I preferred to separate scripts
> > [Remote_Desktop_Services_Script](https://drive.google.com/drive/folders/1UpdH-lWQKxLHWfKuILxAEc29P7vZjZn1?usp=sharing)
> 
> Can anyone help me get this for windows server 2012 r2 9.63.9600.16384 trend micro alao wrecked my rdpwrap .

Check if the security actually removed your entry in the registry. All I have is Windows Server 2012 R2 Foundation x64 - 6.3.9600 compilation 9600. Use at your own risk. I added to the previous link

[Remote_Desktop_Services_Script](https://drive.google.com/drive/folders/1UpdH-lWQKxLHWfKuILxAEc29P7vZjZn1?usp=sharing)
