### ISSUE TITLE
Add/Modify the firewall rule when changing the port number

### ISSUE THREAD

**Issue by birdypme** [stascorp/rdpwrap#86]
Hello, thank you for this great tool.
I have been successful with this tool, with all the documentation that was helpful (setup, update.bat, how to add the "Remote Desktop Users" group) until I tried to connect remotely with a non-standard port.
In this case, I had to manually modify the firewall inbound rule to match the specific Port I am using (I am not using the standard 3389 port).
Is it possible to have RPDConf.exe change the 'Remote Desktop' Inbound firewall rule to match the port it sets when we click Apply?
Thanks,
Julien

Screenshot of the firewall rule: ![rdpwrap-firewall-rule](https://cloud.githubusercontent.com/assets/12393550/12450703/9191f286-bf85-11e5-8dc8-7bcf88dd2483.png)

**Comment by ovizii** [comment]
quick question on how to change the port, do you only do that with rdpconf change the port and apply or do you need to restart some services too? 
I'm asking as I am about to do this on a remote machine so if I mess up I have no other way to connect.

**Comment by birdypme** [comment]
Hello @ovizii, I don't use RPDConf.exe anymore (I switched to using TeamViewer which fits my needs really well), but as far a I remember for RPDConf, I simply needed to add the port to the firewall, change it in RPDConf and click apply for it to work, without restarting.
If you want a safeguard, TeamViewer can be used without installing it on the system, just take the standalone (no install) version, run it, note the ad-hoc id and password, and you can simply stop it one your RPD is working :-)
Cheers,
Julien
