### ISSUE TITLE
Automatic RDP Wrapper installer and updater (autoupdate.bat **bugfix)

### ISSUE THREAD

**Issue by asmtron** [stascorp/rdpwrap#860]
[autoupdate-v07.09.2019.zip](https://github.com/stascorp/rdpwrap/files/3588288/autoupdate-v07.09.2019.zip)

Pull request: https://github.com/stascorp/rdpwrap/pull/859

**The new batch file "autoupdate.bat" check, install and update the RDP Wrapper automatically in the background. _For example very useful after a windows update reboot ..._**

**{ Special thak to binarymaster, saurav-biswas and all other contributors }**

```
 -------------------------------------------------------------------

                        autoupdate.bat

 Automatic RDP Wrapper installer and updater // asmtron (07-09-2019)
 -------------------------------------------------------------------
 Options:
   -log        = redirect display output to the file autoupdate.log
   -taskadd    = add autorun of autoupdate.bat on startup in schedule task
   -taskremove = remove autorun of autoupdate.bat on startup in schedule task

 Info: 
   The autoupdater first use and check the official rdpwrap.ini.
   If a new termsrv.dll is not supported in the offical rdpwrap.ini,
   autoupdater first tries the asmtron rdpwrap.ini (disassembled and
   tested by asmtron). The autoupdater will also use rdpwrap.ini files
   of other contributors like the one of "saurav-biswas".
   Extra rdpwrap.ini sources can also be defined...

 { Special thak to binarymaster, saurav-biswas and all other contributors }




 INSTALL of RDP Wrapper and Autoupdater
 ======================================

 1. Copy the files from the archive "RDPWrap-v1.6.2.zip" (or newer) to the "%ProgramFiles%\RDP Wrapper" directory

    DO NOT use other location to install/extract the RDP Wrapper files.
    USE ONLY the "%ProgramFiles%\RDP Wrapper" directory (normally C:\Program Files\RDP Wrapper)


 2. Copy the files/folder from the archive "autoupdate-v07.09.2019.zip" (or newer) to the "%ProgramFiles%\RDP Wrapper" directory


 3. To enable autorun of autoupdate.bat on system startup, run the folling helper batch file as administrator:

    "%ProgramFiles%\RDP Wrapper\helper\autoupdate__enable_autorun_on_startup.bat"


 4. Set in your Antivirus/WindowsDefnder an exclusion on the folder "%ProgramFiles%\RDP Wrapper" to prevent the deletion of RDP Wrapper files


 5. Now you can use the autoupdate batch file to install and update the RDP Wrapper. Please run the folling autoupdate batch file as administrator:

   "%ProgramFiles%\RDP Wrapper\autoupdate.bat"

```

**Comment by junkwes** [comment]
Thank you but I am getting Listener state: Not listening. Everything else seems supported and fine.

**Comment by asmtron** [comment]
### **Important -> autoupdate.bat _**bugfix!_**

1. **bug:** normal copy with admin right of the file "rdpwrap_new.ini" to "rdpwrap.ini" will not work properly (file locked)
2. **fix:** we need to stream the data line by line from "rdpwrap_new.ini" to "rdpwrap.ini"
3. **add:** listener check

**With this bugfix autoupdate.bat works now as expected...**

**Comment by luisBSBDATA** [comment]
Works like a charm! Incredible work, there's a way to propose that tool to be integrated on RDPWrap? That's a game changer, main problem I have since I'm using RDPWrap is Windows Update handling but with this that's no longer a problem. Thanks!

**Comment by StarfighterJ** [comment]
Ok I just got a update today going from 18362.267 to 18362.295 not sure if rdpwrap is effected yet I hope this Autoupdate.bat works. 
Looks like terms.dil  didn't change in this 295 update no way to know if autoupdate.bat work yet

**Comment by PocketSam** [comment]
Awesome! Thanks a lot!

**Comment by gitgotgone** [comment]
Woot woot! I got Windows Defender warnings the first time just because it was an unknown app, but after that no problem. Thanks!

**Comment by PocketSam** [comment]
On Windows 7 Corporate x64 with termsrv 6.1.7601.24402 Remote Desctop often crashes. :(
[termsrv.dll](https://disk.it-fox.ru/f/bee33563f9d34970ba8c/?dl=1)

**Comment by smyle10** [comment]
cool, it solved my no-listener problem on 17134.885

**Comment by shippj** [comment]
hey Asmtron, I love the work you have done to create that awesome BAT to update the INI, but why not just modify the source code of RDPWInst.exe in your fork to make the native update function (-w) pull the INI from your fork?  Seems like you reinvented the wheel.  Also, I couldn't find a place to send you a message via your github page - did you disable comments or something?  I have a delphi7 compiler if that would be of any help to you.  thanks!

**Comment by asmtron** [comment]
Hi shippj, thanks for your offer. With the batch file we avoid hard coded links in a binary file and the download links are always visible for everyone. It is also very easy for everyone to modify/add new ini download sources. The batch file is an addon for the RDP Wrapper and it does no touch the RDP Wrapper binaries (it's intended).

**Comment by s0nic9** [comment]
@asmtron Can you merge Win7+2008R2 last update of @fre4kyC0de 
 https://github.com/fre4kyC0de/rdpwrap/blob/master/6.1.7601.24402.txt

**Comment by ghost** [comment]
@asmtron Have a look at this https://github.com/stascorp/rdpwrap/issues/872#issuecomment-526190589

**Comment by strarsis** [comment]
@s0nic9: Thanks! I just added your config to an ini file and manually reinstalled rdpwrap with the custom ini and it works now.

**Comment by RsRough** [comment]
I have done the steps listed. Here are my issues:
Service State: Starting...   Ver. 10.0.18362.53
Listener: Not Listening [Fully Supported]

I bring up Remote Desktop Services in services.msc and it shows "Starting" and I am unable to Stop, Restart, or Start it.

**Comment by vlciho** [comment]
Awesome!! This recover my install of RDPwrap! Thank you, man! :-)

**Comment by RDPGREX2019** [comment]
@vlciho Hello sir, I hope you are well, could you please help me with the solution you applied to solve the problem of the rdpwrap_10.0.18362.267 version

**Comment by RDPGREX2019** [comment]
HELPPPPPPPPPPPPPPPP!!!!!!!!!!!!!!!!!!
I couldn't solve this problem

![Captura de pantalla (224)](https://user-images.githubusercontent.com/48032846/68517879-917bd700-0246-11ea-943d-a6d2dea7d48e.png)
![Captura de pantalla (225)](https://user-images.githubusercontent.com/48032846/68517880-92146d80-0246-11ea-9e33-57ebfc3faae6.png)
![Captura de pantalla (226)](https://user-images.githubusercontent.com/48032846/68517881-92146d80-0246-11ea-8291-25647c6a89a3.png)

**Comment by vlciho** [comment]
Hello sir,

i used autoupdate utility:

https://github.com/stascorp/rdpwrap/issues/860

I runed this utility twice and resolved my problém.

V.

**Comment by vlciho** [comment]
Log here.
[autoupdate.log](https://github.com/stascorp/rdpwrap/files/3827718/autoupdate.log)
![note1](https://user-images.githubusercontent.com/43072782/68534831-7fc72c00-0339-11ea-84e9-83830564ba3b.jpg)
![note2](https://user-images.githubusercontent.com/43072782/68534838-9bcacd80-0339-11ea-8f0c-a3d516c5065f.jpg)

**Comment by actanner** [comment]
Please forgive my github ignorance.  How do I get the most recent version of the autoupdate.bat file?  Thank you.

**Comment by shippj** [comment]
> Please forgive my github ignorance. How do I get the most recent version of the autoupdate.bat file? Thank you.

here ya go:
https://github.com/asmtron/rdpwrap/tree/master/bin

**Comment by actanner** [comment]
Well, I still have lots to learn about github.  I see the autoupdate.bat listing, but I still don't know how to download the .bat file directly so that I can execute it.  Thanks in advance, and I hope to learn lots more about github soon.

**Comment by actanner** [comment]
Well, I clicked on the "Raw" button and downloaded but wound up with a strange "overdrive" extension.  Once I renamed the file, it looks like it would properly execute as a batch file, but it has the 07/09/2019 date in the remarks section, leading me to believe that it is not the most recent, since bugs were fixed on 12 Aug.  I think I am getting closer, but....

**Comment by csy9730** [comment]
windows 10.0.18363 暂缺 Build 18363 & 6.3.9600 win8.1 
rdpwrap is ok

**Comment by LiamKarlMitchell** [comment]
Yeah this fixes it.
Also if connecting to local host seemed to have to use 127.0.0.2.

However the Remote Desktop Window Store App does not connect.
Must use mstsc.exe or another Remote Desktop client.

**Comment by viafx24** [comment]
Yeah, it also fixes the problem for me. I'm using windows 10 home 10.0.19041.789. Adding in C:\Program Files\RDP Wrapper and running the autoupdate.bat allow me to get "everything in green" when launching RDPConf.exe

![image](https://user-images.githubusercontent.com/42340158/112841326-a4dc4c00-90a0-11eb-95da-c9327c302653.png)

here, one can see how looks the whole folder:

![image](https://user-images.githubusercontent.com/42340158/112841430-c0dfed80-90a0-11eb-9d65-cfd9a74f1fbc.png)

To summarize, 

-  I downloaded "**RDPWrap-v1.6.2.zip**" and put the files in C:\Program Files\RDP Wrapper

- then I downloaded "**autoupdate-v07.09.2019.zip**", put the content in C:\Program Files\RDP Wrapper

- then, i run cmd as admininstrator and run "**autoupdate.bat**"

- I didn't need to change anything related to antivirus (i'm using avast).

I got "everything in green" but when i launched RDPCheck.exe, I succeed to see the windows connection login page but after putting the password, the connexion was refused. However, when i used another computer to log-in, it Works!!! and thus i can enjoy the remote desktop .

Thanks a lot for developers and hope this comment helps.

 Cheers,

**Comment by LUCKandII** [comment]
> 是的，它也为我解决了这个问题。我正在使用Windows 10家庭版10.0.19041.789。添加C：\ Program Files \ RDP包装程序并运行autoupdate.bat，可以在启动RDPConf.exe时获得“绿色的一切”
> 
> ![图像](https://user-images.githubusercontent.com/42340158/112841326-a4dc4c00-90a0-11eb-95da-c9327c302653.png)
> 
> 在这里，可以看到整个文件夹的外观：
> 
> ![图像](https://user-images.githubusercontent.com/42340158/112841430-c0dfed80-90a0-11eb-9d65-cfd9a74f1fbc.png)
> 
> 总而言之，
> 
> * 我下载了“ **RDPWrap-v1.6.2.zip** ”，并将文件放在C：\ Program Files \ RDP Wrapper中
> * 然后我下载了“ **autoupdate-v07.09.2019.zip** ”，将内容放在C：\ Program Files \ RDP Wrapper中
> * 然后，我以管理员身份运行cmd并运行“ **autoupdate.bat** ”
> * 我不需要更改与防病毒相关的任何内容（我正在使用avast）。
> 
> 我得到了“一切都变成绿色”，但是当我启动RDPCheck.exe时，我成功地看到了Windows连接登录页面，但是在输入密码之后，连接被拒绝了。但是，当我使用另一台计算机登录时，它可以正常工作！！！这样我就可以享受远程桌面了。
> 
> 非常感谢开发人员，希望此评论对您有所帮助。
> 
> 干杯，

Thanks a lot!!!!!

**Comment by sebaxakerhtc** [comment]
Moved to [PR](https://github.com/stascorp/rdpwrap/pull/1160)
