### ISSUE TITLE
Reopen: Windows 10 version 10.0.18362.267 not supported

### ISSUE THREAD

**Issue by fglez-tsl** [stascorp/rdpwrap#861]
Hi,

Latest rdpwrap.ini is not working for me on 

Windows 10 Home 
1903
18362.267
64-bit

![rdpwrap](https://user-images.githubusercontent.com/1586803/62841000-f4d78680-bca2-11e9-8f83-ef5986ebb20b.png)

Does anyone have it working with this same configuration? 

Thank you.

_Originally posted by @fglez-tsl in https://github.com/stascorp/rdpwrap/issues/848#issuecomment-520271248_

**Comment by kastnerp** [comment]
Just got it working. Follow the instructions [here ](https://github.com/stascorp/rdpwrap/issues/860) and [here](https://github.com/stascorp/rdpwrap/issues/795) and execute everything  from 'C:\Program Files\RDP Wrapper'. 
Also, double check the terminal output of the executable, it should tell you if some script failed to execute.

**Comment by asmtron** [comment]
Hello,
up to now it's enough to use only the [autoupdater ](https://github.com/stascorp/rdpwrap/issues/860)(bugfix). Follow the instructions [here](https://github.com/stascorp/rdpwrap/issues/860), as explained also by kastnerp...

**Comment by fglez-tsl** [comment]
I don't know how, but my registry for termservices got corrupted. After fixing it following https://github.com/stascorp/rdpwrap/issues/650 , I started from scratch and got it finally working. Thank you for your support.

**Comment by superchangme** [comment]
i suggest upgrade your windows 10 home edition to professional edition ,then everything will be ok
