### ISSUE TITLE
Documentation on how to build a patch?

### ISSUE THREAD

**Issue by rip747** [stascorp/rdpwrap#865]
I know this might be a really dumb question, but is there documentation out there on exactly how you guys build these patches? I'm on the insider build right now and obviously none of the mini files are working, so I would like to help out and contribute, however I don't exactly know where to start. Is there a blog post or video somewhere that explains how to do these things?

**Comment by PrplHaz4** [comment]
This link is posted in the [Readme](https://github.com/stascorp/rdpwrap/blob/master/README.md), which includes other sources as well.
[How to find offsets for new termsrv.dll versions](http://www.youtube.com/watch?v=FiD86tmRBtk)

**Comment by sebaxakerhtc** [comment]
> This link is posted in the [Readme](https://github.com/stascorp/rdpwrap/blob/master/README.md), which includes other sources as well. [How to find offsets for new termsrv.dll versions](http://www.youtube.com/watch?v=FiD86tmRBtk)
