### ISSUE TITLE
RDP Wrapper not working ( two sessions limit). 6.1.7601.24402 , WITH offsets, all green.

### ISSUE THREAD

**Issue by RobertX2020** [stascorp/rdpwrap#870]
I had to reinstall a server, installed all updates and then re installed RDP wrapper, added the latest stuff to the ini and it shows up all green but still won't work, rdp complains about too many users logged in and says I have to disconnect someone.

This is Windows server 2008 R2 64

DLL version is: 6.1.7601.24402

Offsets added:
(jirijanata posted this)

[6.1.7601.24402]
SingleUserPatch.x64=1
SingleUserOffset.x64=17F26
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=17CFE
DefPolicyCode.x64=CDefPolicy_Query_eax_rdi

Any ideas?

![rdpwrap](https://user-images.githubusercontent.com/54403502/63517185-dbb1af80-c4c4-11e9-8304-e729ab1cbab3.PNG)

IT wouldn't let me upload a .ini file so I changed it to txt.

[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/3530250/rdpwrap.txt)

Already tried restarting remote desktop services and the whole server but it's still not working.

**Comment by RobertX2020** [comment]
![rdpwrap](https://user-images.githubusercontent.com/54403502/63517097-ae650180-c4c4-11e9-874b-5b1c1414b620.PNG)

**Comment by s0nic9** [comment]
Just tested on fresh Win2008R2 fully updated, ini from fre4kyC0de works.
1 local user + 4 concurrent users , no problems.

**Comment by RobertX2020** [comment]
> Just tested on fresh Win2008R2 fully updated, ini from fre4kyC0de works.
> 1 local user + 4 concurrent users , no problems.

You're right, the offsets posted by Fre4kyC0de do work ok, it took me a while to find them out:

(Don't forget to leave an empty line at the end of the text)


[6.1.7601.24402]
SingleUserPatch.x86=1
SingleUserOffset.x86=1A675
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=17F26
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=19E41
DefPolicyCode.x86=CDefPolicy_Query_eax_esi
DefPolicyPatch.x64=1
DefPolicyOffset.x64=17CFE
DefPolicyCode.x64=CDefPolicy_Query_eax_rdi
