### ISSUE TITLE
"fully supported" but cannot connect concurrently still

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#872]
Guest: Windows 10 1607 LTSB, RemoteFX enabled, no updates installed.
Host: Hyper-V machine hosted in another 1607LTSB

<img width="410" alt="Screen Shot 2019-08-29 at 16 04 02" src="https://user-images.githubusercontent.com/8103074/63922119-a550d300-ca76-11e9-9030-6837d089b20c.png">

<img width="702" alt="Screen Shot 2019-08-29 at 16 04 22" src="https://user-images.githubusercontent.com/8103074/63922147-b1d52b80-ca76-11e9-870e-1bda3d018d78.png">

**Comment by s0nic9** [comment]
have you tried updates from https://github.com/stascorp/rdpwrap/issues/860 ?

**Comment by ghost** [comment]
@s0nic9 

Well, I just tried https://github.com/stascorp/rdpwrap/issues/860#issue-479437597 with a brand new 1703 15063.0 OS recommended by https://github.com/stascorp/rdpwrap/issues/127#issuecomment-410929442. But the problem still exist.

![image](https://user-images.githubusercontent.com/8103074/63928596-69236f80-ca82-11e9-853b-a0d5d481c4a0.png)

![image](https://user-images.githubusercontent.com/8103074/63928799-d8995f00-ca82-11e9-9ee6-15269c17f2d9.png)

**Comment by ghost** [comment]
Hi @s0nic9 
Do you know how to configure this manually without using RDPWrapper in Pro? I mean as the common way (however i know enable and configure user account for RDP) but there numerous trouble to set up through group policy for simultaneous and concurrent sessions.
I asked @binarymaster but he refused saying not maintain or support for this project right now :(

**Comment by strarsis** [comment]
@NetE1: From what I read Windows Pro and higher support one single RDP session.
For multiple session support, rdpwrap is still required. – Or has this changed in the meantime (https://github.com/stascorp/rdpwrap/issues/533)?

**Comment by s0nic9** [comment]
Concurrent session is only supported on Server edition or with RDPWrap trick
last updates are made from other users like [@asmtron](https://github.com/asmtron) and @fre4kyC0de

**Comment by ghost** [comment]
@s0nic9 I started to use @asmtron update and it's working as well however when remote session established then physical user screen shake one time. Have you experienced this issue or how to fix it?

**Comment by s0nic9** [comment]
I don't understand "physical user screen shake one time" sorry for my english ...
try https://github.com/stascorp/rdpwrap/issues/858#issuecomment-523192537

**Comment by ghost** [comment]
Hi @s0nic9 
No any connect or usage problem for both physical and remote users. i mean when remote session established to computer then physical computer screen shake **instantly only one time** (less than second)

  (see below GIF)
![flickering-macbook-screen](https://user-images.githubusercontent.com/46082456/64184059-11777080-ce95-11e9-9fbc-b78f9ee036da.gif)

**Comment by carlos107fer** [comment]
hi @haodong and @NetE1 , @s0nic9  ..sorry somebody can help me with this problem .. I read but I have the same error ..thanks

**Comment by strarsis** [comment]
I also experience this flash when someone else logs in remotely. But the flash happens only once per login. This symptom started to happen after the last update.

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/353
