### ISSUE TITLE
Remote printing not working in Windows 10 Pro 10.0.18362.267, RDPWrap v 1.5.0.0

### ISSUE THREAD

**Issue by ryangriggs** [stascorp/rdpwrap#874]
RDP connections work fine, but remote printers do not appear.  What can I do to fix this?  Thanks.

Screenshot of RDP Wrapper Configuration:
![image](https://user-images.githubusercontent.com/5854489/64020225-0fad5600-caff-11e9-9003-4449e12d8562.png)

**Comment by TanMan1217** [comment]
Have you set your RDC remote connection to forward printers? It's off by default.

![image](https://user-images.githubusercontent.com/20880426/64029418-830c9300-cb12-11e9-8d0b-d89a29d4e886.png)

**Comment by ryangriggs** [comment]
Yes it's turned on to enable printers.  Thanks for mentioning this though,
as it may not have been an obvious step.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Ryan Griggs
Hilltop Computing
www.hilltop.net
859-328-3223
Toll Free: 1 (888) 5-HILLTOP (888-544-5586)

**Comment by khshassa** [comment]
Set **Enable**

Computer Configuration –> Administrative Templates –> Windows Components -> Remote Desktop Services –> Remote Desktop Session Host -> Printer Redirection -> Use Remote Desktop Easy Print driver first 

Also, If you connect via the Internet, you can configure ScrewDrivers, but it’s paid

**Comment by ryangriggs** [comment]
I tested this but it's not working.  Any other ideas for getting local
printers working?

Thanks

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Ryan Griggs
Hilltop Computing
www.hilltop.net
859-328-3223
Toll Free: 1 (888) 5-HILLTOP (888-544-5586)

**Comment by khshassa** [comment]
Use Screw Driver

https://yadi.sk/d/ox1YMniQRTI82A

https://yadi.sk/d/kH_JT9Gm1sbFrA

**Comment by s0nic9** [comment]
Remote Printing is working without rdpwrap ? Because I don't think it's related to rdpwrap ...

**Comment by hanneshar** [comment]
Would you mind to give us the PW for the Scre Driver tools?



Thanks,



Hannes

**Comment by khshassa** [comment]
12345678

Sorry )))

**Comment by hanneshar** [comment]
Thanks :-)

**Comment by cra3yk** [comment]
The problem still persist in Windows 10 build newer than 1709 (it starts from 1803) and rdpwrap installed.

Below two screens:
1) With rdpwrap installed the redirected ones ("przekierowana sesja") are the built-in/virtual printers only (PDF, XPS and fax)
![with rdwrap](https://user-images.githubusercontent.com/43071169/72073643-987ba000-32f0-11ea-8f5b-c68862cd3226.PNG)


2) without rdpwrap installed - the physical printers appeared correctly (the KM_C224_IT is physical Konica Minolta printer, installed as TCP/IP printer in my Windows 10 1909 laptop)
![without rdwrap](https://user-images.githubusercontent.com/43071169/72073693-b47f4180-32f0-11ea-9ea7-47a72bd39639.PNG)


The version rdpwrap
![rdp version](https://user-images.githubusercontent.com/43071169/72073778-e690a380-32f0-11ea-914e-3035ca684b7c.PNG)


PS: I have tested different combination of W10 versions and my conclusion is:
a) When host computer is W10 1709 or older (1703 etc) it works well with rdpwrap installed - all printers from client computer are visible in host computer as "redirected" ones)

b) When host computer is W10 1803 or 1809 or 1903 or 1909 and rdpwrap is installed on host computer - the printer redirection from client works partially (only to virtual printers)

c) When host computer is W10 1803 or 1809 or 1903 or 1909 and rdpwrap is NOT installed - the printer redirection works ok (all printers from client computer are visible in host computer as "redirected" ones)

PPS: in [this](https://github.com/stascorp/rdpwrap/issues/504#issuecomment-458906891) thread **novaflash** suggested that this issues are in non-english W10 versions, but I don't know if it is true (i'm using polish version of W10)

**Comment by Mindaugas85** [comment]
any issues abou redireting printers?
from latest w10 Pro versions?

**Comment by cra3yk** [comment]
20H2 - same issue (no redirection for network printers)

**Comment by soundmountain** [comment]
I had the same Issue for a long time, and I just made it work again by installing the printer driver on the remote host and the local client as well. In the not working state, it said "ipp class driver" in the properties of the printer (locally and remotely), after installing the driver on both the host and the client the driver has the actual name of the printer (Brother HL-3142CW in my case) and printing works again. If you install the driver through rdp, disconnect after installation and reconnect. I guess windows 10 installed my printer with a generic driver that worked fine locally but not through rdp connection. A friends pc with a different printer from hp has the same problem, I will test it there as well and report back, could be in a couple of days however.

**Comment by newbiebay2** [comment]
You have to remove Slinit lines from your supported version on the ini file, that will fix it, something must be wrong with the patching of the several policies that interferes with printer redirection, I hope someone can fix this error, it could be patch address or something else, cheers.

**Comment by soundmountain** [comment]
> I had the same Issue for a long time, and I just made it work again by installing the printer driver on the remote host and the local client as well. In the not working state, it said "ipp class driver" in the properties of the printer (locally and remotely), after installing the driver on both the host and the client the driver has the actual name of the printer (Brother HL-3142CW in my case) and printing works again. If you install the driver through rdp, disconnect after installation and reconnect. I guess windows 10 installed my printer with a generic driver that worked fine locally but not through rdp connection. A friends pc with a different printer from hp has the same problem, I will test it there as well and report back, could be in a couple of days however.

Sorry, I forgot to report back, it didn't work for the other device which was a HP printer. So the workaround above only seems to work in some cases.

**Comment by nordscan** [comment]
> You have to remove Slinit lines from your supported version on the ini file, that will fix it, something must be wrong with the patching of the several policies that interferes with printer redirection, I hope someone can fix this error, it could be patch address or something else, cheers.

Perfect answer in right time... i lost only 5hours to solve this issue :)

**Comment by kotoucx** [comment]
Great, thanx, it works.
I have deleted highlighted italic rows:

[10.0.19041.789]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B59D9
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3BC45
SingleUserCode.x86=nop
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E7C9
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
**_SLInitHook.x86=1
SLInitOffset.x86=67BF8
SLInitFunc.x86=New_CSLQuery_Initialize_**

LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F41
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
**_SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize_**

[10.0.19041.789-SLInit]
bInitialized.x86=D0954
bServerSku.x86=D0958
lMaxUserSessions.x86=D095C
bAppServerAllowed.x86=D0964
bRemoteConnAllowed.x86=D096C
bMultimonAllowed.x86=D0970
ulMaxDebugSessions.x86=D0974
bFUSEnabled.x86=D0978

bInitialized.x64=106028
bServerSku.x64=10602C
lMaxUserSessions.x64=106030
bAppServerAllowed.x64=106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64=106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64=10604C

**Comment by cra3yk** [comment]
`curl.exe -j -L "https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini" | sed.exe -re "s/^SLInit/;SLInit/g"`

do this job

**Comment by newbiebay2** [comment]
> `curl.exe -j -L "https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini" | sed.exe -re "s/^SLInit/;SLInit/g"`
> 
> do this job

That would work to remove the troubled lines, but I hope someone can debug the real problem with those.

**Comment by 0142929** [comment]
> You have to remove Slinit lines from your supported version on the ini file, that will fix it, something must be wrong with the patching of the several policies that interferes with printer redirection, I hope someone can fix this error, it could be patch address or something else, cheers.

it really works, thanks!

x86 and x64 SLInit
10.0.19041.964
after removing following lines:
**SLInitHook.x86=1
SLInitOffset.x86=687F8
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=1E29C
SLInitFunc.x64=New_CSLQuery_Initialize**
and all printers work again now

**Comment by newbiebay2** [comment]
> > You have to remove Slinit lines from your supported version on the ini file, that will fix it, something must be wrong with the patching of the several policies that interferes with printer redirection, I hope someone can fix this error, it could be patch address or something else, cheers.
> 
> it really works, thanks!
> 
> x86 and x64 SLInit
> 10.0.19041.964
> after removing following lines:
> **SLInitHook.x86=1 SLInitOffset.x86=687F8 SLInitFunc.x86=New_CSLQuery_Initialize SLInitHook.x64=1 SLInitOffset.x64=1E29C SLInitFunc.x64=New_CSLQuery_Initialize**
> and all printers work again now

You are welcome! :)

**Comment by DrLove73** [comment]
I can attest that commenting out SLInit lines with # worked as a charm. We can print now again, hardware printers can now be redirected again, not just virtual printers by Microsoft.
Is it enough to change **SLInitHook.x64=1**  to **SLInitHook.x64=0** (for 64-bit system) and is it possible to change RDPConfig to have checkbox we can tick on/off to get desired behavior? After any update we will need to edit ini file manually by first searching proper dll version config.

**Comment by nordscan** [comment]
Hi, have another issue,
from last time i disbaled the windows update and nothing in the system was changed but now
the remote printer sharring work  only on some user accounts..
i try some reboots, try to add administrators group to the account but it still doesnt work.
Maybe someone have a solution for this.

thank you

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/504

**Comment by shufog1** [comment]
> > You have to remove Slinit lines from your supported version on the ini file, that will fix it, something must be wrong with the patching of the several policies that interferes with printer redirection, I hope someone can fix this error, it could be patch address or something else, cheers.
> 
> it really works, thanks!
> 
> x86 and x64 SLInit 10.0.19041.964 after removing following lines: **SLInitHook.x86=1 SLInitOffset.x86=687F8 SLInitFunc.x86=New_CSLQuery_Initialize SLInitHook.x64=1 SLInitOffset.x64=1E29C SLInitFunc.x64=New_CSLQuery_Initialize** and all printers work again now

Thank You, all the other posts only say to change the SLInitHook value to 0, which didn't help in my case.
after removing the other lines you mentioned it worked for me.

**Comment by newbiebay2** [comment]
You are welcome 😃
