### ISSUE TITLE
rdpwrap.ini for Windows 17763.678 

### ISSUE THREAD

**Issue by CoyoteRouge** [stascorp/rdpwrap#876]
rdpwrap.ini is not supporting 17763.678 
Is there anyone experienced here to set the right offset on rdpwrap.ini for this version ?

King regards,

**Comment by s0nic9** [comment]
please read issues, you need updates from other users like https://github.com/stascorp/rdpwrap/issues/860

**Comment by CoyoteRouge** [comment]
Thanks. It's amazing
