### ISSUE TITLE
18362.267 limit to five users over windows 10 pro N 32 bit

### ISSUE THREAD

**Issue by lavsoft** [stascorp/rdpwrap#881]
Hi,
we can't connect more than 5 users with remote desktop on 18362.267 (1903 May) version
on Win10 Pro N 32bit.
The problem does not exist with the 1803 always on Win10 Pro N 32 bit. Any suggestions?
We already modified the INI file and termsrv.dll as suggested in an another thread.
Thanks in advance.
![Annotazione 2019-09-10 175223](https://user-images.githubusercontent.com/55151080/64629623-d5dc2980-d3f3-11e9-80cc-9bd22346cc6e.png)

**Comment by s0nic9** [comment]
no problem here, with 6 users + the console.
first try was stuck at 5 users too because i don't remember to modify the default 1GB RAM for a x86 VM !

**Comment by lavsoft** [comment]
> no problem here, with 6 users + the console.
> first try was stuck at 5 users too because i don't remember to modify the default 1GB RAM for a x86 VM !
