### ISSUE TITLE
2 users one mouse pointer

### ISSUE THREAD

**Issue by ndeaveiro** [stascorp/rdpwrap#882]
I am having an issue with the RDP when I log into a machine, the rdp user and the user working directly on the computer are using the same "session" so when one of them move the cursor it moves in the rdp session as well. Every other user that logs in via RDP after the first user works fine.

Even when I do a rdpcheck.exe the whole desktop resolution is reduced to the rdpcheck resolution. It goes back to normal when I disconnect or sign out.

I trust this makes sense?
![Annotation 2019-09-10 190625](https://user-images.githubusercontent.com/55155395/64636000-168e6f80-d401-11e9-8079-4568e355df7b.png)

**Comment by s0nic9** [comment]
I have same problem only using TeamViewer. Do you use another remote control other than native rdp ?

**Comment by ndeaveiro** [comment]
Closing TeamViewer did the trick. didn't even need to uninstall

Thanks for the quick and helpful tip!

**Comment by sebaxakerhtc** [comment]
Not an DRPWrapper issue
