### ISSUE TITLE
@asmtron Can you merge Win7+2008R2 last update of @fre4kyC0de

### ISSUE THREAD

**Issue by carlos107fer** [stascorp/rdpwrap#888]
@asmtron Can you merge Win7+2008R2 last update of @fre4kyC0de 
 https://github.com/fre4kyC0de/rdpwrap/blob/master/6.1.7601.24402.txt

_Originally posted by @s0nic9 in https://github.com/stascorp/rdpwrap/issues/860#issuecomment-526090377_

Sorry men .. you can fixed this error ?

**Comment by asmtron** [comment]
the 6.1.7601.24402 update of @fre4kyC0de is now in the last ini of the **[Automatic RDP Wrapper installer and updater](https://github.com/stascorp/rdpwrap/pulls#issue-479437597)**

**Comment by sebaxakerhtc** [comment]
Not an RDPWrapper issue
