### ISSUE TITLE
stop the service running CMD as administrator

### ISSUE THREAD

**Issue by carlos107fer** [stascorp/rdpwrap#889]
stop the service running CMD as administrator
net stop termservice
	Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
net start termservice
	Reboot your PC
[rdpwrap_10.0.18362.267_x64.zip](https://github.com/stascorp/rdpwrap/files/3439496/rdpwrap_10.0.18362.267_x64.zip)

_Originally posted by @SlavaSumyUA in https://github.com/stascorp/rdpwrap/issues/848#issuecomment-515787789_

Thanks man ..yes it worked

**Comment by brgcosta** [comment]
It works on 1903 (18362.387)

**Comment by adarshmadrecha** [comment]
On my windows 10 pro, 64 bit, OS build: 17134.1040
I had to add configurations specified by https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.17134.706.txt

See discussion - https://github.com/stascorp/rdpwrap/issues/742

**Comment by sawwd** [comment]
Thanks.

![2019-10-05_1237](https://user-images.githubusercontent.com/13658340/66253186-f5edd700-e76c-11e9-954f-2077de830899.png)

**Comment by ddelagneau** [comment]
Thanks It works on 1903 (18362.356)

**Comment by geppoleppo** [comment]
>Doesn't work on 1903 18362.388

**Comment by Infomaniac007** [comment]
**geppoleppo**, the link from the first post is working with Windows build 1903 (18362.388)

![mstsc_2019-10-08_08-17-06](https://user-images.githubusercontent.com/19484277/66369233-3be0b000-e9a4-11e9-880f-285972c0add1.png)

**Comment by SobieskiCodes** [comment]
working on 18362.418

**Comment by vic-t** [comment]
Works on 18362.449

**Comment by jh2222** [comment]
The proposed solution did not work for me.
I followed all the suggested steps, including the replacement of rdpwrap.ini from the provided
rdpwrap_10.0.18362.267_x64.zip. 
Still the listening stated was **not listening**.
I am running Windows 10 Home, OS build 17763.805.

**Comment by kolomiezz** [comment]
Solution did not work
Windows 10 Home, OS build 18363.535

**Comment by cornerdebug** [comment]
Using the rdwrap_10.0.18362.267_x64.zip rdwrap.ini file worked on Windows 10 v1903, Build 18362.476

I used the following steps:

1. Run the install.bat as administrator from the manual installer
2. Run update.bat as administrator, everything already up to date
3. Open an admin CMD prompt and "net stop termservice"
4. Rename the rdwrap.ini file in C:\Program Files\RDP Wrapper" to bak-rdwrap.ini
5. Extract the rdwrap.ini file from [rdwrap_10.0.18362.267_x64.zip ](https://github.com/stascorp/rdpwrap/files/3439496/rdpwrap_10.0.18362.267_x64.zip) into the C:\Program Files\RDP Wrapper directory
6. Open an admin CMD prompt and "net start termservice"
7. Reboot

**Comment by lingyifeng** [comment]
who have rdwrap.ini for 10.0.18362.53

**Comment by sntree** [comment]
works on 10.0.18363.449

**Comment by cornerdebug** [comment]
> Using the rdwrap_10.0.18362.267_x64.zip rdwrap.ini file worked on Windows 10 v1903, Build 18362.476
> 
> I used the following steps:
> 
> 1. Run the install.bat as administrator from the manual installer
> 2. Run update.bat as administrator, everything already up to date
> 3. Open an admin CMD prompt and "net stop termservice"
> 4. Rename the rdwrap.ini file in C:\Program Files\RDP Wrapper" to bak-rdwrap.ini
> 5. Extract the rdwrap.ini file from [rdwrap_10.0.18362.267_x64.zip ](https://github.com/stascorp/rdpwrap/files/3439496/rdpwrap_10.0.18362.267_x64.zip) into the C:\Program Files\RDP Wrapper directory
> 6. Open an admin CMD prompt and "net start termservice"
> 7. Reboot

Update: A recent Windows Update caused RDP Wrapper to stop working. The fix that worked for me is to apply the updater and installer following the instructions here: [https://github.com/stascorp/rdpwrap/issues/860](https://github.com/stascorp/rdpwrap/issues/860)

**Comment by affinityv** [comment]
The easiest thing to do is to simply copy over the "in use" ini file with an updated one using an elevated cmd session and do the following, also in an elevated cmd session:
`RDPWInst.exe -r`
That will do a stop and start of the service and invoke the new INI.
I believe the INI  file is only used during service startup, so replacing it whilst everything is running does no harm.

**Comment by Zachary-2000** [comment]
Solution did not work
Windows 10 Home, eidition 1903 OS build 18362.657

**Comment by 7BigD** [comment]
> **geppoleppo**, the link from the first post is working with Windows build 1903 (18362.388)
> 
> ![mstsc_2019-10-08_08-17-06](https://user-images.githubusercontent.com/19484277/66369233-3be0b000-e9a4-11e9-880f-285972c0add1.png)

hello, could u tell me how did u solve the "not listening" problem?  and what the version of your os is? is the "file.ini" have your os'version

**Comment by sebaxakerhtc** [comment]
Not an issue
