### ISSUE TITLE
Why it is asking another user disconnect?

### ISSUE THREAD

**Issue by Itsmesri** [stascorp/rdpwrap#894]
I just installed rdpwrap and trying to login with user2 (total 2 users) it is trying to disconnecting another user1. Why? Anything I missed it here. Any solutions

![image](https://user-images.githubusercontent.com/3935541/66167397-a6d66380-e5ff-11e9-8a8e-ae0127909301.png)

![image](https://user-images.githubusercontent.com/3935541/66167404-ac33ae00-e5ff-11e9-8e4f-764e139d8c23.png)

![image](https://user-images.githubusercontent.com/3935541/66167408-afc73500-e5ff-11e9-9eaf-d72f403d6d70.png)

**Comment by ghost** [comment]
Your termsrv.dll is not patched for multiple connections to be allowed.

**Comment by Itsmesri** [comment]
How to do that? termsrv.dll need to patched. Please share it

**Comment by jeffheld** [comment]
rdpwrap.ini must have entries for the version of the service state listed.  Here's what I do after Windows Updates.

1. Google "rdpwrap" + the service state version listed in the config application
2. Hope someone posted the code to add to rdpwrap.ini the version (Like this https://github.com/stascorp/rdpwrap/issues/886)
3.  Run this in CMD as admin: net stop termservice
4. Paste the code from #2 into end of  C:\Program Files\RDP Wrapper\rdpwrap.ini
5. Reopen the config application and confirm it's all "green"
6.  Run this in CMD as admin: net start termservice

**Comment by s0nic9** [comment]
don't forget the mandatory empty last line at the end of rdpwrap.ini

**Comment by Itsmesri** [comment]
@jeffheld solution worked for me. Thank you!
