### ISSUE TITLE
Is there an update on 17763.775

### ISSUE THREAD

**Issue by teomihsav** [stascorp/rdpwrap#901]

**Comment by teomihsav** [comment]
I can't roll back less than 17763.775

**Comment by servisichoice** [comment]
Where is .ini file for winver 17763.775 ?

**Comment by teomihsav** [comment]
At Program files directory

**Comment by servisichoice** [comment]
Can you upload it and send link?

**Comment by teomihsav** [comment]
Here is it:   https://drive.google.com/file/d/1Xj0fIr8ihB_itxwWC3a8-FkkRAcAjyXi/view?usp=sharing

**Comment by teomihsav** [comment]
> Can you upload it and send link?



> Can you upload it and send link?

**Comment by teomihsav** [comment]
> Can you upload it and send link?

Here is it: https://drive.google.com/file/d/1Xj0fIr8ihB_itxwWC3a8-FkkRAcAjyXi/view?usp=sharing

**Comment by teomihsav** [comment]
I use that Autoupdate and worked fine: https://github.com/stascorp/rdpwrap/issues/860

**Comment by KLEPTOROTH** [comment]
this is a desktop.ini not an rdpwrap.ini... am i missing something?
