### ISSUE TITLE
RDP WRAPPER NOT WORKING

### ISSUE THREAD

**Issue by ITSUPPORTGIC** [stascorp/rdpwrap#903]
After windows update in october 2019 version KB4519338, Rdp wrapper not working. Need Updated ini.file?

**Comment by SobieskiCodes** [comment]
Which version of windows are you running?

**Comment by nutoles3** [comment]
After windows update in october 2019  Rdp wrapper not working
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
Help please.

**Comment by SobieskiCodes** [comment]
https://github.com/stascorp/rdpwrap/issues/906
can try that (uninstall first), however I don't have Pro, so I have no way of testing - they are both 18362 though and .418 was the October build and working on my system (home).

**Comment by sebaxakerhtc** [comment]
WORKING
