### ISSUE TITLE
Help!win x64 1903 10.0.17763.437 【not listening】【fully supported】

### ISSUE THREAD

**Issue by VirgoArt** [stascorp/rdpwrap#904]
so...Can someone give me a support termsrv.dll?
![image](https://user-images.githubusercontent.com/41778222/66637822-68b3f200-ec46-11e9-9248-744cdbd7f9d8.png)
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/3716500/rdpwrap.zip)

**Comment by DumbRhythmGamer** [comment]
[dlls (1).zip](https://github.com/stascorp/rdpwrap/files/3721238/dlls.1.zip)

**Comment by blacktraceus** [comment]
sorry for ignorance, what should I do with those two .dll?

**Comment by DumbRhythmGamer** [comment]
take the file in system 32 put in system 32 
take the file in syswow64 put in syswow64

**Comment by VirgoArt** [comment]
Thanks all , But I upgrade my cpmputer, will this is enterprise version, its ok
