### ISSUE TITLE
Cant connect more user Windows 10 32bit after update.

### ISSUE THREAD

**Issue by servisichoice** [stascorp/rdpwrap#912]
Hi i cant connect more user on w10  Profi
![Snímek obrazovky (35)](https://user-images.githubusercontent.com/56356648/67279649-b8f34580-f4cb-11e9-954b-8395cde1ce25.png)

**Comment by s0nic9** [comment]
Windows 10 pro ?

**Comment by servisichoice** [comment]
yes Windows 10 Profi sorry

**Comment by s0nic9** [comment]
please read before posting, you need a empty line at the end of the ini because you have edited the file manually.

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/871
