### ISSUE TITLE
RDPWrapper Working but disconnects & turn off session automatically after x mins?

### ISSUE THREAD

**Issue by aloksharma1** [stascorp/rdpwrap#915]
Hi,

i have gone through few fixes to rdpwrap and made it working with new ini files, but now whenever i leave the session unattended for a few mins, it automatically logs me out from system. now all my unsaved work gets at risk due to this.
does anyone else having same issue, whats the remedy to this.
win version Microsoft Windows [Version 10.0.18362.418]
regards

Edit: I Have noticed this behaviour on active session too, so it doesn't matter if its attended or unattended session, it will kick me out and turn off the session.

**Comment by Dabao2010** [comment]
I have the same problem on my desktop with os 17134.885. 

if trying to log on within 5 minutes after startup, the remote window will be closed soon and you will never log on remotely and even cannot logon on the console.

**Comment by sebaxakerhtc** [comment]
Looks like you have any other RDP software (Anydesk/TeamViewer, etc.)
