### ISSUE TITLE
TermDD Error EventID 56 when a new explorer window (not IE) is started

### ISSUE THREAD

**Issue by Spamme1** [stascorp/rdpwrap#92]
"The Terminal Server security layer detected an error in the protocol stream and has disconnected the client. Client IP: 192.168.0.112."

This error happens every time on the remote computer (windows 7 sp1 x64 home premium) when a new explorer window is started or when a file dialog (open or save) in another application is shown , I know it because every time I get disconnected and I have to wait 5 seconds to get reconnected.

[TermDDEventID56.txt](https://github.com/binarymaster/rdpwrap/files/137708/TermDDEventID56.txt)

**Comment by binarymaster** [comment]
Network protocol errors are not related to RDP Wrapper, because its code doesn't have control over network.
