### ISSUE TITLE
Win10 Compilation 101903 18362.418

### ISSUE THREAD

**Issue by jorgego19** [stascorp/rdpwrap#920]
Good afternoon, someone has been able to use RDP.Wrapper.Library with this compilation of Windows 10 Pro. Thank you very much.

**Comment by SobieskiCodes** [comment]
you mean like https://github.com/stascorp/rdpwrap/issues/906?

**Comment by lgzcoollg** [comment]
Use the file below:

[https://github.com/stascorp/rdpwrap/issues/902#issuecomment-541559295](url)

**Comment by WVVxm** [comment]
> Good afternoon, someone has been able to use RDP.Wrapper.Library with this compilation of Windows 10 Pro. Thank you very much.

Please check pull requests, there's some good guys updating rdpwrap.ini.

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/871
