### ISSUE TITLE
i love u

### ISSUE THREAD

**Issue by stepluck** [stascorp/rdpwrap#925]
would anybody behind this magnificent software update it to support the latest windows 10 and server 2016/19 ^^;

This is the best I found for RDP software ^^

**Comment by SobieskiCodes** [comment]
This project is dead.

**Comment by Lowspin47** [comment]
Why though? RDP Wrapper is a great solution to what I've needed.

**Comment by SobieskiCodes** [comment]
Because the dev doesn't have interest anymore? feel free to take it over.
