### ISSUE TITLE
Missing RDPWInst.exe

### ISSUE THREAD

**Issue by bfjeje** [stascorp/rdpwrap#927]
Hi. I've noticed that there is no RDPWInst.exe in the repository. I can't install RDP Wrap. Can any admin see what's going on? Thank you.

**Comment by SobieskiCodes** [comment]
> Files in **release** package:

https://github.com/stascorp/rdpwrap/releases



PS this project is dead.

> Latest commit a5c64a4 on Dec 20, 2018

**Comment by DCS59** [comment]
The missing RDPWinst.exe is probably being removed automatically by your antivirus program. It needs to be excluded as a virus. Some antivirus programs make this difficult and not obvious.

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/277

**Comment by Natotela** [comment]
> The missing RDPWinst.exe is probably being removed automatically by your antivirus program. It needs to be excluded as a virus. Some antivirus programs make this difficult and not obvious.

within the GitHub repo I couln't find the RDPWinst.exe, nothing to do with any antivirus on my personal machine

**Comment by sebaxakerhtc** [comment]
> I couln't find the RDPWinst.exe

Did you downloaded latest release?
![Снимок экрана 2023-02-10 в 10 54 41](https://user-images.githubusercontent.com/32651506/218047439-6ca05379-0759-4f15-a1bc-80457ec6fcd4.png)

**Comment by Natotela** [comment]
> > I couln't find the RDPWinst.exe
> 
> Did you downloaded latest release? ![Снимок экрана 2023-02-10 в 10 54 41](https://user-images.githubusercontent.com/32651506/218047439-6ca05379-0759-4f15-a1bc-80457ec6fcd4.png)

Got it , thanks
