### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by jayjupdhig** [stascorp/rdpwrap#931]
![ergergerg](https://user-images.githubusercontent.com/42765391/69410580-a60ea380-0d0b-11ea-83f2-ce14209790d0.PNG)

**Comment by jayjupdhig** [comment]
after the 2nd try, the message is gone. and i see it in the unisntall list. but when i try to uninstall, the message will be shown again. so not uninstallable!!

it leaved my system in an inconsistenst state, WTF?!?!

**Comment by jayjupdhig** [comment]
how to do a revert, so the system is clean again??

**Comment by jayjupdhig** [comment]
please tell me EXACTLY all step what that .msi has done - then i can uninstall it manually!

**Comment by SobieskiCodes** [comment]
https://github.com/stascorp/rdpwrap/blob/master/src-installer/RDPWInst.dpr
Lucky for you, its open source!

**Comment by jayjupdhig** [comment]
Your installer does not contain that message:

"there is a problem with this windows installer package"


But it will cause it and i don't know why...?

How to uninstall it completely?

I don't have the time to re-install my server completely new...:-(

**Comment by jayjupdhig** [comment]
I also see in that message: "Contact your support personnel or package vendor."

**Comment by jayjupdhig** [comment]
I was successful with that tool:

https://support.microsoft.com/en-nz/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed

 now i will for for another alternative to by pass the rdp connection limit (seems you are not interested to investigate?) because your sw don't work
