### ISSUE TITLE
running, listening, fully supported - but no multi-Session possible 17763.165

### ISSUE THREAD

**Issue by MerisaCWC** [stascorp/rdpwrap#943]
Dear All,
![Screenshot](https://user-images.githubusercontent.com/46190635/70933198-ccd6a600-203b-11ea-8832-ae09cd156c02.jpg)
What can i do? I can not use more than one session.
Thanks in advance

**Comment by RedZepplin** [comment]
Having a similar issue Service V: 10.0.18362.267

**Comment by AjkKarthik** [comment]
same issue 
![Capture](https://user-images.githubusercontent.com/20870970/71094625-49e75400-21d1-11ea-9362-305a6b225f64.PNG)

**Comment by AjkKarthik** [comment]
please help

**Comment by agalisteo** [comment]
Same issue.
**version: 10.0.18362.267**

**Comment by s0nic9** [comment]
use updated version https://github.com/stascorp/rdpwrap/pull/859
if hangs when disconnect use https://github.com/stascorp/rdpwrap/issues/858#issuecomment-523192537

**Comment by agalisteo** [comment]
@s0nic9 not working for us.

**Comment by MerisaCWC** [comment]
> 
> 
> use updated version #859
> if hangs when disconnect use [#858 (comment)](https://github.com/stascorp/rdpwrap/issues/858#issuecomment-523192537)

This one works fine for me. Thanks a lot.
