### ISSUE TITLE
Multiple rdp sessions to and from one machine.

### ISSUE THREAD

**Issue by JL01152** [stascorp/rdpwrap#949]
Hi, I'm having trouble trying to get around this obstacle. I need to run an autohotkey script in the background. It would hog up my laptop if I were to run it in the foreground. How can I open an rdp session from my main session?

I currently use my phone to log into the secondary user but that times out if it is in the background and disconnects the session.

Please help. I'm at my wits end here.

**Comment by sebaxakerhtc** [comment]
Just run Remote Desktop Connection
