### ISSUE TITLE
Support for Windows 10 10.0.19041.1 (20H1) Enterprise

### ISSUE THREAD

**Issue by txsbznog** [stascorp/rdpwrap#950]
Hello,
as says the title it seems like i need new ini for rdpwrap to work, any help would be appreciated!
I've tried using old termsrv.dll's or values joffs posted @ https://github.com/stascorp/rdpwrap/issues/948 but with no luck -- service crashes.
Im attaching my dll, in case someone have time to look at it, thanks.
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/4003437/termsrv.zip)

**Comment by Aradzh** [comment]
Hi, this termsrv.dll exactly the same as in my windows directory for which  joffs @ #948 values are working. Have you add empty line (! this is crucial !) if you add values at the end of the rdpwrap.ini ? Just in case please find attached  rdpwrap.ini which is working for me.
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/4009360/rdpwrap.zip)

> I've tried using old termsrv.dll's or values joffs posted @ #948 but with no luck -- service crashes.
> Im attaching my dll, in case someone have time to look at it, thanks.
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/4003437/termsrv.zip)

**Comment by txsbznog** [comment]
> Hi, this termsrv.dll exactly the same as in my windows directory for which joffs @ #948 values are working. Have you add empty line (! this is crucial !) if you add values at the end of the rdpwrap.ini ? Just in case please find attached rdpwrap.ini which is working for me.
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/4009360/rdpwrap.zip)
> 
> > I've tried using old termsrv.dll's or values joffs posted @ #948 but with no luck -- service crashes.
> > Im attaching my dll, in case someone have time to look at it, thanks.
> > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/4003437/termsrv.zip)

Thank you! It is actually working, guess maybe i really messed up somewhere pasting these values.
Issue fixed after rebooting. Many thanks.
