### ISSUE TITLE
Support required for 10.0.14393.3393

### ISSUE THREAD

**Issue by Terksle** [stascorp/rdpwrap#951]
Hi.

Can anyone deal with it? Thanks

BTW. How to debug and create ini entries by self? Any debug tutorial?

[termsrv_10.0.14393.3393.zip](https://github.com/stascorp/rdpwrap/files/4010898/termsrv_10.0.14393.3393.zip)

**Comment by rolll13** [comment]
> Hi.
> 
> Can anyone deal with it? Thanks
> 
> BTW. How to debug and create ini entries by self? Any debug tutorial?
> 
> [termsrv_10.0.14393.3393.zip](https://github.com/stascorp/rdpwrap/files/4010898/termsrv_10.0.14393.3393.zip)

you can use this archive
[RDPWrap-v1.6.2 (2).zip](https://github.com/stascorp/rdpwrap/files/4012214/RDPWrap-v1.6.2.2.zip)

**Comment by Terksle** [comment]
Thanks, but I don`t see any entries for 14393.3393

**Comment by hajubu** [comment]
@Terksle ,
please read #938 and #939 as your sample termsrv_10.0.14393.3393.zip does contain
the file reference  for termsrv_dll_10.0.14393.3383 (rs1_release.191125-1816).
That should work for you - thanks to @fre4kyC0de  
- https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.3383.txt

**Comment by Terksle** [comment]
Thank you all. Don`t know where 3393 come from.

But does anyone know where I can find a tutorial for termsrv debug?

**Comment by hajubu** [comment]
@Terksle , supposing you have done debugging before as you need a deeper knowledge at all.
0 Application needed : https://www.hex-rays.com/products/ida/index.shtml
1 search for "ida pro tutorial  youtube" finds a lot of Hexrays 'debug / reverse Tutorials
and for rdp/termsrv 
2 search for "rdp wrapper youtube stas'm" gives info / Tutorials for that purpose
 The needed symbol-file.pdb  can be added  with the IDA application, when you start loading the termsrv.dll  ( pdb-file via internet-online or done before manually)

**Comment by s0nic9** [comment]
Windows 10 LTSB 2016 or Serveur 2016 (aka version 1607, build 14393) updated in December (version 3384) use termsrv.dll version 3383 so https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.3383.txt is working
