### ISSUE TITLE
Support for Version 14393.3384

### ISSUE THREAD

**Issue by BrettNordin** [stascorp/rdpwrap#953]
Hello all I am in need of some help.
Version: 1607
Build: 4393.3384
I have tried using the config:
[https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.3383.txt](https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.3383.txt
)
But it causes the RDP Service to crash.

Thanks!

**Comment by victorhooi** [comment]
I tried that file as well - and it didn't seem to work for me either.
