### ISSUE TITLE
support needed for v.10.0.18362.267

### ISSUE THREAD

**Issue by patzelbert** [stascorp/rdpwrap#955]
v.10.0.18362.267

**Comment by s0nic9** [comment]
https://github.com/stascorp/rdpwrap/pull/859

**Comment by buzon7** [comment]
tried everyting here, including reg fix in #954. nothing. termserv just dies (((

**Comment by DamianMorozov** [comment]
> #859

It's working, thank you for support.

**Comment by l-enenen** [comment]
same thing happen for me, I tried 859 as well
![image](https://user-images.githubusercontent.com/59414803/73037395-baeade80-3e03-11ea-8e9b-408551b6c2a1.png)

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/871
