### ISSUE TITLE
Win7 Pro 32bit 6.1.7601.24520 says fully supported, but only 2 concurrent RDP allowed

### ISSUE THREAD

**Issue by kartman85** [stascorp/rdpwrap#959]
As in the title, I cannot connect more than 2 users at a time. Running Win7Pro 32bit, rdpwrap.ini after installation was partially supported, updated to include

[6.1.7601.24402]
SingleUserPatch.x86=1
SingleUserOffset.x86=1A675
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=17F26
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=19E41
DefPolicyCode.x86=CDefPolicy_Query_eax_esi
DefPolicyPatch.x64=1
DefPolicyOffset.x64=17CFE
DefPolicyCode.x64=CDefPolicy_Query_eax_rdi

and since then it says it's fully supported, yet I am limited to 2 users concurrently.

I was hoping someone can give me a solution.

Cheers

**Comment by fusca147** [comment]
Hello,
Sorry for my English.
I have the same problem. Windows 7 32bit. Updated RDPWrap ini for full support. It accepts only two RDP connections and one local. Other than that it doesn't connect anymore.


I did the test, removed the RDPWrap, installed the "Concurrent RDP Patcher" patch from raymond.cc. And the same thing happens.

**Comment by sebaxakerhtc** [comment]
This problem occures when you use other RDP software like teamviewer
