### ISSUE TITLE
Problem with 10.0.18362.267 - User changes

### ISSUE THREAD

**Issue by technics1210** [stascorp/rdpwrap#961]
Hello,

when I start the remote connection, the user selection comes.
I can then log in with the respective user.

for example User A works on the PC
User B logs on remote.

Then the PC is switched to user B, not logged out.
User A sees what User B does.

When user B logs out, automatically fall back to user A.

Problem has been since the last update.

Is there a solution?

Thanks

**Comment by technics1210** [comment]
![Unbenanntes Bild](https://user-images.githubusercontent.com/46656712/72515839-e5132e00-3850-11ea-9a2e-e7a49636737a.png)

**Comment by Crakki** [comment]
I have the same problem - 10.0.18362.267

**Comment by s0nic9** [comment]
have you edited your .ini manually ?

**Comment by technics1210** [comment]
Yes.
It doesn't work without editing.
The other user is logged off, if it will not be edited

**Comment by s0nic9** [comment]
do you use TeamViewer ?

**Comment by technics1210** [comment]
Yes, I have Teamviewer 13
Why?

**Comment by s0nic9** [comment]
I have problem with TeamViewer 13 on an host, if I RDP into one session, my mouse move onto others sessions and I have weird screen. I must close fully TeamViewer on the host before RDP into.
sorry for my english.

**Comment by technics1210** [comment]
Right.
When i close teamviewer it works :-)
Thanks for your help

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/871
