### ISSUE TITLE
В ini добавил соответсвующие правки но так и не заработало. Только разрешен один сеанс соединения.

### ISSUE THREAD

**Issue by o-homyak** [stascorp/rdpwrap#962]
В ini добавил соответсвующие правки но так и не заработало. Только разрешен один сеанс соединения. 

Сборка ОС Вин10 : 18363.476

_Originally posted by @o-homyak in https://github.com/stascorp/rdpwrap/issues/699#issuecomment-575131993_

**Comment by PCMacDr** [comment]
and for those who are fluent in english ( goog trans )

Ini added to the appropriate edits but it didn’t work. Only one connection session is allowed.


Seriously, they do have google translate over there, right ??    ;)

**Comment by sebaxakerhtc** [comment]
Wrong offsets/editing
