### ISSUE TITLE
Not working for Windows 10 - 1909. OS Build 18363.592

### ISSUE THREAD

**Issue by Tzvetelin88** [stascorp/rdpwrap#963]
![tempw](https://user-images.githubusercontent.com/9692941/72662089-36efbb80-39eb-11ea-9e36-9f84a072c41a.png)
Hello, can you please help for Windows 10 -OS Build 18363.592

**Comment by s0nic9** [comment]
use updates from https://github.com/stascorp/rdpwrap/pull/859

**Comment by s635157034** [comment]
我的系统和上图一样，软件使用正常。但是远程桌面登录后闪退。My system is the same as the one above. The software works fine. But the remote desktop client flashes back after logging in.

**Comment by s0nic9** [comment]
try https://github.com/stascorp/rdpwrap/issues/858#issuecomment-523192537

**Comment by Tzvetelin88** [comment]
It worked 10X.

P.S.
To work I needed to uninstall, then install and update. - only with update brakes TermService.

**Comment by nadrojisk** [comment]
@Tzvetelin88 How did you get this to work? I installed the rdpwrap and it says it is up to date but says it is not supported

<img width="755" alt="Screen Shot 2020-02-05 at 1 10 47 PM" src="https://user-images.githubusercontent.com/37343577/73874326-ee246900-4818-11ea-83e0-e3547346166e.png">
