### ISSUE TITLE
create a patched dll from ini information

### ISSUE THREAD

**Issue by daltonlopesmaia** [stascorp/rdpwrap#966]
hi.
is that possible?
i have many problems with some servers running rdpwrap.

**Comment by Magissia** [comment]
Yes, that is the whole point of the ini.

**Comment by daltonlopesmaia** [comment]
How build a patched dll without rdp wrap? Ever when i use rdp wrap in the specific server the termservice stops iven changing folder permissions

**Comment by Magissia** [comment]
You don't, you use the ini file, termsrv is patched in memory and never stored on disk.

**Comment by daltonlopesmaia** [comment]
> You don't, you use the ini file, termsrv is patched in memory and never stored on disk.

yes. i know, but i have problems in a specific server, windows 2012 server R2 x64.
the termserver start and after seconds stops. 
i made changes in the ini file(19318). ok. rdpconf ok and running, but after seconds stops.

**Comment by Magissia** [comment]
Try https://raw.githubusercontent.com/asmtron/rdpwrap/01c887bb42d80730e671a897fd45ee87ff90a981/res/rdpwrap.ini

**Comment by sebaxakerhtc** [comment]
Not an DRPWrapper issue
