### ISSUE TITLE
Send your termsrv.dll to project developer for support

### ISSUE THREAD

**Issue by JimBurd** [stascorp/rdpwrap#97]
During install of v1.6 on a Win10 Pro (build 10586), I got this:
`[*] Installing...`
`[*] Terminal Services version: 10.0.10586.0`
`[-] This version of Terminal Services is not supported.`
`Send your termsrv.dll to project developer for support.`
`[+] TermService found (pid 1016).`

I'm not sure where to submit the termsrv.dll file, so I'm attaching it here.
Well ... I'm *trying* to attach the file, but I seem to be having trouble with that.  :/

**Comment by JimBurd** [comment]
![termsrv dll](https://cloud.githubusercontent.com/assets/17598969/13469129/29ecff46-e063-11e5-9f03-be75cda69fcc.png)

**Comment by binarymaster** [comment]
This version is already supported, run `update.bat`.

**Comment by JimBurd** [comment]
Wow.  I would've sworn I had downloaded the latest, and that's what I installed.  I ran update as you suggested, and now everything works just fine.  Thanks!
(And sorry to have bothered you with such a stupid issue.  My bad.)
