### ISSUE TITLE
Any support for 10.0.14393.3443 ?

### ISSUE THREAD

**Issue by merkuss** [stascorp/rdpwrap#971]
Patch KB4534271

**Comment by merkuss** [comment]
Here is unpatched [termsrv.dll](https://www.dropbox.com/s/30loxd4nzb7qit4/termsrv.dll?dl=0) of this version.

**Comment by fre4kyC0de** [comment]
The termsrv.dll hasn‘t changed since this one:
https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.3383.txt

If you‘re running on the most recent updates, take this one:
https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.3471.txt

**Comment by merkuss** [comment]
Thanks mate! :)
