### ISSUE TITLE
Patched TermSrv.dll to allow multiple connections on Windows 10 Pro 1909

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#974]
Does anyone have a Patched TermSrv.dll to allow multiple users to be logged on in Windows 10 Pro 1909.?

**Comment by s0nic9** [comment]
please read before open issue.
rdpwrap is the solution to skip termsrv.dll and latest is supported using updates from users. read issues.

**Comment by sebaxakerhtc** [comment]
> rdpwrap is the solution to skip termsrv.dll
