### ISSUE TITLE
Not supported on 10.0.18362.267

### ISSUE THREAD

**Issue by richibrics** [stascorp/rdpwrap#975]
![image](https://user-images.githubusercontent.com/12238652/73592942-143bc780-4500-11ea-9b34-ba65a6c70e0d.png)
RDPwrapper is not supported on this Windows Build

**Comment by m-337** [comment]
search for this:
 
Automatic RDP Wrapper installer and updater (autoupdate.bat **bugfix) #860

follow the instructions there.
