### ISSUE TITLE
Not working on 18363.592

### ISSUE THREAD

**Issue by MarkosTech** [stascorp/rdpwrap#976]
![image](https://user-images.githubusercontent.com/48455041/73610701-add7a780-45da-11ea-859f-201ff93fad82.png)
![image](https://user-images.githubusercontent.com/48455041/73610707-be881d80-45da-11ea-842a-89c3ce53e71c.png)

It's not working on windows 10 pro 1909. (18363.592)

**Comment by MarkosTech** [comment]
fixed #859

**Comment by MarkosTech** [comment]
![image](https://user-images.githubusercontent.com/48455041/73610846-0eb3af80-45dc-11ea-82ce-453caf49024c.png)
all ok, but is not working.

**Comment by MarkosTech** [comment]
A restart resolves this issue.

**Comment by jfariasf** [comment]
I have the same version and it's not working. The current user gets disconnected.

**Comment by gerardoparedes** [comment]
any help with this, I am having the same issue, have tried restarting to no avail
