### ISSUE TITLE
Only one account can log in

### ISSUE THREAD

**Issue by cua0930** [stascorp/rdpwrap#978]
these are my version about my win10 and software
![4VJ% WA EL)%KFO}MJWD C8](https://user-images.githubusercontent.com/60654733/73746628-95a98900-4790-11ea-90d4-112c096e06c5.png)
![FYL0FUK )LAANJ6}YVZ3SB9](https://user-images.githubusercontent.com/60654733/73746631-96421f80-4790-11ea-813d-a718b2c8c857.png)
all green but only one account can log how to deal with it. Thank you!

**Comment by s0nic9** [comment]
don't forget : the last line of the .ini must be a one blank line.

**Comment by cua0930** [comment]
> don't forget : the last line of the .ini must be a one blank line.

yes it is 
![G324T_AWOA8PTW((P)DD02P](https://user-images.githubusercontent.com/60654733/73752629-3f424780-479c-11ea-9175-c492e2ab734e.png)

**Comment by s0nic9** [comment]
Try convert your .ini from Unix to ANSI

**Comment by cua0930** [comment]
> Try convert your .ini from Unix to ANSI

no,it doesn't work

**Comment by cua0930** [comment]
could anyone help me =_=?

**Comment by Throdne** [comment]
Are you using the same user account to login because it looks like you have the "Single session per user" checked...

**Comment by cua0930** [comment]
> Are you using the same user account to login because it looks like you have the "Single session per user" checked...

I have three acount,it still remind me only one account can sign in, and another account will offline.
![20200206071028](https://user-images.githubusercontent.com/60654733/73891737-d64bf400-48af-11ea-9534-d463ec0aa9fc.png)

**Comment by xmostera** [comment]
Try to taskkill termservice

**Comment by cua0930** [comment]
> Try to taskkill termservice

i did that and the software were red

**Comment by sebaxakerhtc** [comment]
Add users to RDP group
