### ISSUE TITLE
Not listenning [18362.592]

### ISSUE THREAD

**Issue by matrixrap** [stascorp/rdpwrap#979]
Windows 10 Home
1903
18362.592
Help me please,  I already installed everything, changed rdpwrap.ini for my device. I wasted about 40 hours to repair it. 

What can you advise?
a matter of life and death

**Comment by matrixrap** [comment]
UPD: I installed another ini. It became fully support but not listening also.......

**Comment by JaJe92** [comment]
I have the same issue and hope for a new fix to come. Win 10 - 1903

**Comment by hamzahassan52** [comment]
I have same issue

**Comment by gerardoparedes** [comment]
on the same boat here, shows all the green lights lit, but not working

**Comment by asmtron** [comment]
please upload termsrv.dll 18362.592

**Comment by gerardoparedes** [comment]
here is my termsrv.dll for windows 18362.592 10 pro edition
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/4209964/termsrv.zip)

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/871
