### ISSUE TITLE
Wrappe cant be installed

### ISSUE THREAD

**Issue by DaDexter** [stascorp/rdpwrap#98]
When i try to run install.bat the command utput says:

[-]Installer executable not found.
Please extract all files from the download package or check your antivirus.

I have checked and i have got all files. I downloaded it several times. I deaktivated my antivirus. It still doesnt work.

**Comment by binarymaster** [comment]
Try starting command prompt as admin, and installing it manually:
`RDPWInst.exe -i`

(before using this command, make sure you are located in directory with extracted files)

**Comment by otalado** [comment]
Hi binarymaster, 
No wonder DaDexter cannot install the Wrapper! There are only sources ( it seems Delphi) available in the download. So, without having binaries we are stuck...
Are the binaries missing by mistake? I don't see any link pointin to them.

**Comment by binarymaster** [comment]
@otalado GitHub provides [releases](https://github.com/stascorp/rdpwrap/) section for binaries.

**Comment by DaDexter** [comment]
But there is no RDPWInst.exe in thedirectory with the extracted files?

**Comment by binarymaster** [comment]
> But there is no RDPWInst.exe

You said before...

> I have checked and i have got all files.

**Comment by binarymaster** [comment]
Closing issue, since it's not actual RDP Wrapper issue.
