### ISSUE TITLE
Remote Desktop Easy Print RDP wrap 18362.592

### ISSUE THREAD

**Issue by Desyatov91** [stascorp/rdpwrap#980]
The printer does not work on the new version of rdpwrap, it worked on the old version.
![старая](https://user-images.githubusercontent.com/60746313/73955447-35981b80-4925-11ea-9cda-ac284fed977e.jpg)
![старая2](https://user-images.githubusercontent.com/60746313/73955466-3af56600-4925-11ea-8c9b-a1aa85a572f1.jpg)

updated rdpwrap after a new update was released on windows, the multisession works but Remote Desktop Easy stopped working. When you try to print, it gives a print error. I connect from win7 to win10

![новая](https://user-images.githubusercontent.com/60746313/73955717-9a537600-4925-11ea-9482-f2fdd47648a3.jpg)
![новая2](https://user-images.githubusercontent.com/60746313/73955703-96bfef00-4925-11ea-906f-b6220b40b997.jpg)

who can tell a solution with a printer?

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/871
