### ISSUE TITLE
Windows 10 version 1909

### ISSUE THREAD

**Issue by Fams1973** [stascorp/rdpwrap#987]
terminal services rdpwrap seems to be broken in this latest update
10.0.18363.657

**Comment by StrollStars** [comment]
Me too.
Update time : 10 hours ago
OS Ver. : 18363.657
Try : #859 [autoupdate-v07.09.2019.zip](https://github.com/stascorp/rdpwrap/files/3588284/autoupdate-v07.09.2019.zip) is invalid.
File Ver. : 10.0.18362.657
File : http://ge.tt/616nHF13

**Comment by stvkodra** [comment]
I now have it working for 10.0.18363.657. Replace the rdpwrap.ini file in c:\Program Files\RDP Wrapper with the one I provided. 
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/4193606/rdpwrap.zip)

**Comment by EspacioCivico** [comment]
Thank you very much Stvkodra this if it worked for me, just replace with the one you share and that's it. I send you a hug

Muchas Gracias Stvkodra esto si ha funcionado para mi, solo remplace con el que compartes y listo. te mando un abrazo

**Comment by StrollStars** [comment]
it works for me.
Thank you very much @stvkodra.
can we find the code by ourselves?

**Comment by tomcat53** [comment]
winver 1909 (OS18363.657) and rdpwrap.ini from rdpwrap.zip posted ....ALL Green

THANKS A BUNCH

**Comment by Yifan-Song793** [comment]
Thanks a lot. It works perfectly!

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/983
