### ISSUE TITLE
Windows 10 version 10.0.17134.1304 Now Working.

### ISSUE THREAD

**Issue by Miragi423** [stascorp/rdpwrap#989]
terminal services rdpwrap seems to be broken

**Comment by taehyun-noh** [comment]
How did you solve this problem. Please share your method  to use rdp wrapper.

**Comment by Miragi423** [comment]
> How did you solve this problem. Please share your method to use rdp wrapper.

update for ver 10.0.18362.657 and autoupdate rdpwrap

**Comment by yalkink** [comment]
https://github.com/stascorp/rdpwrap/pull/859

**Comment by yalkink** [comment]
> > Bu sorunu nasıl çözdün? Lütfen rdp sarmalayıcı kullanma yönteminizi paylaşın.
> 
> 10.0.18362.657 ve otomatik güncelleme rdpwrap güncelleştirmesi

https://github.com/stascorp/rdpwrap/pull/859
