### ISSUE TITLE
Unable to Get it working on Windows 10

### ISSUE THREAD

**Issue by imgroup** [stascorp/rdpwrap#99]
Installed the latest version and downloaded the latest ini file

When I do Check this is what I get:

![image](https://cloud.githubusercontent.com/assets/12280877/13580261/6afc227c-e46f-11e5-8f85-0f12fd9e66b6.png)

Please help

**Comment by binarymaster** [comment]
This happens when you already have modified `termsrv.dll` file, or some registry settings are incorrect.

RDP Wrapper requires original `termsrv.dll` file. And also build 10586 is already obsolete - try updating to the latest Windows version.

**Comment by ericmar81** [comment]
Hi Expert, 
I am also having issue to get the RDP wrapper to work correctly. It was working fine until last week. I have no idea what happened. RDPConf shows everything is running but when I tried RDPCheck, I got a black screen. I tried to connect from outside world and I was getting error message of "couldn't connect to the remote PC. Make sure the PC is turned on and connected to the network..."

![screenshot](https://cloud.githubusercontent.com/assets/17726334/13605630/783fd36a-e583-11e5-8e5e-9e8fac067054.png)

Is there anything I can do to resolve this issue?

Thanks & regards,
Eric

**Comment by binarymaster** [comment]
@ericmar81 Hello, Eric!

This can happen when the system is low on resources (CPU, RAM or Disk). Also on some PCs the first connection can hang about 5 minutes — I don't know the reason of this. Anything you can do is to wait until the connection finally establishes or disconnects (then try connecting again).

Also you may try to upgrade your system with Windows Update.

**Comment by ericmar81** [comment]
@binarymaster Hi, 
Thanks for your reply. The thing is I never encounter such issue in the past until recently. It has been running fine. 
:(

**Comment by binarymaster** [comment]
Well, RDP Wrapper can't modify itself and system files, so this issue isn't related to it, but to the system.
