### ISSUE TITLE
RDP problem win10pro allowing only one user 

### ISSUE THREAD

**Issue by jumperjack** [stascorp/rdpwrap#990]
Hi guys,
I have one very an usual problem...like title says I have installed windows 10 pro and wrapper which apparently works just fine...
![Configuration](https://user-images.githubusercontent.com/60986093/74373076-0fb6bf00-4ddc-11ea-8dea-8fd366d1a517.jpg)

but when I tried to connect windows says

![ProblemRDP](https://user-images.githubusercontent.com/60986093/74373258-66bc9400-4ddc-11ea-8232-5f45a9cbc6a7.jpg)

Just a few more info, everything was working just fine when I set it up first time...there was power failure and after that problem happened. I assume some update was installed and applied after rebooting computer. After that I tried to set up wrapper and have this first time, then I update windows again to this build and set it up again but still the same...I have also edited GP policy remote to countless number of connections.
Anyone have any idea whats going on?

**Comment by glennrice** [comment]
I had the same issue myself this morning.

The solution that worked for me is to extract the autoupdate.zip file to your Program Files\RDP Wrapper folder (or wherever it is installed).

The autoupdate is available here: 
https://github.com/stascorp/rdpwrap/pull/859

**Comment by bjgo** [comment]
> Hi guys,
> I have one very an usual problem...like title says I have installed windows 10 pro and wrapper which apparently works just fine...
> ![Configuration](https://user-images.githubusercontent.com/60986093/74373076-0fb6bf00-4ddc-11ea-8dea-8fd366d1a517.jpg)
> 
> but when I tried to connect windows says
> 
> ![ProblemRDP](https://user-images.githubusercontent.com/60986093/74373258-66bc9400-4ddc-11ea-8232-5f45a9cbc6a7.jpg)
> 
> Just a few more info, everything was working just fine when I set it up first time...there was power failure and after that problem happened. I assume some update was installed and applied after rebooting computer. After that I tried to set up wrapper and have this first time, then I update windows again to this build and set it up again but still the same...I have also edited GP policy remote to countless number of connections.
> Anyone have any idea whats going on?

add an empty line at the end of the .ini file

**Comment by jumperjack** [comment]
Thanks guys,
bjgo was right... when I copied text lines in the ini file I made more then one empty lines at the and of ini file.. I have deleted them, left only one and now it is working just fine...
thanks again for ideas...

**Comment by sebthesun** [comment]
I have the exact same problem, same version 10.0.18362.657, I had tried all fix propose here but with no success.  

Forget it, just had to reboot to make it works....
Much thanks to you all

**Comment by snipper12343** [comment]
im having the same issue - left a blank line and rebooted but still not working. someone please help!

**Comment by affinityv** [comment]
[This should be a sticky....](https://www.hostwinds.com/guide/allow-multiple-remote-desktop-rdp-connections-in-windows-server-2012-2016/)

**Comment by sebaxakerhtc** [comment]
Closed as not actual
