### ISSUE TITLE
Windows 10 1903 Build 18362.535, RDP to Self

### ISSUE THREAD

**Issue by mdnext** [stascorp/rdpwrap#995]
Hello, how do I RDP to Self?

When I attempt to RDP to the current station I am on, I am always presented with the following error:

"Your computer could not connect to another console sessions on the remote computer because you already have a console session in progress"

In order to circumvent the error I am having to rdp to another computer then. Once inside the other computer I am then able to rdp to my current station as a different user. 

Basically:
Computer A attempts to RDP to Computer A, presented with above error. 
Computer A RDPs to Computer B
Computer B RDPs to Computer A, success

I would like to do this:
Computer A logged in as user1 RDP to Computer A as user2 without having to go through RDP inception.  

I was able to RDP to Self on windows 7, I have been unsuccessful on achieving this on Windows 10. 

If anyone is able to point me into the right direction, I would greatly appreciate it!

Thank you!

**Comment by iantmarshall** [comment]
Have you used RDPCheck.exe in the zip file?

**Comment by mdnext** [comment]
@iantmarshall rdpcheck not only worked but provided the solution! rdpcheck uses the loopback address 127.0.0.2. I was able to use that to rdp to myself. Case Closed, thank you very much!
