### ISSUE TITLE
rdp wrapper not working windows 10 home 1909 build 18363.657

### ISSUE THREAD

**Issue by saadalvi92** [stascorp/rdpwrap#996]
Rdp Wrapper is not working after the latest update of windows 10 home any help???

it show listener: not listening                [not supported]

**Comment by Moonage62** [comment]
run this in admin mode.  It's an old file someone created but if you change any of the version entries to the one you're having issues with it will update it.  IT might say it's updating the wrong thing and it might kick out an error, but it works.  If termsrv gets updated again in the future, just edit it and change one of those version numbers to the next one.  easy peasy.
[rdpwrapper_updater.zip](https://github.com/stascorp/rdpwrap/files/4204612/rdpwrapper_updater.zip)

**Comment by John78180** [comment]
Hello, this is the last Windows 10 KB4532693 that create the trouble. Uninstall it and it will work fine. Though i think RD Wrapper need an update. If someone may help i have no skills in development.

**Comment by LukasCCB** [comment]
Not working for me, later windows update the two-session stopped.

**Comment by Nikon-ssg** [comment]
Thank you very much Moonage! Works perfect.

Guys, the solution is simple.
Copy all of the RDPWrap files to the program folder - default folder is C:\Program Files\RDP Wrapper
.ini file should be there too. Then copy the updater file from Moonage post and run it as admin.

That's all.

**Comment by blueberry-bytes** [comment]
Confirm. Works like a charm. Thanks.

**Comment by accnetdev** [comment]
Confirm +1
Thanks a lot stascorp !
RDP Wrapper is a must have tool/hack I use for years.

**Comment by snipper12343** [comment]
> 
> 
> run this in admin mode. It's an old file someone created but if you change any of the version entries to the one you're having issues with it will update it. IT might say it's updating the wrong thing and it might kick out an error, but it works. If termsrv gets updated again in the future, just edit it and change one of those version numbers to the next one. easy peasy.
> [rdpwrapper_updater.zip](https://github.com/stascorp/rdpwrap/files/4204612/rdpwrapper_updater.zip)

Can't seem to get this to work for me - run the updater from the same directory and it just disspears and when I test it after it doesnt work. any suggestions?

**Comment by Moonage62** [comment]
Are you doing it in the "c:\program files\rdp wrapper" directory?  It doesn't move or change files.

**Comment by snipper12343** [comment]
Yes :/

**Comment by Moonage62** [comment]
This is just a guess, but I'm betting your anti-virus is killing it when it tries to run.  Be sure to run it as admin.  Probably need to add that entire directory to whatever anti-virus you're using.

**Comment by snipper12343** [comment]
Thanks, I will try that. Before you had replied I had followed John78180's suggestion of uninstalling KB4532693 - waiting for the darn thing to reboot now. I'll advise once I try again without the anti-virus running. Cheers

**Comment by Moonage62** [comment]
You can do that or use a previous termsrv.dll and replace the new one with it.
[termsrv 15063.zip](https://github.com/stascorp/rdpwrap/files/4219942/termsrv.15063.zip)

**Comment by snipper12343** [comment]
Where would I paste that file?

**Comment by snipper12343** [comment]
keep running into windows security problems with replacing the file - it just won't let me replace it.

**Comment by snipper12343** [comment]
I was able to get it working in the end - I followed this post and updated the ini file:

https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini

thanks for all your help Moonage62!

**Comment by saadalvi92** [comment]
tried everything new ini file but the listener is not qorking but now it shows fully supported

**Comment by Moonage62** [comment]
Make sure your antivirus isn't blocking it.  Try re--downloading it and installing.  There's not a whole lot you can do with it.

**Comment by saadalvi92** [comment]
https://github.com/stascorp/rdpwrap/issues/999#issuecomment-586757085




i was using x64 bit windows 10 home edition but this x86 solution worked for me. everything is now in working condition.

**Comment by snipper12343** [comment]
New development - listener state is running and fully supported but only one concurrent session allowed. Not sure why this is happening 
any ideas? 
![Capture](https://user-images.githubusercontent.com/46729949/74945673-23f35100-53c6-11ea-9d87-2c3841b6749a.PNG)

**Comment by Moonage62** [comment]
I use Network level authorization, disable shadowing, and port 3389.

**Comment by snipper12343** [comment]
thanks moonage

**Comment by cpu4u** [comment]
Works fine,thx Nikon-ssg! win10 64 pro,with newest Updates today!

**Comment by cpu4u** [comment]
thx also to Moonage62 :-)

**Comment by Avdey87** [comment]
It doesn't work

**Comment by Avdey87** [comment]
![image](https://user-images.githubusercontent.com/14871952/77943390-cfe16380-72c5-11ea-8de8-644c0929fed0.png)

**Comment by Moonage62** [comment]
Hey avdey87, try this one
[rdpwrapper_updater.zip](https://github.com/stascorp/rdpwrap/files/4404536/rdpwrapper_updater.zip)
The key is to have an ini entry that matches the version you're having issues with.

**Comment by Avdey87** [comment]
![image](https://user-images.githubusercontent.com/14871952/77945089-c1487b80-72c8-11ea-9733-196c6a4c60da.png)

It doesn't work

**Comment by Avdey87** [comment]
M yOS

**Comment by Avdey87** [comment]
![image](https://user-images.githubusercontent.com/14871952/77945570-86931300-72c9-11ea-835c-2358a0f02840.png)

**Comment by Moonage62** [comment]
> ![image](https://user-images.githubusercontent.com/14871952/77945089-c1487b80-72c8-11ea-9733-196c6a4c60da.png)
> 
> It doesn't work

Make sure it's in the \program files\rdpwrap directory and run as administrator, then reboot.

**Comment by Avdey87** [comment]
![image](https://user-images.githubusercontent.com/14871952/77946029-4c764100-72ca-11ea-9b9c-8072914afee8.png)

**Comment by Avdey87** [comment]
![image](https://user-images.githubusercontent.com/14871952/77946070-69ab0f80-72ca-11ea-9194-ebcaed8ca6a8.png)

**Comment by Moonage62** [comment]
Be sure and reboot.

**Comment by Avdey87** [comment]
Yes, twice

**Comment by Avdey87** [comment]
I've downloaded  https://github.com/stascorp/rdpwrap/releases/tag/v1.6.2

**Comment by Moonage62** [comment]
All I can think of is make sure you've got remote assistance and allow remote connections turned on with a user in your Windows.  Can also try uninstalling RDPWrapper and re-installing.  I've not had any issues with that version of termsrv.dll

**Comment by Avdey87** [comment]
![image](https://user-images.githubusercontent.com/14871952/77948673-703b8600-72ce-11ea-946c-c451ec3a2d48.png)
I tryed to reinstall, but it didn't help

**Comment by Moonage62** [comment]
The version has changed after the re-install.  Run the updater again and reboot.  This also requires the original windows termsrv as well.  Otherwise it should work fine.

**Comment by Nikon-ssg** [comment]
Also you can check your .ini file.

On the bottom there should be a line with the current windows version:
[10.0.18362.720]

**Comment by Avdey87** [comment]
After reinstalling, I can see that.
![image](https://user-images.githubusercontent.com/14871952/77951909-78e28b00-72d3-11ea-90b9-cf39636d22c6.png)

**Comment by Avdey87** [comment]
I installed RDPConf.exe  with key - i , and right now everything wor. Thank you!

**Comment by dirtyonekenobi1** [comment]
go to 
https://github.com/stascorp/rdpwrap/pull/859
and download autoupdate-v07.09.2019.zip and uzip in in C:\Program Files\RDP Wrapper
Then run Autoupdater.bat with admin rights

**Comment by pelo76** [comment]
Hi, 
rdpwrapper is running an everything is green, but when I open a second session on my mobile device, the first session stops on my laptop automatically.

Any ideas?

<img width="406" alt="Bildschirmfoto 2020-06-21 um 17 06 26" src="https://user-images.githubusercontent.com/43789603/85228080-92323980-b3e1-11ea-8bea-9379a9832ada.png">

**Comment by robbak** [comment]
That is normal if you are connecting using the same user. The local session
is disconnected and connected remotely. When you connect remotely, all the
documents and windows that were open will be open on the remote desktop.

Can you open a new session if you use a different user account when you log
on remotely

**Comment by pelo76** [comment]
Thanks - Robbak... I've installed a second user - now it works...

**Comment by travismailsa** [comment]
Hi, i have managed to get it working on my pc. No problems with windows 2004 update.
On another pc, running Version	10.0.18363 Build 18363 - version exists in ini file - when i rdp in, the rdp session displays over the local session. So the pc sees the remote session. When signing out, it returns to the normal desktop. Why is this?

**Comment by LakhwinderS** [comment]
hi Guys, I'm getting below
![image](https://user-images.githubusercontent.com/32582521/92753904-ad538a80-f3cd-11ea-9f13-d5cd1e4a3bc4.png)
![1](https://user-images.githubusercontent.com/32582521/92753996-cc521c80-f3cd-11ea-90c7-0681430dc151.JPG)

**Comment by affinityv** [comment]
@LakhwinderS  -- it is probably because of Windows Defender or other AV / "Security" product interfering; you need to add an exclusion the RDP Wrapper directory and any directory with related files.  Then, maybe reinstall or if all is good with just doing `RDPWInst.exe -r`, then even better.

**Comment by addrian1** [comment]
![image](https://user-images.githubusercontent.com/18485323/95651658-956a4600-0af4-11eb-9eb6-79bdcdda440e.png)
Hello.
I still have an error after installing rdpwrap_ini_updater.bat. Already tried a complete reinstallation with reboots at different stages. But the problem still doesn't go away. Any ideas?
Windows version: 18363.1110

When installing the update, I get the error:
- startservice error (code 1056)

**Comment by maj0rmil4d** [comment]
@Moonage62 

I have the problem on 10.0.17763.1613 this build . can you please tell what can I do ? 

your updater does not contain this version , can I just add this version by my self ?

EDIT : 

got solved

https://github.com/asmtron/rdpwrap

**Comment by Moonage62** [comment]
There is another updater floating around primarily mentioned with the
latest windows versions that works better.  Just use it ad be sure to run
it in administrator mode.

**Comment by Inewcoming** [comment]
@Moonage62 Thanks！I come with the same problem. I could login first time, but when I rebooted my win10, an error occurred, "user name or password does not work". I update the .ini file. It works. To use the update tool, you should put it in the directory which contains RDPWInst.exe and rapwrap.ini file.
[rdpwrapper_updater.zip](https://github.com/stascorp/rdpwrap/files/7116750/rdpwrapper_updater.zip)

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/983
