### ISSUE TITLE
termsrv.dll not supported on Windows 10 1903 Build 18362.657

### ISSUE THREAD

**Issue by TheMargarineMan** [stascorp/rdpwrap#997]
The Installer said that the dll I have is not supported by RDP and it told me to run the update batch file. I did and it did nothing so here I am. Here's the file as a txt file
[termsrv.txt](https://github.com/stascorp/rdpwrap/files/4208831/termsrv.txt)

**Comment by sawwd** [comment]
@TheMargarineMan check here https://github.com/stascorp/rdpwrap/issues/999

**Comment by sebaxakerhtc** [comment]
Duplicate of https://github.com/stascorp/rdpwrap/issues/983
