### ISSUE TITLE
Win 8.1 listener state not listening [not supported]

### ISSUE THREAD

**Issue by EliezerBee** [stascorp/rdpwrap#998]
After the most recent updates:

![image](https://user-images.githubusercontent.com/5578694/74599495-953ea700-5048-11ea-94a6-fd29841cb635.png)

I'm seeing not supported:

![image](https://user-images.githubusercontent.com/5578694/74599505-bd2e0a80-5048-11ea-89f4-373d282d9aa1.png)

Please help...
Thank you!

**Comment by 0xdjango** [comment]
You can run update.bat to solve the issue. ( you should be connected to the Internet.)

**Comment by EliezerBee** [comment]
I tried that before but just did it again.

> [*] Checking for updates...
> [*] Current update date: 2018.10.10
> [*] Latest update date:  2018.10.10
> [*] Everything is up to date.

It still doesn't work.

**Comment by affinityv** [comment]
The easiest thing to do is this:
- Download this [ini](https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini) file
- Copy it over the top of "C:\Program Files\RDP Wrapper\rdpwrap.ini"
- Find your copy of RDPWInst.exe and run it via cmd.exe as follows:
`RDPWInst -r`

If you are remotely connected, then It will disconnect your session, so connect again and you should be right.

Find your copy of RDPConf.exe and run it, it should show as all good; if it's running already, close it first as it won't have up to date status.

**DO NOT RUN update.bat as it will only be able to get the ini file from the project and that one isn't fully up to date (it was last updated 16 months ago!)**

**Comment by EliezerBee** [comment]
Thank you! 

Although things now look good here:

![image](https://user-images.githubusercontent.com/5578694/74607892-3c036180-50a2-11ea-8306-d3e2e7584a3d.png)

It doesn't actually seem to work:

![image](https://user-images.githubusercontent.com/5578694/74607885-2d1caf00-50a2-11ea-9e67-71f9d62eab7f.png)

**Comment by affinityv** [comment]
gpedit.msc -- [see section 8) at this link](https://www.trustedtechteam.com/pages/remote-desktop-group-policy-configuration-guide)

**Comment by EliezerBee** [comment]
Not quite... :(

In GP Editor, I don't have the **Policies** node:

Computer Configuration\Policies\Administrative Templates\Windows Components\Remote Desktop Services\Remote Desktop Session Host\Licensing

but I went to this:

Computer Configuration\Administrative Templates\Windows Components\Remote Desktop Services\Remote Desktop Session Host\Licensing

I did go ahead and change the "Set the Remote Desktop licensing mode" to "Per Device" 

And I also set "Limit number of connections" to "999999" and I set the "License servers to use" as the IP address as shown in ipconfig under "IPv4 Address". (I don't have Server Manager being that I'm running 8.1 Pro, not a server version of Windows. _(Is that the problem?...)_

Similarly, in Reg Edit, I don't exactly have this:

HKEY_LOCAL_**SYSTEM**\SYSTEM\CurrentControlSet\Control\Terminal Server\RCM\GracePeriod

This is what I see:

![image](https://user-images.githubusercontent.com/5578694/74611595-e2f7f580-50c2-11ea-9e58-e5fc256f296f.png)

So this is the closest I can get:
HKEY_LOCAL_**MACHINE**\SYSTEM\CurrentControlSet\Control\Terminal Server\RCM
(no HKEY_LOCAL_**SYSTEM** and no **GracePeriod** nodes)

![image](https://user-images.githubusercontent.com/5578694/74611645-539f1200-50c3-11ea-9557-63f76542e1e9.png)

Now what? :((((

**Comment by affinityv** [comment]
Did you restart RDP with `RDPWInst -r` ?

And if that isn't enough, restart the machine to make sure the GPEDIT changes are active....

**Comment by affinityv** [comment]
Sorry, I should have found a simpler reference without GPO, but at least you got the idea.

**Comment by EliezerBee** [comment]
I tried both `RDPWInst -r` and restarting the computer but neither worked. I still get this:

![image](https://user-images.githubusercontent.com/5578694/74613245-2f96fd00-50d2-11ea-9f46-0ef0efcdb85d.png)

When I run `RDPWInst -r` I see this:

![image](https://user-images.githubusercontent.com/5578694/74613294-93b9c100-50d2-11ea-9343-46ef653b8cb1.png)

This is a **big** problem for me... I sincerely appreciate all of your help... Thank you!

**Comment by EliezerBee** [comment]
Should I undo the changes I made above to the Registry and GP?

What else might work? This didn't affect anyone else in this same way?

**Comment by bjgo** [comment]
> Thank you!
> 
> Although things now look good here:
> 
> ![image](https://user-images.githubusercontent.com/5578694/74607892-3c036180-50a2-11ea-8306-d3e2e7584a3d.png)
> 
> It doesn't actually seem to work:
> 
> ![image](https://user-images.githubusercontent.com/5578694/74607885-2d1caf00-50a2-11ea-9e67-71f9d62eab7f.png)

add an empty line at the end of the ini file

**Comment by affinityv** [comment]
If the ini file I referenced above was used, then it has the empty line at the end.
Anybody else got any ideas?

**Comment by EliezerBee** [comment]
Affinityv is completely correct:
> If the ini file I referenced above was used, then it has the empty line at the end.
> Anybody else got any ideas?

Just to start fresh, I rolled-back to a (Windows not data disk) backup from Feb. 7. I updated the RDPWrapper including using the INI file from @affinityv.

When I ran `RDPWInst -r`, I saw this error:

![image](https://user-images.githubusercontent.com/5578694/74675411-1f862880-5179-11ea-8b4a-9d3e9d7ab102.png)

I found that @binarymaster [wrote](https://github.com/stascorp/rdpwrap/issues/159#issuecomment-247986490) it's not an issue and it should be ignored.

So although I now see this:

![image](https://user-images.githubusercontent.com/5578694/74675186-a4247700-5178-11ea-8609-4f4ca3313524.png)

it still only lets me connect one user at a time...

**Comment by EliezerBee** [comment]
Any suggestions please?...

**Comment by EliezerBee** [comment]
So if RDPWrapper looks like it's configured correctly, what other (native Windows?) settings are there I should check? I double checked and see that RDP connections are enabled:

![image](https://user-images.githubusercontent.com/5578694/74743564-3cc50080-5226-11ea-90d3-d758533a6b32.png)

In Windows Firewall:

![image](https://user-images.githubusercontent.com/5578694/74744081-34b99080-5227-11ea-89d7-4a7e0e382855.png)

![image](https://user-images.githubusercontent.com/5578694/74744089-3b480800-5227-11ea-87cf-17ce353ebca8.png)

![image](https://user-images.githubusercontent.com/5578694/74744175-63376b80-5227-11ea-8c7a-1327efa8e954.png)

Also, although numerous, **all** these updates that installed yesterday are all MS Office updates (with one Adobe Reader update at the top) - could any of them be the problem?

![image](https://user-images.githubusercontent.com/5578694/74744650-3afc3c80-5228-11ea-9313-1f21ce854882.png)

What else might be amiss?

**Comment by EliezerBee** [comment]
I tried un- and re-installing RDPWrapper. Didn't change anything. Still get:

![image](https://user-images.githubusercontent.com/5578694/74796685-f1930800-528e-11ea-989e-83bcafdc2ad6.png)

Is there _anything_  that's needed to set-up/verify as "prerequisites" for RDPWrapper to work?

**Comment by EliezerBee** [comment]
This is a serious problem for how we use this computer.

I'm guessing this might not be directly a problem with the configuration of RDPWrapper... Can anyone please advise if there is anything I need to set-up/verify as "prerequisites" for RDPWrapper to work?

**Comment by bjgo** [comment]
> If the ini file I referenced above was used, then it has the empty line at the end.
> Anybody else got any ideas?

so open it up and show us.

**Comment by unbrainwasher** [comment]
I experienced the very same problem with Windows 8.1. The machine is listening, but denies more than one RDP-connection. I suspect, Microsoft has just introduced a new method into termsrv.dll to thwart patching.

**Comment by EliezerBee** [comment]
> > If the ini file I referenced above was used, then it has the empty line at the end.
> > Anybody else got any ideas?
> 
> so open it up and show us.

Wow. As silly as it sounds, what @bjgo wrote was the key. There was some corruption of the INI file. It works now.

**Thank you all for your help!!!**

**Comment by affinityv** [comment]
@EliezerBee What and where was the corruption?  Was it in the file you download from my github repo area? If it was, do you know which INI section was the problem?

**Comment by EliezerBee** [comment]
_OK, this is a bit embarrassing..._

I first downloaded the INI file from:
https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini

I then opened it, and saw it looked right. But something still wasn't working. So at a later point, I _once again_ downloaded the INI file, but the second time, I apparently clicked "Save link as" which then saved it as an HTML document. And the DLL didn't exactly know what to make of a bunch of HTML tags...

**Comment by affinityv** [comment]
Okay, thanks @EliezerBee that explains it.  I'll keep adding INI sections when I learn about them; just added one now.

**Comment by ghost** [comment]
it doesn't seem to work anymore again :(

**Comment by affinityv** [comment]
> it doesn't seem to work anymore again :(

Okay, was it working for you recently?  What changed on your system that you know about?
What is the exact version of your termsrv.dll --- both release and whether it is 32 or 64 bit please.  And out of interest alone... just for curiosity, what is the version that WINVER.EXE provides?

**Comment by EliezerBee** [comment]
I'm also having this problem :(((

From WinVer.exe:
Windows 8.1 Pro v6.3 (build 9600)

[image: image.png]


Please, please help...

**Comment by EliezerBee** [comment]
I'm also having this problem now :(((

From WinVer.exe:
Windows 8.1 Pro v6.3 (build 9600)

![image](https://user-images.githubusercontent.com/5578694/141669564-84dc667c-17b9-42c1-8f0b-1e79174e5541.png)

Please, please help...

**Comment by affinityv** [comment]
> Windows 8.1 Pro v6.3 (build 9600)

32 bit or 64 bit Windows?

And you now have the INI from the [raw link](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini)?

**Comment by EliezerBee** [comment]
64 bit
Should I download that INI from the raw link?

**Comment by affinityv** [comment]
> Should I download that INI from the raw link?

Yes, if you want to be sure it is complete and in the correct format.  Save as plain text file.

**Comment by affinityv** [comment]
If that still doesn't work, I would be looking at your AV / Malware products, make sure you have exceptions.  Also make sure that the Windows registry is in tact for RDP.  This reg file in my [repo](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/Windows_10_Pro_64bit_RDS.reg) might help you work that out.

**Comment by affinityv** [comment]
And if all that fails, there might be a difference b/w the termsrv.dll file of Windows 8.1 and Windows Server 2012 R2 ... not sure about that; I expect it should be the same though.

**Comment by EliezerBee** [comment]
@affinityv, thank you for the "raw link" advice. Now I'm here:

![image](https://user-images.githubusercontent.com/5578694/141697657-b7b5e942-4ebd-4fa1-90ae-88b7852cdc24.png)

So there **was** an improvement. But when a second user tries to connect, they're told the other user has to give up their session first.

What's the next logical step?

**Comment by affinityv** [comment]
> What's the next logical step?

As an admin user `RDPWInst.exe -r`

**Comment by EliezerBee** [comment]
Perfect!!! THANK YOU!

**Comment by affinityv** [comment]
> Perfect!!! THANK YOU!

So... all good now, multi users?

**Comment by EliezerBee** [comment]
YES YES YES

**Comment by ClorindaMiranda** [comment]
> > What's the next logical step?
> 
> As an admin user `RDPWInst.exe -r`

I appreciate that. I had the same issue, and I could fix it with your advice. Thanks a million.
